### PR TITLE
fix(controller): add missing workqueue metrics (#16315)

### LINKED ISSUE #12241: ApplicationSet's Work Queue Related Metrics Missing After Upgrade
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We were following the work queue of applicationset controller using the metrics generated by the controller-runtime library. We upgraded our ArgoCD setup from v2.3.12 to v2.5.5 and we observed that metrics related to the work queue are no more generated in /metrics endpoint.

For instance, /metrics endpoint of applicationset controller was returning  `workqueue_depth` metric in v2.3.12. When we upgraded to v2.5.5 it stopped returning  `workqueue_depth` metric.

We suspect that init function located at https://github.com/argoproj/argo-cd/blob/master/controller/metrics/workqueue.go#L70 interfere with the init function located at https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/metrics/workqueue.go#L91-L99. Since it is imported with the following https://github.com/argoproj/argo-cd/blob/master/cmd/main.go#L9 import statement. 

We built a custom image by commenting out init function located at https://github.com/argoproj/argo-cd/blob/master/controller/metrics/workqueue.go#L70. When we deployed it, we again observed the `workqueue_depth` metric from /metrics endpoint of applicationset controller. However, of course, this is not a solution, I guess it just shows the cause of the problem. 

**To Reproduce**

For instance, you can use the following steps to reproduce it,

- Install ArgoCD v2.3.3 using https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.12/manifests/install.yaml
- Enable metrics endpoint of applicationset controller
- Send a request to /metrics endpoint of applicationset controller and observe that work queue related metrics are generated
- Install latest ArgoCD using https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- Send a request to /metrics endpoint of applicationset controller and observe that work queue related metrics are not generated

**Expected behavior**

Being able to monitor all work queue metrics generated by controller-runtime library.

**Version**

```shell
argocd: v2.5.8+bbe870f.dirty
  BuildDate: 2023-01-25T18:33:35Z
  GitCommit: bbe870ff5904dd1cebeba6c5dcb7129ce7c2b5e2
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.5.5+fc3eaec
```

cc: [@ieud](https://github.com/ieud) [@mstfymrtc](https://github.com/mstfymrtc) [@erkanzileli](https://github.com/erkanzileli) [@peacecwz](https://github.com/peacecwz)

### PR DESCRIPTION
**Pull request by agaudreault**
## Description

Closes #12241 #16315

I believe this should be cherry-picked in 2.9 and 2.10 since it seems to be a regression.

My guess is that another package was calling `workqueue.SetProvider()` after the controller/metrics package, overriding the custom config. To not depend on the loading order, I think it is fair to use the default workqueue metrics.

### Impacts

- Uses default bucket for workqueue metrics
- Adds new metrics emitted by the controller-runtime

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by rumstead** [comment]
Does this PR address the metrics on the applicationset controller as well or just the application controller?

**Comment by agaudreault-jive** [comment]
> Does this PR address the metrics on the applicationset controller as well or just the application controller?

@rumstead the applicationset uses the default metrics from the Kubernetes controller so it does not have the issue. 
See https://github.com/agaudreault-jive/argo-cd/blob/8f84ad1b0c0b0216e65e99bf4b7d796f3fef5fdd/cmd/argocd-applicationset-controller/commands/applicationset_controller.go#L118

**Comment by rumstead** [comment]
> > Does this PR address the metrics on the applicationset controller as well or just the application controller?
> 
> @rumstead the applicationset uses the default metrics from the Kubernetes controller so it does not have the issue. See https://github.com/agaudreault-jive/argo-cd/blob/8f84ad1b0c0b0216e65e99bf4b7d796f3fef5fdd/cmd/argocd-applicationset-controller/commands/applicationset_controller.go#L118

Yup understood where the metrics are coming from. Your PR is closing #12241 which is talking about the applicationset missing the metrics and having a similar issue as described for the application controller (I noted on the ticket the applicationset controller has been missing [since 2.4.* ](https://github.com/argoproj/argo-cd/issues/10952#issuecomment-1290780442)). 

It isn't clear to me if this PR restores the missing metrics for the application controller. I suggest we leave the #12241 issue open if it doesn't.

File: controller/metrics/metrics.go [hunk 1]
```diff
@@ -160,12 +162,12 @@ func NewMetricsServer(addr string, appLister applister.ApplicationLister, appFil
...
 	registry := NewAppRegistry(appLister, appFilter, appLabels)
-	registry.MustRegister(depth, adds, latency, workDuration, unfinished, longestRunningProcessor, retries)
+
 	mux.Handle(MetricsPath, promhttp.HandlerFor(prometheus.Gatherers{
 		// contains app controller specific metrics
 		registry,
-		// contains process, golang and controller workqueues metrics
-		prometheus.DefaultGatherer,
+		// contains workqueue metrics, process and golang metrics
+		ctrl_metrics.Registry,
```
Comment (agaudreault-jive) [inline controller/metrics/metrics.go:170]: This adds the rest_client metrics like the following, so far no idea how to unregister them. I think the cardinality of host is high and I feel they might not be necessary (they are also currently present on the applciationset controller when using the default metrics handler for k8s controller)

```
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="0.005"} 0
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="0.025"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="0.1"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="0.25"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="0.5"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="1"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="2"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="4"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="8"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="15"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="30"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="60"} 2
rest_client_request_duration_seconds_bucket{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET",le="+Inf"} 2
rest_client_request_duration_seconds_sum{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET"} 0.023560624000000002
rest_client_request_duration_seconds_count{host="https://dev.argocd.svc:49999/apis/networking.k8s.io/v1?timeout=32s",verb="GET"} 2
```

File: controller/metrics/metrics_test.go [hunk 2]
```diff
@@ -443,3 +445,69 @@ argocd_app_sync_total{dest_server="https://localhost:6443",name="my-app",namespa
...
+	assert.NoError(t, err)
+	rr := httptest.NewRecorder()
+	metricsServ.Handler.ServeHTTP(rr, req)
+	assert.Equal(t, rr.Code, http.StatusOK)
+	body := rr.Body.String()
+	log.Println(body)
+	assertMetricsPrinted(t, expectedMetrics, body)
+}
+
+func TestGoMetrics(t *testing.T) {
```
Comment (agaudreault-jive) [inline controller/metrics/metrics_test.go:484]: Strangely, this test does not work.

If I add the `prometheus.DefaultGatherer`, the metrics are present in the unit test, but when starting the containers, go collectors and go process metrics are registered twice causing failures.

I cannot find yet from which package go/process metrics get registered to the controller-runtime "ctrl_metrics.Registry". If anyone knows, the solution would be to import the package in the unit test so it runs just like in the container.

Comment (agaudreault-jive) [reply controller/metrics/metrics_test.go:492]: Fixed

File: controller/metrics/metrics.go (hunk 1 above)
Comment (sonamkshenoy) [inline controller/metrics/metrics.go:170]: Hey @agaudreault-jive 
I had happened to [work](https://github.com/argoproj/argo-cd/pull/17017) on this issue too and had faced the issue of the Go metrics being registered twice as well :)
So we could probably unregister it first as `metrics.Registry.Unregister(collectors.NewGoCollector())` like [here](https://github.com/argoproj/argo-cd/pull/17017/files#diff-2c2968dfb2d5ad8d8e69946fffc1a6cde0d55d805f9253b0d1a3a6faf1836ad7R168)

Comment (sonamkshenoy) [reply controller/metrics/metrics.go:170]: Yep. It introduces a whole lot of new metrics including cert, rest client and load balancer metrics. Wondering if we should go ahead with this change..?

Comment (agaudreault-jive) [reply controller/metrics/metrics.go:170]: With the current code, metrics are only registered once. 

The problem was to add a reference to the controller in the unit test to have them there as well.

File: controller/metrics/workqueue.go [hunk 3]
```diff
@@ -1,101 +0,0 @@
-package metrics
```
Comment (leoluz) [inline controller/metrics/workqueue.go:1]: Not sure that we should just discontinue this set of metrics. It was previously added to inspect controller metrics and some companies are relying on this set already. Aren't we breaking existing clients going in this direction?

**Review by leoluz — CHANGES_REQUESTED** [review]
This PR is replacing custom Argo CD controller metrics (original PR https://github.com/argoproj/argo-cd/pull/8318) with the ones provided by the `sigs.k8s.io/controller-runtime/pkg/metrics` package. Does this package provides a one-to-one match with the ones provided by Argo CD originally. If so, can you please provide evidence?

File: controller/metrics/metrics.go (hunk 1 above)
Comment (agaudreault) [reply controller/metrics/metrics.go:170]: Fixed by https://github.com/kubernetes-sigs/controller-runtime/pull/2299. Bumping to https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.14.7

File: controller/metrics/workqueue.go (hunk 3 above)
Comment (agaudreault) [reply controller/metrics/workqueue.go:1]: Metrics comes from https://github.com/kubernetes-sigs/controller-runtime/blob/v0.14.7/pkg/metrics/workqueue.go and have the same name and label set so it will be backward compatible with current metrics

File: controller/metrics/metrics.go [hunk 4]
```diff
@@ -160,12 +162,12 @@ func NewMetricsServer(addr string, appLister applister.ApplicationLister, appFil
...
 	mux := http.NewServeMux()
 	registry := NewAppRegistry(appLister, appFilter, appLabels)
-	registry.MustRegister(depth, adds, latency, workDuration, unfinished, longestRunningProcessor, retries)
+
 	mux.Handle(MetricsPath, promhttp.HandlerFor(prometheus.Gatherers{
 		// contains app controller specific metrics
 		registry,
-		// contains process, golang and controller workqueues metrics
-		prometheus.DefaultGatherer,
+		// contains workqueue metrics, process and golang metrics
```
Comment (leoluz) [inline controller/metrics/metrics.go:169]: We already have process and golang metrics as part of argocd controller metrics. Is this duplicating the metrics?

**Review by leoluz — CHANGES_REQUESTED** [review]
Please double check that we are not duplicating metrics computation by introducing "sigs.k8s.io/controller-runtime/pkg/metrics" in the controller metrics.

File: controller/metrics/metrics.go (hunk 4 above)
Comment (leoluz) [reply controller/metrics/metrics.go:169]: clarified in a call

**Review by leoluz — APPROVED** [review]
LGTM

**Review by gdsoumya — APPROVED** [review]
LGTM! I faced similar issues with the recent argocd versions and was debugging it and came to the same conclusion. Thanks for fixing this!

**Comment by agaudreault** [comment]
After testing to make sure no metrics were lost, these are the added metrics. The new version of controller-runtime fix the cardinality concern of `rest_client`. Other "extra" metrics have low cardinality.

Caveat: sometimes when testing in a local cluster, process metrics like `process_cpu_seconds_total` don't show up in the /metrics endpoint, but when running in live environment they are there, so I assume they are collected properly. 

```
# HELP certwatcher_read_certificate_errors_total Total number of certificate read errors
# TYPE certwatcher_read_certificate_errors_total counter
certwatcher_read_certificate_errors_total
# HELP certwatcher_read_certificate_total Total number of certificate reads
# TYPE certwatcher_read_certificate_total counter
certwatcher_read_certificate_total
# HELP rest_client_requests_total Number of HTTP requests, partitioned by status code, method, and host.
# TYPE rest_client_requests_total counter
rest_client_requests_total{code="200",host="10.43.0.1:443",method="GET"}
rest_client_requests_total{code="200",host="10.43.0.1:443",method="PATCH"}
rest_client_requests_total{code="200",host="dev.argocd.svc:6443",method="GET"}
rest_client_requests_total{code="200",host="production-1.argocd.svc:6443",method="GET"}
rest_client_requests_total{code="200",host="production-2.argocd.svc:6443",method="GET"}
rest_client_requests_total{code="200",host="staging.argocd.svc:6443",method="GET"}
rest_client_requests_total{code="201",host="10.43.0.1:443",method="POST"}
# HELP workqueue_adds_total Total number of adds handled by workqueue
# TYPE workqueue_adds_total counter
workqueue_adds_total{name="app_operation_processing_queue"}
workqueue_adds_total{name="app_reconciliation_queue"}
workqueue_adds_total{name="project_reconciliation_queue"}
# HELP workqueue_depth Current depth of workqueue
# TYPE workqueue_depth gauge
workqueue_depth{name="app_operation_processing_queue"}
workqueue_depth{name="app_reconciliation_queue"}
workqueue_depth{name="project_reconciliation_queue"}
# HELP workqueue_longest_running_processor_seconds How many seconds has the longest running processor for workqueue been running.
# TYPE workqueue_longest_running_processor_seconds gauge
workqueue_longest_running_processor_seconds{name="app_operation_processing_queue"}
workqueue_longest_running_processor_seconds{name="app_reconciliation_queue"}
workqueue_longest_running_processor_seconds{name="project_reconciliation_queue"}
# HELP workqueue_queue_duration_seconds How long in seconds an item stays in workqueue before being requested
# TYPE workqueue_queue_duration_seconds histogram
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="1e-08"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="1e-07"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="1e-06"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="9.999999999999999e-06"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="9.999999999999999e-05"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="0.001"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="0.01"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="0.1"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="1"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="10"}
workqueue_queue_duration_seconds_bucket{name="app_operation_processing_queue",le="+Inf"}
workqueue_queue_duration_seconds_sum{name="app_operation_processing_queue"}
workqueue_queue_duration_seconds_count{name="app_operation_processing_queue"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="1e-08"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="1e-07"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="1e-06"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="9.999999999999999e-06"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="9.999999999999999e-05"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="0.001"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="0.01"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="0.1"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="1"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="10"}
workqueue_queue_duration_seconds_bucket{name="app_reconciliation_queue",le="+Inf"}
workqueue_queue_duration_seconds_sum{name="app_reconciliation_queue"}
workqueue_queue_duration_seconds_count{name="app_reconciliation_queue"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="1e-08"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="1e-07"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="1e-06"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="9.999999999999999e-06"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="9.999999999999999e-05"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="0.001"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="0.01"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="0.1"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="1"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="10"}
workqueue_queue_duration_seconds_bucket{name="project_reconciliation_queue",le="+Inf"}
workqueue_queue_duration_seconds_sum{name="project_reconciliation_queue"}
workqueue_queue_duration_seconds_count{name="project_reconciliation_queue"}
# HELP workqueue_retries_total Total number of retries handled by workqueue
# TYPE workqueue_retries_total counter
workqueue_retries_total{name="app_operation_processing_queue"}
workqueue_retries_total{name="app_reconciliation_queue"}
workqueue_retries_total{name="project_reconciliation_queue"}
# HELP workqueue_unfinished_work_seconds How many seconds of work has been done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases.
# TYPE workqueue_unfinished_work_seconds gauge
workqueue_unfinished_work_seconds{name="app_operation_processing_queue"}
workqueue_unfinished_work_seconds{name="app_reconciliation_queue"}
workqueue_unfinished_work_seconds{name="project_reconciliation_queue"}
# HELP workqueue_work_duration_seconds How long in seconds processing an item from workqueue takes.
# TYPE workqueue_work_duration_seconds histogram
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="1e-08"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="1e-07"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="1e-06"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="9.999999999999999e-06"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="9.999999999999999e-05"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="0.001"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="0.01"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="0.1"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="1"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="10"}
workqueue_work_duration_seconds_bucket{name="app_operation_processing_queue",le="+Inf"}
workqueue_work_duration_seconds_sum{name="app_operation_processing_queue"}
workqueue_work_duration_seconds_count{name="app_operation_processing_queue"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="1e-08"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="1e-07"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="1e-06"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="9.999999999999999e-06"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="9.999999999999999e-05"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="0.001"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="0.01"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="0.1"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="1"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="10"}
workqueue_work_duration_seconds_bucket{name="app_reconciliation_queue",le="+Inf"}
workqueue_work_duration_seconds_sum{name="app_reconciliation_queue"}
workqueue_work_duration_seconds_count{name="app_reconciliation_queue"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="1e-08"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="1e-07"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="1e-06"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="9.999999999999999e-06"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="9.999999999999999e-05"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="0.001"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="0.01"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="0.1"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="1"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="10"}
workqueue_work_duration_seconds_bucket{name="project_reconciliation_queue",le="+Inf"}
workqueue_work_duration_seconds_sum{name="project_reconciliation_queue"}
workqueue_work_duration_seconds_count{name="project_reconciliation_queue"}
```

**Comment by Z3r0Sum** [comment]
@leoluz it doesn't look like this made it into 2.9, was that still the plan?

**Comment by agaudreault** [comment]
> it doesn't look like this made it into 2.9, was that still the plan?

@Z3r0Sum the fix could not be cherry picked because it fails with the kubernetes api updates from v0.24 to v0.26 that happened since 2.9. It is not ideal to change the kubernetes dep versions in a patch, especially that this is mostly fixed upstream and https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.14/go.mod uses 0.26, while 2.9 uses the controller runtime 0.11.

There are no plans to cherry-pick this PR because I don't have enough confidence it wont break 2.9, but another fix could be implemented specifically for 2.9. If you have a cluster running 1.25, you can give a try to this PR.
