### PR TITLE
fix: add CLI client IDs to default OIDC allowed audiences (#12170)

### LINKED ISSUE #12170: Failed to verify token: failed to verify token: oidc: expected audience "argo-cd" got  "argo-cd-cli"
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

With Dex connector configured to use our GHE instance, I am able to login into GUI and SSO login to CLI also looks to be successful but all commands end up with invalid session and failed token validation error.

**Version**

```shell
argocd version
argocd: v2.5.7+e0ee345.dirty
  BuildDate: 2023-01-18T04:28:20Z
  GitCommit: e0ee3458d0921ad636c5977d96873d18590ecf1a
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.5.8+bbe870f
```

**Logs**

```
argocd-dex-server-75d9555bc9-bfbmh dex time="2023-01-27T06:38:05Z" level=info msg="login successful: connector \"github\", username=\"xxxxxx\", preferred_username=\"xxxxxx\", email=\"xxxxxx\", groups=[\"xxxxxx:xxxxxx\"]"
```

```
argocd-server-58f7f86d74-8bbqs argocd-server time="2023-01-27T07:15:21Z" level=warning msg="Failed to verify token: failed to verify token: oidc: expected audience \"argo-cd\" got [\"argo-cd-cli\"]"
```

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Fixes #12170

### CODE REVIEW

**Review by leoluz — APPROVED** [review]
LGTM

File: util/oidc/provider.go [hunk 1]
```diff
@@ -107,6 +107,13 @@ func (p *providerImpl) Verify(tokenString string, argoSettings *settings.ArgoCDS
 		// Token must be verified for at least one allowed audience
 		for _, aud := range allowedAudiences {
 			idToken, err = p.verify(aud, tokenString, false)
+			tokenExpiredError := &gooidc.TokenExpiredError{}
+			if errors.As(err, &tokenExpiredError) {
```
Comment (leoluz) [inline util/oidc/provider.go:111]: in think you could just do:
```golang
if errors.Is(err, gooidc.TokenExpiredError) {
```
and avoid having to declare this additional var: `tokenExpiredError`

Comment (crenshaw-dev) [reply util/oidc/provider.go:111]: Weirdly enough, it requires an instantiated object rather than a type. 🤷‍♂️

Comment (crenshaw-dev) [reply util/oidc/provider.go:111]: Oh! Remembered why we don't do that.

The value of `gooidc.TokenExpiredError` is dynamic:

```go
func (e *TokenExpiredError) Error() string {
	return fmt.Sprintf("oidc: token is expired (Token Expiry: %v)", e.Expiry)
}
```

That type also does not implement `Is`. So `&TokenExpiredError{} != &TokenExpiredError{}` for any two errors where the expiry is not the same.

From docs for `errors.Is`:

```go
// An error is considered to match a target if it is equal to that target or if
// it implements a method Is(error) bool such that Is(target) returns true.
```

`errors.As` works because the concrete type of `TokenExpiredError` is assignable to a `TokenExpiredError`. From the docs for `errors.As`:

```go
// An error matches target if the error's concrete value is assignable to the value
// pointed to by target, or if the error has a method As(interface{}) bool such that
// As(target) returns true. In the latter case, the As method is responsible for
// setting target.
```

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.0-rc6, release-2.5 for 2.5.9, release-2.4 for 2.4.21, and release-2.3 for 2.3.15.
