### PR TITLE
fix(snyk): use version sort #17785

### LINKED ISSUE #17785: Fix Snyk report generation script
The script that generates Snyk reports for the docs doesn't seem to handle versions > 2.9 (probably due to poor version number parsing or sorting somewhere).

We should fix it to handle recent versions.

https://github.com/argoproj/argo-cd/blob/master/hack/snyk-report.sh

### PR DESCRIPTION
**Pull request by rumstead**
Fixes #17785

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by rumstead** [comment]
Dump of the versions that would be scanned and pushed as of today.
```
❯ hack/snyk-report.sh
master v2.11.0-rc1 v2.10.6 v2.9.11 v2.8.15 
```

File: hack/snyk-report.sh [hunk 1]
```diff
@@ -37,8 +37,8 @@ git clone https://github.com/argoproj/argo-cd.git
 cd argo-cd
 git checkout master
 
-minor_version=$(git tag -l | sort -g | tail -n 1 | grep -Eo '[0-9]+\.[0-9]+')
-patch_num=$(git tag -l | grep "v$minor_version." | grep -o "[a-z[:digit:]-]*$" | sort -g | tail -n 1)
```
Comment (rumstead) [inline hack/snyk-report.sh:41]: Both patch sorts don't technically need the version sort but I figured I would update it regardless.

**Review by crenshaw-dev — APPROVED** [review]
Thanks, Ryan!!
