### PR TITLE
fix: controller should refresh app before running sync operation

### LINKED ISSUE #1125: Confusing sequence of events during app creation
Here are the events during an app creation

image

The last series of events show it going from OutOfSync -> Synced twice as well as Missing -> Progressing twice.

I suspect this is happening because we have a second reconciliation happening which is operating on stale app object in the informer. We should see if we can use something like rate limited queue to make sure we are at most operating on an object once per second, which will give time for the informer to catch up to persist updates.

### LINKED ISSUE #5592: level=fatal msg="Operation has completed with phase: Running
Argocd sync action fail with the below error.

Command - argocd app sync test-appplication
Error log - time="2021-02-24T06:46:56Z" level=fatal msg="Operation has completed with phase: Running"

**Version**
Paste the output from `argocd version` here.
argocd: v1.8.1+c2547dc.dirty
  BuildDate: 2020-12-10T04:45:44Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: dirty
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64

**Logs**
```
time="2021-02-24T06:40:31Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:40:31Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=21 fields.level=1 git_ms=6 health_ms=0 live_ms=1 settings_ms=0 sync_ms=0 time_ms=69
time="2021-02-24T06:40:52Z" level=info msg="Refreshing app status (normal refresh requested), level (2)" application=test-application
time="2021-02-24T06:40:52Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:40:52Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:40:52Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:40:52Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:40:52Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:40:52Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=7 version_ms=0
time="2021-02-24T06:40:52Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:40:52Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:40:52Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=32 fields.level=1 git_ms=7 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=86
time="2021-02-24T06:40:53Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=942 unmarshal_ms=942 version_ms=0
time="2021-02-24T06:40:53Z" level=info msg="Skipping auto-sync: application status is Synced" application=test-application
time="2021-02-24T06:40:53Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:40:53Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:40:53Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:40:53Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=7 version_ms=0
time="2021-02-24T06:40:53Z" level=info msg="Update successful" application=test-application
time="2021-02-24T06:40:53Z" level=info msg="Reconciliation completed" application=test-application dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=13 fields.level=2 git_ms=942 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=978
time="2021-02-24T06:40:53Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:40:53Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=20 fields.level=1 git_ms=7 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=40
time="2021-02-24T06:42:00Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:42:00Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:42:00Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:42:00Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:42:00Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:51Z" level=info msg="updated 'test-application' operation (phase: Running)"
time="2021-02-24T06:46:51Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:bbc22125b61e602efb84e9a53a13450eb8789834,Prune:false,DryRun:false,SyncStrategy:&SyncStrategy{Apply:nil,Hook:&SyncStrategyHook{SyncStrategyApply:SyncStrategyApply{Force:false,},},},Resources:[]SyncOperationResource{},Source:nil,Manifests:[],SyncOptions:[CreateNamespace=true],} {admin false} [] {0 nil}}" application=test-application
time="2021-02-24T06:46:51Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:51Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:46:51Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:51Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:51Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=22 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=70
time="2021-02-24T06:46:51Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:51Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:51Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:51Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:51Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:51Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:51Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=21 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=68
time="2021-02-24T06:46:53Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=1414 unmarshal_ms=1414 version_ms=0
time="2021-02-24T06:46:53Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:53Z" level=info msg=Syncing application=test-application skipHooks=false started=false syncId=00022-yxHpZ
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=11 unmarshal_ms=11 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="Skipping auto-sync: another operation is in progress" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Updated sync status: Synced -> OutOfSync" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:54Z" level=info msg="Updated health status: Healthy -> Progressing" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:54Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:54Z" level=info msg="Update successful" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=test-application dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=18 fields.level=1 git_ms=7 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=78
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=19 fields.level=1 git_ms=11 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=75
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=8 unmarshal_ms=8 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="Initiated automated sync to 'e160b33c8e760e85dbedc221938b5d312fe166b1'" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=OperationStarted type=Normal
time="2021-02-24T06:46:54Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:54Z" level=info msg="Initiated automated sync to 'e160b33c8e760e85dbedc221938b5d312fe166b1'" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Updated sync status: Synced -> OutOfSync" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:54Z" level=info msg="Updated health status: Healthy -> Progressing" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:54Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=26 fields.level=1 git_ms=8 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=85
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="Update successful" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=test-application dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=21 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=107
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Update successful" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=23
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="Skipping auto-sync: another operation is in progress" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=19 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=72
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=15 unmarshal_ms=15 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="Update successful" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=test-application dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=15 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=59
time="2021-02-24T06:46:54Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=37 fields.level=1 git_ms=15 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=67
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=24 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=41
time="2021-02-24T06:46:54Z" level=info msg="sync/terminate complete" application=test-application duration=1.355674294s syncId=00022-yxHpZ
time="2021-02-24T06:46:54Z" level=info msg="updated 'test-application' operation (phase: Succeeded)"
time="2021-02-24T06:46:54Z" level=info msg="Sync operation to bbc22125b61e602efb84e9a53a13450eb8789834 succeeded" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=OperationCompleted type=Normal
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=7 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:46:54Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:54Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=19 fields.level=1 git_ms=7 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=63
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=8 unmarshal_ms=8 version_ms=0
time="2021-02-24T06:46:54Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=26 fields.level=1 git_ms=8 health_ms=2 live_ms=0 settings_ms=0 sync_ms=0 time_ms=57
time="2021-02-24T06:46:54Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:54Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:54Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:55Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=21 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=40
time="2021-02-24T06:46:55Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:55Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:46:55Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:55Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=27 fields.level=1 git_ms=7 health_ms=0 live_ms=1 settings_ms=0 sync_ms=0 time_ms=73
time="2021-02-24T06:46:55Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:55Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:55Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=910 unmarshal_ms=910 version_ms=0
time="2021-02-24T06:46:55Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=20 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=38
time="2021-02-24T06:46:55Z" level=info msg="Skipping auto-sync: most recent sync already to bbc22125b61e602efb84e9a53a13450eb8789834" application=test-application
time="2021-02-24T06:46:55Z" level=info msg="Updated health status: Progressing -> Healthy" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:55Z" level=info msg="Update successful" application=test-application
time="2021-02-24T06:46:55Z" level=info msg="Reconciliation completed" application=test-application dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=11 fields.level=2 git_ms=910 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=977
time="2021-02-24T06:46:55Z" level=info msg="Refreshing app status (normal refresh requested), level (2)" application=test-application
time="2021-02-24T06:46:55Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:55Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:46:55Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:55Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=4 version_ms=0
time="2021-02-24T06:46:55Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:55Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=35 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=138
time="2021-02-24T06:46:55Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:55Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:55Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:56Z" level=info msg="updated 'test-application' operation (phase: Running)"
time="2021-02-24T06:46:56Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:bbc22125b61e602efb84e9a53a13450eb8789834,Prune:false,DryRun:false,SyncStrategy:nil,Resources:[]SyncOperationResource{},Source:nil,Manifests:[],SyncOptions:[CreateNamespace=true],} { true} [] {5 nil}}" application=test-application
time="2021-02-24T06:46:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:56Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:46:56Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=7 version_ms=0
time="2021-02-24T06:46:56Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:56Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=20 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=39
time="2021-02-24T06:46:56Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:56Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:56Z" level=info msg=Syncing application=test-application skipHooks=false started=false syncId=00023-BlFyD
time="2021-02-24T06:46:56Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:56Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:56Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=27 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=48
time="2021-02-24T06:46:56Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=914 unmarshal_ms=914 version_ms=0
time="2021-02-24T06:46:56Z" level=error msg="Failed to initiate auto-sync to bbc22125b61e602efb84e9a53a13450eb8789834: rpc error: code = FailedPrecondition desc = another operation is already in progress" application=test-application
time="2021-02-24T06:46:56Z" level=info msg="Updated health status: Progressing -> Healthy" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:56Z" level=info msg="Update successful" application=test-application
time="2021-02-24T06:46:56Z" level=info msg="Reconciliation completed" application=test-application dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=11 fields.level=2 git_ms=914 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=965
time="2021-02-24T06:46:56Z" level=info msg="Refreshing app status (normal refresh requested), level (2)" application=test-application
time="2021-02-24T06:46:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:56Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:46:56Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:57Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:57Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=20 fields.level=1 git_ms=7 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=85
time="2021-02-24T06:46:57Z" level=info msg="sync/terminate complete" application=test-application duration=1.175340765s syncId=00023-BlFyD
time="2021-02-24T06:46:57Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:57Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:57Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:57Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:57Z" level=info msg="updated 'test-application' operation (phase: Succeeded)"
time="2021-02-24T06:46:57Z" level=info msg="Sync operation to bbc22125b61e602efb84e9a53a13450eb8789834 succeeded" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=OperationCompleted type=Normal
time="2021-02-24T06:46:57Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:57Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=20 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=37
time="2021-02-24T06:46:57Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:57Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:57Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:57Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:46:57Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:57Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=18 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=38
time="2021-02-24T06:46:57Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=1035 unmarshal_ms=1035 version_ms=0
time="2021-02-24T06:46:57Z" level=info msg="Skipping auto-sync: another operation is in progress" application=test-application
time="2021-02-24T06:46:57Z" level=info msg="Updated sync status: OutOfSync -> Synced" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:57Z" level=info msg="Updated health status: Healthy -> Progressing" application=test-application dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:57Z" level=info msg="Update successful" application=test-application
time="2021-02-24T06:46:57Z" level=info msg="Reconciliation completed" application=test-application dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=17 fields.level=2 git_ms=1036 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=1098
time="2021-02-24T06:46:57Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=test-application
time="2021-02-24T06:46:57Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:57Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: test-application)" application=test-application
time="2021-02-24T06:46:58Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:58Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:58Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:58Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:46:58Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:46:58Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:46:58Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=19 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=78
time="2021-02-24T06:46:58Z" level=info msg="getRepoObjs stats" application=test-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=890 unmarshal_ms=890 version_ms=0
time="2021-02-24T06:46:58Z" level=info msg="Skipping auto-sync: application status is Synced" application=test-application
time="2021-02-24T06:46:58Z" level=info msg="Update successful" application=test-application
time="2021-02-24T06:46:58Z" level=info msg="Reconciliation completed" application=test-application dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=11 fields.level=2 git_ms=890 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=926
time="2021-02-24T06:46:58Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:46:58Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:46:58Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:46:58Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:46:58Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:46:58Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=27 fields.level=1 git_ms=7 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=47
time="2021-02-24T06:47:07Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:47:07Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:47:07Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:47:07Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:47:07Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:47:07Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:47:08Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:47:08Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:47:08Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:47:08Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:47:08Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:47:08Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:47:08Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:47:08Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:47:08Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:47:08Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=19 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=63
time="2021-02-24T06:47:09Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:47:09Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:47:09Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=6
time="2021-02-24T06:47:09Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:47:09Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:47:09Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:47:09Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:47:09Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:47:09Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=19 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=37
time="2021-02-24T06:47:25Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:47:25Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:47:25Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:47:26Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:47:26Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:47:26Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:47:26Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=9 unmarshal_ms=9 version_ms=0
time="2021-02-24T06:47:26Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:47:26Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:47:26Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=19 fields.level=1 git_ms=9 health_ms=0 live_ms=1 settings_ms=0 sync_ms=0 time_ms=76
time="2021-02-24T06:47:39Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:47:39Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:47:39Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:47:43Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:47:43Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:47:43Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:47:43Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:47:43Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:47:44Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:47:44Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=22 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=66
time="2021-02-24T06:47:54Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:47:54Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:47:54Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:47:55Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:47:55Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:47:55Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:47:55Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:47:55Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:47:55Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:47:55Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=24 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=77
time="2021-02-24T06:48:00Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:48:00Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:48:00Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=
time="2021-02-24T06:48:01Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=21 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=122
time="2021-02-24T06:48:05Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:48:05Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:48:05Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:48:06Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:48:06Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:48:06Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:48:06Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:48:06Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:48:06Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=23 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=48
time="2021-02-24T06:48:07Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:48:07Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:48:07Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:48:07Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:48:07Z" level=info msg="No status changes. Skipping patch" application=xyz
time="2021-02-24T06:48:07Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=19 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=38
time="2021-02-24T06:48:13Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=xxxxx
time="2021-02-24T06:48:13Z" level=info msg="No status changes. Skipping patch" application=xxxxx
time="2021-02-24T06:48:13Z" level=info msg="Reconciliation completed" application=xxxxx dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=xxxxx dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:48:14Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:48:14Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:48:14Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:48:14Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:48:14Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:48:25Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:48:25Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=20 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=63
time="2021-02-24T06:48:44Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:48:44Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:48:44Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:48:45Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:48:45Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:48:45Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:48:45Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=5 unmarshal_ms=5 version_ms=0
time="2021-02-24T06:48:45Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:48:45Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:48:45Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=25 fields.level=1 git_ms=5 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=69
time="2021-02-24T06:48:56Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:48:56Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:48:56Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:48:57Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:48:57Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:48:57Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:48:57Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=7 version_ms=0
time="2021-02-24T06:48:57Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:48:57Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:48:57Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=18 fields.level=1 git_ms=7 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=69
time="2021-02-24T06:49:56Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=xxxxx
time="2021-02-24T06:49:56Z" level=info msg="No status changes. Skipping patch" application=xxxxx
time="2021-02-24T06:49:56Z" level=info msg="Reconciliation completed" application=xxxxx dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=xxxxx dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:49:57Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:49:57Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:49:57Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:49:57Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:49:57Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
time="2021-02-24T06:49:57Z" level=info msg="Update successful" application=xyz
time="2021-02-24T06:49:57Z" level=info msg="Reconciliation completed" application=xyz dedup_ms=0 dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" diff_ms=20 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=69
time="2021-02-24T06:50:05Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=test-application
time="2021-02-24T06:50:05Z" level=info msg="No status changes. Skipping patch" application=test-application
time="2021-02-24T06:50:05Z" level=info msg="Reconciliation completed" application=test-application dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=test-application dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:50:07Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=xxxxx
time="2021-02-24T06:50:07Z" level=info msg="No status changes. Skipping patch" application=xxxxx
time="2021-02-24T06:50:07Z" level=info msg="Reconciliation completed" application=xxxxx dest-name="arn:aws:eks:us-west-2:******:cluster/******" dest-namespace=xxxxx dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" fields.level=0 time_ms=4
time="2021-02-24T06:50:09Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=xyz
time="2021-02-24T06:50:09Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-02-24T06:50:09Z" level=info msg="Comparing app state (cluster: https://******.gr7.us-west-2.eks.amazonaws.com, namespace: argocd)" application=xyz
time="2021-02-24T06:50:09Z" level=info msg="getRepoObjs stats" application=xyz build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=6 version_ms=0
time="2021-02-24T06:50:09Z" level=info msg="Updated health status: Degraded -> Healthy" application=xyz dest-namespace=argocd dest-server="https://******.gr7.us-west-2.eks.amazonaws.com" reason=ResourceUpdated type=Normal
```

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

Closes #5592 
Closes https://github.com/argoproj/argo-cd/issues/1125

### CODE REVIEW

File: controller/appcontroller.go [hunk 1]
```diff
@@ -665,6 +665,17 @@ func (ctrl *ApplicationController) processAppOperationQueueItem() (processNext b
...
+		// If we get here, we are about process an operation but we cannot rely on informer since it might has stale data.
+		// So always retrieve the latest version to ensure it is not stale to avoid unnecessary syncing.
+		freshApp, err := ctrl.applicationClientset.ArgoprojV1alpha1().Applications(ctrl.namespace).Get(context.Background(), app.ObjectMeta.Name, metav1.GetOptions{})
+		if err != nil {
+			log.Errorf("Failed to retrieve latest application state: %v", err)
+			return
+		}
+		app = freshApp
+	}
+
```
Comment (jessesuen) [inline controller/appcontroller.go:678]: minor difference, but I think it might be better to put this at the beginning of processRequestedAppOperation

Comment (jessesuen) [reply controller/appcontroller.go:678]: Actually nvmd. the other code would benefit from a fresh app

**Review by jessesuen — APPROVED** [review]

File: controller/appcontroller.go (hunk 1 above)
Comment (jessesuen) [reply controller/appcontroller.go:678]: Can you add a comment that this code can be deleted after https://github.com/argoproj/argo-cd/issues/6296 is fixed?

Comment (alexmt) [reply controller/appcontroller.go:678]: sure
