### PR TITLE
fix: ArgoCD 2.11 - Loop of PATCH calls to Application objects

### LINKED ISSUE #15126: Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"autoscaling\"
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

We've switched some applications to the new `valuesObject` syntax, and those apps have gotten "stuck". They go into a refreshing status and never finish

**To Reproduce**

Not clear to us how to reproduce. We deleted the entire `.status` of an affected application and it seemed to start working again. Not left it long enough yet to determine if it'll break again

**Expected behavior**

**Screenshots**

**Version**

```shell
argocd-server: v2.8.0+804d4b8
  BuildDate: 2023-08-07T14:25:33Z
  GitCommit: 804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```
{"application":"argocd/istio-gateway-iap","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:10Z"}
{"application":"argocd/istio-gateway-public","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:10Z"}
{"application":"argocd/istio-gateway-vpn","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:25Z"}
{"application":"argocd/istio-gateway-public","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:25Z"}
{"application":"argocd/istio-gateway-vpn","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:39Z"}
{"application":"argocd/istio-gateway-public","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:40Z"}
```

### LINKED ISSUE #18151: ArgoCD 2.11 - Loop of PATCH calls to Application objects
Is it possible that https://github.com/argoproj/argo-cd/pull/18061 has suddenly changed the behavior of the Application Controller so that it isn't  comparing things the same way? We are seeing a massive (relatively speaking) jump in the `PATCH` requests/second that the ArgoCD App controller is making  now across ~10 clusters that we did this upgrade on:

image

I suspect the issue has to do with how the code is comparing the `valueFiles` lists from before and after.. we had some `valueFiles` lists that had duplicate values.. and when we run `kubectl get applications -w -o json | kubectl grep -w`, we see diff's like these:

```
        revision: "794fcbae2671366663e107cd50079c2e96894591"
        source:
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "values.yaml"
              - "values.staging-xx.yaml"
              - "values.staging-xx.yaml"
              - "values/staging/values.yaml"
              - "values/staging/staging-xx/values.yaml"
              - "values/staging/staging-xx/types/values.otherfile.yaml"
              - "values/staging/staging-xx/values.staging-xx.yaml"
-             - 
+             - "values.staging-xx.yaml"
            values: "
cluster:
  accountId: ".."
```

_Originally posted by @diranged in https://github.com/argoproj/argo-cd/issues/18061#issuecomment-2102964797_

### PR DESCRIPTION
**Pull request by alexmt**
Closes https://github.com/argoproj/argo-cd/issues/18151

PR fixes a bug introduced by https://github.com/argoproj/argo-cd/pull/18061 . We were trying to fix https://github.com/argoproj/argo-cd/issues/15126 - error which happened while generating status patch using strategic merge strategy.
We've added `replace` merge strategy to `status.comparedTo` field which apparently does not work as I expected. Instead of generating a patch that replaces `comparedTo` field it just uses new `comparedTo` field value as a patch without trying to merge. As a result, fields under `status. compared` never gets removed, which causes all kinds of issues. For example, if the user switches the app destination from cluster name to cluster server URL, then  `status.comparedTo.destination` ends up having both `name` and `server` fields. Once it happens, the controller will keep continuously reconciling the application because it thinks the destination has changed.

Fix: just don't use a strategic merge patch because controller is the only manager of application status. PR changes controller to generate simple merge patch to update secret. It solves both https://github.com/argoproj/argo-cd/issues/18151 and https://github.com/argoproj/argo-cd/issues/15126 .

### CODE REVIEW

File: controller/appcontroller_test.go [hunk 1]
```diff
@@ -2072,3 +2072,65 @@ func TestAddControllerNamespace(t *testing.T) {
...
+
+	require.NoError(t, err)
+	require.True(t, ok)
+	patchObj := map[string]interface{}{}
+	require.NoError(t, json.Unmarshal(patchData, &patchObj))
+
+	val, has, err := unstructured.NestedFieldNoCopy(patchObj, "sync", "comparedTo", "destination", "server")
+	require.NoError(t, err)
+	require.True(t, has)
+	require.Equal(t, nil, val)
```
Comment (crenshaw-dev) [inline controller/appcontroller_test.go:2135]:
```suggestion
	require.Nil(t, val)
```

**Review by crenshaw-dev — APPROVED** [review]

**Comment by rumstead** [comment]
nice!

**Comment by crenshaw-dev** [comment]
@alexmt mind manually cherry-picking 2.11?

**Comment by alexmt** [comment]
Sure, doing it!

**Comment by daftping** [comment]
since the issue has been introduced in 2.10.10, would it make sense to cherry-pick to 2.10 as well?

**Comment by alexmt** [comment]
Done:
* 2.10: https://github.com/argoproj/argo-cd/pull/19348
* 2.11:  https://github.com/argoproj/argo-cd/pull/19347

**Comment by kencochrane** [comment]
@alexmt thank you for finding and fixing that issue.
