### PR TITLE
fix(util): Fix default key exchange algorthims used for SSH connection to be FIPS compliant

### LINKED ISSUE #24155: repo server panics when using SSH based repo URL in FIPS mode enabled cluster
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

This bug is reproducible in 3.0 and 3.1 versions compiled with go1.24. During the SSH handshake, there is a panic and the repo server pod restarts. This issue happens only when SSH based URL is used. The work around is to switch to an HTTPS based URL.

**To Reproduce**

Add a SSH based repository url with a private key. Check the logs of repo server. You will notice that the repo server has been restarted.

**Expected behavior**

Repo Server must not crash with a panic. The algorithm if not supported in FIPS enviornment as its not FIPS compliant, should be handled gracefully.

**Screenshots**

**Version**
3.0.12

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
2025-08-07T20:00:18.056325712Z panic: curve25519: internal error: scalarBaseMult was not 32 bytes
2025-08-07T20:00:18.056325712Z
2025-08-07T20:00:18.056325712Z goroutine 148 [running]:
2025-08-07T20:00:18.056325712Z [golang.org/x/crypto/curve25519.ScalarBaseMult(0xc001457aa0](http://golang.org/x/crypto/curve25519.ScalarBaseMult(0xc001457aa0), 0xc001457a80)
2025-08-07T20:00:18.056325712Z 	/cachi2/output/deps/gomod/pkg/mod/golang.org/x/crypto@v0.38.0/curve25519/curve25519.go:39 +0x219
2025-08-07T20:00:18.056325712Z [golang.org/x/crypto/ssh.(*curve25519KeyPair).generate(0xc001457a80](http://golang.org/x/crypto/ssh.(*curve25519KeyPair).generate(0xc001457a80), {0xaf96860, 0xaf72af0})
2025-08-07T20:00:18.056325712Z 	/cachi2/output/deps/gomod/pkg/mod/golang.org/x/crypto@v0.38.0/ssh/kex.go:467 +0x110
2025-08-07T20:00:18.056325712Z [golang.org/x/crypto/ssh.(*curve25519sha256).Client(0xe325b60](http://golang.org/x/crypto/ssh.(*curve25519sha256).Client(0xe325b60), {0x7f2df4136218, 0xc0004b6ea0}, {0xaf96860, 0xaf72af0}, 0xc001212a20)
2025-08-07T20:00:18.056325712Z 	/cachi2/output/deps/gomod/pkg/mod/golang.org/x/crypto@v0.38.0/ssh/kex.go:478 +0xa5
2025-08-07T20:00:18.056325712Z [golang.org/x/crypto/ssh.(*handshakeTransport).client(0xc00055f1e0](http://golang.org/x/crypto/ssh.(*handshakeTransport).client(0xc00055f1e0), {0xafb23f8, 0xe325b60}, 0xc001212a20)
2025-08-07T20:00:18.056325712Z 	/cachi2/output/deps/gomod/pkg/mod/golang.org/x/crypto@v0.38.0/ssh/handshake.go:822 +0x11b
2025-08-07T20:00:18.056325712Z [golang.org/x/crypto/ssh.(*handshakeTransport).enterKeyExchange(0xc00055f1e0](http://golang.org/x/crypto/ssh.(*handshakeTransport).enterKeyExchange(0xc00055f1e0), {0xc0011ad800, 0x38f, 0x38f})
2025-08-07T20:00:18.056325712Z 	/cachi2/output/deps/gomod/pkg/mod/golang.org/x/crypto@v0.38.0/ssh/handshake.go:712 +0xa27
2025-08-07T20:00:18.056325712Z [golang.org/x/crypto/ssh.(*handshakeTransport).kexLoop(0xc00055f1e0)](http://golang.org/x/crypto/ssh.(*handshakeTransport).kexLoop(0xc00055f1e0))
2025-08-07T20:00:18.056325712Z 	/cachi2/output/deps/gomod/pkg/mod/golang.org/x/crypto@v0.38.0/ssh/handshake.go:341 +0x3b2
2025-08-07T20:00:18.056325712Z created by [golang.org/x/crypto/ssh.newClientTransport](http://golang.org/x/crypto/ssh.newClientTransport) in goroutine 120
2025-08-07T20:00:18.056325712Z 	/cachi2/output/deps/gomod/pkg/mod/golang.org/x/crypto@v0.38.0/ssh/handshake.go:170 +0x34d
```

### PR DESCRIPTION
**Pull request by anandf**
Fixes https://github.com/argoproj/argo-cd/issues/24155

Needs to be backported to `release-3.0` and `release-3.1` branches which uses `go1.24` or later for compilation.

Argo CD uses hard coded default Key exchange algorithims for SSH. In FIPS enabled cluster, some of these algorithim is not supported. When one such algorithm is used (curve25519), the repo server fails to connect to the SSH host and crashes with a panic. `panic: curve25519: internal error: scalarBaseMult was not 32 bytes`

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: util/git/ssh.go [hunk 1]
```diff
@@ -51,9 +58,19 @@ func (a *PublicKeysWithOptions) ClientConfig() (*ssh.ClientConfig, error) {
...
 	return a.SetHostKeyCallback(opts)
 }
+
+// getDefaultSSHKeyExchangeAlgorithms returns the default key exchange algorithms to be used
+func getDefaultSSHKeyExchangeAlgorithms() []string {
+	if fips140.Enabled() {
+		log.Info("loading fips140 compliant default key exchange algorithms")
+		return SupportedFIPSCompliantSSHKeyExchangeAlgorithms
+	}
+	log.Info("loading default key exchange algorithms")
```
Comment (jannfis) [inline util/git/ssh.go]: I think these logs could get spammy in the end. If we need to print logs about FIPS, we should print them at the start of the repo server imho.

**Review by jannfis — APPROVED** [review]
LGTM, thanks

File: util/git/ssh.go (hunk 1 above)
Comment (anandf) [reply util/git/ssh.go]: Removed these log lines and rebased the code.

**Comment by blakepettersson** [comment]
@anandf can you open cherry-pick PRs for 3.0 and 3.1?
