### PR TITLE
fix: update Jsonnet field tag to avoid `jsonnet: {}` in manifests

### LINKED ISSUE #25485: Using "directory recurse" force jsonnet builtin tool, preventing plugin to be called
argo-cd version: v3.2.1+8c4ab63

When creating an application for a directory containing yaml files, if we select: "Directory Recurse", we see that in the application spec:
```
  source:
    directory:
      jsonnet: {}
      recurse: true
```
Although there is no jsonnet file, argo-cd will use builtin jsonnet tool, preventing my plugin to be called.
If I do not select "directory recurse", I have no more directory section in source and the plugin is correctly called.
Same if I remove the directory section of the spec of the application: the plugin is now called correctly.

I have tried to disable jsonnet builtin tool as explained here: https://argo-cd.readthedocs.io/en/latest/user-guide/tool_detection/#disable-built-in-tools
but same behavior.

### PR DESCRIPTION
**Pull request by 1Shubham7**
"Directory Recurse" option currently causes `jsonnet: {}` to be present in the app manifest, which seemingly triggers Jsonnet tool detection even when irrelevant. Problem is Jsonnet field in `ApplicationSourceDirectory` is a value type, so omitempty does not prevent it from appearing as an empty object in json.

so I  changed  Jsonnet to a pointer *ApplicationSourceJsonnet. and reflected those changes in other funcs and tests.

closes https://github.com/argoproj/argo-cd/issues/25485

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by agaudreault — APPROVED** [review]

**Comment by 1Shubham7** [comment]
image
my code editor taking ages to render such large file :laughing:

**Comment by crenshaw-dev** [comment]
> omitempty does not prevent it from appearing as an empty object in json

Might the new `omitzero` work?

**Comment by 1Shubham7** [comment]
ok, so my suspison was right! these tests kept on failing - reason is my changes to `generated.pb.go` made protobuf serialization faster by skipping nil Jsonnet pointers. hence controller process now syncs faster, consistently winning "the race" with cm. before the cm update could propagate.

so I have just reordered TestSyncWithNoDestinationServiceAccountsInProject just like other tests : )

**Comment by 1Shubham7** [comment]
> > omitempty does not prevent it from appearing as an empty object in json
> 
> Might the new `omitzero` work?

hmm, interesting take @crenshaw-dev! I dont think we should do that. we can have omitzero but then at Protobuf generator, it will marshal empty structs as {} and we will have to handle that case. right now we can just do `if m.Jsonnet != nil` .  I dont think we can verify the `omitzero` tag directly in protobuf . otherwise it's just more complex code to check for the emptiness of the struct

what say ?

**Comment by crenshaw-dev** [comment]
If jsonnet tool detection today relies only on the directory.jsonnet field being non-nil, then it's unclear how non-jsonnet directory manifest generation _ever_ works today. I'll look at the code more, but I don't think it can be possible that adding the pointer type is the only way to prevent jsonnet from being incorrectly invoked.

**Comment by crenshaw-dev** [comment]
I'm concerned that requiring a non-nil jsonnet field for jsonnet to be used may be a breaking change in scenarios where the need to invoke jsonnet was previously inferred.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Requesting changes, because I can't reproduce the issue, and I'm worried this might be a breaking change. https://github.com/argoproj/argo-cd/issues/25485#issuecomment-3646926065

**Review by nitishfy — COMMENTED** [review]
I'm interested in this problem statement and would like to take this PR for reviews. I agree with Michael that if the jsonnet field is going to be a required field, this is definitely going to be a breaking change and would require more thoughts about it. I've not reproduced the issue locally yet but will do that and review this PR. Also, I think this will also require adding additional tests.

**Comment by crenshaw-dev** [comment]
I think the original issue reporter simply misunderstood how the `directory` block affected their CMP.

I do think that `jsonnet: {}` is odd, but I think the fix there is simply to set omitzero on that field.

**Comment by crenshaw-dev** [comment]
Confirmed locally that omitzero removes the dangling field. So this PR can be a single-line PR. :-)

**Comment by 1Shubham7** [comment]
> Confirmed locally that omitzero removes the dangling field. So this PR can be a single-line PR. :-)

great then, making the change.

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -894,7 +894,7 @@ type ApplicationSourceDirectory struct {
 	// Recurse specifies whether to scan a directory recursively for manifests
 	Recurse bool `json:"recurse,omitempty" protobuf:"bytes,1,opt,name=recurse"`
 	// Jsonnet holds options specific to Jsonnet
-	Jsonnet ApplicationSourceJsonnet `json:"jsonnet,omitempty" protobuf:"bytes,2,opt,name=jsonnet"`
+	Jsonnet ApplicationSourceJsonnet `json:"jsonnet,omitzero" protobuf:"bytes,2,opt,name=jsonnet"`
```
Comment (nitishfy) [inline pkg/apis/application/v1alpha1/types.go]: one last thing to do - Please add a comment on line 896 on why are we using the omitzero instead of omitempty.

**Review by nitishfy — COMMENTED** [review]
Left a small comment otherwise LGTM! You'll also have to make sure the codegen check passes - `make codegen-local`.

File: pkg/apis/application/v1alpha1/types.go [hunk 2]
```diff
@@ -894,7 +894,10 @@ type ApplicationSourceDirectory struct {
 	// Recurse specifies whether to scan a directory recursively for manifests
 	Recurse bool `json:"recurse,omitempty" protobuf:"bytes,1,opt,name=recurse"`
 	// Jsonnet holds options specific to Jsonnet
-	Jsonnet ApplicationSourceJsonnet `json:"jsonnet,omitempty" protobuf:"bytes,2,opt,name=jsonnet"`
+	// Note: omitzero is used to prevent the field from being marshaled when it is empty.
+	// This prevents "jsonnet: {}" from appearing in manifests when Jsonnet options are not explicitly defined.
+	// +optional
```
Comment (nitishfy) [inline pkg/apis/application/v1alpha1/types.go]:
```suggestion
	// +optional
```
do we need this?

**Comment by nitishfy** [comment]
The tests are failing, can you fix them please?

File: pkg/apis/application/v1alpha1/types.go (hunk 2 above)
Comment (1Shubham7) [reply pkg/apis/application/v1alpha1/types.go]: yup, otherwise code gen would count that as required field in schema 

Screenshot from 2025-12-13 11-07-02

**Comment by 1Shubham7** [comment]
> The tests are failing, can you fix them please?

yup yup, I am on it. issue looks like is with the tests itself, I am seeing other people also suffering with this - https://cloud-native.slack.com/archives/C020XM04CUW/p1765521644971889

File: pkg/apis/application/v1alpha1/types.go (hunk 2 above)
Comment (nitishfy) [reply pkg/apis/application/v1alpha1/types.go]: i get that. I'm wondering why the other fields like recurse not being shown as required since they don't have an optional marker added to them.

Comment (nitishfy) [reply pkg/apis/application/v1alpha1/types.go]: maybe because of `omitempty`?

Comment (1Shubham7) [reply pkg/apis/application/v1alpha1/types.go]: exactly, generator understands `omitempty` and makes that field optional, but apparently its not understanding/doing the same for `omitzero` so I had to add it (like its used multiple times in that file).

Comment (crenshaw-dev) [reply pkg/apis/application/v1alpha1/types.go]: I think you can specify both omitzero and omitempty. At least that's what I tested locally

Comment (1Shubham7) [reply pkg/apis/application/v1alpha1/types.go]: hmm, ok, doing that

Comment (1Shubham7) [reply pkg/apis/application/v1alpha1/types.go]: PTAL now @crenshaw-dev :)

**Comment by 1Shubham7** [comment]
PTAL now @nitishfy @crenshaw-dev

File: pkg/apis/application/v1alpha1/types.go [hunk 3]
```diff
@@ -894,7 +894,9 @@ type ApplicationSourceDirectory struct {
 	// Recurse specifies whether to scan a directory recursively for manifests
 	Recurse bool `json:"recurse,omitempty" protobuf:"bytes,1,opt,name=recurse"`
 	// Jsonnet holds options specific to Jsonnet
-	Jsonnet ApplicationSourceJsonnet `json:"jsonnet,omitempty" protobuf:"bytes,2,opt,name=jsonnet"`
+	// Note: omitzero is used to prevent the field from being marshaled when it is empty.
```
Comment (crenshaw-dev) [inline pkg/apis/application/v1alpha1/types.go]: Can we drop the two new docs lines? They're helpful for someone reading the code, but they also end up in stuff like swagger docs and kubectl describe output, where they'll probably be more confusing than helpful

**Review by crenshaw-dev — APPROVED** [review]

**Comment by 1Shubham7** [comment]
can we merge this now @nitishfy @agaudreault @crenshaw-dev  ?

**Review by nitishfy — APPROVED** [review]
