### PR TITLE
fix: traverse generator tree when getting requeue time (#12407)

### LINKED ISSUE #12407: ApplicationSet controller sets requeueAfter to 0 when using cluster and nested generators
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ApplicationSets are not being queued.

There is quite a bit of waterfall logic to get the requeue time but I am seeing this [line](https://github.com/argoproj/argo-cd/blob/d311fad538178ef97528edf7f09d1d5b57268f45/applicationset/controllers/applicationset_controller.go#L230) log a time of 0 for both 2.4.14 and 2.5.10. I am not sure why the reconciliation time is much worse on 2.5.10 yet. The controller is saying 0 [here](https://github.com/argoproj/argo-cd/blob/v2.5.10/applicationset/controllers/applicationset_controller.go#L247). You can see in the controller runtime that 0 means never requeue, or at least [their docs state that](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.11.0/pkg/reconcile/reconcile.go#L31).

Reproduced on HEAD as well. 

**To Reproduce**

Here are unit tests that reproduce the issue. 

https://github.com/rumstead/argo-cd/commit/11146a9b45e464d753ae1b0e8266db244f35fb18#diff-1bc0b86ed20d2c14e5c2d4efb5deed697369c8ed49fe91a2c84fcb48c412739d

**Expected behavior**

ApplicationSets are requeued with the default time of `3m` regardless of their generators. 

**Screenshots**

**Version**
2.4.14 and 2.5.10

**Logs**

2.4.10
```
time="2023-02-09T22:35:54Z" level=info msg="end reconcile" requeueAfter=0s
```
2.5.10
```
time="2023-02-09T18:59:44Z" level=info msg="end reconcile" applicationset=argocd/prometheus-appset requeueAfter=0s
```

### PR DESCRIPTION
**Pull request by rumstead**
Fixes #12407

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

```appset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys: ["name"]
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - matrix:
              generators:
                - clusters:
                    selector:
                      matchLabels:
                        argocd.argoproj.io/secret-type: cluster
                      matchExpressions:
                        - key: kubernetes.cnp.io/environment
                          operator: In
                          values: ["dev"]
                - git:
                    repoURL: https://github.com/rumstead/argocd-playground.git
                    revision: HEAD
                    files:
                    - path: "manifests/appset/config.yaml"
  template:
    metadata:
      name: 'test-{{name}}'
    spec:
      project: default
      source:
        path: guestbook
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: '{{app.version}}'
      destination:
        namespace: default
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
```

Before changes:
```
time="2023-02-13T19:33:45Z" level=info msg="created Application" app=test-dev appSet=test-appset
time="2023-02-13T19:33:45Z" level=info msg="created Application" app=test-admin appSet=test-appset
time="2023-02-13T19:33:45Z" level=info msg="end reconcile" applicationset=argocd/test-appset requeueAfter=0s
< ...changes in git never picked up... >
```
This means if I update any GIT config.yaml the applicationset controller never reconciles any changes. The application controller does poke the argo cd applications which the application set resources "own". It "looks like" the applicationsets are being reconciled because argo cd updates the `reconciledAt` on the application CR. Depending on your application controller reconciliation time, it could be too long. 

After changes:
```
time="2023-02-13T20:30:50Z" level=info msg="unchanged Application" app=test-dev appSet=test-appset
time="2023-02-13T20:30:50Z" level=info msg="unchanged Application" app=test-admin appSet=test-appset
time="2023-02-13T20:30:50Z" level=info msg="end reconcile" applicationset=argocd/test-appset requeueAfter=3m0s
< ...changes made in git... >
time="2023-02-13T20:33:52Z" level=info msg="unchanged Application" app=test-admin appSet=test-appset
time="2023-02-13T20:33:52Z" level=info msg="unchanged Application" app=test-dev appSet=test-appset
time="2023-02-13T20:33:52Z" level=info msg="end reconcile" applicationset=argocd/test-appset requeueAfter=3m0s
< ...changes in git picked up... >
```

### CODE REVIEW

**Comment by ishitasequeira** [comment]
@rumstead can you add an example test case to the description of the PR for testing?

File: applicationset/controllers/requeue_after_test.go [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+						},
+					}},
+				},
+			},
+		}}, want: generators.DefaultRequeueAfterSeconds, wantErr: assert.NoError},
+		{name: "ListGenerator", args: args{appset: &argov1alpha1.ApplicationSet{
+			Spec: argov1alpha1.ApplicationSetSpec{
+				Generators: []argov1alpha1.ApplicationSetGenerator{{List: &argov1alpha1.ListGenerator{}}},
+			},
+		}}, want: generators.NoRequeueAfter, wantErr: assert.NoError},
```
Comment (rumstead) [inline applicationset/controllers/requeue_after_test.go:147]: It is not clear to me why we wouldn't want to reconcile list generators.

**Comment by rumstead** [comment]
> @rumstead can you add an example test case to the description of the PR for testing?
Is that what you are looking for?

File: applicationset/controllers/requeue_after_test.go (hunk 1 above)
Comment (rumstead) [inline applicationset/controllers/requeue_after_test.go:147]: It isn't clear to me why we wouldn't want to requeue a `List` generator.

**Comment by ishitasequeira** [comment]
> > @rumstead can you add an example test case to the description of the PR for testing?
> 
> Is that what you are looking for?

Yes. Thanks. I will test the PR out soon.

File: applicationset/generators/merge.go [hunk 2]
```diff
@@ -221,6 +224,28 @@ func (m *MergeGenerator) GetRequeueAfter(appSetGenerator *argoprojiov1alpha1.App
...
+	if r.Matrix == nil {
+		return nil
+	}
+	matrix, err := argoprojiov1alpha1.ToNestedMatrixGenerator(r.Matrix)
+	if err != nil {
+		return nil
+	}
+	return matrix.ToMatrixGenerator()
+}
+
```
Comment (ishitasequeira) [inline applicationset/generators/merge.go:248]: Now that we have created this new functions, can we remove the duplicate code and call this functions there?
Places I saw similar code [here](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/merge.go#L142-L161) and [here](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/matrix.go#L83-L105).

File: applicationset/controllers/requeue_after_test.go (hunk 1 above)
Comment (ishitasequeira) [reply applicationset/controllers/requeue_after_test.go:147]: I am not aware the reason behind not requeuing List Generator, but I can see that there is not much implementation of [GetRequeueAfter](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/list.go#L21) function.

Maybe @crenshaw-dev can shed more light on this.

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
Overall PR looks good to me. I just have some code redundancy suggestions.

**Comment by rumstead** [comment]
> Overall PR looks good to me. I just have some code redundancy suggestions.

Updated.

**Comment by rumstead** [comment]
@ishitasequeira what are the next steps in your opinion?

**Review by ishitasequeira — APPROVED** [review]
Thanks @rumstead. Apologies for taking time to get back to this.
The PR LGTM. @crenshaw-dev could you take 1 more look and help merge this?

File: .gitignore [hunk 3]
```diff
@@ -24,3 +24,4 @@ cmd/argocd/argocd
 cmd/argocd-application-controller/argocd-application-controller
 cmd/argocd-repo-server/argocd-repo-server
 cmd/argocd-server/argocd-server
+/Docker.company
```
[the remark this answers is not in the document]
Comment (rumstead) [reply .gitignore:27]: nope oops

File: applicationset/controllers/requeue_after_test.go [hunk 4]
```diff
@@ -0,0 +1,181 @@
...
+)
+
+func TestRequeueAfter(t *testing.T) {
+	mockServer := argoCDServiceMock{}
+	ctx := context.Background()
+	scheme := runtime.NewScheme()
+	err := argov1alpha1.AddToScheme(scheme)
+	assert.Nil(t, err)
+	err = argov1alpha1.AddToScheme(scheme)
+	assert.Nil(t, err)
```
Comment (crenshaw-dev) [inline applicationset/controllers/requeue_after_test.go:29]: Duplicate call?

File: applicationset/controllers/requeue_after_test.go (hunk 1 above)
Comment (crenshaw-dev) [reply applicationset/controllers/requeue_after_test.go:147]: If you're using a static List generator, the output should never change.

File: applicationset/generators/merge.go [hunk 5]
```diff
@@ -221,6 +201,28 @@ func (m *MergeGenerator) GetRequeueAfter(appSetGenerator *argoprojiov1alpha1.App
 
 }
 
+func getMergeGenerator(r argoprojiov1alpha1.ApplicationSetNestedGenerator) *argoprojiov1alpha1.MergeGenerator {
+	if r.Merge == nil {
+		return nil
+	}
+	merge, err := argoprojiov1alpha1.ToNestedMergeGenerator(r.Merge)
+	if err != nil {
+		return nil
```
Comment (crenshaw-dev) [inline applicationset/generators/merge.go:210]: I think we should continue to throw and handle any error here.

File: applicationset/generators/merge.go [hunk 6]
```diff
@@ -221,6 +201,28 @@ func (m *MergeGenerator) GetRequeueAfter(appSetGenerator *argoprojiov1alpha1.App
...
+	return merge.ToMergeGenerator()
+}
+
+func getMatrixGenerator(r argoprojiov1alpha1.ApplicationSetNestedGenerator) *argoprojiov1alpha1.MatrixGenerator {
+	if r.Matrix == nil {
+		return nil
+	}
+	matrix, err := argoprojiov1alpha1.ToNestedMatrixGenerator(r.Matrix)
+	if err != nil {
+		return nil
```
Comment (crenshaw-dev) [inline applicationset/generators/merge.go:221]: I think we should continue to throw and handle any error here.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Overall looks great! A few small requests.

File: applicationset/controllers/requeue_after_test.go (hunk 1 above)
Comment (rumstead) [reply applicationset/controllers/requeue_after_test.go:147]: I guess with these changes it will be a moot point and if someone updates an application outside of the appset, the owner reference will trigger a reconciliation.

File: applicationset/controllers/requeue_after_test.go (hunk 4 above)
Comment (rumstead) [reply applicationset/controllers/requeue_after_test.go:29]: calling out my copy-pasta! :)

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Not surprising... I can't remember if we were even bundling appset as of 2.4.

**Comment by crenshaw-dev** [comment]
Nah, just conflicts. Will fix manually.

**Comment by ishitasequeira** [comment]
> Not surprising... I can't remember if we were even bundling appset as of 2.4.

We started bundling appsets in 2.3

**Comment by crenshaw-dev** [comment]
https://github.com/googleapis/repo-automation-bots/issues/4983

**Comment by rumstead** [comment]
thanks for the reviews @ishitasequeira and @crenshaw-dev
