### PR TITLE
feat(webhook): Fixed manifest-generate-paths annotation support for monorepos in BitBucket

### LINKED ISSUE #18968: manifest-generate-paths monorepo support for Bitbucket
# Summary

Support `argocd.argoproj.io/manifest-generate-paths` [Manifest Paths Annotation](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#manifest-paths-annotation) for Bitbucket to prevent spurious refreshes when multiple Applications use the same git monorepo stored in Bitbucket.

# Motivation

See #9472, where this ticket was spawned from.

# Proposal

Add support to the bitbucket webhook receiver to implement support the `argocd.argoproj.io/manifest-generate-paths` annotation.

### PR DESCRIPTION
**Pull request by anandf**
Fixes https://github.com/argoproj/argo-cd/issues/18968

This PR addresses adds improvements for https://github.com/argoproj/argo-cd/pull/20993

### PR Summary:
This PR addresses an issue with the argocd.argoproj.io/manifest-generate-paths [Manifest Paths Annotation](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#manifest-paths-annotation) in Argo CD when used with Bitbucket repositories.

### Key Changes:
Prevents spurious refreshes in cases where multiple Applications are using the same Git monorepo stored in Bitbucket.
Ensures that the manifest-generate-paths annotation is handled correctly, refreshing the app only when the files changed match with the paths in manifest-generate-paths .

### Steps to Verify this feature:
1. Disable the periodic polling of the git repositories by the following command to ensure that all refreshes happen only via webhook notifications.
```
kubectl patch cm argocd-cm -n argocd -p '{"data": {"timeout.reconciliation": "0"}}'
```
2. Set the debug logs in Argo CD Server component using the following command to verify changed files are being calculated correctly.
```
kubectl patch cm argocd-cmd-params-cm -n argocd -p '{"data": {"server.log.level": "debug"}}'
```
3. Restart the `argocd-server` deployment to ensure that the log level configuration change is picked up by the application.
```
kubectl scale deploy argocd-server -n argocd --replicas=0
kubectl scale deploy argocd-server -n argocd --replicas=1
```
4. Create a webhook for the private repository using the steps provided in https://support.atlassian.com/bitbucket-cloud/docs/manage-webhooks/

5. Create a Repository webhook token in BitBucket for the private repository and add the repository secret as follows
Detailed steps provided in this link : https://support.atlassian.com/bitbucket-cloud/docs/create-a-repository-access-token/
```
argocd login <server_hostname> --username admin --password $(kubectl get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d) --insecure
export WEBHOOK_TOKEN=<token_from_bb_console>
argocd repo add https://bitbucket.org/anandjoseph/argocd-sample-pvt.git --username x-token-auth --password $(echo $WEBHOOK_TOKEN)
```
6. Create a webhook in BitBucket, update the webhook UUID in secret
```
export WEBHOOK_UUID=<uuid_from_bb_console>
kubectl patch secret argocd-secret -n argocd -p '{"stringData": {"webhook.bitbucket.uuid": "$WEBHOOK_UUID"}}'
```
7. Check the logs and see if you find some debug logs as below
```
{"level":"debug","msg":"https://bitbucket.org/anandjoseph/argocd-sample-pvt.git has credentials","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"quay.io/rh-ee-anjoseph has credentials","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"found a matching repository for URL https://bitbucket.org/anandjoseph/argocd-sample-pvt","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"fetched user/password for repository URL 'https://bitbucket.org/anandjoseph/argocd-sample-pvt.git', initializing basic auth client","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"created bitbucket client with base URL 'https://api.bitbucket.org/2.0'","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"invoking diffstat call with parameters: [Owner:anandjoseph, RepoSlug:argocd-sample-pvt, Spec:..397e8a657cc47a32b8c4e150cb731a0f9d3cb751]","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"changed files for spec ..397e8a657cc47a32b8c4e150cb731a0f9d3cb751: [guestbook/guestbook-ui-deployment.yaml]","time":"2025-05-18T07:53:50Z"}
{"level":"info","msg":"Received push event repo: https://bitbucket.org/anandjoseph/argocd-sample-pvt, revision: change_version_28, touchedHead: false","time":"2025-05-18T07:53:51Z"}
```

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Good iterations on the previous PR. I think we can only enable this feature if webook auth is enabled. Otherwise it's an easy SSRF

**Comment by anandf** [comment]
> Good iterations on the previous PR. I think we can only enable this feature if webook auth is enabled. Otherwise it's an easy SSRF

Would mandating that the request from webhook handler would be made only if the repo creds are present in the system. If there is no secret present for the given URL, then we will not do the call to get the diffs.

**Comment by anandf** [comment]
If there is no valid repo creds for a given URL, then no external call is made and the changeset remains empty.
```
if repoCreds == nil {
		return []string{}, fmt.Errorf("unable to retrive repository credentials for bitbucket workspace %s and reposlug %s", workspace, repoSlug)
	}
```

**Comment by crenshaw-dev** [comment]
I don't think that's sufficient. Allowing a completely unauthenticated user to cause a credentialed API call would allow anyone with network access to use Argo to launch a DoS attack or to DoS Argo itself.

**Comment by anandf** [comment]
@crenshaw-dev Could you please check my recent change, where I am relying on `settings.WebhookBitbucketServerSecret` to check if its an authenticated webhook or not. If this is set, then all the webhook calls are checked for signature validity. Please advise if there is a better way to do the same.

File: util/webhook/webhook.go [hunk 1]
```diff
@@ -189,11 +193,31 @@ func affectedRevisionInfo(payloadIf any) (webURLs []string, revision string, cha
...
-			break
+		for _, changes := range payload.Push.Changes {
+			revision = changes.New.Name
+			change.shaBefore = changes.Old.Target.Hash
+			change.shaAfter = changes.New.Target.Hash
+			var repoCreds *v1alpha1.RepoCreds
+			var err error
+			// when webhook.bitbucket.secret is set in argocd-secret, then the payload must be signed and
+			// signature is validated before payload is parsed. Get DiffSet only for authenticated webhooks.
+			if len(a.settings.WebhookBitbucketServerSecret) > 0 {
```
Comment (crenshaw-dev) [inline util/webhook/webhook.go:204]: I think this should be BitbucketUUID instead of BitbucketServerSecret. But the idea lgmt.

File: util/webhook/webhook.go [hunk 2]
```diff
@@ -189,11 +193,31 @@ func affectedRevisionInfo(payloadIf any) (webURLs []string, revision string, cha
 		// See: https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Push
 		// NOTE: this is untested
 		webURLs = append(webURLs, payload.Repository.Links.HTML.Href)
-		// TODO: bitbucket includes multiple changes as part of a single event.
-		// We only pick the first but need to consider how to handle multiple
-		for _, change := range payload.Push.Changes {
-			revision = change.New.Name
-			break
+		for _, changes := range payload.Push.Changes {
```
Comment (crenshaw-dev) [inline util/webhook/webhook.go:196]: I'd consider still taking just the first item. Better to avoid making two major behavior changes in the same PR.

File: util/webhook/webhook.go [hunk 3]
```diff
@@ -189,11 +193,31 @@ func affectedRevisionInfo(payloadIf any) (webURLs []string, revision string, cha
 		// See: https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Push
 		// NOTE: this is untested
 		webURLs = append(webURLs, payload.Repository.Links.HTML.Href)
```
Comment (crenshaw-dev) [inline util/webhook/webhook.go:195]: Everything network-bound in this block should be handled within a context with a reasonable timeout, i.e. fetching the repo creds and then fetching the diffs.

**Comment by anandf** [comment]
@crenshaw-dev This PR is ready for review. Can it be considered for `release-3.0` release milestone ?

File: util/webhook/webhook.go (hunk 2 above)
Comment (anandf) [reply util/webhook/webhook.go:198]: Processing only the first item in the change list to avoid any major behaviour change.

File: util/webhook/webhook.go (hunk 3 above)
Comment (anandf) [reply util/webhook/webhook.go:197]: Using context with deadline of 10s to complete all callbacks.

File: util/webhook/webhook.go (hunk 1 above)
Comment (anandf) [reply util/webhook/webhook.go]: Corrected. Made the required changes in the recent commit.

**Review by jannfis — APPROVED** [review]
LGTM

**Comment by anandf** [comment]
Steps to verify this feature:
======================
1. Disable the periodic polling of the git repositories by the following command to ensure that all refreshes happen only via webhook notifications.
```
kubectl patch cm argocd-cm -n argocd -p '{"data": {"timeout.reconciliation": "0"}}'
```
2. Set the debug logs in Argo CD Server component using the following command to verify changed files are being calculated correctly.
```
kubectl patch cm argocd-cmd-params-cm -n argocd -p '{"data": {"server.log.level": "debug"}}'
```
3. Restart the `argocd-server` deployment to ensure that the log level configuration change is picked up by the application.
```
kubectl scale deploy argocd-server -n argocd --replicas=0
kubectl scale deploy argocd-server -n argocd --replicas=1
```
4. Create a webhook for the private repository using the steps provided in https://support.atlassian.com/bitbucket-cloud/docs/manage-webhooks/

5. Create a Repository webhook token in BitBucket for the private repository and add the repository secret as follows
Detailed steps provided in this link : https://support.atlassian.com/bitbucket-cloud/docs/create-a-repository-access-token/
```
argocd login <server_hostname> --username admin --password $(kubectl get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d) --insecure
export WEBHOOK_TOKEN=<token_from_bb_console>
argocd repo add https://bitbucket.org/anandjoseph/argocd-sample-pvt.git --username x-token-auth --password $(echo $WEBHOOK_TOKEN)
```
6. Create a webhook in BitBucket, update the webhook UUID in secret
```
export WEBHOOK_UUID=<uuid_from_bb_console>
kubectl patch secret argocd-secret -n argocd -p '{"stringData": {"webhook.bitbucket.uuid": "$WEBHOOK_UUID"}}'
```
7. Check the logs and see if you find some debug logs as below
```
{"level":"debug","msg":"https://bitbucket.org/anandjoseph/argocd-sample-pvt.git has credentials","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"quay.io/rh-ee-anjoseph has credentials","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"found a matching repository for URL https://bitbucket.org/anandjoseph/argocd-sample-pvt","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"fetched user/password for repository URL 'https://bitbucket.org/anandjoseph/argocd-sample-pvt.git', initializing basic auth client","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"created bitbucket client with base URL 'https://api.bitbucket.org/2.0'","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"invoking diffstat call with parameters: [Owner:anandjoseph, RepoSlug:argocd-sample-pvt, Spec:..397e8a657cc47a32b8c4e150cb731a0f9d3cb751]","time":"2025-05-18T07:53:49Z"}
{"level":"debug","msg":"changed files for spec ..397e8a657cc47a32b8c4e150cb731a0f9d3cb751: [guestbook/guestbook-ui-deployment.yaml]","time":"2025-05-18T07:53:50Z"}
{"level":"info","msg":"Received push event repo: https://bitbucket.org/anandjoseph/argocd-sample-pvt, revision: change_version_28, touchedHead: false","time":"2025-05-18T07:53:51Z"}
```

**Comment by jblsk** [comment]
Unfortunately, this fix is only for Bitbucket Cloud, not for Bitbucket DataCentre (DC, Server).
