### PR TITLE
fix: Inconsistent normalization logic during diff

### LINKED ISSUE #7938: Diffs ignored by trusted managers and tracking method normalization does not work for Secrets
**Describe the bug**

The trusted managers and tracking method normalization is not working for secrets.

**To Reproduce**

The simplest way to reproduce is to:
1. Create an app with an empty secret.
2. Switch tracking method to annotation: add `application.resourceTrackingMethod: annotation` to `argocd-cm` ConfigMap.
3. Refresh app and **click** on secret

**Expected behavior**

The secret should not have any difference

**Version**

```shell
v2.3.0
```

2.2.0 is not affected.

### PR DESCRIPTION
**Pull request by leoluz**
Signed-off-by: Leonardo Luz Almeida <leonardo_almeida@intuit.com>

### Problem:
This PR addresses the issue when different ArgoCD components were getting inconsistent diff results between live and desired state. The diff function requires a configuration to determine how to normalize the resource's state. The root problem is that different parts of the application were providing incomplete configurations to the diff which was causing inconsistent results.

### Solution:
This PR introduces the `DiffConfig` interface and the `DiffConfigBuilder` with the following responsibilities:
- `DiffConfig`: defines the public interface that diff consumers need to provide in order to compute diffs
- `DiffConfigBuilder`: The utility object to ensure consumers will provide valid DiffConfig

Fixes https://github.com/argoproj/argo-cd/issues/7938

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: util/argo/diff.go [hunk 1]
```diff
@@ -0,0 +1,379 @@
...
+func (b *DiffConfigBuilder) Build() (DiffConfig, error) {
+	err := b.diffConfig.Validate()
+	if err != nil {
+		return nil, err
+	}
+	return b.diffConfig, nil
+}
+
+// DiffConfig defines methods to retrieve the configurations used while applying diffs.
+type DiffConfig interface {
```
Comment (alexmt) [inline util/argo/diff.go:109]: Nitpick: we could just avoid introducing an interface and instead introduce `DataConfig` struct which has only private fields. This still ensures that consumer cannot modify config fields

File: util/argo/diff.go [hunk 2]
```diff
@@ -0,0 +1,379 @@
...
+	overrides := o
+	if overrides == nil {
+		overrides = make(map[string]appv1.ResourceOverride)
+	}
+	b.diffConfig.overrides = overrides
+	return b
+}
+
+// WithAppLabelKey sets the appLabelKey in the diff config.
+func (b *DiffConfigBuilder) WithAppLabelKey(l string) *DiffConfigBuilder {
```
Comment (alexmt) [inline util/argo/diff.go:53]: Nitpick:

Can you consider grouping methods to make it easier to catch errors during compilation time:

* `WithAppLabelKey`, `WithTrackingMethod` -> `WithTracking(appLabelKey string, trackingMethod string)`
* `WithAppName`, `WithNoCache` , `WithStateCache` -> `WithCaching(appName string, appStateCache *appstatecache.Cache, noCache bool)`
* `WithOverrides`, `WithIgnores`, `WithIgnoreAggregatedRoles` -> `WithDiffSettings(o map[string]v1alpha1.ResourceOverride, i []v1alpha1.ResourceIgnoreDifferences, ignoreAggregatedRoles bool)`

I'm hoping this way we will get methods with a manageable number of parameters and code won't compile if we introduce one more "diffing setting"

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you @leoluz ! Look good. Found one minor bug and added a few suggestions.

File: util/argo/diff.go [hunk 3]
```diff
@@ -0,0 +1,379 @@
...
+// WithNoCache sets the nocache in the diff config. Defines if it should retrieve
+// the computed diff from the cache.
+func (b *DiffConfigBuilder) WithNoCache(c bool) *DiffConfigBuilder {
+	b.diffConfig.noCache = &c
+	return b
+}
+
+// WithStateCache sets the appstatecache.Cache in the diff config. Only required if
+// retrieving the diff from the cache (NoCache = false).
+func (b *DiffConfigBuilder) WithStateCache(s *appstatecache.Cache) *DiffConfigBuilder {
```
Comment (alexmt) [inline util/argo/diff.go:80]: Instead of providing `*appstatecache.Cache` and `appName` you can provide `cache retriever` of type (`func(res *[]*appv1.ResourceDiff) error`):

```golang
WithStateCache(func(res *[]*appv1.ResourceDiff) error {
	return m.cache.GetAppManagedResources(app.Name res)
})
```

Not a big deal but might make it easier to test and minus one field in DiffConfig

File: test/testutil.go [hunk 4]
```diff
@@ -69,3 +71,12 @@ func MustLoadFileToString(path string) string {
 	}
 	return string(o)
 }
+
+func StrToUnstructured(jsonStr string) *unstructured.Unstructured {
```
[the remark this answers is not in the document]
Comment (leoluz) [reply test/testutil.go:75]: done

File: util/argo/diff.go [hunk 5]
```diff
@@ -0,0 +1,379 @@
+package argo
```
[the remark this answers is not in the document]
Comment (leoluz) [reply util/argo/diff.go:1]: done

File: util/argo/diff.go [hunk 6]
```diff
@@ -0,0 +1,379 @@
...
+
+// DiffFromCache will verify if it should retrieve the cached ResourceDiff based on this
+// DiffConfig. Returns true and the cached ResourceDiff if configured to use the cache.
+// Returns false and nil otherwise.
+func (c *diffConfig) DiffFromCache(appName string) (bool, []*appv1.ResourceDiff) {
+	if *c.noCache || c.stateCache == nil || appName == "" {
+		return false, nil
+	}
+	cachedDiff := make([]*appv1.ResourceDiff, 0)
+	if c.stateCache != nil && c.stateCache.GetAppManagedResources(appName, &cachedDiff) != nil {
```
[the remark this answers is not in the document]
Comment (leoluz) [reply util/argo/diff.go:336]: oh.. nice catch! Tks for that!

File: util/argo/diff.go (hunk 1 above)
Comment (leoluz) [reply util/argo/diff.go]: I thought about that but I think that with interface is safer. The reason is because consumers would still be able to instantiate an empty `DataConfig` struct and pass that as a parameter without validations. With the interface, the only way to get a valid instance is calling `DiffConfigBuilder.Build` which runs all the validations before returning the instance.

File: util/argo/diff.go (hunk 2 above)
Comment (leoluz) [reply util/argo/diff.go]: I implemented this approach. I had to make modifications in the validation logic as many of them didn't make sense anymore. Hopefully this will provide us compilation error and better tracking how consumers configure the diff.

File: util/argo/diff.go (hunk 3 above)
Comment (leoluz) [reply util/argo/diff.go]: I introduced 2 different methods in the builder instead:
- `WithNoCache()`
- `WithCache(s *appstatecache.Cache, appName string)`

I think this is cleaner and more intuitive for consumers to use. One thing I disliked about the cache retriever idea is that it would mutate the provided `*[]*appv1.ResourceDiff` parameter which would be very confusing.

**Comment by leoluz** [comment]
@alexmt Pushed 2 more commits addressing the review comments.
Please take a look.
Thank you

**Review by alexmt — APPROVED** [review]
LGTM
