### PR TITLE
fix(health): app missing health only when all resources are missing (#23995)

### LINKED ISSUE #23995: Application Missing health is inconsistent
Due to the following code, the Application Health goes to missing only when the desired resources does not have a health check defined. This is related to https://github.com/argoproj/argo-cd/pull/6446

https://github.com/argoproj/argo-cd/blob/678f61b8d3a4ce4443a49983f7deae9c80ad8983/controller/health.go#L69-L72

Since Application are implicitly "OutOfSync" when a resource is missing, there is no point to reflect this as the Application health. An app may be healthy with Missing resources, however, an app may not be synced.

### Proposal 

The Application should only be missing when ALL the resources are missing. If only one resource is Missing (whether it has a health check defined or not), the Application should have the normal aggregated status excluding the missing resources. 

This will allow user to know if an initial sync has been done, or perhaps the Application configuration have been changed to something totally different, without hiding the actual Application health.

### PR DESCRIPTION
**Pull request by agaudreault**
Fixes https://github.com/argoproj/argo-cd/issues/23995

### CODE REVIEW

File: controller/health.go [hunk 1]
```diff
@@ -21,27 +20,35 @@ import (
...
 		}
-		if res.Live != nil && (hookutil.IsHook(res.Live) || ignore.Ignore(res.Live)) {
+
+		// Contains actual resources that are not hooks
+		containsResources = true
+		if res.Live != nil {
+			containsLiveResources = true
+		}
+
+		// Do not aggreagte the health of the resource if the annotation to ignore health check is set to true
```
Comment (pjiang-dev) [inline controller/health.go]:
```suggestion
		// Do not aggregate the health of the resource if the annotation to ignore health check is set to true
```

File: controller/health.go [hunk 2]
```diff
@@ -79,6 +86,12 @@ func setApplicationHealth(resources []managedResource, statuses []appv1.Resource
 			appHealthStatus = healthStatus.Status
 		}
 	}
+
+	// If the app is expected to have resources but does not contain any live resources, set the app health to missing
+	if containsResources && !containsLiveResources && health.IsWorse(appHealthStatus, health.HealthStatusMissing) {
```
Comment (pjiang-dev) [inline controller/health.go:91]: Not a major concern but isn't `IsWorse` check not needed here because when `!containsLiveResources `is true (no live resources exist), appHealthStatus can only be Healthy (the default) since all missing resources are skipped in the loop and never updated it?

**Review by pjiang-dev — APPROVED** [review]
Minor comments but overall LGTM

File: controller/health.go (hunk 2 above)
Comment (agaudreault) [reply controller/health.go:91]: yeah, it will always return true with the current implementation. It is merely a safeguard for future proofing that if anything in the for-loop above change, the missing code wont break, because the requirement is to not/never set the health to a better status.

File: docs/operator-manual/upgrading/3.3-3.4.md [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+- Individual missing resources no longer affect the Application's overall health status
+- The health status now reflects the aggregated health of **existing resources**
+- The `OutOfSync` status already indicates when resources are missing, making the health status redundant for individual missing resources
+
+**Impact:**
+
+- Applications with some missing resources will now show the health of their existing resources (e.g., `Healthy`, `Progressing`, `Degraded`) instead of `Missing`
+- This provides better visibility into the actual state of deployed resources
+- Users can now distinguish between an Application that has never been synced (all resources missing = `Missing` health) vs. an Application with some resources deleted (shows health of remaining resources)
+- If the defined resource health check is explicitly returning `Missing` for an existing resource, that will still be reflected in the overall Application health
```
Comment (leoluz) [inline docs/operator-manual/upgrading/3.3-3.4.md]: What if CD pipelines expect the Argo CD application status to change to identify when it is necessary to sync? I believe that this is somehow a common configuration users have in their pipeline and we should state that they need to look at the sync status as well to identify those missing cases.

**Review by leoluz — CHANGES_REQUESTED** [review]

File: docs/operator-manual/upgrading/3.3-3.4.md (hunk 3 above)
Comment (agaudreault) [reply docs/operator-manual/upgrading/3.3-3.4.md]: Using the health status to detect sync would inherently be incorrect since the Application will usually not change Health state when it is required to sync. In this case, it was only change status when a new git resource was added, not modified. The Sync status is expected to go OutOfSync (unchanged) when a resource is modified or missing.

What may be impacted (positively) is Application monitoring based on health, since the apps are expected to go in Healthy instead of missing.

Comment (leoluz) [reply docs/operator-manual/upgrading/3.3-3.4.md]: > Using the health status to detect sync would inherently be incorrect since the Application will usually not change Health state when it is required to sync. In this case, it was only change status when a new git resource was added, not modified. The Sync status is expected to go OutOfSync (unchanged) when a resource is modified or missing.

Regardless of what we think it is correct or not, the impact section should state the situations where users may face issues. I think that we should clearly state those situations in that section instead of saying "xyz is better".

File: docs/operator-manual/upgrading/3.3-3.4.md [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+
+- Applications now show `Missing` health **only when ALL resources are missing** (e.g., before the first sync)
+- Individual missing resources no longer affect the Application's overall health status
+- The health status now reflects the aggregated health of **existing resources**
+- The `OutOfSync` status already indicates when resources are missing, making the health status redundant for individual missing resources
+
+**Impact:**
+
+- Applications with some missing resources will now show the health of their existing resources (e.g., `Healthy`, `Progressing`, `Degraded`) instead of `Missing`
+- This provides better visibility into the actual state of deployed resources
```
Comment (leoluz) [inline docs/operator-manual/upgrading/3.3-3.4.md]: I feel like this statement doesn't fit the "Impact" section. I would remove of move it somewhere else. Here we should clearly state the use-cases that can be impacted by this change only.

**Review by leoluz — CHANGES_REQUESTED** [review]

File: docs/operator-manual/upgrading/3.3-3.4.md (hunk 3 above)
Comment (agaudreault) [reply docs/operator-manual/upgrading/3.3-3.4.md]: updated description to describe the impact for automation.

**Review by leoluz — APPROVED** [review]
LGTM
