### PR TITLE
fix: prevent automatic refreshes from informer resync and status updates

### LINKED ISSUE #25291: Viewing Application in Argo CD UI triggers refresh
Checklist:

- [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [ ] I've pasted the output of `argocd version`.

**Describe the bug**
viewing an Application in the Argo CD web console triggers a refresh. This is notable even when the Argo CD instance has `timeout.reconciliation {.jitter}` set to 0s, which should otherwise stop the refresh behaviour barring other circumstances.

Creating an Argo CD instance, and checking the Argo CD web console should demonstrate the issue. Disabling the standard reconciliation should make the behaviour easier to witness

**To Reproduce**
Create an instance of Argo CD
(Optional) Disable the standard reconciliation loop using the `timeout.reconciliation` parameter
Create and view a sample Application from the web UI

**Expected behavior**
Application does not update due to UI, merely updating in its existing cycle

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**
created a script to monitor the logs locally

```
Monitoring for up to 10 minutes to detect refresh pattern...

Check 1 (2025-11-14T15:28:50Z): Still 2025-11-14T15:27:34Z (no change)
Check 2 (2025-11-14T15:29:06Z): Still 2025-11-14T15:27:34Z (no change)
Check 3 (2025-11-14T15:29:21Z): Still 2025-11-14T15:27:34Z (no change)
Check 4 (2025-11-14T15:29:36Z): Still 2025-11-14T15:27:34Z (no change)
Check 5 (2025-11-14T15:29:51Z): Still 2025-11-14T15:27:34Z (no change)
Check 6 (2025-11-14T15:30:06Z): Still 2025-11-14T15:27:34Z (no change)
Check 7 (2025-11-14T15:30:21Z): Still 2025-11-14T15:27:34Z (no change)
⚠️  FIRST CHANGE detected at 2025-11-14T15:30:36Z
   reconciledAt: 2025-11-14T15:27:34Z → 2025-11-14T15:30:22Z
   Time elapsed: ~120 seconds (~2 minutes)

Check 9 (2025-11-14T15:30:51Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 10 (2025-11-14T15:31:06Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 11 (2025-11-14T15:31:21Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 12 (2025-11-14T15:31:36Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 13 (2025-11-14T15:31:52Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 14 (2025-11-14T15:32:07Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 15 (2025-11-14T15:32:22Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 16 (2025-11-14T15:32:37Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 17 (2025-11-14T15:32:52Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 18 (2025-11-14T15:33:07Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 19 (2025-11-14T15:33:22Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 20 (2025-11-14T15:33:37Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 21 (2025-11-14T15:33:52Z): Still 2025-11-14T15:30:22Z (same as first change)
Check 22 (2025-11-14T15:34:07Z): Still 2025-11-14T15:30:22Z (same as first change)
⚠️  SECOND CHANGE detected at 2025-11-14T15:34:22Z
   reconciledAt: 2025-11-14T15:30:22Z → 2025-11-14T15:34:18Z

=== INTERVAL ANALYSIS ===
Checks between changes: 15 (each check = 15 seconds)
Interval between changes: 225 seconds (~3.75 minutes)
⚠️  Pattern: ~3.75 minutes (unexpected interval)

=== Stopping after detecting 2 changes ===

=== Summary ===
First change: 2025-11-14T15:30:36Z
Second change: 2025-11-14T15:34:22Z

```

### PR DESCRIPTION
**Pull request by aali309**
Fixes: #25291 

When timeout.reconciliation is set to 0s, Argo CD should disable automatic
refreshes. However, the informer's UpdateFunc handler was calling
requestAppRefresh() unconditionally on every update event, including:

1. Informer resync events (periodic re-list operations with same ResourceVersion)
2. Status-only updates (controller's own status patches)

This created a feedback loop where status updates triggered refresh requests,
which caused refreshes to occur every ~2-4 minutes even when
timeout.reconciliation=0s.

The fix:
- Skip refresh requests for informer resync events (ResourceVersion == ResourceVersion)
- Skip refresh requests for status-only updates (spec unchanged)
- Still process legitimate spec changes and automated sync enablement

This ensures that when timeout.reconciliation=0s, no automatic refreshes occur
from resync events or status update feedback loops, while still allowing manual
refreshes and legitimate spec changes to trigger refreshes as expected.

See logs 

```
Monitoring for up to 10 minutes to detect refresh pattern...

Check 1 (2025-11-14T14:52:12Z): Still 2025-11-14T14:51:11Z (no change)
Check 2 (2025-11-14T14:52:27Z): Still 2025-11-14T14:51:11Z (no change)
Check 3 (2025-11-14T14:52:42Z): Still 2025-11-14T14:51:11Z (no change)
Check 4 (2025-11-14T14:52:58Z): Still 2025-11-14T14:51:11Z (no change)
Check 5 (2025-11-14T14:53:13Z): Still 2025-11-14T14:51:11Z (no change)
Check 6 (2025-11-14T14:53:28Z): Still 2025-11-14T14:51:11Z (no change)
Check 7 (2025-11-14T14:53:43Z): Still 2025-11-14T14:51:11Z (no change)
Check 8 (2025-11-14T14:53:58Z): Still 2025-11-14T14:51:11Z (no change)
Check 9 (2025-11-14T14:54:13Z): Still 2025-11-14T14:51:11Z (no change)
Check 10 (2025-11-14T14:54:28Z): Still 2025-11-14T14:51:11Z (no change)
Check 11 (2025-11-14T14:54:43Z): Still 2025-11-14T14:51:11Z (no change)
Check 12 (2025-11-14T14:54:58Z): Still 2025-11-14T14:51:11Z (no change)
Check 13 (2025-11-14T14:55:13Z): Still 2025-11-14T14:51:11Z (no change)
Check 14 (2025-11-14T14:55:28Z): Still 2025-11-14T14:51:11Z (no change)
Check 15 (2025-11-14T14:55:43Z): Still 2025-11-14T14:51:11Z (no change)
Check 16 (2025-11-14T14:55:58Z): Still 2025-11-14T14:51:11Z (no change)
Check 17 (2025-11-14T14:56:14Z): Still 2025-11-14T14:51:11Z (no change)
Check 18 (2025-11-14T14:56:29Z): Still 2025-11-14T14:51:11Z (no change)
Check 19 (2025-11-14T14:56:44Z): Still 2025-11-14T14:51:11Z (no change)
Check 20 (2025-11-14T14:56:59Z): Still 2025-11-14T14:51:11Z (no change)
Check 21 (2025-11-14T14:57:14Z): Still 2025-11-14T14:51:11Z (no change)
Check 22 (2025-11-14T14:57:29Z): Still 2025-11-14T14:51:11Z (no change)
Check 23 (2025-11-14T14:57:44Z): Still 2025-11-14T14:51:11Z (no change)
Check 24 (2025-11-14T14:57:59Z): Still 2025-11-14T14:51:11Z (no change)
Check 25 (2025-11-14T14:58:14Z): Still 2025-11-14T14:51:11Z (no change)
Check 26 (2025-11-14T14:58:29Z): Still 2025-11-14T14:51:11Z (no change)
Check 27 (2025-11-14T14:58:44Z): Still 2025-11-14T14:51:11Z (no change)
Check 28 (2025-11-14T14:58:59Z): Still 2025-11-14T14:51:11Z (no change)
Check 29 (2025-11-14T14:59:15Z): Still 2025-11-14T14:51:11Z (no change)
Check 30 (2025-11-14T14:59:30Z): Still 2025-11-14T14:51:11Z (no change)
Check 31 (2025-11-14T14:59:45Z): Still 2025-11-14T14:51:11Z (no change)
Check 32 (2025-11-14T15:00:00Z): Still 2025-11-14T14:51:11Z (no change)
Check 33 (2025-11-14T15:00:15Z): Still 2025-11-14T14:51:11Z (no change)
Check 34 (2025-11-14T15:00:30Z): Still 2025-11-14T14:51:11Z (no change)
Check 35 (2025-11-14T15:00:45Z): Still 2025-11-14T14:51:11Z (no change)
Check 36 (2025-11-14T15:01:00Z): Still 2025-11-14T14:51:11Z (no change)
Check 37 (2025-11-14T15:01:15Z): Still 2025-11-14T14:51:11Z (no change)
Check 38 (2025-11-14T15:01:30Z): Still 2025-11-14T14:51:11Z (no change)
Check 39 (2025-11-14T15:01:46Z): Still 2025-11-14T14:51:11Z (no change)
Check 40 (2025-11-14T15:02:01Z): Still 2025-11-14T14:51:11Z (no change)

=== Summary ===
✅ No automatic refreshes detected during monitoring period
```

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: controller/appcontroller.go [hunk 1]
```diff
@@ -2486,11 +2487,46 @@ func (ctrl *ApplicationController) newApplicationInformerAndLister() (cache.Shar
...
+					// Skip refresh requests for status-only updates (spec unchanged)
+					// This prevents feedback loop: status update → UpdateFunc → requestAppRefresh → refresh → status update
+					if equality.Semantic.DeepEqual(oldApp.Spec, newApp.Spec) {
+						// Check if user requested refresh/hydrate via annotations
+						// Don't skip if user explicitly requested refresh/hydrate
+						oldAnnotations := oldApp.GetAnnotations()
+						newAnnotations := newApp.GetAnnotations()
+						refreshAdded := (oldAnnotations == nil || oldAnnotations[appv1.AnnotationKeyRefresh] == "") &&
+							(newAnnotations != nil && newAnnotations[appv1.AnnotationKeyRefresh] != "")
+						hydrateAdded := (oldAnnotations == nil || oldAnnotations[appv1.AnnotationKeyHydrate] == "") &&
```
Comment (anandf) [inline controller/appcontroller.go:2613]: Is this a new constant `appv1.AnnotationKeyHydrate` added as part of this PR ? I could not find this constant at `./pkg/apis/application/v1alpha1/application_annotations.go` where similar constant `AnnotationKeyRefresh` is defined.

File: controller/appcontroller.go [hunk 2]
```diff
@@ -2486,11 +2487,46 @@ func (ctrl *ApplicationController) newApplicationInformerAndLister() (cache.Shar
...
+						// User explicitly requested refresh/hydrate - fall through to normal processing
+					}
+
+					// Spec changed - legitimate update, proceed with refresh
 					if automatedSyncEnabled(oldApp, newApp) {
 						log.WithFields(applog.GetAppLogFields(newApp)).Info("Enabled automated sync")
 						compareWith = CompareWithLatest.Pointer()
 					}
-					if ctrl.statusRefreshJitter != 0 && oldApp.ResourceVersion == newApp.ResourceVersion {
+					if ctrl.statusRefreshJitter != 0 {
```
Comment (anandf) [inline controller/appcontroller.go]: Why is the additional check `oldApp.ResourceVersion == newApp.ResourceVersion`. Do we want to apply jitter to all updates  instead of only the updates related to spec ?

File: controller/appcontroller_test.go [hunk 3]
```diff
@@ -1808,6 +1809,220 @@ func TestUnchangedManagedNamespaceMetadata(t *testing.T) {
...
+		newApp.Annotations[v1alpha1.AnnotationKeyRefresh] = string(v1alpha1.RefreshTypeNormal)
+
+		// Simulate UpdateFunc call
+		simulateUpdateFunc(oldApp, newApp)
+
+		// Check that refresh WAS requested (annotation should trigger refresh)
+		checkRefreshRequested(app.QualifiedName(), true, "Status-only update WITH refresh annotation")
+	})
+
+	t.Run("Status-only update WITH hydrate annotation SHOULD trigger refresh", func(_ *testing.T) {
```
Comment (anandf) [inline controller/appcontroller_test.go:2125]: For completeness, can you add a test case for scenario when both the annotations are added ? Also if the annotation is removed, is it expected to trigger a referesh ? Will it be treated as a change to the Annotation ?

**Review by anandf — CHANGES_REQUESTED** [review]
Posted few comments. Looks good overall. It will be good to add an E2E test case to ensure that the setting `timeout.reconciliation=0s` does not trigger to many refreshes.

File: controller/appcontroller.go (hunk 1 above)
Comment (aali309) [reply controller/appcontroller.go:2613]: `AnnotationKeyHydrate` is not a new constant. It is defined in application_annotations.go [at line 8](https://github.com/aali309/argo-cd/blob/de6ad566ce4f1e8d04d97bb954ab4a85364cbb90/pkg/apis/application/v1alpha1/application_annotations.go#L8)

File: controller/appcontroller.go (hunk 2 above)
Comment (aali309) [reply controller/appcontroller.go]: Good catch. The original code applied jitter only to resync events (oldApp.ResourceVersion == newApp.ResourceVersion). With this fix, resync events return early and don't trigger refreshes, so jitter for resyncs is no longer relevant

File: controller/appcontroller_test.go (hunk 3 above)
Comment (aali309) [reply controller/appcontroller_test.go:2125]: I tested these scenarios locally: only annotation addition should trigger refresh. Removal should not. I will add these tests.

**Review by anandf — APPROVED** [review]
LGTM

File: controller/appcontroller.go [hunk 4]
```diff
@@ -1013,17 +1011,71 @@ func (ctrl *ApplicationController) processAppOperationQueueItem() (processNext b
...
+		// We cannot rely on informer since applications might be updated by both application controller and api server
+		if app.Operation != nil {
+			freshApp, err := ctrl.applicationClientset.ArgoprojV1alpha1().Applications(app.ObjectMeta.Namespace).Get(context.Background(), app.Name, metav1.GetOptions{})
+			if err != nil {
+				if apierrors.IsNotFound(err) {
+					// App was deleted, skip processing
+					return processNext
+				}
+				logCtx.WithError(err).Error("Failed to retrieve latest application state")
+				return processNext
```
Comment (jannfis) [inline controller/appcontroller.go]: This could be much easier written as:

```go
if !apierrors.IsNotFound(err) {
    logCtx.WithError(...)
}
return processNext
```

File: controller/appcontroller.go [hunk 5]
```diff
@@ -2514,34 +2554,82 @@ func (ctrl *ApplicationController) newApplicationInformerAndLister() (cache.Shar
 				}
 			},
 			UpdateFunc: func(old, new any) {
-				if !ctrl.canProcessApp(new) {
```
Comment (jannfis) [inline controller/appcontroller.go:2534]: Moving this check further down will have undesired side effects. 

`canProcessApp()` checks things like shard assignment, whether the source namespace is allowed and more. Do not add items to the operation queue before this check has passed.

File: controller/appcontroller.go [hunk 6]
```diff
@@ -2514,34 +2554,82 @@ func (ctrl *ApplicationController) newApplicationInformerAndLister() (cache.Shar
...
 					return
 				}
 
-				key, err := cache.MetaNamespaceKeyFunc(new)
-				if err != nil {
+				oldApp, oldOK := old.(*appv1.Application)
+				newApp, newOK := new.(*appv1.Application)
+
+				// Always queue operations if present, regardless of canProcessApp result
+				// Operations are explicit user actions and must be processed
```
Comment (jannfis) [inline controller/appcontroller.go]: This is plain wrong.

File: controller/appcontroller.go [hunk 7]
```diff
@@ -2514,34 +2554,82 @@ func (ctrl *ApplicationController) newApplicationInformerAndLister() (cache.Shar
...
+							// Operations are already queued above if present
+							// Still update sharding and hydration queue for status changes
+							if ctrl.hydrator != nil {
+								ctrl.appHydrateQueue.AddRateLimited(newApp.QualifiedName())
+							}
+							ctrl.clusterSharding.UpdateApp(newApp)
+							return
+						}
+						// User explicitly requested refresh/hydrate - fall through to normal processing
+					}
```
Comment (jannfis) [inline controller/appcontroller.go:2623]: Frankly, I think all this complex logic here adds too much cognitive complexity and is difficult to unit test.

I would suggest to outsource some of the more complex assignments (operationChanged, deletioneTimestampChanged) to their own short functions, or even to wrap all the logic for checking whether only the status has changed into its own function. This keeps code a little more readable, testable and potentially reusable.

**Comment by fvogl** [comment]
we're eagerly waiting for this to get closed. :(

**Review by jannfis — APPROVED** [review]
LGTM, thanks!
