### PR TITLE
fix(repo-server): excess git requests, resolveReferencedSources and runManifestGenAsync not using cache (Issue #14725)

### LINKED ISSUE #14725: Excessive requests to git repository on commit to monorepo w/ multi-source apps
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

With 71 multi-source applications in a monorepo (in Bitbucket), a single commit triggers 271 requests to the git repository (11 fetch, 260 ls-remote). Logs show 333 "getting manifest cache" entries, with 15 cache hits and 318 cache misses. Example application sources:

```shell
sources:
  - path: manifests/my-app/
    repoURL: git@bitbucket.org:my-company/argo.git
    targetRevision: HEAD
  - chart: my-chart
    helm:
      releaseName: my-release
      valueFiles:
      - $values/values/my-app-values.yaml
    repoURL: my-helm-repo/charts
    targetRevision: 0.1.0
  - ref: values
    repoURL: git@bitbucket.org:my-company/argo.git
    targetRevision: HEAD
``` 

**To Reproduce**

Make any commit to the repository.

**Expected behavior**

Far fewer requests to the git repository and more cache hits.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.7.7+4650bb2.dirty
  BuildDate: 2023-07-05T19:42:32Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```shell
msg="getting manifests cache" appName=tenant-1 appSrc="{\"appSrc\":{\"repoURL\":\"\",\"ref\":\"values\"},\"srcRefs\":{\"$values\":{\"repoURL\":\"git@bitbucket.org:my-company/argo-dev.git\",\"project\":\"\",\"targetRevision\":\"HEAD\",\"chart\":\"\"}}}
```

In depth discussion with @crenshaw-dev on Slack with more detail. https://cloud-native.slack.com/archives/C01TSERG0KZ/p1690317861587929

Discussed at Argo SIG Scalability meeting on July and @ishitasequeira volunteered to take a look.

### PR DESCRIPTION
**Pull request by nromriell**
Partially Fixes #14725

First part of a split of the [initial PR](https://github.com/argoproj/argo-cd/pull/16309). Starts the fixes required to remove the excess git requests when using multi-source and ref sources.

Issue:
When `resolveReferencedSources` and `runManifestGenAsync` call `newClientResolveRevision` they currently do not pass the git options to use the cache when enabled, because of this when `newClientResolveRevision` creates a new git client and calls `LsRemote` the cache is always skipped 

Changes: 
Updated the ls-remote calls from resolveReferencedSources and runManifestGenAsync to have access to the cache

Impact:
On its own this does not fix the issue. This will reduce the number of ls-remote currently being made by preventing multiple calls inside the same goroutine or slightly time offset calls from missing cache, however due to the fact that a large number of calls are made by nearly simultaneous processes when the cache expires this is only a partial fix.

This also does not fix the large number of fetch calls being made to ref-only repos.

These two remaining items will be addressed in follow PRs

Baseline v2.9.0 with 200 multi-source applications with a ref only source:
Screenshot from 2023-11-18 18-24-30

With the changes in this PR under the same conditions:
Screenshot from 2023-11-21 00-43-54

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [X] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [X] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Nice, looks like this massively mitigates the issue with a relatively lightweight change. Very safe and easy to cherry-pick back. Thanks for splitting up the PRs!

**Comment by nromriell** [comment]
> Nice, looks like this massively mitigates the issue with a relatively lightweight change. Very safe and easy to cherry-pick back. Thanks for splitting up the PRs!

Of course! Definitely was a great idea to split them, much easier to follow the changes

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -686,6 +687,8 @@ func (s *Service) runManifestGenAsync(ctx context.Context, repoRoot, commitSHA,
 		close(ch.responseCh)
 	}()
 
+	settings := operationSettings{sem: s.parallelismLimitSemaphore, noCache: q.NoCache, noRevisionCache: q.NoRevisionCache, allowConcurrent: q.ApplicationSource.AllowsConcurrentProcessing()}
```
Comment (crenshaw-dev) [inline reposerver/repository/repository.go:690]: Instead of instantiating this settings object, what if we directly reference `q.NoCache` and `q.NoRevisionCache` below when we instantiate the cache?

Comment (nromriell) [reply reposerver/repository/repository.go]: Great point, thanks, removed

**Review by ishitasequeira — APPROVED** [review]
Thanks @nromriell for breaking the huge PR into smaller chunks. The change is really effective.

The code looks good to me overall.

**Comment by nromriell** [comment]
> Thanks @nromriell for breaking the huge PR into smaller chunks. The change is really effective.
> 
> 
> 
> The code looks good to me overall.

Of course, thanks for taking the time to review!

File: reposerver/repository/repository.go [hunk 2]
```diff
@@ -300,6 +300,7 @@ func (s *Service) runRepoOperation(
 	var gitClient git.Client
 	var helmClient helm.Client
 	var err error
+	gitClientOpts := git.WithCache(s.cache, !settings.noRevisionCache && !settings.noCache)
```
Comment (leoluz) [inline reposerver/repository/repository.go:303]: It seems that the `repository.Service.cache` is just Redis based and doesn't leverage the `twolevel` cache client. Can you please confirm my understanding of this part of the code? If so, it means that we are moving the chatty communication from Git to Redis which can bring new problems.

I don't want to push for a premature optimization as long as we are aware of this possible behaviour and have a plan B if we want to go with this implementation which I am not opposed to.

**Review by leoluz — COMMENTED** [review]
Tks a lot for breaking the original PR. 
Please check my comment.

File: reposerver/repository/repository.go (hunk 2 above)
Comment (nromriell) [reply reposerver/repository/repository.go:303]: That's right, overall redis requests are down after the change due to not having to try and get and set the values for each application each time. 

I do however have the optimization for moving this to a two level cache as part of the original PR and in the final part of the PR split https://github.com/nromriell/argo-cd/pull/3

**Review by leoluz — APPROVED** [review]
LGTM
Awesome job @nromriell !

**Comment by nromriell** [comment]
Thanks @crenshaw-dev @ishitasequeira @leoluz for taking the time to review!
