### PR TITLE
fix: prevent rootpath duplication in OIDC redirect URLs, fixes #21857 #20790 #12195 

### LINKED ISSUE #12195: ArgoCD : Redirect loop UI
### Discussed in https://github.com/argoproj/argo-cd/discussions/12175

<div type='discussions-op-text'>

<sup>Originally posted by **mravily** January 27, 2023</sup>

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

1.  When installing ArgoCD at a root path (e.g., "/argocd") and accessing that root path, you get redirected to /argocd/applications, and then immediately redirected to /argocd/argocd/login?...

This appears to enter a redirect loop.

2. When installing ArgoCD at a base href (e.g., "/argocd") and accessing that base href, the UI doesn't appear anymore and a error text was displayed `Unable to load data: Not Found.`..

Environment: K3D Cluster 

**To Reproduce**

```
├── cluster.yaml
├── config
│   ├── Kustomization.yaml
│   └── argocd-cmd-params-cm-patch.yaml
├── ingress.yaml
└── start.sh
```
1. Install K3D Cluster with this minimal config 

`cluster.yaml`
```yaml
apiVersion: k3d.io/v1alpha4 # this will change in the future as we make everything more stable
kind: Simple # internally, we also have a Cluster config, which is not yet available externally
metadata:
  name: argo-cd # name that you want to give to your cluster (will still be prefixed with `k3d-`)
servers: 1 # same as `--servers 1`
agents: 2 # same as `--agents 2`
kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
  hostIP: "127.0.0.1" # where the Kubernetes API will be listening on
  hostPort: "6445" # where the Kubernetes API listening port will be mapped to on your host system
image: rancher/k3s:v1.22.17-k3s1 # same as `--image rancher/k3s:v1.20.4-k3s1`
ports:
  - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
```

2.  Install ArgoCD with Kustomize (separate in two file on a same folder config) 

`argocd-cmd-params-cm-patch.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  # server.basehref: "/argocd"
  server.rootpath: "/argocd"
```
`Kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# ## changes to config maps
patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yml

namespace: argocd
```

3.  Setup an Ingress to redirect on GUI

`ingress.yaml`
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: argocd-ingress
    namespace: argocd
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: localhost 
      http:
        paths:
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
```

4. Launch start.sh

`start.sh`
```shell
k3d cluster create --config config/k3d-default.yaml

kubectl create namespace argocd

kubectl apply -k config/install

kubectl apply -f config/ingress.yaml

kubectl wait deploy/argocd-server -n argocd --for condition=available --timeout=600s
```

5. Access on the `localhost:8080/argocd`, enter password and see the errors 
```shell
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo 
```

**Expected behavior**

**Screenshots**

**Version**

```
argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:45:12Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/amd64
FATA[0000] configmap "argocd-cm" not found  
```

**Logs**

```shell
argocd login localhost:8080 --grpc-web-root-path /argo-cd
```

```
FATA[0019] rpc error: code = Unknown desc = POST https://localhost:8080/argo-cd/session.SessionService/Create failed with status code 404 
```
</div>

### LINKED ISSUE #20790: Base path KO during login phase
Hi,

Since 2.13.0 version, the login phase is KO because the root path is duplicated if login is correct. 

```
server:
  extraArgs:
    - --insecure
    - --rootpath
    - /argocd

  ingress:
    enabled: true
    ingressClassName: "nginx"
    path: /argocd

configs:
  cm:
    url: https://test.com/argocd

notifications:
  enabled: true
  argocdUrl: https://test.com/argocd
```

When login is correct, browser try to load  https://test.com/argocd/argocd/applications

In 2.12.6, it's correct.

Maybe because of this  ?
- https://github.com/argoproj/argo-cd/pull/20004
- https://github.com/argoproj/argo-cd/pull/20571

### LINKED ISSUE #21857: ArgoCD Helmchart login page loads normally but the applications shows blank colored page
Checklist:

* [yes] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [yes ] I've included steps to reproduce the bug.
* [yes ] I've pasted the output of `argocd version`.

**Describe the bug**
ArgoCD Helmchart login page loads normally but the applications shows blank colored page after the username and password login
I access it with nginx ingress as a node port and it`s working fine with a lot of other services on my cluster
this is the link I use :http://nodehostname/argocd it changes to :
http://nodehostname/argocd/login?return_url=http%3A%2F%2Fdc3adastsl03v%2Fargocd%2Fapplications
I enter the username and password correctly and sign in it takes me to this :
http://nodehostname/argocd/argocd/applications
duplicating the argocd path and taking me to blank page 

This is the configurations for the ingress:
#
#
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    # -- Specific implementation for ingress controller. One of `generic`, `aws` or `gke`
    ## Additional configuration might be required in related configuration sections
    controller: generic
    # -- Additional ingress labels
    labels: {}
    # -- Additional ingress annotations
    ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-1-ssl-passthrough
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /argocd/$2
      # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/ssl-passthrough: "true"

    # -- Defines which ingress controller will implement the resource
    ingressClassName: "nginx"

    # -- Argo CD server hostname
    # @default -- `""` (defaults to global.domain)
    hostname: ""

    # -- The path to Argo CD server
    path: /argocd(/|$)(.*)

    # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
    pathType: ImplementationSpecific

    # -- Enable TLS configuration for the hostname defined at `server.ingress.hostname`
    ## TLS certificate will be retrieved from a TLS secret `argocd-server-tls`
    ## You can create this secret via `certificate` or `certificateSecret` option
    tls: false

and also edited this in configs.params:
    ## Server properties
    # -- Run server without TLS
    ## NOTE: This value should be set when you generate params by other means as it changes ports used by ingress template.
    server.insecure: true
    # -- Value for base href in index.html. Used if Argo CD is running behind reverse proxy under subpath different from /
    server.basehref: /argocd
    # -- Used if Argo CD is running behind reverse proxy under subpath different from /
    server.rootpath: '/argocd'

**To Reproduce**
I enter the link 
http://dc3adastsl03v/argocd
and login then the issue happens

**Expected behavior**
To show me the applications page

**Screenshots**

Image

Image

**Version**
v2.13.4
Helm version :
7.8.2
```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by Diasker**
# Fix rootPath duplication in OIDC callback URLs

Fixes #21857
Fixes #20790
Fixes #12195

## Checklist

- [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
- [x] The title of the PR states what changed and the related issues number (used for the release note)
- [x] The title of the PR conforms to the Toolchain Guide
- [x] I've included "Fixes [ISSUE #]" in the description to automatically close the associated issues
- [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them (N/A - this is a bug fix)
- [ ] Does this PR require documentation updates? (No)
- [ ] I've updated documentation as required by this PR (N/A - no documentation updates needed)
- [x] I have signed off all my commits as required by DCO
- [x] I have written unit tests for my change
- [x] My build is green
- [ ] My new feature complies with the feature status guidelines (N/A - this is a bug fix)
- [x] I have added a brief description of why this PR is necessary and what this PR solves
- [ ] Optional. My organization is added to USERS.md
- [x] Optional. For bug fixes, this fix should be cherry-picked into v2.8, v2.9, and v2.10 releases as it affects OIDC authentication functionality 

## Problem Description

When ArgoCD is configured with a `rootPath`, there is an issue where the `rootPath` appears duplicated in OIDC authentication callback URLs. For example, when `rootPath` is set to `/argocd`, the callback URL becomes `https://example.com/argocd/argocd/...`, causing authentication to fail and preventing users from successfully logging in.

Note that the `/argocd` segment appears twice in the URL. This causes the authentication callback to fail, preventing users from successfully logging in.

This issue has been reported in multiple tickets:
- #21857
- #20790
- #12195

## Root Cause Analysis

After reviewing the code, I identified two functions in `server.go` that contribute to this issue:

1. `withRootPath` function: When `rootPath` is empty, it still creates an `http.ServeMux` and processes the path, instead of directly returning the original handler.

2. `newRedirectServer` function: When constructing the server address and handling redirect URLs, it doesn't properly handle the empty `rootPath` case, which can lead to rootPath being added multiple times in certain scenarios.

## Fix Implementation

I've made the following changes to `server.go`:

1. Modified the `withRootPath` function to add handling for empty `rootPath`.
2. Modified the `newRedirectServer` function to improve address construction logic.
These changes ensure that `rootPath` is handled correctly in URL processing, preventing the path duplication issue.

## Testing Validation

I've validated the fix through the following methods:

1. **Unit Testing**:
   - I've added unit tests in `server/rootpath_test.go` to verify the fix.
   - Tests cover scenarios with and without rootPath, as well as cases with rootPath duplication.
   - All tests pass, confirming the effectiveness of the fix.
   
   Here are the test results:
   ```
   === RUN   TestWithRootPathEmptyRootPath
   --- PASS: TestWithRootPathEmptyRootPath (0.00s)
   === RUN   TestWithRootPathNonEmptyRootPath
   --- PASS: TestWithRootPathNonEmptyRootPath (0.00s)
   === RUN   TestNewRedirectServerEmptyRootPath
   --- PASS: TestNewRedirectServerEmptyRootPath (0.00s)
   === RUN   TestNewRedirectServerNonEmptyRootPath
   --- PASS: TestNewRedirectServerNonEmptyRootPath (0.00s)
   === RUN   TestNewRedirectServerRootPathDuplication
   --- PASS: TestNewRedirectServerRootPathDuplication (0.00s)
   PASS
   ```
   
   The key test `TestNewRedirectServerRootPathDuplication` verifies that when a request path already contains the rootPath (e.g., `/argocd/applications`), the redirect URL correctly becomes `https://example.com:8080/argocd/applications` instead of the duplicated `https://example.com:8080/argocd/argocd/applications`.

2. **Building ArgoCD Image**:
   - Successfully built an ArgoCD image with the fix (available at docker.io/fuckery/argocd:rootpath-fix)
   - The build process completed without any issues

3. **Deployment Testing**:
   - Deployed an ArgoCD instance with the fix, configured with `rootPath: /argocd`
   - Verified that the UI is accessible
   - Verified that the OIDC login flow works correctly
   - Verified that the redirect URL after login does not contain duplicated rootPath

4. **Comparison Testing**:
   - Compared behavior before and after the fix
   - Before: Redirect URL contained duplicated rootPath (`/argocd/argocd/`)
   - After: Redirect URL is correct, without duplicated rootPath (`/argocd/`)

## Impact Scope

This fix only affects ArgoCD instances configured with a `rootPath` parameter, particularly when using OIDC authentication. The fix does not impact other functionality or configurations.

## Summary

This fix resolves the rootPath duplication issue in ArgoCD, allowing ArgoCD instances configured with `rootPath` to properly use OIDC authentication. The fix is minimal and focused, and has been validated through actual deployment testing.

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -1342,13 +1347,25 @@ func (server *ArgoCDServer) registerDexHandlers(mux *http.ServeMux) {
 
 // newRedirectServer returns an HTTP server which does a 307 redirect to the HTTPS server
 func newRedirectServer(port int, rootPath string) *http.Server {
-	addr := fmt.Sprintf("localhost:%d/%s", port, strings.TrimRight(strings.TrimLeft(rootPath, "/"), "/"))
+	var addr string
+	if rootPath == "" {
+		addr = fmt.Sprintf("localhost:%d", port)
+	} else {
+		addr = fmt.Sprintf("localhost:%d/%s", port, strings.TrimRight(strings.TrimLeft(rootPath, "/"), "/"))
```
Comment (andrii-korotkov-verkada) [inline server/server.go:1354]: Just use `strings.Trim(...)`

File: server/server.go [hunk 2]
```diff
@@ -1342,13 +1347,25 @@ func (server *ArgoCDServer) registerDexHandlers(mux *http.ServeMux) {
...
+	}
+
 	return &http.Server{
 		Addr: addr,
 		Handler: http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
 			target := "https://" + req.Host
 			if rootPath != "" {
-				target += "/" + strings.TrimRight(strings.TrimLeft(rootPath, "/"), "/")
+				root := strings.TrimRight(strings.TrimLeft(rootPath, "/"), "/")
```
Comment (andrii-korotkov-verkada) [inline server/server.go:1362]: `strings.Trim(...)`

File: server/server.go [hunk 3]
```diff
@@ -1342,13 +1347,25 @@ func (server *ArgoCDServer) registerDexHandlers(mux *http.ServeMux) {
...
+				target += "/" + root
+
+				// Check if the request path already contains rootPath
+				// If so, remove rootPath from the request path
+				prefix := "/" + root
+				req.URL.Path = strings.TrimPrefix(req.URL.Path, prefix)
```
Comment (andrii-korotkov-verkada) [inline server/server.go:1368]: Maybe modify how `target` is updated instead? req.URL.Path modification may bring req in the inconsistent state.

**Review by andrii-korotkov-verkada — APPROVED** [review]

File: server/server.go (hunk 3 above)
Comment (Diasker) [reply server/server.go]: Thank you for your review and suggestions! I have made changes based on your feedback!

**Comment by Diasker** [comment]
> Hi, I have same problem. I am using helmchart deploy
> 
> Deployed Chart version: 7.8.22 Deployed App version: v2.14.9
> 
> in 2.14.9 version, Since the login phase is ok, after that the root path is duplicated.
> 
> server.basehref: /argocd server.rootpath: '/argocd'
> 
> but it's redirecting after login https://localhost/argocd/argocd/applications

Hi there. As you see now, the reviewers might be busy and haven’t had time to merge the fix for this yet.

In the meantime, you can try applying the changes from my PR (if applicable) directly to your setup, or you can test the pre-built image I’ve shared: fuckery/argocd:rootpath-fix. This image includes the fix for the root path duplication issue.

**Review by agaudreault — APPROVED** [review]
LGTM

**Comment by Diasker** [comment]
> Hello is this applied on the latest docker image or just on this fuckery/argocd ?

Sorry, I'm not sure about that. But I think they haven't built the latest image just now after merging my PR.

**Comment by PandelisZ** [comment]
For those also browsing:

Key highlights 
    **nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"**

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # If you encounter a redirect loop or are getting a 307 response code
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: https
  tls:
  - hosts:
    - argocd.example.com
    secretName: argocd-server-tls # as expected by argocd-server
```
