### PR TITLE
fix: updated config file permission requirements for windows (#9666)

### LINKED ISSUE #9666: CLI returns "config file has incorrect permission flags" error on Windows
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

The CLI is returning the error "config file has incorrect permission flags:-rw-rw-rw-.change the file permission either to 0400 or 0600." when running commands on Windows.

I have tried changing the permissions on my config file so that only my user (the owner of the file) has access to it however it still produces the same error. I have also tried deleting the config file and generating a new file via `argocd login` but it didn't help.

I do not get the error on v2.3.4.

**To Reproduce**

1. Run `argocd app list`

**Expected behavior**

The command runs without any errors and returns the list of applicatons.

**Screenshots**

image

**Version**

```shell
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:54:25Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: windows/amd64
```

**Logs**

```
time="2022-06-15T19:47:59+10:00" level=fatal msg="config file has incorrect permission flags:-rw-rw-rw-.change the file permission either to 0400 or 0600."
```

### LINKED ISSUE #9702: Not able to run argocd commands in Windows CLI- cmd and powershell
I am trying to connect to my ArgoCD setup in my windows laptop. I am getting the below error.

PS C:\kube> ./argocd proj list
time="2022-06-17T15:35:09+05:30" level=fatal msg="config file has incorrect permission flags:-rw-rw-rw-.change the file permission either to 0400 or 0600."
PS C:\kube>

argogitissue

### PR DESCRIPTION
**Pull request by gdsoumya**
Fixes #9666 
Fixes #9702 

This PR updates the permission requirements for windows to 0444 or 0666 instead of 0400 and 0600. The config file produced by argocd cli on windows always appears to be having 0666 permission this is probably due to some limitations on windows acl, hence this PR updates the requirement specifically for windows for 0666 or 0444 permission instead of 0400/0600.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
Thank you!

File: util/localconfig/localconfig_test.go [hunk 1]
```diff
@@ -1,3 +1,5 @@
+//go:build !windows
```
Comment (crenshaw-dev) [inline util/localconfig/localconfig_test.go:1]: Can we have an equivalent test for windows?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: util/localconfig/localconfig_test.go (hunk 1 above)
Comment (crenshaw-dev) [reply util/localconfig/localconfig_test.go:1]: From Slack:

> I actually did try to create windows only tests but I just couldn't manage to set the permission properly with golang it just won't set it to something other than 0444 or 0666

lgtm. :-)

**Review by crenshaw-dev — APPROVED** [review]
