### PR TITLE
fix(hydrator): git fetch needs creds (#25727)

### LINKED ISSUE #25727: Source Hydrator fails due to Git notes conflict (`refs/notes/hydrator.metadata`) (v3.3.0-rc2)
<!-- If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack). -->

Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [ ] I've pasted the output of `argocd version`.

---

## Describe the bug
# image: quay.io/argoproj/argocd:v3.3.0-rc2

Argo CD Source Hydrator intermittently fails during hydration due to a Git notes push conflict on  
`refs/notes/hydrator.metadata`.

When multiple hydrations run close together (e.g. multiple apps or parallel syncs), the hydrator attempts to push a Git note and fails with a `fetch first` error. This causes hydration to fail even though the rendered manifests are valid.

---

## To Reproduce

1. Enable Source Hydrator
2. Configure multiple applications using the same Git repository
3. Trigger hydration concurrently (parallel or closely timed syncs)
4. Observe hydration failure due to Git note push rejection

---

## Expected behavior

Hydration should not fail due to Git note conflicts, or the single-writer limitation should be clearly documented.

---

## Screenshots

<img width="1438" height="740" alt="Image" src="https://github.com/user-attachments/assets/0d355e34-e8a1-4e4f-9448-706f583645d4" />

---
## Logs
```│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:07Z" level=warning msg="Author email not available, using 'argo-cd@example.com'." branch=environment/ripple10/stag/proxy-server-next drySHA=d9a73ce87 │
│ 84ab9fc41b0e8599db6bc689fc209ce repo="https://github.com/ivosights/r10-k8s"                                                                                                                                               │
│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:07Z" level=info msg="git checkout --force environment/ripple10/stag/proxy-server" dir=/tmp/_commit-service/44c78b7d-c19c-4018-bbb3-e8bba334bc61 execI │
│ D=34f22                                                                                                                                                                                                                   │
│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:07Z" level=info msg=Trace args="[git checkout --force environment/ripple10/stag/proxy-server]" dir=/tmp/_commit-service/44c78b7d-c19c-4018-bbb3-e8bba │
│ 334bc61 operation_name="exec git" time_ms=4.0831859999999995                                                                                                                                                              │
│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:07Z" level=info msg="git checkout --force environment/ripple10/stag/proxy-server-next" dir=/tmp/_commit-service/44c78b7d-c19c-4018-bbb3-e8bba334bc61  │
│ execID=a459a                                                                                                                                                                                                              │
│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:07Z" level=info msg=Trace args="[git checkout --force environment/ripple10/stag/proxy-server-next]" dir=/tmp/_commit-service/44c78b7d-c19c-4018-bbb3- │
│ e8bba334bc61 operation_name="exec git" time_ms=2.912042                                                                                                                                                                   │
│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:07Z" level=info msg="git ls-files --error-unmatch apps/r10/core/proxy-server/overlay/stag/manifest.yaml" dir=/tmp/_commit-service/44c78b7d-c19c-4018- │
│ bbb3-e8bba334bc61 execID=b93b3                                                                                                                                                                                            │
│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:07Z" level=info msg=Trace args="[git ls-files --error-unmatch apps/r10/core/proxy-server/overlay/stag/manifest.yaml]" dir=/tmp/_commit-service/44c78b │
│ 7d-c19c-4018-bbb3-e8bba334bc61 operation_name="exec git" time_ms=2.851273                                                                                                                                                 │
│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:07Z" level=info msg="git diff --quiet -- apps/r10/core/proxy-server/overlay/stag/manifest.yaml" dir=/tmp/_commit-service/44c78b7d-c19c-4018-bbb3-e8bb │
│ a334bc61 execID=49d35                                                                                                                                                                                                     │
│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:07Z" level=info msg=Trace args="[git diff --quiet -- apps/r10/core/proxy-server/overlay/stag/manifest.yaml]" dir=/tmp/_commit-service/44c78b7d-c19c-4 │
│ 018-bbb3-e8bba334bc61 operation_name="exec git" time_ms=1.852965                                                                                                                                                          │
│ argo-cd-argocd-commit-server-cd56dc9d5-722kr time="2025-12-18T03:51:12Z" level=error msg="failed to handle commit request" branch=environment/ripple10/stag/proxy-server-next drySHA=d9a73ce8784ab9fc41b0e8599db6bc689fc2 │
│ 09ce error="failed to add commit note: failed to add commit note: failed to push note after retries: `git push origin refs/notes/hydrator.metadata` failed exit status 1: To https://github.com/ivosights/r10-k8s\n ! [re │
│ ected[]            refs/notes/hydrator.metadata -> refs/notes/hydrator.metadata (fetch first)\nerror: failed to push some refs to 'https://github.com/ivosights/r10-k8s'\nhint: Updates were rejected because the remote  │
│ contains work that you do not\nhint: have locally. This is usually caused by another repository pushing to\nhint: the same ref. If you want to integrate the remote changes, use\nhint: 'git pull' before pushing again.\ │
│ nhint: See the 'Note about fast-forwards' in 'git push --help' for details." output=                                                                                                                                      │
```

related
https://github.com/argoproj/argo-cd/pull/25700

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Fixes #25727

Use credentials when doing git fetches.

I confirmed that the e2e test failed before applying the fix and that it passes now.

### CODE REVIEW

File: test/e2e/fixture/fixture.go [hunk 1]
```diff
@@ -1034,6 +1034,12 @@ func EnsureCleanState(t *testing.T, opts ...TestOption) {
 			if err != nil {
 				return err
 			}
+			// Configure git to create files with more permissive permissions to avoid
+			// issues when cleaning up. By default git creates object files as 0444.
+			_, err = Run(repoDirectory(), "git", "config", "core.sharedRepository", "0666")
+			if err != nil {
+				return err
+			}
```
Comment (crenshaw-dev) [inline test/e2e/fixture/fixture.go:1042]: This is necessary because for the first time we have a test that writes changes _back_ to the git repo. If we don't add this, then the test fixture (running under a different user) can't clean up the temp dir.

**Review by leoluz — APPROVED** [review]
LGTM
