### PR TITLE
fix: create serviceaccount token for v1.24 clusters

### LINKED ISSUE #9422: Unable to add 1.24.0 Kubernetes cluster
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I tried to add a freshly created v1.24.0 Kubernetes cluster to argocd, I got timeout (see the **Logs** for details). The cluster can't be added.

Then I created a fresh v1.23.6 cluster, I can add it successfully.

I'm using kubeadm to create my Kubernetes clusters. The only difference between the two creation is one single parameter passed to `kubeadm init`, which is `--kubernetes-version`.

**Version**

```shell
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T01:46:59Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.3+07ac03
```

**Logs**

```
INFO[0001] ServiceAccount "argocd-manager" already exists in namespace "kube-system" 
INFO[0001] ClusterRole "argocd-manager-role" updated    
INFO[0002] ClusterRoleBinding "argocd-manager-role-binding" updated 
FATA[0032] Failed to wait for service account secret: timed out waiting for the condition
```

### PR DESCRIPTION
**Pull request by danielhelfand**
Closes #9422 

This pull request allows users to add v1.24 Kubernetes clusters to be managed by Argo CD by creating a service account secret with a bearer token. In previous versions of Kubernetes, this secret was created when serviceaccounts were created, but was removed in order to discourage the use of long lived tokens.

Two approaches were explored to address this:
1. Create the secret for serviceaccounts via Argo CD UX experiences
2. Use the TokenRequest API provided by Kubernetes to request tokens with configurable expiration

The decision was made to go with option 1 above since using the tokenrequest api would require moving the InstallClusterManagerRBAC func behind an API endpoint. This would need to be done in order to persist a TokenManager that would be injected into the cluster server upon start up to manage tokens created by the token request api. 

There may need to be a longer term discussion on adding this new endpoint/token manager to the cluster server so the current proposal would keep the use of secrets for storing bearer tokens for service accounts.

Due to k3s not having a stable 1.24 release available, testing for 1.24 clusters was conducted manually using kind. 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: util/clusterauth/clusterauth.go [hunk 1]
```diff
@@ -215,39 +215,85 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+				return existingSecret.Name, nil
 			}
 		}
-		return false, nil
-	})
+	}
+
+	secret := &corev1.Secret{
+		ObjectMeta: metav1.ObjectMeta{
+			GenerateName: ArgoCDManagerServiceAccount + "-token-",
```
[the remark this answers is not in the document]
Comment (danielhelfand) [reply util/clusterauth/clusterauth.go:284]: Yes, GenerateName will result in a random suffix to assure a unique name for each secret.

File: test/e2e/cluster_test.go [hunk 2]
```diff
@@ -184,8 +184,6 @@ func TestClusterURLInRestAPI(t *testing.T) {
 }
 
 func TestClusterDeleteDenied(t *testing.T) {
-	EnsureCleanState(t)
```
Comment (danielhelfand) [inline test/e2e/cluster_test.go:187]: This is handled by the Given helper func so no need to call.

File: util/clusterauth/clusterauth.go [hunk 3]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+		if len(serviceAccount.Secrets) == 0 {
+			return false, nil
 		}
-		// Scan all secrets looking for one of the correct type:
-		for _, oRef := range serviceAccount.Secrets {
-			var getErr error
-			secret, err = clientset.CoreV1().Secrets(ns).Get(context.Background(), oRef.Name, metav1.GetOptions{})
+		return true, nil
+	})
+	if errors.IsNotFound(err) {
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:270]: How about this?

```go
if serviceAccount == nil {
    if err != nil {
        return "", fmt.Errorf("failed to create service account token secret: %w", err)
    }
    log.Error("Unexpected nil service account '%s/%s' with no error returned", ns, sa)
    return "", fmt.Errorf("failed to create service account token secret: nil service account returned for '%s/%s' with no error", ns, sa)
}
```

Might be excessive, but I think it covers all the bases.

File: util/clusterauth/clusterauth.go [hunk 4]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+		return "", err
+	}
+
+	if len(serviceAccount.Secrets) != 0 {
+		for _, s := range serviceAccount.Secrets {
+			existingSecret, err := clientset.CoreV1().Secrets(ns).Get(context.Background(), s.Name, metav1.GetOptions{})
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:276]: Seems like we should set a timeout.

File: util/clusterauth/clusterauth.go [hunk 5]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+			GenerateName: serviceAccount.Name + "-token-",
+			Namespace:    serviceAccount.Namespace,
+			Annotations: map[string]string{
+				corev1.ServiceAccountNameKey: serviceAccount.Name,
+			},
+		},
+		Type: corev1.SecretTypeServiceAccountToken,
+	}
+
+	secret, err = clientset.CoreV1().Secrets(ns).Create(context.Background(), secret, metav1.CreateOptions{})
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:298]: Probably needs a timeout.

File: util/clusterauth/clusterauth.go [hunk 6]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+	log.Infof("Created bearer token secret for ServiceAccount %q", sa)
+	serviceAccount.Secrets = append(serviceAccount.Secrets,
+		corev1.ObjectReference{
+			Name:      secret.Name,
+			Namespace: secret.Namespace,
+		})
+
+	_, err = clientset.CoreV1().ServiceAccounts(ns).Update(context.Background(), serviceAccount, metav1.UpdateOptions{})
+	if err != nil {
+		return "", fmt.Errorf("Failed to update ServiceAccount %q with bearer token secret: %v", sa, err)
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:312]: s/Failed/failed, and maybe `%w` for the error

File: util/clusterauth/clusterauth.go [hunk 7]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+				corev1.ServiceAccountNameKey: serviceAccount.Name,
+			},
+		},
+		Type: corev1.SecretTypeServiceAccountToken,
+	}
+
+	secret, err = clientset.CoreV1().Secrets(ns).Create(context.Background(), secret, metav1.CreateOptions{})
 	if err != nil {
-		return "", fmt.Errorf("Failed to wait for service account secret: %v", err)
+		return "", fmt.Errorf("Failed to create secret for ServiceAccount %q: %v", sa, err)
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:300]: s/Failed/failed, and maybe %w for the error

File: util/clusterauth/clusterauth.go [hunk 8]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
-		return "", fmt.Errorf("Secret %q for service account %q did not have a token", secret.Name, serviceAccount)
+
+	log.Infof("Created bearer token secret for ServiceAccount %q", sa)
+	serviceAccount.Secrets = append(serviceAccount.Secrets,
+		corev1.ObjectReference{
+			Name:      secret.Name,
+			Namespace: secret.Namespace,
+		})
+
+	_, err = clientset.CoreV1().ServiceAccounts(ns).Update(context.Background(), serviceAccount, metav1.UpdateOptions{})
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:310]: Probably needs a timeout.

Also should we use a patch instead of an update, just in case something else about the secret has changed since we fetched it?

File: util/clusterauth/clusterauth.go [hunk 9]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
-// exists, iterate the secrets associated with it looking for one of type
-// kubernetes.io/service-account-token, and return it's token if found.
+// GetServiceAccountBearerToken determine if a ServiceAccount has a
+// bearer token sercet to use or if one should be created. It then
+// waits for the secret to have a bearer token if a secret needs to
+// be created and returns the token.
 func GetServiceAccountBearerToken(clientset kubernetes.Interface, ns string, sa string) (string, error) {
+	secretName, err := createServiceAccountTokenSecret(clientset, sa, ns)
+	if err != nil {
+		return "", err
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:226]: Let's wrap this error.

File: util/clusterauth/clusterauth.go [hunk 10]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+
 	var serviceAccount *corev1.ServiceAccount
 	var secret *corev1.Secret
-	var err error
 	err = wait.Poll(500*time.Millisecond, 30*time.Second, func() (bool, error) {
-		serviceAccount, err = clientset.CoreV1().ServiceAccounts(ns).Get(context.Background(), sa, metav1.GetOptions{})
+		secret, err = clientset.CoreV1().Secrets(ns).Get(context.Background(), secretName, metav1.GetOptions{})
 		if err != nil {
-			return false, err
+			return false, fmt.Errorf("Failed to retrieve secret %q: %v", secretName, err)
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:234]: s/Failed/failed, maybe use `%w` instead of `%v` for the error.

File: util/clusterauth/clusterauth.go [hunk 11]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+// already has a kubernetes.io/service-account-token secret associated
+// with it or creates one if the ServiceAccount doesn't have one. This
+// was added to help add k8s v1.24+ clusters.
+func createServiceAccountTokenSecret(clientset kubernetes.Interface, sa, ns string) (string, error) {
+	// Wait for sa to have secret, but don't wait too
+	// long for 1.24+ clusters
+	var serviceAccount *corev1.ServiceAccount
+	err := wait.Poll(500*time.Millisecond, 5*time.Second, func() (bool, error) {
+		var getErr error
+		serviceAccount, getErr = clientset.CoreV1().ServiceAccounts(ns).Get(context.Background(), sa, metav1.GetOptions{})
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:261]: Probably needs a timeout.

File: util/clusterauth/clusterauth.go [hunk 12]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+
+		_, ok := secret.Data["token"]
+		if !ok {
+			return false, fmt.Errorf("Secret %q for service account %q did not have a token", secret.Name, serviceAccount)
+		}
+
+		return true, nil
+	})
+	if err != nil {
+		return "", err
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:245]: Let's wrap the error, in case it's not one that we already wrapped - I believe `wait.Poll` will throw its own error on timeout.

File: util/clusterauth/clusterauth.go [hunk 13]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
 }
 
-// GetServiceAccountBearerToken will attempt to get the provided service account until it
-// exists, iterate the secrets associated with it looking for one of type
-// kubernetes.io/service-account-token, and return it's token if found.
+// GetServiceAccountBearerToken determine if a ServiceAccount has a
+// bearer token sercet to use or if one should be created. It then
+// waits for the secret to have a bearer token if a secret needs to
+// be created and returns the token.
 func GetServiceAccountBearerToken(clientset kubernetes.Interface, ns string, sa string) (string, error) {
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:223]: Will this return the base64-encoded secret, or raw? Might be worth documenting.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
All the nitpicks.  :-)

I think the only substantial things are:
1. timeouts for requests
2. using patch instead of update for the sa

File: util/clusterauth/clusterauth.go (hunk 4 above)
Comment (danielhelfand) [reply util/clusterauth/clusterauth.go:276]: Any timeout amount make sense to you?

File: util/clusterauth/clusterauth.go [hunk 14]
```diff
@@ -215,39 +216,103 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+	if err != nil {
+		return "", err
+	}
+
 	var serviceAccount *corev1.ServiceAccount
 	var secret *corev1.Secret
-	var err error
 	err = wait.Poll(500*time.Millisecond, 30*time.Second, func() (bool, error) {
-		serviceAccount, err = clientset.CoreV1().ServiceAccounts(ns).Get(context.Background(), sa, metav1.GetOptions{})
+		secret, err = clientset.CoreV1().Secrets(ns).Get(context.Background(), secretName, metav1.GetOptions{})
```
[the remark this answers is not in the document]
Comment (danielhelfand) [reply util/clusterauth/clusterauth.go:232]: Agreed, any recommendation on timeout/interval? 500ms/30s was how it was originally implemented before this change.

File: util/clusterauth/clusterauth.go (hunk 8 above)
Comment (danielhelfand) [reply util/clusterauth/clusterauth.go]: Changed to patch. Still need to update with timeout.

File: util/clusterauth/clusterauth.go [hunk 15]
```diff
@@ -215,39 +217,111 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
 		if err != nil {
-			return false, err
+			return false, fmt.Errorf("failed to retrieve secret %q: %v", secretName, err)
+		}
+
+		_, ok := secret.Data["token"]
+		if !ok {
+			return false, fmt.Errorf("secret %q for serviceaccount %q did not have a token", secret.Name, sa)
+		}
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:240]: Reading this again... at this point, are we waiting for k8s to populate the `token` field? If so, seems like we should return `false, nil`. The way the anonymous function is currently written, `wait.Poll` will never retry - it will either exit on success (`return true, nil`) or exit on error (`return false, err`).

File: util/clusterauth/clusterauth.go [hunk 16]
```diff
@@ -215,39 +217,111 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
 		}
-		// Scan all secrets looking for one of the correct type:
-		for _, oRef := range serviceAccount.Secrets {
-			var getErr error
-			secret, err = clientset.CoreV1().Secrets(ns).Get(context.Background(), oRef.Name, metav1.GetOptions{})
+		log.Errorf("Unexpected nil serviceaccount '%s/%s' with no error returned", ns, sa)
+		return "", fmt.Errorf("failed to create serviceaccount token secret: nil serviceaccount returned for '%s/%s' with no error", ns, sa)
+	}
+
+	if len(serviceAccount.Secrets) != 0 {
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:278]: I think the `len` check is unnecessary - if `Secrets` has no items, the loop will just be a no-op.

File: util/clusterauth/clusterauth.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (crenshaw-dev) [reply util/clusterauth/clusterauth.go:232]: How about something like this:

```go
ctx, cancel := context.WithTimeout(context.Background(), 10 * time.Second)
defer cancel()
secret, err = clientset.CoreV1().Secrets(ns).Get(ctx, secretName, metav1.GetOptions{})
```

10s should be enough for even the farthest-edge cluster, and it ensures we get in at least four attempts even if the first three all time out. 

(`wait.Poll` always calls the function one more time after `timeout` is reached. It's weird, and I didn't believe it until I tested it.)

```go
// this will always take > 61 sec to run (two func calls, and one initial interval)
	_ = wait.Poll(1 * time.Second, 10 * time.Second, func() (done bool, err error) {
		time.Sleep(30 * time.Second)
		return false, nil
	})
```

File: util/clusterauth/clusterauth.go [hunk 17]
```diff
@@ -215,39 +217,111 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
 func GetServiceAccountBearerToken(clientset kubernetes.Interface, ns string, sa string) (string, error) {
-	var serviceAccount *corev1.ServiceAccount
+	secretName, err := createServiceAccountTokenSecret(clientset, sa, ns)
+	if err != nil {
+		return "", err
+	}
+
 	var secret *corev1.Secret
-	var err error
 	err = wait.Poll(500*time.Millisecond, 30*time.Second, func() (bool, error) {
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:231]: Is there any reason not to switch to `wait.PollImmediate`? `wait.Poll` will always wait one interval before calling the func, and it seems like an unnecessary half-second on the happy path.

File: util/clusterauth/clusterauth.go (hunk 11 above)
Comment (crenshaw-dev) [reply util/clusterauth/clusterauth.go:261]: How about 10s? Absolute worst-case scenario, the first call takes 9.999s to return a non-error code, `wait.Poll` calls it once more, and the second call takes 10s. The 10s will let far-away clusters respond, but in 99.9% of cases, low latency will mean we quit trying after ~5s.

File: util/clusterauth/clusterauth.go (hunk 4 above)
Comment (crenshaw-dev) [reply util/clusterauth/clusterauth.go:280]: How about an outside-the-loop context with a `30s` timeout and an inside-the-loop context with a 10s timeout?

If for some absurd reason there are 100 secrets, the outer context will keep us from waiting forever.

If there's high latency, inner context will make sure we give a nice amount of time to get the secret.

If there's high latency _and_ 3+ secrets _and_ the target secret isn't in the first 3... well that's just a bummer.

File: util/clusterauth/clusterauth.go (hunk 5 above)
Comment (crenshaw-dev) [reply util/clusterauth/clusterauth.go:302]: How bout the ol' 10s. Maybe we need a constant.  :-P

File: util/clusterauth/clusterauth.go [hunk 18]
```diff
@@ -215,39 +217,111 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+	patch, err := json.Marshal(serviceAccount)
 	if err != nil {
-		return "", fmt.Errorf("Failed to wait for service account secret: %v", err)
+		return "", fmt.Errorf("failed marshaling patch for serviceaccount %s: %w", sa, err)
 	}
-	token, ok := secret.Data["token"]
-	if !ok {
-		return "", fmt.Errorf("Secret %q for service account %q did not have a token", secret.Name, serviceAccount)
+
+	_, err = clientset.CoreV1().ServiceAccounts(ns).Patch(context.Background(), serviceAccount.Name, types.MergePatchType, patch, metav1.PatchOptions{})
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:319]: Another 10s timeout?  :-)

File: util/clusterauth/clusterauth.go [hunk 19]
```diff
@@ -215,39 +217,111 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+
+// createServiceAccountTokenSecret will check if a ServiceAccount
+// already has a kubernetes.io/service-account-token secret associated
+// with it or creates one if the ServiceAccount doesn't have one. This
+// was added to help add k8s v1.24+ clusters.
+func createServiceAccountTokenSecret(clientset kubernetes.Interface, sa, ns string) (string, error) {
+	// Wait for sa to have secret, but don't wait too
+	// long for 1.24+ clusters
+	var serviceAccount *corev1.ServiceAccount
+	err := wait.Poll(500*time.Millisecond, 5*time.Second, func() (bool, error) {
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:259]: Would PollImmediate be alright?

File: util/clusterauth/clusterauth.go [hunk 20]
```diff
@@ -215,39 +217,111 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+	}
+
+	return string(secret.Data["token"]), nil
+}
+
+// createServiceAccountTokenSecret will check if a ServiceAccount
+// already has a kubernetes.io/service-account-token secret associated
+// with it or creates one if the ServiceAccount doesn't have one. This
+// was added to help add k8s v1.24+ clusters.
+func createServiceAccountTokenSecret(clientset kubernetes.Interface, sa, ns string) (string, error) {
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:255]: nit: maybe name it `getOrCreateServiceAccountTokenSecret`? because it is impossible for a function name to be too long. `itIsImpossibleForAFunctionNameToBeTooLong(true, facts)`.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: util/clusterauth/clusterauth.go [hunk 21]
```diff
@@ -215,39 +218,121 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+		return true, nil
+	})
+	if err != nil {
+		return "", fmt.Errorf("failed to get token for serviceaccount %q: %w", sa, err)
+	}
+
+	_, ok := secret.Data["token"]
+	if !ok {
+		return "", fmt.Errorf("secret %q for serviceaccount %q did not have a token", secret.Name, sa)
+	}
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:248]: Do we want this inside the poll loop? As it's currently written, the poll will only ever run once, because there is no "still waiting" condition. I think that this check can go inside, and we can just return `false, nil` to indicate that the poll logic should retry.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: util/clusterauth/clusterauth.go [hunk 22]
```diff
@@ -215,39 +218,121 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+
+	outerCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
+	defer cancel()
+	for _, s := range serviceAccount.Secrets {
+		select {
+		case <-outerCtx.Done():
+			// break loop if taking longer than 30s
+			break
+		default:
+			innerCtx, cancel := context.WithTimeout(context.Background(), ClientGoRequestTimeout)
```
[the remark this answers is not in the document]
Comment (danielhelfand) [reply util/clusterauth/clusterauth.go]: Thanks, didn't realize was that simple! Added.

File: util/clusterauth/clusterauth.go (hunk 21 above)
Comment (danielhelfand) [reply util/clusterauth/clusterauth.go]: Originally doing this was causing panics when I ran the test locally. This is due to my vscode setup where running tests were being timed out after 30s. The downside of moving this into the poll loop is the clusterauth tests now take 60s to run: `ok  	github.com/argoproj/argo-cd/v2/util/clusterauth	65.522s	coverage: 74.7% of statements`.

This is from tests that were looking at how this would behave in a scenario where the token key never populates. It's working in CI, but might be not so great running locally.

Comment (crenshaw-dev) [reply util/clusterauth/clusterauth.go]: Could we parameterize the timeout so it can be overridden for tests?

Comment (danielhelfand) [reply util/clusterauth/clusterauth.go]: Yeah, I can add to InstallClusterManagerRBAC/GetServiceAccountBearerToken.

Comment (danielhelfand) [reply util/clusterauth/clusterauth.go]: Added a 5 second timeout for tests.

**Review by crenshaw-dev — APPROVED** [review]
LGTM! Can I get another review from @alexmt, @jannfis, or @leoluz?

File: util/clusterauth/clusterauth.go [hunk 23]
```diff
@@ -212,42 +216,119 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+		if err != nil {
+			return "", fmt.Errorf("failed to create serviceaccount token secret: %w", err)
+		}
+		log.Errorf("Unexpected nil serviceaccount '%s/%s' with no error returned", ns, sa)
+		return "", fmt.Errorf("failed to create serviceaccount token secret: nil serviceaccount returned for '%s/%s' with no error", ns, sa)
+	}
+
+	outerCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
+	defer cancel()
+	for _, s := range serviceAccount.Secrets {
```
Comment (crenshaw-dev) [inline util/clusterauth/clusterauth.go:286]: According to one [article](https://itnext.io/big-change-in-k8s-1-24-about-serviceaccounts-and-their-secrets-4b909a4af4e0), the `Secrets` field won't be populated with the manually-created secret reference. So we should try to get the secret by annotation before creating a new one.

Should we add an Argo CD-internal annotation so it's easier to identify the Secret we created?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: util/clusterauth/clusterauth.go (hunk 23 above)
Comment (crenshaw-dev) [reply util/clusterauth/clusterauth.go:286]: Yep, that makes sense to me! Logic's starting to get a little complex, but seems necessary.

Comment (danielhelfand) [reply util/clusterauth/clusterauth.go:286]: Actually, I am not sure if the custom annotation is needed. Unfortunately, you can't query by annotations, just labels. So we would need to pull back all secrets regardless. FieldSelector also does not work with secret type, so it might just be that we would need to iterate over all secrets in namespace to find the correct type/annotation.

Comment (leoluz) [reply util/clusterauth/clusterauth.go:286]: I think we can simplify a bit and make it a bit more performatic. 
I'm thinking about having the logic such as:
1. Retrieve the provided service account (SA)
2. Inspect for existing secrets linked in the SA
2.1. If there are no secrets create a SA type secret and assign it to the SA
2.2. If there are secrets but none are of type SA token create create a SA type secret and assign it to the SA
3. return the SA assigned token

This way we don't need to retrieve all secrets in the namespace nor have to define specific annotations to search for. Do you think this simplified version would work or I am missing something?

**Review by leoluz — CHANGES_REQUESTED** [review]

File: util/clusterauth/clusterauth.go (hunk 23 above)
Comment (crenshaw-dev) [reply util/clusterauth/clusterauth.go:286]: I misunderstood. By "assign it to the SA," you mean patch the ServiceAccount `secrets` field to add the secret we created.

Comment (leoluz) [reply util/clusterauth/clusterauth.go:286]: Correct. My suggestion is basically automating the steps that are now removed from 1.24 as a short term solution.
The longer term solution is approach #2 (in the PR description) leveraging the TokenRequest API.

@danielhelfand pls let me know if you are in sync with the suggestion and agree with it. I'm happy to jump on a call to clarify things if necessary.

File: util/clusterauth/clusterauth.go [hunk 24]
```diff
@@ -212,42 +216,119 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string, namesp
...
+		if getErr != nil {
+			return false, fmt.Errorf("failed to get serviceaccount %q: %w", sa, getErr)
 		}
-		return false, nil
+		if len(serviceAccount.Secrets) == 0 {
+			return false, nil
+		}
+		return true, nil
 	})
+	if serviceAccount == nil {
```
Comment (danielhelfand) [inline util/clusterauth/clusterauth.go:276]: TODO: Move err check on line 277 out of this loop.

File: util/clusterauth/clusterauth.go (hunk 23 above)
Comment (danielhelfand) [reply util/clusterauth/clusterauth.go:285]: So recapping here:
* @leoluz and I reviewed, and think the current implementation is satisfying the cases mentioned above
* The main impact of this will be helping argocd cli users add clusters via `argocd cluster add CONTEXTNAME`
* The longer term goal here will be to migrate to the TokenRequest API but is out of scope for this pr
* Using annotations would be difficult in this case, and it is probably reasonable to ask users to add tokens for their serviceaccount in advance. Worst case is this will result in a duplicate token secret as we currently are always checking in advance if the serviceaccount has secrets.

File: util/clusterauth/clusterauth.go (hunk 24 above)
Comment (danielhelfand) [reply util/clusterauth/clusterauth.go:275]: @leoluz I think we still need to keep the current approach here in order to prevent the timeout from wait.PollImmediate(). Adding if err != nil leads to tests failing from the timeout. Let me know if I misunderstood.

File: util/clusterauth/clusterauth.go [hunk 25]
```diff
@@ -21,6 +23,8 @@ const (
 	ArgoCDManagerServiceAccount     = "argocd-manager"
 	ArgoCDManagerClusterRole        = "argocd-manager-role"
 	ArgoCDManagerClusterRoleBinding = "argocd-manager-role-binding"
+	ClientGoRequestTimeout          = 10 * time.Second
+	BearerTokenTimeout              = 30 * time.Second
```
[the remark this answers is not in the document]
Comment (danielhelfand) [reply util/clusterauth/clusterauth.go]: Moved to `common.go`. Let me know if names make sense.

File: util/clusterauth/clusterauth.go (hunk 24 above)
Comment (leoluz) [reply util/clusterauth/clusterauth.go:275]: Strange. 
What if the code is like:
```go
if err != nil {
	return "", fmt.Errorf("failed to create serviceaccount token secret: %w", err)
}
if serviceAccount == nil {
    log.Errorf("Unexpected nil serviceaccount '%s/%s' with no error returned", ns, sa)
    return "", fmt.Errorf("failed to create serviceaccount token secret: nil serviceaccount returned for '%s/%s' with no error", ns, sa)
}
```

Comment (danielhelfand) [reply util/clusterauth/clusterauth.go:275]: I think the problem is just the timeout from wait.PollImmediate will prevent this from moving on to the secret creation if err != nil comes immediately after.

Comment (leoluz) [reply util/clusterauth/clusterauth.go:275]: @danielhelfand you should be able to check the timeout error by the returned error type:
https://github.com/kubernetes/apimachinery/blob/v0.24.1/pkg/util/wait/wait.go#L205:5
It would be something like:
```golang
if err != nil && err != wait.ErrWaitTimeout {
	return "", fmt.Errorf("failed to create serviceaccount token secret: %w", err)
}
if serviceAccount == nil {
    log.Errorf("Unexpected nil serviceaccount '%s/%s' with no error returned", ns, sa)
    return "", fmt.Errorf("failed to create serviceaccount token secret: nil serviceaccount returned for '%s/%s' with no error", ns, sa)
}
```

Comment (danielhelfand) [reply util/clusterauth/clusterauth.go:278]: Thanks! I have gone ahead and added.

**Review by leoluz — APPROVED** [review]
LGTM
Thank you Daniel!

**Review by crenshaw-dev — APPROVED** [review]
Tested adding a 1.24 docker-desktop cluster from a 1.20 minikube cluster. lgtm. Thanks so much!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto 2.4.

**Comment by rishabh625** [comment]
Hi @crenshaw-dev will this be backported to 2.3 too?

**Comment by crenshaw-dev** [comment]
Good question... I'm not opposed to it, if anyone needs it. Want to ask in #argo-contributors on CNCF Slack?

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.3 for 2.3.7.
