### PR TITLE
fix(ui): consistent resource menu across views (#18060)

### LINKED ISSUE #18060: Delete UI for Pod resource is inconsistent
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

https://github.com/argoproj/argo-cd/assets/47184027/1e35ed9d-ecf1-4fac-97f8-1ca98ed80fa3

**Describe the bug**

**To Reproduce**

1. Open an Application
2. Find a pod
3. Click on the Delete pod action
4. Observe the popup
5. Close
6. Enable/Disable the Resource Grouping
3. Click on the Delete pod action
4. Observe the popup

**Expected behavior**

The popup for Pod deletion should always be the same.

The checkbox in the popup has no effect. If it is not checked and the user click OK, the API to delete the resource is performed. The checkbox should be removed.
image

**Version**

v2.11.0+1cffa15 (cd.apps.argoproj.io)

### PR DESCRIPTION
**Pull request by agaudreault**
Closes https://github.com/argoproj/argo-cd/issues/18060 

Changes

Non-visible changes:
- Logs will not be displayed if the permission is not given on the application
- Exec will not be displayed if the permission is not given on the application
- Delete resource CLI help had incorrect documentation

| Description | Before | After |
| -------- | -------- | ------- |
| Consistent Menu Items: Tree view | image | image |
| Consistent Menu Items: Tree view (Grouped) | image | image |
| Consistent Menu Items: Pods view | image | image |
| Consistent Menu Items: Network view | image | image |
| Consistent Menu Items: Network view (Grouped) | image | image |
| Consistent Menu Items: List view | image | image |
| Delete popup broken Force Delete checkbox display | image | image |
| List view display with multiple kinds | image | image |
| List view display single kind with same parent | image | image |
| Only have sync action on managed resources | image |  image |
| Highlight the deleted resource type | image | image |
| Add Icon to Applciation list actions | image | image |
| Application delete menu in Red | image | image |

**See it in action**

https://github.com/argoproj/argo-cd/assets/47184027/deee9574-3010-4622-8176-e7d2dff6c31d

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by wanghong230** [comment]
Amazing details! Unfortunately, I am not entitled to review the UI code, so I cannot just approve the PR.

File: ui/src/app/applications/components/utils.tsx [hunk 1]
```diff
@@ -119,8 +119,8 @@ export async function deleteApplication(appName: string, appNamespace: string, a
                 }
             }
         },
-        {name: 'argo-icon-warning', color: 'warning'},
-        'yellow',
+        {name: 'argo-icon-warning', color: 'failed'},
+        'red',
```
Comment (ishitasequeira) [inline ui/src/app/applications/components/utils.tsx:123]: Any specific reason to make this `failed`? Considering this is a warning to the user, we should continue with `warning` itself.

**Review by ishitasequeira — COMMENTED** [review]
I tested the feature, and the overall changes look good!!

File: ui/src/app/applications/components/utils.tsx (hunk 1 above)
Comment (agaudreault) [reply ui/src/app/applications/components/utils.tsx:123]: The goal is to have the "self" application delete popup in red to make it significantly different from deleting another resource.

**Review by todaywasawesome — APPROVED** [review]
Looks great!

File: ui/src/app/applications/components/utils.tsx [hunk 2]
```diff
@@ -296,31 +296,31 @@ export function findChildPod(node: appModels.ResourceNode, tree: appModels.Appli
     });
 }
 
-export const deletePodAction = async (pod: appModels.Pod, appContext: AppContext, appName: string, appNamespace: string) => {
-    appContext.apis.popup.prompt(
+const deletePodAction = async (ctx: ContextApis, pod: appModels.ResourceNode, app: appModels.Application) => {
+    ctx.popup.prompt(
         'Delete pod',
```
Comment (keithchong) [inline ui/src/app/applications/components/utils.tsx:301]: Should this delete pod popup have the same icon and yellow color as the other delete resource popups, just for consistency?

Comment (agaudreault) [reply ui/src/app/applications/components/utils.tsx:301]: No. The goal of this popup is to ask for confirmation like a "normal" action. The reasoning behind this is that managed pods are likely to be recreated automatically. Deleting a pod should not cause an outage of an application as Pod deletion is expected in Kubernetes. 

If you compare it to a ReplicaSet or Deployment for instance, the impact of deleting such resources could create outages, even if they end up being recreated, hence the difference in the pupup reflecting the risk level.

**Review by ishitasequeira — APPROVED** [review]
Looks nice!!

File: ui/src/app/applications/components/utils.tsx (hunk 2 above)
Comment (keithchong) [reply ui/src/app/applications/components/utils.tsx:301]: I see your point.  The reason is more of consistency in presentation in general for any Delete action and it's less about the resulting outcome and severity of the action.  For example, the user could have inadvertently or accidentally selected this menu item action.  This accidental selection is one of the reasons why a warning popup is needed.

For those other more detrimental outcomes, forcing the user to type in the resource/app name was added.  

If we find that this is still not sufficient, then perhaps the popup should be more of a Caution or Stop indicator? (It's no longer a Warning).

Comment (todaywasawesome) [reply ui/src/app/applications/components/utils.tsx:301]: From the meeting today the consensus is this isn't a show stopper and we should go ahead and merge but it would be great to get a different icon so that it's more accessible.
