### PR TITLE
fix: unset --plugin-env should return OK when not found

### LINKED ISSUE #6325: Make `argocd app unset` idempotent
# Summary

Currently CLI exit with fatal error when unsetting plugin env variable that does not exist.

```
+ argocd app unset ambassador --plugin-env HELM_CHART --plugin-env HELMFILE_CHART
+ tee
time="2021-05-26T08:09:05Z" level=fatal msg="unable to find env variable with key \"HELM_CHART\" for plugin \"helmfile\""
```

# Motivation

We may argue the app is already in the desired state so API/CLI should return OK. It helps make this action idempotent, thus more friendly to retry.

# Proposal

Return OK from API when trying unset an env variable that does not exist.

### PR DESCRIPTION
**Pull request by yujunz**
Closes #6325

### CODE REVIEW

File: cmd/argocd/commands/app.go [hunk 1]
```diff
@@ -673,9 +673,10 @@ func NewApplicationUnsetCommand(clientOpts *argocdclient.ClientOptions) *cobra.C
 				}
 				for _, env := range pluginEnvs {
```
Comment (alexmt) [inline cmd/argocd/commands/app.go:674]: This might be a breaking change for some users. For backward compatibility please add `--force` CLI flag. If it is set to true then unset should act idempotently.

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you @yujunz ! Can you please address one comment.

File: cmd/argocd/commands/app.go (hunk 1 above)
Comment (yujunz) [reply cmd/argocd/commands/app.go:674]: Per my comments in https://github.com/argoproj/argo-cd/issues/6325#issuecomment-859528827

> Reviewed related code. It turns out only unset --plugin-env will return errors on not found while the others do return OK.

> I think it is better to keep a consistent behavior. What do you think? @alexmt

I am considering current `unset APPNAME --plugin-env`'s behavior as a bug and needs to be corrected. Do we want to keep backward compatibility of such feature too?

There are also some other error handling in the `unset` command. Should the `--force` flag override all or just plugin env not found?

Comment (alexmt) [reply cmd/argocd/commands/app.go:674]: Thanks for checking other flags behavior. I agree with you, perhaps `--plugin-env` validation was added by mistake.

**Review by alexmt — APPROVED** [review]
