### PR TITLE
Issue #1940 - Wait for CRD creation during sync process

### LINKED ISSUE #1940: Argo CD sync might fail to create if app contains CRD and instance of the same CRD
**Describe the bug**
Argo CD sync might fail to create if app contains CRD and instance of the same CRD. Although Argo CD creates resources in the right order( CRD first then everything else ) sync still might fail because Kubernetes needs some time after CRD creation.

**To Reproduce**
Existing e2e test `TestCRDs` is flaky. Controller has logs which prove that CRD got successfully created but creation of the instance of the same CRD fails:

```
INFO[0084] Applying resource ClusterDummy/cluster-dummy-crd-instance in cluster: https://default-8993bb99-b78b-496c-b705-f99154b61c88:6443, namespace: argocd-e2e-test-cr-ds-yteju 
DEBU[0084] {"apiVersion":"argoproj.io/v1alpha1","kind":"ClusterDummy","metadata":{"labels":{"app.kubernetes.io/instance":"test-cr-ds"},"name":"cluster-dummy-crd-instance","namespace":"argocd-e2e-test-cr-ds-yteju"}} 
INFO[0084] kubectl --kubeconfig /dev/shm/443155372 -f - apply -n argocd-e2e-test-cr-ds-yteju  dir= execID=g8B4v
DEBU[0085] Start watch Dummy.argoproj.io on https://kubernetes.default.svc 
DEBU[0085]                                               duration=499.710968ms execID=g8B4v
ERRO[0085] `kubectl --kubeconfig /dev/shm/443155372 -f - apply -n argocd-e2e-test-cr-ds-yteju` failed exit status 1: error: unable to recognize "STDIN": no matches for kind "ClusterDummy" in version "argoproj.io/v1alpha1"  execID=g8B4v
INFO[0085] adding resource result, status: 'SyncFailed', phase: 'Failed', message: '`kubectl --kubeconfig /dev/shm/443155372 -f - apply -n argocd-e2e-test-cr-ds-yteju` failed exit status 1: error: no matches for kind "ClusterDummy" in version "argoproj.io/v1alpha1"'  application=test-cr-ds kind=ClusterDummy name=cluster-dummy-crd-instance namespace=argocd-e2e-test-cr-ds-yteju phase=Sync
```

**Version***: v1.2.0

### PR DESCRIPTION
**Pull request by alexmt**
Closes #1940

### CODE REVIEW

File: controller/sync.go [hunk 1]
```diff
@@ -502,13 +519,32 @@ func (sc *syncContext) setOperationPhase(phase v1alpha1.OperationPhase, message
 	sc.opState.Message = message
 }
 
+// ensureCRDReady waits until specified CRD is ready (established condition is true).
```
Comment (jessesuen) [inline controller/sync.go]: Mention that this is best effort.

**Review by jessesuen — APPROVED** [review]

File: controller/sync.go (hunk 1 above)
Comment (alexmt) [reply controller/sync.go]: done
