### PR TITLE
fix: password reset requirements

### LINKED ISSUE #5787: Manual password reset process does not enforce password complexity requirements
# Summary
Argo CD requires username/password authentication, such as that for the default administrator account, be set via kubectl. This account can then be logged into later with the CLI or Web UI. However, due to password reset conventions, there are no password complexity requirements.
In the event a user selects a password which is considered inefficient by today’s standards, an attacker may be able to gain access to their account. This is a scenario which would be otherwise easily preventable if password setting/resetting methodology was implemented first-party.

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal
Implement first-party password setting functionality that enforces reasonable password complexity requirements.

How do you think this should be implemented?

### PR DESCRIPTION
**Pull request by mayzhang2000**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

fixes: #5787

### CODE REVIEW

File: cmd/argocd/commands/account.go [hunk 1]
```diff
@@ -80,14 +82,27 @@ func NewAccountUpdatePasswordCommand(clientOpts *argocdclient.ClientOptions) *co
...
+			//Need to validate password complexity with regular expression
+			settingsConn, settingsIf, err := acdClient.NewSettingsClient()
+			defer io.Close(settingsConn)
+			errors.CheckError(err)
+			argoSettings, err := settingsIf.Get(context.Background(), &settingspkg.SettingsQuery{})
+			errors.CheckError(err)
+			passwordPattern := argoSettings.PasswordPattern
+			var validPasswordRegexp = regexp.MustCompile(passwordPattern)
+			if !validPasswordRegexp.Match([]byte(newPassword)) {
+				err := fmt.Errorf("New password does not match requirements.")
```
Comment (alexmt) [inline cmd/argocd/commands/account.go:94]: Please add regex expression to the error text. E.g. 

```
fmt.Errorf("New password must match the following regex expression: %s", passwordPattern)
```

File: cmd/argocd/commands/account.go [hunk 2]
```diff
@@ -80,14 +82,27 @@ func NewAccountUpdatePasswordCommand(clientOpts *argocdclient.ClientOptions) *co
...
 
+			//Need to validate password complexity with regular expression
+			settingsConn, settingsIf, err := acdClient.NewSettingsClient()
+			defer io.Close(settingsConn)
+			errors.CheckError(err)
+			argoSettings, err := settingsIf.Get(context.Background(), &settingspkg.SettingsQuery{})
+			errors.CheckError(err)
+			passwordPattern := argoSettings.PasswordPattern
+			var validPasswordRegexp = regexp.MustCompile(passwordPattern)
+			if !validPasswordRegexp.Match([]byte(newPassword)) {
```
Comment (alexmt) [inline cmd/argocd/commands/account.go:93]: The password must be validated on server side, not CLI. Please move the validation logic to https://github.com/argoproj/argo-cd/blob/1d3d03f5d3f62755ae90730121e75124c88340fe/server/account/account.go#L79

Note: the `passwordPattern` field in settings API is still required. UI will use it later to perform client side validation.

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you @mayzhang2000 . Added couple comments.

Please also document config map settings in  https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml

File: cmd/argocd/commands/account.go [hunk 3]
```diff
@@ -80,14 +82,27 @@ func NewAccountUpdatePasswordCommand(clientOpts *argocdclient.ClientOptions) *co
...
 			}
 
+			//Need to validate password complexity with regular expression
+			settingsConn, settingsIf, err := acdClient.NewSettingsClient()
+			defer io.Close(settingsConn)
+			errors.CheckError(err)
+			argoSettings, err := settingsIf.Get(context.Background(), &settingspkg.SettingsQuery{})
+			errors.CheckError(err)
+			passwordPattern := argoSettings.PasswordPattern
+			var validPasswordRegexp = regexp.MustCompile(passwordPattern)
```
Comment (alexmt) [inline cmd/argocd/commands/account.go:92]: If the user configures an invalid regex then this line will panic. Instead we need to return error message

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
Awesome. It works great!
