### PR TITLE
fix(in-cluster): do not allow the cluster to be used when disabled

### LINKED ISSUE #21207: Disabling in-cluster does not prevent the usage of in-cluster
**Describe the bug**

When disabling the in-cluster via `cluster.inClusterEnabled: 'false'`, the cluster is properly not showing from the Argo CD cluster list. However, Argo CD can still sync existing applications using this cluster and create resources on the in-cluster if it has k8s permissions via RoleBindings. Furthermore, applications can still be created using https://kubernetes.default.svc cluster url.

See the missing validation on `inClusterEnabled` usage in https://github.com/agaudreault/argo-cd/blob/0074bb4b486312e552f96f325f26148b3bbabbc0/util/db/cluster.go#L228-L230. 

Another impact of this is that the controller will start to watch all resources on the local cluster when `inClusterEnabled=false` and no "in-cluster" secret exist, because the liveStateCache calls `c.db.GetCluster`, which returns the local cluster with default configuration. The cluster watches also do not handle the in-cluster secret to be disabled, so it will never be removed from the watches.

The usage of variable `KubernetesInternalAPIServerAddr` should be analyzed and probably the settings should be checked too when necessary in other code paths.

**To Reproduce**

1. Create an Application using https://kubernetes.default.svc
2. Update the configMap to use `cluster.inClusterEnabled: 'false'` and deleted the in-cluster secret.
3. Restart controller
4. Sync the app or create a new app

**Expected behavior**

- An error should be returned that "cluster `https://kubernetes.default.svc` is disabled" when an Application is created/updated.
- An error should be returned when the application is reconciled and/or synced.

**Version**

Latest master (2.13.1)

### PR DESCRIPTION
**Pull request by agaudreault**
Closes https://github.com/argoproj/argo-cd/issues/21207

The ApplicationSet code is still using the in-cluster, even when disabled. However, the apps will fail in Argo CD, which is expected. See https://github.com/argoproj/argo-cd/issues/10473

Depends on https://github.com/argoproj/argo-cd/pull/21225

Existing applications:
image

New applications creation (API):
image

### CODE REVIEW

**Review by rumstead — CHANGES_REQUESTED** [review]
Could you fix the linting errors? It seems that there is a race condition being caught. The stack traces look like a similar problem I fixed before - https://github.com/argoproj/argo-cd/pull/20805/files

**Review by terrytangyuan — COMMENTED** [review]
Good catch. Thanks!

**Comment by agaudreault** [comment]
Cherry pick in 2.13 will require https://github.com/argoproj/argo-cd/pull/20805 and https://github.com/argoproj/argo-cd/pull/21225

**Review by ishitasequeira — COMMENTED** [review]
The changes LGTM
@agaudreault can you fix the CI failures?

**Comment by agaudreault** [comment]
@ishitasequeira @terrytangyuan @rumstead  lint/test fixed. Let's wait for discussion on the issue to know if we should cherry-pick.

Thanks for the review!

File: applicationset/controllers/applicationset_controller_test.go [hunk 1]
```diff
@@ -41,6 +41,39 @@ import (
...
+			Namespace: "argocd",
+			Labels: map[string]string{
+				"app.kubernetes.io/part-of": "argocd",
+			},
+		},
+		Data: map[string]string{},
+	}
+
+	objects := append([]runtime.Object{}, emptyArgoCDConfigMap, argoCDSecret)
+	kubeclientset := kubefake.NewSimpleClientset(objects...)
```
Comment (crenshaw-dev) [inline applicationset/controllers/applicationset_controller_test.go:73]: NewSimpleClientset is deprecated, you can use NewClientset. Should work fine as a drop-in replacement.

File: applicationset/controllers/applicationset_controller_test.go [hunk 2]
```diff
@@ -1320,8 +1353,10 @@ func TestRemoveFinalizerOnInvalidDestination_DestinationTypes(t *testing.T) {
 				},
 			}
 
-			objects := append([]runtime.Object{}, secret)
-			kubeclientset := kubefake.NewSimpleClientset(objects...)
+			kubeclientset := getDefaultTestClientSet()
+			err := kubeclientset.Tracker().Add(secret)
```
Comment (crenshaw-dev) [inline applicationset/controllers/applicationset_controller_test.go:1357]: Instead of accessing the tracker like this, maybe just parameterize `getDefaultTestClientSet` to accept additional objects? I've seen that pattern in other tests.

File: util/db/cluster.go [hunk 3]
```diff
@@ -142,11 +142,19 @@ func (db *db) WatchClusters(ctx context.Context,
...
 	if err != nil {
 		return err
 	}
-	handleAddEvent(localCls)
+
+	localCls := db.getLocalCluster()
+	if argoSettings.InClusterEnabled {
+		localCls, err = db.GetCluster(ctx, appv1.KubernetesInternalAPIServerAddr)
+		if err != nil {
+			return err
```
Comment (crenshaw-dev) [inline util/db/cluster.go:154]: Wrap the error?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
lgtm besides a few nitpicks. One final suggestion would be to change the tests to tabular tests for readability. Will go with your decision on whether that's worth the time.

**Review by rumstead — APPROVED** [review]
Overall LGTM

**Review by crenshaw-dev — APPROVED** [review]

**Comment by agaudreault** [comment]
Need https://github.com/argoproj/argo-cd/pull/21615 to fix an incorrect behavior making the new e2e fail
