### PR TITLE
fix(ui, rbac): project-roles

### LINKED ISSUE #12852: UI: Support setting rbac for repository under project
# Summary

PR #7008 support rbac policy repository under project but UI dosn't support.
Therefore, I want to make some small changes in component `project-role-policies-edit` to support the feature.

# Motivation
Just like ISSUE #2251

e.g. Add a project role and Allow the role view repositories under the project

image

It will generate policy like this
```
p, proj:default:test-role, repositories, get, default/*, allow
```

# Proposal
I update the component `project-role-policies-edit.tsx` and change some css styles to fit the screen.

### PR DESCRIPTION
**Pull request by blakepettersson**
This PR builds upon the PR done in #12853. The only real difference to the prior PR is that this adds support for `applicationsets` as well as all other project-scoped resources (`clusters`, `applications`, `repositories` etc etc). In order to ensure that future rbac policies are in sync I wanted to make use of the project-scoped map in `rbacpolicies`, but since that led to circular build dependency issues I needed to move that to the `rbac` package, which makes this PR look more substantial than it actually is.

Otherwise as the previous PR, this adds support for displaying/adding resources other than `applications` to the project roles UI.

Closes #12852

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by andrii-korotkov-verkada — APPROVED** [review]

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -2350,7 +2352,7 @@ type ResourceActionParam struct {
 	Default string `json:"default,omitempty" protobuf:"bytes,4,opt,name=default"`
 }
 
-// TODO: refactor to use rbacpolicy.ActionGet, rbacpolicy.ActionCreate, without import cycle
+// TODO: refactor to use rbac.ActionGet, rbac.ActionCreate, without import cycle
```
Comment (nitishfy) [inline pkg/apis/application/v1alpha1/types.go:2355]:
```suggestion
// TODO: refactor to use rbac.ActionGet, rbac.ActionCreate, without import cycle
```
Since you've solved the circular dependency issue, can you verify if this is still needs to be done?

**Review by nitishfy — COMMENTED** [review]
Left a comment, PTAL.

File: pkg/apis/application/v1alpha1/types.go (hunk 1 above)
Comment (blakepettersson) [reply pkg/apis/application/v1alpha1/types.go:2355]: Yup good point. I'll remove that comment.

Comment (blakepettersson) [reply pkg/apis/application/v1alpha1/types.go:2355]: Actually, looking at this this is still valid. I guess the comment can be amended to 
```suggestion
// TODO: refactor to use rbac.ActionGet, rbac.ActionCreate
```

**Review by wanghong230 — APPROVED** [review]

**Review by gdsoumya — APPROVED** [review]

**Review by nitishfy — APPROVED** [review]
LGTM!

**Comment by nitishfy** [comment]
@blakepettersson You'd be required to manually raise a cherry pick PR for 2.13 & 2.14. The automatic cherry-pick bot is having troubles right now.

**Comment by blakepettersson** [comment]
@nitishfy yeah the 2.0 -> 3.0 migration is making things a bit of a PITA atm.
