### PR TITLE
fix: Unknown sync operation state on app list page

### LINKED ISSUE #11599: Unknown sync operation state on app list page
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Application list page incorrectly displays `unknown` sync operation  state

**To Reproduce**

* Create any application and sync it once
* Navigate to application list page

**Expected behavior**

Correct sync operation state should be shown 

**Screenshots**

image

**Version**

```shell
v2.6.0 unreleased
```

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>
Closes https://github.com/argoproj/argo-cd/issues/11599

PR ensures that `API /appilication?fields=...` does not return empty values for nil fields.

### CODE REVIEW

**Comment by ashutosh16** [comment]
Fix works for me. thx!

**Review by ashutosh16 — APPROVED** [review]
LGTM

**Review by gdsoumya — APPROVED** [review]

File: pkg/apiclient/application/forwarder_overwrite_test.go [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+	require.NoError(t, err)
+	resMap, ok := res.(map[string]interface{})
+	require.True(t, ok)
+
+	items, ok := resMap["items"].([]map[string]interface{})
+	require.True(t, ok)
+	item, err := toMap(items[0])
+	require.NoError(t, err)
+
+	val, ok, err := unstructured.NestedString(item, "operation", "sync", "revision")
```
Comment (alexef) [inline pkg/apiclient/application/forwarder_overwrite_test.go:43]: what is this test checking? operation.sync.revision is not part of the appFields

**Comment by alexef** [comment]
Thanks @alexmt 🙏 

Unrelated question, could `status.operationState.startedAt` / `status.operationState.finishedAt` be added to the response? I know the original change was done for performance reasons, and I wonder how expensive two additional fields in the response would be. 

I am interested in these fields as a way to detect and display recently changed application (as either a Sort option to the Application List view, or as a sidebar extension).

File: pkg/apiclient/application/forwarder_overwrite_test.go [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+	"encoding/json"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
+
+	"github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1"
+)
+
+func toMap(obj interface{}) (map[string]interface{}, error) {
```
Comment (ashutosh16) [inline pkg/apiclient/application/forwarder_overwrite_test.go:13]: Can `toMap` method be moved to utils? Often we need to convert to interface to map

**Review by jessesuen — APPROVED** [review]

File: pkg/apiclient/application/forwarder_overwrite_test.go (hunk 1 above)
Comment (alexmt) [reply pkg/apiclient/application/forwarder_overwrite_test.go:29]: The `operation.sync.revision` is return since `operation.sync` is available in list of `requestable` fields. So test verifying that `operation.sync` is returned correctly.

**Comment by alexmt** [comment]
@alexef is won't be too expensive. JSON serialization was consuming a lot of CPU but adding two small fields into response won't make a big difference. 

Just to save Github Action minutes added  support for `status.operationState.startedAt` and `status.operationState.finishedAt` in the same PR

**Review by ashutosh16 — APPROVED** [review]

**Comment by RomanBats** [comment]
Tried '4c673e99f1c07238b348e06d8b49a8f6b576c38ef79bcc235990660a1ea77332' nightly build and it works great!
