### PR TITLE
Shows chart name in apps tiles and apps table pages. Closes #2726

### LINKED ISSUE #2726: App list does not show chart for Helm app
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

* Install the 'sealed-secrets' chart.
* Expect to see the chart name, but see empty path instead.

**Expected behavior**

You should see chart.

**Screenshots**

Screen Shot 2019-11-15 at 3 27 47 PM

**Version**

```shell
v1.3.0
```

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Closes #2726

Needs back-porting to v1.3

## Screenshots

Screen Shot 2019-11-15 at 4 53 30 PM
Screen Shot 2019-11-15 at 5 02 30 PM

### CODE REVIEW

File: ui/src/app/applications/components/applications-list/applications-table.tsx [hunk 1]
```diff
@@ -1,25 +1,13 @@
...
 import * as models from '../../../shared/models';
 import {ApplicationURLs} from '../application-urls';
 import * as AppUtils from '../utils';
 import {OperationState} from '../utils';
-
-const GitUrlParse = require('git-url-parse');
-
 require('./applications-table.scss');
 
-function shortRepo(repo: string) {
```
Comment (alexec) [inline ui/src/app/applications/components/applications-list/applications-table.tsx]: this nulls helm urls, and only bare shortens them, so lets get rid of it

**Comment by alexec** [comment]
@alexmt this is a bug introduced in v1.3 and therefore will need to be back ported.

**Review by alexmt — APPROVED** [review]
