### PR TITLE
fix: Health status bar button does not re-render properly. Fixes #8569

### LINKED ISSUE #8569: UI: Application Health Status bar toggle is broken
The Application health status bar toggle (the ruler icon to the right of the search bar on the Applications List page) is broken; clicking this button once hides the status bar as intended, but clicking again does not re-show the status bar. 

Using Safari v15.1

### PR DESCRIPTION
**Pull request by terrytangyuan**
Fixes #8569. The health status bar on the applications page can only be clicked once and then it will be hidden. However, when I click it again, the status bar does not appear, which is unexpected.

It turns out that the state of this should be persisted in order to re-render properly.

Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by rbreeze — CHANGES_REQUESTED** [review]
This will work, but the current implementation uses local storage to set this as a view preference - this way when you refresh the page, or quit your browser and come back, the status bar will be shown or hidden according to how it was before you left. 

I think there's a bug with the local storage update; this solution will fix the behavior for toggling, but removes the benefit of saving this as a view pref

File: ui/src/app/applications/components/applications-list/applications-list.tsx [hunk 1]
```diff
@@ -293,6 +293,7 @@ export const ApplicationsList = (props: RouteComponentProps<{}>) => {
     const [isAppCreatePending, setAppCreatePending] = React.useState(false);
     const loaderRef = React.useRef<DataLoader>();
     const {List, Summary, Tiles} = AppsListViewKey;
+    const [isStatusBarShown, showStatusBar] = React.useState(true);
```
Comment (rbreeze) [inline ui/src/app/applications/components/applications-list/applications-list.tsx:296]: Actually, now that I'm thinking about this, if you make this change to your PR: 

```suggestion
    const [isStatusBarShown, showStatusBar] = React.useState(healthBarPrefs.showHealthStatusBar);
```

this may solve the problem and still have the local storage benefit

Comment (rbreeze) [reply ui/src/app/applications/components/applications-list/applications-list.tsx:296]: You'll have to move the declaration of `healthBarPrefs` on line 363 to above

```ts
const healthBarPrefs = pref.statusBarView || ({} as HealthStatusBarPreferences);
```

**Comment by terrytangyuan** [comment]
@rbreeze I just realized that the issue is because we were using a local variable that was not updated. I've verified that this fixed the issue and refreshing persists the state correctly.

**Review by rbreeze — APPROVED** [review]
LGTM
