### PR TITLE
fix: CMP manifest generation fails with ENHANCE_YOUR_CALM if over 40s

### LINKED ISSUE #9924: gRPC upgrade in 2.4.x causes ENHANCE_YOUR_CALM error for gRPC streams taking longer than ~40s
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading to 2.4.x, our CMP sidecars were mysteriously failing 100% of the time with an `ENHANCE_YOUR_CALM` error from the cmp-server to the repo-server.

Looking into gRPC documentation and everything I could find on the internet, the error itself is triggered when the client sends pings too early. We upgraded from gRPC v1.15 to v1.45 in https://github.com/argoproj/argo-cd/pull/8929. And in v1.35, gRPC merged this PR that adds throttling: https://github.com/grpc/grpc/pull/23313

It seems others ran into the same issue here: https://github.com/grpc/grpc-go/issues/5161

So far I've only reproduced this on CMPs.

It seems that we set the client timeout rate to 10 seconds, which is too low now that there is ping throttling. After four pings, the client is forcefully disconnected and the RPC cancelled. Settings have to be configured on the servers now as well.

https://github.com/argoproj/argo-cd/blob/10324a62162cf5c80ac8babd586ae370baa39f9a/util/grpc/grpc.go#L90

**To Reproduce**

Create a CMP that takes longer than ~40 seconds, i.e.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      generate:
        command: [sh, -c, 'sleep 45; echo "{\"kind\": \"ConfigMap\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"$ARGOCD_APP_NAME\", \"namespace\": \"$ARGOCD_APP_NAMESPACE\", \"annotations\": {\"Foo\": \"$FOO\", \"KubeVersion\": \"$KUBE_VERSION\", \"KubeApiVersion\": \"$KUBE_API_VERSIONS\",\"Bar\": \"baz\"}}}"']
      discover:
        find:
          command:
            [sh, -c, "date >> /tmp/plugin-discover-has-run; echo hello; exit 0"]
```

Attempt to run any refresh, sync, create and it will fail with the ENHANCE_YOUR_CALM error.

**Expected behavior**

gRPC request doesn't fail with this error

**Version**

2.4.x

**Logs**

```
rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: "too_many_pings"
```

### PR DESCRIPTION
**Pull request by notfromstatefarm**
Signed-off-by: notfromstatefarm <86763948+notfromstatefarm@users.noreply.github.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Fixes #9924

### CODE REVIEW

File: cmpserver/server.go [hunk 1]
```diff
@@ -61,6 +64,11 @@ func NewServer(initConstants plugin.CMPServerInitConstants) (*ArgoCDCMPServer, e
 		grpc.StreamInterceptor(grpc_middleware.ChainStreamServer(streamInterceptors...)),
 		grpc.MaxRecvMsgSize(apiclient.MaxGRPCMessageSize),
 		grpc.MaxSendMsgSize(apiclient.MaxGRPCMessageSize),
+		grpc.KeepaliveEnforcementPolicy(
+			keepalive.EnforcementPolicy{
+				MinTime: (time.Duration(10) * time.Second),
+			},
+		),
```
Comment (crenshaw-dev) [inline cmpserver/server.go:71]: Would this be a good candidate for a common.go constant?

File: util/grpc/grpc.go [hunk 2]
```diff
@@ -87,7 +88,7 @@ func BlockingDial(ctx context.Context, network, address string, creds credential
 			grpc.FailOnNonTempDialError(true),
 			grpc.WithContextDialer(dialer),
 			grpc.WithTransportCredentials(insecure.NewCredentials()), // we are handling TLS, so tell grpc not to
-			grpc.WithKeepaliveParams(keepalive.ClientParameters{Time: 10 * time.Second}),
+			grpc.WithKeepaliveParams(keepalive.ClientParameters{Time: 20 * time.Second}),
```
Comment (crenshaw-dev) [inline util/grpc/grpc.go:91]: Question because I'm not too bright: why is this 2x the keepalive enforcement policy minimum? 

If the minimum ends up in commons.go, should we just use `2 * commons.GRPCKeepAliveEnforcementMinimum` here?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Organization nitpicks

File: cmpserver/server.go (hunk 1 above)
Comment (notfromstatefarm) [reply cmpserver/server.go:71]: Yup, I believe so - especially since it needs to match in multiple places.

File: util/grpc/grpc.go (hunk 2 above)
Comment (crenshaw-dev) [reply util/grpc/grpc.go:91]: Makes sense! Want to add something about that as a comment? Just so future readers understand more easily.

**Comment by notfromstatefarm** [comment]
force pushed to retrigger a (I think) flaky E2E test

**Review by crenshaw-dev — APPROVED** [review]
lgtm, thanks!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.4 for 2.4.6.
