### PR TITLE
fix: Log an error when invalid token exists (#4156)

### LINKED ISSUE #4156: API requests break when invalid account token exists in secret
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

If an invalid token for a local user exists in `argocd-secret`, the API will refuse to process any request with an error message similar to:

```
FATA[0002] rpc error: code = Unknown desc = invalid character 'e' looking for beginning of value
```

**To Reproduce**

Set an invalid token for an existing local user in `argocd-secret`, i.e.

```
accounts.foobar.tokens: someinvalidvalue
```

Then try to use any command in the CLI.

**Expected behavior**

All users except the one with invalid token should be able to continue working with the API.

**Version**

```shell
argocd-server: v1.7.0+ee57ded
  BuildDate: 2020-08-24T23:48:05Z
  GitCommit: ee57ded16f7095498ed84b561aa41ef574cd7a2c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8

```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by chetan-rns**
Instead of returning an error for invalid token and thereby breaking API requests for all users, print the error to the logs.

Fixes: #4156

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to USERS.md.
* [X] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

File: util/settings/accounts.go [hunk 1]
```diff
@@ -307,7 +307,7 @@ func parseAccounts(secret *v1.Secret, cm *v1.ConfigMap) (map[string]Account, err
 			account.Tokens = make([]Token, 0)
 			if string(tokensStr) != "" {
 				if err := json.Unmarshal(tokensStr, &account.Tokens); err != nil {
-					return nil, err
+					log.Errorf("Invalid token '%s' found in secret '%s'", string(tokensStr), secret.Name)
```
Comment (alexmt) [inline util/settings/accounts.go:310]: The token might be invalid because it has trailing whitespace characters. In this case, we might log information that contains a valid token which is a security issue. Just to be safe lets print the only account name:

```
log.Errorf("Account '%s' has invalid token in secret '%s'", name, secret.Name)
```

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
LGTM. Thank you!
