### PR TITLE
fix(appset): Matrix Generator Override not Working for Booleans (#14498)

### LINKED ISSUE #14498: AppSet Matrix Generator Override not Working for Booleans
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using a matrix generator combining two git generators with go template activated, we experienced strange behavior regarding booleans. If you define a boolean and set it to `true` in one repository and like to override it with `false` in another repository, it is simply not working and the boolean stays `true`.

We're using this pattern as a standard way to define a default value in one repository and override it with stage-specific values in another repository. So this bug is pretty critical for us, especially because it produces unexpected behavior which is hard to indentify.

**To Reproduce**

Although we experienced the issue with the git generator, I was able to narrow it down to the following minimal example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements: # these values (should) take precedence over the values in the second generator
                - expectBooleanFalse: false
                  expectBooleanTrue: true
                  expectStringFalse: "false"
                  expectStringTrue: "true"
          - list:
              elements:
                - expectBooleanFalse: true
                  expectBooleanTrue: false
                  expectStringFalse: "true"
                  expectStringTrue: "false"
  goTemplate: true
  template:
    ...
    spec:
      source:
        ...
        helm:
          values: |
            {{ `{{ . | mustToPrettyJson }}` }}
        ...
```

Which generates the following application:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  ...
  source:
    helm:
      values: |
        {
          "expectBooleanFalse": true, # <= unexpected behavior
          "expectBooleanTrue": true,
          "expectStringFalse": "false",
          "expectStringTrue": "true"
        }
    ...
```

As you can see, the string-typed value is overridden with `"false"` correctly. Inspite of this, the boolean-typed value states `false` unexpectedly.

**Expected behavior**

An application is generated with the Helm value `expectBooleanFalse` set to `false`, thus:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  ...
  source:
    helm:
      values: |
        {
          "expectBooleanFalse": false,
          "expectBooleanTrue": true,
          "expectStringFalse": "false",
          "expectStringTrue": "true"
        }
    ...
```

**Screenshots**

n/a

**Version**

```json
{
    "Version": "v2.7.7+4650bb2.dirty",
    "BuildDate": "2023-07-05T19:42:32Z",
    "GitCommit": "4650bb2817c3c81405f40cf77e93ef2b5fb275fb",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

n/a

**Possible Solution**

We noticed the same behavior in Helm templates using the `merge` function. Our solution in Helm is to use the `mergeOverwrite` function instead.

Diving into the implementation of the matrix generator, you can see the `mergo.Merge(&dst, src)` function is used: [applicationset/generators/matrix.go#L62-L67](https://github.com/argoproj/argo-cd/blob/v2.7.7/applicationset/generators/matrix.go#L62-L67). Luckily, [mergo provides a flag](https://github.com/imdario/mergo#usage), to enable override functionality. Using `mergo.Merge(&dst, src, mergo.WithOverride)` instead of the implementation above, should fix the issue.

### PR DESCRIPTION
**Pull request by alexbde**
Using a matrix generator combining two git generators with go template activated, we experienced the following behavior regarding booleans: if you define a boolean and set it to `true` in one repository and like to override it with `false` in another repository, it is simply not working and the boolean stays `true`. See #14498 for extended bug description & example.

This PR fixes the merge behavior of the matrix generator to always override values regardless of its value. This aligns the behavior with the merge generator which also uses the same flag while merging parameters: [applicationset/generators/merge.go#L80](https://github.com/argoproj/argo-cd/blob/v2.7.7/applicationset/generators/merge.go#L80).

Fixes #14498.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] ~I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.~ n/a
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] ~Optional. My organization is added to USERS.md.~
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] ~My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.~ n/a - bug fix
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

File: applicationset/generators/matrix.go [hunk 1]
```diff
@@ -61,11 +61,11 @@ func (m *MatrixGenerator) GenerateParams(appSetGenerator *argoprojiov1alpha1.App
...
 				tmp := map[string]interface{}{}
-				if err := mergo.Merge(&tmp, a); err != nil {
-					return nil, fmt.Errorf("failed to merge params from the first generator in the matrix generator with temp map: %w", err)
+				if err := mergo.Merge(&tmp, b, mergo.WithOverride); err != nil {
+					return nil, fmt.Errorf("failed to merge params from the second generator in the matrix generator with temp map: %w", err)
 				}
-				if err := mergo.Merge(&tmp, b); err != nil {
-					return nil, fmt.Errorf("failed to merge params from the first generator in the matrix generator with the second: %w", err)
+				if err := mergo.Merge(&tmp, a, mergo.WithOverride); err != nil {
+					return nil, fmt.Errorf("failed to merge params from the second generator in the matrix generator with the first: %w", err)
```
Comment (crenshaw-dev) [inline applicationset/generators/matrix.go:68]: I think it's more intuitive to have `b` take precedence over `a`. I believe that more closely matches the non-gotemplate behavior.

Comment (crenshaw-dev) [reply applicationset/generators/matrix.go:68]: Gotcha, okay, we can worry about precedence on this issue. https://github.com/argoproj/argo-cd/issues/14556 Let's stay as close as possible to current behavior.

Comment (alexbde) [reply applicationset/generators/matrix.go:68]: Let me add that I switched positions of `a` and `b` in this code to ensure _the same merge order_ as before. I tested in our local Argo and was surprised that I needed to do this. But it is actually the same with `merge` and `mergeOverwrite` functions in Helm: you need to change the parameter order to ensure the same behaviour (see https://masterminds.github.io/sprig/dicts.html#merge-mustmerge).

**Review by ishitasequeira — APPROVED** [review]
LGTM!
@alexbde you would need to push an empty commit to re-trigger the e2e tests. The e2e failure is because of a flaky test.

**Comment by alexbde** [comment]
@crenshaw-dev @ishitasequeira Thank you for pointing out, all green now :)

**Review by ishitasequeira — APPROVED** [review]

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Comment by alexbde** [comment]
@ishitasequeira @crenshaw-dev I tried to implement another test case, using a nested matrix generator. It failed because of my lack of Go skills 🙈  If you like to add it, here's the test I ran in our local Argo:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - booleanFalse: false
                  booleanTrue: true
                  stringFirst: "1st"
                  stringFirstOnly: "1st"
          - matrix:
              generators:
                - list:
                    elements:
                      - booleanFalse: true
                        booleanTrue: false
                        stringFirst: "2nd"
                        stringSecond: "2nd"
                        stringSecondOnly: "2nd"
                - list:
                    elements:
                      - booleanFalse: true
                        booleanTrue: false
                        stringFirst: "3rd"
                        stringSecond: "3rd"
                        stringThird: "3rd"
                        stringThirdOnly: "3rd"
  goTemplate: true
  template:
    ...
```

expected:

```yaml
- booleanFalse: false
  booleanTrue: true
  stringFirst: "1st"
  stringFirstOnly: "1st"
  stringSecond: "2nd"
  stringSecondOnly: "2nd"
  stringThird: "3rd"
  stringThirdOnly: "3rd"
```

**Comment by alexbde** [comment]
Hey @crenshaw-dev, do you still think we might get this into the 2.8 release? This would be great 🚀

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
@alexbde , would you mind rebasing the PR with master?

**Comment by alexbde** [comment]
> @alexbde , would you mind rebasing the PR with master?

@ishitasequeira is merging master fine or should I git rebase master?

**Comment by alexbde** [comment]
> @alexbde , would you mind rebasing the PR with master?

Done

**Review by ishitasequeira — APPROVED** [review]
