### PR TITLE
fix: allow pipes to be present in git username

### LINKED ISSUE #15949: Revision metadata breaks with `|` in commit author name
Hello, I put `|` symbol in my git  `user.name`.
I broke the response from revision metadata api of argo server
`/api/v1/applications/${reponame}/revisions/${commitid}/metadata?appNamespace=${namespace}`

So that it returns
```
{"author":"PSy ","date":"1970-01-01T00:00:00Z","message":"1689860699|fix: do not use deploy in app label"}
```
This is cause by https://github.com/argoproj/argo-cd/blob/f8f9ae9accd413b417be1d188418f2b3b7c25e63/util/git/client.go#L632C38-L632C63

resp. the git show format expression `--format="%an <%ae>|%at|%B"` that is then split by `|`.

I suggest to rewrite the method without such formatting.

### PR DESCRIPTION
**Pull request by blakepettersson**
Pipe symbol `|` can potentially appear in the username. Fixes #15949.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: util/git/client.go [hunk 1]
```diff
@@ -735,27 +735,33 @@ func (m *nativeGitClient) CommitSHA() (string, error) {
 	return strings.TrimSpace(out), nil
 }
 
-// returns the meta-data for the commit
+// RevisionMetadata returns the metadata for the commit
 func (m *nativeGitClient) RevisionMetadata(revision string) (*RevisionMetadata, error) {
-	out, err := m.runCmd("show", "-s", "--format=%an <%ae>|%at|%B", revision)
+	author, err := m.runCmd("show", "-s", "--format=%an", revision)
```
Comment (jannfis) [inline util/git/client.go:740]: Have you considered using `%n` (newline) to separate tokens in the string instead of running multiple commands, i.e. `%an <%ae>%n%at%n%B`? I'd believe that a newline isn't allowed in email or name.

Comment (blakepettersson) [reply util/git/client.go:740]: I did actually - #15952 had that implementation. I was concerned that there was a potential for a newline in the name, but now that I looked closer that doesn't seem to be the case. That's what I get for doing this late at night...

Comment (blakepettersson) [reply util/git/client.go]: I set it back to the original impl from @dosmanak, PTAL

Comment (dosmanak) [reply util/git/client.go]: I just tested it and git binary really strips the newline inside the author name.
```
git commit --author=$'first\nsecond <dosmanak@test>' -am "resetme"
git show -s --format="%an%x00%at"| xxd
00000000: 6669 7273 7473 6563 6f6e 6400 3137 3236  firstsecond.1726
00000010: 3932 3532 3737 0a                        925277.
```

File: util/git/client_test.go [hunk 2]
```diff
@@ -296,3 +297,43 @@ func Test_IsRevisionPresent(t *testing.T) {
...
+
+	p := path.Join(client.Root(), "README")
+	f, err := os.Create(p)
+	require.NoError(t, err)
+	_, err = f.WriteString("Hello.")
+	require.NoError(t, err)
+	err = f.Close()
+	require.NoError(t, err)
+
+	err = runCmd(client.Root(), "git", "config", "user.name", `FooBar ||| something`)
```
Comment (dosmanak) [inline util/git/client_test.go:317]:
```suggestion
	err = runCmd(client.Root(), "git", "config", "user.name", "FooBar ||| something\nelse")
```

File: util/git/client.go (hunk 1 above)
Comment (dosmanak) [reply util/git/client.go]: I just tested it and git binary really strips the newline inside the author name.
```
$ git commit --author=$'first\nsecond <dosmanak@test>' -am "resetme"
$ git show -s --format="%an%x00%at"| xxd
00000000: 6669 7273 7473 6563 6f6e 6400 3137 3236  firstsecond.1726
00000010: 3932 3532 3737 0a                        925277.
```

**Review by nitishfy — APPROVED** [review]
LGTM!

File: util/git/client.go [hunk 3]
```diff
@@ -737,11 +737,11 @@ func (m *nativeGitClient) CommitSHA() (string, error) {
 
 // returns the meta-data for the commit
 func (m *nativeGitClient) RevisionMetadata(revision string) (*RevisionMetadata, error) {
-	out, err := m.runCmd("show", "-s", "--format=%an <%ae>|%at|%B", revision)
+	out, err := m.runCmd("show", "-s", "--format=%an <%ae>%n%at%n%B", revision)
```
Comment (crenshaw-dev) [inline util/git/client.go:740]: May be a silly question, but... are newlines allowed in a git username? 0_o

Comment (blakepettersson) [reply util/git/client.go:740]: That doesn't seem to be the case, we debated that [here](https://github.com/argoproj/argo-cd/pull/20040#discussion_r1769545321)

Also added a [test](https://github.com/argoproj/argo-cd/pull/20040/files#diff-a7b72b46e16649a80020d533dac6c2c4ed5bbc2dc72852f43a44e01037c48b55R317) for that, and it seems like Git strips the newlines from the [username](https://github.com/argoproj/argo-cd/pull/20040/files#diff-a7b72b46e16649a80020d533dac6c2c4ed5bbc2dc72852f43a44e01037c48b55R334).

**Review by crenshaw-dev — APPROVED** [review]
