### PR TITLE
fix: ensure compatibility of kubeversion.version with what helm reeturns

### LINKED ISSUE #26330: [Helm] ArgoCD-provided .Capabilities.KubeVersion.Version is inconsistent with Helm
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

If you deploy an Helm Application that uses `.Capabilities.KubeVersion.Version` in its chart's template, the result is inconsistent if the user does not explicitly specify `helm.kubeVersion`.

- Helm (tested with `v3.19.5`) outputs a format like `v1.34.0`.
- ArgoCD (tested with `v3.3.0`) outputs a format like `v1.34`.

This is making the installation of [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) fail because it relies on the full semver to pull the `kubectl` image (see https://github.com/prometheus-community/helm-charts/blob/a3300192e5ff039d59db6209811f21fda9033b80/charts/kube-prometheus-stack/charts/crds/templates/upgrade/job.yaml#L78).

Other charts that rely on reading the full value (major.minor.patch) may fail too.

**To Reproduce**

1. Produce a minimal chart with this template:
   ```yaml
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: debug-cm
   data:
     direct: "{{ .Capabilities.KubeVersion.Version }}"
   ```
2. Render it with Helm
   ```sh
   helm template debug-chart ./debug-chart --debug
   ```
3. Deploy an ArgoCD application that uses the chart
   ```yaml
   apiVersion: argoproj.io/v1alpha1
   kind: Application
   metadata:
     name: debug-app
     namespace: argocd
   spec:
     destination:
       server: https://kubernetes.default.svc
       namespace: default
     project: default
   
     sources:
       - repoURL: https://github.com/example/example.git
         path: debug-chart
         targetRevision: "main"
   
   ```

**Expected behavior**

Helm and ArgoCD shall have the same behavior.

**Version**

```shell
argocd: v3.2.3+unknown
  BuildDate: 2025-12-29T04:22:33Z
  GitCommit:
  GitTreeState:
  GitTag: 3.2.3
  GoVersion: go1.25.5 X:nodwarf5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v3.3.0
  BuildDate: 2026-02-02T07:28:36Z
  GitCommit: fd6b7d5b3cba5e7aa7ad400b0fb905a81018a77b
  GitTreeState: clean
  GitTag: v3.3.0
  GoVersion: go1.25.5
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.8.0 2025-11-09T14:39:49Z
  Helm Version: v3.19.4+g7cfb6e4
  Kubectl Version: v0.34.0
  Jsonnet Version: v0.21.0
```

**Possible cause**
This might happen because the value that ArgoCD passes to `helm template --kube-version <value>` is gotten from this cached entry, which explicitly prints just `<major>.<minor>`:

https://github.com/argoproj/argo-cd/blob/76162a93105a5cf01a10a3faa8203621b487a0c3/util/db/cluster.go#L38-L55

NOTE: I've tried to track the source value down, but I'm not very familiar with the code.

### PR DESCRIPTION
**Pull request by ppapapetrou76**
closes https://github.com/argoproj/argo-cd/issues/26330

I used the example chart and app in the original issue to reproduce the problem.
Before the fix the manifest was rendered like this 

```
apiVersion: v1
data:
  direct: v1.31
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: debug-app:/ConfigMap:argocd/debug-cm
  name: debug-cm
  namespace: argocd
```

after the fix it renders as follows. 

```
apiVersion: v1
data:
  direct: v1.31.5
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: debug-app:/ConfigMap:argocd/debug-cm
  name: debug-cm
  namespace: argocd
```

I think we need to backport this in the supported versions ( 3.3 and 3.2 ) 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: gitops-engine/pkg/utils/kube/ctl.go [hunk 1]
```diff
@@ -349,7 +350,12 @@ func (k *KubectlCmd) GetServerVersion(config *rest.Config) (string, error) {
 	if err != nil {
 		return "", fmt.Errorf("failed to get server version: %w", err)
 	}
-	return fmt.Sprintf("%s.%s", v.Major, v.Minor), nil
+
+	ver, err := version.ParseGeneric(v.GitVersion)
+	if err != nil {
+		return "", fmt.Errorf("failed to parse server version: %w", err)
+	}
+	return "v" + ver.String(), nil
```
Comment (nitishfy) [inline gitops-engine/pkg/utils/kube/ctl.go:361]:
```suggestion
     // ParseGeneric removes the leading "v" and any vendor-specific suffix
	 // (e.g. "-gke.100", "-eks-123", "+k3s1"). Helm expects a semver-like
	 // Kubernetes version with a "v" prefix for capability checks, so we
	// normalize the version to "v<major>.<minor>.<patch>".
	return "v" + ver.String(), nil
```

We need to add a clear comment for the normalization done here. Reading the [code](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/version/version.go#L46-L60) for how parsing is done, the vendor-suffixes are removed. I don’t expect removing vendor suffixes to cause issues, since feature detection depends on the numeric version only, but the intent should be made explicit in the code.

File: gitops-engine/pkg/utils/kube/ctl_test.go [hunk 2]
```diff
@@ -69,6 +73,80 @@ func TestConvertToVersion(t *testing.T) {
...
+			GitVersion: "v1.30.0",
+		}, nil)
+		defer fakeServer.Close()
+		config := mockConfig(fakeServer.URL)
+		serverVersion, err := kubectlCmd().GetServerVersion(config)
+		require.NoError(t, err)
+
+		assert.Equal(t, "v1.30.0", serverVersion)
+		assert.NotContains(t, serverVersion, "+", "Should not contain the '+' from Minor field")
+	})
```
Comment (nitishfy) [inline gitops-engine/pkg/utils/kube/ctl_test.go:139]: All the tests looks good. However, let's add a test for removal of vendor-specific suffixes since this is one of the case normalization targets.

**Review by nitishfy — DISMISSED** [review]
Left a couple of comments, PTAL.

File: gitops-engine/pkg/utils/kube/ctl_test.go (hunk 2 above)
Comment (ppapapetrou76) [reply gitops-engine/pkg/utils/kube/ctl_test.go:139]: @nitishfy I believe you are talking about this [one ](https://github.com/argoproj/argo-cd/pull/26469/changes#diff-beca1b7600e3419a6a11094252790982124853135494861b276158db2e8aecc2R95) - it is already part of the PR

**Comment by ppapapetrou76** [comment]
Thanks for review @nitishfy - I added a comment explaining how `ParseGeneric` works and what we want to return back 
Also the test you asked for already exists in the PR

Feel free to review again when you have some time

**Comment by ppapapetrou76** [comment]
@nitishfy can you please have another look or unblock the PR if you don't have time for review? 🙏🏾

**Review by dudinea — COMMENTED** [review]
The patch IMHO is good, the info.Minor and info.Major fields are deprecated and we should migrate to use the GitVersion field even with no relation to the parent issue. 

But I see that we're changing the server behavior depending on cluster version: 

Previously we were forgiving and accepted any values that were in the struct. 

Now, the server will just panic if the local cluster has some GitVersion string that cannot be parsed by ParseGeneric() 
and we'll refuse to use any remote cluster with such an unparseable GitVersion.

I wonder if it is ok to make such a change?

The GitVersion is just a string that is passed at compilation time when compiling API server. If someone recompiled api server with incompatible version string, or if it is some product that tries to imitate kubernetes api and provides an incompatible string -  now ArgoCD just will refuse to work.

I think that in such cases we should just print warning into the log and continue

**Comment by ppapapetrou76** [comment]
> The patch IMHO is good, the info.Minor and info.Major fields are deprecated and we should migrate to use the GitVersion field even with no relation to the parent issue.
> 
> But I see that we're changing the server behavior depending on cluster version:
> 
> Previously we were forgiving and accepted any values that were in the struct.
> 
> Now, the server will just panic if the local cluster has some GitVersion string that cannot be parsed by ParseGeneric() and we'll refuse to use any remote cluster with such an unparseable GitVersion.
> 
> I wonder if it is ok to make such a change?
> 
> The GitVersion is just a string that is passed at compilation time when compiling API server. If someone recompiled api server with incompatible version string, or if it is some product that tries to imitate kubernetes api and provides an incompatible string - now ArgoCD just will refuse to work.
> 
> I think that in such cases we should just print warning into the log and continue

Sure I can change it to work like [this](https://github.com/argoproj/argo-cd/pull/26469/changes#diff-ab87bc0baec33f4dc87e50bdb589657963b08bb9fb4b7b61d731124ee63c745fR354) piece of code

**Comment by ppapapetrou76** [comment]
@dudinea addressed [here](75ce82d40e430720393534da7b9015dd04bdb2bb)

**Comment by dudinea** [comment]
> [here](https://github.com/argoproj/argo-cd/pull/75ce82d40e430720393534da7b9015dd04bdb2bb)

error 404

File: util/db/cluster.go [hunk 3]
```diff
@@ -39,7 +40,12 @@ func (db *db) getLocalCluster() *appv1.Cluster {
 	initLocalCluster.Do(func() {
 		info, err := db.kubeclientset.Discovery().ServerVersion()
 		if err == nil {
-			localCluster.Info.ServerVersion = fmt.Sprintf("%s.%s", info.Major, info.Minor)
+			ver, verErr := version.ParseGeneric(info.GitVersion)
+			if err == nil {
```
Comment (dudinea) [inline util/db/cluster.go]:
```suggestion
			if verErr == nil {
```

Comment (jannfis) [inline util/db/cluster.go]: Did you mean `verErr == nil` here?

File: gitops-engine/pkg/utils/kube/ctl.go [hunk 4]
```diff
@@ -349,7 +350,15 @@ func (k *KubectlCmd) GetServerVersion(config *rest.Config) (string, error) {
 	if err != nil {
 		return "", fmt.Errorf("failed to get server version: %w", err)
 	}
-	return fmt.Sprintf("%s.%s", v.Major, v.Minor), nil
+
+	ver, err := version.ParseGeneric(v.GitVersion)
+	if err != nil {
+		return "", fmt.Errorf("failed to parse server version: %w", err)
```
Comment (dudinea) [inline gitops-engine/pkg/utils/kube/ctl.go:356]: Do not fail on failure to parse but just return "". This way it will be consistent with what we're doing in [reposerver/repository.go](https://github.com/argoproj/argo-cd/blob/630c6e86ea327ae1d214dd8527f585e29f552970/reposerver/repository/repository.go#L1180)

**Review by dudinea — CHANGES_REQUESTED** [review]

File: gitops-engine/pkg/utils/kube/ctl.go (hunk 4 above)
Comment (ppapapetrou76) [reply gitops-engine/pkg/utils/kube/ctl.go:356]: @dudinea `parseKubeVersion` actually fails when there's an error in `ParseGeneric` - see here https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L1185 

so the code in ctl.go has the same behavior as repository

**Review by dudinea — APPROVED** [review]
LGTM

File: util/db/cluster.go [hunk 5]
```diff
@@ -39,7 +40,12 @@ func (db *db) getLocalCluster() *appv1.Cluster {
 	initLocalCluster.Do(func() {
 		info, err := db.kubeclientset.Discovery().ServerVersion()
 		if err == nil {
-			localCluster.Info.ServerVersion = fmt.Sprintf("%s.%s", info.Major, info.Minor)
+			ver, verErr := version.ParseGeneric(info.GitVersion)
```
Comment (reggie-k) [inline util/db/cluster.go:42]: Since we are now changing how the version will be displayed in cluster CLI commands, let's add a note in the upgrade guide that the parsing of the version changed in this version.
And as we discussed, it would be better to have a single way to parse the version for Helm and for cluster command, in a follow up PR.
Other than that, LGTM.

Comment (ppapapetrou76) [reply util/db/cluster.go:42]: Thanks @reggie-k added and I will follow-up in another PR to formalize the version as we do it for Helm

**Review by reggie-k — APPROVED** [review]
