### PR TITLE
fix(ui): show full labels, projects, clusters, and namespaces on hover in sidebar (#7520)

### LINKED ISSUE #7520: ArgoCD 2.1 Filters hide a lot of information
# Summary

Labels used in filters used to either wrap or float within the filters pane.

In 2.1 with the new filter sidebar, it cuts off a lot of the label making it harder to use.

The clear button also doesn't look quite right in the window.

image

# Motivation

Don't hide filter information.

# Proposal

Either wrap and expand the label if it overflows the panel or make the entire side filter panel resizable?

Doing a hover popup might work, but for long labels it'd basically make their display at all kinda useless since all the important information is at the end when you use labels like `app.kubernetes.io/name: my-app`

### PR DESCRIPTION
**Pull request by adityaraj178**
Closes: #7520 

Changes made:
On hover on labels, projects, cluster and ns in Application filters in sidebar, it will show full information.

after:

https://github.com/user-attachments/assets/cdb00ddf-6105-4b32-95ac-a766a6f54707

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* -[x] The title of the PR states what changed and the related issues number (used for the release note).
* -[x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* -[x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* -[x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* -[x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* -[x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* -[x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: ui/src/app/applications/components/filter/filter.tsx [hunk 1]
```diff
@@ -31,6 +32,17 @@ export const CheckboxRow = (props: {value: boolean; onChange?: (value: boolean)
...
+    const tooltipProps = {
+        placement: 'top' as any,
+        popperOptions: {
+            modifiers: {
+                preventOverflow: {
+                    boundariesElement: 'window' as any
+                }
+            }
+        }
+    };
```
Comment (jwinters01) [inline ui/src/app/applications/components/filter/filter.tsx:44]: I would push to avoid `any` type declarations when possible, here we can delare this type as `Partial<React.ComponentProps<typeof tooltip>>` to remove the type error without declaring the properties as `any`

```suggestion
    const tooltipProps: Partial<React.ComponentProps<typeof Tooltip>> = {
        placement: 'top',
        popperOptions: {
            modifiers: {
                preventOverflow: {
                    boundariesElement: 'window'
                }
            }
        }
    };
```

**Review by jwinters01 — CHANGES_REQUESTED** [review]
Slight change to props declaration but once that is fixed LGTM

File: ui/src/app/applications/components/filter/filter.tsx (hunk 1 above)
Comment (adityaraj178) [reply ui/src/app/applications/components/filter/filter.tsx:44]: Thanks for the review @jwinters01. Made the changes.

**Review by jwinters01 — APPROVED** [review]

**Review by crenshaw-dev — APPROVED** [review]
