### PR TITLE
fix: app create with -f should not ignore other options

### LINKED ISSUE #3943: argocd app create -f should not ignore --values-from-literal or other options that are used to specify part of the app manifest
# Summary

The `-f` option ignores `--values-from-literal`, `--values`, `-p`, and `--helm-set`. IMO this should not be the case, and these options should be used to generate the final manifest.

# Motivation
An Application manifest that uses using a Helm chart, might be used for several clusters - each cluster needing to bring its own `--values-literal-file`. This is not possible now. Instead we need to put an application manifest with each cluster. This makes it impossible to externalize the app manifest to a central repo which would be useful for those of us managing fleets of clusters which all get the same Application. The app manifest could be kept in a `fleet-apps` repo, and the cluster-specific values file (passed to the Application via `--values-literal-file`) would be kept in a cluster's repo. This is not possible now - and for this use case - we need to put an application manifest in each cluster repo - with the only difference being the `spec.helm.values` block.

# Proposal

The `-f` option should not ignore other options that specify parts of the app manifest.

### PR DESCRIPTION
**Pull request by mayzhang2000**
fixes: #3943

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

File: test/e2e/fixture/app/actions.go [hunk 1]
```diff
@@ -58,7 +58,26 @@ func (a *Actions) AddSignedFile(fileName, fileContents string) *Actions {
 	return a
 }
 
-func (a *Actions) CreateFromFile(handler func(app *Application)) *Actions {
+func (a *Actions) CreateFromPartialFile(data string, flags ...string) *Actions {
+	a.context.t.Helper()
```
Comment (alexmt) [inline test/e2e/fixture/app/actions.go:62]: Can you re-use existing `Create` method here? e.g.:

```
func (a *Actions) CreateFromPartialFile(data string, flags ...string) *Actions {
	tmpFile, err := ioutil.TempFile("", "")
	errors.CheckError(err)
	_, err = tmpFile.Write([]byte(data))
	errors.CheckError(err)
	return a.Create(append(flags..., "-f", tmpFile.Name())
}
```

**Review by alexmt — APPROVED** [review]
LGTM. 

Added one comment about tests but don't have strong opinion about it.
