### PR TITLE
fix: disable automaxprocs logging

### LINKED ISSUE #20066: 2.13 RC Argo CD CLI returns
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Any command ran using the `argocd` client CLI returns the following

```
2024/09/23 12:24:25 maxprocs: Leaving GOMAXPROCS=24: CPU quota undefined
```

This is happening on a x86_64 Linux client

```
$ uname -a
Linux desktop.cloud.chx 6.10.10-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:26:09 UTC 2024 x86_64 GNU/Linux
```

**To Reproduce**

Run any `argocd` command on a Linux client

**Expected behavior**

Golang specific things should be suppressed 

**Version**

```shell
$ argocd version
2024/09/23 14:50:13 maxprocs: Leaving GOMAXPROCS=24: CPU quota undefined
argocd: v2.13.0-rc2+0f083c9
  BuildDate: 2024-09-20T11:59:25Z
  GitCommit: 0f083c9e58638fc292cf064e294a1aa53caa5630
  GitTreeState: clean
  GoVersion: go1.22.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.0-rc2+0f083c9
  BuildDate: 2024-09-20T11:37:53Z
  GitCommit: 0f083c9e58638fc292cf064e294a1aa53caa5630
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

### PR DESCRIPTION
**Pull request by nitishfy**
Closes https://github.com/argoproj/argo-cd/issues/20066

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by gdsoumya — CHANGES_REQUESTED** [review]

File: cmd/argocd/commands/root.go [hunk 1]
```diff
@@ -20,6 +22,10 @@ import (
 
 func init() {
 	cobra.OnInitialize(initConfig)
+	_, err := maxprocs.Set()
```
[the remark this answers is not in the document]
Comment (nitishfy) [reply cmd/argocd/commands/root.go:25]: with the current change, we still have maxproc logging disabled for all the commands. I personally prefer keeping the `main` simple and clean. WDYT?

File: cmd/main.go [hunk 2]
```diff
@@ -6,8 +6,6 @@ import (
 
 	"github.com/spf13/cobra"
```
Comment (reggie-k) [inline cmd/main.go:8]: Looks like removing the dependency actually removes the functionality of auto-setting the GOMAXPROCS based on K8S requests/limits and not just the logging:
https://github.com/argoproj/argo-cd/pull/16528

**Comment by reggie-k** [comment]
I think that it is useful to log the GOMAXPROCS after it was auto-set by the automaxprocs.
The reason is that now, when using automaxprocs, it's value would probably be changed for pods, and when investigating resource consumption / performance issues, it might be important to know what it was set to.
Since the error for local environments / argocd cli commands is obviously annoying, disabling the default logging like you did, makes total sense, and I suggest to add an explicit DEBUG-level log for CPU and GOMAXPROCS values similarly to here afterwards:
https://github.com/uber-go/automaxprocs/issues/18#issuecomment-2081309145
Then it can be tested on both cli commands and argocd container startups to see whether acceptable. 
WDYT? I am definitely open to other opinions :)

File: cmd/main.go [hunk 3]
```diff
@@ -25,6 +24,10 @@ const (
 )
 
 func main() {
+	_, err := maxprocs.Set()
+	if err != nil {
+		return
+	}
```
Comment (agaudreault) [inline cmd/main.go:30]: Error should be ignored as this is an optimization. It could be logged as a warning, but shouldn't return.

File: cmd/main.go [hunk 4]
```diff
@@ -25,6 +24,10 @@ const (
 )
 
 func main() {
+	_, err := maxprocs.Set()
```
Comment (agaudreault) [inline cmd/main.go:27]: I think the goal is to have 2 different behavior. 1 for the CLI (no logging) and 1 for the "services" (info logs).

**Review by agaudreault — CHANGES_REQUESTED** [review]

File: cmd/main.go [hunk 5]
```diff
@@ -60,3 +62,21 @@ func main() {
...
+func setAutoMaxProcs(binaryName string) {
+	isCLI := binaryName == "argocd" ||
+		binaryName == "argocd-linux-amd64" ||
+		binaryName == "argocd-darwin-amd64" ||
+		binaryName == "argocd-windows-amd64.exe"
+
+	if isCLI {
+		_, _ = maxprocs.Set() // Intentionally ignore errors for CLI binaries
+	} else {
+		_, err := maxprocs.Set(maxprocs.Logger(log.Debugf))
```
[the remark this answers is not in the document]
Comment (nitishfy) [reply cmd/main.go:77]: resolved

**Review by gdsoumya — APPROVED** [review]

**Review by wanghong230 — APPROVED** [review]

**Comment by nitishfy** [comment]
@agaudreault can you review the PR now?

**Review by alexmt — APPROVED** [review]

File: cmd/main.go [hunk 6]
```diff
@@ -60,3 +63,21 @@ func main() {
 		os.Exit(1)
 	}
 }
+
+// setAutoMaxProcs sets the GOMAXPROCS value based on the binary name.
+// It suppresses logs for CLI binaries and logs the setting for services.
+func setAutoMaxProcs(binaryName string) {
+	isCLI := binaryName == "argocd" ||
```
Comment (pasha-codefresh) [inline cmd/main.go:70]: just as small improvement suggestion, not really blocker to merge. I think it would be nice to move this function to utils and also reuse it inside 

`switch binaryName {
	case "argocd", "argocd-linux-amd64", "argocd-darwin-amd64", "argocd-windows-amd64.exe":`
	
it should be pretty small change, also it would be super easy to cover with unit tests

Comment (nitishfy) [reply cmd/main.go:70]: why do we need to reuse it inside the switch case for cli when we are already setting those values based on binary name?

Comment (nitishfy) [reply cmd/main.go]: resolved

**Review by agaudreault — APPROVED** [review]
