### PR TITLE
fix(ui): Add title for full content without clicking (issue #17600)

### LINKED ISSUE #17600: I cannot see whole name of resource in config map
### Discussed in https://github.com/argoproj/argo-cd/discussions/17585

<div type='discussions-op-text'>

<sup>Originally posted by **LadaVarga** March 21, 2024</sup>
Hello,
Have you changed something recently in ArgoCD UI, I cannot see the whole name of name of the configmap in configmap view? We use version v2.10.3+0fd6344. I definitely use that table pretty heavily and I was able to the almost whole name of the resource.
2024-03-21 16_58_49-_ Channel_ team-software-delivery - Procore Technologies, Inc - Slack
Thanks</div>

We are probable upgraded, but it can't see whole name of the column, it is really annoying.

### PR DESCRIPTION
**Pull request by sunyeongchoi**
Fixes https://github.com/argoproj/argo-cd/issues/17600

If the text is long, it will be cut off and can't see the entire text. So I added `title`.
When hovering the mouse, the user can see the entire text.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

# Results
### Before
image

### After(Before review)
**NAME field title**
image

**GROUP/KIND field title**
image

**SYNC ORDER field title**
image

**NAMESPACE field title**
image

**CREATED AT field title**
image

### After(After review)
**NAME field title**
image

**GROUP/KIND field title**
image

**SYNC ORDER field title**
image

**NAMESPACE field title**
image

**CREATED AT field title**
image

### CODE REVIEW

File: ui/src/app/applications/components/application-details/application-resource-list.tsx [hunk 1]
```diff
@@ -102,9 +102,15 @@ export const ApplicationResourceList = (props: ApplicationResourceListProps) =>
                                             </Consumer>
                                         )}
                                     </div>
-                                    <div className='columns small-1 xxxlarge-1'>{[res.group, res.kind].filter(item => !!item).join('/')}</div>
-                                    <div className='columns small-1 xxxlarge-1'>{res.syncWave || '-'}</div>
-                                    <div className='columns small-2 xxxlarge-1'>{res.namespace}</div>
+                                    <div className='columns small-1 xxxlarge-1' title={[res.group, res.kind].filter(item => !!item).join('/')}>
```
Comment (oleksandr-codefresh) [inline ui/src/app/applications/components/application-details/application-resource-list.tsx:105]: let's move this filtering to local variable, to reuse code

Comment (plakyda-codefresh) [inline ui/src/app/applications/components/application-details/application-resource-list.tsx:105]: Would you consider using the tooltip component from argo-ui, which is already available, instead of the native tooltip?

Comment (sunyeongchoi) [reply ui/src/app/applications/components/application-details/application-resource-list.tsx]: Thanks for your review! I applied your review and defined a local variable to reuse.
df59d795364acff62460f67a65c17b62df7d2fe4

Comment (sunyeongchoi) [reply ui/src/app/applications/components/application-details/application-resource-list.tsx]: Thanks for your review! I applied it as a tooltip in argo-ui as you said, and it looked much prettier :)
https://github.com/argoproj/argo-cd/commit/df59d795364acff62460f67a65c17b62df7d2fe4

**Review by oleksandr-codefresh — APPROVED** [review]

**Review by pasha-codefresh — APPROVED** [review]

**Comment by y-elip** [comment]
@sunyeongchoi I've reviewed your fix for the "hover" issue with names in this pull request: https://github.com/argoproj/argo-cd/pull/18243

It looks good, but when dealing with a large number of resources, hovering over each one to find the needed item becomes quite tedious.
Are there any options to add flexibility to the column width to make this process more efficient?
