### PR TITLE
fix: enable redis retries; add redis request duration metric

### LINKED ISSUE #3547: Login attempt fails sometimes after 1.5.3 upgrade
After upgrading to 1.5.3 I'm getting these errors on the first attempt to authenticate via `/api/v1/session` route after some idle period. It would eventually work if I retry a second or few more times. I did not configure any of the rate limiting and the credentials used to hit the route is the admin user. Not quite sure why this is happening.

```
time="2020-05-05T16:58:46Z" level=error msg="finished unary call with code Unknown" error="failed to enforce max concurrent logins limit: EOF" grpc.code=Unknown grpc.method=Create grpc.service=session.SessionService grpc.start_time="2020-05-05T16:58:46Z" grpc.time_ms=0.664 span.kind=server system=grpc
```

### PR DESCRIPTION
**Pull request by alexmt**
Partially fixes #3547 

PR enables redis client retries and additionally redis request duration metric

### CODE REVIEW

File: cmd/argocd-application-controller/main.go [hunk 1]
```diff
@@ -96,14 +96,7 @@ func newCommand() *cobra.Command {
...
 			errors.CheckError(err)
-			metricsServer := appController.GetMetricsServer()
-			redisClient.WrapProcess(func(oldProcess func(cmd redis.Cmder) error) func(cmd redis.Cmder) error {
-				return func(cmd redis.Cmder) error {
-					err := oldProcess(cmd)
-					metricsServer.IncRedisRequest(err != nil && err != rediscache.ErrCacheMiss)
-					return err
-				}
-			})
+			cacheutil.CollectMetrics(redisClient, appController.GetMetricsServer())
```
Comment (jannfis) [inline cmd/argocd-application-controller/main.go:99]: :+1:

**Review by jannfis — APPROVED** [review]
LGTM despite bad code coverage.
