### PR TITLE
fix(ui): add exec check to avoid API calls

### LINKED ISSUE #16165: Bug(ui): Add check execEnabled to avoid extra  API call
I see there are multiple `can-i/exec/create/test/argo-analysis` APIs calls  to fetch if exec action is allowed on the UI and pod resource should be rendered with exec action button. The issue is more prominent when viewing the resource list.

The UI is making unnecessary calls even if the exec action is disabled by default. 

**To Reproduce**

- open the network tab, and inspect the API 
[can-i/exec/create/test/argo-analysis 
](http://localhost:4000/api/v1/account/can-i/exec/create/test/argo-analysis)**Expected behavior**

API
**Screenshots**
Screenshot 2023-10-30 at 1 39 20 PM

### PR DESCRIPTION
**Pull request by ashutosh16**
fixes https://github.com/argoproj/argo-cd/issues/16165

Along with this PR, fixing UI bug on the resource list when pod group is enabled and total pod count is grater than 15
UI displays Parent Node Ref details which shouldn't be displayed on this list view. Parent Ref details should only be displayed when the user clicks on the pod group on the tree view
Screenshot 2023-10-30 at 7 00 56 PM

### CODE REVIEW

**Comment by ashutosh16** [comment]
Fix - 1
no api call to `[can-i/exec/create/test/argo-analysis](http://localhost:4000/api/v1/account/can-i/exec/create/test/argo-analysis)`

Screenshot 2023-10-30 at 8 11 21 PM

Fix -2 
Uploading Screen Recording 2023-10-30 at 8.08.56 PM.mov…

**Comment by ashutosh16** [comment]
@ishitasequeira  Would it be possible for you to test my changes. There are two issues that this PR addresses.
- Check settings.execEnabled to determine whether exec is enabled, and only make API queries if exec is enabled.
- Determine the location of the UI - resource list or tree view. Only display the UI component when the user is viewing the tree or network

**Comment by ishitasequeira** [comment]
> @ishitasequeira Would it be possible for you to test my changes. There are two issues that this PR addresses.
> 
> * Check settings.execEnabled to determine whether exec is enabled, and only make API queries if exec is enabled.
> * Determine the location of the UI - resource list or tree view. Only display the UI component when the user is viewing the tree or network

Sure, I will test it out this week.

**Comment by chengfang** [comment]
@ashutosh16 can you include `fix(ui)` in the title since this PR is all about ui changes. Thanks.

File: ui/src/app/applications/components/application-details/application-resource-list.tsx [hunk 1]
```diff
@@ -31,35 +31,43 @@ export const ApplicationResourceList = ({
         return null;
     }
     const parentNode = ((resources || []).length > 0 && (getResNode(tree.nodes, nodeKey(resources[0])) as ResourceNode)?.parentRefs?.[0]) || ({} as ResourceRef);
+    const searchParams = new URLSearchParams(window.location.search);
+    const view = searchParams.get('view');
 
+    const ParenRefDetails = () => {
```
Comment (ishitasequeira) [inline ui/src/app/applications/components/application-details/application-resource-list.tsx:37]: nit: `ParenRefDetails` -> `ParentRefDetails`

**Review by ishitasequeira — APPROVED** [review]
Thanks @ashutosh16, I tested the change and the changes look good to me.

File: ui/src/app/applications/components/resource-details/resource-details.tsx [hunk 2]
```diff
@@ -280,7 +280,7 @@ export const ResourceDetails = (props: ResourceDetailsProps) => {
                         const settings = await services.authService.settings();
                         const execEnabled = settings.execEnabled;
                         const logsAllowed = await services.accounts.canI('logs', 'get', application.spec.project + '/' + application.metadata.name);
-                        const execAllowed = await services.accounts.canI('exec', 'create', application.spec.project + '/' + application.metadata.name);
+                        const execAllowed = settings.execEnabled && (await services.accounts.canI('exec', 'create', application.spec.project + '/' + application.metadata.name));
```
Comment (keithchong) [inline ui/src/app/applications/components/resource-details/resource-details.tsx:283]: Perhaps use execEnabled instead of settings.execEnabled?

File: ui/src/app/applications/components/utils.tsx [hunk 3]
```diff
@@ -473,7 +473,7 @@ function getActionItems(
     const execAction = services.authService
         .settings()
         .then(async settings => {
-            const execAllowed = await services.accounts.canI('exec', 'create', application.spec.project + '/' + application.metadata.name);
+            const execAllowed = settings.execEnabled && (await services.accounts.canI('exec', 'create', application.spec.project + '/' + application.metadata.name));
```
Comment (keithchong) [inline ui/src/app/applications/components/utils.tsx:476]: Perhaps use execEnabled instead of settings.execEnabled?

File: ui/src/app/applications/components/application-details/application-resource-list.tsx [hunk 4]
```diff
@@ -31,35 +31,43 @@ export const ApplicationResourceList = ({
...
+                    <div>Kind:</div>
+                    <div>{parentNode?.kind}</div>
+                </div>
+            </div>
+        );
+    };
     return (
         <div>
-            <div className='resource-details__header' style={{paddingTop: '20px'}}>
-                {Object.keys(parentNode).length > 0 && (
```
Comment (keithchong) [inline ui/src/app/applications/components/application-details/application-resource-list.tsx:38]: Did you want to show this info/text when there is no parent node info? eg.:

```
        return (Object.keys(parentNode).length > 0 ? (
            <div className='resource-parent-node-info-title'>
                <div>Parent Node Info</div>
                <div className='resource-parent-node-info-title__label'>
                    <div>Name:</div>
                    <div>{parentNode?.name}</div>
                </div>
                <div className='resource-parent-node-info-title__label'>
                    <div>Kind:</div>
                    <div>{parentNode?.kind}</div>
                </div>
            </div> ) : (
                <div></div>
            )
        );
```

File: ui/src/app/applications/components/application-details/application-resource-list.tsx [hunk 5]
```diff
@@ -31,35 +31,43 @@ export const ApplicationResourceList = ({
...
-                            <div>{parentNode?.name}</div>
-                        </div>
-                        <div className='resource-parent-node-info-title__label'>
-                            <div>Kind:</div>
-                            <div> {parentNode?.kind}</div>
-                        </div>
-                    </div>
-                )}
-            </div>
+            {/*Display only when the view is set to tree*/}
```
Comment (keithchong) [inline ui/src/app/applications/components/application-details/application-resource-list.tsx:54]: Display only when the view is set to tree or network ?

File: ui/src/app/applications/components/application-details/application-resource-list.tsx (hunk 4 above)
Comment (ashutosh16) [reply ui/src/app/applications/components/application-details/application-resource-list.tsx:38]: >Did you want to show this info/text when there is no parent node info? eg.:

Added the code, if no parent information is available, do not display anything. Additionally, I would like the parent information to appear only when viewing the resource list (pod/replicaset) in tree view or network view and the total pod count exceeds 15.

**Comment by ashutosh16** [comment]
@keithchong /@ishitasequeira  Would you be able to merge the PR?

**Review by ishitasequeira — APPROVED** [review]
Thanks @ashutosh16 for fixing the comments.
