### PR TITLE
Only delete resources during app delete cascade if permitted to (fixes #2693)

### LINKED ISSUE #2693: Project destination restrictions not respected during cascade deleting an application
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an application is deleted using the "Cascade" option, it might also delete resources in the cluster that are not allowed by an application's target namespace restriction. This can result in extraneous resources being deleted.

This is a similar yet not quite the same issue as discussed in #2650 and was found during the discussion in mentioned issue.

**To Reproduce**

1. Create two namespaces, `nsa` and `nsb`
1. Create a project `restricted` with restrictions on the destination cluster and destination namespace `nsa`
1. Create a new application for project `restricted`, named `guestbook-test`, with a source repository `https://github.com/argoproj/argocd-example-apps` and a target namespace of `nsa`.
1. Sync the application to the cluster
1. Create an arbitrary resource (see below for example) in the cluster that is annotated with a label `app.kubernetes.io/instance: guestbook-test` in another namespace `nsb` (which is not allowed by project restrictions) and see your `guestbook-test` application become OutOfSync due to a stray resource not contained in the manifests. It's worth discussing if the application should even see/show this resource, since it's in a namespace not allowed via project restrictions.
1. Delete the application `guestbook-test` with the Cascade option and see how the resource manually created in the previous step also gets deleted from the cluster, despite being in a non-allowed namespace (i.e. `kubectl -n nsb get cm test-cm` does not give you a result)

**Expected behavior**

Destination restrictions in project should be honoured and the resource in non-allowed namespace is not deleted when the application is deleted with cascade option.

**Version**
Latest available build from master

```shell
argocd-server: v1.3.0+cb6d7ea
  BuildDate: 2019-11-07T02:43:42Z
  GitCommit: cb6d7eaad208c91966f13a95f73860029ce9c659
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: vkustomize/v3.2.1
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```
**Example resource for reproducing**
Apply using `kubectl -n nsb apply -f <file.yaml>`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
  labels: 
    app.kubernetes.io/instance: guestbook-test
data:
```

### PR DESCRIPTION
**Pull request by jannfis**
Checklist:

* [x]  this is a bug fix
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* ~~I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them~~ Not necessary for this bug fix
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Only delete resources during app delete cascade when the project permits the namespace the resource resides in. Fixes #2693

### CODE REVIEW

File: controller/appcontroller.go [hunk 1]
```diff
@@ -477,8 +477,15 @@ func (ctrl *ApplicationController) processAppOperationQueueItem() (processNext b
 	return
 }
 
-func shouldBeDeleted(app *appv1.Application, obj *unstructured.Unstructured) bool {
-	return !kube.IsCRD(obj) && !isSelfReferencedApp(app, kube.GetObjectRef(obj))
+// shouldbeDeleted returns whether a given resource obj should be deleted on cascade delete of application app
+func (ctrl *ApplicationController) shouldBeDeleted(app *appv1.Application, obj *unstructured.Unstructured) bool {
+	permitted := false
```
Comment (jannfis) [inline controller/appcontroller.go]: I chose default permitted state to be false in case project cannot be retrieved - better safe than sorry.

**Comment by jannfis** [comment]
I tried writing a unit test for this behaviour, but since `Controller.getAppProject()` relies on informers and more state than is available from fake controller, I will rather supply end-to-end testing for this bugfix (should be more simple).

**Comment by jannfis** [comment]
After thinking a while, unit tests were feasable and are now implemented. However, I had to slightly change semantics of `Controller.finalizeApplicationDeletion()` in that it now also returns the list of objects it had actually deleted from the cluster, so I can check for in the unit tests. It seems not possible to get the actual resources in the fake cluster.

File: controller/appcontroller.go [hunk 2]
```diff
@@ -477,11 +477,22 @@ func (ctrl *ApplicationController) processAppOperationQueueItem() (processNext b
...
+// shouldbeDeleted returns whether a given resource obj should be deleted on cascade delete of application app
 func shouldBeDeleted(app *appv1.Application, obj *unstructured.Unstructured) bool {
 	return !kube.IsCRD(obj) && !isSelfReferencedApp(app, kube.GetObjectRef(obj))
 }
 
-func (ctrl *ApplicationController) finalizeApplicationDeletion(app *appv1.Application) error {
+// Checks whether an object is permitted to be deleted according to the project restrictions
+func (ctrl *ApplicationController) isPermittedForDelete(app *appv1.Application, obj *unstructured.Unstructured) bool {
+	permitted := false
+	if proj, err := ctrl.getAppProj(app); err == nil {
```
Comment (alexec) [inline controller/appcontroller.go]: I think we should error here

Comment (jannfis) [reply controller/appcontroller.go]: Agreed. It makes the function not inline expressable, but I guess it's worth it. Committed appropriate changes.

File: controller/appcontroller.go [hunk 3]
```diff
@@ -490,23 +501,27 @@ func (ctrl *ApplicationController) finalizeApplicationDeletion(app *appv1.Applic
...
 
 	objsMap, err := ctrl.stateCache.GetManagedLiveObjs(app, []*unstructured.Unstructured{})
 	if err != nil {
-		return err
+		return nil, err
 	}
 	objs := make([]*unstructured.Unstructured, 0)
 	for k := range objsMap {
-		if objsMap[k].GetDeletionTimestamp() == nil && shouldBeDeleted(app, objsMap[k]) {
+		permitted, err := ctrl.isPermittedForDelete(app, objsMap[k])
```
Comment (alexec) [inline controller/appcontroller.go]: do you want to move this into the block below?

File: controller/appcontroller.go [hunk 4]
```diff
@@ -515,29 +530,33 @@ func (ctrl *ApplicationController) finalizeApplicationDeletion(app *appv1.Applic
...
 	}
 
 	objsMap, err = ctrl.stateCache.GetManagedLiveObjs(app, []*unstructured.Unstructured{})
 	if err != nil {
-		return err
+		return objs, err
 	}
 	for k, obj := range objsMap {
-		if !shouldBeDeleted(app, obj) {
+		permitted, err := ctrl.isPermittedForDelete(app, obj)
```
Comment (alexec) [inline controller/appcontroller.go]: move check into block below?

**Comment by alexec** [comment]
I'm pondering this. Should we actually return an error if you try and delete a resource you are not allowed to? Rather than just not deleting it?

**Comment by jannfis** [comment]
> I'm pondering this. Should we actually return an error if you try and delete a resource you are not allowed to? Rather than just not deleting it?

Hm, good question. The use case for application delete with cascade is to remove all resources in the cluster that are managed by the application and finally the application itself, right? The question is, are resources in the cluster in namespaces not even allowed for the app, accidentally labeled with the instance value for given app, considered managed by the application? 

Because when we error out once we stumble over such a resource during delete, someone else who is able to create resources in other namespaces, could effectively prevent us from deleting any application under control of ArgoCD by labeling their resources wrongly.

So I think we just ignore the resource for deletion, otherwise nasty side-effects could occur.

File: controller/appcontroller.go (hunk 3 above)
Comment (jannfis) [reply controller/appcontroller.go]: Do you mean like instead of
```go
		permitted, err := ctrl.isPermittedForDelete(app, objsMap[k])
		if err != nil {
			return nil, err
		}
		if permitted && objsMap[k].GetDeletionTimestamp() == nil && shouldBeDeleted(app, objsMap[k]) {
			objs = append(objs, objsMap[k])
		}
```
something along these lines?
```go
			permitted, err := ctrl.isPermittedForDelete(app, objsMap[k])
			if err != nil {
				return nil, err
			} else if permitted {
				objs = append(objs, objsMap[k])
			}
```

File: controller/appcontroller.go [hunk 5]
```diff
@@ -477,11 +477,22 @@ func (ctrl *ApplicationController) processAppOperationQueueItem() (processNext b
...
 
+// shouldbeDeleted returns whether a given resource obj should be deleted on cascade delete of application app
 func shouldBeDeleted(app *appv1.Application, obj *unstructured.Unstructured) bool {
 	return !kube.IsCRD(obj) && !isSelfReferencedApp(app, kube.GetObjectRef(obj))
 }
 
-func (ctrl *ApplicationController) finalizeApplicationDeletion(app *appv1.Application) error {
+// Checks whether an object is permitted to be deleted according to the project restrictions
+func (ctrl *ApplicationController) isPermittedForDelete(app *appv1.Application, obj *unstructured.Unstructured) (bool, error) {
+	if proj, err := ctrl.getAppProj(app); err != nil {
```
Comment (alexec) [inline controller/appcontroller.go]: What about combining this into `shouldBeDeleted` it seems to me that your interpretation would be consistent?

Comment (jannfis) [reply controller/appcontroller.go]: Hm, I had it initially together in `shouldBeDeleted()`, but decided to decouple them. Mainly for reasons of differentiating later on, i.e. if we want to cancel deletion if there are resources who are not permitted. So I'd really like to keep it the way it currently is.

Comment (alexec) [reply controller/appcontroller.go]: I thought you wanted to semantics to be the same?

Comment (jannfis) [reply controller/appcontroller.go]: Hm, semantics of `shouldBeDeleted()` are untouched?

Comment (alexec) [reply controller/appcontroller.go]: I think the semantics of a theoretical func`shouldNotBeDeleted` would include the permission check, so conversely I feel like `shouldBeDeleted`. Does that make sense?

**Comment by alexec** [comment]
Does this fix #2573

**Comment by jannfis** [comment]
> Does this fix #2573?

Hm, I don't think so.

**Review by alexec — DISMISSED** [review]
Changes requested as per last comment.

**Comment by jannfis** [comment]
Comment has been addressed @alexec, please have a look

**Review by alexec — APPROVED** [review]
LGTM
