### PR TITLE
fix(ui): convert EditablePanel, EditbleSection and Query to function component

### LINKED ISSUE #22700: Replace uses of `componentWillMount` and `componentWillReceiveProps`
# Summary

The `componentWillMount` and `componentWillReceiveProps` React lifecycle hooks are [deprecated](https://legacy.reactjs.org/blog/2018/03/27/update-on-async-rendering.html). We should migrate to better APIs according to React docs.

# Motivation

We're using old React library versions. Moving away from deprecated lifecycle hooks will help use upgrade to newer React versions.

# Proposal

Adding the `UNSAFE_` prefix just silences warnings, it doesn't actually fix the problems. The [React docs point out that we probably can simplify things](https://legacy.reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html). Evaluate that documentation and follow React's recommendations.

### PR DESCRIPTION
**Pull request by linghaoSu**
Fix https://github.com/argoproj/argo-cd/issues/22700

This PR removes deprecated lifecycle methods and refactors class components into modern function components using hooks.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
This is awesome! Let me know if I can help. Will happily review when ready.

**Comment by linghaoSu** [comment]
> This is awesome! Let me know if I can help. Will happily review when ready.

Hi @crenshaw-dev, I think this PR is ready for review now — let me know if there's anything you'd like me to adjust. 

Also, I noticed that some components from the `argo-ui` library are still using deprecated methods, and the `react-form` library we're using for form validation is quite outdated as well. (It has since been renamed to [`@tanstack/react-form`](https://tanstack.com/form/latest)).

Maybe as a next step, we could consider updating `argo-ui` and evaluating whether to upgrade or replace `react-form` with something more modern and actively maintained.

File: ui/src/app/shared/components/query.tsx [hunk 1]
```diff
@@ -1,49 +1,43 @@
...
+
+    React.useEffect(() => {
+        const unsubscribe = context.history.listen(handleLocationChange);
+        return unsubscribe;
+    }, [context.history, handleLocationChange]);
+
+    return <>{children(searchParams$)}</>;
 }
+
+export {ObservableQuery, Query};
```
Comment (jwinters01) [inline ui/src/app/shared/components/query.tsx:26]: It feels like the "components" in this file would be better defined as custom hooks, since they express reusable behaviors as opposed to views. Could we refactor a bit and create `useObservableQuery` and `useQuery` hooks for these two components?

**Review by jwinters01 — CHANGES_REQUESTED** [review]

File: ui/src/app/shared/components/query.tsx (hunk 1 above)
Comment (linghaoSu) [reply ui/src/app/shared/components/query.tsx:26]: Thanks for your review. I agree with your point. I provided this approach because I didn’t want to modify the usage of these components. So, I kept both of them as components.
However, I’ll try to split the hook and the component: other code can continue using the component for now, while the hook will be available for future replacement.

File: ui/src/app/shared/components/query.tsx [hunk 2]
```diff
@@ -1,49 +1,56 @@
...
+    return <>{children(query)}</>;
+}
+
+function ObservableQuery({children}: ObservableQueryProps) {
+    const searchParams$ = useObservableQuery();
+
+    return <>{children(searchParams$)}</>;
 }
+
+export {ObservableQuery, Query, useQuery, useObservableQuery};
```
Comment (jwinters01) [inline ui/src/app/shared/components/query.tsx]: The Components here feel redundant now, can we just remove the components altogether, and instead call the hooks directly in the consuming components? Alternatively we could do this as a separate refactor

Comment (linghaoSu) [reply ui/src/app/shared/components/query.tsx]: image


image

I’m trying to replace all of these components with hooks, but some components that reference these two are still class components. Since we cannot call hooks in a class component’s render method, we can’t fully replace them yet.

I suggest we hold this PR for now. Once the other two PRs are merged, I can rebase and complete the replacement.

- project-details:  https://github.com/argoproj/argo-cd/pull/23797
- application-details: https://github.com/argoproj/argo-cd/pull/23767

**Review by jwinters01 — APPROVED** [review]

**Review by crenshaw-dev — APPROVED** [review]
