### PR TITLE
fix(repo-server): excess git requests, short-circuit GenerateManifests ref only

### LINKED ISSUE #14725: Excessive requests to git repository on commit to monorepo w/ multi-source apps
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

With 71 multi-source applications in a monorepo (in Bitbucket), a single commit triggers 271 requests to the git repository (11 fetch, 260 ls-remote). Logs show 333 "getting manifest cache" entries, with 15 cache hits and 318 cache misses. Example application sources:

```shell
sources:
  - path: manifests/my-app/
    repoURL: git@bitbucket.org:my-company/argo.git
    targetRevision: HEAD
  - chart: my-chart
    helm:
      releaseName: my-release
      valueFiles:
      - $values/values/my-app-values.yaml
    repoURL: my-helm-repo/charts
    targetRevision: 0.1.0
  - ref: values
    repoURL: git@bitbucket.org:my-company/argo.git
    targetRevision: HEAD
``` 

**To Reproduce**

Make any commit to the repository.

**Expected behavior**

Far fewer requests to the git repository and more cache hits.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.7.7+4650bb2.dirty
  BuildDate: 2023-07-05T19:42:32Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```shell
msg="getting manifests cache" appName=tenant-1 appSrc="{\"appSrc\":{\"repoURL\":\"\",\"ref\":\"values\"},\"srcRefs\":{\"$values\":{\"repoURL\":\"git@bitbucket.org:my-company/argo-dev.git\",\"project\":\"\",\"targetRevision\":\"HEAD\",\"chart\":\"\"}}}
```

In depth discussion with @crenshaw-dev on Slack with more detail. https://cloud-native.slack.com/archives/C01TSERG0KZ/p1690317861587929

Discussed at Argo SIG Scalability meeting on July and @ishitasequeira volunteered to take a look.

### PR DESCRIPTION
**Pull request by nromriell**
Partially Fixes #14725

Second part of a split of the https://github.com/argoproj/argo-cd/pull/16309 and follow-up to https://github.com/argoproj/argo-cd/pull/16410. Continues the fixes required to remove the excess git requests when using multi-source and ref sources.

Issue:
When `GenerateManifest` is called with a ref only source manifest generation is still run, and since there are no manifests this is always considered a manifest cache miss causing an excess number of fetch requests to the git server

Changes:
Short-circuit calls to `GenerateManifest` when it is a ref only source, however as part of the short circuit still resolve the references if they are not already in cache, this can help prevent additional calls to ls-remote when `GenerateManifest` is called with a related manifest generating source 

Impact:
This PR should greatly reduce the number of fetch calls made to git for multi-source applications with a ref only source. Some minor improvements to ls-remote should be observed as well since we skip unnecessary git util calls.

There is one additional item (race condition fix) along with a performance improvement (move to two level-cache) that will be included in follow-up PRs to finish up the reduction of ls-remote calls

Baseline v2.9.0 with 200 multi-source applications with a ref only source:
Screenshot from 2023-11-18 18-24-30

With the changes in the first PR under the same conditions:
Screenshot from 2023-11-21 00-43-54

With the changes from the first PR and this PR under the same conditions:
Screenshot from 2023-11-21 01-23-41

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [X] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [X] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -507,6 +507,16 @@ func resolveReferencedSources(hasMultipleSources bool, source *v1alpha1.Applicat
 func (s *Service) GenerateManifest(ctx context.Context, q *apiclient.ManifestRequest) (*apiclient.ManifestResponse, error) {
 	var res *apiclient.ManifestResponse
 	var err error
+
+	// Skip this path for ref only sources
+	if q.HasMultipleSources && q.ApplicationSource.Path == "" && q.ApplicationSource.Chart == "" && q.ApplicationSource.Ref != "" {
+		_, revision, err := s.newClientResolveRevision(q.Repo, q.Revision, git.WithCache(s.cache, !q.NoRevisionCache && !q.NoCache))
```
Comment (ishitasequeira) [inline reposerver/repository/repository.go:513]: Might be worth adding a debug message here in case we need to dive deeper for investigations.

File: reposerver/repository/repository.go [hunk 2]
```diff
@@ -507,6 +507,17 @@ func resolveReferencedSources(hasMultipleSources bool, source *v1alpha1.Applicat
 func (s *Service) GenerateManifest(ctx context.Context, q *apiclient.ManifestRequest) (*apiclient.ManifestResponse, error) {
 	var res *apiclient.ManifestResponse
 	var err error
+
+	// Skip this path for ref only sources
+	if q.HasMultipleSources && q.ApplicationSource.Path == "" && q.ApplicationSource.Chart == "" && q.ApplicationSource.Ref != "" {
+		log.Debugf("Skipping manifest generation for ref only source for application: %s", q.AppName)
```
Comment (ishitasequeira) [inline reposerver/repository/repository.go:513]: It would be helpful to add the source in the log as well in case there are multiple ref only sources in the same app.

**Review by ishitasequeira — COMMENTED** [review]
Overall PR LGTM!! Thanks @nromriell. Just left 1 minor comment.

File: reposerver/repository/repository.go (hunk 2 above)
Comment (nromriell) [reply reposerver/repository/repository.go]: Great point, thanks! Added in `ApplicationSource.Ref` to the log

**Review by ishitasequeira — APPROVED** [review]
Thanks @nromriell !! The changes LGTM, Great work!!
