### PR TITLE
fix: register controller workqueue metrics correctly

### LINKED ISSUE #7682: Application controller should export workqueue depth metrics
# Summary

Application controller should export workqueue depth metrics

# Motivation

Queuing delay and queue length are important information to debug control plane performance in large scale applications(3k+).

We use one ArgoCD instance to manage about 3K applications. And the number is still increasing, followed by the performance downgrade, for example it would take more time to trigger the auto sync or it can't refresh the resources status and keep with live status.

We have tried multi method to enhance performance.
1. scale up the replicas of ArgoCD server and repo-server with the [HA guide](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/) 
2. increase the `--status-processors` to 200 and `--operation-processors` to 100 refer to the [doc](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller)
3. configure server replicas with the HPA.

But unfortunately we still need about 20s to list application and update project role, e.g.

image
image

And after we switch to HA mode, the reconcile performance looks worse.
image 

Not sure if I am understanding this right, any response would be appreciated🙏.

# Proposal

Application controller export the workqueue depth metrics.

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <ben.ye@bytedance.com>

Fixes: https://github.com/argoproj/argo-cd/issues/7682.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

# Verification
image

### CODE REVIEW

File: controller/appcontroller.go [hunk 1]
```diff
@@ -36,9 +36,6 @@ import (
 	"k8s.io/client-go/tools/cache"
 	"k8s.io/client-go/util/workqueue"
 
-	// make sure to register workqueue prometheus metrics
-	_ "k8s.io/component-base/metrics/prometheus/workqueue"
```
Comment (yeya24) [inline controller/appcontroller.go:40]: About why this line doesn't work, because it registers to another metrics registry https://github.com/kubernetes/component-base/blob/master/metrics/prometheus/workqueue/metrics.go#L99 so that we cannot query those metrics when serving `/metrics`

Comment (crenshaw-dev) [reply controller/appcontroller.go:40]: Adding commit-specific link in case the file changes in master: https://github.com/kubernetes/component-base/blob/f57281d7c18ff3a9d1c2404bf97f4ca70bdcb655/metrics/prometheus/workqueue/metrics.go#L99

File: controller/metrics/workqueue.go [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+limitations under the License.
+*/
+
+// This file is copied and adapted from k8s.io/kubernetes/pkg/util/workqueue/prometheus
+// which registers metrics to the default prometheus Registry. We require very
+// similar functionality, but must register metrics to a different Registry.
+
+// Metrics subsystem and all keys used by the workqueue.
+
+package metrics
```
Comment (alexmt) [inline controller/metrics/workqueue.go:23]: Instead of implementing own metrics provider we could use `Registry` from `sigs.k8s.io/controller-runtime/pkg/metrics` package:


pkg/metrics/registry.go
```go
import (
	controllermetrics "sigs.k8s.io/controller-runtime/pkg/metrics"
)

type MetricsServer struct {
	// ...
	registry                controllermetrics.RegistererGatherer
	// ...
}

func NewAppRegistry(appLister applister.ApplicationLister, appFilter func(obj interface{}) bool, appLabels []string) controllermetrics.RegistererGatherer {
	registry := controllermetrics.Registry
	// ...
}


```

**Review by alexmt — CHANGES_REQUESTED** [review]

File: controller/metrics/workqueue.go (hunk 2 above)
Comment (yeya24) [reply controller/metrics/workqueue.go:23]: I prefer to not reuse their metrics because it doesn't support customizing histogram buckets.
From what I can see in our environment the upper limit 10s is very small. We can see queue metrics and work metrics up to several minutes.

File: controller/metrics/workqueue.go [hunk 3]
```diff
@@ -0,0 +1,123 @@
+/*
```
Comment (alexmt) [inline controller/metrics/workqueue.go:1]: I think this copyright should be removed. Code was copied but just because there are not many options of how metrics provider could be implemented.

**Review by alexmt — CHANGES_REQUESTED** [review]

File: controller/metrics/workqueue.go (hunk 2 above)
Comment (alexmt) [reply controller/metrics/workqueue.go:23]: Got it. It makes sense. I wish they make it possible to configure metrics properties but it is what it is. Added one more minor request about copyright.

File: controller/metrics/workqueue.go (hunk 3 above)
Comment (yeya24) [reply controller/metrics/workqueue.go]: Done

**Review by alexmt — APPROVED** [review]

**Comment by alexmt** [comment]
Thank you!
