### PR TITLE
fix(appset): Fix name conflict in appset controller (#16207)

### LINKED ISSUE #16114: ApplicationSets Across Namespaces Conflict
Checklist:

* [ ✅ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ✅ ] I've included steps to reproduce the bug.
* [ ✅ ] I've pasted the output of `argocd version`.

**Describe the bug**

An ApplicationSet that is project and namespace scoped can still conflict with an ApplicationSet in another namespace.

We are trying to implement namespace per tenant via the source and destination AppProject fields wherein our tenants can use apps and appsets in an isolated manner.

Unfortunately, we tried using `appset-sync` as the name of an ApplicationSet in two different namespaces, and that would continually conflict -- thus pruning what was created via the ApplciationSet in the other namespace.

From here the two sets of applications cycled their deployments.

Obviously this could be extremely dangerous to our production applications.

**To Reproduce**

Create two ApplicationSets in two different tenant namespaces with the same name.

Have these both target different namespaces.

The applications output will continually cycle in and out of existence as the output of one ApplicationSet will prune the output of the other.

**Expected behavior**

The namespacing of an ApplicationSet should work exactly like the namespacing of an Application.

`someNamespace/someApp` does not currently conflict with `someOtherNamespace/someApp`

yet,

`someNamespace/someAppSet` conflicts with `someOtherNamespace/someAppSet`

**Screenshots**

N/A

**Version**

```shell
argocd: v2.8.3+77556d9.dirty
  BuildDate: 2023-09-07T19:45:50Z
  GitCommit: 77556d9e64304c27c718bb0794676713628e435e
  GitTreeState: dirty
  GoVersion: go1.21.1
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.8.4+c279299

```

**Logs**

```
N/A
```

### LINKED ISSUE #16207: [appset in any namespace] ApplicationSet with same name in different namespaces conflict
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating two ApplicationSet with same name in two different source namespaces. The name conflict in the applicationset-controller and the source namespace for the application is not taken into account resulting in infinite loop deleting child applications and re-triggering reconcile loop. Logs attached

Quick fix: Ensure there are no name conflicting

**To Reproduce**

- Activate [appset in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/)
- Create two appset in different namespace with different behavior with same name

**Expected behavior**

**Screenshots**

**Version**

```json
{
    "Version": "v2.8.4+c279299",
    "BuildDate": "2023-09-13T19:12:09Z",
    "GitCommit": "c27929928104dc37b937764baf65f38b78930e59",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
time="2023-11-01T15:44:12Z" level=info msg="Deleted application" app=my-app-one appSet=my-application-set
time="2023-11-01T15:44:12Z" level=info msg="created Application" app=my-app-one appSet=my-application-set
time="2023-11-01T15:44:13Z" level=info msg="unchanged Application" app=my-app-one appSet=my-application-set
```

### PR DESCRIPTION
**Pull request by speedfl**
Fixes #16207
Fixes https://github.com/argoproj/argo-cd/issues/16114

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

File: test/e2e/fixture/applicationsets/utils/fixture.go [hunk 1]
```diff
@@ -112,9 +122,15 @@ func EnsureCleanState(t *testing.T) {
...
+	err2 := fixtureClient.KubeClientset.CoreV1().Namespaces().Delete(context.Background(), string(ArgoCDExternalNamespace), v1.DeleteOptions{PropagationPolicy: &policy})
 	if err2 != nil && !strings.Contains(err2.Error(), "not found") { // 'not found' error is expected
-		CheckError(err)
+		CheckError(err2)
+	}
+
+	// Delete the argocd-e2e-external namespace, if it exists
+	err3 := fixtureClient.KubeClientset.CoreV1().Namespaces().Delete(context.Background(), string(ArgoCDExternalNamespace2), v1.DeleteOptions{PropagationPolicy: &policy})
+	if err3 != nil && !strings.Contains(err3.Error(), "not found") { // 'not found' error is expected
+		CheckError(err3)
```
Comment (ishitasequeira) [inline test/e2e/fixture/applicationsets/utils/fixture.go:133]: we should cleanup `argocd-e2e-external2` as well to ensure clean state.

File: test/e2e/fixture/applicationsets/utils/fixture.go [hunk 2]
```diff
@@ -210,56 +235,45 @@ func waitForExpectedClusterState() error {
...
-		}
-
-		if msg == "" && err != nil && strings.Contains(err.Error(), "not found") {
-			// Success is an error containing 'applicationset-e2e' not found.
-			return nil
-		}
-
-		if msg == "" {
-			msg = err.Error()
+	for _, namespace := range []string{string(ApplicationsResourcesNamespace), string(ArgoCDExternalNamespace), string(ArgoCDExternalNamespace2)} {
```
Comment (ishitasequeira) [inline test/e2e/fixture/applicationsets/utils/fixture.go:238]: Can we use `fixtureClient.ExternalAppSetClientsets` instead of creating a new list to loop over?

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
Overall change looks good!! Few minor comments.

File: test/e2e/fixture/applicationsets/utils/fixture.go (hunk 1 above)
Comment (crenshaw-dev) [reply test/e2e/fixture/applicationsets/utils/fixture.go:133]: @ishitasequeira I think that's what's happening on line 131, right?

Comment (ishitasequeira) [reply test/e2e/fixture/applicationsets/utils/fixture.go:133]: Ahh my bad. Got confused with the comment added.

**Review by ishitasequeira — APPROVED** [review]
Approving the change to get into 2.9.0 GA

**Comment by speedfl** [comment]
Wow so fast! Thanks a lot @ishitasequeira and @crenshaw-dev 🙂
