### PR TITLE
fix: allow docker dhi helm charts to be used

### LINKED ISSUE #25811: Docker Hardened Images (dhi.io) Helm Charts not able to be used with ArgoCD
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**
When using a dhi.io helm chart, it fails with `Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = expected only a single oci content layer, got 2`

**To Reproduce**

Add the following application to ArgoCD
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        args:
          - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

    repoURL: oci://dhi.io/metrics-server-chart
    path: .
    targetRevision: 3.13.0
```

For reference here is the chart manifest
```bash
$ regctl manifest get dhi.io/metrics-server-chart:3.13.0
Name:                                     dhi.io/metrics-server-chart:3.13.0
MediaType:                                application/vnd.oci.image.manifest.v1+json
Digest:                                   sha256:1f4b80c3f52a0c9ea40610e442dda66e4330616d482c58f4359a209b2dd6c76a
Annotations:
  com.docker.dhi.compliance:              cis
  com.docker.dhi.created:                 2025-12-22T15:59:39Z
  com.docker.dhi.definition:              chart/metrics-server/helm/3
  com.docker.dhi.flavor:
  com.docker.dhi.name:                    dhi/metrics-server-chart
  com.docker.dhi.package-manager:
  com.docker.dhi.shell:
  com.docker.dhi.title:                   Metrics Server Helm chart 3.x
  com.docker.dhi.url:                     https://dhi.io/catalog/metrics-server-chart
  com.docker.dhi.variant:                 helm
  com.docker.dhi.version:                 3.13.0
  org.opencontainers.image.authors:       Docker, Inc. https://docker.com
  org.opencontainers.image.created:       2025-12-22T15:59:39Z
  org.opencontainers.image.description:   Metrics Server Helm chart 3.x
  org.opencontainers.image.documentation: https://dhi.io/catalog/metrics-server-chart/guides
  org.opencontainers.image.source:        https://github.com/docker-hardened-images/definitions
  org.opencontainers.image.title:         dhi/metrics-server-chart
  org.opencontainers.image.url:           https://dhi.io/catalog/metrics-server-chart
  org.opencontainers.image.vendor:        Docker, Inc.
  org.opencontainers.image.version:       3.13.0
Total Size:                               20.173kB

Config:
  Digest:                                 sha256:d09fda92703a20f55d35742b7fb6adbbd27591644c97d295ffc5094f4e2fc431
  MediaType:                              application/vnd.cncf.helm.config.v1+json
  Size:                                   747B

Layers:

  Digest:                                 sha256:f0ac7af00ba4c8544778e032df9dc80d721d6aefdfba2febb202cc7a685d9cbd
  MediaType:                              application/vnd.cncf.helm.chart.content.v1.tar+gzip
  Size:                                   14061B

  Digest:                                 sha256:7ba6524d69541852615bac2fdd0413b9c5fe25d92f0d9c49f69dc60056c01630
  MediaType:                              application/vnd.oci.image.layer.v1.tar+gzip
  Size:                                   6112B
```

**Expected behavior**
I would expect this to use the `application/vnd.cncf.helm.chart.content.v1.tar+gzip` since it is configured as a helm chart

**Version**

```shell
$ argocd version
argocd: v3.2.3
  BuildDate: 2025-12-24T15:46:00Z
  GitCommit: 2b6251dfedb54de40596272a73ed1fb19d740219
  GitTreeState: clean
  GitTag: v3.2.3
  GoVersion: go1.25.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2025-12-28T21:34:59-08:00" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:oci://dhi.io/metrics-server-chart,Path:.,TargetRevision:3.13.0,Helm:&ApplicationSourceHelm{ValueFiles:[$values/argocd/values/monitoring/metrics-server.yaml],Parameters:[]HelmParameter{},ReleaseName:,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,ValuesObject:nil,Namespace:,KubeVersion:,APIVersions:[],SkipTests:false,SkipSchemaValidation:false,},Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:,Name:,}/sha256:1f4b80c3f52a0c9ea40610e442dda66e4330616d482c58f4359a209b2dd6c76a"
time="2025-12-28T21:35:00-08:00" level=error msg="finished call" grpc.code=Unknown grpc.component=server grpc.error="expected only a single oci content layer, got 2" grpc.method=GenerateManifest grpc.method_type=unary grpc.request.deadline="2025-12-28T21:35:57-08:00" grpc.service=repository.RepoServerService grpc.start_time="2025-12-28T21:34:57-08:00" grpc.time_ms=2964.788 peer.address="10.42.2.246:58308" protocol=grpc
```

### PR DESCRIPTION
**Pull request by blakepettersson**
Docker has a set of OCI Helm charts used as a part of their Hardened Images offering, which doesn't work with our OCI support 😢 

Previously for Helm charts we checked for the presence of only one content layer (=a layer media type ending with `tar` or `tar+gzip`). The problem with that is that DHI Helm charts have two content layers, one with the actual Helm content, and another with SBOM content, failing the check.

Now we instead check to see if the image's `config.mediaType` is `application/vnd.cncf.helm.config.v1+json`, if so then only lookup a single layer == `application/vnd.cncf.helm.chart.content.v1.tar+gzip`, ignoring all others.

Fixes #25811.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: util/oci/client.go [hunk 1]
```diff
@@ -44,6 +44,8 @@ var (
 	indexLock  = sync.NewKeyLock()
 )
 
+const helmOCIConfigType = "application/vnd.cncf.helm.config.v1+json"
```
Comment (choejwoo) [inline util/oci/client.go]: NIT: Since we’re adding a const, would it make sense to also extract the Helm chart content `mediaType` string used in `isHelmOCI()` into the const block at the top of the file?
https://github.com/argoproj/argo-cd/blob/d11d0251865aa02bf9c21af41aedc556de569a46/util/oci/client.go#L590-L592 
Other than that, LGTM.

**Review by chansuke — APPROVED** [review]
lgtm

File: util/oci/client.go (hunk 1 above)
Comment (blakepettersson) [reply util/oci/client.go]: Sure makes sense, I added it now 😄

**Review by choejwoo — APPROVED** [review]
Thanks for addressing my comment, LGTM!

**Review by nitishfy — APPROVED** [review]

**Review by christianh814 — APPROVED** [review]
LGTM!

**Review by christianh814 — APPROVED** [review]

**Review by alexmt — APPROVED** [review]
