### PR TITLE
fix: validate empty server address for destination cluster (#4852)

### LINKED ISSUE #4852: argocli --dest-name argument fails with "Destination server missing from app spec"
**Describe the bug**

Trying to use `argocd app create --dest-name myclustername` fails with e.g.
> time="2020-11-17T07:25:01Z" level=fatal msg="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Destination server missing from app spec"

**Expected behavior**

An app would be created.

**Version**

Using the argocd cli out of the docker image `argoproj/argocd:v1.7.6@sha256:e561b4caa56a7ec41f59ba305b1f8158ada2c7eaee7a87d29fad8d88da650fec`

Edit: confirmed to also exist with 1.7.8

### PR DESCRIPTION
**Pull request by kshamajain99**
Signed-off-by: kshamajain99 <kshamajain99@gmail.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

fixes #4852

### CODE REVIEW

File: util/argo/argo.go [hunk 1]
```diff
@@ -506,6 +506,8 @@ func getDestinationServer(ctx context.Context, db db.ArgoDB, clusterName string)
 		return "", fmt.Errorf("there are %d clusters with the same name: %v", len(servers), servers)
 	} else if len(servers) == 0 {
 		return "", fmt.Errorf("there are no clusters with this name: %s", clusterName)
+	} else if servers[0] == "" {
```
Comment (alexmt) [inline util/argo/argo.go:509]: The `server[0]` is empty only if the Argo CD settings have an invalid cluster configuration ( cluster with missing server field  ). I think instead of trying to handle it here we need to find how such cluster configuration was created. 

I found another possible reason of #4852 : https://github.com/argoproj/argo-cd/issues/4852#issuecomment-730509010

**Review by alexmt — CHANGES_REQUESTED** [review]

File: util/argo/argo.go (hunk 1 above)
Comment (kshamajain99) [reply util/argo/argo.go:509]: @alexmt You are right, if --validate=false then we won't call 
https://github.com/argoproj/argo-cd/blob/59443ad18585258ba8c49d62b3a5bf5ad51a656a/util/argo/argo.go#L294

File: util/argo/argo.go [hunk 2]
```diff
@@ -301,6 +301,20 @@ func ValidateDestination(ctx context.Context, dest *argoappv1.ApplicationDestina
 	return nil
 }
 
+func SetDestinationServer(ctx context.Context, dest *argoappv1.ApplicationDestination, db db.ArgoDB) error {
```
Comment (alexmt) [inline util/argo/argo.go:304]: What is the difference between this method and `ValidateDestination` ? I think it is pretty much the same. Cannot we use `ValidateDestination` instead?

**Review by alexmt — CHANGES_REQUESTED** [review]

File: util/argo/argo.go (hunk 2 above)
Comment (kshamajain99) [reply util/argo/argo.go:304]: Not much, `ValidateDestination` has an additional validation like
https://github.com/argoproj/argo-cd/blob/c147320687c7bf0e3da885c9ed02fbfcb6b45c2c/util/argo/argo.go#L296

We can use `ValidateDestination` as well, which means `ValidateDestination` will move out of `if validate {}` check. I don't know why it was added to 
https://github.com/argoproj/argo-cd/blob/c147320687c7bf0e3da885c9ed02fbfcb6b45c2c/server/application/application.go#L752

**Review by alexmt — APPROVED** [review]
LGTM
