### PR TITLE
Fix a bug with cluster add when token secret is not first in list.

### LINKED ISSUE #2743: "cluster add" can break due to assumption about first Secret type in a ServiceAccounts list
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

"create cluster" can fail if another secret type is the first in the list for a ServiceAccount, despite the fact that a valid token secret does exist.

**To Reproduce**

I am not positive if this is purely an OpenShift thing or how frequently it happens, but when adding a cluster I got the following failure:

```
$ argocd cluster add admin                                                                                                          (admin/default)
INFO[0000] ServiceAccount "argocd-manager" already exists in namespace "kube-system" 
INFO[0000] ClusterRole "argocd-manager-role" updated    
INFO[0000] ClusterRoleBinding "argocd-manager-role-binding" already exists 
FATA[0001] Secret "argocd-manager-dockercfg-fd5fl" for service account "&ServiceAccount{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:argocd-manager,GenerateName:,Namespace:kube-system,SelfLink:/api/v1/namespaces/kube-system/serviceaccounts/argocd-manager,UID:36d1f96c-0aea-11ea-9009-028ddafea165,ResourceVersion:64019,Generation:0,CreationTimestamp:2019-11-19 12:32:44 -0400 AST,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,ManagedFields:[],},Secrets:[{  argocd-manager-dockercfg-fd5fl    } {  argocd-manager-token-pct8w    }],ImagePullSecrets:[{argocd-manager-dockercfg-fd5fl}],AutomountServiceAccountToken:nil,}" did not have a token 
```

Checking the ServiceAccount argo created:

```yaml
apiVersion: v1
imagePullSecrets:
- name: argocd-manager-dockercfg-fd5fl
kind: ServiceAccount
metadata:
  creationTimestamp: "2019-11-19T16:32:44Z"
  name: argocd-manager
  namespace: kube-system
  resourceVersion: "64019"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/argocd-manager
  uid: 36d1f96c-0aea-11ea-9009-028ddafea165
secrets:
- name: argocd-manager-dockercfg-fd5fl
- name: argocd-manager-token-pct8w
```

The two secret types:

```
argocd-manager-dockercfg-fd5fl                       kubernetes.io/dockercfg               1      3m40s
argocd-manager-token-pct8w                           kubernetes.io/service-account-token   4      3m40s
```

As you can see, the token secret we want is second in the list, which is probably valid, but the add code assumes it will be the first:

https://github.com/argoproj/argo-cd/blob/master/util/clusterauth/clusterauth.go#L168

**Expected behavior**

The code should be updated to scan the list of secrets for one of type kubernetes.io/service-account-token rather than use the first in the list.

**Version**

```shell
argocd: v1.2.0+674978c
  BuildDate: 2019-09-04T21:26:04Z
  GitCommit: 674978cd587701b39e81fce6d5c960b6d76d5882
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.2.4+ad7a69a
  BuildDate: 2019-10-23T20:06:50Z
  GitCommit: ad7a69a79883b7767cbeb88ca9a36d28277bd4ab
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

### PR DESCRIPTION
**Pull request by dgoodwin**
ServiceAccounts contain a list of secret references, in some cases these
can be of other types (dockercfg) and the bearer token is not
necessarily going to be first in the list, in which case cluster add
will fail.

Instead this change iterates the list of secret references, looks each
up, and checks it's type. If it is the correct token type we have found
our secret and proceed, otherwise we keep looking.

Fixes #2743

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to the README.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexec** [comment]
Looks good so far. Any thoughts on how to write tests for this?

**Comment by dgoodwin** [comment]
Yes, my apologies should have thought of that. Added a test with a dockercfg secret first in the list.

File: util/clusterauth/clusterauth.go [hunk 1]
```diff
@@ -165,19 +173,25 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string) (strin
 		if len(serviceAccount.Secrets) == 0 {
 			return false, nil
 		}
-		secretName = serviceAccount.Secrets[0].Name
-		return true, nil
+		// Scan all secrets looking for one of the correct type:
+		for _, oRef := range serviceAccount.Secrets {
+			var getErr error
+			secret, getErr = clientset.CoreV1().Secrets(ns).Get(oRef.Name, metav1.GetOptions{})
```
Comment (alexec) [inline util/clusterauth/clusterauth.go]: minor - can you rename to `err`?

File: util/clusterauth/clusterauth.go [hunk 2]
```diff
@@ -165,19 +173,25 @@ func InstallClusterManagerRBAC(clientset kubernetes.Interface, ns string) (strin
 		if len(serviceAccount.Secrets) == 0 {
```
Comment (alexec) [inline util/clusterauth/clusterauth.go]: this guard can be removed

File: util/clusterauth/clusterauth.go (hunk 1 above)
Comment (alexec) [reply util/clusterauth/clusterauth.go]: This results in a change from 1 to N+1, would you typically expect this to return on the 1st secret? There's no way to get this from `oRef`?

Comment (dgoodwin) [reply util/clusterauth/clusterauth.go]: Was a little nervous about using "err" here as it's declared outside the wrap call, but it looks like it's probably safe to do so, will adjust.

Comment (dgoodwin) [reply util/clusterauth/clusterauth.go]: I don't think there is any way to get it from oRef unfortunately, the type is an attribute specific to secret and thus not present on the generic ObjectReference. However in this case it is unlikely a SA has more than 3 secrets, and I can't imagine any scenario we'd see more than 5-10.

It would often return on the 1st secret I'm sure given no one else has found this problem yet.

**Comment by dgoodwin** [comment]
Updates pushed.

**Review by alexec — APPROVED** [review]
