### PR TITLE
fix(cli): avoid panic in configure command when no local config exists (#23085)

### LINKED ISSUE #23085: SIGSEGV on configure if the config file does not exist yet
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

A SIGSEGV occurs when attempting to configure a certificate authority within an OCI image.

**To Reproduce**

```powershell
docker run -it --entrypoint= ghcr.io/argoproj/argo-cd/argocd:3.1.0-146a7798 sh
argocd configure --certificate-authority ca.pem
```

**Expected behavior**

An error is printed since ca.pem does not exist (to keep the reproducer minimal I left out the creation of `ca.pem`).

**Screenshots**

n/a

**Version**

```shell
argocd: v3.1.0+146a779
  BuildDate: 2025-05-21T03:03:58Z
  GitCommit: 146a7798ed1a0d63fb20dff49fffe4ed7d1b8b9e
  GitTreeState: clean
  GoVersion: go1.24.3
  Compiler: gc
  Platform: linux/amd64
{"level":"fatal","msg":"Argo CD server address unspecified","time":"2025-05-21T13:09:46Z"}
```

**Logs**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x3e84d35]

goroutine 1 [running]:
github.com/argoproj/argo-cd/v3/cmd/argocd/commands.NewConfigureCommand.func1(0xc00105f200?, {0x4d96258?, 0x4?, 0x4d9625c?})
        /go/src/github.com/argoproj/argo-cd/cmd/argocd/commands/configure.go:31 +0x95
github.com/spf13/cobra.(*Command).execute(0xc001074608, {0xc00059c680, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1019 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0xc000724008)
        /go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x46f
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071
main.main()
        /go/src/github.com/argoproj/argo-cd/cmd/main.go:87 +0x3c5
```

### PR DESCRIPTION
**Pull request by krapie**
Currently, the `argocd configure` command panics when no local config exists at the expected path. This is because `localconfig.ReadLocalConfig()` returns `nil` for both `LocalConfig` and `error`.

https://github.com/argoproj/argo-cd/blob/fe6aaad4f0a4eebcdf2722d75f5b0bc9a6c36b7e/util/localconfig/localconfig.go#L92-L95

As a result, `localCfg.PromptsEnabled` in `configure.go` triggers a panic due to a nil reference.

https://github.com/argoproj/argo-cd/blob/fe6aaad4f0a4eebcdf2722d75f5b0bc9a6c36b7e/cmd/argocd/commands/configure.go#L31

This PR adds a nil check for `localCfg` to prevent the CLI from panicking and to provide a clearer error message explaining why the command failed to execute, just like other commands like `context.go`.

https://github.com/argoproj/argo-cd/blob/fe6aaad4f0a4eebcdf2722d75f5b0bc9a6c36b7e/cmd/argocd/commands/context.go#L86-L90

Fixes #23085

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: cmd/argocd/commands/configure.go [hunk 1]
```diff
@@ -27,6 +27,10 @@ argocd configure --prompts-enabled=false`,
 		Run: func(_ *cobra.Command, _ []string) {
 			localCfg, err := localconfig.ReadLocalConfig(globalClientOpts.ConfigPath)
 			errors.CheckError(err)
+			if localCfg == nil {
+				fmt.Println("No local configuration found.")
```
Comment (nitishfy) [inline cmd/argocd/commands/configure.go]:
```suggestion
				log.Println("No local configuration found.")
```
I'd prefer printing it as log.

**Review by nitishfy — CHANGES_REQUESTED** [review]
Overall LGTM!

File: cmd/argocd/commands/configure.go (hunk 1 above)
Comment (krapie) [reply cmd/argocd/commands/configure.go]: Hello @nitishfy, thank you for the prompt review :)

I noticed that the `configure.go` is currently using `fmt` for logging. Would you like me to update those to use `log` as well?

https://github.com/argoproj/argo-cd/blob/fe6aaad4f0a4eebcdf2722d75f5b0bc9a6c36b7e/cmd/argocd/commands/configure.go#L36-L38

Comment (nitishfy) [reply cmd/argocd/commands/configure.go]: thank you for pointing it.

**Review by nitishfy — APPROVED** [review]

File: cmd/argocd/commands/configure.go (hunk 1 above)
Comment (krapie) [reply cmd/argocd/commands/configure.go]: FYI, other CLI files like `account.go` are using `fmt`. Thanks for the confirmation 😄

**Comment by krapie** [comment]
Mistakenly committed requested `log` changes, reverting back to `fmt` as per Slack discussion with nitishfy@.

**Comment by krapie** [comment]
Hello @nitishfy, could you please review the PR again so that the PR can be merged afterwards?

File: cmd/argocd/commands/configure.go (hunk 1 above)
Comment (rumstead) [inline cmd/argocd/commands/configure.go]: Should this be a `log.Fatal` or at least a `os.Exit(1)`?

Comment (krapie) [reply cmd/argocd/commands/configure.go]: Thanks for pointing it out. I agree that the code should use `os.Exit(1)` instead of `return`. As for `log.Fatal`, I think using `fmt` is more consistent with the rest of the CLI codebase. Referencing `applicationset.go` as an example of similar error handling. 

https://github.com/argoproj/argo-cd/blob/678f61b8d3a4ce4443a49983f7deae9c80ad8983/cmd/argocd/commands/applicationset.go#L142-L145

**Review by rumstead — APPROVED** [review]

**Review by agaudreault — APPROVED** [review]
