### PR TITLE
fix: credential cleanup func being called too early for plugins

### LINKED ISSUE #7995: Private repo credentials deleted from disk before plugin is run
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using ArgoCD 2.2.0 with an existing plugin (Not using the new plugin server), the environment contains a `GIT_SSH_COMMAND` which includes an ssh identity on shared memory containing the private key for the detected repository, placed there by ArgoCD. In the latest changes for the CMP server, the file is deleted before it can be read due to the pluginEnv's being constructed in a seperate `getPluginEnvs` method now which itself does a defer cleanup of the SSH key before the plugin itself has run.

https://github.com/argoproj/argo-cd/blame/6d8ff61b16163e960126f2205166513d924a64a9/reposerver/repository/repository.go#L1142

**To Reproduce**

Create an application with a config management plugin that internally uses git and is pointed at a private repository.
Attempt to refresh the application

**Expected behavior**

The identity file contained in the GIT_SSH_COMMAND is not deleted before the plugin is run

**Screenshots**

N/A

**Version**

2.2.0

**Logs**
```
Warning: Identity file /dev/shm/254152362 not accessible: No such file or directory.
```

### PR DESCRIPTION
**Pull request by dhild**
The io.Closer returned from the call to creds.Environ() removes the
underlying file. The desired behavior here is to clean up the
credentials files only after the plugin code has been run, which now
happens one level up in the call stack.

Fixes #7995, #8820

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them. _N/A_
* [x] Does this PR require documentation updates? _No_
* [x] I've updated documentation as required by this PR. _N/A_
* [x] ~Optional. My organization is added to USERS.md.~
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -1354,10 +1357,11 @@ func runConfigManagementPluginSidecars(ctx context.Context, appPath, repoPath st
 	}
 
 	// generate manifests using commands provided in plugin config file in detected cmp-server sidecar
-	env, err := getPluginEnvs(envVars, q, creds)
+	cleanup, env, err := getPluginEnvs(envVars, q, creds)
```
Comment (davemann-mgl) [inline reposerver/repository/repository.go:1360]: IMO it's worth calling `cleanup()` regardless of `error` ?

Comment (dhild) [reply reposerver/repository/repository.go:1360]: That's a good observation. Technically, with the code as written, I think it should already be called, because [`getPluginEnvs` calls `cleanup`](https://github.com/argoproj/argo-cd/pull/8389/files#diff-66db997cf6001ce63d5c5803380962f4b474aae67abacc9e86192673080d2c59R1323) in the event that it _does_ return an `error` where `cleanup` may need to be called.

I'm partial to coding with that convention (assume you'd only need to `defer cleanup()` if the returned error is non-nil). This kind of cleanup pattern matches what I've experienced in go standard libraries, e.g. [http.Do](https://pkg.go.dev/net/http#Client.Do), which states:
> On error, any Response can be ignored. A non-nil Response with a non-nil error only occurs when CheckRedirect fails, and even then the returned Response.Body is already closed.

All that being said, I'm a first time contributor here so some guidance on how to proceed would be appreciated; if you're not swayed by this explanation then I'm happy to make the change.

**Review by crenshaw-dev — APPROVED** [review]
Nicely done. Thanks!

**Comment by crenshaw-dev** [comment]
@dhild apologies for the about-face, but we're planning to revert this change for the reasons described here: https://github.com/argoproj/argo-cd/issues/8820#issuecomment-1099247399

We still plan to provide a secure way for sidecar CMPs to get private git creds. But we think that should only be implemented for sidecars.
