### PR TITLE
fix: tree output with app selector permission denied. 

### LINKED ISSUE #18714: tree output with app selector permission denied
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

when specifying the output flag with the value `tree` i get permission denied error

**To Reproduce**

```
# works 
argocd app sync my-app --output tree

# not working 
argocd app sync -l app=my-app --output tree
```

**Expected behavior**

**Screenshots**

**Version**

```shell
argocd: v2.11.2+25f7504
  BuildDate: 2024-05-23T15:31:09Z
  GitCommit: 25f7504ecc198e7d7fdc055fdb83ae50eee5edd0
  GitTreeState: clean
  GoVersion: go1.22.3
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.10.9+c071af8
  BuildDate: 2024-04-30T15:53:28Z
  GitCommit: c071af808170bfc39cbdf6b9be4d0212dd66db0c
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.3+gf03cc04
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

```
argocd-server-857d9cb6b7-cd8hl time="2024-06-18T11:40:43Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied" grpc.code=PermissionDenied grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2024-06-18T11:40:43Z" grpc.time_ms=0.583 span.kind=server system=grpc
```

### PR DESCRIPTION
**Pull request by thecooldrop**
The application name which was passed into the function was a namespace-qualified name for the application, but actually a simple non-qualified name was needed.

This leads to issue on the kube-apiserver side
where qualified app name is used to retrieve
the resource from a lister, leading to a cache-miss basically, since app was looked up by namespace/namespace/appname key, instead of namespace/appname key.

Should be cherry-picked into supported releases ( How can I do that ? )

Closes #18714

There is an issue with this PR though and I would like to ask for clarification. The "bug" was literally usage of wrong variable, which is part of the whole flow of the app-sync command. I was unable to find the e2e tests testing the functionality of the commands as whole. Are there any? If yes, where should I implement a test, that this feature now works?

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates? => No
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged. => No, see description above
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [X] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: cmd/argocd/commands/app.go [hunk 1]
```diff
@@ -2400,7 +2400,7 @@ func waitOnApplicationStatus(ctx context.Context, acdClient argocdclient.Client,
 				_ = w.Flush()
 			}
 		case "tree":
-			mapUidToNode, mapParentToChild, parentNode, mapNodeNameToResourceState := resourceParentChild(ctx, acdClient, appName, appNs)
+			mapUidToNode, mapParentToChild, parentNode, mapNodeNameToResourceState := resourceParentChild(ctx, acdClient, appRealName, appNs)
```
Comment (ishitasequeira) [inline cmd/argocd/commands/app.go:2403]: @thecooldrop , can you check for `case "tree=detailed"` as well?

Comment (thecooldrop) [reply cmd/argocd/commands/app.go:2403]: There was a same error there as well. Fixed it.

**Review by ishitasequeira — APPROVED** [review]
Thank you @thecooldrop!!  LGTM!!
