### PR TITLE
fix: argocd cluster add <context> --in-cluster

### LINKED ISSUE #6233: argocd cluster add <context> --in-cluster fails with `x509: certificate signed by unknown authority`
It seems the `--in-cluster` flag in `argocd cluster add` can fail like so:

```
$ argocd cluster add <CONTEXT> --in-cluster
 INFO[0001] ServiceAccount "argocd-manager" already exists in namespace "kube-system"  
INFO[0001] ClusterRole "argocd-manager-role" updated     
INFO[0001] ClusterRoleBinding "argocd-manager-role-binding" updated 
 FATA[0002] rpc error: code = Unknown desc = Get "https://kubernetes.default.svc/version?timeout=32s": x509: certificate signed by unknown authority 
```

I believe this is happening because it's trying to use the certs of the kubeconfig rather than the in-cluster certs.

Possible fixes:

1. In CLI, we can nil out the CA/Cert data from the context (hoping that it will fall back to the certificate of the pod). Not sure if this will work:
 
```
			clst := cmdutil.NewCluster(contextName, clusterOpts.Namespaces, conf, managerBearerToken, awsAuthConf, execProviderConf)
			if clusterOpts.InCluster {
				clst.Server = common.KubernetesInternalAPIServerAddr
				clst.Config.TLSClientConfig.CAData = nil   // << don't use cert from context 
				clst.Config.TLSClientConfig.CertData = nil  // << don't use cert from context
			}
```

2. On server side, when we see `https://kubernetes.default.svc` is the cluster being registered, we fill in cert data of the *in-cluster* cert.

```golang
func (s *Server) Create(ctx context.Context, q *cluster.ClusterCreateRequest) (*appv1.Cluster, error) {
	if err := s.enf.EnforceErr(ctx.Value("claims"), rbacpolicy.ResourceClusters, rbacpolicy.ActionCreate, q.Cluster.Server); err != nil {
		return nil, err
	}
	c := q.Cluster
	if c.Server == "https://kubernetes.default.svc" {
		c.Config.TLSClientConfig = // < FILL with in-cluster cert data
	}
```

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by kshamajain99**
fixes https://github.com/argoproj/argo-cd/issues/6233

We set bearer token if either of certData and KeyData is missing, even if `--in-cluster` option is provided. 
https://github.com/argoproj/argo-cd/blob/cc4eea0d6951f1025c9ebb487374658186fa8984/cmd/util/cluster.go#L96-L98

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -2278,7 +2278,7 @@ func (c *Cluster) RawRestConfig() *rest.Config {
 		} else {
 			config, err = clientcmd.BuildConfigFromFlags("", filepath.Join(os.Getenv("HOME"), ".kube", "config"))
 		}
-	} else if c.Server == KubernetesInternalAPIServerAddr && c.Config.Username == "" && c.Config.Password == "" && c.Config.BearerToken == "" {
```
Comment (alexmt) [inline pkg/apis/application/v1alpha1/types.go:2281]: I think it will break existing in-clusters config with bearer tokens: Argo CD might incorrectly ignore configured in-cluster config if it has bearer token.

I bearer token is missing for EKS clusters etc. So I would suggest to add move checks into if instead of removing bearer token check:

```
} else if c.Server == KubernetesInternalAPIServerAddr && c.Config.Username == "" && c.Config.Password == "" && c.Config.BearerToken == "" && c.Config.AWSAuthConfig == nil && c.Config.ExecProviderConfig == nil 	{
```

**Review by alexmt — CHANGES_REQUESTED** [review]

File: pkg/apis/application/v1alpha1/types.go (hunk 1 above)
Comment (kshamajain99) [reply pkg/apis/application/v1alpha1/types.go:2281]: @alexmt the problem that we ran into was that for eks cluster certData and keyData were missing. And, because of that argocd-cli appended bearer token to cluster config (see logic below). And, hence cluster config was incorrectly selected to be TLSClientConfig instead of in-cluster config. 

https://github.com/argoproj/argo-cd/blob/cc4eea0d6951f1025c9ebb487374658186fa8984/cmd/util/cluster.go#L96-L98

Add more checks will not solve this problem #6233

**Review by alexmt — APPROVED** [review]
LGTM. Thank you!
