### PR TITLE
Use gRPC timeout for sidecar CMPs (#8131)

### LINKED ISSUE #8131: 5-second GRPC timeouts causing sync failure in sidecar plugin
**Describe the bug**
I'm trying to get [Tanka](https://tanka.dev/) working as a sidecar plugin, and I think I'm mostly there, but I'm getting the following error when trying to sync my app:
```
rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
When I look at the logs of the Tanka container, I see that the init and generate commands are succeeding, but taking up to 30 seconds. I also see log messages like this one:
```
time="2022-01-10T16:07:36Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.request.deadline="2022-01-10T16:07:13Z" grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2022-01-10T16:07:08Z" grpc.time_ms=27908.912 span.kind=server system=grpc
```
I've googled around and tried changing application controller settings like `repo-server-timeout-seconds`, `operation-processors` and `status-processors`, but it seems to have no effect, the `grpc.request.deadline` in these logs is always 5 seconds after `grpc.start_time`...
Is there a way to avoid this timeout/failure?

I first [posted about this in the CNCF Slack's #argo-cd channel](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1641831516135400), and it was suggested I make this issue.

**To Reproduce**

My Tanka plugin config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tanka-cmp
  annotations:
    app.kubernetes.io/part-of: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: tanka
    spec:
      version: v1.0
      init:
        command: [jb, install]
      generate:
        command: [sh, -c]
        args: ["/usr/local/bin/tk show --dangerous-allow-redirect $TANKA_JSONNET_PATH"]
      discover:
        fileName: "./jsonnetfile.json"
      allowConcurrency: true
      lockRepo: false
```

**Expected behavior**

The app should sync, since I can see the init and generate commands are succeeding from the Tanka container logs.

**Version**

```shell
argocd version
argocd: v2.1.2+7af9dfb.dirty
  BuildDate: 2021-09-02T21:28:55Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: dirty
  GoVersion: go1.17
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.2.2+03b17e0
  BuildDate: 2022-01-01T06:27:52Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Fixes https://github.com/argoproj/argo-cd/issues/8131

Previously, we had a hard-coded timeout in the CMP server client of 5s.

This change makes sure that all paths calling CMPs pass along their context (i.e. their timeout) to the CMP server.

The CMP server now creates its own context with a deadline 100ms earlier than the caller's deadline so there's enough time to send back a failure message.

Each command run by a CMP will also respect the `ARGOCD_EXEC_TIMEOUT`, which defaults to 90s.

### CODE REVIEW

File: cmd/argocd/commands/app.go [hunk 1]
```diff
@@ -762,7 +762,7 @@ func getLocalObjects(app *argoappv1.Application, local, localRepoRoot, appLabelK
 func getLocalObjectsString(app *argoappv1.Application, local, localRepoRoot, appLabelKey, kubeVersion string, kustomizeOptions *argoappv1.KustomizeOptions,
 	configManagementPlugins []*argoappv1.ConfigManagementPlugin, trackingMethod string) []string {
 
-	res, err := repository.GenerateManifests(local, localRepoRoot, app.Spec.Source.TargetRevision, &repoapiclient.ManifestRequest{
+	res, err := repository.GenerateManifests(context.Background(), local, localRepoRoot, app.Spec.Source.TargetRevision, &repoapiclient.ManifestRequest{
```
Comment (crenshaw-dev) [inline cmd/argocd/commands/app.go:765]: `context.Background()` is fine here, because it's the CLI. We don't really want a timeout.

File: cmpserver/plugin/plugin.go [hunk 2]
```diff
@@ -55,17 +66,26 @@ func environ(envVars []*apiclient.EnvEntry) []string {
 
 // GenerateManifest runs generate command from plugin config file and returns generated manifest files
 func (s *Service) GenerateManifest(ctx context.Context, q *apiclient.ManifestRequest) (*apiclient.ManifestResponse, error) {
+	bufferedCtx, cancel := buffered_context.WithEarlierDeadline(ctx, 100*time.Millisecond)
```
Comment (crenshaw-dev) [inline cmpserver/plugin/plugin.go:69]: Is 100ms reasonable? Should it be relocated to somewhere with other constants? Should it be configurable?

File: util/buffered_context/buffered_context_test.go [hunk 3]
```diff
@@ -0,0 +1,37 @@
+package buffered_context_test
+
+import (
+	"context"
+	"testing"
+	"time"
+
+	"gopkg.in/go-playground/assert.v1"
```
Comment (alexmt) [inline util/buffered_context/buffered_context_test.go:8]: I think you meant to use `"github.com/stretchr/testify/assert"`?

File: util/grpc/grpc.go [hunk 4]
```diff
@@ -157,6 +158,7 @@ func WithTimeout(duration time.Duration) grpc.UnaryClientInterceptor {
 		clientDeadline := time.Now().Add(duration)
 		ctx, cancel := context.WithDeadline(ctx, clientDeadline)
 		defer cancel()
+		fmt.Printf("calling %s with timeout %v from now\n", method, duration)
```
Comment (alexmt) [inline util/grpc/grpc.go:161]: This is for debugging, right? please use `log.Debug` instead.

File: cmpserver/plugin/plugin.go [hunk 5]
```diff
@@ -82,6 +103,9 @@ func (s *Service) GenerateManifest(ctx context.Context, q *apiclient.ManifestReq
 
 // MatchRepository checks whether the application repository type is supported by config management plugin server
 func (s *Service) MatchRepository(ctx context.Context, q *apiclient.RepositoryRequest) (*apiclient.RepositoryResponse, error) {
+	bufferedCtx, cancel := buffered_context.WithEarlierDeadline(ctx, 100*time.Millisecond)
```
Comment (alexmt) [inline cmpserver/plugin/plugin.go:106]: I think this time is internal implementation details, so no need to configure it. I would introduce a const though.

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you @crenshaw-dev ! Added few minor comments

File: cmpserver/plugin/plugin.go [hunk 6]
```diff
@@ -32,11 +36,19 @@ func NewService(initConstants CMPServerInitConstants) *Service {
...
 	}
-	cmd := exec.Command(command.Command[0], append(command.Command[1:], command.Args...)...)
+	cmd := exec.CommandContext(ctx, command.Command[0], append(command.Command[1:], command.Args...)...)
+
+	// Make sure the command is killed immediately on timeout. https://stackoverflow.com/a/29552044/684776
+	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
+	go func() {
+		<-ctx.Done()
+		_ = syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
+	}()
```
Comment (jannfis) [inline cmpserver/plugin/plugin.go:50]: I think you want to use the process group ID instead of the process ID as argument to `syscall.Kill()` here, because you specify it as negative number, or specify just the command's PID as positive number.

From the manpage to `kill(2)`:

```
       The kill() system call can be used to send any signal to any process group or process.

       If pid is positive, then signal sig is sent to the process with the ID specified by pid.

       If pid equals 0, then sig is sent to every process in the process group of the calling process.

       If  pid  equals  -1,  then  sig is sent to every process for which the calling process has permission to send signals, except for
       process 1 (init), but see below.

       If pid is less than -1, then sig is sent to every process in the process group whose ID is -pid.
```

File: util/buffered_context/buffered_context_test.go (hunk 3 above)
Comment (crenshaw-dev) [reply util/buffered_context/buffered_context_test.go:8]: Ah yep. Thanks GoLand. :-)

File: util/grpc/grpc.go (hunk 4 above)
Comment (crenshaw-dev) [reply util/grpc/grpc.go:161]: Ah I'll just kill that line. I was trying to figure out who was calling what, and `log` wasn't available in that module.

(I assume "`log` wasn't available in that module" is a reasonable thing to say. Basically GoLand complained, so I went with easy. :-))

File: cmpserver/plugin/plugin.go (hunk 6 above)
Comment (crenshaw-dev) [reply cmpserver/plugin/plugin.go:54]: Good catch. I'm actually not sure why this worked with the process ID. Will change and test with the group ID.

Comment (crenshaw-dev) [reply cmpserver/plugin/plugin.go:54]: Oh! The linked solution didn't work for me, that's why I went with this one. I just pasted the wrong link. https://stackoverflow.com/a/38133948/684776

Comment (crenshaw-dev) [reply cmpserver/plugin/plugin.go:54]: I had to do some reading, but I think I finally understand what this code is actually doing. From the [syscall docs](https://pkg.go.dev/syscall#SysProcAttr):

	// Setpgid sets the process group ID of the child to Pgid,
	// or, if Pgid == 0, to the new child's process ID.
	Setpgid bool

Since I'm not setting Pgid, the group ID is the same as the process ID.

Using the process ID saves a call to `syscall.Getpgid`, which returns an error that would have to be handled.

Comment (crenshaw-dev) [reply cmpserver/plugin/plugin.go:54]: Locally (in osx) the commands started by `sh -c` don't seem to run in the same group as `sh`. So I'm not sure what benefit killing the `sh` group would provide.

I'm testing again with just killing the `sh` process.

Comment (crenshaw-dev) [reply cmpserver/plugin/plugin.go:54]: With the go func commented out, the CMP server doesn't send a response immediately. This makes me think that the sub-process(es) aren't killed along with the root process.

I'll try again but kill the PID instead of the GID.

Comment (crenshaw-dev) [reply cmpserver/plugin/plugin.go]: Alright. I've developed a thousand-yard stare tinkering with this.

Running locally, I don't need this custom kill logic. The process is always killed immediately at timeout.

Running in Docker, the following combinations all fail to kill the process at timeout:

```go
	// no additional kill logic
```

```go
	// just setting the group id
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
```

```go
	// setting the group id and killing by process id
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	go func() {
		<-ctx.Done()
		_ = syscall.Kill(cmd.Process.Pid, syscall.SIGKILL)
	}()
```

This is the only combination that worked:

```go
	// kill the process by group id (which will always be the same as the process id)
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	go func() {
		<-ctx.Done()
		_ = syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
	}()
```

I've added a unit test and a comment about pid==gid. I have no idea if this issue will present in other environments. But I'm confident the extra code won't do any harm.

**Comment by crenshaw-dev** [comment]
I was hoping I could go my whole professional life without _really_ having to know what a race condition is.

File: cmpserver/plugin/plugin.go [hunk 7]
```diff
@@ -32,14 +43,78 @@ func NewService(initConstants CMPServerInitConstants) *Service {
...
 		return "", fmt.Errorf("Command is empty")
 	}
-	cmd := exec.Command(command.Command[0], append(command.Command[1:], command.Args...)...)
+	cmd := exec.CommandContext(ctx, command.Command[0], append(command.Command[1:], command.Args...)...)
+
 	cmd.Env = env
 	cmd.Dir = path
-	return executil.Run(cmd)
+
+	execId, err := rand.RandString(5)
```
Comment (crenshaw-dev) [inline cmpserver/plugin/plugin.go:55]: I pulled all this from `pkg` rather than putting up a PR and making that code more convoluted.

The error stuff could probably be simplified here, but I'm trying to match current behavior as closely as possible since I don't know the background on why the `pkg` code was written the way it was.

File: cmpserver/plugin/plugin.go [hunk 8]
```diff
@@ -32,14 +43,78 @@ func NewService(initConstants CMPServerInitConstants) *Service {
...
+	// Make sure the command is killed immediately on timeout. https://stackoverflow.com/a/38133948/684776
+	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
+
+	start := time.Now()
+	err = cmd.Start()
+	if err != nil {
+		return "", err
+	}
+
+	go func() {
```
Comment (crenshaw-dev) [inline cmpserver/plugin/plugin.go:79]: This has to be after `cmd.Start()` to avoid the race condition, and that's why I copied this function in from `pkg`.

File: util/buffered_context/buffered_context_test.go [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+	"context"
+	"testing"
+	"time"
+
+	"github.com/stretchr/testify/assert"
+
+	"github.com/argoproj/argo-cd/v2/util/buffered_context"
+)
+
+func TestWithEarlierDeadline_NoDeadline(t *testing.T) {
```
Comment (jannfis) [inline util/buffered_context/buffered_context_test.go:13]: :+1:

File: util/buffered_context/buffered_context_test.go [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+	bufferedCtx, cancel := buffered_context.WithEarlierDeadline(ctx, 100*time.Millisecond)
+	defer cancel()
+
+	assert.Equal(t, ctx, bufferedCtx)
+
+	_, hasDeadline := bufferedCtx.Deadline()
+	assert.Equal(t, false, hasDeadline)
+}
+
+func TestWithEarlierDeadline_WithDeadline(t *testing.T) {
```
Comment (jannfis) [inline util/buffered_context/buffered_context_test.go:25]: :+1:

File: util/buffered_context/buffered_context.go [hunk 11]
```diff
@@ -0,0 +1,22 @@
...
+// and a pointer to a cancel function for the new context.
+//
+// If the given context doesn't have a deadline, return the original context unchanged and a do-nothing cancel function.
+func WithEarlierDeadline(originalCtx context.Context, buffer time.Duration) (context.Context, context.CancelFunc) {
+	var cancelFunc context.CancelFunc = func() {}
+	bufferedCtx := originalCtx
+	if deadline, ok := originalCtx.Deadline(); ok {
+		newCtx, newCancelFunc := context.WithDeadline(originalCtx, deadline.Add(-1*buffer))
+		bufferedCtx = newCtx
+		cancelFunc = newCancelFunc
```
Comment (jannfis) [inline util/buffered_context/buffered_context.go:19]: I was just wondering why this is not condensed into a simple

```go
bufferedCtx, cancelFunc = context.WithDeadline(originalCtx, deadline.Add(-1*buffer)=
```

File: cmpserver/plugin/plugin.go [hunk 12]
```diff
@@ -32,14 +43,78 @@ func NewService(initConstants CMPServerInitConstants) *Service {
...
+
+	execId, err := rand.RandString(5)
+	if err != nil {
+		return "", err
+	}
+	logCtx := log.WithFields(log.Fields{"execID": execId})
+
+	// log in a way we can copy-and-paste into a terminal
+	args := strings.Join(cmd.Args, " ")
+	logCtx.WithFields(log.Fields{"dir": cmd.Dir}).Info(args)
```
Comment (jannfis) [inline cmpserver/plugin/plugin.go:63]: I was wondering, should we let the user know (in the docs) not to pass confidential information in the command line since it's gonna be logged?

**Review by jannfis — APPROVED** [review]
LGTM with just a few minor comments and nits

File: util/buffered_context/buffered_context.go (hunk 11 above)
Comment (crenshaw-dev) [reply util/buffered_context/buffered_context.go:19]: Ha. Because I'm a golang noob and tried to use `:=` the first time. Fixing. :-)

File: cmpserver/plugin/plugin.go (hunk 12 above)
Comment (crenshaw-dev) [reply cmpserver/plugin/plugin.go:63]: Yep, good idea.

**Review by alexmt — APPROVED** [review]
LGTM. Thank you!

**Comment by gmalkov** [comment]
Awesome! Looks like this change turned out to be more involved than it seemed originally, thanks for pushing this through @crenshaw-dev !!!

**Comment by crenshaw-dev** [comment]
@gmalkov yeah, a little bit, but hopefully we can use this chained-timeouts pattern elsewhere so it'll be worth the up-front effort. You bet! I hope the Tanka effort goes well!
