### PR TITLE
fix: Normalize Helm chart path when chart name contains a slash

### LINKED ISSUE #3981: None of the charts from JFrog's Helm repository can be installed via ArgoCD
**Describe the bug**

None of the charts from JFrog's helm repository (`https://repo.chartcenter.io`) can be installed via ArgoCD.
I'm trying to create an application for Artifactory (jfrog/artifactory:10.0.6) and it fails; it actually fails with every helm chart in their repository. **However, when installing via the `helm` command (`helm install ...`), it works**. Issue seems to be with ArgoCD's repo-server

**To Reproduce**
- Deploy ArgoCD
```shell
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.6.1/manifests/install.yaml
```
- (wait for it to deploy)

```shell
kubectl port-forward svc/argocd-server -n argocd 9999:80
```

- Navigate to http://localhost:9999
- Login and create an application with the following helm chart (as per https://github.com/jfrog/charts/tree/master/stable/artifactory):
  - Repo URL: https://repo.chartcenter.io
  - Chart: jfrog/artifactory
  - Version: 10.0.6

**Expected behavior**

Application should get created successfully.

**Screenshots**

image

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

These are the logs from Repo Server

```
time="2020-07-22T14:55:49Z" level=info msg="app details cache miss: 10.0.6/&ApplicationSource{RepoURL:https://repo.chartcenter.io,Path:,TargetRevision:10.0.6,Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:jfrog/artifactory,}"
time="2020-07-22T14:55:49Z" level=info msg="helm pull --destination /tmp/helm598770335 --version 10.0.6 --repo https://repo.chartcenter.io jfrog/artifactory" dir="/tmp/https:__repo.chartcenter.io" execID=lQEBx
time="2020-07-22T14:55:52Z" level=error msg="finished unary call with code Unknown" error="rename /tmp/helm598770335/artifactory-10.0.6.tgz /tmp/https:__repo.chartcenter.io/jfrog/artifactory-10.0.6.tgz: no such file or directory" grpc.code=Unknown grpc.method=GetAppDetails grpc.request.deadline="2020-07-22T14:56:49Z" grpc.service=repository.RepoServerService grpc.start_time="2020-07-22T14:55:49Z" grpc.time_ms=2932.979 span.kind=server system=grpc
```

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #3981 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

File: util/helm/client_test.go [hunk 1]
```diff
@@ -41,3 +41,34 @@ func Test_nativeHelmChart_ExtractChart(t *testing.T) {
 	assert.NoError(t, err)
 	assert.True(t, info.IsDir())
 }
+
+func Test_normalizeChartName(t *testing.T) {
```
Comment (alexmt) [inline util/helm/client_test.go:45]: 👍

**Review by alexmt — APPROVED** [review]
LGTM
