### PR TITLE
fix: Use ghost icon for unknown/missing permissions (#4730)

### LINKED ISSUE #4730: (?) icon is used both for unknown and help
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an app is first found by argo, or if after being first found by argo, the helm template command fails, argo will show two `(?)` icons ([fa-question-circle](https://fontawesome.com/icons/question-circle)) next to each other, one is an "unknown state", and the other is "help" -- they are ~nearly~ identical and the juxtaposition is problematic.

**To Reproduce**

1. Create an app file pointing to a chart that requires a values file
1. Don't provide the values file
1. Ask argo to digest the set

**Expected behavior**

Don't use nearly identical icons (even if the sizes are slightly different) to refer to unrelated concepts

**Screenshots**

https://cd.apps.argoproj.io/applications/rollouts-demo
? Missing ?

**Version**

```shell
{
    "Version": "v1.8.0+05c493b",
    "BuildDate": "2020-10-20T02:01:12Z",
    "GitCommit": "05c493b3a6de9f95f7e11eb35148e1639cf601b4",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.1",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.3.1+g249e521",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.16.0"
}
```

**Logs**

### PR DESCRIPTION
**Pull request by jsoref**
closes #4730

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

File: ui/src/app/settings/components/project-sync-windows-edit/project-sync-windows-edit.tsx [hunk 1]
```diff
@@ -14,7 +14,7 @@ function helpTip(text: string) {
         <Tooltip content={text}>
             <span style={{fontSize: 'smaller'}}>
                 {' '}
-                <i className='fa fa-question-circle' />
```
Comment (alexmt) [inline ui/src/app/settings/components/project-sync-windows-edit/project-sync-windows-edit.tsx:17]: I think this should still be a question icon. This is a tooltip with a help text, so it is ok to use question mark.

File: ui/src/app/settings/components/project-details/project-details.tsx [hunk 2]
```diff
@@ -34,7 +34,7 @@ function helpTip(text: string) {
         <Tooltip content={text}>
             <span style={{fontSize: 'smaller'}}>
                 {' '}
-                <i className='fa fa-question-circle' />
```
Comment (alexmt) [inline ui/src/app/settings/components/project-details/project-details.tsx:37]: I think tooltip with the help text should keep using question icon.

**Review by alexmt — CHANGES_REQUESTED** [review]

**Comment by alexmt** [comment]
Can you please update icon in https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/__snapshots__/utils.test.tsx.snap please? 

UI test is failing because of it.

**Review by alexmt — APPROVED** [review]
LGTM
