### PR TITLE
fix: respect delete confirmation for argocd app deletion

### LINKED ISSUE #22656: CLI app deletion confirmation not respected
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In Argo CD v2.14 the argocd CLI introduced a new logic for delete app confirmation. When choosing No the application the application is deleted anyways, this also effect Appsets.

```
argocd app delete bootstraper                                                                                                                              
Are you sure you want to delete 'bootstraper' and all its resources? [y/n] n
application 'bootstraper' deleted
```

Suspected PRs that introduced the changes:

https://github.com/argoproj/argo-cd/commit/4a38442b99ac459b4ed5985b3416ac09599ac31f
https://github.com/argoproj/argo-cd/commit/b9d5387979d61195f6c42528714f0c637d9950f7

**To Reproduce**

1. Install Argo CD OSS locally or use AKP and argocd CLI 2.14+
2. Create a app with the CLI (argocd app create guestbook --repo https://github.com/argoproj/argocd-example-apps.git --path guestbook --dest-namespace default --dest-server https://kubernetes.default.svc/)
3. Delete the app with the CLI and choose n when prompted. (argocd app delete guestbook)
4. Application will be deleted

**Expected behavior**

The application shouldn't be deleted when prompted 'n'

**Version**

```shell
argocd: v2.14.1+3345d05
  BuildDate: 2025-02-03T21:45:26Z
  GitCommit: 3345d05a43d8edd7ec42ec71ffe8b5f95bc68dbe
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.14.6+fe2a6e9
  BuildDate: 2025-03-18T13:26:42Z
  GitCommit: fe2a6e91b61299a476cc25948cbb53eb1ca1cc14
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

### PR DESCRIPTION
**Pull request by nitishfy**
Closes https://github.com/argoproj/argo-cd/issues/22656

## After

```
> dist/argocd app list            
NAME                               CLUSTER                         NAMESPACE  PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO                                                 PATH                                                               TARGET
argocd/engineering-dev-guestbook   https://kubernetes.default.svc  guestbook  default  OutOfSync  Missing  Manual      <none>      https://github.com/argoproj/argo-cd.git              applicationset/examples/list-generator/guestbook/engineering-dev   HEAD
argocd/engineering-prod-guestbook  https://kubernetes.default.svc  guestbook  default  OutOfSync  Missing  Manual      <none>      https://github.com/argoproj/argo-cd.git              applicationset/examples/list-generator/guestbook/engineering-prod  HEAD
argocd/guestbook1                  https://kubernetes.default.svc  default    default  OutOfSync  Missing  Manual      <none>      https://github.com/argoproj/argocd-example-apps.git  guestbook                                                          
               
> dist/argocd appset list
NAME              PROJECT  SYNCPOLICY  CONDITIONS                                                                                                                                                                                                                                     REPO                                     PATH                                                           TARGET
argocd/guestbook  default  nil         [{ParametersGenerated Successfully generated parameters for all Applications 2025-04-14 10:53:11 +0530 IST True ParametersGenerated} {ResourcesUpToDate ApplicationSet up to date 2025-04-14 10:53:11 +0530 IST True ApplicationSetUpToDate}]  https://github.com/argoproj/argo-cd.git  applicationset/examples/list-generator/guestbook/{{.cluster}}  HEAD
               
> dist/argocd app delete guestbook1
Are you sure you want to delete 'guestbook1' and all its resources? [y/n] n
The command to delete 'guestbook1' was cancelled.
               
> dist/argocd app delete guestbook1
Are you sure you want to delete 'guestbook1' and all its resources? [y/n] y
application 'guestbook1' deleted
               
> dist/argocd appset delete guestbook
Are you sure you want to delete 'guestbook' and all its Applications? [y/n] n
The command to delete 'guestbook' was cancelled.
               
> dist/argocd appset delete guestbook
Are you sure you want to delete 'guestbook' and all its Applications? [y/n] y
applicationset 'guestbook' deleted
```

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

<!-- Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request. -->

### CODE REVIEW

File: cmd/argocd/commands/utils/prompt_test.go [hunk 1]
```diff
@@ -38,11 +38,47 @@ func TestConfirmBaseOnCountPromptDisabled(t *testing.T) {
...
+		p := &Prompt{enabled: true}
+		result1, result2 := p.ConfirmBaseOnCount("Proceed?", "Proceed all?", tt.count)
+		assert.Equal(t, tt.output, result1)
+		if tt.count == 1 {
+			assert.False(t, result2)
+		} else {
+			assert.Equal(t, tt.output, result2)
+		}
+		os.Remove(tmpFile.Name())
+		_ = tmpFile.Close()
```
Comment (rumstead) [inline cmd/argocd/commands/utils/prompt_test.go:78]: We should probably close the file before it is removed

Comment (nitishfy) [reply cmd/argocd/commands/utils/prompt_test.go:77]: done.

**Review by rumstead — APPROVED** [review]
LGTM
