### PR TITLE
fix: Increase HAProxy check interval to prevent intermittent failures

### LINKED ISSUE #3358: HAProxy mode causes Redis intermittent failures
**Describe the bug**

After upgrading to 1.5.0 SSO logins are failing in some environments due to intermittent Redis failures. 

As part of 1.5.0 release bundled Redis was [upgraded](https://github.com/argoproj/argo-cd/pull/3147) to 4.3.4 with enabled HAProxy . It appears that default HAProxy check interval is too tight which might cause intermittent failures

**Version**

```shell
v1.5.0
```

**Logs**

<details><summary>LOGS</summary>
<p>

```
argocd-redis-ha-haproxy haproxy [WARNING] 093/131235 (6) : Server check_if_redis_is_master_1/R2 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string '172.20.31.132')", check duration: 1000ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
argocd-redis-ha-haproxy haproxy [ALERT] 093/131235 (6) : backend 'check_if_redis_is_master_1' has no server available!
argocd-redis-ha-haproxy haproxy [WARNING] 093/131241 (6) : Server check_if_redis_is_master_0/R1 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 0ms. 3 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
argocd-redis-ha-haproxy haproxy [WARNING] 093/131242 (6) : Server bk_redis_master/R0 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 1000ms. 0 active and 0 backup servers left. 1 sessions active, 0 requeued, 0 remaining in queue.
argocd-redis-ha-haproxy haproxy [ALERT] 093/131242 (6) : backend 'bk_redis_master' has no server available!
argocd-redis-ha-haproxy haproxy [WARNING] 093/131244 (6) : Server check_if_redis_is_master_0/R0 is DOWN, reason: Layer4 connection problem, info: "Connection refused at step 1 of tcp-check (connect)", check duration: 1001ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
argocd-redis-ha-haproxy haproxy [WARNING] 093/131246 (6) : Server bk_redis_master/R2 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 1ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
argocd-redis-ha-haproxy haproxy [WARNING] 093/131248 (6) : Server check_if_redis_is_master_2/R1 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
argocd-redis-ha-haproxy haproxy [WARNING] 093/131248 (6) : Server check_if_redis_is_master_2/R2 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 1ms. 2 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
argocd-redis-ha-haproxy haproxy [WARNING] 093/131251 (6) : Server check_if_redis_is_master_0/R2 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string '172.20.3.51')", check duration: 1001ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
argocd-redis-ha-haproxy haproxy [WARNING] 093/131251 (6) : Server check_if_redis_is_master_0/R1 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string '172.20.3.51')", check duration: 1001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
argocd-redis-ha-haproxy haproxy [ALERT] 093/131251 (6) : backend 'check_if_redis_is_master_0' has no server available!
argocd-redis-ha-haproxy haproxy [WARNING] 093/131257 (6) : Server check_if_redis_is_master_2/R0 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 2ms. 3 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jannfis**
Increases HAProxy check interval from 1s to 3s, see slack thread https://argoproj.slack.com/archives/CASHNF6MS/p1585935567397100

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Closes https://github.com/argoproj/argo-cd/issues/3358

### CODE REVIEW

File: manifests/ha/base/redis-ha/generate.sh [hunk 1]
```diff
@@ -16,4 +16,6 @@ helm2 template ./chart \
   --name argocd \
   --values ./chart/values.yaml \
   ${helm_execute} \
-  >> ./chart/upstream.yaml
+  >> ./chart/upstream_orig.yaml
+
+sed -e 's/check inter 1s/check inter 3s/' ./chart/upstream_orig.yaml > ./chart/upstream.yaml && rm ./chart/upstream_orig.yaml
```
Comment (alexmt) [inline manifests/ha/base/redis-ha/generate.sh:21]: 👍 that looks good enough to me

**Review by alexmt — APPROVED** [review]
