### PR TITLE
fix(appset): generated app errors should use the default requeue (#21887)

### LINKED ISSUE #21887: Github rate limiting on Appset Controller causing resync storm
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**
In a k8s environment that I have deployed I am noticing that the SCM generator is failing with GHE rate limits. The ApplicationSet resource is continuously updated with the github rate limit request ID on the `status` conditions of the resource which is further causing the controller to reconcile the resource again. This further strains our github deployment as this happens many times per second. 

Will update with more details shortly.

**To Reproduce**

**Expected behavior**

If an applicationset using SCM generators fails it should back off and respect the requeueAfterSeconds parameter. Ideally the error message returned from the SCM generator is idempotent and does not pass in a unique request id that causes the ApplicationSet to be reconciled again. 

**Screenshots**

**Version**
ArgoCD version 2.13.4

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by rumstead**
fixes #21887

I think we should cherry pick this into 2.14, 2.13, and 2.12

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: applicationset/controllers/applicationset_controller.go [hunk 1]
```diff
@@ -164,7 +164,8 @@ func (r *ApplicationSetReconciler) Reconcile(ctx context.Context, req ctrl.Reque
 				Status:  argov1alpha1.ApplicationSetConditionStatusTrue,
 			}, parametersGenerated,
 		)
-		return ctrl.Result{RequeueAfter: ReconcileRequeueOnValidationError}, err
+		// In order for the controller SDK to respect RequeueAfter, the error must be nil
```
Comment (rumstead) [inline applicationset/controllers/applicationset_controller.go:167]: https://github.com/kubernetes-sigs/controller-runtime/blob/52b17917caa97ec546423867d9637f1787830f3e/pkg/reconcile/reconcile.go#L102

Comment (rumstead) [reply applicationset/controllers/applicationset_controller.go:167]: // If the returned error is non-nil, the Result is ignored and the request will be
	// requeued using exponential backoff. The only exception is if the error is a
	// TerminalError in which case no requeuing happens.

File: applicationset/controllers/applicationset_controller.go [hunk 2]
```diff
@@ -164,7 +164,8 @@ func (r *ApplicationSetReconciler) Reconcile(ctx context.Context, req ctrl.Reque
...
+		return ctrl.Result{RequeueAfter: ReconcileRequeueOnValidationError}, nil
```
Comment (zachaller) [inline applicationset/controllers/applicationset_controller.go:168]: Even though we set the error in the status do we also want to log an error? We do this here https://github.com/argoproj/argo-cd/blob/7cf2728a0a7ba43fac79e41b593ca2174fc36b9c/applicationset/controllers/applicationset_controller.go#L182

Comment (rumstead) [reply applicationset/controllers/applicationset_controller.go:168]: Yea doesn’t hurt and won’t add any additional logs.

**Review by gdsoumya — APPROVED** [review]

**Review by ishitasequeira — APPROVED** [review]
LGTM!

File: applicationset/controllers/applicationset_controller.go [hunk 3]
```diff
@@ -155,6 +155,7 @@ func (r *ApplicationSetReconciler) Reconcile(ctx context.Context, req ctrl.Reque
 	// desiredApplications is the main list of all expected Applications from all generators in this appset.
 	desiredApplications, applicationSetReason, err := template.GenerateApplications(logCtx, applicationSetInfo, r.Generators, r.Renderer, r.Client)
 	if err != nil {
+		logCtx.Errorf("unable to gererate applications: %v", err)
```
Comment (blakepettersson) [inline applicationset/controllers/applicationset_controller.go:158]: Minor nit, otherwise LGTM
```suggestion
		logCtx.Errorf("unable to generate applications: %v", err)
```
