### PR TITLE
Returns a clearer error on invalid Helm version. Closes #2665 and #2736

### LINKED ISSUE #2665: No error on `argocd app create` in  CLI if `--revision` is omitted
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Expect error when trying to create an app and omit revision.

**To Reproduce**

```
argocd app create sealed-secrets --repo https://kubernetes-charts.storage.googleapis.com --helm-chart sealed-secrets --dest-server https://kubernetes.default.svc --dest-namespace kube-system 
```

```
FATA[0000] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = improper constraint: 
```
**Expected behavior**

Expect better error.

**Version**

```shell
master
```

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

 Closes #2665 and #2736

### CODE REVIEW

File: reposerver/repository/repository_test.go [hunk 1]
```diff
@@ -446,3 +446,16 @@ func Test_newEnv(t *testing.T) {
...
+
+	t.Run("EmptyRevision", func(t *testing.T) {
+		_, _, err := service.newHelmClientResolveRevision(&argoappv1.Repository{}, "", "")
+		assert.EqualError(t, err, "invalid revision '': improper constraint: ")
+	})
+	t.Run("InvalidRevision", func(t *testing.T) {
+		_, _, err := service.newHelmClientResolveRevision(&argoappv1.Repository{}, "???", "")
+		assert.EqualError(t, err, "invalid revision '???': improper constraint: ???")
+	})
+}
```
Comment (golangcibot) [inline reposerver/repository/repository_test.go]: File is not `goimports`-ed with -local github.com/argoproj/argo-cd (from `goimports`)
```suggestion
}
```

**Review by jannfis — APPROVED** [review]
LGTM

**Review by alexmt — APPROVED** [review]
