### PR TITLE
fix: unable to delete an Application if its target cluster is deleted, Argo CD enters infinite app deletion reconciliation loop

### LINKED ISSUE #5817: Unable to delete an Application if its target cluster is deleted, Argo CD enters infinite app deletion reconciliation loop
If you delete an application whose cluster no longer exists, the application delete will fail (not great). But, worse, after 3-4 minutes, Argo CD enters an infinite deletion reconciliation loop, flooding the k8s server with requests (see logs below).

There are two problems here:
1) I don't think we should prevent Applications from being deleted when the targeted cluster doesn't exist anymore. The cluster being deleted seems like a pretty clear signal of user intent.
2) We probably shouldn't be entering an infinite deletion reconciliation loop :smile: .

This was originally reproduced with the ApplicationSet controller (and is causing issues with cluster generator), but here are a quick set of steps to reproduce that don't require the controller.

Reproduced with Argo CD master branch (as of this writing), but was also reproducible with v1.8.x. 

## Steps to reproduce:
1) Create a cluster named 'cluster1' (for example)
2) Create an application against that cluster
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1-guestbook
  namespace: argocd
spec:
  destination:
    name: cluster1  # must match cluster name above, of course
    namespace: guestbook
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
```
(you don't need to sync it)

3) Ensure that the application appears within Argo CD.

4) Begin tailing the logs of the application controller, eg `kubectl logs -f pod/argocd-application-controller-0 -n argocd`

5) Delete that cluster (either delete the cluster within the web UI, or delete the cluster secret)

6) Delete the application within the web UI or CLI (foreground deletion, though background has the same behaviour) 

Within the application controller logs, you will see:
```
time="2021-03-19T11:49:22Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:49:22Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server=
```

Which isn't great (IMHO we should allow deletion if the cluster doesn't exist), but keep going...

7) **IMPORTANT**: wait ~3-4 minutes, and watch the application controller logs. 

After about 3-4 minutes, you will see Argo CD get stuck in what appears to be a deletion reconciliation loop. It gets into a state where it keeps trying to process that Application over and over, and since the cluster doesn't exist, it will never succeed. 

IMHO it seems like the correct behaviour is for Argo CD to allow invalid Applications (Applications that point to clusters w/o a corresponding secret) to be deleted. The deletion finalizer and/or reconciler shouldn't prevent this operation.

## Raw logs:
```
# Initial deletion error
time="2021-03-19T11:49:22Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:49:22Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=StatusRefreshed type=Warning
time="2021-03-19T11:49:22Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:49:22Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=StatusRefreshed type=Warning


# A minute later, still OK
time="2021-03-19T11:50:25Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:50:25Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=StatusRefreshed type=Warning


# We enter the infinite loop
time="2021-03-19T11:53:25Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Updated sync status: OutOfSync -> Unknown" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=ResourceUpdated type=Normal
time="2021-03-19T11:53:25Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=StatusRefreshed type=Warning
time="2021-03-19T11:53:25Z" level=info msg="Updated health status: Missing -> Unknown" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=ResourceUpdated type=Normal
time="2021-03-19T11:53:25Z" level=info msg="Update successful" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Reconciliation completed" application=cluster1-guestbook dest-name=cluster6 dest-namespace=guestbook dest-server= fields.level=2 time_ms=69
time="2021-03-19T11:53:25Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=StatusRefreshed type=Warning
time="2021-03-19T11:53:25Z" level=info msg="Update successful" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Reconciliation completed" application=cluster1-guestbook dest-name=cluster6 dest-namespace=guestbook dest-server= fields.level=2 time_ms=21
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Update successful" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Reconciliation completed" application=cluster1-guestbook dest-name=cluster6 dest-namespace=guestbook dest-server= fields.level=2 time_ms=19
time="2021-03-19T11:53:25Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=StatusRefreshed type=Warning
time="2021-03-19T11:53:25Z" level=info msg="Update successful" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Reconciliation completed" application=cluster1-guestbook dest-name=cluster6 dest-namespace=guestbook dest-server= fields.level=2 time_ms=19
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Update successful" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Reconciliation completed" application=cluster1-guestbook dest-name=cluster6 dest-namespace=guestbook dest-server= fields.level=2 time_ms=25
time="2021-03-19T11:53:25Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=StatusRefreshed type=Warning
time="2021-03-19T11:53:25Z" level=info msg="Update successful" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Reconciliation completed" application=cluster1-guestbook dest-name=cluster6 dest-namespace=guestbook dest-server= fields.level=2 time_ms=24
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Update successful" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Reconciliation completed" application=cluster1-guestbook dest-name=cluster6 dest-namespace=guestbook dest-server= fields.level=2 time_ms=16
time="2021-03-19T11:53:25Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=StatusRefreshed type=Warning
time="2021-03-19T11:53:25Z" level=info msg="Update successful" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Reconciliation completed" application=cluster1-guestbook dest-name=cluster6 dest-namespace=guestbook dest-server= fields.level=2 time_ms=21
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Deleting resources" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Update successful" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Reconciliation completed" application=cluster1-guestbook dest-name=cluster6 dest-namespace=guestbook dest-server= fields.level=2 time_ms=20
time="2021-03-19T11:53:25Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-03-19 11:47:54 +0000 UTC, expiry: 3m0s), level (2)" application=cluster1-guestbook
time="2021-03-19T11:53:25Z" level=info msg="Unable to delete application resources: unable to find destination server: there are no clusters with this name: cluster6" application=cluster1-guestbook dest-namespace=guestbook dest-server= reason=StatusRefreshed type=Warning
(... this keeps going ...)
```

### PR DESCRIPTION
**Pull request by jgwest**
### Description

On Application deletion, this PR verifies whether the target cluster (defined in the `destination` field of the `Application` resource) is defined within Argo CD (exists as a cluster secret, or is a local cluster). If the target cluster is not defined, it allows the Application to be deleted (rather than returning an error, as before).

### Details

If the target cluster is not defined, it is assumed that either:
a) the cluster was deleted from Argo CD (for example, via the Argo CD settings UI, or by deleting the cluster secret)
*or*
b) the Application spec is invalid (referencing a cluster that doesn't exist).

In both cases, since there are no cluster resources to clean up, we can safely allow the `Application` resource to be deleted.

So, if we detect that the Application targets a valid cluster:
- No change: everything works in this function as it currently does.

OTOH, if we detect the Application contains an invalid cluster:
- We empty the various Argo CD caches for the Application, as before.
- We skip the steps that would delete the live resources from the target cluster (because there is no target cluster)
- We report a warning, but allow the `Application` resource to be deleted (eg we remove the finalizer from the Application)

See parent issue for reproduction steps and details.

Fixes #5817 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [X] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: controller/appcontroller.go [hunk 1]
```diff
@@ -812,79 +812,100 @@ func (ctrl *ApplicationController) finalizeApplicationDeletion(app *appv1.Applic
...
-	if err != nil {
-		return nil, err
-	}
-	config := metrics.AddMetricsTransportWrapper(ctrl.metricsServer, app, cluster.RESTConfig())
+	if validDestination {
+		// ApplicationDestination points to a valid cluster, so we may clean up the live objects
 
-	filteredObjs := FilterObjectsForDeletion(objs)
+		objsMap, err := ctrl.getPermittedAppLiveObjects(app, proj)
+		if err != nil {
```
Comment (jgwest) [inline controller/appcontroller.go:841]: For reviewers: FYI the code inside this block is unchanged from the original (there aren't any changes hidden in there :smile: )

**Review by jannfis — APPROVED** [review]
LGTM, thanks @jgwest !

Before you merge this PR, please assign it to yourself.

File: controller/appcontroller.go [hunk 2]
```diff
@@ -1546,6 +1567,12 @@ func (ctrl *ApplicationController) newApplicationInformerAndLister() (cache.Shar
 			cache.NamespaceIndex: func(obj interface{}) ([]string, error) {
 				app, ok := obj.(*appv1.Application)
 				if ok {
+					// This call to 'ValidateDestination' ensures that the .spec.destination field of all Applications
+					// returned by the informer/lister will have server field set (if not already set) based on the name.
+					// (or, if not found, an error app condition)
+
+					// If the server field is not set, set it based on the cluster name; if the cluster name can't be found,
+					// log an error as an App Condition.
```
Comment (jannfis) [inline controller/appcontroller.go:1575]: :+1:

File: pkg/apis/application/v1alpha1/types.go [hunk 3]
```diff
@@ -2396,13 +2396,19 @@ func (r ResourceDiff) TargetObject() (*unstructured.Unstructured, error) {
...
 	d.Server = server
 }
 
-// TODO: document this method
+// An ApplicationDestination has an 'inferred server' if the ApplicationDestination
+// contains a Name, but not a Server URL. In this case it is necessary to retrieve
+// the Server URL by looking up the cluster name.
+//
+// As of this writing, looking up the cluster name, and setting the URL, is
+// performed by 'utils.ValidateDestination(...)', which then calls SetInferredServer.
```
Comment (jannfis) [inline pkg/apis/application/v1alpha1/types.go:2411]: +1+

File: util/argo/argo.go [hunk 4]
```diff
@@ -289,9 +289,15 @@ func enrichSpec(spec *argoappv1.ApplicationSpec, appDetails *apiclient.RepoAppDe
...
-// if we used both name and server then we return an invalid spec error
+// ValidateDestination sets the 'Server' value of the ApplicationDestination, if it is not set.
+// NOTE: this function WILL write to the object pointed to by the 'dest' parameter.
+//
+// If an ApplicationDestination has a Name field, but has an empty Server (URL) field,
+// ValidationDestination will look up the cluster by name (to get the server URL), and
+// set the corresponding Server field value.
+//
+// It also checks:
+// - If we used both name and server then we return an invalid spec error
```
Comment (jannfis) [inline util/argo/argo.go:300]: :+1:

**Comment by jgwest** [comment]
Previously verified downstream: https://github.com/argoproj-labs/applicationset/issues/175#issuecomment-874488353 so removing tag.
