### PR TITLE
fix: respect ignore differences for individual array elements in CRDs

### LINKED ISSUE #17694: ignoreDifferences and RespectIgnoreDifferences=true does allow ignoring differences in selected array elements
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Once https://github.com/argoproj/argo-cd/pull/17693 is merged Argo CD will be able to "ignore" arrays. However it is still not possible to ignore individual array elements. In order to fix it Argo CD would need to use strategic merge patch (using built-in k8s schema and dynamic CRD schema)

**To Reproduce**

Unit tests from https://github.com/argoproj/argo-cd/pull/14602 are reproducing behavior.

**Expected behavior**

It should be possible to ignore different individual array elements.

**Version**

```shell
v2.10.4
```

### PR DESCRIPTION
**Pull request by nitishfy**
Fixes https://github.com/argoproj/argo-cd/issues/17694
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by nitishfy** [comment]
The problem that I'm stuck at right now is how to get the OpenAPISchema for CRDs in order to use that in my tests. Can anyone provide some hints here?

```
=== FAIL: controller TestNormalizeTargetResourcesWithList (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered, repanicked]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4c08f17]

goroutine 9151 [running]:
testing.tRunner.func1.2({0x511f460, 0x8679a50})
	/opt/hostedtoolcache/go/1.25.0/x64/src/testing/testing.go:1872 +0x237
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.25.0/x64/src/testing/testing.go:1875 +0x35b
panic({0x511f460?, 0x8679a50?})
	/opt/hostedtoolcache/go/1.25.0/x64/src/runtime/panic.go:783 +0x132
github.com/argoproj/argo-cd/v3/controller.normalizeTargetResources({0x0, 0x0}, 0xc0040ded20)
	/home/runner/work/argo-cd/argo-cd/controller/sync.go:479 +0x3f7
github.com/argoproj/argo-cd/v3/controller.TestNormalizeTargetResourcesWithList.func2(0xc002645dc0)
	/home/runner/work/argo-cd/argo-cd/controller/sync_test.go:605 +0x15e
testing.tRunner(0xc002645dc0, 0xc000eca5b0)
	/opt/hostedtoolcache/go/1.25.0/x64/src/testing/testing.go:1934 +0xea
created by testing.(*T).Run in goroutine 9150
	/opt/hostedtoolcache/go/1.25.0/x64/src/testing/testing.go:1997 +0x465
```

**Comment by alexmt** [comment]
Here is how open api schema is loaded from real cluster:

https://github.com/argoproj/gitops-engine/blob/15973bc6b42d0b0f376c8cb2b7ee9de7715b1d7a/pkg/utils/kube/ctl.go#L133

```golang
	oapiGetter := openapi.NewOpenAPIGetter(disco)
	oapiResources, err := openapi.NewOpenAPIParser(oapiGetter).Parse()
```

I suggest to create fake implementation of `disco`. It implements `discovery.OpenAPISchemaInterface` which is only one method that returns schema document:

```golang
type OpenAPISchemaInterface interface {
	// OpenAPISchema retrieves and parses the swagger API schema the server supports.
	OpenAPISchema() (*openapi_v2.Document, error)
}
```

**Comment by blakepettersson** [comment]
@nitishfy looks reasonable to me, apart from the linting issues

File: controller/sync.go [hunk 1]
```diff
@@ -434,53 +435,68 @@ func (m *appStateManager) SyncAppState(app *v1alpha1.Application, project *v1alp
...
+
 	patchedTargets := []*unstructured.Unstructured{}
+
 	for idx, live := range cr.reconciliationResult.Live {
 		normalizedTarget := normalized.Targets[idx]
+		gvk := normalizedTarget.GroupVersionKind()
 		if normalizedTarget == nil {
 			patchedTargets = append(patchedTargets, nil)
 			continue
 		}
```
Comment (blakepettersson) [inline controller/sync.go]:
```suggestion
		if normalizedTarget == nil {
			patchedTargets = append(patchedTargets, nil)
			continue
		}
        gvk := normalizedTarget.GroupVersionKind()
```

File: controller/sync.go [hunk 2]
```diff
@@ -490,24 +506,41 @@ func getMergePatch(original, modified *unstructured.Unstructured, lookupPatchMet
 		return nil, err
 	}
 	if lookupPatchMeta != nil {
-		return strategicpatch.CreateThreeWayMergePatch(modifiedJSON, modifiedJSON, originalJSON, lookupPatchMeta, true)
+		return strategicpatch.CreateThreeWayMergePatch(originalJSON, modifiedJSON, originalJSON, lookupPatchMeta, true)
```
Comment (blakepettersson) [inline controller/sync.go]: Why does this change from `modifiedJSON` to `originalJSON`?

File: controller/sync.go [hunk 3]
```diff
@@ -434,53 +435,68 @@ func (m *appStateManager) SyncAppState(app *v1alpha1.Application, project *v1alp
...
-			if err != nil {
+		var (
+			lookupPatchMeta strategicpatch.LookupPatchMeta
+			versionedObject any
+		)
+
+		// Load patch meta struct or OpenAPI schema for CRDs
+		if obj, err := scheme.Scheme.New(gvk); err == nil {
+			var meta strategicpatch.PatchMetaFromStruct
+			if meta, err = strategicpatch.NewPatchMetaFromStruct(obj); err != nil {
```
Comment (blakepettersson) [inline controller/sync.go]: This can be simplified with this (Github doesn't allow the suggestion to span all affected lines, but you get the idea)

```suggestion
		var (
			lookupPatchMeta strategicpatch.LookupPatchMeta
			versionedObject runtime.Object
		)

		// Load patch meta struct or OpenAPI schema for CRDs
		if versionedObject, err = scheme.Scheme.New(gvk); err == nil {
			if lookupPatchMeta, err = strategicpatch.NewPatchMetaFromStruct(versionedObject); err != nil {
				return nil, err
			}
		} else if crdSchema := openAPISchema.LookupResource(gvk); crdSchema != nil {
			lookupPatchMeta = strategicpatch.NewPatchMetaFromOpenAPI(crdSchema)
```

File: controller/sync.go (hunk 2 above)
Comment (blakepettersson) [reply controller/sync.go]: I ran the unit tests and they were unaffected when switching it back to the previous impl - so my question remains, why do we need to modify the merge patch? 

Can you add a test which needs this (alternatively create a test that fails if this were to be modified)?

Comment (nitishfy) [reply controller/sync.go]: I can't remember why i modified this field. I looked at it again today and i think it makes sense to keep the field as it was initially.

**Review by crenshaw-dev — APPROVED** [review]
