### PR TITLE
fix(ui): Consolidate sync options 

### LINKED ISSUE #5215: Consolidate/standard on sync options in UI
# Summary

We have inconsistent UX with regards to sync options in our UI (and possibly CLI):

image

image

# Proposal

The same set of options should be presented in App sync options, and sync button options, and CLI.

### PR DESCRIPTION
**Pull request by rbreeze**
Signed-off-by: Remington Breeze <remington@breeze.software>

Fix #5215

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

File: ui/src/app/applications/components/application-sync-options.tsx [hunk 1]
```diff
@@ -33,10 +33,46 @@ function booleanOption(name: string, label: string, defaultVal: boolean, props:
...
+interface SyncOption {
+    name?: string;
+    key: SyncOptionKey;
+    value?: boolean;
+    default?: boolean;
+}
+
+const enum SyncOptions {
+    Validate = 'Validate',
+    CreateNamespace = 'Auto-create Namespace',
```
Comment (alexmt) [inline ui/src/app/applications/components/application-sync-options.tsx:45]: Nitpick:

```suggestion
    CreateNamespace = 'Auto-Create Namespace',
```

File: ui/src/app/applications/components/application-sync-options.tsx [hunk 2]
```diff
@@ -33,10 +33,46 @@ function booleanOption(name: string, label: string, defaultVal: boolean, props:
...
 
+interface SyncOption {
+    name?: string;
+    key: SyncOptionKey;
+    value?: boolean;
+    default?: boolean;
+}
+
+const enum SyncOptions {
+    Validate = 'Validate',
```
Comment (alexmt) [inline ui/src/app/applications/components/application-sync-options.tsx:44]: This option actually disables validation. Can you rename it to `Skip Schema Validation` and keep it disabled by default?

File: ui/src/app/shared/components/revision.tsx [hunk 3]
```diff
@@ -5,7 +5,13 @@ export const Revision = ({repoUrl, revision, children}: {repoUrl: string; revisi
     revision = revision || '';
```
Comment (alexmt) [inline ui/src/app/shared/components/revision.tsx:5]: Did you mean to change `revision.tsx` in this PR?

File: ui/src/app/shared/components/repo.tsx [hunk 4]
```diff
@@ -4,5 +4,11 @@ import {repoUrl} from './urls';
 export const Repo = ({url, children}: {url: string; children?: React.ReactNode}) => {
```
Comment (alexmt) [inline ui/src/app/shared/components/repo.tsx:4]: Did you mean to change `repo.tsx` in this PR?

File: ui/src/app/applications/components/application-sync-options.tsx (hunk 2 above)
Comment (alexmt) [inline ui/src/app/applications/components/application-sync-options.tsx:44]: We have only following sync options: `PruneLast=true`, `Validate=false`and `CreateNamespace=true`. 

* DryRun can be specified in UI/API during manual sync only
* ApplyOnly  is UI only checkbox that allows to specify. SyncStrategy can be specified in UI/API during manual sync only
* Force is specified as a boolean field in of sync strategy. Probably is should be replaced with a sync option but this can should be done in a separate PR.

**Review by alexmt — CHANGES_REQUESTED** [review]
Added several commits. Also noticed the following error when tried to sync

```
Uncaught TypeError: Cannot read property 'slice' of undefined
    at booleanOption (application-sync-options.tsx:11)
    at application-sync-options.tsx:73
    at Array.map (<anonymous>)
    at ApplicationSyncOptions (application-sync-options.tsx:71)
    at renderWithHooks (react-dom.development.js:14803)
    at mountIndeterminateComponent (react-dom.development.js:17482)
    at beginWork (react-dom.development.js:18596)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
```

File: ui/src/app/shared/components/revision.tsx (hunk 3 above)
Comment (rbreeze) [reply ui/src/app/shared/components/revision.tsx:5]: I didn't, must be an issue with my linter

File: ui/src/app/shared/components/repo.tsx (hunk 4 above)
Comment (rbreeze) [reply ui/src/app/shared/components/repo.tsx:4]: Same as above

File: ui/src/app/applications/components/application-sync-options.tsx [hunk 5]
```diff
@@ -31,22 +31,65 @@ function booleanOption(name: string, label: string, defaultVal: boolean, props:
...
-const optionStyle: React.CSSProperties = {marginTop: '0.5em'};
+enum ManualSyncFlags {
+    Prune = 'Prune',
+    DryRun = 'Dry Run',
+    ApplyOnly = 'Apply Only',
+    Force = 'Force'
+}
+
+enum SyncOptions {
+    Validate = 'Skip Schema Validation',
```
Comment (alexmt) [inline ui/src/app/applications/components/application-sync-options.tsx:42]: I think `Validate` is handled incorrectly. Unlike other options validate default value is true, so when it is checked we need to add `Validate=false` (currently UI adds `Validate=true`)

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
