### PR TITLE
fix: Fixed inconsistent alignment of titles and headings in status panel

### LINKED ISSUE #23022: Inconsistent alignment in app panel
Image

The dark-grey titles should share the same baseline, and the large titles in each panel should share the same baseline.

### PR DESCRIPTION
**Pull request by sivasath16**
Fixes #23022 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by sivasath16** [comment]
@reggie-k, I've fixed the UI bug. Can you take a look at it?

**Comment by surajyadav1108** [comment]
It would be better if you could please provide a before and after of the UI changes.

**Review by nitishfy — CHANGES_REQUESTED** [review]
I tested it locally.

### Before
Screenshot 2025-05-27 at 3 04 29 PM

### After
Screenshot 2025-05-27 at 2 58 42 PM

I don't see much of a difference here.

**Comment by crenshaw-dev** [comment]
The easiest way to test the worst of the alignment issues (the conditions panel) is to intentionally add a typo to the source.repoURL field. I tested with that situation, looks like this PR doesn't yet address that alignment issue. 
image

File: ui/src/app/applications/components/application-status-panel/application-status-panel.tsx [hunk 1]
```diff
@@ -47,7 +47,7 @@ const sectionLabel = (info: SectionInfo) => (
 
 const sectionHeader = (info: SectionInfo, onClick?: () => any) => {
     return (
-        <div style={{display: 'flex', alignItems: 'center', marginBottom: '0.5em'}}>
+        <div style={{display: 'flex', alignItems: 'center'}}>
```
Comment (linghaoSu) [inline ui/src/app/applications/components/application-status-panel/application-status-panel.tsx:54]: Some status headers could support buttons to enable more actions. To maintain visual alignment across both cases, I recommend using a fixed row height of 20px and avoiding fractional line heights.

```suggestion
        <div style={{display: 'flex', alignItems: 'center', lineHeight: '20px'}}>
```
I noticed the remaining sectionLabel usages at:

https://github.com/argoproj/argo-cd/blob/5684a19d8fbced5959b8c0a06c1ac21c0894618b/ui/src/app/applications/components/application-status-panel/application-status-panel.tsx#L319-L330
https://github.com/argoproj/argo-cd/blob/5684a19d8fbced5959b8c0a06c1ac21c0894618b/ui/src/app/applications/components/application-status-panel/application-status-panel.tsx#L170-L175

Also, there's an unusual marginTop defined in [application-status-panel.scss](https://github.com/argoproj/argo-cd/blob/5684a19d8fbced5959b8c0a06c1ac21c0894618b/ui/src/app/applications/components/application-status-panel/application-status-panel.scss#L102), which I'd suggest removing to simplify the layout.

File: ui/src/app/applications/components/application-status-panel/application-status-panel.tsx [hunk 2]
```diff
@@ -156,7 +156,8 @@ export const ApplicationStatusPanel = ({application, showDiff, showOperation, sh
     return (
         <div className='application-status-panel row'>
             <div className='application-status-panel__item'>
-                <div style={{lineHeight: '19.5px', marginBottom: '0.3em'}}>{sectionLabel({title: 'APP HEALTH', helpContent: 'The health status of your app'})}</div>
+                {/* <div style={{lineHeight: '19.5px', marginBottom: '0.3em'}}>{sectionLabel({title: 'APP HEALTH', helpContent: 'The health status of your app'})}</div> */}
+                {sectionHeader({title: 'APP HEALTH', helpContent: 'The health status of your app'})}
                 <div className='application-status-panel__item-value'>
```
Comment (linghaoSu) [inline ui/src/app/applications/components/application-status-panel/application-status-panel.tsx:164]: Additionally, for the `application-status-panel__item-value` className, I recommend constraining its layout using a `min-height` rather than fixed heights. Since this element is based on a flex layout, using a consistent height will ensure vertical alignment across items. From experiments, a `min-height: 40px` works well for most cases, except for `appConditions`, which includes multiple status labels and may require special handling.

To fine-tune the alignment, I suggest adding `margin-top: 1px`; around this line (L50)https://github.com/argoproj/argo-cd/blob/5684a19d8fbced5959b8c0a06c1ac21c0894618b/ui/src/app/applications/components/application-status-panel/application-status-panel.scss#L50, and adding vertical-align: middle; at this line (L190)https://github.com/argoproj/argo-cd/blob/5684a19d8fbced5959b8c0a06c1ac21c0894618b/ui/src/app/applications/components/application-status-panel/application-status-panel.scss#L190 to ensure the status icon in the conditions section is vertically aligned with the text.

Also, I recommend removing the line `margin: auto;`https://github.com/argoproj/argo-cd/blob/5684a19d8fbced5959b8c0a06c1ac21c0894618b/ui/src/app/applications/components/application-status-panel/application-status-panel.scss#L44, as it causes vertical misalignment due to its effect on the element's positioning within flex containers.

With these adjustments, we should be able to achieve a more consistent and visually aligned layout.

image

For comparison, here's a screenshot of the previous layout before these adjustments:

image

**Comment by sivasath16** [comment]
image
image

These are the current improvements done based on previous review. Please review.

**Review by nitishfy — COMMENTED** [review]
Please fix the DCO check and we are good to go.

**Comment by sivasath16** [comment]
Hey @nitishfy, I've made sure that all the necessary checks are passed. Please verify and merge the changes. Thanks.

**Comment by sivasath16** [comment]
Hey @nitishfy @linghaoSu , could you please review and merge the code. Thanks

File: ui/src/app/applications/components/application-status-panel/application-status-panel.tsx (hunk 2 above)
Comment (sivasath16) [reply ui/src/app/applications/components/application-status-panel/application-status-panel.tsx:164]: image
image

I've made the necessary code changes and status panel have been fixed.

**Review by nitishfy — APPROVED** [review]

**Review by surajyadav1108 — APPROVED** [review]

**Comment by sivasath16** [comment]
Hi @nitishfy, could you please verify and merge the changes? Thank you.

**Review by nitishfy — COMMENTED** [review]
Thank you!
