### PR TITLE
fix: stop caching helm index

### LINKED ISSUE #3107: New release from Helm repo not immediately picked up on resync
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I have set `--app-resync` in `argocd-application-controller` to `15s`. In the logs I can see that the app status is refreshed but the change is only picked up after ~5 minutes.

**To Reproduce**

1. Create an application with `Helm` source.
1. Set `app-resync` to something short like `15s`
1. Release new Chart version to Helm Chart Repository.
1. Wait for application to be synced

**Expected behavior**

I expect my application synced/updated after ~`15s` instead ~`5m`

**Question**

1. Against which state is the comparison done after `app-resync` interval? It seems the Helm Repository is **not** queried to check for a new version!?
1. Is there another timeout to define how often the Helm Repository is _actually_ being queried for new releases?

**Version**

```shell
argocd: v1.5.0+d528629
  BuildDate: 2020-02-08T23:41:37Z
  GitCommit: d5286296ebb5ec8770020308723cbb8f3eb7f956
  GitTreeState: clean
  GoVersion: go1.13.7
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

15s interval of refreshing the app
```
time="2020-02-10T19:12:31Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2020-02-10 19:12:16 +0000 UTC, expiry: 15s), level (2)" application=lessorfinder
time="2020-02-10T19:12:31Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: applications)" application=lessorfinder
time="2020-02-10T19:12:31Z" level=info msg="Skipping auto-sync: application status is Synced" application=lessorfinder
time="2020-02-10T19:12:31Z" level=info msg="Update successful" application=lessorfinder
time="2020-02-10T19:12:31Z" level=info msg="Reconciliation completed" application=lessorfinder dest-namespace=applications dest-server="https://kubernetes.default.svc" fields.level=2 time_ms=57.696346000000005
```

When the change is finally picked up
```
time="2020-02-10T19:16:31Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2020-02-10 19:16:16 +0000 UTC, expiry: 15s), level (2)" application=lessorfinder
time="2020-02-10T19:16:31Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: applications)" application=lessorfinder
time="2020-02-10T19:16:34Z" level=info msg="Initiated automated sync to '0.7.0-alpha.5'" application=lessorfinder dest-namespace=applications dest-server="https://kubernetes.default.svc" reason=OperationStarted type=Normal
time="2020-02-10T19:16:34Z" level=info msg="Initiated automated sync to '0.7.0-alpha.5'" application=lessorfinder
time="2020-02-10T19:16:34Z" level=info msg="Updated sync status: Synced -> OutOfSync" application=lessorfinder dest-namespace=applications dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-02-10T19:16:34Z" level=info msg="updated 'lessorfinder' operation (phase: Running)"
time="2020-02-10T19:16:34Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:0.7.0-alpha.5,Prune:true,DryRun:false,SyncStrategy:nil,Resources:[]SyncOperationResource{},Source:nil,Manifests:[],}}" application=lessorfinder
time="2020-02-10T19:16:34Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: applications)" application=lessorfinder
time="2020-02-10T19:16:34Z" level=info msg="Update successful" application=lessorfinder
time="2020-02-10T19:16:34Z" level=info msg="Reconciliation completed" application=lessorfinder dest-namespace=applications dest-server="https://kubernetes.default.svc" fields.level=2 time_ms=3102.543216
```

### PR DESCRIPTION
**Pull request by alexmt**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Closes: #3107

Argo CD controller caches resolve chart revision in the application CRD. So index is not loaded on every app reconciliation and it is ok not to cache it at all.

### CODE REVIEW

File: util/helm/cmd.go [hunk 1]
```diff
@@ -44,7 +44,11 @@ func (c Cmd) run(args ...string) (string, error) {
 	cmd := exec.Command(c.binaryName, args...)
 	cmd.Dir = c.WorkDir
 	cmd.Env = os.Environ()
-	cmd.Env = append(cmd.Env, fmt.Sprintf("HELM_HOME=%s", c.helmHome))
+	cmd.Env = append(cmd.Env,
+		fmt.Sprintf("XDG_CACHE_HOME=%s", c.helmHome),
```
Comment (jannfis) [inline util/helm/cmd.go]: I'm not sure whether we should point `XDG_CACHE_HOME` to same location as `HELM_HOME` - how about `$HELM_HOME/cache`? Also, I found a discussion around this at https://github.com/helm/helm/issues/7206, but I'm not sure if this will apply to us (except when users have a sidecar that installs Helm plugins).

**Review by jannfis — CHANGES_REQUESTED** [review]
LGTM, just would like to discuss the location of `XDG_CACHE_HOME` value.

File: util/helm/cmd.go (hunk 1 above)
Comment (alexmt) [reply util/helm/cmd.go]: Thanks for pointing this out. I think it is better to use `$HELM_HOME/cache` at least for consistency. Updated the `XDG_CACHE_HOME` env variable.

**Review by jannfis — APPROVED** [review]
LGTM
