### PR TITLE
chore(ui): fix Incorrect links to applications managed by other argo instances

### LINKED ISSUE #12380: Incorrect links to applications managed by other argo instances
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
GitOps user has reported a bug regarding links to applications managed by other argocd instance. As shown in the below chart, App-of-Apps application is managed by the Argocd in namespace A. And both App-of-Apps application and the Argocd in namespace A are deployed by the default openshift-gitops argocd instance. When the user tries to open App-of-Apps application link from the defaut openshift-gitops argocd instance UI, it fails to load data. The root cause is that the application link uses wrong argocd_server_url comming from the default argocd instance.
bug
Screenshot 2023-02-09 at 1 45 29 PM
Screenshot 2023-02-09 at 1 46 58 PM

The correct link and page:
Screenshot 2023-02-09 at 1 53 29 PM

**To Reproduce**
1. Start an Argocd instance in namespace A.
2. Prepare a repository includes manifests of an Argocd instance and an App-of-Apps application in namespace B.
3. In Argocd instance from step1. deploy an application using the repoURL of the step2. repository.
4. In Argocd instance from step1., sync the application added in step3, and click on "Open application" icon of App-of-Apps application.

**Expected behavior**
It goes to the right application page with no data loading issue.

**Version**
v2.5.8

### PR DESCRIPTION
**Pull request by aali309**
Fixes: #12380 
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: ui/src/app/applications/components/application-details/application-details.tsx [hunk 1]
```diff
@@ -1174,8 +1174,20 @@ export class ApplicationDetails extends React.Component<RouteComponentProps<{app
         return from(services.applications.get(name, appNamespace))
             .pipe(
                 mergeMap(app => {
+                    // Check if this application is managed by another Argo CD instance
```
Comment (keithchong) [inline ui/src/app/applications/components/application-details/application-details.tsx]: I don't think this is the place to put this. It seems like application-resource-tree.tsx is more appropriate.

**Review by keithchong — CHANGES_REQUESTED** [review]

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx [hunk 2]
```diff
@@ -771,11 +781,19 @@ function renderResourceNode(props: ApplicationResourceTreeProps, id: string, nod
                     {comparisonStatus != null && <ComparisonStatusIcon status={comparisonStatus} resource={!rootNode && node} />}
                     {appNode && !rootNode && (
                         <Consumer>
-                            {ctx => (
```
Comment (keithchong) [inline ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx:774]: It looks like if you don't have a managedByURL, this link should be still there, since it is an appNode

**Review by keithchong — CHANGES_REQUESTED** [review]

File: ui/src/app/applications/components/applications-list/applications-tiles.tsx [hunk 3]
```diff
@@ -139,7 +139,13 @@ export const ApplicationTiles = ({applications, syncApplication, refreshApplicat
...
                                                         <div className={app.status.summary.externalURLs?.length > 0 ? 'columns small-2' : 'columns small-1'}>
                                                             <div className='applications-list__external-link'>
-                                                                <ApplicationURLs urls={app.status.summary.externalURLs} />
+                                                                <a
+                                                                    href={linkInfo.url}
+                                                                    target={linkInfo.isExternal ? '_blank' : undefined}
+                                                                    rel={linkInfo.isExternal ? 'noopener noreferrer' : undefined}
+                                                                    title={`Link: ${linkInfo.url}\nmanaged-by-url: ${getManagedByURL(app) || 'none'}`}>
+                                                                    <i className='fa fa-external-link-alt' />
+                                                                </a>
```
Comment (keithchong) [inline ui/src/app/applications/components/applications-list/applications-tiles.tsx]: Look for examples elsewhere where we run ctx.navigation.goto for handling onClick

This allows you to click on the forward and back buttons in the browser and it will navigate properly.

**Review by keithchong — CHANGES_REQUESTED** [review]

File: ui/src/app/applications/components/applications-list/applications-tiles.tsx (hunk 3 above)
Comment (aali309) [reply ui/src/app/applications/components/applications-list/applications-tiles.tsx]: Yah, I noticed this when clicking the back button.

File: controller/cache/info.go [hunk 4]
```diff
@@ -476,6 +480,13 @@ func populateHostNodeInfo(un *unstructured.Unstructured, res *ResourceInfo) {
 	}
 }
 
+func populateApplicationInfo(un *unstructured.Unstructured, res *ResourceInfo) {
+	// Add managed-by-url annotation to info if present
+	if managedByURL, ok := un.GetAnnotations()["argocd.argoproj.io/managed-by-url"]; ok {
+		res.Info = append(res.Info, v1alpha1.InfoItem{Name: "managed-by-url", Value: managedByURL})
```
Comment (ishitasequeira) [inline controller/cache/info.go]: Move the hardcoded values to constants.

File: server/deeplinks/deeplinks.go [hunk 5]
```diff
@@ -70,6 +71,17 @@ func CreateDeepLinksObject(resourceObj *unstructured.Unstructured, app *unstruct
 	if app != nil {
 		deeplinkObj[AppDeepLinkKey] = app.Object
 		deeplinkObj[AppDeepLinkShortKey] = app.Object
+
+		// Add managed-by URL if present in annotations
+		if app.Object["metadata"] != nil {
+			if metadata, ok := app.Object["metadata"].(map[string]any); ok {
+				if annotations, ok := metadata["annotations"].(map[string]any); ok {
+					if managedByURL, ok := annotations["argocd.argoproj.io/managed-by-url"].(string); ok {
```
Comment (ishitasequeira) [inline server/deeplinks/deeplinks.go]: Move `"argocd.argoproj.io/managed-by-url"` to a constant

File: ui/src/app/applications/components/applications-list/applications-list.tsx [hunk 6]
```diff
@@ -52,6 +52,7 @@ const APP_LIST_FIELDS = ['metadata.resourceVersion', ...APP_FIELDS.map(field =>
 const APP_WATCH_FIELDS = ['result.type', ...APP_FIELDS.map(field => `result.application.${field}`)];
 
 function loadApplications(projects: string[], appNamespace: string): Observable<models.Application[]> {
+    console.log('🔍 Loading applications for projects:', projects, 'and namespace:', appNamespace);
```
Comment (ishitasequeira) [inline ui/src/app/applications/components/applications-list/applications-list.tsx]: Can we remove this console log?

File: ui/src/app/applications/components/applications-list/applications-list.tsx [hunk 7]
```diff
@@ -396,6 +397,7 @@ export const ApplicationsList = (props: RouteComponentProps<{}>) => {
                                             </div>
                                         )}>
                                         {(applications: models.Application[]) => {
+                                            console.log('🔍 ApplicationsList applications:', applications);
```
Comment (ishitasequeira) [inline ui/src/app/applications/components/applications-list/applications-list.tsx]: Same for this.

File: server/cluster/cluster.proto [hunk 8]
```diff
@@ -26,6 +27,11 @@ message ClusterQuery {
 
 message ClusterResponse {}
 
+message ListClusterLinksRequest {
+	string name = 1;
+	string server = 2;
+}
```
Comment (ishitasequeira) [inline server/cluster/cluster.proto]: The struct looks unused. Do we require this struct?

File: server/cluster/cluster.proto [hunk 9]
```diff
@@ -80,5 +86,9 @@ service ClusterService {
 	rpc InvalidateCache(ClusterQuery) returns (github.com.argoproj.argo_cd.v3.pkg.apis.application.v1alpha1.Cluster) {
 		option (google.api.http).post = "/api/v1/clusters/{id.value}/invalidate-cache";
 	}
-	
+
+	// ListLinks returns list of links for a cluster
+	rpc ListLinks(ClusterQuery) returns (application.LinksResponse) {
+		option (google.api.http).get = "/api/v1/clusters/{name}/links";
+	}
```
Comment (ishitasequeira) [inline server/cluster/cluster.proto]: The function does not seem to be used either. Can we remove this if not required?

**Comment by yohanb** [comment]
noticed the issue #12380 as well, glad to see there's a fix on the way.
@aali309 if you need some help, let me know!

**Review by ishitasequeira — APPROVED** [review]
@aali309 , Overall changes look good!!

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx [hunk 10]
```diff
@@ -486,13 +488,21 @@ function renderPodGroup(props: ApplicationResourceTreeProps, id: string, node: R
...
-                                )}
+                                {ctx => {
+                                    // For nested applications, use the node's data to construct the URL
+                                    const linkInfo = getApplicationLinkURLFromNode(node, ctx.baseHref);
+                                    return (
+                                        <a
+                                            href={linkInfo.url}
+                                            target={linkInfo.isExternal ? '_blank' : undefined}
+                                            rel={linkInfo.isExternal ? 'noopener noreferrer' : undefined}
+                                            title={`Link: ${linkInfo.url}\nmanaged-by-url: ${getManagedByURLFromNode(node) || 'none'}`}>
```
Comment (keithchong) [inline ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx]: 'Open application' was the original title. What is the title if there is no managed-by-url annotation

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx [hunk 11]
```diff
@@ -769,13 +779,21 @@ function renderResourceNode(props: ApplicationResourceTreeProps, id: string, nod
                     {node.hook && <i title='Resource lifecycle hook' className='fa fa-anchor' />}
                     {healthState != null && <HealthStatusIcon state={healthState} />}
                     {comparisonStatus != null && <ComparisonStatusIcon status={comparisonStatus} resource={!rootNode && node} />}
-                    {appNode && !rootNode && (
+                    {appNode && (
```
Comment (keithchong) [inline ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx]: What's the reason for removing `!rootNode &&`

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx [hunk 12]
```diff
@@ -769,13 +779,21 @@ function renderResourceNode(props: ApplicationResourceTreeProps, id: string, nod
...
-                            )}
+                            {ctx => {
+                                // For nested applications, use the node's data to construct the URL
+                                const linkInfo = getApplicationLinkURLFromNode(node, ctx.baseHref);
+                                return (
+                                    <a
+                                        href={linkInfo.url}
+                                        target={linkInfo.isExternal ? '_blank' : undefined}
+                                        rel={linkInfo.isExternal ? 'noopener noreferrer' : undefined}
+                                        title={`Link: ${linkInfo.url}\nmanaged-by-url: ${getManagedByURLFromNode(node) || 'none'}`}>
```
Comment (keithchong) [inline ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx]: Also here, what's the title if there is no managed-by-url annotation?

File: ui/src/app/applications/components/applications-list/applications-tiles.tsx [hunk 13]
```diff
@@ -139,7 +139,18 @@ export const ApplicationTiles = ({applications, syncApplication, refreshApplicat
                                                         </div>
                                                         <div className={app.status.summary.externalURLs?.length > 0 ? 'columns small-2' : 'columns small-1'}>
                                                             <div className='applications-list__external-link'>
-                                                                <ApplicationURLs urls={app.status.summary.externalURLs} />
+                                                                <button
```
Comment (keithchong) [inline ui/src/app/applications/components/applications-list/applications-tiles.tsx:144]: Can you check this.  The application can have multiple external URLs and you can click on these links.  Are you maintaining this?

**Review by keithchong — CHANGES_REQUESTED** [review]

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx (hunk 11 above)
Comment (aali309) [reply ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx]: restored

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx [hunk 14]
```diff
@@ -488,11 +490,19 @@ function renderPodGroup(props: ApplicationResourceTreeProps, id: string, node: R
...
-                                    </a>
-                                )}
+                                {ctx => {
+                                    // For nested applications, use the node's data to construct the URL
+                                    const linkInfo = getApplicationLinkURLFromNode(node, ctx.baseHref);
+                                    return (
+                                        <a
+                                            href={linkInfo.url}
+                                            target={linkInfo.isExternal ? '_blank' : undefined}
+                                            rel={linkInfo.isExternal ? 'noopener noreferrer' : undefined}
```
Comment (keithchong) [inline ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx:500]: Add this and other related links
```
                                            onClick={e => {
                                                e.stopPropagation();
                                            }}
```

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx [hunk 15]
```diff
@@ -488,11 +490,19 @@ function renderPodGroup(props: ApplicationResourceTreeProps, id: string, node: R
...
-                                {ctx => (
-                                    <a href={ctx.baseHref + 'applications/' + node.namespace + '/' + node.name} title='Open application'>
-                                        <i className='fa fa-external-link-alt' />
-                                    </a>
-                                )}
+                                {ctx => {
+                                    // For nested applications, use the node's data to construct the URL
+                                    const linkInfo = getApplicationLinkURLFromNode(node, ctx.baseHref);
+                                    return (
+                                        <a
```
Comment (keithchong) [inline ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx:497]: Update the link also in:

ui/src/app/applications/components/application-details/application-resource-list.tsx

**Review by keithchong — CHANGES_REQUESTED** [review]

**Review by keithchong — APPROVED** [review]
LGTM

**Comment by keithchong** [comment]
Incorrectly added the cherry pick label here.  Ignore to above message.
