### PR TITLE
Make BeforeHookCreation the default. Fixes #2754

### LINKED ISSUE #2754: BeforeHookCreation should be the default hook
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

An examination of the Helm source code show that if no delete policy is provided, then before hook creation is the default:

https://github.com/helm/helm/blob/84de17e7e5255e5033967f005d4b4c05c024317c/pkg/action/hooks.go#L50

**Expected behavior**

Hooks should be deleted by creation by default

**Version**

```shell
v1.3
```

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Fixes #2754

### CODE REVIEW

File: test/manifests_test.go [hunk 1]
```diff
@@ -16,7 +15,7 @@ func TestBuildManifests(t *testing.T) {
 
 	out, err := argoexec.RunCommand("kustomize", argoexec.CmdOpts{}, "version")
 	assert.NoError(t, err)
-	assert.True(t, Contains(out, "Version:kustomize/v3"), "kustomize should be version 3")
+	assert.Contains(t,out, "Version:3", "kustomize should be version 3")
```
Comment (golangcibot) [inline test/manifests_test.go]: File is not `goimports`-ed with -local github.com/argoproj/argo-cd (from `goimports`)
```suggestion
	assert.Contains(t, out, "Version:3", "kustomize should be version 3")
```

**Review by alexmt — APPROVED** [review]

**Comment by alexec** [comment]
Back-ported to v1.3
