### PR TITLE
fix(reposerver): using timeouts in http transport for Github App authentication

### LINKED ISSUE #26749: Github App Authentication fails with "context deadline exceeded" when TLS handshake fails
When using GitHub App Authentication, if the proxy settings drop TLS packets that are too large, then the error message is not clear. The error message says, `context deadline exceeded` without much information. This happens for all timeout/latency related scenarios causing confusion and time lost in debugging process.

This issue happens in Argo CD v2.14.12 onwards ( and 3.x.x, master versions too) when using Go 1.23+
The exact commit id from where this issue started happening is after the below commit when go was upgraded from `go1.22`to `go1.23` for the first time. 
https://github.com/argoproj/argo-cd/commit/efe5d2956ed9dd1511f198a770f909594839181e

#### Root cause:
Go 1.23 introduces Kyber768 post-quantum encryption by default, which can cause TLS handshake timeouts when passing through Suricata-based firewalls (e.g., AWS Network Firewall). These large packets may fragment, leading to dropped traffic. The fix is to set `GODEBUG=tlskyber=0` in your environment to disable it for `go 1.23` and `GODEBUG=tlsmlkem=0` for `go 1.24` and later.

Checklist:

- [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [ ] I've included steps to reproduce the bug.
- [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

You need an EKS instance with Suricata Firewal set and configured to drop big TLS packets. Then in Argo CD UI, try adding a repo with Github App Authentication. The connection will fail and logs will show error something like `

**Expected behavior**

The expectation is for the Github Authentication to fail, but with an error that indicate TLS handshake error, something like 
```2026-02-17T15:35:06.009729951Z time="2026-02-17T15:35:06Z" level=debug msg="error string when doing ls remote: failed to list refs: could not refresh installation id <redacted>'s token: could not get access_tokens from GitHub API for installation ID <redacted>: net/http: TLS handshake timeout
``` 
rather than 
```
2026-02-17T15:35:06.009729951Z time="2026-02-17T15:35:06Z" level=debug msg="error string when doing ls remote: failed to list refs: could not refresh installation id <redacted>'s token: could not get access_tokens from GitHub API for installation ID <redacted>: context deadline exceeded
```

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
argocd: v3.2.0+66b2f30
  BuildDate: 2025-11-04T19:52:35Z
  GitCommit: 66b2f302d91a42cc151808da0eec0846bbe1062c
  GitTreeState: clean
  GoVersion: go1.25.3
  Compiler: gc
  Platform: darwin/arm64
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by anandf**
Fixes https://github.com/argoproj/argo-cd/issues/26749

Assisted-by: Claude code, Opus 4.6 model for unit tests, reviewed by author.

Currently, the GitHub App Authentication uses a custom `http.Transport` which does not set any timeout values. When these timeouts are not set, the default behaviour is it never timesout and the only thing that is interrupting the failed connection is the context deadline. This way for all network issues, like dialer timeout, tls handshake timeout, the error is `context deadline exceeded`, which makes the debugging difficult.

In this fix, when creating a custom `http.Transport` for performing the GitHub App based authentication, the `http.DefaultTransport` is cloned and the custom settings are overridden. The `http.DefaultTransport` contains the timeout values set instead of the default infinite timeout value, so that the error messages are meaningful and help in quick diagnosis. The earlier error message `context deadline exceeded` was not helping with the diagnosis of the actual issue.

The  value set for `ARGOCD_GIT_REQUEST_TIMEOUT`, is used for the context timeout as well instead of the hardcoded `15 * time.Second`. With this approach, it is possible to handle scenarios when there is too much latency in the network and users can set a higher value in those cases.

The added unit tests fail without the corresponding fix, ensuring that the fix works as expected.
 
Needs to be backported to all releases that uses go 1.23 or later
 i.e. `release-2.14`, `release-3.0`, `release-3.1`, `release-3.2`, `release-3.3`

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: util/git/client.go [hunk 1]
```diff
@@ -327,13 +327,12 @@ func GetRepoHTTPClient(repoURL string, insecure bool, creds Creds, proxyURL stri
...
-		TLSClientConfig: &tls.Config{
-			GetClientCertificate: clientCertFunc,
-		},
-		DisableKeepAlives: true,
+	transport := http.DefaultTransport.(*http.Transport).Clone()
+	transport.Proxy = proxyFunc
+	transport.TLSClientConfig = &tls.Config{
+		GetClientCertificate: clientCertFunc,
 	}
+	transport.DisableKeepAlives = true
```
Comment (ppapapetrou76) [inline util/git/client.go:335]: why this change here? -it's not the standard way of creating a go struct....

Comment (anandf) [reply util/git/client.go:335]: The change is for using the default http transport which has the required timeout values set and override only the fields that require customization. This pattern has been used in quite a number of places within the Argo CD project and I have used the same pattern here too. Alternative option is to create the struct from scratch and set all the default timeouts in it.
https://github.com/argoproj/argo-cd/blob/8a507b783e3ac3bd672ee2e8e95649d9fb08159b/applicationset/services/pull_request/gitea.go#L30
https://github.com/argoproj/argo-cd/blob/8a507b783e3ac3bd672ee2e8e95649d9fb08159b/applicationset/services/pull_request/gitlab.go#L36
https://github.com/argoproj/argo-cd/blob/8a507b783e3ac3bd672ee2e8e95649d9fb08159b/applicationset/services/scm_provider/gitea.go#L30
https://github.com/argoproj/argo-cd/blob/8a507b783e3ac3bd672ee2e8e95649d9fb08159b/applicationset/services/scm_provider/gitlab.go#L34
https://github.com/argoproj/argo-cd/blob/8a507b783e3ac3bd672ee2e8e95649d9fb08159b/applicationset/services/util.go#L17

**Review by ppapapetrou76 — APPROVED** [review]
LGTM 🏅  - thanks for addressing my comments

**Review by blakepettersson — APPROVED** [review]
LGTM, thanks!
