### PR TITLE
fix: Better enforcement of application namespace restrictions

### LINKED ISSUE #11116: ArgoCD doesn't respect application.namespaces
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I tried to use application namespaces (#9755) but there are problems in multi-argocd-instances environments. Problem is that neither application-controller nor server respects specified application namespaces.

There are two problems with argocd instance with application namespaces:
1) `server` displays `Application` resources from all namespaces (not only from the argocd home namespace and allowed namespaces using `ARGOCD_APPLICATION_NAMESPACES` env or `--application-namespaces` argument)
   note: argocd server UI displays unwanted Applications only when there is a change on them and refreshing UI these ones go away, but this is very confusing
2) argocd CLI/GUI can access any `Application` resource in any namespace (independent of "application namespaces" setting)
3) `application-controller` decorate foreign `Application` resources belonging to another argocd instance with `UnknownError` with message like `application 'helm-guestbook' in namespace 'argocd1' is not permitted to use project 'default'`

**To Reproduce**

1. deploy two argocd instances - `argocd1` without "application namespaces" and `argocd2` with `default` as "application namespace"
```shell
helm install argocd1 argo/argo-cd -n argocd1 --create-namespace --set "server.config.application\.instanceLabelKey=argocd.argoproj.io/instance-1" --set server.service.type=NodePort --set server.service.nodePortHttp=31080 --set server.service.nodePortHttps=31443
helm install argocd2 argo/argo-cd -n argocd2 --create-namespace --set "server.config.application\.instanceLabelKey=argocd.argoproj.io/instance-2" --set server.service.type=NodePort --set server.service.nodePortHttp=32080 --set server.service.nodePortHttps=32443 --set crds.install=false --set "configs.params.application\.namespaces=default"
```
2. allow `default` namespace for `argocd2` AppProject `default`
```shell
kubectl patch -n argocd2 appproject/default --type merge -p '{"spec": {"sourceNamespaces": ["default"]}}'
```
3. create namespaces for applications
```shell
kubectl create namespace helm-guestbook-1
kubectl create namespace helm-guestbook-2
kubectl create namespace helm-guestbook-default
```
4. create `Application` resources in namespaces: `argocd1` (for `argocd1` instance), `argocd2` (for `argocd2` instance) and `default` (also for `argocd2` instance as an application namespace)
```shell
cat <<EOF | kubectl create -f-
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd1
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook-2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook-default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOF
```

Now all three applications is accessible from both instances (tried with both argocd contexts):
```shell
# switch argocd CLI context to argocd1
argocd app get argocd1/helm-guestbook
argocd app get argocd2/helm-guestbook
argocd app get default/helm-guestbook
# switch argocd CLI context to argocd2
argocd app get argocd1/helm-guestbook
argocd app get argocd2/helm-guestbook
argocd app get default/helm-guestbook
```

Application `argocd1/helm-guestbook` (which belongs to `argocd1` instance) has error from `argocd2` `application controller` (which has nothing to do with it).
```shell
$ argocd app get argocd1/helm-guestbook | grep -A1 CONDITION

CONDITION     MESSAGE                                                                                        LAST TRANSITION
UnknownError  application 'helm-guestbook' in namespace 'argocd1' is not permitted to use project 'default'  2022-10-30 23:37:20 +0100 CET
```
Stopping `argocd2` `application-controller` and refreshing the application this error disappears

**Expected behavior**

I would expect following:
- `argocd` CLI displays only "own" application, i.e. `Application` resources only from its "home" namespace or "application namespaces"
- `argocd-server` GUI displays only "own" application, i.e. `Application` resources only from its "home" namespace or "application namespaces"
- `argocd-application-controller` ignores foreign `Application` resources, i.e. application from namespaces other than "home" namespace or "application namespaces"

**Version**

```shell
argocd: v2.5.0+b895da4.dirty
  BuildDate: 2022-10-25T19:12:35Z
  GitCommit: b895da457791d56f01522796a8c3cd0f583d5d91
  GitTreeState: dirty
  GoVersion: go1.19.2
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.0+b895da4
  BuildDate: 2022-10-25T14:40:01Z
  GitCommit: b895da457791d56f01522796a8c3cd0f583d5d91
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

### PR DESCRIPTION
**Pull request by jannfis**
Fixes https://github.com/argoproj/argo-cd/issues/11116

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

File: controller/appcontroller.go [hunk 1]
```diff
@@ -1879,6 +1885,14 @@ func (ctrl *ApplicationController) newApplicationInformerAndLister() (cache.Shar
...
 				app, ok := obj.(*appv1.Application)
 				if ok {
+					// If the application is not allowed to use the project,
+					// log an error.
+					if ctrl.isAppNamespaceAllowed(app) {
+						if _, err := ctrl.getAppProj(app); err != nil {
+							ctrl.setAppCondition(app, ctrl.projectErrorToCondition(err, app))
+						}
+					}
+
```
Comment (ishitasequeira) [inline controller/appcontroller.go:1895]: A quick question, should we move the validate destination within AppNamespaceAllowed check as well? Wondering if we need to separately check for it if the Application is not allowed to use the project.

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Comment by alexmt** [comment]
FYI : this change also addresses a bug that causes the application controller to disagree with itself and get stuck in an endless reconciliation loop. Steps to reproduce:

* create any Argo CD application 
* change it to use a non-existing project and target non-existing cluster
* the cluster must be referenced by name
* controller keep updating application conditions: keeps swapping project related error with cluster error and visa vera

The issue typically happens when the argocd user performs migration and forgets to cleanup no longer-used applications.
