### PR TITLE
fix: Add https prefix to ingress URLs if hosts field is present

### LINKED ISSUE #6884: application external url is exposed with http instead of https
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD dashboard shows external URL of app based on ingress host, but it uses "http" instead of "https".
It was originally fixed from https://github.com/argoproj/argo-cd/pull/4339.

But it doesn't seem to respect `tls` spec: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/

`tls` can have `hosts` string array, but `argocd` checks only `host` field: https://github.com/argoproj/argo-cd/blob/bcfc112d828476270c006a349be4c14228336be5/controller/cache/info.go#L146

I am pretty new to argoCD, so I am not sure, though.

**To Reproduce**

Create a simple app with ingress with host rule.

**Expected behavior**

URL scheme should be `https` when the host is included in `spec.tls[i].hosts[m]`.

**Screenshots**

ingress manifest: I defined host in tls host list.
image

external url seen from argocd dashboard: url is seen with `http` instead of `https`
image

**Version**

```shell
argocd: v2.0.5+4c94d88.dirty
  BuildDate: 2021-07-23T05:12:02Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: dirty
  GoVersion: go1.16.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.5+4c94d88
```

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #6884

Signed-off-by: Remington Breeze <remington@breeze.software>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM

File: controller/cache/info.go [hunk 1]
```diff
@@ -146,6 +146,13 @@ func populateIngressInfo(un *unstructured.Unstructured, res *ResourceInfo) {
 						tlshost := tlsline["host"]
 						if tlshost == host {
 							stringPort = "https"
+							continue
+						}
+						tlshosts := tlsline["hosts"].(map[string]interface{})
```
Comment (alexmt) [inline controller/cache/info.go:151]: Ops, TestGetIngressInfoWithHost crashed with a panic. 
Please add a check to avoid panic here.

**Review by alexmt — CHANGES_REQUESTED** [review]

File: controller/cache/info.go [hunk 2]
```diff
@@ -146,6 +146,15 @@ func populateIngressInfo(un *unstructured.Unstructured, res *ResourceInfo) {
 						tlshost := tlsline["host"]
 						if tlshost == host {
 							stringPort = "https"
+							continue
+						}
+						if hosts := tlsline["hosts"]; hosts != nil {
+							tlshosts := tlsline["hosts"].(map[string]interface{})
```
Comment (alexmt) [inline controller/cache/info.go:152]: It is unlikely but if one day `hosts` got converted to list this code will crash. Can you add a cast check similar to check of `tlsline`? E.g.:

```
tlshosts, ok := tlsline["hosts"].(map[string]interface{})
if ok {
	for j := range tlshosts {
		if tlshosts[j] == host {
			stringPort = "https"
		}
	}
}
```

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
LGTM
