### PR TITLE
fix: Better handling of K8s secrets for repository credentials & templates (#3016 #3028)

### LINKED ISSUE #3016: v1.4 SSH credential template not working
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Trying to add a credential template for SSH repositories seems to fail.

I've replaced our companies github url with [enterprise github] and the name of the github organization I'm trying to add repos from with [organization] in the code below.

The help page for `argocd repocreds` states:
```
# Add credentials with SSH private key authentication to use for all repositories under https://git.example.com/repos
  argocd repocreds add https://git.example.com/repos/ --ssh-private-key-path ~/.ssh/id_rsa
```
this results in:
```
$ argocd repocreds add https://[enterprise github]/[organization-name]/ --ssh-private-key-path ~/.ssh/argo
FATA[0000] --ssh-private-key-path is only supported for SSH repositories.
```

Assuming the help page is incorrect, I tried using the SSH url instead, as one would when adding a single repo. An error gets thrown because of the '@':
```
$ argocd repocreds add git@[enterprise github]:[organization] --ssh-private-key-path ~/.ssh/argo
FATA[0000] rpc error: code = InvalidArgument desc = Secret "repo-git@[enterprise github]:[organization]-3092902216" is invalid: metadata.name: Invalid value: "repo-git@[enterprise github]:[organization]-3092902216": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
Leaving out the `git@` part:
```
$ argocd repocreds add [enterprise github]:[organization] --ssh-private-key-path ~/.ssh/argo
FATA[0000] --ssh-private-key-path is only supported for SSH repositories.
```

**Expected behavior**

A template that causes ArgoCD to automatically uses the given private key when fetching repos of the specified organization.

**Version**

```shell
argocd: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:53:00Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:55:02Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

### LINKED ISSUE #3028: K8s secrets for repository credential templates are not deleted when credential template is deleted
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The K8s secret that is created to store the secrets used for repository credentials are not deleted when the repository credential is deleted, thus leaving orphaned K8s secrets behind. 

**To Reproduce**

- Create repository credential template, i.e. `argocd repocreds add https://yourserver/path --ssh-private-key-path ~/.ssh/id_rsa`
- A corresponding K8s secret is created in `argocd` namespace
- Delete the credential template created in first step, i.e. `argocd repocreds rm https://yourserver/path`
- Check that previously created K8s secret still exist in cluster

**Expected behavior**

The corresponding K8s secret should be deleted when the credential template is removed

**Screenshots**

**Version**

```shell
argocd: v1.4.0+b28bdb7.dirty
  BuildDate: 2020-01-22T10:10:27Z
  GitCommit: b28bdb7f4dc971f1d4f28cd28546aba2ed09c0a6
  GitTreeState: dirty
  GoVersion: go1.12.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v99.99.99+unknown
  BuildDate: 1970-01-01T00:00:00Z
  GitCommit: 
  GitTreeState: 
  GoVersion: go1.12.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: vdev-2019-05-15T19:48:06+0200
  Kustomize Version: Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:linux GoArch:amd64}
  Helm Version: v2.13.1
  Kubectl Version: v1.15.2

```

### PR DESCRIPTION
**Pull request by jannfis**
This PR fixes correct deletion of credential templates secrets when the corresponding template is deleted from ArgoCD (fixes #3028) and also handle secret generation in a much more stable way (fixes #3016).

It changes the name of newly generated secrets in that it will not encode part of the repo or template URL into the name anymore, and just uses the FNV hash as identifier (i.e. `repo-XYZ`, where `XYZ` is the hash represented as number). Also, to better differentiate between actual repository credential secrets and credential template secrets, the latter will be prefixed with `creds-` instead of `repo-`. This change is not breaking and fully backward compatible, as existing secrets will not be touched.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

File: test/e2e/fixture/fixture.go [hunk 1]
```diff
@@ -55,7 +55,6 @@ var (
 	KubeClientset       kubernetes.Interface
 	AppClientset        appclientset.Interface
 	ArgoCDClientset     argocdclient.Client
-	settingsManager     *settings.SettingsManager
```
Comment (jannfis) [inline test/e2e/fixture/fixture.go]: The linter accused this of being unused, and I think it was right.

File: test/e2e/fixture/fixture.go [hunk 2]
```diff
@@ -123,7 +122,6 @@ func init() {
 	})
 	CheckError(err)
 
-	settingsManager = settings.NewSettingsManager(context.Background(), KubeClientset, "argocd-e2e")
```
Comment (jannfis) [inline test/e2e/fixture/fixture.go]: Same as above.

**Review by alexmt — APPROVED** [review]
LGTM. Thank you @jannfis !
