### PR TITLE
fix: do not normalize resource tracking on live crds

### LINKED ISSUE #22721: CRDs are reporting an incorrect diff when `ServerSideDiff` + annotation tracking is used
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* ~[ ] I've pasted the output of `argocd version`~. (this is happening on `master` and at least since 2.14)

**Describe the bug**

When `ServerSideDiff` is used in conjunction with annotation resource tracking, the live CRDs incorrectly get a diff of a tracking annotation that should be removed. The tracking annotation is not there nor should it be there in the first place.

**To Reproduce**

Apply this application

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.1.4
    chart: kyverno
    helm:
      releaseName: kyverno
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
```

**Expected behavior**

No diffs should appear on the CRDs; they should be `Synced`.

**Screenshots**

Image

Image

**Logs**

N/A

### PR DESCRIPTION
**Pull request by blakepettersson**
Fixes #22721. CRDs should not have resource annotations set on them. This normalization causes erroneus diffs when used with ServerSideDiff.

This should be cherry-picked for 2.12 - 3.0.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by blakepettersson** [comment]
Draft pending writing tests for this.

File: util/argo/resource_tracking.go [hunk 1]
```diff
@@ -232,23 +233,25 @@ func (rt *resourceTracking) Normalize(config, live *unstructured.Unstructured, l
...
 
-	annotation, err := kube.GetAppInstanceAnnotation(config, common.AnnotationKeyAppInstance)
-	if err != nil {
-		return err
-	}
-	err = kube.SetAppInstanceAnnotation(live, common.AnnotationKeyAppInstance, annotation)
-	if err != nil {
-		return err
-	}
+	if !kubeutil.IsCRD(live) {
```
Comment (crenshaw-dev) [inline util/argo/resource_tracking.go:236]: I'd short-circuit instead of nesting

```go
if kubeutil.IsCRD(live) {
// CRDs don't get tracking annotations.
return nil
}
```

File: util/argo/resource_tracking_test.go [hunk 2]
```diff
@@ -204,6 +204,50 @@ func TestResourceIdNormalizer_Normalize(t *testing.T) {
...
+			},
+			"spec": map[string]any{
+				"group": "stable.example.com",
+				"scope": "Namespaced",
+			},
+		},
+	}
+
+	// config object is a CRD resource
+	configObj := &unstructured.Unstructured{
```
Comment (nitishfy) [inline util/argo/resource_tracking_test.go:229]:
```suggestion
	configObj := &unstructured.Unstructured{
```

what is configObj representing here? The CRD present in git?

**Review by nitishfy — COMMENTED** [review]
One minor comment added otherwise LGTM!

**Review by gdsoumya — APPROVED** [review]

File: util/argo/resource_tracking_test.go (hunk 2 above)
Comment (blakepettersson) [reply util/argo/resource_tracking_test.go:229]: @nitishfy that's right, the `configObj` is a manifest that the repo-server has extracted from Git (or Helm) and the application-controller in turn would like to apply to the cluster. The `liveObj` is the actual object found in the cluster.

**Comment by nitishfy** [comment]
@blakepettersson If you want this to be cherry-picked for v2.13 and prior, I am afraid you'll have to manually raise a PR for those brances.
