### PR TITLE
fix: Make change of tracking method work at runtime

### LINKED ISSUE #9781: Argo CD loses track of managed live resource when switching tracking method
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When switching tracking method from `label` to `annotation` (or vice versa) in a running Argo CD system, Argo CD will lose track of managed live resources, resulting in a situation where Argo CD will not pick up changes to live resources and also fails to prune them.

**To Reproduce**

* Create the `guestbook` Application:
  ```shell
  $ argocd app create guestbook --repo https://github.com/argoproj/argocd-example-apps.git --path guestbook --dest-namespace guestbook --dest-server https://kubernetes.default.svc --sync-option CreateNamespace=true
  application 'guestbook' created
  ```

* Sync application
  ```shell
  $ argocd app sync guestbook
  TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS    HEALTH        HOOK  MESSAGE
  2022-06-24T10:23:26+00:00            Service   guestbook          guestbook-ui  OutOfSync  Missing              
  2022-06-24T10:23:26+00:00   apps  Deployment   guestbook          guestbook-ui  OutOfSync  Missing              
  2022-06-24T10:23:29+00:00          Namespace                         guestbook   Running   Synced              namespace/guestbook created
  2022-06-24T10:23:29+00:00          Namespace                         guestbook  Succeeded   Synced              namespace/guestbook created
  2022-06-24T10:23:29+00:00            Service   guestbook          guestbook-ui  OutOfSync  Missing              service/guestbook-ui created
  2022-06-24T10:23:29+00:00   apps  Deployment   guestbook          guestbook-ui  OutOfSync  Missing              deployment.apps/guestbook-ui created

  Name:               guestbook
  Project:            default
  Server:             https://kubernetes.default.svc
  Namespace:          guestbook
  URL:                http://127.0.0.1:8080/applications/guestbook
  Repo:               https://github.com/argoproj/argocd-example-apps.git
  Target:             
  Path:               guestbook
  SyncWindow:         Sync Allowed
  Sync Policy:        <none>
  Sync Status:        Synced to  (53e28ff)
  Health Status:      Progressing

  Operation:          Sync
  Sync Revision:      53e28ff20cc530b9ada2173fbbd64d48338583ba
  Phase:              Succeeded
  Start:              2022-06-24 10:23:26 +0000 UTC
  Finished:           2022-06-24 10:23:29 +0000 UTC
  Duration:           3s
  Message:            successfully synced (all tasks run)

  GROUP  KIND        NAMESPACE  NAME          STATUS     HEALTH       HOOK  MESSAGE
         Namespace              guestbook     Succeeded  Synced             namespace/guestbook created
         Service     guestbook  guestbook-ui  Synced     Healthy            service/guestbook-ui created
  apps   Deployment  guestbook  guestbook-ui  Synced     Progressing        deployment.apps/guestbook-ui created

  ```
  
* Check that application is healthy and in sync
  ```shell
  $ argocd app list
  NAME       CLUSTER                         NAMESPACE  PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                                 PATH       TARGET
  guestbook  https://kubernetes.default.svc  guestbook  default  Synced  Healthy  <none>      <none>      https://github.com/argoproj/argocd-example-apps.git  guestbook  
  ```
  
* Change a managed live resource in the cluster and check that Argo CD is aware of it
  ```shell
  $ kubectl patch -n guestbook deployments.apps guestbook-ui --patch='{"spec":{"replicas":2}}'
  deployment.apps/guestbook-ui patched
  
  $ argocd app list
  NAME       CLUSTER                         NAMESPACE  PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO                                                 PATH       TARGET
  guestbook  https://kubernetes.default.svc  guestbook  default  OutOfSync  Healthy  <none>      <none>      https://github.com/argoproj/argocd-example-apps.git  guestbook  

  ```

* Revert change by syncing the app
  ```shell
  $ argocd app sync
  TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS    HEALTH        HOOK  MESSAGE
  2022-06-24T10:36:12+00:00            Service   guestbook          guestbook-ui    Synced   Healthy              
  2022-06-24T10:36:12+00:00   apps  Deployment   guestbook          guestbook-ui  OutOfSync  Healthy              
  2022-06-24T10:36:12+00:00            Service   guestbook          guestbook-ui    Synced   Healthy              service/guestbook-ui unchanged
  2022-06-24T10:36:12+00:00   apps  Deployment   guestbook          guestbook-ui  OutOfSync  Healthy              deployment.apps/guestbook-ui configured

  Name:               guestbook
  Project:            default
  Server:             https://kubernetes.default.svc
  Namespace:          guestbook
  URL:                http://127.0.0.1:8080/applications/guestbook
  Repo:               https://github.com/argoproj/argocd-example-apps.git
  Target:             
  Path:               guestbook
  SyncWindow:         Sync Allowed
  Sync Policy:        <none>
  Sync Status:        Synced to  (53e28ff)
  Health Status:      Healthy

  Operation:          Sync
  Sync Revision:      53e28ff20cc530b9ada2173fbbd64d48338583ba
  Phase:              Succeeded
  Start:              2022-06-24 10:36:12 +0000 UTC
  Finished:           2022-06-24 10:36:12 +0000 UTC
  Duration:           0s
  Message:            successfully synced (all tasks run)

  GROUP  KIND        NAMESPACE  NAME          STATUS  HEALTH   HOOK  MESSAGE
         Service     guestbook  guestbook-ui  Synced  Healthy        service/guestbook-ui unchanged
  apps   Deployment  guestbook  guestbook-ui  Synced  Healthy        deployment.apps/guestbook-ui configured
  ```
  
* Change tracking method to annotation
  ```shell
  $ kubectl patch configmaps argocd-cm --patch='{"data": {"application.resourceTrackingMethod": "annotation"}}'
  configmap/argocd-cm patched
  ```
  
* Sync application to apply annotation to live resources and remove previous label
  ```shell
  $ argocd app sync guestbook
  TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
  2022-06-24T10:39:29+00:00   apps  Deployment   guestbook          guestbook-ui    Synced  Healthy              
  2022-06-24T10:39:29+00:00            Service   guestbook          guestbook-ui    Synced  Healthy              

  Name:               guestbook
  Project:            default
  Server:             https://kubernetes.default.svc
  Namespace:          guestbook
  URL:                http://127.0.0.1:8080/applications/guestbook
  Repo:               https://github.com/argoproj/argocd-example-apps.git
  Target:             
  Path:               guestbook
  SyncWindow:         Sync Allowed
  Sync Policy:        <none>
  Sync Status:        Synced to  (53e28ff)
  Health Status:      Healthy

  Operation:          Sync
  Sync Revision:      53e28ff20cc530b9ada2173fbbd64d48338583ba
  Phase:              Succeeded
  Start:              2022-06-24 10:39:29 +0000 UTC
  Finished:           2022-06-24 10:39:30 +0000 UTC
  Duration:           1s
  Message:            successfully synced (all tasks run)

  GROUP  KIND        NAMESPACE  NAME          STATUS  HEALTH   HOOK  MESSAGE
         Service     guestbook  guestbook-ui  Synced  Healthy        service/guestbook-ui configured
  apps   Deployment  guestbook  guestbook-ui  Synced  Healthy        deployment.apps/guestbook-ui configured
  ```
  
* Check annotation has been applied, and label has been removed
  ```shell
  $ kubectl get -n guestbook deployments.apps guestbook-ui -o jsonpath='{.metadata.annotations.argocd\.argoproj\.io\/tracking-id}'
  guestbook:apps/Deployment:guestbook/guestbook-ui
  $ kubectl get -n guestbook deployments.apps guestbook-ui -o jsonpath='{.metadata.labels.app\.kubernetes\.io\/instance}'
  # <empty>
  ```
  
* Patch managed live resource again
  ```shell
  $ kubectl patch -n guestbook deployments.apps guestbook-ui --patch='{"spec":{"replicas":4}}'
  ```
  
* Observe that Argo CD has not picked up the change (i.e. Application is still in Synced state)
  ```shell
  $ argocd app list
  NAME       CLUSTER                         NAMESPACE  PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                                 PATH       TARGET
  guestbook  https://kubernetes.default.svc  guestbook  default  Synced  Healthy  <none>      <none>      https://github.com/argoproj/argocd-example-apps.git  guestbook  
  ```
  
* Delete the app with cascade, and observe that resources will not get removed:
  ```shell
  $ argocd app delete guestbook --cascade
  Are you sure you want to delete 'guestbook' and all its resources? [y/n]
  y
  application 'guestbook' deleted
  $ kubectl get -n guestbook all
  NAME                               READY   STATUS    RESTARTS   AGE
  pod/guestbook-ui-6b689986f-dqgvm   1/1     Running   0          13m
  pod/guestbook-ui-6b689986f-hsdlt   1/1     Running   0          2m32s

  NAME                   TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
  service/guestbook-ui   ClusterIP   10.43.104.8   <none>        80/TCP    13m

  NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
  deployment.apps/guestbook-ui   2/2     2            2           13m

  NAME                                     DESIRED   CURRENT   READY   AGE
  replicaset.apps/guestbook-ui-6b689986f   2         2         2       13m
  ```

**Expected behavior**

Argo CD being able to switch resource tracking methods while running.

**Screenshots**

**Version**

Latest code in `master` branch as of 2022-06-24 13:00:00 CEST (commit 9d4c940a5afb19a08af1e4ab315fb32c13a6297a)

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #9781

The handler for populating resource information would not pick up changes to the tracking methods at runtime.

This fix makes the tracking method be part of settings, so that the controller gets notified on changes to pick up any change to the setting and updates the cluster cache settings struct appropriately.

Signed-off-by: jannfis <jann@mistrust.net>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: controller/cache/cache.go [hunk 1]
```diff
@@ -400,9 +400,10 @@ func (c *liveStateCache) getCluster(server string) (clustercache.ClusterCache, e
 		clustercache.SetPopulateResourceInfoHandler(func(un *unstructured.Unstructured, isRoot bool) (interface{}, bool) {
 			res := &ResourceInfo{}
 			populateNodeInfo(un, res)
+			cacheSettings := c.cacheSettings
```
Comment (jannfis) [inline controller/cache/cache.go:403]: I was wondering, do I need to acquire a lock on the `c.lock` mutex here?

Comment (jessesuen) [reply controller/cache/cache.go:403]: Isn't it happening already on line 374?

Comment (jannfis) [reply controller/cache/cache.go:403]: Yes, but this is a call-back function, which will be called outside the scope of the lock on line 374

Comment (jannfis) [reply controller/cache/cache.go:403]: Also, looking at the code between lines 365 and 368, the assignment of `c.cacheSettings` is also done in a locked way. So probably makes sense to lock it here as well, just for the assignment to `cacheSettings`. 

However, since the `PopulateResourceInfoHandler` will be called on every resource on the cluster, I'm wondering about the performance impact of this lock.

Comment (crenshaw-dev) [reply controller/cache/cache.go:403]: Mutexes break my brain. What problem would the mutex solve?

Comment (jannfis) [reply controller/cache/cache.go:403]: @crenshaw-dev `c.cacheSettings` is a variable of composite type. The mutex would ensure exclusive operation on that variable for the current holder of the lock on the mutex, to ensure that no other goroutine would modify any of the fields in that struct at the same time we copy it (given that the other goroutine also tries to acquire a lock on the same mutex).

For example, `c.cacheSettings` is modified whenever there are changes to the Argo CD settings.

Comment (crenshaw-dev) [reply controller/cache/cache.go:403]: That much I follow. But I'm trying to understand what the lock would span and what problem it would prevent. I'm not sure why we'd care if `c.cacheSettings` changed in the context of one of these callback executions.

Comment (jannfis) [reply controller/cache/cache.go:403]: The lock would span the copy operation of assigning `c.cacheSettings` to the local variable `cacheSettings`, to perform the copy as one atomic operation.

Maybe in the current context, this doesn't seem to be important. However, when the cache settings get expanded at some point in time, and another process modifies the settings while we copy it, we may end up with non-working data.

Comment (crenshaw-dev) [reply controller/cache/cache.go:403]: Makes sense, thanks!

Comment (jannfis) [reply controller/cache/cache.go:404]: Thanks, I added the read locks.

File: util/settings/settings.go [hunk 2]
```diff
@@ -1271,6 +1273,7 @@ func updateSettingsFromConfigMap(settings *ArgoCDSettings, argoCDCM *apiv1.Confi
 	}
 	settings.InClusterEnabled = argoCDCM.Data[inClusterEnabledKey] != "false"
 	settings.ExecEnabled = argoCDCM.Data[execEnabledKey] == "true"
+	settings.TrackingMethod = argoCDCM.Data[settingsResourceTrackingMethodKey]
```
Comment (crenshaw-dev) [inline util/settings/settings.go:1276]: Should this be documented here? https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml

**Review by crenshaw-dev — APPROVED** [review]
One nitpick, but lgtm even without the change.

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.4 for 2.4.6.
