### PR TITLE
Issue #2060 - Make sure endpoint is shown as a child of service

### LINKED ISSUE #2060: Endpoint is no longer shown as a child of services
We used to show endpoint objects as a child of services. In v1.1, we no longer, which is a regression.

image

### PR DESCRIPTION
**Pull request by alexmt**
Closes #2060

### CODE REVIEW

File: controller/cache/node.go [hunk 1]
```diff
@@ -35,6 +35,11 @@ func (n *node) resourceKey() kube.ResourceKey {
 }
 
 func (n *node) isParentOf(child *node) bool {
+	// Special case for endpoint. Remove after https://github.com/kubernetes/kubernetes/issues/28483 is fixed
+	if len(child.ownerRefs) == 0 && child.ref.APIVersion == "v1" && child.ref.Kind == kube.EndpointsKind && n.ref.APIVersion == "v1" && n.ref.Kind == kube.ServiceKind && n.ref.Name == child.ref.Name {
+		child.ownerRefs = []metav1.OwnerReference{{Name: n.ref.Name, Kind: n.ref.Kind, APIVersion: n.ref.APIVersion, UID: n.ref.UID}}
```
Comment (alexec) [inline controller/cache/node.go]: no test?

**Review by alexec — CHANGES_REQUESTED** [review]

File: controller/cache/node.go (hunk 1 above)
Comment (alexmt) [reply controller/cache/node.go]: oh, you are right. Added missing test

**Review by alexec — APPROVED** [review]
