### PR TITLE
fix: do not fail on manifest-like yaml files - fixes #21934

### LINKED ISSUE #21934: Failed to unmarshal "config.yaml": <nil>
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Through the helm chart, argo-cd should deploy the following manifests to kubernetes
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool-1
spec:
  limits:
    memory: 192Gi
  template:
    metadata:
      labels:
        node-group: nodepool-1
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: generic
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - r6a
        - key: karpenter.k8s.aws/instance-memory
          operator: In
          values:
            - '4096'
      startupTaints:
        - effect: NoExecute
          key: node.cilium.io/agent-not-ready
          value: 'true'
      taints:
        - effect: NoSchedule
          key: node-group
          value: nodepool-1
```
We also use this helm template in our helm chart
```yaml
{{- if .Values.karpenterNodePools }}
{{-   range .Values.karpenterNodePools }}
{{-     $namespace := $.Release.Namespace }}
{{-     $apiVersion := .apiVersion }}
{{-     if not $apiVersion }}
{{-         $apiVersion = "karpenter.sh/v1beta1" }}
{{-     end }}
{{-     $name := .name }}
{{-     $spec := .spec }}
---
apiVersion: {{ $apiVersion }}
kind: NodePool
metadata:
  name: {{ $namespace }}-{{ $name }}
spec:
{{-      if $spec }}
  {{- toYaml .spec | nindent 2 }}
{{-      end }}
...
{{-   end }}
{{- end }}
```
and this `config.yaml`
```yaml
karpenterNodePools:
  - name: nodepool-1
    apiVersion: karpenter.sh/v1
    spec:
      template:
        metadata:
          labels:
            node-group: nodepool-1
        spec:
          nodeClassRef:
            name: generic
            kind: EC2NodeClass
            group: karpenter.k8s.aws
          startupTaints:
            - key: node.cilium.io/agent-not-ready
              value: "true"
              effect: NoExecute
          taints:
            - key: node-group
              effect: NoSchedule
              value: nodepool-1
          requirements:
            - key: karpenter.sh/capacity-type
              operator: In
              values: ["on-demand"]
            - key: karpenter.k8s.aws/instance-family
              operator: In
              values: ["r6a"]
            - key: karpenter.k8s.aws/instance-memory
              operator: In
              values: ["4096"]
      limits:
        memory: 192Gi
```
As soon as we try to start synchronization, the application freezes with an error
```bash
ComparisonError: Failed to load target state: failed to generate manifest for source 2 of 2: rpc error: code = FailedPrecondition desc = Failed to unmarshal "config.yaml": <nil>
```
Experimentally, we found out that reading `config.yml` starts to break as soon as we add these two parameters.
```yaml
            kind: EC2NodeClass
            group: karpenter.k8s.aws
```
If we remove them, the application starts to work correctly.
We also tried to reproduce the problem directly by running the `helm template` with this `config.yaml` and our diagram for argo-cd, but we were unable to reproduce this problem.

**To Reproduce**

1. Make helm chart with the following template
```yaml
{{- if .Values.karpenterNodePools }}
{{-   range .Values.karpenterNodePools }}
{{-     $namespace := $.Release.Namespace }}
{{-     $apiVersion := .apiVersion }}
{{-     if not $apiVersion }}
{{-         $apiVersion = "karpenter.sh/v1beta1" }}
{{-     end }}
{{-     $name := .name }}
{{-     $spec := .spec }}
---
apiVersion: {{ $apiVersion }}
kind: NodePool
metadata:
  name: {{ $namespace }}-{{ $name }}
spec:
{{-      if $spec }}
  {{- toYaml .spec | nindent 2 }}
{{-      end }}
...
{{-   end }}
{{- end }}
```
2. Make config.yaml with the following content
```yaml
karpenterNodePools:
  - name: nodepool-1
    apiVersion: karpenter.sh/v1
    spec:
      template:
        metadata:
          labels:
            node-group: nodepool-1
        spec:
          nodeClassRef:
            name: generic
            kind: EC2NodeClass
            group: karpenter.k8s.aws
          startupTaints:
            - key: node.cilium.io/agent-not-ready
              value: "true"
              effect: NoExecute
          taints:
            - key: node-group
              effect: NoSchedule
              value: nodepool-1
          requirements:
            - key: karpenter.sh/capacity-type
              operator: In
              values: ["on-demand"]
            - key: karpenter.k8s.aws/instance-family
              operator: In
              values: ["r6a"]
            - key: karpenter.k8s.aws/instance-memory
              operator: In
              values: ["4096"]
      limits:
        memory: 192Gi
```
3. Add the application to argo-cd
4. Start synchronization

**Expected behavior**
Argo-CD should correctly process the following `config.yaml` file
```yaml
karpenterNodePools:
  - name: nodepool-1
    apiVersion: karpenter.sh/v1
    spec:
      template:
        metadata:
          labels:
            node-group: nodepool-1
        spec:
          nodeClassRef:
            name: generic
            kind: EC2NodeClass
            group: karpenter.k8s.aws
          startupTaints:
            - key: node.cilium.io/agent-not-ready
              value: "true"
              effect: NoExecute
          taints:
            - key: node-group
              effect: NoSchedule
              value: nodepool-1
          requirements:
            - key: karpenter.sh/capacity-type
              operator: In
              values: ["on-demand"]
            - key: karpenter.k8s.aws/instance-family
              operator: In
              values: ["r6a"]
            - key: karpenter.k8s.aws/instance-memory
              operator: In
              values: ["4096"]
      limits:
        memory: 192Gi
```

**Screenshots**
Image
Image

**Version**

```shell
argocd: v2.14.1+3345d05
  BuildDate: 2025-02-03T21:23:31Z
  GitCommit: 3345d05a43d8edd7ec42ec71ffe8b5f95bc68dbe
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2025-02-21T13:44:42Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal \"config.yaml\": <nil>" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2025-02-21T13:44:42Z" grpc.time_ms=13.638 span.kind=server system=grpc
```

### PR DESCRIPTION
**Pull request by CefBoud**
# Description 
Fixes https://github.com/argoproj/argo-cd/issues/21934

Repositories may contain YAML files that resemble valid k8s manifests, as they include `apiVersion`, `metadata`, and `kind`, but are not necessarily valid k8s manifests.  An example highlighted in [this GitHub issue](https://github.com/argoproj/argo-cd/issues/21934)  involves a Helm values file that could be mistaken for a manifest.

Currently, these manifest-like YAMLs cause an error in the form of `Failed to unmarshal "{filename}": <nil>` that stops the Application from continuing. 

This PR replaces the error with a warning  without stopping execution. The rationale being that manifest-like files are allowed to exist but a warning is issued to provide information on true positives (manifest that are malformed).

# Alternative
A potential downside of this change is that invalid manifests (true positives) will only trigger a warning rather than causing a failure. An alternative approach to address this could be to introduce an annotation or comment, such as `# ArgoCD: IgnoreNotAManifest`, which can be added to non-manifest YAML files. This would allow those manifests to be ignored if their unmarshalling fails.

# Testing
https://github.com/argoproj/argo-cd/issues/21934 contains a fairly simple way to reproduce the problem. Using this PR's branch should allow the Application to proceed while logging the warning.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by nitishfy — CHANGES_REQUESTED** [review]
Couple of things that I'd suggest here doing:

1. Please add a test case to validate the behaviour.
2. Please fix the failing tests. They are failing because we are not returning an error when the manifest is invalid.
```
=== FAIL: reposerver/repository TestInvalidManifestsInDir (0.00s)
time="2025-02-27T00:26:33Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:,Path:./testdata/invalid-manifests,TargetRevision:,Helm:nil,Kustomize:nil,Directory:&ApplicationSourceDirectory{Recurse:true,Jsonnet:ApplicationSourceJsonnet{ExtVars:[]JsonnetVar{},TLAs:[]JsonnetVar{},Libs:[],},Exclude:,Include:,},Plugin:nil,Chart:,Ref:,Name:,}/mock.Anything"
time="2025-02-27T00:26:33Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:,Path:./testdata/invalid-manifests,TargetRevision:,Helm:nil,Kustomize:nil,Directory:&ApplicationSourceDirectory{Recurse:true,Jsonnet:ApplicationSourceJsonnet{ExtVars:[]JsonnetVar{},TLAs:[]JsonnetVar{},Libs:[],},Exclude:,Include:,},Plugin:nil,Chart:,Ref:,Name:,}/mock.Anything"
time="2025-02-27T00:26:33Z" level=warning msg="Failed to unmarshal \"bad.yaml\": file contains 'apiVersion:', 'kind:', and 'metadata:', but is not a valid manifest: failed to unmarshal manifest: error converting YAML to JSON: yaml: line 3: did not find expected key" application=
    repository_test.go:680: 
        	Error Trace:	/home/runner/work/argo-cd/argo-cd/reposerver/repository/repository_test.go:680
        	Error:      	An error is expected but got nil.
        	Test:       	TestInvalidManifestsInDir

=== FAIL: reposerver/repository Test_findManifests/invalid_manifest_throws_an_error (0.00s)
time="2025-02-27T00:26:36Z" level=warning msg="Failed to unmarshal \"bad.yaml\": file contains 'apiVersion:', 'kind:', and 'metadata:', but is not a valid manifest: failed to unmarshal manifest: error converting YAML to JSON: yaml: line 3: did not find expected key" test=test
    repository_test.go:2810: 
        	Error Trace:	/home/runner/work/argo-cd/argo-cd/reposerver/repository/repository_test.go:2810
        	Error:      	An error is expected but got nil.
        	Test:       	Test_findManifests/invalid_manifest_throws_an_error
```

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -1746,12 +1746,12 @@ func getObjsFromYAMLOrJSON(logCtx *log.Entry, manifestPath string, filename stri
...
 			// Read the whole file to check whether it looks like a manifest.
-			out, err := utfutil.ReadFile(manifestPath, utfutil.UTF8)
-			// Otherwise, let's see if it looks like a resource, if yes, we return error
+			out, _ := utfutil.ReadFile(manifestPath, utfutil.UTF8)
+			// Otherwise, let's see if it looks like a resource, if yes, we log a warning.
 			if bytes.Contains(out, []byte("apiVersion:")) &&
 				bytes.Contains(out, []byte("kind:")) &&
 				bytes.Contains(out, []byte("metadata:")) {
-				return status.Errorf(codes.FailedPrecondition, "Failed to unmarshal %q: %v", filename, err)
+				logCtx.Warnf("Failed to unmarshal %q: file contains 'apiVersion:', 'kind:', and 'metadata:', but is not a valid manifest: %v", filename, err)
```
Comment (andrii-korotkov-verkada) [inline reposerver/repository/repository.go:1754]: What if it's an actual invalid yaml which is a manifest?

Comment (CefBoud) [reply reposerver/repository/repository.go:1754]: It would simply log a warning, as mentioned in the PR description. 
There's also an "Alternative" section where I suggest adding an annotation to mark non-manifest YAML files. This would maintain the existing behavior and also allow to fix the issue this PR is trying to address.

**Review by andrii-korotkov-verkada — APPROVED** [review]

File: reposerver/repository/repository.go (hunk 1 above)
Comment (ishitasequeira) [inline reposerver/repository/repository.go:1754]: Let's keep the err on line 1749 and log it as part of the warning.

Comment (CefBoud) [reply reposerver/repository/repository.go]: @ishitasequeira Thanks for review.
If the file read fails, I think it doesn't make much sense to run the following `if bytes.Contains(out, []byte(...))`. 

I suggest returning an error instead:

```go
out, rerr := utfutil.ReadFile(manifestPath, utfutil.UTF8)
if rerr != nil {
    return status.Errorf(codes.FailedPrecondition, "Failed to read %q: %v", filename, rerr)
    }
```

Let me know what you think.

Comment (ishitasequeira) [reply reposerver/repository/repository.go]: Thanks @CefBoud, that would actually be better and I see that you have already addressed that in your latest commits.

**Review by ishitasequeira — COMMENTED** [review]
Overall change looks good to me. @CefBoud can you resolve the conflicts?

File: reposerver/repository/repository.go
Comment (agaudreault) [inline reposerver/repository/repository.go:1]: I think I disagree with the idea of having this feature merged because the risk of ignoring malformed yaml error that could cause resources to be automatically pruned is just to big. 

In my opinion, the only way we can safely ignore "kubernetes-like" resources is if they follow the kubernetes pattern of annotations as well and they explicitly specify an annotation such as `argocd.argoproj.io/ignore-rendering: true`.

Let me know what you think, maybe i over evaluate the risks here.

**Review by agaudreault — CHANGES_REQUESTED** [review]

File: reposerver/repository/repository.go
Comment (CefBoud) [reply reposerver/repository/repository.go:1]: Thanks for chiming in, @agaudreault. I mentioned this in the Alternatives section of the PR description, and now that you say it, I believe it's best to stay on the safe side. Adding support for skipping files containing `+argocd:skip-rendering` seems like the right approach.
I've made the changes. Let me know what you think.

CC @ishitasequeira @andrii-korotkov-verkada

File: reposerver/repository/repository.go [hunk 2]
```diff
@@ -1814,6 +1817,15 @@ func getPotentiallyValidManifestFile(path string, f os.FileInfo, appPath, repoRo
 		return nil, "", nil
 	}
 
+	// Read the whole file to check whether it looks like a manifest.
+	out, rerr := utfutil.ReadFile(path, utfutil.UTF8)
+	if rerr != nil {
+		return nil, "", fmt.Errorf("failed to read %q: %w", relPath, rerr)
+	}
+	//	skip file if it contains "+argocd:skip-rendering"
```
Comment (agaudreault) [inline reposerver/repository/repository.go]:
```suggestion
	// skip file if it contains "+argocd:skip-rendering"
```

File: reposerver/repository/repository.go [hunk 3]
```diff
@@ -1814,6 +1817,15 @@ func getPotentiallyValidManifestFile(path string, f os.FileInfo, appPath, repoRo
...
+	if bytes.Contains(out, []byte("+argocd:skip-rendering")) {
```
Comment (agaudreault) [inline reposerver/repository/repository.go]: Extract as constant and document in go code.

I would also rename to `"+argocd:skip-file-rendering"` because it might be confusing if this is in a file containing (---) with multiple objects

**Review by agaudreault — CHANGES_REQUESTED** [review]
This should also be documented somewhere in the documentation, probably in https://argo-cd.readthedocs.io/en/stable/user-guide/directory/

**Comment by CefBoud** [comment]
Thanks for the review @agaudreault . I've made the changes and added this to the documentation.

**Review by agaudreault — APPROVED** [review]
