### PR TITLE
fix: improve error message when `hydrateTo` sync path does not exist yet

### LINKED ISSUE #27325: Improve "app path does not exist" error when using `hydrateTo`
# Summary

When using Source Hydrator with `hydrateTo`, you'll get this error until you move your manifests from `env/whatever-next` to `env/whatever`. It's expected

Image

But the error message isn't very helpful:

> Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = e2e-usw2: app path does not exist

# Proposal

Add more context to the end of the error:

> Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = e2e-usw2: app path does not exist - waiting for an external process to update `env/whatever` from `env/whatever-next`

### PR DESCRIPTION
**Pull request by nitishfy**
Closes https://github.com/argoproj/argo-cd/issues/27325

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: controller/state.go [hunk 1]
```diff
@@ -332,7 +332,11 @@ func (m *appStateManager) GetRepoObjs(ctx context.Context, app *v1alpha1.Applica
 			InstallationID:                  installationID,
 		})
 		if err != nil {
-			return nil, nil, false, fmt.Errorf("failed to generate manifest for source %d of %d: %w", i+1, len(sources), err)
+			genErr := fmt.Errorf("failed to generate manifest for source %d of %d: %w", i+1, len(sources), err)
+			if app.Spec.SourceHydrator != nil && app.Spec.SourceHydrator.HydrateTo != nil && strings.Contains(err.Error(), "app path does not exist") {
```
Comment (crenshaw-dev) [inline controller/state.go]: Nice, thanks!

Is there any shot we could use a typed error with errors.As instead of a strings.Contains?

Comment (crenshaw-dev) [reply controller/state.go]: Actually I guess no there's not,  since this error comes from repo server, and the error type won't survive the grpc call. Maybe just a shared string constant?

Comment (nitishfy) [reply controller/state.go]: Done!

**Review by crenshaw-dev — APPROVED** [review]
Looks great, thank you!
