### PR TITLE
fix(ui): Improve Delete Dialog Behaviour when deleting child apps in the app-of-app pattern

### LINKED ISSUE #24901: Improve Delete Dialog Behaviour for Application/ApplicationSet
There is confusion particularly when selecting the Delete action in Details Tree or Details List views because the dialog that pops up is entitled "Delete resource".  From the "top" application List view, it clearly says it's an "Delete application". Furthermore, the Non-Cascade option is confusing.

Confirmation dialog that appears when deleting application from the Applications List view:

Image

Confirmation dialog that appears when deleting application in the Details view

Image

Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [ ] I've included steps to reproduce the bug.
- [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by aali309**
Fixes: #24901

Improve the messaging when deleting an application from the List view and the Details view.  See the parent feature for more details.

There is confusion particularly when selecting the Delete action in Details Tree or Details List views because the dialog that pops up is entitled "Delete resource".  From the "top" application List view, it clearly says it's an "Delete application". Furthermore, the Non-Cascade option is confusing.

See screenshots below

Confirmation dialog that appears when deleting application from the Applications List view:

image

Confirmation dialog that appears when deleting application in the Details view

image

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by aali309** [comment]
Deleting child app

Screenshot 2025-10-07 at 4 16 47 PM

Deleting normal app
 
Screenshot 2025-10-01 at 2 32 57 PM

Deleting resources

Screenshot 2025-10-07 at 4 17 49 PM

File: ui/src/app/applications/components/utils.tsx [hunk 1]
```diff
@@ -443,6 +448,181 @@ export const deletePopup = async (
...
+        if (isChildApp) {
+            return ctx.popup.prompt(
+                'Delete child application',
+                api => (
+                    <div>
+                        <p>
+                            Are you sure you want to delete the <strong>child Application</strong> <kbd>{resource.name}</kbd>?
+                        </p>
+                        <p>
+                            <strong>⚠️ Warning:</strong> You are about to delete an Application resource <kbd>{resource.name}</kbd> from the resource tree.
```
Comment (keithchong) [inline ui/src/app/applications/components/utils.tsx]: Perhaps instead of embedding the icon here, use:
` <i className='fa fa-warning' />`
with the appropriate color style in the scss file.

File: ui/src/app/applications/components/utils.tsx [hunk 2]
```diff
@@ -443,6 +448,181 @@ export const deletePopup = async (
...
+        // Standard dialog for regular applications
+        return ctx.popup.prompt(
+            'Delete application',
+            api => (
+                <div>
+                    <p>
+                        Are you sure you want to delete the <strong>Application</strong> <kbd>{resource.name}</kbd>?
+                    </p>
+                    <p>
+                        <strong>⚠️ Warning:</strong> You are about to delete an Application resource <kbd>{resource.name}</kbd> from the resource tree.
```
Comment (keithchong) [inline ui/src/app/applications/components/utils.tsx]: See my comment above

File: ui/src/app/applications/components/utils.tsx [hunk 3]
```diff
@@ -443,6 +448,181 @@ export const deletePopup = async (
...
+        const isChildApp = application.metadata.name !== resource.name && hasParentLabel;
+
+        // Show child app dialog with specific warning
+        if (isChildApp) {
+            return ctx.popup.prompt(
+                'Delete child application',
+                api => (
+                    <div>
+                        <p>
+                            Are you sure you want to delete the <strong>child Application</strong> <kbd>{resource.name}</kbd>?
```
Comment (keithchong) [inline ui/src/app/applications/components/utils.tsx]: Is the difference between this if block `if (isChildApp) {` and the standard dialog for regular applications after the if-block, just the title and this message where 'child' is used.  Seems like we can use one dialog with just a custom title and message and everything else can be the same?

File: ui/src/app/applications/components/utils.tsx [hunk 4]
```diff
@@ -454,17 +634,44 @@ export const deletePopup = async (
...
+    // Determine dialog title and add custom messaging
+    let dialogTitle = 'Delete resource';
+    let customMessage: React.ReactNode = null;
+
+    if (isInParentContext) {
+        dialogTitle = 'Delete resource';
+        customMessage = (
+            <div>
+                <p>
+                    <strong>ℹ️ Note:</strong> You are about to delete a resource from a parent application's resource tree.
```
Comment (keithchong) [inline ui/src/app/applications/components/utils.tsx]: Consider using the following or something similar:
`<i className='fa fa-info'/> `and update the scss with the appropriate style?

File: ui/src/app/applications/components/utils.tsx [hunk 5]
```diff
@@ -454,17 +634,44 @@ export const deletePopup = async (
...
+    const partOfLabel = application.metadata.labels?.['app.kubernetes.io/part-of'];
+    const hasParentLabel = partOfLabel && partOfLabel.trim() !== '';
+    const isInParentContext = hasParentLabel;
+
+    // Determine dialog title and add custom messaging
+    let dialogTitle = 'Delete resource';
+    let customMessage: React.ReactNode = null;
+
+    if (isInParentContext) {
+        dialogTitle = 'Delete resource';
```
Comment (keithchong) [inline ui/src/app/applications/components/utils.tsx]: The dialogTitle value here is the same as the initial value

File: ui/src/app/applications/components/utils.tsx [hunk 6]
```diff
@@ -443,6 +448,181 @@ export const deletePopup = async (
     childResources: appModels.ResourceNode[],
     appChanged?: BehaviorSubject<appModels.Application>
 ) => {
+    // Detect if this is an Application resource
+    const isApplication = isApplicationResource(resource);
+
+    // For Application resources, show different dialogs based on context
+    if (isApplication) {
+        // Check if this is a child application
+        const partOfLabel = application.metadata.labels?.['app.kubernetes.io/part-of'];
```
Comment (keithchong) [inline ui/src/app/applications/components/utils.tsx]: Looks like these three const's can be moved out of the if block because the same logic is used later on when deleting (non-Application) resources

File: ui/src/app/applications/components/utils.tsx [hunk 7]
```diff
@@ -443,6 +448,181 @@ export const deletePopup = async (
...
+        const hasParentLabel = partOfLabel && partOfLabel.trim() !== '';
```
Comment (keithchong) [inline ui/src/app/applications/components/utils.tsx]: If the annotations are used to determine whether or not it's a child application, could you consider applying this same logic to the function at approx line 68

`export async function deleteApplication(appName: string, appNamespace: string, apis: ContextApis): Promise<boolean> {`

And there, you can common up code?

**Review by keithchong — CHANGES_REQUESTED** [review]

File: ui/src/app/applications/components/utils.tsx (hunk 3 above)
Comment (aali309) [reply ui/src/app/applications/components/utils.tsx]: +1

File: ui/src/app/applications/components/utils.tsx [hunk 8]
```diff
@@ -435,6 +442,17 @@ export const deleteSourceAction = (app: appModels.Application, source: appModels
...
 
+// Detect if a resource is an Application
+const isApplicationResource = (resource: ResourceTreeNode): boolean => {
+    return resource.kind === 'Application' && resource.group === 'argoproj.io';
+};
+
+// Detect if an application is a child application
+const isChildApplication = (application: appModels.Application): boolean => {
+    const partOfLabel = application.metadata.labels?.['app.kubernetes.io/part-of'];
+    return partOfLabel && partOfLabel.trim() !== '';
```
Comment (todaywasawesome) [inline ui/src/app/applications/components/utils.tsx:482]: Rather than checking if it's a child application, why not just check if the resource type is "application" we don't need to know which app it's part of, just that the type is application right?

File: ui/src/app/applications/components/utils.tsx [hunk 9]
```diff
@@ -443,6 +461,107 @@ export const deletePopup = async (
...
+                        </strong>{' '}
+                        You are about to delete an Application resource <kbd>{resource.name}</kbd> from the resource tree.
+                    </p>
+                    <p>
+                        The deletion behavior may differ from what you expect. Even with <kbd>"Non-cascading"</kbd> selected, managed resources may still be deleted if the
+                        application has finalizers.
+                    </p>
+                    <p>
+                        For more predictable deletion behavior, consider deleting this application from the
+                        <strong> Applications list</strong> instead.
```
Comment (todaywasawesome) [inline ui/src/app/applications/components/utils.tsx]: What is the different behavior when deleting from another view? 

Maybe we should have an enhancement to make these behaviors identical.

**Review by todaywasawesome — COMMENTED** [review]
I think it's probably worthwhile to have a different dialog for child applications to reduce confusion so it's probably ok to check if the application is specifically a child application. 

Can you share more about the behavior difference between deleting applications in different views?

File: ui/src/app/applications/components/utils.tsx (hunk 9 above)
Comment (aali309) [reply ui/src/app/applications/components/utils.tsx]: **Behavior difference between deleting applications in different views:**

**Applications List View:**
- Uses services.applications.delete() API directly
- Standard Application deletion with proper propagation policies
- Non-cascading truly only deletes the Application resource, leaving managed resources orphaned

**Resource Tree View (Before the Fix):**
- Treated the Application as a generic Kubernetes resource **(main problem)**
- Used Kubernetes resource deletion mechanism
- Problem: Even with Non-cascading selected, if the Application has finalizers (like resources-finalizer.argoproj.io), the finalizers may still trigger deletion of managed resources **(another problem)**
- Result: "Non-cascading" didn't behave as expected - managed resources may still be deleted

**Resource Tree View (After the Fix):**
- Now detects Application resources and uses the same services.applications.delete() API as the Applications list
- Behaviors are now identical between both views
- The warning message is just being extra cautious and informative

The different headings serve to distinguish the context and reduce user confusion. i.e Users immediately know they're dealing with a child application vs. a standalone application
- "Delete child application": Clearly indicates this is a child application that's part of an App of Apps pattern, helping users understand they're deleting a managed application
- "Delete application": Standard heading for regular applications

Also, extra warning when Parent Context (isInParentContext = true) vs (isInParentContext = false) :

- Context: Resource is part of a parent application's resource tree (App of Apps pattern)
- Message: Explains you're deleting from a parent application's resource tree

So the different messages help users understand whether they're deleting resources in a normal context or within an App of Apps pattern, which may have different implications and behaviours.

Comment (jannfis) [reply ui/src/app/applications/components/utils.tsx]: Hm, if you changed the deletion procedure for deleting a resource from the tree view to the one that is used for Applications specifically, then now the new dialogue is misleading I guess - because it will behave exactly the same?

Or do I misunderstand something here?

Comment (aali309) [reply ui/src/app/applications/components/utils.tsx]: Yes, you are right, the delete behaviour is now identical, the dialogue is being extra informative!

Comment (aali309) [reply ui/src/app/applications/components/utils.tsx]: I think it makes more sense to make the delete app behaviour consistent. This approach ensures complete consistency across all deletion contexts. ApplicationSets create child applications that are sometimes visible on the Applications List page and get the standard deletion dialogue when deleting it. These changes (see screenshot below) now extend that same familiar deletion experience to the Resource Tree context as well. Users get identical deletion behaviour whether they access applications from the Applications List or Resource Tree, with just an additional contextual note to clarify they're deleting from the resource tree view (at least for now and can be removed later). This eliminates confusion and provides a predictable user experience across all access points.


Screenshot 2025-10-09 at 5 34 59 PM

**Comment by aali309** [comment]
Discussed in the Argo CD/Rollouts Contributor Meeting on - Oct 16, 2025. No objections raised, got approved to proceed.

[See recording](https://youtu.be/ctnpKqAROLc)

**Comment by keithchong** [comment]
@jannfis , should we cherry pick this fix back to 3.2 (an RC) ?

**Comment by aali309** [comment]
@alexmt , Please review this for me. Thnx.

**Comment by keithchong** [comment]
Thanks again @aali309  for providing this change. @alexmt , I heard on last week's call you ('we') wanted to review this.  Is the latest changes ok to you?

**Review by keithchong — APPROVED** [review]
LGTM
