### PR TITLE
fix: Use t.Fatal instead of os.Exit in tests (part 2) (#21003)

### LINKED ISSUE #21003: Sometimes e2e tests are marked as wrongfully passed with early termination and some failures
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

There were some test failures and not all tests were run, see https://github.com/argoproj/argo-cd/actions/runs/12089478179/job/33714912896?pr=20998.

**To Reproduce**

It happens sporadically. I don't know how to trigger it.

**Expected behavior**

Test run is marked as failure and/or run all non-skipped tests.

**Screenshots**

Screenshot 2024-11-29 at 11 22 16 AM
Screenshot 2024-11-29 at 11 22 26 AM

**Version**
It reproduces from master.

**Logs**

### PR DESCRIPTION
**Pull request by andrii-korotkov-verkada**
Closes #21003

This one focuses on checking functions that return just an error and no other value. Same idea - use t.Fatal under the hood to not exit a whole test suite of failure. This time using handler is not required, but decided to do so for consistency.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: util/errors/errors.go [hunk 1]
```diff
@@ -28,6 +21,14 @@ func NewHandler(t *testing.T) *Handler {
...
 }
 
+// CheckForErr fails the test if there is an error.
+func (h *Handler) CheckForErr(err error) {
+	h.t.Helper()
+	if err != nil {
+		h.t.Fatal(err)
+	}
+}
+
```
Comment (crenshaw-dev) [inline util/errors/errors.go:31]: Since this and CheckError don't return any values, wouldn't it be preferable to just use `require.NoError`?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: util/errors/errors.go (hunk 1 above)
Comment (andrii-korotkov-verkada) [reply util/errors/errors.go:31]: require.NoError continues test execution, while the errors handled here are usually non-recoverable for a given test, e.g. some key setup part failed.

Comment (andrii-korotkov-verkada) [reply util/errors/errors.go:31]: https://pkg.go.dev/github.com/stretchr/testify/require#NoError

Comment (crenshaw-dev) [reply util/errors/errors.go:31]: I'm pretty sure `require.NoError` immediately stops test execution for the given test:

```
func NoError(t TestingT, err error, msgAndArgs ...interface{}) {
	if h, ok := t.(tHelper); ok {
		h.Helper()
	}
	if assert.NoError(t, err, msgAndArgs...) {
		return
	}
	t.FailNow()
}
```

Comment (andrii-korotkov-verkada) [reply util/errors/errors.go:31]: Hm, their example docs are incorrect then
```
  actualObj, err := SomeFunction()
  if require.NoError(t, err) {
	   require.Equal(t, expectedObj, actualObj)
  }
```

Comment (andrii-korotkov-verkada) [reply util/errors/errors.go:31]: Ah, I misread how this is supposed to work, let me update to require.NoError, probably would give better error messages

Comment (andrii-korotkov-verkada) [reply util/errors/errors.go]: Updated the PR.

File: util/errors/errors.go [hunk 2]
```diff
@@ -28,14 +22,25 @@ func NewHandler(t *testing.T) *Handler {
 	return &Handler{t: t}
 }
 
+// CheckForErr fails the test if there is an error.
+func (h *Handler) CheckForErr(err error) {
+	h.t.Helper()
+	require.NoError(h.t, err)
+}
+
```
Comment (crenshaw-dev) [inline util/errors/errors.go:30]: Instead of centralizing this as a trivial function, can we just directly call `require.NoError` wherever `CheckForErr` is currently called?

Comment (andrii-korotkov-verkada) [reply util/errors/errors.go:30]: Actually yeah, not that t is passed to nearly all places needed, we can do that. I'll update the PR

File: test/e2e/fixture/account/consequences.go [hunk 3]
```diff
@@ -47,12 +48,13 @@ func (c *Consequences) get() (*account.Account, error) {
 			return acc, nil
 		}
 	}
-	return nil, errors.New("account not found")
+	return nil, stderrors.New("account not found")
```
Comment (crenshaw-dev) [inline test/e2e/fixture/account/consequences.go:51]: Can be switched back to just `errors` now I believe

**Review by crenshaw-dev — APPROVED** [review]
Requested one small change. Otherwise lgtm. Thanks!
