### PR TITLE
fix: Fix false positive in plugin application discovery

### LINKED ISSUE #20195: [v2.13.0-rc2] ArgoCD is not working when plugin without discovery is configured
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Many (if not all) applications registered in ArgoCD is incorrectly recognized as plugin application when a [plugin](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/) without discovery  functionality is configured.
The bug seems introduced by this PR https://github.com/argoproj/argo-cd/pull/18053 . Specifically, [this line of code](https://github.com/argoproj/argo-cd/blob/48551b3746510123285b3ce4aae324b41fd37652/util/app/discovery/discovery.go#L177) in cmpSupports function.

**To Reproduce**
1. Install ArgoCD version v2.13.0-rc1 / rc-2
2. Create kustomize application, for example
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: git@github.com:pradithya/argocd-hack.git
    targetRevision: main
    path: bootstrap
    kustomize: {}
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
```
3. Create CM plugin without discovery functionality configured
4. Check that the application above is somehow recognized as plugin app instead of kustomize app

Full repository to reproduce https://github.com/pradithya/argocd-hack/commit/4ab374e180ffc94d19270652ef70906610fc2927 

**Expected behavior**

application should be rendered properly and recognized as kustomize application instead of plugin application.

**Screenshots**
Screenshot 2024-10-02 at 5 41 14 PM

Screenshot 2024-10-02 at 5 38 28 PM

**Version**

```shell

2024/10/02 17:32:56 maxprocs: Leaving GOMAXPROCS=10: CPU quota undefined
argocd: v2.13.0-rc1+74a367d
  BuildDate: 2024-09-16T08:51:02Z
  GitCommit: 74a367d10e7110209610ba3ec225539ebe5f7522
  GitTreeState: clean
  GoVersion: go1.22.7
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.13.0-rc2+0f083c9
  BuildDate: 2024-09-20T11:37:53Z
  GitCommit: 0f083c9e58638fc292cf064e294a1aa53caa5630
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0

```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by pradithya**
Fix false positive in plugin application discovery when plugin doesn't configure discovery configuration by only returning connection for named plugin.

Close #20195

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by nitishfy — APPROVED** [review]
LGTM!

File: util/app/discovery/discovery.go [hunk 1]
```diff
@@ -174,7 +174,7 @@ func cmpSupports(ctx context.Context, pluginSockFilePath, appPath, repoPath, fil
 	}
 
 	// if discovery is not configured, return the client without further checks
-	if !cfg.IsDiscoveryConfigured {
+	if !cfg.IsDiscoveryConfigured && namedPlugin {
```
[the remark this answers is not in the document]
Comment (todaywasawesome) [reply util/app/discovery/discovery.go:177]: Because we want to return the plugin if it's named directly.

**Review by todaywasawesome — APPROVED** [review]
Looks good.

File: util/app/discovery/discovery.go [hunk 2]
```diff
@@ -174,7 +174,7 @@ func cmpSupports(ctx context.Context, pluginSockFilePath, appPath, repoPath, fil
...
 		return conn, cmpClient, true
 	}
```
Comment (crenshaw-dev) [inline util/app/discovery/discovery.go:179]:
```suggestion
	if !cfg.IsDiscoveryConfigured {
		// If discovery isn't configured but the plugin is named, then the plugin supports the repo.
		if namedPlugin {
			return conn, cmpClient, true
		}
		return nil, nil, false
	}
```

Your change would cause us to call `matchRepositoryCMP` in the case where discovery isn't configured and the plugin isn't named. But it's nonsensical to call `matchRepositoryCMP` if discovery isn't configured. 

This changes makes sure we never unnecessarily call `matchRepositoryCMP`. And it also ensures that we return `true` in the case that discovery isn't configured but the plugin is named.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: util/app/discovery/discovery.go (hunk 2 above)
Comment (pradithya) [reply util/app/discovery/discovery.go]: Make sense! I pushed the suggestion.

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@pradithya if you'd like the change backported further than 2.13, you'll need to open PRs against those release branches.
