### PR TITLE
Issue 1476 - Avoid validating repository in application controller

### LINKED ISSUE #1476: ArgoCd becomes unresponsive in Failed to watch {...} Start watch {...} loop
**Describe the bug**
We are seeing an issue where there is a new commit pushed to master, the argo UI shows a spinner in the repo area. But nothing ever happens. Looking at the logs on application-controller we are seeing a lots of `Failed to watch {...}` and then a `Start watch {...}` over and over. If we restart the pod, things pick back up and work. I've included logs which show at the top the successful behavior where we see `Reconciliation completed` a few times and then it enters a state where we never see that message again and all we get are constant Failed to watch..., Start watch...

**To Reproduce**
Unclear exact steps yet.

**Expected behavior**
Argo remains responsive and syncs our application

**Screenshots**
N/A

**Additional context**

```
time="2019-04-17T16:01:19Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd-cluster-application
time="2019-04-17T16:01:19Z" level=info msg="Update successful" application=argocd-cluster-application
time="2019-04-17T16:01:19Z" level=info msg="Reconciliation completed" application=argocd-cluster-application full=true time_ms=17343.614956999998
time="2019-04-17T16:01:19Z" level=info msg="Refreshing app status (controller refresh requested)" application=argocd-cluster-application
time="2019-04-17T16:01:25Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=argocd-cluster-application
time="2019-04-17T16:01:29Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd-cluster-application
time="2019-04-17T16:01:29Z" level=info msg="Update successful" application=argocd-cluster-application
time="2019-04-17T16:01:29Z" level=info msg="Reconciliation completed" application=argocd-cluster-application full=true time_ms=9807.459459
time="2019-04-17T16:01:29Z" level=info msg="Refreshing app status (controller refresh requested)" application=argocd-cluster-application
time="2019-04-17T16:01:29Z" level=warning msg="Failed to watch {certmanager.k8s.io Order} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Order} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:01:30Z" level=warning msg="Failed to watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:01:30Z" level=info msg="Start watch {certmanager.k8s.io Order} on https://kubernetes.default.svc"
time="2019-04-17T16:01:31Z" level=info msg="Start watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc"
time="2019-04-17T16:01:32Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=argocd-cluster-application
time="2019-04-17T16:01:36Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd-cluster-application
time="2019-04-17T16:01:36Z" level=info msg="Update successful" application=argocd-cluster-application
time="2019-04-17T16:01:36Z" level=info msg="Reconciliation completed" application=argocd-cluster-application full=true time_ms=6891.188064
time="2019-04-17T16:01:36Z" level=info msg="Refreshing app status (controller refresh requested)" application=argocd-cluster-application
time="2019-04-17T16:01:39Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=argocd-cluster-application
time="2019-04-17T16:01:42Z" level=warning msg="Failed to watch {argoproj.io AppProject} on https://kubernetes.default.svc: Watch {argoproj.io AppProject} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:01:43Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd-cluster-application
time="2019-04-17T16:01:43Z" level=info msg="Update successful" application=argocd-cluster-application
time="2019-04-17T16:01:43Z" level=info msg="Reconciliation completed" application=argocd-cluster-application full=true time_ms=6461.022227
time="2019-04-17T16:01:43Z" level=info msg="Refreshing app status (controller refresh requested)" application=argocd-cluster-application
time="2019-04-17T16:01:43Z" level=info msg="Start watch {argoproj.io AppProject} on https://kubernetes.default.svc"
time="2019-04-17T16:02:00Z" level=warning msg="Failed to watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc: Watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:01Z" level=info msg="Start watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc"
time="2019-04-17T16:02:02Z" level=warning msg="Failed to watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:03Z" level=info msg="Start watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc"
time="2019-04-17T16:02:16Z" level=warning msg="Failed to watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc: Watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:17Z" level=info msg="Start watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc"
time="2019-04-17T16:02:20Z" level=warning msg="Failed to watch {argoproj.io Application} on https://kubernetes.default.svc: Watch {argoproj.io Application} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:21Z" level=info msg="Start watch {argoproj.io Application} on https://kubernetes.default.svc"
time="2019-04-17T16:02:22Z" level=warning msg="Failed to watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:23Z" level=info msg="Start watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc"
time="2019-04-17T16:02:26Z" level=warning msg="Failed to watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:27Z" level=info msg="Start watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc"
time="2019-04-17T16:02:37Z" level=warning msg="Failed to watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:38Z" level=info msg="Start watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc"
time="2019-04-17T16:02:40Z" level=warning msg="Failed to watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:41Z" level=info msg="Start watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc"
time="2019-04-17T16:02:45Z" level=warning msg="Failed to watch {argoproj.io AppProject} on https://kubernetes.default.svc: Watch {argoproj.io AppProject} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:46Z" level=info msg="Start watch {argoproj.io AppProject} on https://kubernetes.default.svc"
time="2019-04-17T16:02:50Z" level=warning msg="Failed to watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:02:51Z" level=info msg="Start watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc"
time="2019-04-17T16:03:08Z" level=warning msg="Failed to watch {certmanager.k8s.io Order} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Order} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:03:09Z" level=info msg="Start watch {certmanager.k8s.io Order} on https://kubernetes.default.svc"
time="2019-04-17T16:03:12Z" level=warning msg="Failed to watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:03:13Z" level=info msg="Start watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc"
time="2019-04-17T16:03:13Z" level=warning msg="Failed to watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc: Watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:03:14Z" level=info msg="Start watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc"
time="2019-04-17T16:03:14Z" level=warning msg="Failed to watch {bitnami.com SealedSecret} on https://kubernetes.default.svc: Watch {bitnami.com SealedSecret} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:03:15Z" level=info msg="Start watch {bitnami.com SealedSecret} on https://kubernetes.default.svc"
time="2019-04-17T16:03:30Z" level=info msg="Alloc=17278 TotalAlloc=457392143 Sys=76158 NumGC=42124 Goroutines=231"
time="2019-04-17T16:03:33Z" level=warning msg="Failed to watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:03:34Z" level=info msg="Start watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc"
time="2019-04-17T16:04:00Z" level=warning msg="Failed to watch {storage.k8s.io StorageClass} on https://kubernetes.default.svc: Watch {storage.k8s.io StorageClass} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:01Z" level=info msg="Start watch {storage.k8s.io StorageClass} on https://kubernetes.default.svc"
time="2019-04-17T16:04:09Z" level=warning msg="Failed to watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:10Z" level=warning msg="Failed to watch {certmanager.k8s.io Order} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Order} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:10Z" level=info msg="Start watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc"
time="2019-04-17T16:04:11Z" level=info msg="Start watch {certmanager.k8s.io Order} on https://kubernetes.default.svc"
time="2019-04-17T16:04:12Z" level=warning msg="Failed to watch {argoproj.io Application} on https://kubernetes.default.svc: Watch {argoproj.io Application} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:13Z" level=warning msg="Failed to watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:13Z" level=info msg="Start watch {argoproj.io Application} on https://kubernetes.default.svc"
time="2019-04-17T16:04:14Z" level=info msg="Start watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc"
time="2019-04-17T16:04:17Z" level=warning msg="Failed to watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc: Watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:18Z" level=info msg="Start watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc"
time="2019-04-17T16:04:19Z" level=warning msg="Failed to watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:20Z" level=info msg="Start watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc"
time="2019-04-17T16:04:23Z" level=warning msg="Failed to watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:24Z" level=info msg="Start watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc"
time="2019-04-17T16:04:42Z" level=warning msg="Failed to watch {bitnami.com SealedSecret} on https://kubernetes.default.svc: Watch {bitnami.com SealedSecret} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:43Z" level=info msg="Start watch {bitnami.com SealedSecret} on https://kubernetes.default.svc"
time="2019-04-17T16:04:44Z" level=warning msg="Failed to watch {argoproj.io AppProject} on https://kubernetes.default.svc: Watch {argoproj.io AppProject} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:45Z" level=warning msg="Failed to watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:04:45Z" level=info msg="Start watch {argoproj.io AppProject} on https://kubernetes.default.svc"
time="2019-04-17T16:04:46Z" level=info msg="Start watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc"
time="2019-04-17T16:04:59Z" level=warning msg="Failed to watch { Service} on https://kubernetes.default.svc: Watch { Service} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:05:00Z" level=warning msg="Failed to watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc: Watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:05:00Z" level=info msg="Start watch { Service} on https://kubernetes.default.svc"
time="2019-04-17T16:05:01Z" level=info msg="Start watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc"
time="2019-04-17T16:05:06Z" level=warning msg="Failed to watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:05:07Z" level=info msg="Start watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc"
time="2019-04-17T16:05:20Z" level=warning msg="Failed to watch {argoproj.io Application} on https://kubernetes.default.svc: Watch {argoproj.io Application} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:05:21Z" level=info msg="Start watch {argoproj.io Application} on https://kubernetes.default.svc"
time="2019-04-17T16:05:24Z" level=warning msg="Failed to watch {certmanager.k8s.io Order} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Order} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:05:25Z" level=info msg="Start watch {certmanager.k8s.io Order} on https://kubernetes.default.svc"
time="2019-04-17T16:05:48Z" level=warning msg="Failed to watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:05:49Z" level=info msg="Start watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc"
time="2019-04-17T16:05:51Z" level=warning msg="Failed to watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:05:52Z" level=info msg="Start watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc"
time="2019-04-17T16:05:52Z" level=warning msg="Failed to watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:05:53Z" level=info msg="Start watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc"
time="2019-04-17T16:06:04Z" level=warning msg="Failed to watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc: Watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:06:05Z" level=info msg="Start watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc"
time="2019-04-17T16:06:10Z" level=warning msg="Failed to watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:06:11Z" level=warning msg="Failed to watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:06:11Z" level=info msg="Start watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc"
time="2019-04-17T16:06:12Z" level=info msg="Start watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc"
time="2019-04-17T16:06:17Z" level=warning msg="Failed to watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:06:18Z" level=info msg="Start watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc"
time="2019-04-17T16:06:32Z" level=warning msg="Failed to watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc: Watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:06:33Z" level=info msg="Start watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc"
time="2019-04-17T16:06:35Z" level=warning msg="Failed to watch {bitnami.com SealedSecret} on https://kubernetes.default.svc: Watch {bitnami.com SealedSecret} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:06:36Z" level=info msg="Start watch {bitnami.com SealedSecret} on https://kubernetes.default.svc"
time="2019-04-17T16:06:40Z" level=warning msg="Failed to watch {argoproj.io AppProject} on https://kubernetes.default.svc: Watch {argoproj.io AppProject} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:06:41Z" level=info msg="Start watch {argoproj.io AppProject} on https://kubernetes.default.svc"
time="2019-04-17T16:06:52Z" level=warning msg="Failed to watch { ServiceAccount} on https://kubernetes.default.svc: Watch { ServiceAccount} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:06:53Z" level=info msg="Start watch { ServiceAccount} on https://kubernetes.default.svc"
time="2019-04-17T16:06:58Z" level=warning msg="Failed to watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:06:59Z" level=info msg="Start watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc"
time="2019-04-17T16:06:59Z" level=warning msg="Failed to watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:00Z" level=info msg="Start watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc"
time="2019-04-17T16:07:03Z" level=warning msg="Failed to watch {certmanager.k8s.io Order} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Order} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:04Z" level=info msg="Start watch {certmanager.k8s.io Order} on https://kubernetes.default.svc"
time="2019-04-17T16:07:12Z" level=warning msg="Failed to watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:13Z" level=info msg="Start watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc"
time="2019-04-17T16:07:19Z" level=warning msg="Failed to watch {argoproj.io Application} on https://kubernetes.default.svc: Watch {argoproj.io Application} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:20Z" level=info msg="Start watch {argoproj.io Application} on https://kubernetes.default.svc"
time="2019-04-17T16:07:22Z" level=warning msg="Failed to watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc: Watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:23Z" level=info msg="Start watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc"
time="2019-04-17T16:07:27Z" level=warning msg="Failed to watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:28Z" level=info msg="Start watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc"
time="2019-04-17T16:07:39Z" level=warning msg="Failed to watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:40Z" level=info msg="Start watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc"
time="2019-04-17T16:07:41Z" level=warning msg="Failed to watch {bitnami.com SealedSecret} on https://kubernetes.default.svc: Watch {bitnami.com SealedSecret} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:42Z" level=info msg="Start watch {bitnami.com SealedSecret} on https://kubernetes.default.svc"
time="2019-04-17T16:07:46Z" level=warning msg="Failed to watch {argoproj.io AppProject} on https://kubernetes.default.svc: Watch {argoproj.io AppProject} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:47Z" level=warning msg="Failed to watch {policy PodSecurityPolicy} on https://kubernetes.default.svc: Watch {policy PodSecurityPolicy} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:47Z" level=info msg="Start watch {argoproj.io AppProject} on https://kubernetes.default.svc"
time="2019-04-17T16:07:48Z" level=info msg="Start watch {policy PodSecurityPolicy} on https://kubernetes.default.svc"
time="2019-04-17T16:07:51Z" level=warning msg="Failed to watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:07:52Z" level=info msg="Start watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc"
time="2019-04-17T16:08:15Z" level=warning msg="Failed to watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:08:16Z" level=info msg="Start watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc"
time="2019-04-17T16:08:26Z" level=warning msg="Failed to watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc: Watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:08:27Z" level=info msg="Start watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc"
time="2019-04-17T16:08:34Z" level=warning msg="Failed to watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:08:35Z" level=info msg="Start watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc"
time="2019-04-17T16:08:44Z" level=warning msg="Failed to watch {argoproj.io Application} on https://kubernetes.default.svc: Watch {argoproj.io Application} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:08:45Z" level=info msg="Start watch {argoproj.io Application} on https://kubernetes.default.svc"
time="2019-04-17T16:08:49Z" level=warning msg="Failed to watch {argoproj.io AppProject} on https://kubernetes.default.svc: Watch {argoproj.io AppProject} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:08:50Z" level=info msg="Start watch {argoproj.io AppProject} on https://kubernetes.default.svc"
time="2019-04-17T16:08:50Z" level=warning msg="Failed to watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:08:51Z" level=info msg="Start watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc"
time="2019-04-17T16:08:57Z" level=warning msg="Failed to watch {certmanager.k8s.io Order} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Order} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:08:57Z" level=warning msg="Failed to watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:08:57Z" level=warning msg="Failed to watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:08:58Z" level=info msg="Start watch {certmanager.k8s.io Order} on https://kubernetes.default.svc"
time="2019-04-17T16:08:58Z" level=info msg="Start watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc"
time="2019-04-17T16:08:58Z" level=info msg="Start watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc"
time="2019-04-17T16:09:14Z" level=warning msg="Failed to watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc: Watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:09:15Z" level=info msg="Start watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc"
time="2019-04-17T16:09:21Z" level=warning msg="Failed to watch {bitnami.com SealedSecret} on https://kubernetes.default.svc: Watch {bitnami.com SealedSecret} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:09:22Z" level=info msg="Start watch {bitnami.com SealedSecret} on https://kubernetes.default.svc"
time="2019-04-17T16:09:47Z" level=warning msg="Failed to watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:09:47Z" level=warning msg="Failed to watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc: Watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:09:48Z" level=info msg="Start watch {certmanager.k8s.io Certificate} on https://kubernetes.default.svc"
time="2019-04-17T16:09:48Z" level=info msg="Start watch {monitoring.coreos.com ServiceMonitor} on https://kubernetes.default.svc"
time="2019-04-17T16:09:54Z" level=warning msg="Failed to watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:09:54Z" level=warning msg="Failed to watch {argoproj.io AppProject} on https://kubernetes.default.svc: Watch {argoproj.io AppProject} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:09:55Z" level=info msg="Start watch {monitoring.coreos.com Prometheus} on https://kubernetes.default.svc"
time="2019-04-17T16:09:55Z" level=info msg="Start watch {argoproj.io AppProject} on https://kubernetes.default.svc"
time="2019-04-17T16:10:02Z" level=warning msg="Failed to watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc: Watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:10:03Z" level=info msg="Start watch {monitoring.coreos.com Alertmanager} on https://kubernetes.default.svc"
time="2019-04-17T16:10:07Z" level=warning msg="Failed to watch {admissionregistration.k8s.io MutatingWebhookConfiguration} on https://kubernetes.default.svc: Watch {admissionregistration.k8s.io MutatingWebhookConfiguration} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:10:08Z" level=warning msg="Failed to watch {certmanager.k8s.io Order} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Order} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:10:08Z" level=info msg="Start watch {admissionregistration.k8s.io MutatingWebhookConfiguration} on https://kubernetes.default.svc"
time="2019-04-17T16:10:09Z" level=info msg="Start watch {certmanager.k8s.io Order} on https://kubernetes.default.svc"
time="2019-04-17T16:10:21Z" level=warning msg="Failed to watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:10:22Z" level=info msg="Start watch {certmanager.k8s.io Challenge} on https://kubernetes.default.svc"
time="2019-04-17T16:10:22Z" level=warning msg="Failed to watch {bitnami.com SealedSecret} on https://kubernetes.default.svc: Watch {bitnami.com SealedSecret} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:10:23Z" level=info msg="Start watch {bitnami.com SealedSecret} on https://kubernetes.default.svc"
time="2019-04-17T16:10:29Z" level=warning msg="Failed to watch {argoproj.io Application} on https://kubernetes.default.svc: Watch {argoproj.io Application} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:10:30Z" level=info msg="Start watch {argoproj.io Application} on https://kubernetes.default.svc"
time="2019-04-17T16:10:33Z" level=warning msg="Failed to watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:10:34Z" level=info msg="Start watch {certmanager.k8s.io Issuer} on https://kubernetes.default.svc"
time="2019-04-17T16:10:43Z" level=warning msg="Failed to watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc: Watch {certmanager.k8s.io ClusterIssuer} on https://kubernetes.default.svc has closed, retrying in 1s"
time="2019-04-17T16:10:43Z" level=warning msg="Failed to watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc: Watch {monitoring.coreos.com PrometheusRule} on https://kubernetes.default.svc has closed, retrying in 1s"
```

### PR DESCRIPTION
**Pull request by alexmt**
PR removes repository validation during app reconciliation. It is safe to skip repository validation in the controller because it is executed right before manifests generation which includes all the checks.

With that change we can close https://github.com/argoproj/argo-cd/issues/1476 and 2x reduce number of `git ls-remote`

### CODE REVIEW

File: test/e2e/app_management_test.go [hunk 1]
```diff
@@ -529,3 +529,64 @@ func TestSyncResourceByLabel(t *testing.T) {
...
+	proj.Spec.Destinations = []v1alpha1.ApplicationDestination{{Server: "*", Namespace: "*"}}
+	proj.Spec.SourceRepos = []string{"*"}
+	proj, err = fixture.AppClientset.ArgoprojV1alpha1().AppProjects(fixture.ArgoCDNamespace).Update(proj)
+	assert.NoError(t, err)
+
+	// make sure controller report permissions issues in conditions
+	_, err = fixture.RunCli("app", "create", "test-app", "--repo", fixture.RepoURL(),
+		"--path", guestbookPath, "--project", "test", "--dest-server", common.KubernetesInternalAPIServerAddr, "--dest-namespace", fixture.DeploymentNamespace)
+	assert.NoError(t, err)
+	if err == nil {
```
Comment (alexec) [inline test/e2e/app_management_test.go]: why guard this?

File: test/e2e/app_management_test.go [hunk 2]
```diff
@@ -529,3 +529,64 @@ func TestSyncResourceByLabel(t *testing.T) {
...
+	sourceErrorExist := false
+	for i := range app.Status.Conditions {
+		if strings.Contains(app.Status.Conditions[i].Message, destinationError) {
+			destinationErrorExist = true
+		}
+		if strings.Contains(app.Status.Conditions[i].Message, sourceError) {
+			sourceErrorExist = true
+		}
+	}
+	assert.True(t, destinationErrorExist)
```
Comment (alexec) [inline test/e2e/app_management_test.go]: 👍

File: util/argo/argo.go [hunk 3]
```diff
@@ -127,36 +128,19 @@ func WaitForRefresh(ctx context.Context, appIf v1alpha1.ApplicationInterface, na
...
-	conditions := make([]argoappv1.ApplicationCondition, 0)
-	if spec.Source.RepoURL == "" || spec.Source.Path == "" {
-		conditions = append(conditions, argoappv1.ApplicationCondition{
-			Type:    argoappv1.ApplicationConditionInvalidSpecError,
-			Message: "spec.source.repoURL and spec.source.path are required",
-		})
-		return conditions, "", nil
-	}
-
+func ValidateRepo(ctx context.Context, spec *argoappv1.ApplicationSpec, repoClientset reposerver.Clientset, db db.ArgoDB) (argoappv1.ApplicationSourceType, error) {
```
Comment (alexec) [inline util/argo/argo.go]: Covered by e2e test?

File: util/argo/argo.go [hunk 4]
```diff
@@ -166,70 +150,71 @@ func GetSpecErrors(
...
+					return "", err
 				}
 			}
 		}
 	}
+	return appSourceType, nil
+}
+
+// ValidatePermissions ensures that the referenced cluster has been added to Argo CD and the app source repo and destination namespace/cluster are permitted in app project
+func ValidatePermissions(ctx context.Context, spec *argoappv1.ApplicationSpec, proj *argoappv1.AppProject, db db.ArgoDB) ([]argoappv1.ApplicationCondition, error) {
```
Comment (alexec) [inline util/argo/argo.go]: covered by e2e test?

File: util/argo/argo.go (hunk 3 above)
Comment (alexec) [reply util/argo/argo.go]: One change here is that we can only return one error. Is that ok?

**Review by alexec — APPROVED** [review]
I've added some comments.

File: util/argo/argo.go (hunk 3 above)
Comment (alexmt) [reply util/argo/argo.go]: Good point. We should collect all the errors instead of fail fast. Fixing it
