### PR TITLE
fix: AAD Domain Hint Improvement (fixes #18066) 

### LINKED ISSUE #18066: Add domain_hint option in oidc configuration
# Summary
We are using Azure Active Directory (AAD) for authentication and authorization.
We have integrated Argo CD with Azure AD using oidc config (sample config below without values):
oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/
    clientID: 
     clientSecret: 
    allowedAudiences:
    - 
    requestedScopes:
    - openid

As we have multiple domains, each time when user tries to log in, user needs to select which domain and then the login process continues. This creates some confusion to users on which account to select for which application.

# Motivation
As we have multiple domains, each time when user tries to log in to ArgoCD, user needs to select which domain and then the login process continues. This creates some confusion to users on which account to select for which application.
The estimated impact of this issue is a loss of approximately 15 seconds each time a user opens different applications, which happens 15 to 20 times per day depending on profile.
We would like to improve this user experience. 

# Proposal
To solve this issue, we have found an option from Azure - if we use domain_hint with the authentication request, login process becomes seamless as the right account is automatically picked.
We request to support this domain_hint option from Argo CD.

oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/
    domain_hint: abc.<company>.net
    requestedScopes:
    - openid

References:
This is already supported in dex - https://github.com/dexidp/dex/pull/2586

Documentation from Azure - https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#send-the-sign-in-request 

domain_hint -	The realm of the user in a federated directory. This skips the email-based discovery process that the user goes through on the sign-in page, for a slightly more streamlined user experience. For tenants that are federated through an on-premises directory like AD FS, this often results in a seamless sign-in because of the existing login session.

### PR DESCRIPTION
**Pull request by jhansireddy01**
This change allows domain_hint parameter to be parsed if its configured in the oidc
Closes https://github.com/argoproj/argo-cd/issues/18066
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by nitishfy — COMMENTED** [review]
Based on feedback received in contributor meeting, please add unit tests and relevant docs (if required).

**Comment by jhansireddy01** [comment]
> Based on feedback received in contributor meeting, please add unit tests and relevant docs (if required).

Hello @nitishfy i have added the required changes can you please check now ?

**Review by nitishfy — COMMENTED** [review]
Please fix the failing tests.

File: util/oidc/oidc.go [hunk 1]
```diff
@@ -87,7 +87,8 @@ type ClientApp struct {
 	// clientCache represent a cache of sso artifact
 	clientCache cache.CacheClient
 	// properties for azure workload identity.
-	azure azureApp
+	domainHint string
+	azure      azureApp
```
Comment (nitishfy) [inline util/oidc/oidc.go:106]: please document these fields.

File: util/oidc/oidc.go [hunk 2]
```diff
@@ -187,7 +188,14 @@ func NewClientApp(settings *settings.ArgoCDSettings, dexServerAddr string, dexTL
...
 		clientCache:              cacheClient,
 		azure:                    azureApp{mtx: &sync.RWMutex{}},
-		refreshTokenThreshold:    settings.OIDCRefreshTokenThreshold,
+		domainHint: func() string {
+			oidcConfig := settings.OIDCConfig()
+			if oidcConfig != nil {
+				return oidcConfig.DomainHint
+			}
+			return ""
+		}(),
```
Comment (nitishfy) [inline util/oidc/oidc.go]: I'm not trying to be pricky here but I'd not prefer having an inline function here since it's not testable easily. I'd prefer you create a separate helper function and add unit tests for it. You can get the `domainHint` value before initializing the variable which is a neat and clean approach.

File: util/oidc/oidc.go [hunk 3]
```diff
@@ -397,6 +405,11 @@ func (a *ClientApp) HandleLogin(w http.ResponseWriter, r *http.Request) {
 		http.Error(w, "Invalid redirect URL: the protocol and host (including port) must match and the path must be within allowed URLs if provided", http.StatusBadRequest)
 		return
 	}
+	if a.domainHint != "" {
+		opts = append(opts, oauth2.SetAuthURLParam("domain_hint", a.domainHint))
+	}
+	// debug log to confirm domainHint at runtime
+	log.Infof("OIDC HandleLogin: domainHint=%q", a.domainHint)
```
Comment (nitishfy) [inline util/oidc/oidc.go]: These are info logs and not debug logs.

**Review by nitishfy — CHANGES_REQUESTED** [review]
Left a few comments, PTAL!

File: util/oidc/oidc.go (hunk 2 above)
Comment (nitishfy) [reply util/oidc/oidc.go]: Even though the function is doing a pretty simple job, i'd still prefer adding unit tests for it.

Comment (nitishfy) [reply util/oidc/oidc.go]: Under what conditions will `oidcConfig` be a nil value?

File: util/oidc/oidc_test.go [hunk 4]
```diff
@@ -49,6 +49,43 @@ func setupAzureIdentity(t *testing.T) {
...
+
+	t.Run("Returns empty string when OIDC config is nil", func(t *testing.T) {
+		settings := &settings.ArgoCDSettings{
+			OIDCConfigRAW: "",
+		}
+		domainHint := getDomainHint(settings)
+		assert.Empty(t, domainHint)
+	})
+}
+
```
Comment (nitishfy) [inline util/oidc/oidc_test.go:110]: We need two more tests:

1. Test that ensure that an empty string is returned when the yaml is malformed.
2. Test that ensures whitespaces are trimmed for domainHint (optional but let's not skip it).

**Review by nitishfy — CHANGES_REQUESTED** [review]
Please add two tests i specified in the [comment](https://github.com/argoproj/argo-cd/pull/24639#discussion_r2813061562) and we're good to go.

**Review by nitishfy — APPROVED** [review]

**Review by reggie-k — COMMENTED** [review]
Thanks for the PR! 
Did you test it with AAD?

**Comment by jhansireddy01** [comment]
> Thanks for the PR! Did you test it with AAD?
Hello @reggie-k 
I have tested with AAD and it seems to be working as expected

**Comment by reggie-k** [comment]
Thanks @jhansireddy01 ! Can you add docs about this option here: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/?

**Comment by jhansireddy01** [comment]
> Thanks @jhansireddy01 ! Can you add docs about this option here: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/?

Added it can you please check  now?

**Review by reggie-k — COMMENTED** [review]
Thanks for adding the docs! Probably the last thing in order to merge is fixing the linting issues.

**Comment by jhansireddy01** [comment]
> Thanks for adding the docs! Probably the last thing in order to merge is fixing the linting issues.
Fixed the lint issues, can you please check now ?

**Review by reggie-k — APPROVED** [review]
