### PR TITLE
fix: identify pluginName with quotes (#12040)

### LINKED ISSUE #12040: `config management plugin not supported` error needs better quoting
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Error message includes a bunch of free text w/ no particular hint about which part of the free text is actually the plugin.

**To Reproduce**

Create an argocd application that references a cmp that is not currently available

**Expected behavior**

The error should include quotes around the plugin name.

**Screenshots**

**Version**

```shell
{
    "Version": "v2.4.11+3d9e9f2",
    "BuildDate": "2022-08-22T09:13:16Z",
    "GitCommit": "3d9e9f2f95b7801b90377ecfc4073e5f0f07205b",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

```
rpc error: code = Unknown desc = config management plugin not supported. plugin name conf
```

### PR DESCRIPTION
**Pull request by drozd-A**
Closes #12040

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: util/app/discovery/discovery.go [hunk 1]
```diff
@@ -100,7 +100,7 @@ func DetectConfigManagementPlugin(ctx context.Context, repoPath, pluginName stri
 		// check if the given plugin supports the repo
 		conn, cmpClient, connFound = cmpSupports(ctx, pluginSockFilePath, repoPath, fmt.Sprintf("%v.sock", pluginName), env, tarExcludedGlobs)
 		if !connFound {
-			return nil, nil, fmt.Errorf("couldn't find cmp-server plugin with name %v supporting the given repository", pluginName)
+			return nil, nil, fmt.Errorf("couldn't find cmp-server plugin with name '%v' supporting the given repository", pluginName)
```
Comment (crenshaw-dev) [inline util/app/discovery/discovery.go:103]:
```suggestion
			return nil, nil, fmt.Errorf("couldn't find cmp-server plugin with name %q supporting the given repository", pluginName)
```

**Review by crenshaw-dev — APPROVED** [review]
