### PR TITLE
fix: existingWindows to treat all fields of the window instead of a small subset of them (#20712)

### LINKED ISSUE #20712: SyncWindow should allow to have multiple sync windows which has same kind,schedule,duration
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Currently, it does not allow having multiple sync windows which have same kind+schedule+duration combination
Let's say I want to have sync windows like the below
```json
[
  {
    "kind": "allow",
    "schedule": "0 0 * * *",
    "duration": "6h",
    "applications": [
      "two*"
    ],
    "timeZone": "Asia/Seoul"
  },
  {
    "kind": "allow",
    "schedule": "0 0 * * *",
    "duration": "6h",
    "applications": [
      "one*"
    ],
    "timeZone": "Asia/Seoul"
  },
...
```

It would stuck at project validation step at
https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/app_project_types.go#L261

We can mitigate this by just splits it by minutes, but hope it been resolved to make it simple to manage.

**To Reproduce**

Just create multiple sync windows having the same kind+schedule+duration

**Expected behavior**

Allow to have multiple time duplicated sync windows

**Version**

```shell
argocd: v2.11.1+9f40df0
  BuildDate: 2024-05-21T22:43:41Z
  GitCommit: 9f40df0c29eca7e45a73f802f033dfd1ed0068e3
  GitTreeState: clean
  GoVersion: go1.22.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.11.5+c4b283c
  BuildDate: 2024-07-15T17:39:54Z
  GitCommit: c4b283ce0c092aeda00c78ae7b3b2d3b28e7feec
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

### PR DESCRIPTION
**Pull request by itaispiegel**
This PR fixes the [ValidateProject](https://github.com/argoproj/argo-cd/blob/04794332d28e44c18c89b83e9c54f0bcd69bcc43/pkg/apis/application/v1alpha1/app_project_types.go#L177) method to treat all the fields of the SyncWindow to validate the uniqueness of the windows.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

Closes #20712

### CODE REVIEW

File: pkg/apis/application/v1alpha1/app_project_types.go [hunk 1]
```diff
@@ -257,17 +259,22 @@ func (proj *AppProject) ValidateProject() error {
 			if window == nil {
 				continue
 			}
-			if _, ok := existingWindows[window.Kind+window.Schedule+window.Duration]; ok {
+			windowJSON, err := json.Marshal(window)
+			if err != nil {
+				return status.Errorf(codes.Internal, "failed to marshal window: %v", err)
+			}
+			windowJSONHash := md5.Sum(windowJSON)
```
Comment (agaudreault) [inline pkg/apis/application/v1alpha1/app_project_types.go]: Marshaling + md5 hash will be very slow. You could run a go benchmark to validate it.

If more fields should be considered for uniqueness, create a function on the type to return the "key" as a concatenation of the fields to consider for uniqueness.

In general, string concatenation will be faster than using the struct as a key.

File: pkg/apis/application/v1alpha1/types_test.go [hunk 2]
```diff
@@ -4543,3 +4543,17 @@ func TestCluster_ParseProxyUrl(t *testing.T) {
 		}
 	}
 }
+
+func TestAppProject_ValidateSyncWindowDuplicates(t *testing.T) {
```
Comment (agaudreault) [inline pkg/apis/application/v1alpha1/types_test.go]: Test should not be in the types_test.go file if the code changed is in app_project_types.go

Comment (agaudreault) [inline pkg/apis/application/v1alpha1/types_test.go]: Test should be part of TestAppProject_ValidateSyncWindowList

**Review by agaudreault — CHANGES_REQUESTED** [review]

File: pkg/apis/application/v1alpha1/app_project_types.go (hunk 1 above)
Comment (itaispiegel) [reply pkg/apis/application/v1alpha1/app_project_types.go]: You're right, this is probably not the best way to implement this.
I just addresses this by defining a `Hash` method for the `SyncWindow` struct, and implemented it using the `gob` encoder and `xxhash` which should have much better performance.
What do you think about this? Does this look okay to you?
The things is that I think that we shouldn't limit ourselves only to a subset of fields, and I think we should use all fields to compare the windows.

File: pkg/apis/application/v1alpha1/types_test.go (hunk 2 above)
Comment (itaispiegel) [reply pkg/apis/application/v1alpha1/types_test.go]: Is it okay then to move this to be in `TestAppProject_ValidateSyncWindowList` as you mentioned in the [comment](https://github.com/argoproj/argo-cd/pull/23636#discussion_r2180542523) below?

**Comment by itaispiegel** [comment]
@agaudreault can you please review again? 😄

File: pkg/apis/application/v1alpha1/app_project_types.go [hunk 3]
```diff
@@ -252,12 +252,13 @@ func (proj *AppProject) ValidateProject() error {
...
-		existingWindows := make(map[string]bool)
+		existingWindows := make(map[uint64]bool)
 		for _, window := range proj.Spec.SyncWindows {
 			if window == nil {
 				continue
 			}
-			if _, ok := existingWindows[window.Kind+window.Schedule+window.Duration]; ok {
+			windowHash := window.Hash()
+			if _, ok := existingWindows[windowHash]; ok {
 				return status.Errorf(codes.AlreadyExists, "window '%s':'%s':'%s' already exists, update or edit", window.Kind, window.Schedule, window.Duration)
```
Comment (andrii-korotkov) [inline pkg/apis/application/v1alpha1/app_project_types.go]: Let's add the hash to the message as well

File: pkg/apis/application/v1alpha1/types.go [hunk 4]
```diff
@@ -22,6 +24,7 @@ import (
 	"github.com/argoproj/gitops-engine/pkg/health"
 	synccommon "github.com/argoproj/gitops-engine/pkg/sync/common"
 	"github.com/argoproj/gitops-engine/pkg/utils/kube"
+	"github.com/cespare/xxhash/v2"
```
Comment (andrii-korotkov) [inline pkg/apis/application/v1alpha1/types.go:27]: Let's use some standard hash library?

File: pkg/apis/application/v1alpha1/app_project_types.go (hunk 3 above)
Comment (itaispiegel) [reply pkg/apis/application/v1alpha1/app_project_types.go]: Okay, sure 😄

File: pkg/apis/application/v1alpha1/types.go (hunk 4 above)
Comment (itaispiegel) [reply pkg/apis/application/v1alpha1/types.go:27]: xxHash is widely regarded as a standard non-cryptographic hash function. It's extremely fast and well-suited for use cases like this where performance matters more than cryptographic security.
Are there any other hash functions you’d suggest we consider instead?

**Comment by itaispiegel** [comment]
Can we merge this? 🙏🏻

File: pkg/apis/application/v1alpha1/types.go [hunk 5]
```diff
@@ -3130,6 +3133,16 @@ func (w *SyncWindow) Validate() error {
 	return nil
 }
 
+func (w *SyncWindow) Hash() uint64 {
+	var windowBuffer bytes.Buffer
+	enc := gob.NewEncoder(&windowBuffer)
+	err := enc.Encode(w)
+	if err != nil {
+		return 0
```
Comment (agaudreault) [inline pkg/apis/application/v1alpha1/types.go]: should return `err`. If there is a problem with this code, the hash will be 0 for 2 windows leading to a `window '%s':'%s':'%s' already exists, update or edit` error. This will not be easy to figure out why.

and it requires a test for error handling

File: pkg/apis/application/v1alpha1/types.go [hunk 6]
```diff
@@ -3130,6 +3133,16 @@ func (w *SyncWindow) Validate() error {
 	return nil
 }
 
+func (w *SyncWindow) Hash() uint64 {
+	var windowBuffer bytes.Buffer
+	enc := gob.NewEncoder(&windowBuffer)
+	err := enc.Encode(w)
```
Comment (agaudreault) [inline pkg/apis/application/v1alpha1/types.go]: Should it really be all fields? I am not sure `ManualSync` and `Description` should be part of what decide if a window is unique or not.

**Review by agaudreault — CHANGES_REQUESTED** [review]

**Comment by itaispiegel** [comment]
@agaudreault Fixed. Please review again 😄

**Review by agaudreault — APPROVED** [review]
