### PR TITLE
Deprecate componentParameterOverrides in favor of source specific config

### LINKED ISSUE #1141: Deprecate ComponentParameterOverrides in favor of source specific config
Our ComponentParameterOverrides feature is getting overloaded and is attempting to normalize different concepts of "parameters" into a single datastructure, which doesn't always fit. Some examples of this:

* the concept of "component" came from ksonnet, but has no meaning in helm.
* helm has both `--set` and `--set-string`, but we only support `--set`
* kustomize 2.0 has image whereas kustomize 1.0 has imagetag
* jsonnet has `ext-str` and `tla-code`

Rather than trying to fit everything into this concept of ComponentParameterOverrides, the current thought is to deprecate this feature in favor of explicit application source config specific to the tool.

### LINKED ISSUE #1196: Application history should include copy of application source.
Currently application history stores only component parameter overrides. Instead, it should include a full copy of the application source at a moment of synchronization.

Application source path, template tool settings might change in git over time. In this case rollback could be impossible since history does not have such information.

### LINKED ISSUE #1201: `argocd app create APPNAME --file` should fail when name conflicts
A user tried using `argocd app create APPNAME --file app.yaml`, but APPNAME disagreed with the file's metadata.name in this case, but we still allowed this to be created. We should error instead.

### LINKED ISSUE #1208: Deletion of an auto-synced app causes infighting
Auto-sync does not take into account that an app has was marked for deleting, and will try to auto-sync even when it is deleting, which causes resources to be recreated.

### PR DESCRIPTION
**Pull request by jessesuen**
1. begins the deprecation process of componentParameterOverrides. Application reconciliation will invoke migration logic to move componentParameterOverrides to their new locations in ksonnet.parameters, helm.parameters, and kustomize.imageTags. componentParameterOverrides will be removed in a future release (likely the next release).

Resolves #1141

2. With the deprecation of componentParameterOverrides, we now store the entire appSource as part of sync history. This allows us to rollback even when user changes things like the repo, path, kustomize namePrefix, etc...

Resolves #1196

3. Removes the legacy `spec.source.environment` and `spec.source.valuesFiles` which were deprecated in v0.11

4. Fixes small issue where `argocd app create APPNAME --file` didn't fail when there were name conflicts

Resolves: #1201

6. Fixes issue where auto-sync and app deletion would fight each other

Resolves: #1208

### CODE REVIEW

**Comment by jessesuen** [comment]
Example of the new history. Notice it is able to switch between repo paths and app source types. 

```yaml
  - deployedAt: "2019-03-01T07:28:32Z"
    id: 12
    revision: a95c7943effa602740aa54fe4755ad3f4870bee3
    source:
      ksonnet:
        environment: default
      path: ksonnet-guestbook
      repoURL: https://github.com/argoproj/argocd-example-apps
      targetRevision: HEAD
  - deployedAt: "2019-03-01T07:28:44Z"
    id: 13
    revision: a95c7943effa602740aa54fe4755ad3f4870bee3
    source:
      ksonnet:
        environment: default
      path: ksonnet-guestbook
      repoURL: https://github.com/argoproj/argocd-example-apps
      targetRevision: HEAD
  - deployedAt: "2019-03-01T07:29:06Z"
    id: 14
    revision: a95c7943effa602740aa54fe4755ad3f4870bee3
    source:
      path: guestbook
      repoURL: https://github.com/argoproj/argocd-example-apps
      targetRevision: HEAD
```

File: controller/appcontroller.go [hunk 1]
```diff
@@ -703,7 +703,13 @@ func (ctrl *ApplicationController) normalizeApplication(app *appv1.Application)
 	logCtx := log.WithFields(log.Fields{"application": app.Name})
 	appClient := ctrl.applicationClientset.ArgoprojV1alpha1().Applications(app.Namespace)
 	modifiedApp := app.DeepCopy()
-	modifiedApp.Spec = *argo.NormalizeApplicationSpec(&app.Spec)
+
+	appSourceType, err := argo.QueryAppSourceType(context.Background(), app, ctrl.repoClientset, ctrl.db)
```
Comment (alexmt) [inline controller/appcontroller.go]: I think it would be better to return app source type as part of `GenerateManifest`. In this case, type should be available after executing `CompareAppState` in `compareResult` and we don't need to query it again. 

This is just nice to have enhancement. Implement it if you want to.

**Review by alexmt — CHANGES_REQUESTED** [review]

File: server/application/application.go [hunk 2]
```diff
@@ -875,19 +850,14 @@ func (s *Server) Rollback(ctx context.Context, rollbackReq *ApplicationRollbackR
...
-			Revision:           deploymentInfo.Revision,
-			DryRun:             rollbackReq.DryRun,
-			Prune:              rollbackReq.Prune,
-			SyncStrategy:       &appv1.SyncStrategy{Apply: &appv1.SyncStrategyApply{}},
-			ParameterOverrides: overrides,
+			Revision:     deploymentInfo.Revision,
+			DryRun:       rollbackReq.DryRun,
+			Prune:        rollbackReq.Prune,
+			SyncStrategy: &appv1.SyncStrategy{Apply: &appv1.SyncStrategyApply{}},
+			Source:       &deploymentInfo.Source,
```
[the remark this answers is not in the document]
Comment (jessesuen) [reply server/application/application.go]: Agree. Will change.

File: controller/appcontroller.go (hunk 1 above)
Comment (jessesuen) [reply controller/appcontroller.go]: Good idea. Let me give it a try.

Comment (jessesuen) [reply controller/appcontroller.go]: API sever will error if deploymentInfo.Source.IsZero().

File: server/application/application.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (jessesuen) [reply server/application/application.go]: API sever will error if deploymentInfo.Source.IsZero().

**Review by alexmt — APPROVED** [review]
LGTM
