### PR TITLE
fix: use custom cluster secret informer

### LINKED ISSUE #25517: Application Controller higher CPU in 3.X upgrade
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

Related issues #24167, #17277, #23965

I am noticing a performance regression in v3.x after upgrading from 2.14, where syncs are taking minutes instead of seconds in Argo CD 3.x. CPU profiling shows 62% of time spent in `GetDestinationCluster`.

Image

Image

#21189 replaced `ValidateDestination` with `GetDestinationCluster`.

`ValidateDestination` was pretty lightweight, but with `GetDestinationCluster`, it's parsing secrets, decoding JSON, etc. [Every 10 seconds](https://github.com/argoproj/argo-cd/blob/a62e3687f2dbf74d22c570075dc722614d476a29/controller/clusterinfoupdater.go#L59), for each cluster, we check every app to count how many belong to that cluster. This results in N (apps) × M (clusters) calls to `GetDestinationCluster`. 

Even though the db uses [informer caching](https://github.com/argoproj/argo-cd/blob/a62e3687f2dbf74d22c570075dc722614d476a29/util/db/cluster.go#L281), `GetDestinationCluster` has [significant overhead](https://github.com/argoproj/argo-cd/blob/a62e3687f2dbf74d22c570075dc722614d476a29/util/settings/settings.go#L1293) when called thousands of times per cycle.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
❯ argocd version
argocd: v3.2.1+8c4ab63
  BuildDate: 2025-12-01T09:30:10Z
  GitCommit: 8c4ab63a9c72b31d96c6360514cda6254e7e6629
  GitTreeState: clean
  GoVersion: go1.25.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v3.2.1+8c4ab63
  BuildDate: 2025-11-30T11:48:14Z
  GitCommit: 8c4ab63a9c72b31d96c6360514cda6254e7e6629
  GitTreeState: clean
  GoVersion: go1.25.0
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.7.0 2025-06-28T07:01:13Z
  Helm Version: v3.18.4+gd80839c
  Kubectl Version: v0.34.0
  Jsonnet Version: v0.21.0
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by blakepettersson**
Create a dedicated cluster secret informer that transforms from a `v1.Secret` to a `Cluster`, saving a bunch of parsing from secret to cluster. Hopefully fixes #25517.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by blakepettersson** [comment]
@rumstead will give this a spin to benchmark it in his env.

**Comment by rumstead** [comment]
In a local cluster syncing and managing 300 applicaitons across 3 cluster


| Function | Before (cum%) | After (cum%) | Net |
|----------|---------------|--------------|-------------|
| `GetDestinationCluster` | **19.85%** | **4.10%** | **4.8x reduction** |
| `clusterInfoUpdater.getUpdatedClusterInfo` | **17.56%** | **2.13%** | **8.2x reduction** |
| `db.GetClusterServersByName` | **12.21%** | **3.44%** | **3.5x reduction** |
| `db.GetCluster` | **7.63%** | **0.66%** | **11.6x reduction** |
| `SecretToCluster` | **6.87%** | **Not visible** | **Woohoo** |

Going to do a similar exercise in our proprod clusters.

File: util/settings/cluster_informer.go [hunk 1]
```diff
@@ -0,0 +1,234 @@
...
+				return []string{cluster.Name}, nil
+			}
+			return nil, nil
+		},
+	}, func(options *metav1.ListOptions) {
+		// Only watch secrets with the cluster label
+		options.LabelSelector = fmt.Sprintf("%s=%s", common.LabelKeySecretType, common.LabelValueSecretTypeCluster)
+	})
+
+	err := informer.SetTransform(func(obj any) (any, error) {
```
Comment (rumstead) [inline util/settings/cluster_informer.go:73]: I was just reading the transformer docs and going to paste them here so we can verify. 
```
// It's recommended for the TransformFunc to be idempotent.
// It MUST be idempotent if objects already present in the cache are passed to
// the Replace() to avoid re-mutating them. Default informers do not pass
// existing objects to Replace though.
//
// Note that TransformFunc is called while inserting objects into the
// notification queue and is therefore extremely performance sensitive; please
// do not do anything that will take a long time.
```

I believe we meet both citeria. The most expensive action here is converting the secret to a cluster and unmarshaling.

**Comment by rumstead** [comment]
Here are less applications but with half a dozen live AKS clusters. 

| Function | Before (cum%) | After (cum%) | Net |
-- | -- | -- | --
GetClusterServersByName | 0.13s | 0.03s | -77% 
Secret.DeepCopy | 0.09s | 0.02s | -78% 
GetSettings | 0.18s | 0.11s | -39%
getSecrets | 0.07s | 0.04s | -43%
SecretToCluster | 0.05s | 0s | Gone from the samples Woohoo 
GetCluster | 0.10s | 0.09s | -10%

**Review by rumstead — APPROVED** [review]
LGTM

**Review by christianh814 — APPROVED** [review]
