### PR TITLE
fix: Exec with disable auth not logged in #17114

### LINKED ISSUE #17114: When --disable-auth is enabled, exec no longer works without a log in
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When `argocd-server` is started with `--disable-auth --insecure`, pod exec will not work without a login. It was working on v2.5.8 but not on v2.10.0/v2.8.3. After logging in as an admin user, it works.

I understand this fix for expiring sessions for some CVE here: https://github.com/argoproj/argo-cd/commit/e047efa8f9518c54d00d2e4493b64bc4dba98478, so it should not be working since v2.6.0

From what I checked, without logging in as an admin user, it does not send any cookie with the key `argocd.token`, causing the session to produce an `Internal server error`. There are no logs that are relevant other than this:

```
time="2024-02-07T07:55:59Z" level=info msg="terminal session starting" appNamespace=argo application=argo-cd container=argocd-server namespace=argo podName=argocd-server-645954b5ff-kxjf9 project=default userName=
```

When logged in as an admin user, the `argocd.token` appears in the cookie and it works. 

**To Reproduce**

Main manifest is here: https://github.com/argoproj/argo-cd/blob/v2.10.0/manifests/install.yaml, with these edits:

```yaml
# argocd-cm
data:
  exec.enabled: "true"

# argocd-rbac-cm
data:
  policy.default: role:admin

# argocd-server Role
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create

# argocd-server ClusterRole
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
```

Exec into a known pod with a shell without logging in.

**Expected behavior**

A non logged in user should be able to exec into pods with `--disable-auth` and `policy.default: role:admin` set.

**Screenshots**

Screenshot 2024-02-07 at 4 42 37 PM

**Version**

```shell
argocd@argocd-server-645954b5ff-kxjf9:~$ argocd version
argocd: v2.10.0+2175939
  BuildDate: 2024-02-06T14:28:43Z
  GitCommit: 2175939ed6156ddd743e60f427f7f48118c971bf
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Largely irrelevant but this was the only log that was attached.

```
time="2024-02-07T07:55:59Z" level=info msg="terminal session starting" appNamespace=argo application=argo-cd container=argocd-server namespace=argo podName=argocd-server-645954b5ff-kxjf9 project=default userName=
```

### PR DESCRIPTION
**Pull request by reggie-k**
Closes #17114

Checklist:

* [ X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ X] The title of the PR states what changed and the related issues number (used for the release note).
* [ X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
@CodiumAI-Agent /review

File: server/server.go [hunk 1]
```diff
@@ -1041,7 +1041,9 @@ func (a *ArgoCDServer) newHTTPServer(ctx context.Context, port int, grpcWebHandl
 	}
 	mux.Handle("/api/", handler)
 
-	terminal := application.NewHandler(a.appLister, a.Namespace, a.ApplicationNamespaces, a.db, a.enf, a.Cache, appResourceTreeFn, a.settings.ExecShells, a.sessionMgr).
+	terminalOpts := application.NewTerminalOptions(a.ArgoCDServerOpts.DisableAuth, a.enf)
```
Comment (pasha-codefresh) [inline server/server.go:1044]: i think just TermalOptions{disableAuth: a.ArgoCDServerOpts.DisableAuth, enf: a.enf} will looks better

**Review by pasha-codefresh — CHANGES_REQUESTED** [review]

**Comment by pasha-codefresh** [comment]
Also please run `make lint-local`

File: server/application/websocket.go [hunk 2]
```diff
@@ -56,7 +54,7 @@ func getToken(r *http.Request) (string, error) {
 }
 
 // newTerminalSession create terminalSession
-func newTerminalSession(ctx context.Context, w http.ResponseWriter, r *http.Request, responseHeader http.Header, sessionManager *util_session.SessionManager, appRBACName string, enf *rbac.Enforcer) (*terminalSession, error) {
+func newTerminalSession(ctx context.Context, w http.ResponseWriter, r *http.Request, responseHeader http.Header, sessionManager *util_session.SessionManager, appRBACName string, terminalOpts TerminalOptions) (*terminalSession, error) {
```
Comment (pasha-codefresh) [inline server/application/websocket.go:57]: TerminalOptions , i would pass it as reference

**Review by pasha-codefresh — CHANGES_REQUESTED** [review]

**Review by pasha-codefresh — APPROVED** [review]
