### PR TITLE
fix: copy github app key from repocreds

### LINKED ISSUE #6150: Github App cannot be used as a Repository Credentials Template
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Github Apps do not work as credentials template. From inspection of the source code, it appears that the private key is not being copied from the credential template to the instance of credentials being used to connect for the repository. 

**To Reproduce**
Create a GitHub App credential template and attempt to create a private repository that should match the template. You will get an authentication required error. 

**Expected behavior**
Repositories that match an authorized GitHub App credential template should be able to connect using the credential template. 

**Version**
2.0.1

### PR DESCRIPTION
**Pull request by backjo**
Closes #6150 

Signed-off-by: Jonah Back <jonah@jonahback.com>

This PR includes the GithubAppPrivateKey as a secret to be copied over from repocreds. This allows Github Apps to work as a credential template.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Thanks @backjo! For the sake of completeness, would you mind creating a bug issue that's linked to this PR please?

**Comment by backjo** [comment]
#6093 is probably this bug.

**Comment by backjo** [comment]
@jannfis  added!

**Review by jannfis — APPROVED** [review]
LGTM, thank you!

File: util/db/repository.go [hunk 1]
```diff
@@ -186,11 +186,12 @@ func (db *db) credentialsToRepository(repoInfo settings.Repository) (*appsv1.Rep
...
-		&SecretMaperValidation{Dest: &repo.SSHPrivateKey, Transform: StripCRLFCharacter}:     repoInfo.SSHPrivateKeySecret,
-		&SecretMaperValidation{Dest: &repo.TLSClientCertData, Transform: StripCRLFCharacter}: repoInfo.TLSClientCertDataSecret,
-		&SecretMaperValidation{Dest: &repo.TLSClientCertKey, Transform: StripCRLFCharacter}:  repoInfo.TLSClientCertKeySecret,
+		&SecretMaperValidation{Dest: &repo.Username, Transform: StripCRLFCharacter}:            repoInfo.UsernameSecret,
+		&SecretMaperValidation{Dest: &repo.Password, Transform: StripCRLFCharacter}:            repoInfo.PasswordSecret,
+		&SecretMaperValidation{Dest: &repo.SSHPrivateKey, Transform: StripCRLFCharacter}:       repoInfo.SSHPrivateKeySecret,
+		&SecretMaperValidation{Dest: &repo.TLSClientCertData, Transform: StripCRLFCharacter}:   repoInfo.TLSClientCertDataSecret,
+		&SecretMaperValidation{Dest: &repo.TLSClientCertKey, Transform: StripCRLFCharacter}:    repoInfo.TLSClientCertKeySecret,
+		&SecretMaperValidation{Dest: &repo.GithubAppPrivateKey, Transform: StripCRLFCharacter}: repoInfo.GithubAppPrivateKeySecret,
```
Comment (joebowbeer) [inline util/db/repository.go:194]: It would be great if there were a unit test for this. This is actually fixing an earlier regression that went undetected.

**Comment by jannfis** [comment]
This commit has been cherry-picked into 2.0 release branch.

/cc @alexmt
