### PR TITLE
fix(repo-server): When using custom kustomize versions, obtain the correct path (#21449)

### LINKED ISSUE #21449: Error with Kustomize with --enable-helm option
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using ArgoCD v2.13+ with kustomize v5.3.0 or below, configured through [Custom kustomize versions](https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#custom-kustomize-versions), an error occurs during synchronization when the --enable-helm option is used.

##### Problem Details

This error occurs because the specified version of kustomize in the repository is v5.2.1-helm, which does not implement the --helm-kube-version flag. This is confirmed by the help output of kustomize_5_2_1.

##### Root Cause Analysis

The root cause of the problem was analyzed as follows:

The parseKustomizeBuildOptions function checks build options.([source](https://github.com/argoproj/argo-cd/blob/v2.13.1/util/kustomize/kustomize.go#L353))

A specific condition is true when buildOpts is not empty, the kustomize version is v5.3.0 or above, and --enable-helm is set.([source](https://github.com/argoproj/argo-cd/blob/v2.13.1/util/kustomize/kustomize.go#L356))

There is an issue with the version obtained through the getSemverSafe -> getSemver -> Version functions.*([source](https://github.com/argoproj/argo-cd/blob/v2.13.1/util/kustomize/kustomize.go#L430))

The desired binary version is /usr/local/bin/kustomize_5_2_1, but the binary is fixed as kustomize, leading to inconsistency.([source](https://github.com/argoproj/argo-cd/blob/v2.13.1/util/kustomize/kustomize.go#L436))

**To Reproduce**

Steps to reproduce the issue:

1.Configure ArgoCD with kustomize v5.2.1-helm.
1. Attempt to sync a project using the --enable-helm option.
1. Observe the error message.

**Expected behavior**

Synchronization should proceed without errors, and the --helm-kube-version flag should be handled correctly.

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v2.13.2+dc43124
  BuildDate: 2024-12-11T19:59:01Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.23.4
  Compiler: gc
  Platform: darwin/arm64

```

**Logs**

```
Failed to load target state: failed to generate manifest for source 1 of 1:
rpc error: code = Unknown desc =
`/usr/local/bin/kustomize_5_2_1 build <path to cached source>/beta
--enable-helm
--helm-kube-version 1.24
...
failed exit status 1: Error: unknown flag: --helm-kube-version
```

### PR DESCRIPTION
**Pull request by Asuforce**
Fixes #21449

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by Asuforce** [comment]
@nitishfy I fixed conflict. Could you review it?

**Review by andrii-korotkov-verkada — APPROVED** [review]

File: util/kustomize/kustomize.go [hunk 1]
```diff
@@ -448,7 +448,12 @@ func getSemverSafe() *semver.Version {
 }
 
 func Version() (string, error) {
-	cmd := exec.Command("kustomize", "version", "--short")
+	return versionWithBinaryPath(&kustomize{})
+}
+
+func versionWithBinaryPath(k *kustomize) (string, error) {
+	executable := k.getBinaryPath()
+	cmd := exec.Command(executable, "version", "--short")
```
Comment (rumstead) [inline util/kustomize/kustomize.go:456]: `--short` has been deprecated, should we move it? It also makes parsing the version way easier now.

Comment (Asuforce) [reply util/kustomize/kustomize.go:456]: @rumstead I understand your point, but this is outside the scope of this PR. It should be addressed in a separate PR.

**Review by agaudreault — APPROVED** [review]
