### PR TITLE
fix(applications): update application navigation URLs (#22671)

### LINKED ISSUE #22671: UI: Browsing to an application from the search box on another application's page has incorrect URL path
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

See: 

https://github.com/argoproj/argo-cd/issues/21730
https://github.com/argoproj/argo-cd/issues/21730#issuecomment-2703333092

I can reproduce this from the main page. I also have still seen it happen from an application page but I cannot currently reproduce it.

**To Reproduce**

Go to `https://argocd/applications/`

Note the trailing slash.

The path becomes `https://argocd/applications?showFavorites=false&proj=&sync=&autoSync=&health=&namespace=&cluster=&labels=`

Open an application, the path becomes:

`https://argocd/applications/applications/argocd/my-app?view=tree`

No app is opened because namespace applications does not exist and or contains no app named argocd.

**Expected behavior**

Path should be `https://argocd/applications/argocd/my-app?view=tree`

**Version**

```shell
{
    "Version": "v2.14.9+38985bd",
    "BuildDate": "2025-04-02T19:31:28Z",
    "GitCommit": "38985bdcd6c3b031fb83757a1fb0c39a55bf6a24",
    "GitTreeState": "clean",
    "GoVersion": "go1.23.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.3 2024-07-19T16:40:33Z",
    "HelmVersion": "v3.16.3+gcfd0749",
    "KubectlVersion": "v0.31.0",
    "JsonnetVersion": "v0.20.0"
}
```

### PR DESCRIPTION
**Pull request by Ruby-rc**
Close #22671

## Summary

Fix application list navigation routing errors

## Description

Fixed missing leading slash in navigation paths that caused incorrect routing when:
- Using keyboard navigation (Enter key) in applications table and tiles view
- Clicking on application rows/tiles 
- Selecting applications from search autocomplete

### Before

https://github.com/user-attachments/assets/45dd11bc-d2fa-4939-9f48-95978ffbea48

### After fixed navigation

https://github.com/user-attachments/assets/54e97d7e-02fa-4fe3-8843-a66dcaa603ac

 
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: ui/src/app/applications/components/applications-list/applications-list.tsx [hunk 1]
```diff
@@ -263,7 +263,10 @@ const SearchBar = (props: {content: string; ctx: ContextApis; apps: models.Appli
                 </React.Fragment>
             )}
             onSelect={val => {
-                ctx.navigation.goto(`./${val}`);
+                const selectedApp = apps.find(app => AppUtils.appQualifiedName(app, useAuthSettingsCtx?.appsInAnyNamespaceEnabled) === val);
```
Comment (nitishfy) [inline ui/src/app/applications/components/applications-list/applications-list.tsx]:
```suggestion
                const qualifiedName = AppUtils.appQualifiedName(app, useAuthSettingsCtx?.appsInAnyNamespaceEnabled);
                const selectedApp = apps?.find(app => qualifiedName === val);
```

I'd suggest assigning it to a temporary variable to clarify what you're matching against.

File: ui/src/app/applications/components/applications-list/applications-list.tsx [hunk 2]
```diff
@@ -263,7 +263,11 @@ const SearchBar = (props: {content: string; ctx: ContextApis; apps: models.Appli
                 </React.Fragment>
             )}
             onSelect={val => {
-                ctx.navigation.goto(`./${val}`);
+                const qualifiedName = AppUtils.appQualifiedName(app, useAuthSettingsCtx?.appsInAnyNamespaceEnabled);
+                const selectedApp = apps?.find(app => qualifiedName === val);
```
Comment (linghaoSu) [inline ui/src/app/applications/components/applications-list/applications-list.tsx]: image


```suggestion
                const selectedApp = apps?.find(app => {
                    const qualifiedName = AppUtils.appQualifiedName(app, useAuthSettingsCtx?.appsInAnyNamespaceEnabled);
                    return qualifiedName === val;
                });
```

**Review by linghaoSu — CHANGES_REQUESTED** [review]

**Review by linghaoSu — COMMENTED** [review]
Maybe we could also update the other relative paths here, as they could potentially lead to similar issues.

Cleaning these up would help make the navigation behavior more consistent and predictable.

https://github.com/argoproj/argo-cd/blob/0093bddc39eaca16ac4d69dbf110de95e10fd7c6/ui/src/app/settings/components/accounts-list/accounts-list.tsx#L28

https://github.com/argoproj/argo-cd/blob/7945b26d95b39a57998b61ef48264ca5deb8c122/ui/src/app/settings/components/clusters-list/clusters-list.tsx#L76

https://github.com/argoproj/argo-cd/blob/e53a3f89f01c90017bb63a266f4fdca750663af9/ui/src/app/settings/components/projects-list/projects-list.tsx#L38

https://github.com/argoproj/argo-cd/blob/e53a3f89f01c90017bb63a266f4fdca750663af9/ui/src/app/settings/components/projects-list/projects-list.tsx#L85

**Comment by Ruby-rc** [comment]
> Maybe we could also update the other relative paths here, as they could potentially lead to similar issues.
> 
> Cleaning these up would help make the navigation behavior more consistent and predictable.
> 
> https://github.com/argoproj/argo-cd/blob/0093bddc39eaca16ac4d69dbf110de95e10fd7c6/ui/src/app/settings/components/accounts-list/accounts-list.tsx#L28
> 
> https://github.com/argoproj/argo-cd/blob/7945b26d95b39a57998b61ef48264ca5deb8c122/ui/src/app/settings/components/clusters-list/clusters-list.tsx#L76
> 
> https://github.com/argoproj/argo-cd/blob/e53a3f89f01c90017bb63a266f4fdca750663af9/ui/src/app/settings/components/projects-list/projects-list.tsx#L38
> 
> https://github.com/argoproj/argo-cd/blob/e53a3f89f01c90017bb63a266f4fdca750663af9/ui/src/app/settings/components/projects-list/projects-list.tsx#L85

I don't think this would constitute a bug at this moment. (For example: Clicking on a specific cluster at https://xxx/settings/clusters/, takes you back to https://xxx/settings).

If we were to change the absolute path, would we manually append the previous path (e.g., /settings/clusters/xxx)?

I feel that in such a case,  using the absolute path makes it too tightly coupled with the first-level route, which could lead to issues if the root path changes. Maybe a relative path would be safer?

**Review by linghaoSu — APPROVED** [review]
LGTM

**Review by agaudreault — APPROVED** [review]
