### PR TITLE
fix: updating cluster drops secret (#5135)

### LINKED ISSUE #5135: Token lost when renaming a cluster
**Describe the bug**

When renaming a cluster, Argo CD looses the bearer token and thus is unable to connect to the cluster anymore.

**To Reproduce**

* Dump the argocd config of the cluster: `kubectl -n argocd get secrets cluster-XXX-XXX -o yaml` 
* Change the name of the cluster in the Argo CD web interface.
* Notice that the cache info on the cluster page is blank and apps from that cluster turn into the state unknown.
* Check the config of the cluster again: `kubectl -n argocd get secrets cluster-XXX-XXX -o yaml` 
* Notice that the config is now `{"tlsClientConfig":{"insecure":false,"caData":"..."}}` instead of `{"bearerToken":"...","tlsClientConfig":{"insecure":false,"caData":"..."}}`. The bearerToken key disappeared.

**Expected behavior**

Connection to cluster still works after renaming.

**Version**

```shell
argocd: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:57:57Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

```
time="2020-12-28T09:20:58Z" level=error msg="finished unary call with code Unknown" error="ComparisonError: forbidden: User \"system:anonymous\" cannot get path \"/apis/apps/v1\"" grpc.code=Unknown grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2020-12-28T09:20:58Z" grpc.time_ms=1.832 span.kind=server system=grpc
```

### PR DESCRIPTION
**Pull request by kshamajain99**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

closes #5135

### CODE REVIEW

File: ui/src/app/shared/services/clusters-service.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export class ClustersService {
     public update(cluster: models.Cluster, ...paths: string[]): Promise<models.Cluster> {
         return requests
             .put(`/clusters/${encodeURIComponent(cluster.server)}`)
-            .query({updatedPaths: paths})
+            .query({updatedFields: paths})
```
Comment (alexmt) [inline ui/src/app/shared/services/clusters-service.ts:25]: 🤦

**Review by alexmt — APPROVED** [review]
Thank you @kshamajain99 !
Cherry-picking into 1.8
