### PR TITLE
fix(pkce): 20111 PKCE auth flow does not return user to previous path like dex auth flow

### LINKED ISSUE #18045: OIDC: PKCE Incorrectly Uses Base Redirect URL for ArgoCD Hosted Under Custom Path
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

I'm hosting ArgoCD at a custom base path (`mycompany.org/infra/argocd`) and using Keycloak as an external IdP. The configuration functions as expected until I enable PKCE (Proof Key for Code Exchange). Specifically, when enablePKCEAuthentication is set to true in the `argocd-cm` config map, the ArgoCD frontend incorrectly uses `window.location.origin` as the redirect URL, as demonstrated in the `getPKCERedirectURI` function located in [utils.ts](https://github.com/argoproj/argo-cd/blob/50027733db96e793c057fa64690cbbc38b76fda4/ui/src/app/login/components/utils.ts#L26C36-L26C57). 

**To Reproduce**

* Host Argocd under a sub-path, e.g. https://mycompany.org/infra/argocd/
* Configure an Idp Provider

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://mycompany.org/infra/argocd/
  enablePKCEAuthentication: true
  oidc.config: >-
    name: Keycloak
    issuer: https://<redacted>
    clientID: <redacted>
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes:
    - openid
    - profile
    - email
    - roles
    logoutURL: https://<redacted>/protocol/openid-connect/logout?redirect_uri={{logoutRedirectURL}}&id_token_hint={{token}}
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  - server.rootpath=/infra/argocd
  - server.basehref=/infra/argocd
```

* Click on `Login via Keycloak` button

**Expected behavior**

ArgoCD should respect one of the configured parameters (`server.rootpath`, `server.basehref`, or `url` from the `argocd-cm` or `argocd-cmd-params-cm` config map) to determine the correct base URL for redirects.

**Version**

```shell
v2.11.0-rc3+20fd621
```

### LINKED ISSUE #20111: Allow PKCE auth flow to preserve the user's current path to match Dex return_url capaility
# Summary

What change you think needs making.

The current PKCE auth flow will redirect to the authentication provider and return back to 'pkce/verify' which then calls pkceCallback and redirects the user back to '/applications' regardless of what path the user was previously at.

in ui/src/app/login/components/utils.ts
```
export const pkceCallback = ...

document.cookie = `argocd.token=${result.id_token}; path=/`;

window.location.replace('/applications');
```

This does not save the place of the user like the Dex auth flow where the return url is sent as a query param to Dex to return the user to after sso auth.

in ui/src/app/login/components/login.tsx
```
{href: `auth/login?return_url=${encodeURIComponent(this.state.returnUrl)}`})}
```

To make the two auth flows a similar user experience, the PKCE auth flow should return the user to their previous path like the Dex auth flow does.

# Motivation

Please give examples of your use case, e.g. when would you use this.

This would be used in any PKCE auth flow setup for SSO for ArgoCD.

# Proposal

How do you think this should be implemented?

I think the simplest way to achieve this is by caching the return url as a cookie in the pkceLogin function and reading back the cached path in the pkceCallback function which will then clean up the return url cookie or send the user to '/applications' if no return url cookie is present.

This would be similar to how the ID token is cached as a cookie after the pkce auth flow.

### PR DESCRIPTION
**Pull request by austin5219**
Fixes https://github.com/argoproj/argo-cd/issues/20111
Fixes https://github.com/argoproj/argo-cd/issues/18045

This stores the users path during a PKCE auth flow and returns the user to the saved path on the PKCE callback in order to mirror the behavior that dex auth has. With the exception of the login path, the users path is stored in session storage during pkcelogin and retrieved during pkcecallback, defaulting to '/applications' when not present. This mirrors Dex's behavior with the return_url query parameter.

This fix should be cherry-picked to 2.12

Below is a screenshot of a pkce token expiry triggering a reauth that now redirects the user to their previous path. Certain sections have been redacted to not leak confidential or sensitive information.
pkce_return_path

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [n/a] Does this PR require documentation updates?
* [n/a] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [n/a] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: ui/src/app/login/components/utils.ts [hunk 1]
```diff
@@ -153,7 +160,18 @@ export const pkceCallback = async (queryParams: string, oidcConfig: AuthSettings
...
+    // This is because when base href if not just '/' toAbsURL() will append a trailing '/'.
+    // Just removing a trailing '/' from the string would break when base href is not specified, defaulted to '/'.
+    // This pattern is used to handle both cases.
+    document.cookie = `argocd.token=${result.id_token}; path=/${requests.toAbsURL('').replace(/^\/|\/$/g, '')}`;
 
-    window.location.replace('/applications');
+    const returnURL = sessionStorage.getItem('return_url');
+
+    if (returnURL) {
+        sessionStorage.removeItem('return_url');
```
Comment (reggie-k) [inline ui/src/app/login/components/utils.ts:172]: Can you describe a little more the flow here? I see that the return_url is added to the sessionStorage and then removed from it. What would happen after setting it and before/after removing it?

Comment (austin5219) [reply ui/src/app/login/components/utils.ts:172]: Once a PKCE auth flow has been initiated, I attempt to cache the path that the user is at to sessionStorage. This caches the path information locally on the users browser before the user is redirected to the OIDC provider to authenticate with PKCE.

Once the user is authenticated and redirected back to ArgoCD with the ID Token, I attempt to get the cached path from sessionStorage. On a failure I default to redirecting the user back to `/applications' to maintain the behavior that existed before this change. On a success I remove the item from sessionStorage to clean up resources then redirect the user to the cached path.

I use sessionStorage instead of a cookie as I do not need to send this information as part of an HTTP request. This path data does not leave the users browser and while I do add a step to clean up this resource, it is automatically cleaned up by the browser once the session is ended anyways.

File: ui/src/app/app.tsx [hunk 2]
```diff
@@ -101,7 +102,19 @@ requests.onError.subscribe(async err => {
         // If basehref is the default `/` it will become an empty string.
         const basehref = document.querySelector('head > base').getAttribute('href').replace(/\/$/, '');
         if (isSSO) {
-            window.location.href = `${basehref}/auth/login?return_url=${encodeURIComponent(location.href)}`;
+            const authSettings = await services.authService.settings();
+            const ctx = React.useContext(Context);
```
Comment (reggie-k) [inline ui/src/app/app.tsx:106]: It is better to move this into the if that handles the error handling, cause needed only in case of error.

**Review by reggie-k — CHANGES_REQUESTED** [review]
It is better to move this into the if that handles the error handling, cause needed only in case of error.

**Comment by reggie-k** [comment]
@austin5219 regarding the error handling upon pkce-relogin and using the React context, please make sure to test the error use case to see the notification in action, I am not confident that using the React context there goes smooth.

File: ui/src/app/app.tsx (hunk 2 above)
Comment (austin5219) [reply ui/src/app/app.tsx]: This section had to be moved to a location that I could access the react component state. It should also clean this up.

**Review by reggie-k — APPROVED** [review]
Also had a session with Austin where he showed the behavior before and after the change, LGTM.

**Review by pasha-codefresh — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
Thank you @austin5219 , amazing work

**Comment by pasha-codefresh** [comment]
@austin5219 will it be big issue if we release it in 2.14 in next 3 months? it is available under latest tag, but because this bug fix is also affecting other components, i would consider it to release as part of 2.14 RC

**Comment by austin5219** [comment]
@pasha-codefresh  given it is a bug fix, is there any way it could be at least backported to 2.13?

**Comment by pasha-codefresh** [comment]
Yes, issue can be closed. Okay, we are doing 2.13 release on Monday, Can we cherry-pick it as part of 2.13.1? For example in 1 week after release
