### PR TITLE
fix: put/get ocimetadata to/from redis cache (#27521)

### LINKED ISSUE #27521: 3.3.8: OCI revision metadata fails on page load with multiple repo-server replicas: error creating oci store from cache: open /tmp/_argocd-repo/...: no such file or directory
Checklist:

  - [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
  - [x] I've included steps to reproduce the bug.
  - [x] I've pasted the output of `argocd version`.

  **Describe the bug**

  After upgrading to Argo CD `3.3.8`, OCI-backed Helm applications fail to load revision metadata in the UI on every page load when running multiple `repo-server` replicas.

  The UI shows errors like:

  ```text
  Unable to load data: failed to extract digest metadata for revision "sha256:9bbd48edfdc7c85bc6a17c9e4153b365dcc17723d73b9b385700b3205a968765": error creating oci store from cache: open /tmp/_argocd-repo/36bfedaf-
  4d2e-4f7f-aab7-eee040810dbf: no such file or directory
```

  This appears to affect the revision metadata/details request for OCI charts rather than sync itself.

  We are running Argo CD in HA mode with:

```
  - server.replicas: 3
  - repoServer.replicas: 4
  - controller.replicas: 8
```

  Relevant Helm values:

```
  server:
    replicas: 3

  repoServer:
    replicas: 4
    initContainers:
    - name: download-tools
      image: alpine:3
      command: [ sh, -c ]
      args:
      - |
        cd /var/run/docker-credential-gcr
        wget -qO - https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.8/docker-credential-gcr_linux_amd64-2.1.8.tar.gz | tar xz
        PATH=.:$PATH HOME=/var/run/config docker-credential-gcr configure-docker --include-artifact-registry
        chmod +r /var/run/config/.docker/config.json
    volumeMounts:
    - mountPath: /usr/local/bin/docker-credential-gcr
      name: docker-credential-gcr
      subPath: docker-credential-gcr
      readOnly: true
    - mountPath: /home/argocd/.docker
      name: docker-config
      readOnly: true
    volumes:
    - emptyDir: {}
      name: docker-credential-gcr
    - emptyDir: {}
      name: docker-config
```

  To Reproduce

  1. Deploy Argo CD 3.3.8
  2. Run with multiple repo-server replicas
  3. Configure an application that uses an OCI Helm chart
  4. Open the application details page in the UI
  5. Observe that the revision metadata/details request fails on page load

  Expected behavior

  The application details page should load OCI revision metadata successfully regardless of which repo-server replica handles the request.

  Screenshots

  UI error shown on page load:

```
  Unable to load data: failed to extract digest metadata for revision "sha256:9bbd48edfdc7c85bc6a17c9e4153b365dcc17723d73b9b385700b3205a968765": error creating oci store from cache: open /tmp/_argocd-repo/36bfedaf-
  4d2e-4f7f-aab7-eee040810dbf: no such file or directory
```

Image

  Version

```
argocd: v3.3.8
    BuildDate: 2026-04-21T17:19:47Z
    GitCommit: 7ae7d2cc723f5408b080a31263e705198af08613
    GitTreeState: clean
    GitTag: v3.3.8
    GoVersion: go1.25.5
    Compiler: gc
    Platform: linux/amd64
```

  Logs

```text
  From pod `argocd-repo-server-64b9fddb76-jltsc`:

  {"grpc.code":"Unknown","grpc.component":"server","grpc.error":"failed to extract digest metadata for revision \"sha256:f77ce4bdca89b63bf7fc423f56804580daf83f00783b279f9ec3e70a9946cbe0\": error creating oci store
  from cache: open /tmp/_argocd-repo/6d5cd8b9-57ad-4041-bbf5-28f61605ee7b: no such file or directory","grpc.method":"GetOCIMetadata","grpc.method_type":"unary","grpc.request.deadline":"2026-04-
  23T13:22:22Z","grpc.service":"repository.RepoServerService","grpc.start_time":"2026-04-23T13:21:22Z","grpc.time_ms":"0.182","level":"error","msg":"finished
  call","peer.address":"10.28.128.222:37364","protocol":"grpc","time":"2026-04-23T13:21:22Z"}
```

  Potentially relevant context:

  - The UI bit started after upgrading to 3.3.8 from 3.3.0. However this was reproducible before then by trying to open the sync status menu
  - The missing path is under /tmp/_argocd-repo/..., which seems replica-local/ephemeral
  - This looks HA-sensitive and may involve the RevisionMetadata path for OCI revisions landing on a different repo-server than the one that created/populated the cache

### PR DESCRIPTION
**Pull request by blakepettersson**
Prevents the issue where multiple repo-server pods may or may not have the oci image metadata on local disk. Fixes #27521.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by jacobboykin — APPROVED** [review]
lgtm

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -2730,20 +2730,30 @@ func (s *Service) GetRevisionMetadata(_ context.Context, q *apiclient.RepoServer
 }
 
 func (s *Service) GetOCIMetadata(ctx context.Context, q *apiclient.RepoServerRevisionChartDetailsRequest) (*v1alpha1.OCIMetadata, error) {
+	metadata, err := s.cache.GetOCIMetadata(q.Repo.Repo, q.Revision)
+	if err == nil {
+		log.Infof("oci metadata cache hit: %s/%s", q.Repo.Repo, q.Revision)
```
Comment (nitishfy) [inline reposerver/repository/repository.go:2735]:
```suggestion
		log.Debugf("oci metadata cache hit: %s/%s", q.Repo.Repo, q.Revision)
```

File: reposerver/repository/repository.go [hunk 2]
```diff
@@ -2730,20 +2730,30 @@ func (s *Service) GetRevisionMetadata(_ context.Context, q *apiclient.RepoServer
...
+		return metadata, nil
+	}
+	if errors.Is(err, cache.ErrCacheMiss) {
+		log.Infof("oci metadata cache miss: %s/%s", q.Repo.Repo, q.Revision)
```
Comment (nitishfy) [inline reposerver/repository/repository.go:2739]:
```suggestion
		log.Debugf("oci metadata cache miss: %s/%s", q.Repo.Repo, q.Revision)
```

File: reposerver/repository/repository.go [hunk 3]
```diff
@@ -2752,7 +2762,9 @@ func (s *Service) GetOCIMetadata(ctx context.Context, q *apiclient.RepoServerRev
 		SourceURL:   a["org.opencontainers.image.source"],
 		Version:     a["org.opencontainers.image.version"],
 		Description: a["org.opencontainers.image.description"],
-	}, nil
+	}
+	_ = s.cache.SetOCIMetadata(q.Repo.Repo, q.Revision, metadata)
```
Comment (nitishfy) [inline reposerver/repository/repository.go:2766]: I understand why are we not checking for error here but i think it makes more sense to atleast log a warning so operators know when Redis is unhealthy

**Review by nitishfy — APPROVED** [review]
Overall LGTM!

File: reposerver/repository/repository.go (hunk 1 above)
Comment (gdsoumya) [reply reposerver/repository/repository.go:2735]: +1

File: reposerver/repository/repository.go (hunk 2 above)
Comment (gdsoumya) [reply reposerver/repository/repository.go:2739]: +1

File: reposerver/repository/repository.go (hunk 3 above)
Comment (blakepettersson) [reply reposerver/repository/repository.go:2766]: Makes sense, will fix 👍

**Review by gdsoumya — APPROVED** [review]
LGTM.

As for the info logs we seeem to be doing this for git and helm chart already so not a blocker :
https://github.com/argoproj/argo-cd/blob/cd2255a84bab6f24ecd4068bcb4fb4a7a7c2f441/reposerver/repository/repository.go#L2658-L2665

https://github.com/argoproj/argo-cd/blob/cd2255a84bab6f24ecd4068bcb4fb4a7a7c2f441/reposerver/repository/repository.go#L2762-L2769

**Review by alexmt — APPROVED** [review]
