### PR TITLE
fix(ui): include _-prefixed dirs in embedded assets

### LINKED ISSUE #26568: New icons for custom resource types in UI are 404 not found
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**
Icons for certain custom resources, in our case for Crossplane, are missing. Server requests them and gets a 404:
`https://{our argo host}/assets/images/resources/_.crossplane.io/icon.svg`   <-- 404 not found

**Expected behavior**

Icons are available on the server

**Screenshots**

Image

**Version** 
```
NAME            CHART VERSION   APP VERSION  
argocd/argo-cd  9.4.4           v3.3.2       
```

```shell
$ argocd version
argocd: v3.3.2
  BuildDate: 2026-02-22T12:33:55Z
  GitCommit: 8a3940d8db27928931f0a85ba7c636e54786bddc
  GitTreeState: clean
  GitTag: v3.3.2
  GoVersion: go1.25.5
  Compiler: gc
  Platform: linux/arm64
```

### PR DESCRIPTION
**Pull request by choejwoo**
Closes #26568

Go `//go:embed` excludes files/dirs starting with `_` or `.`, so wildcard-group icon directories like `_.crossplane.io` were not embedded and returned 404s. Use `//go:embed all:dist/app` to include them.

Change `//go:embed dist/app` to `//go:embed all:dist/app` in `ui/embed.go`.
I verified the behavior locally: on `master` the endpoint returned 404, and after this change it returned 200.
```
$ curl -o /dev/null -w "_.crossplane.io: %{http_code}\n" http://localhost:8080/assets/images/resources/_.crossplane.io/icon.svg
[1] 3409
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1736  100  1736    0     0  1382k      0 --:--:-- --:--:-- --:--:-- 1695k
_.crossplane.io: 200
```

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by todaywasawesome — CHANGES_REQUESTED** [review]
Instead, lets just change the filenames.

File: ui/embed.go [hunk 1]
```diff
@@ -4,5 +4,5 @@ import "embed"
 
 // Embedded contains embedded UI resources
 //
-//go:embed dist/app
+//go:embed all:dist/app
```
Comment (agaudreault) [inline ui/embed.go]: Perhaps changing the current `_` pattern is not the best approach.

instead of applying "all" directive to dist/app, can we have 2 paths and the image specific one with something like `//go:embed dist/app all:dist/app/assets/images/resources` ?

**Review by ranakan19 — COMMENTED** [review]
Thanks for the fix!
I see that adding all: fixes the missing _ file, but I wanted to pause on potential reach of this change. I see there are other filenames leading with '_' or '.' . Since Go's default behavior is to skip files starting with . or _ , enabling all: will now embed everything.

Could someone with UI expertise weigh in here? do we have any files in these directories that we should be wary of embedding? maybe @keithchong @pjiang-dev 

I want to ensure we aren't accidentally bloating or over-matching. I like the suggestion by @agaudreault to pick only image specific files instead, if changing the names of files with _ is not the best approach. 
There are atleast two more folders that i can see with _ (_.fluxcd.io, _.knative.dev), maybe following a convention? cc: @crenshaw-dev

File: ui/embed.go (hunk 1 above)
Comment (choejwoo) [reply ui/embed.go]: Thanks for the review!
I updated the embed directives to keep `dist/app` as-is and add `all:` only for `dist/app/assets/images/resources`. 
I built and tested locally and can confirm `Crossplane`/`FluxCD`/`Knative` icons are served correctly.

**Comment by choejwoo** [comment]
@ranakan19 @todaywasawesome
Thanks for the review!

I agree with the scope concern. As suggested by @agaudreault, I updated the embed directives to keep `//go:embed dist/app` as-is and add `all:` only for `dist/app/assets/images/resources`.

The `_.<suffix>` convention comes from the custom resource icon support introduced in #20864, where `_` is used as a filesystem-friendly stand-in for the `*` wildcard (e.g. `*.crossplane.io` → `_.crossplane.io`). In #20864, the only built-in wildcard icon groups currently added are `*.crossplane.io`, `*.fluxcd.io`, and `*.knative.dev`.

**Comment by agaudreault** [comment]
@choejwoo doesn't it need both path? I think there may be other resources embedded in dist/app.

EDIT: Both syntax are valid, nevermind!

**Review by agaudreault — APPROVED** [review]

**Comment by agaudreault** [comment]
@todaywasawesome requiring your review on this since you previously requested changes.

**Review by todaywasawesome — APPROVED** [review]
LGTM!
