### PR TITLE
Sets app status to unknown if there is an error. Closes #2577

### LINKED ISSUE #2577: UI incorrectly mark resources as `Required Pruning`
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

There are two cases when UI incorrectly mark resources as `requires pruning`:
- if repo server goes down after app is deployed then all live objects marked as `requires pruning`
- if resource requires pruning but annotated with `sync-options: Prune=false`. 

**To Reproduce**

1. Deploy and app
2. Stop repo server
3. See all resources marked as `requires pruning`.

**Expected behavior**

**Screenshots**

**Version**

```shell
1.3.0-rc1
```

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

 Closes #2577

Screen Shot 2019-10-28 at 14 12 30

### CODE REVIEW

File: util/resource/prune_test.go [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+	"github.com/stretchr/testify/assert"
+
+	. "github.com/argoproj/argo-cd/test"
+)
+
+func TestNoPrune(t *testing.T) {
+	assert.False(t, NoPrune(nil))
+	assert.False(t, NoPrune(NewPod()))
+	assert.True(t, NoPrune(Annotate(NewPod(), "argocd.argoproj.io/sync-options", "Prune=false")))
+}
```
Comment (golangcibot) [inline util/resource/prune_test.go]: File is not `goimports`-ed with -local github.com/argoproj/argo-cd (from `goimports`)
```suggestion
}
```

**Comment by alexec** [comment]
@alexmt please can you review? I'd like to backport to v1.2.

**Review by alexmt — APPROVED** [review]

**Comment by alexec** [comment]
Back-ported to v1.2 and v1.3
