### PR TITLE
fix: wrong Git file generator globbing (fixes #13284, #13313 and #13686)

### LINKED ISSUE #13284: Git generator does not support submodules
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using Git generator and the the repo contains submodules, the generator does not find files in submodules.

While preparing the repo it uses `git submodule sync --recursive` and `git submodule update --init --recursive` which fetches the actual submodule contents, but the file search for the generator uses `git ls-files --full-name -z -- **/config.json`, which does not search in submodules. The correct command would be `git ls-files --full-name -z --recurse-submodules -- **/config.json`.

As I researched how it works, I found the Git client util command here: https://github.com/argoproj/argo-cd/blob/b38ff175245465f1da07b5f32208c4535ed09602/util/git/client.go#L366

The function does not care if the submodule env is set or not, it does not search for files in submodules.

**To Reproduce**

Example repo structure:
```
├── apps
│   └── app-a (submodule
│       └── config.json
│   └── app-b (submodule
│       └── config.json
└── git-generator-files.yaml
```

Generator:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: submodule-generator
  namespace: argocd
spec:
  generators:
    - git:
        revision: HEAD
        repoURL: git@github.com:user/configs.git
        files:
          - path: "**/config.json"
        template:
          ...
```

See that the generator does not generate any applications.

**Expected behavior**

ApplicatioSet Controller finds files matching the pattern in Git submodlues.

**Screenshots**

**Version**

```shell
argocd: v2.6.3+e05298b
  BuildDate: 2023-02-27T14:40:19Z
  GitCommit: e05298b9c6ab8610104271fa8491f019fee3c587
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2023-04-19T07:53:56Z" level=info msg="git checkout --force 6a9be03e97f4010dec9de29213fe4bde321baf03" dir=/tmp/git@github.com_********* execID=6e70b
time="2023-04-19T07:53:56Z" level=info msg=Trace args="[git checkout --force 6a9be03e97f4010dec9de29213fe4bde321baf03]" dir=/tmp/git@github.com_********* operation_name="exec git" time_ms=6.21754
time="2023-04-19T07:53:56Z" level=info msg="git submodule sync --recursive" dir=/tmp/git@github.com_******* execID=b37c5
time="2023-04-19T07:53:56Z" level=info msg=Trace args="[git submodule sync --recursive]" dir=/tmp/git@github.com_********* operation_name="exec git" time_ms=36.418946
time="2023-04-19T07:53:56Z" level=info msg="git submodule update --init --recursive" dir=/tmp/git@github.com_********* execID=96efd
time="2023-04-19T07:53:57Z" level=info msg=Trace args="[git submodule update --init --recursive]" dir=/tmp/git@github.com_********* operation_name="exec git" time_ms=1406.008223
time="2023-04-19T07:53:57Z" level=info msg="git clean -fdx" dir=/tmp/git@github.com_********* execID=7dce8
time="2023-04-19T07:53:57Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/git@github.com_********** operation_name="exec git" time_ms=2.634399
time="2023-04-19T07:53:57Z" level=info msg="git ls-files --full-name -z -- ./**/config.json" dir=/tmp/git@github.com_******** execID=bd0ff
time="2023-04-19T07:53:57Z" level=info msg=Trace args="[git ls-files --full-name -z -- ./**/config-gap-infra.json]" dir=/tmp/git@github.com_******* operation_name="exec git" time_ms=5.545562
time="2023-04-19T07:53:57Z" level=info msg="generated 0 applications" generator=..."
```

### LINKED ISSUE #13313: Wrong globbing in Git file generator
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The Git file generator currently implements globbing in a way which can trigger errors or catch users off-guard. For example, consider the following repository layout:

```
└── cluster-charts/
    ├── cluster1
    │   ├── mychart/
    │   │   ├── charts/
    │   │   │    └── mysubchart/
    │   │   │        ├── values.yaml
    │   │   │        └── etc…
    │   │   ├── values.yaml
    │   │   └── etc…
    │   └── myotherchart/
    │       ├── values.yaml
    │       └── etc…
    └── cluster2
        └── etc…
```

In `cluster1` we have two charts, one of them with a subchart.

Assuming we need the ApplicationSet to template values in the `values.yaml`, then we need to use a Git file generator instead of a directory generator. The value of the `path` key of the Git file generator should be set to:

```
path: cluster-charts/*/*/values.yaml
```

However, the current implementation will interpret the above pattern as:

```
path: cluster-charts/**/values.yaml
```

Meaning, for `mychart` in `cluster1`, that it will pick up both the chart's `values.yaml` but also the one from its subchart. This will most likely fail, and even if it didn't it would be wrong.

This is the failure users are most likely to encounter but there are multiple other ways this undesirable globbing can fail. For example:

```
path: some-path/*.yaml
```

This will return all YAML files in any directory at any level under `some-path`, instead of only those directly under it.

**To Reproduce**

I have created a repository to reproduce the second type of failure above (https://github.com/Calchan/monorepo-local), based on an actual configuration we currently run in production. The repository layout is in the form:
```prod/clusters/<cluster name>/<namespace>```
We're using a cluster named `local` and deploy in the `default` namespace because it's easier, so the path to our charts in the repository is:
```prod/clusters/local/default/```

In there, we have two types of charts. The first one is in the usual form of a directory with the usual files and sub-directories in it: `Chart.yaml`, `values.yaml`, `templates/`, etc… The example for that is at `prod/clusters/local/default/hello-world/`.

The second type of chart is a simple YAML file pointing to a chart on another directory. The use case here is to store charts that are commonly used in all clusters which increases DRY when dealing with dozens of clusters. In our example we point to the `guestbook` chart at `prod/clusters/virtual/default/`.

Both type of charts are managed by two ApplicationSets at `prod/bootstrap/local/` in the repository. The implementation details can be perused in the example repository but are not important for this bug.

Save the following file as `bootstrap.yaml`:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: argocd:argoproj.io/Application:argocd/bootstrap
  name: bootstrap
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: prod/bootstrap/local
    repoURL: https://github.com/Calchan/monorepo-local.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

Then bootstrap the cluster with `kubectl -n argocd apply -f bootstrap.yaml`.

The regular ApplicationSet generating applications for charts in the directory form will work, but not the one for charts in link YAML files (see screenshots below). In the latter case, the value of the `path` key in the Git file generator spec is set to `prod/clusters/local/*/*.yaml`.

The reason is instead of picking up YAML files directly under `prod/clusters/local/*/` as the ApplicationSet expects, the Git file generator returns all `*.yaml` files at any level under `prod/clusters/local/`.

The log shows this (simplified for readability, see full log below):

```
msg="git ls-files --full-name -z -- prod/clusters/local/*/*.yaml"
msg="prod/clusters/local/default/hello-world/Chart.yaml\x00prod/clusters/local/default/hello-world/templates/deployment.yaml\x00prod/clusters/local/default/hello-world/templates/service.yaml\x00prod/clusters/local/default/hello-world/templates/serviceaccount.yaml\x00prod/clusters/local/default/hello-world/values.yaml\x00prod/clusters/local/default/helm-guestbook.yaml\x00"
```

**Expected behavior**

The `bootstrap-applications-link` ApplicationSet is not in degraded mode and the log shows only this:

```
msg="git ls-files --full-name -z -- prod/clusters/local/*/*.yaml"
msg="prod/clusters/local/default/helm-guestbook.yaml\x00"
```

**Screenshots**

![image](https://user-images.githubusercontent.com/119488/233706403-0d3be8d0-265f-4198-8b4a-ed7e8de8f7dd.png)

![image](https://user-images.githubusercontent.com/119488/233706628-0520ebb6-b1d8-4ac1-a10c-871f6534be13.png)


**Version**

```shell
argocd: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
18:16:51 applicationset-controller | time="2023-04-21T18:16:51Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/https___github.com_calchan_monorepo-local operation_name="exec git" time_ms=1.791212                                                                                                                                                                                                                                                                                    
18:16:51 applicationset-controller | time="2023-04-21T18:16:51Z" level=info msg="git ls-files --full-name -z -- prod/clusters/local/*/*.yaml" dir=/tmp/https___github.com_calchan_monorepo-local execID=80997                                                                                                                                                                                                                                                                                  
18:16:51 applicationset-controller | time="2023-04-21T18:16:51Z" level=debug msg="prod/clusters/local/default/hello-world/Chart.yaml\x00prod/clusters/local/default/hello-world/templates/deployment.yaml\x00prod/clusters/local/default/hello-world/templates/service.yaml\x00prod/clusters/local/default/hello-world/templates/serviceaccount.yaml\x00prod/clusters/local/default/hello-world/values.yaml\x00prod/clusters/local/default/helm-guestbook.yaml\x00" duration=1.531613ms execID=80997                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
18:16:51 applicationset-controller | time="2023-04-21T18:16:51Z" level=info msg=Trace args="[git ls-files --full-name -z -- prod/clusters/local/*/*.yaml]" dir=/tmp/https___github.com_calchan_monorepo-local operation_name="exec git" time_ms=1.618197                                                                                                        
18:16:51 applicationset-controller | time="2023-04-21T18:16:51Z" level=error msg="error generating params" error="unable to process file 'prod/clusters/local/default/hello-world/templates/deployment.yaml': unable to parse file: error converting YAML to JSON: yaml: line 5: did not find expected node content" generator="&{0xc0012eaa50 true}"                                                                                                                                          
18:16:51 applicationset-controller | time="2023-04-21T18:16:51Z" level=error msg="error generating application from params" error="unable to process file 'prod/clusters/local/default/hello-world/templates/deployment.yaml': unable to parse file: error converting YAML to JSON: yaml: line 5: did not find expected node content" generator="{nil nil &GitGenerator{RepoURL:https://github.com/Calchan/monorepo-local.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:prod/clusters/local/*/*.yaml,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,} nil nil nil nil nil nil}"
```

Slack discussion with Michael Crenshaw about this issue:
https://cloud-native.slack.com/archives/C01TSERG0KZ/p1681230308737899

I have a PR coming up.

### LINKED ISSUE #13686: Using the wildcard "*" in "Git Generator: Files" path parameter shouldn't be recursive
# Summary

I am using the ArgoCD `Git Generator: Files` with a wildcard (`*` or `**`) in the `path` parameter. With any of the wildcards the Generator looks for files recursively.

In my opinion, the `*` wildcard should represent a single directory.

# Motivation

If someone is using the `Git Generator: Files` with any of the following `path` parameter:
- `path: examples/**/config.json`
- `path: examples/*/config.json`

In both cases these will also find `config.json` files located at `examples/test/dir/another/config.json`.

I don't think it is expected to have ArgoCD recurse through the directories when `*` is used

# Proposal

- Using `path: examples/**/config.json` should find `examples/test/config.json` and `examples/test/dir/another/config.json`
- Using `path: examples/*/config.json` should find `examples/test/config.json` **BUT NOT** `examples/test/dir/another/config.json`

### PR DESCRIPTION
**Pull request by Calchan**
The current implementation of the Git file generator does undesirable globbing which breaks ApplicationSets in some cases. Please see full description of the issue in https://github.com/argoproj/argo-cd/issues/13313.

I have extensively discussed this issue and PR with @crenshaw-dev on Slack at https://cloud-native.slack.com/archives/C01TSERG0KZ/p1681230308737899.

In this discussion, Micheal suggested I put the fix behind a configuration setting which defaults to the current behavior in case some users were relying on it. I did that, using the configuration for progressive syncs as a model.

Fixes: #13284
Fixes: #13313
Fixes: #13686

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by Calchan** [comment]
It seems checks fail randomly. The first time they ran `Integration tests / Run end-to-end tests (v1.24.3)` failed, and the second time it didn't but `Integration tests / Lint Go code (pull_request)` failed although it passed the first time. There were no changes in between except a rebase of master into my branch for two unrelated commits.

I'm going to push some changes to add some test coverage. Let's see what the checks do this time.

**Comment by Calchan** [comment]
> if I understand right, this would also fix #13284, right?

Actually it won't. With this option it won't do any globbing at all, neither the wrong globbing it did before, nor correct globbing.

But it would if I used the `doublestar` package. That's actually a good idea. I'll try and look into it on Monday.

**Comment by Calchan** [comment]
I have updated the PR to use the `doublestar` package which optionally replaces the overly greedy globbing with correct globbing (instead of optionally disabling it in my initial iteration).

This should now also fix https://github.com/argoproj/argo-cd/issues/13284.

**Comment by Calchan** [comment]
I have rebased and tested this PR over the `release-2.7` branch. It worked as expected.

I have saved the merge in the following branch since there was some manual work:
https://github.com/Calchan/argo-cd/tree/release-2.7

**Comment by Calchan** [comment]
@ishitasequeira I have rebased this PR. Some of it had to be rewritten mostly because of https://github.com/argoproj/argo-cd/issues/10952. It's now ready for review again.

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
Thanks @Calchan for the PR!! I tested the PR and was able to very the new globbing behavior with nested subcharts. 

I went through the code and it looks good as well. Just a minor nit.

File: util/git/client.go [hunk 1]
```diff
@@ -365,14 +366,28 @@ func (m *nativeGitClient) Fetch(revision string) error {
...
 
 // LsFiles lists the local working tree, including only files that are under source control
-func (m *nativeGitClient) LsFiles(path string) ([]string, error) {
-	out, err := m.runCmd("ls-files", "--full-name", "-z", "--", path)
-	if err != nil {
-		return nil, err
+func (m *nativeGitClient) LsFiles(path string, enableNewGitFileGlobbing bool) ([]string, error) {
+	if enableNewGitFileGlobbing {
+		// This is the new way with safer globbing
+		err := os.Chdir(m.root)
```
Comment (crenshaw-dev) [inline util/git/client.go:372]: Is this sufficient to prevent directory enumeration outside the repo dir?

File: applicationset/services/repo_service.go [hunk 2]
```diff
@@ -49,10 +51,11 @@ func (a *argoCDService) GetFiles(ctx context.Context, repoURL string, revision s
 	}
 
 	fileRequest := &apiclient.GitFilesRequest{
-		Repo:             repo,
-		SubmoduleEnabled: a.submoduleEnabled,
-		Revision:         revision,
-		Path:             pattern,
+		Repo:                      repo,
+		SubmoduleEnabled:          a.submoduleEnabled,
+		Revision:	               revision,
```
[the remark this answers is not in the document]
Comment (Calchan) [reply applicationset/services/repo_service.go]: Good catch, thanks. It should be fixed now.

File: util/git/client.go (hunk 1 above)
Comment (Calchan) [reply util/git/client.go:372]: That's a very good remark. I have added code below to filter out returned files that would be coming from outside of the repo, either because of a suitably crafted search pattern or because of a symlink. I know AppSets do not currently follow symlinks, but in case they do in the future (which I hope) then we won't have a hidden security issue. When a file is filtered out from the results a warning is logged.

I have also added unit tests for all that. The old `git ls-files` method will return unresolved symlinks. I didn't changed that. One more unit test checks the new method does not return symlinks that resolve outside of the repo. One last unit test checks files outside of the repo can't be returned using a specifically crafted search pattern.

**Comment by Calchan** [comment]
I have fixed some rebase conflicts, so this PR is ready to merge again.

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @Calchan!
