### PR TITLE
fix: enable logging for the controller runtime

### LINKED ISSUE #19123: [controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

ApplicationSet Controller periodically throws exceptions in the logs

On start
```
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller [controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller Detected at:
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  goroutine 787 [running]:
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  runtime/debug.Stack()
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/log.go:60 +0xcd
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc000621540, 0x0)
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/deleg.go:111 +0x32
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  github.com/go-logr/logr.Logger.Info({{0x556b798?, 0xc000621540?}, 0xc0001577a8?}, {0x400c1ad, 0x36}, {0x0, 0x0, 0x0})
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  	/go/pkg/mod/github.com/go-logr/logr@v1.4.1/logr.go:276 +0x6e
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func3()
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/manager/internal.go:516 +0x53
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  created by sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure in goroutine 1
argo-cd-argocd-applicationset-controller-84bbf4b7d4-wmkp7 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/manager/internal.go:514 +0x265
```

In a few minutes
```
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller [controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller Detected at:
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  goroutine 331 [running]:
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  runtime/debug.Stack()
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/log.go:60 +0xcd
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithValues(0xc000e4fe00, {0xc000d67e20, 0x2, 0x2})
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/deleg.go:168 +0x49
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  github.com/go-logr/logr.Logger.WithValues(...)
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  	/go/pkg/mod/github.com/go-logr/logr@v1.4.1/logr.go:332
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  sigs.k8s.io/controller-runtime/pkg/builder.(*Builder).doController.func1(0xc000d67e00)
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/builder/controller.go:400 +0x193
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000fe0c80, {0x55605d0, 0xc0003056d0}, {0x3a49e80, 0xc000d678a0})
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:306 +0x162
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000fe0c80, {0x55605d0, 0xc0003056d0})
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266 +0x1be
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227 +0x79
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 307
argo-cd-argocd-applicationset-controller-7f8dcc7f76-rsf29 applicationset-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:223 +0x50c
```

**To Reproduce**
- Deploy Argo CD v2.12.0-rc4
- Check ApplicationSet controller logs

**Expected behavior**
No exceptions in the logs

**Version**

```json
{
    "Version": "v2.12.0-rc4+0704aa6",
    "BuildDate": "2024-07-15T17:39:56Z",
    "GitCommit": "0704aa65062b1ff29dc9fb83229ef1db6ecdba2d",
    "GitTreeState": "clean",
    "GoVersion": "go1.22.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.2 2024-05-22T15:19:38Z",
    "HelmVersion": "v3.15.2+g1a500d5",
    "KubectlVersion": "v0.29.6",
    "JsonnetVersion": "v0.20.0"
}

```

### PR DESCRIPTION
**Pull request by fengshunli**
fix https://github.com/argoproj/argo-cd/issues/19123

### CODE REVIEW

File: cmd/argocd-applicationset-controller/commands/applicationset_controller.go [hunk 1]
```diff
@@ -95,6 +96,8 @@ func NewCommand() *cobra.Command {
 			cli.SetLogFormat(cmdutil.LogFormat)
 			cli.SetLogLevel(cmdutil.LogLevel)
 
+			ctrl.SetLogger(zap.New(zap.UseDevMode(true)))
```
Comment (blakepettersson) [inline cmd/argocd-applicationset-controller/commands/applicationset_controller.go:99]: Why add a new dependency? Can you reuse the existing logger impl?
 
```suggestion
			ctrl.SetLogger(logutils.NewLogrusLogger(logutils.NewWithCurrentConfig()))
```

Comment (fengshunli) [reply cmd/argocd-applicationset-controller/commands/applicationset_controller.go]: done

**Review by ishitasequeira — APPROVED** [review]
