### PR TITLE
fix: add all resources in list view

### LINKED ISSUE #7236: UI: List view not showing all resource types
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In the UI choosing the list view to show resources in an application results in a list which shows not all resources in the project. The most prominent resource type missing is "pod". It seems the list view is only showing parent resources.

**To Reproduce**

- Browse ArgoCD UI
- Click on an application
- Choose list view

**Expected behavior**

To see a full list of all deployed resources in this application. In the screenshot you can see an application deployment in the list view instead of the tree view, which is lacking resources. I would expect to find also pod, controllerrevisions, pvcs, ... resources in this list.

image

**Version**

```shell
argocd: v2.1.2+7af9dfb
  BuildDate: 2021-09-02T18:05:23Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

There are no relevant logs for this bug, since it is actually questionable to define this as bug, maybe this could also be an enhancement request.

### PR DESCRIPTION
**Pull request by saumeya**
Note on DCO:
closes #7236 - current resource view doesn't contain all the resources present in the app, this PR adds all those resources

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

resource
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by reginaelyse — APPROVED** [review]
LGTM, the only thing I will mention (which maybe can be made as a separate issue and have its own PR) is that now some resource type names are too long for the space they're given, such as `controllerrevision` and `endpointslice`. Maybe now that we have to account for longer-named resource types being included in the list they should be truncated and have a tooltip.

saumeya-pr7295

**Comment by saumeya** [comment]
Hi, please put this review on hold, i get an issue when i enable SHOW ORPHANED, where the page repeats and entry gets repeated. I am still trying to understand what part of the code is causing it

File: ui/src/app/applications/components/application-details/application-details.tsx [hunk 1]
```diff
@@ -141,23 +141,10 @@ export class ApplicationDetails extends React.Component<RouteComponentProps<{nam
                             const syncResourceKey = new URLSearchParams(this.props.history.location.search).get('deploy');
                             const tab = new URLSearchParams(this.props.history.location.search).get('tab');
```
Comment (keithchong) [inline ui/src/app/applications/components/application-details/application-details.tsx:143]: There's a filter to show orphaned resources. Does this mean they will not be accounted for?

Comment (saumeya) [reply ui/src/app/applications/components/application-details/application-details.tsx:143]: Thanks for catching this Keith, that part of code got lost in resolving merge conflicts. will add it back

File: ui/src/app/applications/components/application-details/application-details.tsx [hunk 2]
```diff
@@ -168,8 +158,19 @@ export class ApplicationDetails extends React.Component<RouteComponentProps<{nam
                                         resource.hook = status.hook;
                                         resource.requiresPruning = status.requiresPruning;
                                     }
-                                    resources.push(resource);
+                                    resources.set(node.uid, resource);
                                 });
+                                const resourcesRef = Array.from(resources.values());
+                                return resourcesRef;
+                            };
+
```
Comment (keithchong) [inline ui/src/app/applications/components/application-details/application-details.tsx:166]: You want to add back the orphaned nodes here, so they will be counted?

Comment (saumeya) [reply ui/src/app/applications/components/application-details/application-details.tsx:166]: only if `pref.orphanedResources` is true i.e. if the check box for showing orphaned is ticked it will get counted, yes.

**Review by alexmt — APPROVED** [review]
Looks good. Also tested and verified that orphaned resources are shown correctly. 

Can you fix linter errors: `yarn lint --fix --project .`
