### PR TITLE
fix: login with apiKey capability

### LINKED ISSUE #4542: I can login to ArgoCD UI even if user is created as apiKey only
Hi,
I've created a local user with apiKey only option but still can login via UI. I've expected that this is not working

**how to reproduce:**
- edit cm/argocd-cm and add a user with apiKey
- change/update password
- login via webUI

**Version**
deployed wiht helm chart:
- chart version: argo-cd-2.9.0
- app version: 1.7.6

```shell
argocd version
argocd: v1.6.2+3d1f37b
  BuildDate: 2020-07-31T23:43:46Z
  GitCommit: 3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:52:04Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

```
time="2020-10-13T07:01:23Z" level=info msg="Notifying 1 settings subscribers: [0xc000c06c60]"
time="2020-10-13T07:01:53Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2020-10-13T07:00:45Z" grpc.time_ms=67978.766 span.kind=server system=grpc
time="2020-10-13T07:01:54Z" level=info msg="Notifying 1 settings subscribers: [0xc000c06c60]"
time="2020-10-13T07:02:14Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims="{\"iat\":1602571629,\"iss\":\"argocd\",\"nbf\":1602571629,\"sub\":\"admin\"}" grpc.request.content= grpc.service=session.SessionService grpc.start_time="2020-10-13T07:02:14Z" span.kind=server system=grpc
time="2020-10-13T07:02:14Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2020-10-13T07:02:14Z" grpc.time_ms=2.184 span.kind=server system=grpc
time="2020-10-13T07:02:15Z" level=info msg="Starting configmap/secret informers"
time="2020-10-13T07:02:15Z" level=info msg="secrets informer cancelled"
time="2020-10-13T07:02:15Z" level=info msg="configmap informer cancelled"
time="2020-10-13T07:02:15Z" level=info msg="Configmap/secret informer synced"
time="2020-10-13T07:02:15Z" level=info msg="Starting configmap/secret informers"
time="2020-10-13T07:02:15Z" level=info msg="secrets informer cancelled"
time="2020-10-13T07:02:15Z" level=info msg="configmap informer cancelled"
time="2020-10-13T07:02:15Z" level=info msg="Configmap/secret informer synced"
time="2020-10-13T07:02:15Z" level=info msg="user 'admin' updated password of user 'foobar'"
time="2020-10-13T07:02:15Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=UpdatePassword grpc.service=account.AccountService grpc.start_time="2020-10-13T07:02:14Z" grpc.time_ms=994.96 span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="Issuing claims: { 0  1602572597 argocd 1602572597 foobar}"
time="2020-10-13T07:03:17Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Create grpc.service=session.SessionService grpc.start_time="2020-10-13T07:03:16Z" grpc.time_ms=826.334 span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="received unary call /cluster.ClusterService/List" grpc.method=List grpc.request.claims="{\"iat\":1602572597,\"iss\":\"argocd\",\"nbf\":1602572597,\"sub\":\"foobar\"}" grpc.request.content= grpc.service=cluster.ClusterService grpc.start_time="2020-10-13T07:03:17Z" span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2020-10-13T07:03:17Z" grpc.time_ms=2.617 span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims="{\"iat\":1602572597,\"iss\":\"argocd\",\"nbf\":1602572597,\"sub\":\"foobar\"}" grpc.request.content= grpc.service=session.SessionService grpc.start_time="2020-10-13T07:03:17Z" span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2020-10-13T07:03:17Z" grpc.time_ms=0.734 span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="received unary call /application.ApplicationService/List" grpc.method=List grpc.request.claims="{\"iat\":1602572597,\"iss\":\"argocd\",\"nbf\":1602572597,\"sub\":\"foobar\"}" grpc.request.content="resourceVersion:\"\" selector:\"\" " grpc.service=application.ApplicationService grpc.start_time="2020-10-13T07:03:17Z" span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=List grpc.service=application.ApplicationService grpc.start_time="2020-10-13T07:03:17Z" grpc.time_ms=2.029 span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="received unary call /project.ProjectService/List" grpc.method=List grpc.request.claims="{\"iat\":1602572597,\"iss\":\"argocd\",\"nbf\":1602572597,\"sub\":\"foobar\"}" grpc.request.content= grpc.service=project.ProjectService grpc.start_time="2020-10-13T07:03:17Z" span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=List grpc.service=project.ProjectService grpc.start_time="2020-10-13T07:03:17Z" grpc.time_ms=7.112 span.kind=server system=grpc
time="2020-10-13T07:03:17Z" level=info msg="received streaming call /application.ApplicationService/Watch" grpc.method=Watch grpc.request.claims="{\"iat\":1602572597,\"iss\":\"argocd\",\"nbf\":1602572597,\"sub\":\"foobar\"}" grpc.request.content="resourceVersion:\"239187\" selector:\"\" " grpc.service=application.ApplicationService grpc.start_time="2020-10-13T07:03:17Z" span.kind=server system=grpc
time="2020-10-13T07:03:38Z" level=info msg="received unary call /session.SessionService/Delete" grpc.method=Delete grpc.request.claims="{\"iat\":1602572597,\"iss\":\"argocd\",\"nbf\":1602572597,\"sub\":\"foobar\"}" grpc.request.content= grpc.service=session.SessionService grpc.start_time="2020-10-13T07:03:38Z" span.kind=server system=grpc
time="2020-10-13T07:03:38Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Delete grpc.service=session.SessionService grpc.start_time="2020-10-13T07:03:38Z" grpc.time_ms=0.457 span.kind=server system=grpc
time="2020-10-13T07:03:38Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2020-10-13T07:03:38Z" span.kind=server system=grpc
time="2020-10-13T07:03:38Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-10-13T07:03:38Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2020-10-13T07:03:38Z" grpc.time_ms=0.974 span.kind=server system=grpc


kubectl get secret/argocd-secret -n argocd -o yaml
apiVersion: v1
data:
  accounts.foobar.password: JDJhJDEwJEkuTnozQzladktObjI3UEV6NTFCNnVGQXk3TjNHS0Zyc3ZDZUlHR3IuRFVvYlNHbnljQUpL
  accounts.foobar.passwordMtime: MjAyMC0xMC0xM1QwNzowMjoxNVo=
  accounts.foobar.tokens: bnVsbA==
  
kubectl get cm/argocd-cm -n argocd -o yaml
apiVersion: v1
data:
  accounts.foobar: apiKey
  admin.enabled: "true"
```

### PR DESCRIPTION
**Pull request by mayzhang2000**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Fixes: #4542

### CODE REVIEW

**Review by jannfis — CHANGES_REQUESTED** [review]

File: util/session/sessionmanager.go [hunk 1]
```diff
@@ -403,6 +404,10 @@ func (mgr *SessionManager) VerifyUsernamePassword(username string, password stri
 		return status.Errorf(codes.Unauthenticated, accountDisabled, username)
 	}
 
+	if !account.HasCapability(settings.AccountCapabilityLogin) {
+		return status.Errorf(codes.Unauthenticated, userDoesNotHaveCapability, username, settings.AccountCapabilityLogin)
```
[the remark this answers is not in the document]
Comment (mayzhang2000) [reply util/session/sessionmanager.go:408]: 👍

File: util/session/sessionmanager.go [hunk 2]
```diff
@@ -400,7 +401,13 @@ func (mgr *SessionManager) VerifyUsernamePassword(username string, password stri
 		return err
 	}
 	if !account.Enabled {
-		return status.Errorf(codes.Unauthenticated, accountDisabled, username)
+		log.Errorf(accountDisabled, username)
+		return InvalidLoginErr
```
Comment (alexmt) [inline util/session/sessionmanager.go:405]: The previous implementation returns the error message that explains why login attempt failed. I think we should preserve that behavior.

File: util/session/sessionmanager.go [hunk 3]
```diff
@@ -400,7 +401,13 @@ func (mgr *SessionManager) VerifyUsernamePassword(username string, password stri
 		return err
 	}
 	if !account.Enabled {
-		return status.Errorf(codes.Unauthenticated, accountDisabled, username)
+		log.Errorf(accountDisabled, username)
```
Comment (alexmt) [inline util/session/sessionmanager.go:404]: We should not print error message if user is trying to login using invalid username/password. Please remove `log.Errorf`

**Review by alexmt — CHANGES_REQUESTED** [review]

File: util/session/sessionmanager.go (hunk 2 above)
Comment (jannfis) [reply util/session/sessionmanager.go]: I was thinking of `return status.Errorf(codes.Unauthenticated, invalidLoginError, username)` here.

File: util/session/sessionmanager.go (hunk 3 above)
Comment (jannfis) [reply util/session/sessionmanager.go]: And here also, a `return status.Errorf(codes.Unauthenticated, invalidLoginError, username)`. In both cases (this and the above one) I think we should log the error (i.e. whether account is disabled, or login not allowed) to prevent user enumeration (i.e. you can enumerate users which have apiKey permissions this way)

**Review by alexmt — APPROVED** [review]
LGTM!

**Review by jannfis — APPROVED** [review]
LGTM, too. And sorry again for confusion.

**Comment by mayzhang2000** [comment]
Thank you @jannfis and @alexmt for your review!
