### PR TITLE
fix(appset): bitbucket server scm provider EOF on empty repo

### LINKED ISSUE #12079: Bitbucket Server SCM provider fails to fetch repository list.
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The Bitbucket server scm provider fails to query project for repos. The error is not very descriptive: `error listing repos: EOF`. I've tried using the Bitbucket Golang library used by ArgoCD and a request using curl. In both cases  it works as expected, so I assume something is wrong on the application set controller side or my YAML configuration.

**To Reproduce**

**NOTE:** I've substituted sensitive information with placeholders

The following application set manifest was applied:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: repo-appset
spec:
  generators:
    - scmProvider:
        cloneProtocol: https
        bitbucketServer:
          project: MYPROJECT
          api: https://my.server.com/rest
          allBranches: true
          basicAuth:
            username: my-username
            passwordRef:
              secretName: bitbucket-token
              key: password
  template:
    metadata:
      name: "{{ repository }}-{{ branch }}"
    spec:
      source:
        helm:
          releaseName: "test-app-{{ branch }}"
        repoURL: "{{ url }}"
        targetRevision: "{{ branch }}"
        path: charts/test-app
      project: default
      destination:
        server: in-cluster
        namespace: "{{ branch }}"
```

**Expected behavior**

A list of repositories residing in that project should be returned with no EOF errors.

**Version**

```shell
argocd: v2.5.7+e0ee345.dirty
  BuildDate: 2023-01-18T04:28:20Z
  GitCommit: e0ee3458d0921ad636c5977d96873d18590ecf1a
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

**NOTE:** I've substituted sensitive information with placeholders

```
time="2023-01-23T11:42:17Z" level=error msg="error generating application from params" error="error listing repos: EOF" generator="{nil nil nil &SCMProviderGenerator{Github:nil,Gitlab:nil,Bitbucket:nil,BitbucketServer:&SCMProviderGeneratorBitbucketServer{Project:MYPROJECT,API:https://my.server.com/rest,BasicAuth:&BasicAuthBitbucketServer{Username:my-username,PasswordRef:&SecretRef{SecretName:bitbucket-token,Key:password,},},AllBranches:true,},Gitea:nil,AzureDevOps:nil,Filters:[]SCMProviderGeneratorFilter{},CloneProtocol:https,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:ApplicationSource{RepoURL:,Path:,TargetRevision:,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,},Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,},},} nil nil nil nil nil}"
```

### PR DESCRIPTION
**Pull request by jjsiv**
Fixes #12079, #9845
The b.client.DefaultApi.GetDefaultBranch(org, repo) call in BitbucketServer SCM provider generator will return a nil response and EOF err if the queried repository is empty (without a default branch set). This seems to go against what the Bitbucket docs say - that an empty repo with no default branch should return code 204 (https://docs.atlassian.com/bitbucket-server/rest/7.1.1/bitbucket-rest.html#idp205). Ultimately this might be a bug in the library used but this PR introduces handling for this case.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
Thanks @jjsiv for the PR!! The changes look good!! Can you fix the lint errors?

**Comment by jjsiv** [comment]
@ishitasequeira fixed

**Comment by jjsiv** [comment]
@jannfis @ishitasequeira added a unit test - could you please review? Thanks!

**Review by ishitasequeira — APPROVED** [review]

**Review by todaywasawesome — APPROVED** [review]

File: applicationset/services/scm_provider/bitbucket_server.go [hunk 1]
```diff
@@ -183,8 +183,8 @@ func (b *BitbucketServerProvider) listBranches(repo *Repository) ([]bitbucketv1.
 
 func (b *BitbucketServerProvider) getDefaultBranch(org string, repo string) (*bitbucketv1.Branch, error) {
 	response, err := b.client.DefaultApi.GetDefaultBranch(org, repo)
-	if response != nil && response.StatusCode == 404 {
-		// There's no default branch i.e. empty repo, not an error
+	// The API will return 404 if a default branch is set but doesn't exist or nil in case the default branch is not set (empty repo)
+	if (response != nil && response.StatusCode == 404) || (response == nil) {
```
Comment (crenshaw-dev) [inline applicationset/services/scm_provider/bitbucket_server.go:187]: @jjsiv I'm worried that this is going to incorrectly capture instances where there's a proper error (i.e. `response` is nil for some reason _besides_ an empty repo, and `err` contains info about the actual failure).

Can you re-craft the conditions in a way that ensures we're only returning `nil, nil` for the empty repo case?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: applicationset/services/scm_provider/bitbucket_server.go (hunk 1 above)
Comment (jjsiv) [reply applicationset/services/scm_provider/bitbucket_server.go:187]: Right, and it does actually return an error (EOF) alongside a nil response. Perhaps we could explicitly check for that - do you think this would be an appropriate solution?
`if (response != nil && response.StatusCode == 404) || (response == nil && err == io.EOF)`

Comment (crenshaw-dev) [reply applicationset/services/scm_provider/bitbucket_server.go:187]: Yep, that should do it!

**Review by ishitasequeira — APPROVED** [review]
LGTM! @crenshaw-dev PTAL

**Review by crenshaw-dev — APPROVED** [review]
Thanks!
