### PR TITLE
Fixes flaky e2e tests. Closes #2086

### LINKED ISSUE #2086: Fix `TestAutoSyncSelfHealEnabled`
This test is flakey and causes builds to randomly fail. If it is a quick fix, got for it. Otherwise, maybe disable in one PR and fix in another.

See logs below.

I'd note this test is also slow (around 30s, similar to `TestNoLocalSyncWithAutosyncEnabled`), this might indicate it's doing special work. Is it using the commonly used image `alpine:latest`?

https://circleci.com/build-insights/gh/argoproj/argo-cd/master

## Logs

https://circleci.com/gh/argoproj/argo-cd/3281

```
time="2019-08-02T20:17:54Z" level=info msg="kubectl delete ns -l e2e.argoproj.io=true --field-selector status.phase=Active --wait=false" dir= execID=MSUbX
time="2019-08-02T20:17:54Z" level=debug msg="namespace \"argocd-e2e-test-auto-sync-self-heal-disabled-uvnys\" deleted\n" duration=99.589104ms execID=MSUbX
time="2019-08-02T20:17:54Z" level=info msg="Starting configmap/secret informers"
time="2019-08-02T20:17:54Z" level=info msg="configmap informer cancelled"
time="2019-08-02T20:17:54Z" level=info msg="secrets informer cancelled"
time="2019-08-02T20:17:55Z" level=info msg="Configmap/secret informer synced"
time="2019-08-02T20:17:56Z" level=info msg="mkdir -p /tmp/argo-e2e" dir= execID=MNx9V
time="2019-08-02T20:17:56Z" level=debug duration=1.865625ms execID=MNx9V
time="2019-08-02T20:17:56Z" level=info msg="mkdir -p /tmp/argo-e2e/app/config/tls" dir= execID=pGhQQ
time="2019-08-02T20:17:56Z" level=debug duration=1.308222ms execID=pGhQQ
time="2019-08-02T20:17:56Z" level=info msg="mkdir -p /tmp/argo-e2e/app/config/ssh" dir= execID=8BiaR
time="2019-08-02T20:17:56Z" level=debug duration=1.122798ms execID=8BiaR
time="2019-08-02T20:17:56Z" level=info msg="cp -Rf testdata /tmp/argo-e2e/testdata.git" dir= execID=zYj5B
time="2019-08-02T20:17:56Z" level=debug duration=3.840207ms execID=zYj5B
time="2019-08-02T20:17:56Z" level=info msg="chmod 777 ." dir=/tmp/argo-e2e/testdata.git execID=lrX2T
time="2019-08-02T20:17:56Z" level=debug duration=1.049014ms execID=lrX2T
time="2019-08-02T20:17:56Z" level=info msg="git init" dir=/tmp/argo-e2e/testdata.git execID=3zUJ5
time="2019-08-02T20:17:56Z" level=debug msg="Initialized empty Git repository in /tmp/argo-e2e/testdata.git/.git/\n" duration=3.183905ms execID=3zUJ5
time="2019-08-02T20:17:56Z" level=info msg="git add ." dir=/tmp/argo-e2e/testdata.git execID=YGune
time="2019-08-02T20:17:56Z" level=debug duration=12.431201ms execID=YGune
time="2019-08-02T20:17:56Z" level=info msg="git commit -q -m initial commit" dir=/tmp/argo-e2e/testdata.git execID=iWQgW
time="2019-08-02T20:17:56Z" level=debug duration=11.629183ms execID=iWQgW
time="2019-08-02T20:17:56Z" level=info msg="kubectl create ns argocd-e2e-test-auto-sync-self-heal-enabled-pijsb" dir= execID=G08Z8
time="2019-08-02T20:17:56Z" level=debug msg="namespace/argocd-e2e-test-auto-sync-self-heal-enabled-pijsb created\n" duration=102.615689ms execID=G08Z8
time="2019-08-02T20:17:56Z" level=info msg="kubectl label ns argocd-e2e-test-auto-sync-self-heal-enabled-pijsb e2e.argoproj.io=true" dir= execID=HE24h
time="2019-08-02T20:17:56Z" level=debug msg="namespace/argocd-e2e-test-auto-sync-self-heal-enabled-pijsb labeled\n" duration=99.628016ms execID=HE24h
time="2019-08-02T20:17:56Z" level=info msg="clean state" duration=1.665043671s id=test-auto-sync-self-heal-enabled-pijsb name=test-auto-sync-self-heal-enabled
time="2019-08-02T20:17:56Z" level=info msg="../../dist/argocd app create -f /tmp/233010365 --plaintext --server localhost:8080 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjQ3NzcwNjMsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU2NDc3NzA2Mywic3ViIjoiYWRtaW4ifQ.i3Wf-WBsvIGxknFlbi3nrE7HCXRnQoIYPBXbcbsfjnY --insecure" dir= execID=VN4v6
time="2019-08-02T20:17:56Z" level=debug msg="application 'test-auto-sync-self-heal-enabled' created\n" duration=216.317011ms execID=VN4v6
time="2019-08-02T20:17:56Z" level=info msg="polling for expectation" message="found success with message 'application 'test-auto-sync-self-heal-enabled' created'" state=succeeded
time="2019-08-02T20:17:56Z" level=info msg="polling for expectation" message="sync status to be Synced, is " state=pending
time="2019-08-02T20:17:59Z" level=info msg="polling for expectation" message="sync status to be Synced, is Synced" state=succeeded
time="2019-08-02T20:17:59Z" level=info msg="polling for expectation" message="sync status to be Synced, is Synced" state=succeeded
time="2019-08-02T20:17:59Z" level=info msg=patching jsonPatch="[{\"op\": \"replace\", \"path\": \"/spec/revisionHistoryLimit\", \"value\": \"badValue\"}]" path=guestbook/guestbook-ui-deployment.yaml
time="2019-08-02T20:17:59Z" level=info msg="converting YAML to JSON"
time="2019-08-02T20:17:59Z" level=info msg=JSON bytes="{\"apiVersion\":\"apps/v1beta2\",\"kind\":\"Deployment\",\"metadata\":{\"name\":\"guestbook-ui\"},\"spec\":{\"replicas\":0,\"revisionHistoryLimit\":3,\"selector\":{\"matchLabels\":{\"app\":\"guestbook-ui\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"guestbook-ui\"}},\"spec\":{\"containers\":[{\"image\":\"gcr.io/heptio-images/ks-guestbook-demo:0.2\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"guestbook-ui\",\"ports\":[{\"containerPort\":80}]}]}}}}"
time="2019-08-02T20:17:59Z" level=info msg="converting JSON back to YAML"
time="2019-08-02T20:17:59Z" level=info msg="git diff" dir=/tmp/argo-e2e/testdata.git execID=4InHJ
time="2019-08-02T20:17:59Z" level=debug msg="diff --git a/guestbook/guestbook-ui-deployment.yaml b/guestbook/guestbook-ui-deployment.yaml\nindex 1d7f77b..371ef70 100644\n--- a/guestbook/guestbook-ui-deployment.yaml\n+++ b/guestbook/guestbook-ui-deployment.yaml\n@@ -4,7 +4,7 @@ metadata:\n   name: guestbook-ui\n spec:\n   replicas: 0\n-  revisionHistoryLimit: 3\n+  revisionHistoryLimit: badValue\n   selector:\n     matchLabels:\n       app: guestbook-ui\n" duration=10.925066ms execID=4InHJ
time="2019-08-02T20:17:59Z" level=info msg="git commit -am patch" dir=/tmp/argo-e2e/testdata.git execID=ijC86
time="2019-08-02T20:17:59Z" level=debug msg="[master 7ded92e] patch\n 1 file changed, 1 insertion(+), 1 deletion(-)\n" duration=12.419827ms execID=ijC86
time="2019-08-02T20:17:59Z" level=info msg="../../dist/argocd app get test-auto-sync-self-heal-enabled --refresh --plaintext --server localhost:8080 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjQ3NzcwNjMsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU2NDc3NzA2Mywic3ViIjoiYWRtaW4ifQ.i3Wf-WBsvIGxknFlbi3nrE7HCXRnQoIYPBXbcbsfjnY --insecure" dir= execID=Wz1ot
time="2019-08-02T20:18:00Z" level=debug msg="Name:               test-auto-sync-self-heal-enabled\nProject:            default\nServer:             https://kubernetes.default.svc\nNamespace:          argocd-e2e-test-auto-sync-self-heal-enabled-pijsb\nURL:                http://localhost:8080/applications/test-auto-sync-self-heal-enabled\nRepo:               file:///tmp/argo-e2e/testdata.git\nTarget:             \nPath:               guestbook\nSync Policy:        Automated\nSync Status:        OutOfSync from  (7ded92e)\nHealth Status:      Healthy\n\nGROUP  KIND        NAMESPACE                                          NAME          STATUS     HEALTH   HOOK  MESSAGE\n       Service     argocd-e2e-test-auto-sync-self-heal-enabled-pijsb  guestbook-ui  Synced     Healthy        \napps   Deployment  argocd-e2e-test-auto-sync-self-heal-enabled-pijsb  guestbook-ui  OutOfSync  Healthy        \n" duration=551.737247ms execID=Wz1ot
time="2019-08-02T20:18:00Z" level=info msg="polling for expectation" message="found success with message 'Name:               test-auto-sync-self-heal-enabled\nProject:            default\nServer:             https://kubernetes.default.svc\nNamespace:          argocd-e2e-test-auto-sync-self-heal-enabled-pijsb\nURL:                http://localhost:8080/applications/test-auto-sync-self-heal-enabled\nRepo:               file:///tmp/argo-e2e/testdata.git\nTarget:             \nPath:               guestbook\nSync Policy:        Automated\nSync Status:        OutOfSync from  (7ded92e)\nHealth Status:      Healthy\n\nGROUP  KIND        NAMESPACE                                          NAME          STATUS     HEALTH   HOOK  MESSAGE\n       Service     argocd-e2e-test-auto-sync-self-heal-enabled-pijsb  guestbook-ui  Synced     Healthy        \napps   Deployment  argocd-e2e-test-auto-sync-self-heal-enabled-pijsb  guestbook-ui  OutOfSync  Healthy        '" state=succeeded
time="2019-08-02T20:18:00Z" level=info msg="polling for expectation" message="sync status to be OutOfSync, is OutOfSync" state=succeeded
time="2019-08-02T20:18:00Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
time="2019-08-02T20:18:03Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
time="2019-08-02T20:18:06Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
time="2019-08-02T20:18:09Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
time="2019-08-02T20:18:12Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
time="2019-08-02T20:18:15Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
time="2019-08-02T20:18:18Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
time="2019-08-02T20:18:21Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
time="2019-08-02T20:18:24Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
time="2019-08-02T20:18:27Z" level=info msg="polling for expectation" message="condition {SyncError Failed sync attempt} in []" state=pending
app_autosync_test.go:65: timeout waiting, condition {SyncError Failed sync attempt} in []
```

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

File: test/e2e/hook_test.go [hunk 1]
```diff
@@ -295,6 +299,7 @@ func TestHookDeleteBeforeCreation(t *testing.T) {
 }
 
 func getCreationTimestamp() (string, error) {
+	FailOnErr(Run(".", "kubectl", "-n", DeploymentNamespace(), "get", "all"))
```
Comment (alexec) [inline test/e2e/hook_test.go]: this is diagnostics

**Review by alexmt — APPROVED** [review]
