### PR TITLE
fix: diffing should not fail if resource fail schema validation

### LINKED ISSUE #18402: Argo CD validating duplicate variables and causing sync issues
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I'm having errors in argocd when using the managedFieldsManagers configuration with duplicated envs in PodSpecTemplate

**To Reproduce**

1. Configure the argocd-cm to add ignore for managedFieldsManagers
  ```yaml
  resource.customizations.ignoreDifferences.all: |-
    managedFieldsManagers:
    - kube-controller-manager
  ```
2. Create the application with with the resources in repository  are with duplicated variables, the first creation of deployment is ok
3. Remove duplicated variables from the repository manifests and sync with removed variable
4. Get the error Sync Application and get error `Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedLive: .spec.template.spec.containers[name="contaienr"].env: duplicate entries for key [name="ENV_TESTE"]`

**Expected behavior**

I expected that argocd would be able to sync the application even with duplicate variables because kubernetes only blocks this operation if applied with Server Side Apply, but even when applied without serverSideApply, argocd returns an error.

Version:
I tested it on the latest stable version and this still happens
```json
{
    "Version": "v2.10.0+2175939",
    "BuildDate": "2024-02-06T14:28:43Z",
    "GitCommit": "2175939ed6156ddd743e60f427f7f48118c971bf",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.0+g3fc9f4b",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

Additional Info:
I investigated this problem in argocd and found that it does not accept this because the functions in the lines below do not have the allowDuplicates option. I performed a test and compiled argocd with this option and the duplicate variables error does not occur.

https://github.com/argoproj/argo-cd/blob/2175939ed6156ddd743e60f427f7f48118c971bf/util/argo/managedfields/managed_fields.go#L94
https://github.com/argoproj/argo-cd/blob/2175939ed6156ddd743e60f427f7f48118c971bf/util/argo/managedfields/managed_fields.go#L99

code

### PR DESCRIPTION
**Pull request by alexmt**
Closes https://github.com/argoproj/argo-cd/issues/18402

When Argo CD is configured to ignore differences using `managedFieldsManagers`, the controller unnecessarily applies schema validation to known k8s types and fails if the object is invalid.  Instead controller should just skip diff normalization so that user can see the diff

### CODE REVIEW

**Review by todaywasawesome — APPROVED** [review]
Looks good, thanks for adding tests already.

File: util/argo/managedfields/managed_fields.go [hunk 1]
```diff
@@ -28,12 +28,14 @@ func Normalize(live, config *unstructured.Unstructured, trustedManagers []string
 
 	liveCopy := live.DeepCopy()
 	configCopy := config.DeepCopy()
+	normalized := false
+
 	results, err := newTypedResults(liveCopy, configCopy, pt)
+	// error might happen if the resources are not parsable and so cannot be normalized
 	if err != nil {
-		return nil, nil, fmt.Errorf("error building typed results: %w", err)
+		return liveCopy, configCopy, nil
```
Comment (ishitasequeira) [inline util/argo/managedfields/managed_fields.go:36]: As we are not returning the error anymore, it might be helpful to log the error message here for debugging.

**Review by ishitasequeira — COMMENTED** [review]
Overall PR looks good. Just 1 comment to log the error.

File: util/argo/managedfields/managed_fields.go (hunk 1 above)
Comment (alexmt) [reply util/argo/managedfields/managed_fields.go:38]: Agreed -  I've added logging! Used debug level since this method will be executed on each app reconciliation and might produce a lot of noise in logs.

**Comment by alexmt** [comment]
Thank you for review @ishitasequeira ! PTAL

File: util/argo/managedfields/managed_fields.go (hunk 1 above)
Comment (ishitasequeira) [reply util/argo/managedfields/managed_fields.go:38]: Debug sounds good!!

**Review by ishitasequeira — APPROVED** [review]
Looks good!!

**Comment by blakepettersson** [comment]
Does this need to be cherry-picked into < 2.12 releases as well?

**Comment by alexmt** [comment]
@blakepettersson , yes - it is pretty old bug. Created PRs for 2.10 https://github.com/argoproj/argo-cd/pull/19734 and 2.11 https://github.com/argoproj/argo-cd/pull/19735
