### PR TITLE
fix: trigger ApplicationSet reconciliation for clusters matching cluster generators in matrix or merge generators

### LINKED ISSUE #12542: No ApplicationSet reconciliation triggered for cluster generators in matrix and merge generators
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When updating a cluster in ArgoCD a new reconciliation is triggered for all ApplicationSets with a cluster generator matching this cluster.

But when updating a cluster in ArgoCD no reconciliation is triggered for all ApplicationSets with a matrix or a merge generator with a cluster generator matching the updated cluster.

**To Reproduce**

1. Create two ApplicationSets:
- an ApplicationSet with the cluster generator as 1st level generator:
```yaml
generators:
- clusters:
    selector:
      matchLabels:
        argocd.argoproj.io/secret-type: cluster
 ```
-  an ApplicationSet with a matrix or a merge generator with a cluster generator as a child:
```yaml
generators:
# matrix 'parent' generator
- matrix:
    generators:
      # git generator, 'child' #1
      - git:
          repoURL: https://github.com/argoproj/argo-cd.git
          revision: HEAD
          directories:
            - path: applicationset/examples/matrix/cluster-addons/*
      # cluster generator, 'child' #2
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
```
3. Update a cluster. For instance, set a label.
4. You'll see in applicationset-controller logs that a reconciliation is triggered for the ApplicationSet with the cluster generator but no reconciliation is triggered for ApplicationSet with the matrix generator.

**Expected behavior**

When  a cluster is updated, any ApplicationSet matching the cluster in one of its nested generator should be reconcilied.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:30:45Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.0+acc554f
```

**Logs**

N/A, see reproducing steps.

### PR DESCRIPTION
**Pull request by alexandrevilain**
This PR fixes #12542 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: applicationset/controllers/clustereventhandler.go [hunk 1]
```diff
@@ -82,3 +95,42 @@ func (h *clusterSecretEventHandler) queueRelatedAppGenerators(q addRateLimitingI
...
+	for _, generator := range generators {
+		if h.nestedGeneratorHasClusterGenerator(generator) {
+			return true
+		}
+	}
+	return false
+}
+
+// nestedGeneratorHasClusterGenerator checks if the provided generator has a cluster generator.
+func (h *clusterSecretEventHandler) nestedGeneratorHasClusterGenerator(nested argoprojiov1alpha1.ApplicationSetNestedGenerator) bool {
```
Comment (crenshaw-dev) [inline applicationset/controllers/clustereventhandler.go:110]: Instead of just logging, can we propagate the error up to `queueRelatedAppGenerators` and then log/ignore it there? Just would be nice to consolidate the places where errors are logged/ignored.

File: applicationset/controllers/clustereventhandler.go [hunk 2]
```diff
@@ -82,3 +95,42 @@ func (h *clusterSecretEventHandler) queueRelatedAppGenerators(q addRateLimitingI
...
+	if nested.Clusters != nil {
+		return true
+	}
+
+	if nested.Matrix != nil {
+		nestedMatrix, err := argoprojiov1alpha1.ToNestedMatrixGenerator(nested.Matrix)
+		if err != nil {
+			h.Log.WithError(err).Error("unable to get nested matrix generator")
```
Comment (crenshaw-dev) [inline applicationset/controllers/clustereventhandler.go:118]: Is something like this possible?

```suggestion
			h.Log.WithError(err).Errorf("unable to get nested matrix generator: %w", err)
```

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: applicationset/controllers/clustereventhandler.go (hunk 2 above)
Comment (alexandrevilain) [reply applicationset/controllers/clustereventhandler.go:118]: You mean, removing the `WithError` ? What's the benefit of this ?

Comment (crenshaw-dev) [reply applicationset/controllers/clustereventhandler.go:118]: I'm a fool. There is no benefit, just missed the WithError. Thanks!

Comment (alexandrevilain) [reply applicationset/controllers/clustereventhandler.go:118]: Oh! I see, will be fix with resolution of previous comment. Thx.

**Comment by alexandrevilain** [comment]
Hi @crenshaw-dev ! 
Thanks for the review! All comments have been addressed.

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @alexandrevilain!
