### PR TITLE
fix: evaluate all possible refresh reasons for multi-source apps (#12379)

### LINKED ISSUE #12379: 2.6.1 Multi Source App - Application status / Sync / Refresh
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Application status of multi source Apps in WebUI and ArgoCD CLI doesn't match with live system/deployed resources. 

**To Reproduce**

* Create a multi source Argo App. I created [this one](https://github.com/carslen/LalaLand/blob/main/demo-multi-source.yaml) for testing purpose with sync policy manual.
* `kubectl apply -f demo-multi-source.yaml`
* The app is listed as OutOfSync in WebUI and CLI
```shell
$ argocd app list
NAME             CLUSTER                         NAMESPACE  PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO  PATH  
TARGET
argocd/maria-db  https://kubernetes.default.svc  maria-db   default  OutOfSync  Missing  <none>      <none>
```
* Sync the app (WebUI or CLI). The App will remain OutOfSync in WebUI and CLI, but the resources will created in background:
```shell
$ argocd app list
NAME             CLUSTER                         NAMESPACE  PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO  PATH  TARGET
argocd/maria-db  https://kubernetes.default.svc  maria-db   default  OutOfSync  Missing  <none>      <none>
[~/kind]$ argocd app sync maria-db
TIMESTAMP                  GROUP        KIND       NAMESPACE                  NAME    STATUS    HEALTH        HOOK  MESSAGE
2023-02-09T18:23:27+01:00          ConfigMap        maria-db      maria-db-mariadb  OutOfSync  Missing
2023-02-09T18:23:27+01:00             Secret        maria-db      maria-db-mariadb  OutOfSync  Missing
2023-02-09T18:23:27+01:00            Service        maria-db      maria-db-mariadb  OutOfSync  Missing
2023-02-09T18:23:27+01:00         ServiceAccount    maria-db      maria-db-mariadb  OutOfSync  Missing
2023-02-09T18:23:27+01:00   apps  StatefulSet       maria-db      maria-db-mariadb  OutOfSync  Missing
2023-02-09T18:23:30+01:00          Namespace                          maria-db   Running   Synced              namespace/maria-db created
2023-02-09T18:23:30+01:00   apps  StatefulSet       maria-db      maria-db-mariadb  OutOfSync  Missing              statefulset.apps/maria-db-mariadb created
2023-02-09T18:23:30+01:00         ServiceAccount    maria-db      maria-db-mariadb  OutOfSync  Missing              serviceaccount/maria-db-mariadb created
2023-02-09T18:23:30+01:00             Secret        maria-db      maria-db-mariadb  OutOfSync  Missing              secret/maria-db-mariadb created
2023-02-09T18:23:30+01:00          ConfigMap        maria-db      maria-db-mariadb  OutOfSync  Missing              configmap/maria-db-mariadb created
2023-02-09T18:23:30+01:00            Service        maria-db      maria-db-mariadb  OutOfSync  Missing              service/maria-db-mariadb created
[~/kind]$ argocd app list
NAME             CLUSTER                         NAMESPACE  PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO  PATH  TARGET
argocd/maria-db  https://kubernetes.default.svc  maria-db   default  OutOfSync  Missing  <none>      <none>
[~/kind]$ k -n maria-db get all
NAME                     READY   STATUS    RESTARTS   AGE
pod/maria-db-mariadb-0   2/2     Running   0          81s

NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/maria-db-mariadb   ClusterIP   10.96.213.213   <none>        3306/TCP,9104/TCP   81s

NAME                                READY   AGE
statefulset.apps/maria-db-mariadb   1/1     81s
```
* After refreshing the app, WebUI and CLI the created resources appear immediately and the app is in sync again with live system.

https://user-images.githubusercontent.com/28647218/217892299-77374654-8c20-4610-8b31-004a6503b204.mov

If the multi-source app is configured for auto sync, the resources gets created immediately, but the Argo App will remain OutOfSync. If the `values.yaml` changes, an App sync isn't sufficient, refresh is required. If a resource is out of sync and need pruning, then it get even worse, because then a combination of app sync + prune followed by refreshing the app is required. 

**Expected behavior**

App Sync should update the App and update the App status.

**Version**

```shell
argocd: v2.5.6+9db2c94.dirty
  BuildDate: 2023-01-11T01:02:03Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.1+3f143c9
  BuildDate: 2023-02-08T18:51:05Z
  GitCommit: 3f143c9307f99a61bf7049a2b1c7194699a7c21b
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

### PR DESCRIPTION
**Pull request by crenshaw-dev**
The way the "should we refresh the app" logic is currently written, if it's a multi-source app where the sources haven't changed, we just quit.

But there are three other possible reasons the app might need refreshing:
* last refresh is expired
* the destination has changed
* the controller itself has requested a refresh (this is the one we're missing on sync)

I gotta think about how to test this...

Fixes https://github.com/argoproj/argo-cd/issues/12379

### CODE REVIEW

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -183,6 +183,18 @@ type ApplicationSource struct {
 // ApplicationSources contains list of required information about the sources of an application
 type ApplicationSources []ApplicationSource
 
+func (s ApplicationSources) Equals(other ApplicationSources) bool {
+	if len(s) != len(other) {
+		return false
+	}
+	for i := range s {
+		if !s[i].Equals(other[i]) {
```
Comment (leoluz) [inline pkg/apis/application/v1alpha1/types.go:191]: If the 2 `ApplicationSources` being compared have the same elements but in a different order, is this considered to be equal or not? If it does, the code needs to be adapted to address this case.

Comment (crenshaw-dev) [reply pkg/apis/application/v1alpha1/types.go:191]: It's not equal, because that changes the "winner" when there are duplicate resources - the later source always wins.

**Review by leoluz — APPROVED** [review]
LGTM
