### PR TITLE
fix: improves the ui message when an operation is terminated due to controller sync timeout

### LINKED ISSUE #23523: Sync timeout does not work.
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have configured ArgoCD with a Sync timeout 

```
controller.sync.timeout.seconds: 600 # 10 minutes
```
When Application in "Syncing" state reaches 10min threshold, message gets updated with "Operation terminated" but Sync is never gets terminated...

**To Reproduce**

1. Configure Sync timeout:
```
controller.sync.timeout.seconds: 600 # 10 minutes
```

2. Have an application that is stuck in sync due to missing CRD or namespace

**Expected behavior**

After 10minutes application Sync is expected to be **TERMINATED**

**Actual behavior**

Application Sync never gets terminated until I manually click "TERMINATE" button

**Screenshots**

Image

**Version**

3.0.6

### PR DESCRIPTION
**Pull request by ppapapetrou76**
The UI message was misleading when an operation was terminated due to a controller sync timeout, and there were pending retries. 

I'm improving the message to explain to the user why the operation was terminated, as we do in other cases - Attaching also images  after the change 

image

Eventually, the UI will be like this when all retries have been completed

image

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

Closes #23523

### CODE REVIEW

**Review by nitishfy — APPROVED** [review]

**Review by agaudreault — APPROVED** [review]

File: controller/appcontroller.go [hunk 1]
```diff
@@ -1471,7 +1471,7 @@ func (ctrl *ApplicationController) processRequestedAppOperation(app *appv1.Appli
 			} else {
 				state.Phase = synccommon.OperationRunning
 				state.RetryCount++
-				state.Message = fmt.Sprintf("%s. Retrying attempt #%d at %s.", state.Message, state.RetryCount, retryAt.Format(time.Kitchen))
+				state.Message = fmt.Sprintf("%s due to application controller sync timeout. Retrying attempt #%d at %s.", state.Message, state.RetryCount, retryAt.Format(time.Kitchen))
```
Comment (agaudreault) [inline controller/appcontroller.go:1474]: Revisiting this after the refactor to this method on master. It seems like it is adding "due to application controller sync timeout." to every failures, even the ones unrelated to the timeout.
