### PR TITLE
fix(server): make a copy of secret objects when listing from the informers #19913

### LINKED ISSUE #19913: argocd-server panics with concurrent map read and write
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Server is panicking from reading and writing to a map concurrently. I believe it is happening from `github.com/argoproj/argo-cd/v2/util/settings.(*SettingsManager).GetSettings` 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
{
    "Version": "v2.10.6+d504d2b",
    "BuildDate": "2024-04-05T00:27:47Z",
    "GitCommit": "d504d2b1d92f0cf831a124a5fd1a96ee29fa7679",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
}

```

**Logs**

```
time="2024-09-12T02:11:41Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Create grpc.service=session.SessionService grpc.start_time="2024-09-12T02:11:37Z" grpc.time_ms=3804.154 span.kind=server system=grpc
fatal error: concurrent map read and map write

goroutine 872259 [running]:
k8s.io/apimachinery/pkg/labels.Set.Has(0x4105e5?, {0xc0496d15c0?, 0xef?})
	/go/pkg/mod/k8s.io/apimachinery@v0.26.11/pkg/labels/labels.go:53 +0x28
k8s.io/apimachinery/pkg/labels.(*Requirement).Matches(0xc041234ec0, {0x507f4c0, 0xc05e465050})
	/go/pkg/mod/k8s.io/apimachinery@v0.26.11/pkg/labels/selector.go:235 +0xcf
k8s.io/apimachinery/pkg/labels.internalSelector.Matches(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.11/pkg/labels/selector.go:396
k8s.io/client-go/tools/cache.ListAllByNamespace({0x50c3cc0, 0xc00e2028a0}, {0xc000b8fc80, 0xa}, {0x50b4020, 0xc04263d4b8}, 0xc01d322cf8)
	/go/pkg/mod/k8s.io/client-go@v0.26.11/tools/cache/listers.go:89 +0x3fe
k8s.io/client-go/listers/core/v1.secretNamespaceLister.List({{0x50c3cc0?, 0xc00e2028a0?}, {0xc000b8fc80?, 0xc00e2028a0?}}, {0x50b4020?, 0xc04263d4b8?})
	/go/pkg/mod/k8s.io/client-go@v0.26.11/listers/core/v1/secret.go:83 +0x69
github.com/argoproj/argo-cd/v2/util/settings.(*SettingsManager).GetSettings(0xc000c5e780)
	/go/src/github.com/argoproj/argo-cd/util/settings/settings.go:1283 +0x1fd
github.com/argoproj/argo-cd/v2/server.newArgoCDServiceSet.func1()
	/go/src/github.com/argoproj/argo-cd/server/server.go:878 +0x25
github.com/argoproj/argo-cd/v2/server/version.(*Server).Version(0xc000b2cff0, {0x50a8638, 0xc037878a80}, 0x0?)
	/go/src/github.com/argoproj/argo-cd/server/version/version.go:32 +0x69
github.com/argoproj/argo-cd/v2/pkg/apiclient/version._VersionService_Version_Handler.func1({0x50a8638, 0xc037878a80}, {0x3892f40?, 0xc0378785a0})
	/go/src/github.com/argoproj/argo-cd/pkg/apiclient/version/version.pb.go:279 +0x72
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.PanicLoggerUnaryServerInterceptor.func19({0x50a8638?, 0xc037878a80?}, {0x3892f40?, 0xc0378785a0?}, 0xc01d323118?, 0xc04b0012c0?)
	/go/src/github.com/argoproj/argo-cd/util/grpc/grpc.go:31 +0x8c
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc037878a80?}, {0x3892f40?, 0xc0378785a0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ErrorCodeGitUnaryServerInterceptor.func18({0x50a8638?, 0xc037878a80?}, {0x3892f40?, 0xc0378785a0?}, 0x0?, 0xc01d323120?)
	/go/src/github.com/argoproj/argo-cd/util/grpc/errors.go:108 +0x2a
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc037878a80?}, {0x3892f40?, 0xc0378785a0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ErrorCodeK8sUnaryServerInterceptor.func17({0x50a8638?, 0xc037878a80?}, {0x3892f40?, 0xc0378785a0?}, 0xc03b9c4340?, 0xc03cd59a00?)
	/go/src/github.com/argoproj/argo-cd/util/grpc/errors.go:124 +0x2a
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc037878a80?}, {0x3892f40?, 0xc0378785a0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.PayloadUnaryServerInterceptor.func16({0x50a8638, 0xc037878a80}, {0x3892f40, 0xc0378785a0}, 0xc044ef61c0, 0xc02bede140)
	/go/src/github.com/argoproj/argo-cd/util/grpc/logging.go:91 +0x15a
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc037878a80?}, {0x3892f40?, 0xc0378785a0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/argoproj/argo-cd/v2/util/grpc.UserAgentUnaryServerInterceptor.func1({0x50a8638, 0xc037878a80}, {0x3892f40, 0xc0378785a0}, 0x50a8638?, 0xc02bede180)
	/go/src/github.com/argoproj/argo-cd/util/grpc/useragent.go:25 +0x7c
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc037878a80?}, {0x3892f40?, 0xc0378785a0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.UnaryServerInterceptor.func15({0x50a8638, 0xc037878900}, {0x3892f40, 0xc0378785a0}, 0xc044ef61c0, 0xc02bede200)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/auth/auth.go:47 +0xb0
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc037878900?}, {0x3892f40?, 0xc0378785a0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3({0x50a8638, 0xc037878900}, {0x3892f40, 0xc0378785a0}, 0x0?, 0xc02bede240)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x7d
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc037878900?}, {0x3892f40?, 0xc0378785a0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1({0x50a8638, 0xc037878660}, {0x3892f40, 0xc0378785a0}, 0xc044ef61c0, 0xc02bede280)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/server_interceptors.go:31 +0xf6
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc037878660?}, {0x3892f40?, 0xc0378785a0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x50a8638, 0xc037878510}, {0x3892f40, 0xc0378785a0}, 0xc044ef61c0, 0xc02bede2c0)
	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.42.0/interceptor.go:344 +0x52b
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc037878510?}, {0x3892f40?, 0xc0378785a0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/argoproj/argo-cd/v2/server.bug21955WorkaroundInterceptor({0x50a8638, 0xc037878510}, {0x3892f40?, 0xc0378785a0?}, 0xc04ae84138?, 0xc02bede300)
	/go/src/github.com/argoproj/argo-cd/server/server.go:1496 +0x503
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21({0x50a8638, 0xc037878510}, {0x3892f40, 0xc0378785a0}, 0xc044ef61c0, 0x3658640?)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x135
github.com/argoproj/argo-cd/v2/pkg/apiclient/version._VersionService_Version_Handler({0x36b20c0?, 0xc000b2cff0}, {0x50a8638, 0xc037878510}, 0xc031cb1800, 0xc001466ab0)
	/go/src/github.com/argoproj/argo-cd/pkg/apiclient/version/version.pb.go:281 +0x135
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001440f00, {0x50a8638, 0xc037878390}, {0x50b8f60, 0xc01c27d520}, 0xc028b678c0, 0xc001466c00, 0x71a5240, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc001440f00, {0x50b8f60, 0xc01c27d520}, 0xc028b678c0)
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x86
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 872258
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x145


goroutine 872357 [runnable]:
vendor/golang.org/x/crypto/cryptobyte.(*String).ReadASN1Element(0xc01f10e720?, 0xc01f10e750?, 0x30)
	/usr/local/go/src/vendor/golang.org/x/crypto/cryptobyte/asn1.go:612 +0x5a
crypto/x509.parseCertificate({0xc002aca800, 0x76d, 0x789})
	/usr/local/go/src/crypto/x509/parser.go:902 +0x665
crypto/x509.ParseCertificate({0xc002aca800?, 0x76d, 0x690?})
	/usr/local/go/src/crypto/x509/parser.go:985 +0x1d
crypto/tls.X509KeyPair({0xc00f842a80?, 0xc02ac26748?, 0x1e?}, {0xc047045c00, 0x68f, 0x690})
	/usr/local/go/src/crypto/tls/tls.go:294 +0x691
github.com/argoproj/argo-cd/v2/util/settings.(*SettingsManager).updateSettingsFromSecret(0xc000c5e780, 0xc02bf2cfc0, 0xc035b5cab0, {0xc02bebfce0, 0x4, 0xc04f4129c0?})
	/go/src/github.com/argoproj/argo-cd/util/settings/settings.go:1535 +0x668
github.com/argoproj/argo-cd/v2/util/settings.(*SettingsManager).GetSettings(0xc000c5e780)
	/go/src/github.com/argoproj/argo-cd/util/settings/settings.go:1290 +0x265
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).Authenticate(0xc00089ea00, {0x50a8638, 0xc04f412870})
	/go/src/github.com/argoproj/argo-cd/server/server.go:1310 +0x24b
github.com/argoproj/argo-cd/v2/server/version.(*Server).AuthFuncOverride(0xc000e26e70?, {0x50a8638?, 0xc04f412870?}, {0x410965?, 0xc001758240?})
	/go/src/github.com/argoproj/argo-cd/server/version/version.go:79 +0x2f
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.UnaryServerInterceptor.func15({0x50a8638, 0xc04f412870}, {0x3892f40, 0xc04f412630}, 0xc054e24260, 0xc04221be00)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/auth/auth.go:40 +0x77
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc04f412870?}, {0x3892f40?, 0xc04f412630?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3({0x50a8638, 0xc04f412870}, {0x3892f40, 0xc04f412630}, 0x0?, 0xc04221be40)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x7d
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc04f412870?}, {0x3892f40?, 0xc04f412630?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1({0x50a8638, 0xc04f412780}, {0x3892f40, 0xc04f412630}, 0xc054e24260, 0xc04221be80)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/server_interceptors.go:31 +0xf6
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc04f412780?}, {0x3892f40?, 0xc04f412630?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x50a8638, 0xc04f4125a0}, {0x3892f40, 0xc04f412630}, 0xc054e24260, 0xc04221bec0)
	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.42.0/interceptor.go:344 +0x52b
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21.1({0x50a8638?, 0xc04f4125a0?}, {0x3892f40?, 0xc04f412630?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
github.com/argoproj/argo-cd/v2/server.bug21955WorkaroundInterceptor({0x50a8638, 0xc04f4125a0}, {0x3892f40?, 0xc04f412630?}, 0xc04e345230?, 0xc04221bf00)
	/go/src/github.com/argoproj/argo-cd/server/server.go:1496 +0x503
github.com/argoproj/argo-cd/v2/server.(*ArgoCDServer).newGRPCServer.ChainUnaryServer.func21({0x50a8638, 0xc04f4125a0}, {0x3892f40, 0xc04f412630}, 0xc054e24260, 0x3658640?)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x135
github.com/argoproj/argo-cd/v2/pkg/apiclient/version._VersionService_Version_Handler({0x36b20c0?, 0xc000b2cff0}, {0x50a8638, 0xc04f4125a0}, 0xc0348cb700, 0xc001466ab0)
	/go/src/github.com/argoproj/argo-cd/pkg/apiclient/version/version.pb.go:281 +0x135
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001440f00, {0x50a8638, 0xc00f36b0e0}, {0x50b8f60, 0xc01f5ce820}, 0xc015c44000, 0xc001466c00, 0x71a5240, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc001440f00, {0x50b8f60, 0xc01f5ce820}, 0xc015c44000)
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x86
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 872356
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x145
```
[argocd-server.log](https://github.com/user-attachments/files/16983334/argocd-server.log)

### PR DESCRIPTION
**Pull request by rumstead**
closes #19913

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by andrii-korotkov-verkada — APPROVED** [review]

File: util/settings/settings.go [hunk 1]
```diff
@@ -1336,13 +1336,20 @@ func (mgr *SettingsManager) GetSettings() (*ArgoCDSettings, error) {
...
+	var secretsCopy []*apiv1.Secret
+	// SecretNamespaceLister lists all Secrets in the indexer for a given namespace.
+	// Objects returned by the lister must be treated as read-only.
+	// To allow us to modify the secrets, make a copy
+	for _, secret := range secrets {
+		secretsCopy = append(secretsCopy, secret.DeepCopy())
+	}
 	if err != nil {
 		return nil, err
 	}
```
Comment (ishitasequeira) [inline util/settings/settings.go:1348]: Can we move this into a common function to avoid duplicity of code?
Also, I think we should check for errors before making the copy.

File: util/db/secrets.go [hunk 2]
```diff
@@ -35,10 +35,18 @@ func (db *db) listSecretsByType(types ...string) ([]*apiv1.Secret, error) {
...
+	// SecretNamespaceLister lists all Secrets in the indexer for a given namespace.
+	// Objects returned by the lister must be treated as read-only.
+	// To allow us to modify the secrets, make a copy
+	for _, secret := range secrets {
+		sc := secret.DeepCopy()
+		secretsCopy = append(secretsCopy, sc)
+	}
 	if err != nil {
 		return nil, err
 	}
```
Comment (ishitasequeira) [inline util/db/secrets.go:48]: Same here.

File: util/settings/settings.go (hunk 1 above)
Comment (rumstead) [reply util/settings/settings.go:1348]: yes good catch thank you!

File: util/util.go [hunk 3]
```diff
@@ -16,3 +18,18 @@ func MakeSignature(size int) ([]byte, error) {
 	b = []byte(base64.StdEncoding.EncodeToString(b))
 	return b, err
 }
+
+// SecretCopy generates a deep copy of a slice containing secrets
+//
+// This function takes a slice of pointers to Secrets and returns a new slice
+// containing deep copies of the original secrets.
+func SecretCopy(secrets []*apiv1.Secret) []*apiv1.Secret {
+	var secretsCopy []*apiv1.Secret
```
Comment (crenshaw-dev) [inline util/util.go:27]: Wanna go ahead and initialize with length since we know the length?

Comment (rumstead) [reply util/util.go:27]: good idea!

**Review by ishitasequeira — APPROVED** [review]
LGTM!!
