### PR TITLE
fix(cli): honor ALL_PROXY and other proxy environment variables

### LINKED ISSUE #22854: `argocd` CLI not using web proxy when `ALL_PROXY` env var is set
I see #10451 was supposed to add proxy support to `argocd` using the `ALL_PROXY` environment variable sometime after 2.9.x. However, it doesn't appear to work in versions I've tested, v2.11.2 and v2.14.11.

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The `ALL_PROXY` environment variable has no effect on the `argocd` CLI app, despite claims in #10451 (requested in #9040).

**To Reproduce**

Tested with `argocd` v2.11.2 and v2.14.11 (latest).

0. Launch a local web proxy such as [Burp Suite Community Edition](https://portswigger.net/burp/releases#community).
1. Verify the proxy works and logs requests:
  `curl -k --proxy localhost:8080 https://duckduckgo.com`
2. Log in to an ArgoCD server (I don't need a proxy for this):
  `argocd login argocd.example.com`
3. Try a simple request using `ALL_PROXY`:
  `ALL_PROXY=localhost:8080 argocd version`
4. Check your proxy logs for evidence of this request. Observe that the CLI didn't use the proxy.

I also tried variants with `ALL_PROXY=http://localhost:8080` and `--loglevel debug`, with no change in behavior or output.

**Expected behavior**

When running a web proxy (tested with Burp Suite on macOS), I expected to see the proxy log a connection from `argocd` to my server when `ALL_PROXY` was set to the proxy's address.

**Version**

The missing server output below contains an error that I'm trying to use the web proxy to troubleshoot. My server version doesn't matter for this issue, but it's v2.11.2.

```shell
argocd: v2.14.11+8283115.dirty
  BuildDate: 2025-04-22T17:03:17Z
  GitCommit: 82831155c2c1873b3b5d19449bfa3970dab9ce24
  GitTreeState: dirty
  GoVersion: go1.24.2
  Compiler: gc
  Platform: darwin/arm64
FATA[0001] rpc error: code = Internal desc = unexpected HTTP status code received from server: 400 (Bad Request); transport: received unexpected content-type "text/html"
```

### PR DESCRIPTION
**Pull request by SinnoLn**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

Closes #22854 

 The PR fixes the Argo CD CLI to properly honor standard proxy environment variables including `ALL_PROXY`, `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` when making network requests.

  Previously, the CLI was not respecting these environment variables, making it difficult to use in corporate environments or networks that require proxy configuration.

### CODE REVIEW

File: util/grpc/grpc_proxy_test.go [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+	for _, tt := range tests {
+		tt := tt
+		t.Run(tt.name, func(t *testing.T) {
+			for _, env := range []string{"ALL_PROXY", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY"} {
+				t.Setenv(env, "")
+			}
+
+			for key, value := range tt.proxyEnv {
+				t.Setenv(key, value)
+			}
```
Comment (nitishfy) [inline util/grpc/grpc_proxy_test.go]: Please put this in a separate helper function.

**Review by nitishfy — CHANGES_REQUESTED** [review]
Left a small comment. Can you please the test file name to `grpc_test.go` instead?

**Review by blakepettersson — APPROVED** [review]
LGTM

File: util/grpc/grpc_proxy_test.go (hunk 1 above)
Comment (SinnoLn) [reply util/grpc/grpc_proxy_test.go]: Thanks for the feedback! I’ll extract this into a helper function. 👍

**Review by nitishfy — APPROVED** [review]
