### PR TITLE
fix(repo-server): completely clean up Git working directory (#3683)

### LINKED ISSUE #3683: Repo-server doesn't fully clean workspace
**Describe the bug**

When I have two Applications with same git repo (but different branch) there is a situation, when repo-server doesn't fully clean working directory of cloned repo. Directories containing git working directory (including .git subdir) are not cleaned when changing branch by repo-server.
The specific situation is when the one branch has git submodule, but the other one doesn't. After switching the branch, the directory with submodule are kept, even when the new branch doesn't contain it.
It is applicable not only to submodule, but to any subdir with regular .git folder. And it is not applicable only when switching branch, but in the case of hard refresh too.

This is a big problem when the git submodule is subchart because after switching to another branch (branch without that subchart) the subchart is also applied and the deployment doesn't correspond to git.

I've checked that repo-server uses "git clean -fdx", when (according to doc) single "-f" preserves untracked nested git repositories. Using double force "git clean -ffdx" solves the issue.
But better solution may be using "--recurse-submodules" git-checkout argument (as stated here: https://git-scm.com/book/en/v2/Git-Tools-Submodules#Issues-with-Submodules).

**To Reproduce**

1. Using argocd-repo-server pod terminal create subdir in the repo working dir
2. Copy any regular .git folder (including content) to that subdir
3. Create another empty subdir (for comparing)
4. Do application Hard refresh in argo web UI
5. Check the repo working dir on repo-server pod
   - subdir contain .git folder remained
   - empty folder is gone

**Expected behavior**

Full working dir cleanup in all situations when the cleanup is in place.

**Version**

```shell
argocd: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:02:57Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:04:43Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

And I have one question: Is it possible to have .gitconfig with "submodule.recurse true" as a workaround?

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
In some cases, for example when a Git submodule wasn’t present anymore in a Git revision, the repo-server didn’t completely clean up its Git working directory.

Fixes #3683

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by blakepettersson** [comment]
Looks good! Would it be possible to add an E2E test that exercises that this works as intended?

**Comment by yann-soubeyrand** [comment]
Hello @blakepettersson, it’s done :wink:

Adding this test showed me that my PR wasn’t correct, as `git checkout --recurse-submodule` failed due to a missing submodule commit. So I introduced a new parameter to the `Fetch()` function to use `git fetch --recurse-submodule` when submodules are enabled, which made me modify a lot of code (essentially tests though). But I finally realized that adding a double `f` argument to the `git clean` command should be sufficient.

File: util/git/client.go [hunk 1]
```diff
@@ -424,7 +424,7 @@ func (m *nativeGitClient) Checkout(revision string, submoduleEnabled bool) error
 			}
 		}
 	}
-	if _, err := m.runCmd("clean", "-fdx"); err != nil {
+	if _, err := m.runCmd("clean", "-ffdx"); err != nil {
```
Comment (blakepettersson) [inline util/git/client.go:427]: Could you add a comment about the double `f`, just so that it's not mistaken for a typo?

Something like (from the `git clean` docs):

>  If the Git configuration variable clean.requireForce is not set to false, git clean will refuse to delete files or directories unless given -f or -i. Git will refuse to modify untracked nested git repositories (directories with a .git subdirectory) unless a second -f is given.

Comment (yann-soubeyrand) [reply util/git/client.go:432]: Sure!

**Review by blakepettersson — APPROVED** [review]
This LGTM at least, good stuff! Will need to add a few more eyes on this though.

**Review by ishitasequeira — APPROVED** [review]
The PR looks good!!

**Review by crenshaw-dev — APPROVED** [review]
lgtm, thanks @yann-soubeyrand!

**Comment by chris-ng-scmp** [comment]
Seems the fix has not released in version 2.5 / 2.6 / 2.7 yet
Currently, my ArgoCD v2.4 can't go for any upgrade due to migrating CMP from configmap to sidecard with the bug.

Keen to see if we can have this fix release for v2.5 as part of the upgrade path from v2.4

**Comment by yann-soubeyrand** [comment]
I don’t know if I can run these commands, but just trying :wink: 

/cherry-pick release-2.7

**Comment by chris-ng-scmp** [comment]
> I don’t know if I can run these commands, but just trying 😉
> 
> /cherry-pick release-2.7

Seems not working... haha

Just checked the new release for both 2.7 / 2.6 / 2.5, not including these changes as well

**Comment by yann-soubeyrand** [comment]
Hi @crenshaw-dev, I can’t issue cherry-pick commands myself, could you do it please? Or tell me if I should open cherry-pick PRs instead.

**Comment by ldacey** [comment]
I believe this is the fix required to get Gitlab to sync properly. Any idea if it will be in 2.8? I just updated to 2.7.9 a bit ago and my Gitlab app has an error

**Comment by blakepettersson** [comment]
It should be @ldacey, try out the latest 2.8-rc and see if that helps.
