### PR TITLE
fix: 21634 Check for semver constraint matching in application webhook handler

### LINKED ISSUE #21634: Gitlab webhook tag push events are ignored when source target revision is a Semver constraint
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using [tag tracking](https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/#tag-tracking) with a SemVer constraint in an Application source, if using a Gitlab [webhook](https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/), then tag push events for new tags which match the constraint do not trigger a resync of the Application.

**To Reproduce**

* Create a code repository in Gitlab with your Kubernetes manifests and add a SemVer tag, eg "1.0.0"
* Create an Application with a target revision set to a version constraint that matches the tag, eg "1.*", and observe that it is synced to "1.0.0".
* Set up a Gitlab webhook which includes tag push events
* Make a change to the code repository and create/push a new tag which matches the source's target revision's constraint, eg "1.1.0"
* Observe that the Application does not resync and remains at "1.0.0" until either you manually sync or after the automated sync interval, at which point it will finally sync to revision "1.1.0".

**Expected behavior**

The Application should sync to revision "1.1.0" almost immediately after the webhook has fired.

**Version**

```shell
argocd: v2.13.2+dc43124
  BuildDate: 2024-12-11T18:37:15Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

We see acknowledgement that the webhook was received, eg

```
Received push event repo: <repo>, revision: <pushed tag>, touchedHead: false
```

but there are no further log messages after that (so, for example, there have been no errors logged).

**Suspected Root Cause**

I suspect the cause is in the `sourceRevisionHasChanged` method in `util/webhook/webhook.go`. For tag push events the `revision` parameter is coming through as the new tag name, but the method (apart from a bit of edge case handling) is essentially just doing a string equality check between this and the source's target revision. This will obviously fail when the revision is something like `1.1.0` but the target revision is `1.*`. Instead, in the event the equality check fails, it ought to additionally try doing a semver constraint check, eg something like the example [here](https://github.com/Masterminds/semver?tab=readme-ov-file#checking-version-constraints).

If this is the underlying cause then the fact we saw this specifically with _Gitlab_ webhooks is likely irrelevant, and I'm guessing the same issue will be seen with other SCM providers' webhooks.

### PR DESCRIPTION
**Pull request by eadred**
The `sourceRevisionHasChanged` method, rather than doing a simple equality check, now checks if the revision supplied by the webhook matches the target revision's semver constraint, if the latter is a constraint.

Fixes https://github.com/argoproj/argo-cd/issues/21634

This change ought to be possible to cherry-pick back as far as 2.12 (support for semver constraints for Git revisions isn't present in 2.11).

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: util/webhook/webhook.go [hunk 1]
```diff
@@ -390,11 +391,33 @@ func sourceRevisionHasChanged(source v1alpha1.ApplicationSource, revision string
...
+		return false
+	}
+
+	version, err := semver.NewVersion(revision)
+	if err != nil {
+		// The new revision is not a valid semver version, so it can't match the constraint.
+		return false
+	}
+
+	return constraint.Check(version)
```
Comment (eadred) [inline util/webhook/webhook.go:420]: I suppose in theory this logic could trigger an unnecessary sync if the new tag is not the latest tag that would match the constraint.

For example, if the constraint was "1.1.*", there was already a tag "1.1.5" which the application was already synced to, and somebody introduces (or moves) a tag "1.1.4". A sync would be triggered, but the outcome would still be that the application would select the "1.1.5" revision.

However, I doubt this is a circumstance that would happen for any sensible SemVer tagging strategy.

**Review by andrii-korotkov-verkada — APPROVED** [review]

**Review by ishitasequeira — APPROVED** [review]
LGTM!! Thanks @eadred !!

**Review by NielsMooren — APPROVED** [review]

**Comment by mariapadh** [comment]
Hi, what are the next steps to getting this progressed or in a release? 

Looking forward to using this as its a key enabler for us.

**Comment by andrii-korotkov-verkada** [comment]
Feel free to bring this up the contributors meeting https://docs.google.com/document/d/1xkoFkVviB70YBzSEa4bDnu-rUZ1sIFtwKKG1Uw8XsY8/edit?tab=t.0
