### PR TITLE
fix: failed to add cluster when the cluster server address is ipv6 (#8204)

### LINKED ISSUE #8204: Unable to add multi cluster with IPv6 , secret name appending "[" with metadata.name from the server url
I am trying ArgoCD to add multiple IPv6 clusters for my POC. I followed the instructions from the docs page.
I ran the below commad
./cli-argocd cluster add  cntxtname  --name sp2 --kubeconfig sp2

I got below error
INFO[0002] ServiceAccount "argocd-manager" created in namespace "kube-system"
INFO[0002] ClusterRole "argocd-manager-role" created
INFO[0002] ClusterRoleBinding "argocd-manager-role-binding" created 
FATA[0003] rpc error: code = InvalidArgument desc = Secret "cluster-[240b-2849613443" is invalid: metadata.name: Invalid value: "cluster-[240b-2849613443": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') 

I could see  service account, cluster-role, cluster-role bindings are created in the target cluster.

Its very clear  bug is  with IPv6 when constructing secret name.

i could see the function URIToSecretName at util/db/secrets.go -> that is taking  input ("cluster", "http://foo") and converting to secretName like "cluster-foo-752281925"
image

In IPv6 case server url will be [240b:x:x:x:x:x:x:x] , its parsing with [240b which causing probelm.

here we need to replace "[" brackets for ipv6 cluster. 
I tried to change the code but it's not reflecting when i tested it. 

I could see one more function for appending "cluster-"
GenerateNewClusterManagerSecret function at /util/clusterauth/clusterauth.go line no 328.

image

**To Reproduce**
- one k8s ipv6 cluster where argocd is deployed.  no problem here. I am able to deploy applications.
- setup another  ipv6 k8s cluster
- download argocd cli 
- run ->  ./argocd-linux-amd64 cluster add  cntxtname  --name sp2 --kubeconfig sp2
- you will get below 
image

**Expected behavior**

Cluster added successfully.

**Screenshots**

**Version**

```shell
![image](https://user-images.githubusercontent.com/30072921/149876120-5196ab7a-f61b-48f9-b18c-2fbbc0669a54.png)

```
OS:
Red Hat Enterprise Linux 7"
argocd: v2.3.0+41fc70d.dirty
argocd-server: v2.2.2+03b17e0

```

### PR DESCRIPTION
**Pull request by huyinhou**
[Fixes #8204 ]

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

File: util/db/secrets.go [hunk 1]
```diff
@@ -155,8 +159,20 @@ func URIToSecretName(uriType, uri string) (string, error) {
 	if err != nil {
 		return "", err
 	}
+	re := regexp.MustCompile(`:\d+$`)
+	host := re.ReplaceAllLiteralString(parsedURI.Host, "")
+	if strings.Contains(host, ":") {
+		addr, err := netip.ParseAddr(host[1 : len(host)-1])
```
Comment (jannfis) [inline util/db/secrets.go:165]: This will crash if `host` is simply `:`

File: util/db/secrets.go [hunk 2]
```diff
@@ -155,8 +159,20 @@ func URIToSecretName(uriType, uri string) (string, error) {
...
+		if err != nil {
+			return "", err
+		}
+		host = strings.ReplaceAll(addr.StringExpanded(), ":", "-")
+	}
+	length := len(host) + len(uriType) + 12
+	if length > 63 {
+		host = host[0 : len(host)-(length-63)]
```
Comment (jannfis) [inline util/db/secrets.go:173]: This will crash if `uriType` is really long and `host` is really short. In general, I do not understand how `length` is calculated here.

**Review by jannfis — CHANGES_REQUESTED** [review]
Thanks for your PR. I have a couple of concerns, see below.

Also, this seems to do some "magic". Can you please inline comment on what all of this is doing, and more important, why?

File: util/db/secrets.go (hunk 2 above)
Comment (huyinhou) [reply util/db/secrets.go]: Thanks for your comment. I removed these codes, the secret name length is limited to 253, it's long enough.

File: util/db/secrets.go [hunk 3]
```diff
@@ -155,8 +157,23 @@ func URIToSecretName(uriType, uri string) (string, error) {
...
+		}
+	} else {
+		last := strings.Index(host, ":")
+		if last >= 0 {
+			host = host[0:last]
+		}
+	}
 	h := fnv.New32a()
 	_, _ = h.Write([]byte(uri))
-	host := strings.ToLower(strings.Split(parsedURI.Host, ":")[0])
```
Comment (jannfis) [inline util/db/secrets.go:160]: Any particular reason we're not using `ToLower` anymore?

File: util/db/secrets.go [hunk 4]
```diff
@@ -155,8 +157,23 @@ func URIToSecretName(uriType, uri string) (string, error) {
...
 	}
+	host := parsedURI.Host
+	if strings.HasPrefix(host, "[") {
+		last := strings.Index(host, "]")
+		if last >= 0 {
+			addr, err := netip.ParseAddr(host[1:last])
+			if err != nil {
+				return "", err
+			}
+			host = strings.ReplaceAll(addr.StringExpanded(), ":", "-")
```
Comment (jannfis) [inline util/db/secrets.go:168]: Any particular reason for using `StringExpanded` instead of just `String` here?

**Review by jannfis — APPROVED** [review]
LGTM, thanks!
