### PR TITLE
fix: UI can now get clusters with slashes in name (#9812)

### LINKED ISSUE #9812: Clusters with slashes in name cannot be fetched by UI
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If a cluster name has a slash in it (and I would guess possibly other characters that need to be URL-encoded), the API will return a 403 instead of information on that cluster, presumably because it is interpreting the extra slashes as part of an API route and not the name of the cluster.

**To Reproduce**

1. Make a cluster with a slash in the name.
2. Deploy an app to it.
3. Open that application's details view in the UI and observe that the cluster name on the Summary tab is `in-cluster (undefined)`.
4. Check the console and verify that you are getting a 403 from the Argo CD API.

**Expected behavior**

The cluster should be fetched as normal.

**Screenshots**

**Version**

```shell
argocd: v2.4.2+c6d0c8b
  BuildDate: 2022-06-21T21:03:41Z
  GitCommit: c6d0c8baaa291cd68465acd7ad6bef58b2b6f942
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by erhudy**
Fixes #9812

If a cluster name has a slash in it, the API would not be able
to fetch that cluster and would display "in-cluster (undefined)"
for that application. This fixes that issue by URI-encoding
the cluster name on the UI side and URI-decoding the cluster name
on the API side.

Signed-off-by: Edmund Rhudy <erhudy@users.noreply.github.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by ashutosh16** [comment]
@erhudy  I tried to reproduce the issue by adding slash in the cluster name `in-cluster` and tested  your  fix in my local with [URL](http://localhost:4000/api/v1/clusters/https%3A%2F%2Fkubernetes.default.svc?id.type=name) but I'm still getting 403. However with type `q.Id.Type = url`, i'm getting the valid response.
Screen Shot 2022-07-26 at 9 19 14 PM

**Comment by erhudy** [comment]
What was the full URL sent to the API server? My fix just urlencodes the cluster name before sending it to the API, and the API urldecodes the cluster name, so if you looked up like `/api/v1/clusters/in/cluster`, that won't work, but `in%2fcluster` would.

**Comment by ashutosh16** [comment]
> What was the full URL sent to the API server? My fix just urlencodes the cluster name before sending it to the API, and the API urldecodes the cluster name, so if you looked up like `/api/v1/clusters/in/cluster`, that won't work, but `in%2fcluster` would.

URL encode works well with cluster name [API](http://localhost:4000/api/v1/clusters/in%2fcluster?id.type=name). Changes LGTM!

**Review by ashutosh16 — APPROVED** [review]
LG

**Review by pasha-codefresh — APPROVED** [review]
LGTM

File: server/cluster/cluster.go [hunk 1]
```diff
@@ -144,7 +145,11 @@ func (s *Server) getCluster(ctx context.Context, q *cluster.ClusterQuery) (*appv
 		q.Server = ""
 		q.Name = ""
 		if q.Id.Type == "name" {
-			q.Name = q.Id.Value
+			name, err := url.QueryUnescape(q.Id.Value)
```
Comment (crenshaw-dev) [inline server/cluster/cluster.go:148]: This would be a breaking API change for all clusters for which `url.QueryUnescape(name) != name`. For example, if my cluster were named (for some weird reason) `in%40cluster`, I'd now get a 403 when requesting that cluster _unless_ I did so with the UI.

Could we introduce a new `name_escaped` to solve the bug and still support other use cases?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: server/cluster/cluster.go (hunk 1 above)
Comment (erhudy) [reply server/cluster/cluster.go]: Got it, I changed the UI to submit with type `name_escaped` instead and adjusted the backend side of things to handle that appropriately while still preserving the original behavior. I also duplicated the test to check that clusters where something in their name could be interpreted as escaped will pass through unmodified.

**Review by blakepettersson — APPROVED** [review]

**Comment by erhudy** [comment]
I built another internal image with the updated PR and deployed it. Everything seems good, continues to handle cluster names properly that do and don't have / in them. @crenshaw-dev could I get your reconsideration?

**Review by crenshaw-dev — APPROVED** [review]
Love it. Thanks for your patience, @erhudy!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.5 for 2.5.3, release-2.4 for 2.4.18, and release-2.3 for 2.3.12.
