### PR TITLE
fix(ui): Cannot add an app that has both name and server destination

### LINKED ISSUE #21437: Application destination can't have both name and server defined
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When we provide both name and server destination, we can't add a new app.

**To Reproduce**
1. Start creating an app in Argo CD
2. Switch to YAML and enter both server and name fields in the destination data
3. Switch to the wizard (save button) and try to add an app

**Expected behavior**
The app is created with a visible option (name or URL)

**Screenshots**
image

**Version**
Latest (master)

### PR DESCRIPTION
**Pull request by rpelczar**
Fixes #21437 

In the destination config, before saving, we make sure that there is only one field depending on the dropdown selection (name or URL).

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by blakepettersson — APPROVED** [review]
LGTM

File: ui/src/app/applications/components/application-create-panel/application-create-panel.tsx [hunk 1]
```diff
@@ -170,6 +170,16 @@ export const ApplicationCreatePanel = (props: {
         }
     }
 
+    const onCreateApp = (data: models.Application) => {
```
Comment (agaudreault) [inline ui/src/app/applications/components/application-create-panel/application-create-panel.tsx:173]: I see logic above from lines 138 to 171 that seems to address this issue. Can you provide an explanation on why these lines are not working correctly?

**Review by agaudreault — CHANGES_REQUESTED** [review]

File: ui/src/app/applications/components/application-create-panel/application-create-panel.tsx (hunk 1 above)
Comment (rpelczar) [reply ui/src/app/applications/components/application-create-panel/application-create-panel.tsx:173]: The logic from these lines doesn't cover this problem - I've added steps to reproduce. You can test it, and you will see the problem is still there.

**Review by alexmt — APPROVED** [review]
LGTM!

**Review by agaudreault — APPROVED** [review]
