### PR TITLE
fix: remove invalid assumption about OCI helm chart path

### LINKED ISSUE #5030: Error creating application from OCI helm chart in ACR
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

Error "unsupported protocol scheme" when creating an application from an OCI helm chart hosted in ACR. I have tried both repos (both give the same error). This repo is confirmed working (attached a screenshot of helm pulling the chart)
See screenshots below

**Expected behavior**

Application is created

**Screenshots**

Names removed for security purposes
argocd repos
argo1

error creating 
argo2

helm pulling the chart
argo4

**Version**

argo3

### LINKED ISSUE #5136: Adding an OCI enabled repository does not support repos without passwords
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When adding a Helm repo that does not require a username/password with --enable-oci I get an error message stating that I must specify a username and password.

**To Reproduce**

The following method works: `argocd repo add  https://kubernetes-charts.banzaicloud.com --type helm --name banzaicloud-stable`
The erros occurs when adding the --enalbe-oci flag: `argocd repo add  https://kubernetes-charts.banzaicloud.com --type helm --name banzaicloud-stable  --enable-oci`
Message: FATA[0000] rpc error: code = Unknown desc = `helm registry login https://kubernetes-charts.banzaicloud.com` failed exit status 1: Error: EOF

**Expected behavior**

_repository 'https://kubernetes-charts.banzaicloud.com' added_ when --enable-oci is specified. 

**Screenshots**

image

**Version**

```shell
argocd: v1.8.1+c2547dc.dirty
  BuildDate: 2020-12-10T05:00:12Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: dirty
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

### PR DESCRIPTION
**Pull request by alexmt**
Closes #5030 
Closes https://github.com/argoproj/argo-cd/issues/5136

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -1303,6 +1303,9 @@ func (s *Service) newHelmClientResolveRevision(repo *v1alpha1.Repository, revisi
 	if helm.IsVersion(revision) {
 		return helmClient, revision, nil
 	}
+	if repo.EnableOCI {
+		return nil, "", errors.New("OCI helm registers don't support semver ranges. Exact revision must be specified.")
+	}
```
Comment (jannfis) [inline reposerver/repository/repository.go:1308]: Is this documented yet?

**Review by jannfis — CHANGES_REQUESTED** [review]
Please see inline comments.

So, for my understanding, previous to this change, OCI repository has been detected by looking at the chart name (i.e. matches `repository/chartname` pattern) and now requires explicit configuration via `enableOCI` setting?

File: util/helm/client.go [hunk 2]
```diff
@@ -98,57 +98,81 @@ func (c *nativeHelmChart) ExtractChart(chart string, version *semver.Version) (s
...
+	defer c.repoLock.Unlock(chartPath)
+
+	// check if tar already downloaded
+	exists, err := fileExist(chartPath)
+	if err != nil {
+		return "", nil, err
+	}
+	if !exists {
+		// download chart using 'helm fetch' command and create tar to avoid re-downloading chart in future
+
```
[the remark this answers is not in the document]
Comment (alexmt) [reply util/helm/client.go]: Great catch. Thank you!

I had a wrong assumption - OCI registry charts have to be cached in tar files same as non-OCI chart (we blow away helm cache including OCI registry cache). Rewrote code so that OCI charts are also stored in pre-defined tar file location that can be deleted by force refresh.

**Comment by alexmt** [comment]
Good point about `repository/chartname` pattern.

The OCI chart can stored in the root directory however only OCI support sub-directories, so we should use it to "guess" that registry is OCI. Updated code accordingly and had to fix https://github.com/argoproj/argo-cd/issues/5136 as well (since we don't have username/password of not registered OCI). 

So now user can use OCI repo without registering it and Argo CD will assume OCI unless chart is stored in root. I think chart is root directory is an edge case - as workaround user can just register repo and specify OCI explicitly.

File: reposerver/repository/repository.go (hunk 1 above)
Comment (alexmt) [reply reposerver/repository/repository.go:1308]: Looks like we don't have documentation about OCI registries. Adding it in next PR and will mention semver restriction.

**Comment by alexmt** [comment]
I think both #5030 and #5136 are pretty critical for OCI helm support. I will cherry-pick the fix to 1.8 unless there are any objections.

File: util/helm/client.go [hunk 3]
```diff
@@ -214,16 +236,19 @@ func (c *nativeHelmChart) TestHelmOCI() (bool, error) {
...
-		return false, err
-	}
-	defer func() {
-		_, _ = helmCmd.Logout(c.repoURL, c.creds)
-	}()
-
-	log.WithFields(log.Fields{"seconds": time.Since(start).Seconds()}).Info("took to test helm oci repository")
+	// Looks like there is no good way to test access to OCI repo if credentials are not provided
+	// just assume it is accessible
+	if c.creds.Username != "" && c.creds.Password != "" {
```
Comment (jannfis) [inline util/helm/client.go:241]: :+1:

**Review by jannfis — APPROVED** [review]
LGTM.

**Comment by jannfis** [comment]
> I think both #5030 and #5136 are pretty critical for OCI helm support. I will cherry-pick the fix to 1.8 unless there are any objections.

You are right. I was first thinking that the change is pretty intrusive for a cherry-pick, but then probably OCI feature is not very usable at the moment and therefore not really used currently. So, I'm all for cherry-picking too.

File: util/helm/client.go [hunk 4]
```diff
@@ -293,6 +318,7 @@ func newTLSConfig(creds Creds) (*tls.Config, error) {
 
 // Normalize a chart name for file system use, that is, if chart name is foo/bar/baz, returns the last component as chart name.
 func normalizeChartName(chart string) string {
+	strings.Join(strings.Split(chart, "/"), "_")
```
Comment (cobexer) [inline util/helm/client.go:321]: @alexmt The return value of `strings.Join()` is not used, is this a bug, or unnecessary code?
/cc @jannfis
