### PR TITLE
fix: support longer http cookie (#2917)

### LINKED ISSUE #2917: "illegal base64 data at input byte 2174" when working with Dex Ldap connector when groupSearch is enabled
I am using ArgoCD version, argocd:v1.3.0, dex version dex:v2.14.0.
Have configured Dex connector for LDAP, and since then I am able to login to Argo.
Noted that the groups of the user are empty:
time="2019-12-25T09:55:13Z" level=info msg="login successful: connector \"ldap\", username=\"MY_USER\", email=\"MY_USER@MY_EMAIL_DOMAIN\", groups=[]" 

Reviewed my dex ldap config and realized the userAttr under groupSearch was wrong, fixed it.
The next LDAP login to ArgoCD, which was supposed to bring the groups along, failed with:

illegal base64 data at input byte 2174

From ArgoCD logs during the login:
```
time="2019-12-25T09:58:56Z" level=info msg="Performing authorization_code flow login: https://myargo.mydomain.com/api/dex/auth?client_id=argo-cd&redirect_uri=https%3A%2F%2Fmyargo.mydomain.com%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=OCdjvsGxRR "
time="2019-12-25T09:58:57Z" level=info msg="Callback: /auth/callback?code=MY_CODE&state=OCdjvsGxRR"
2019/12/25 09:59:57 http: panic serving 10.11.8.1:43130: interface conversion: interface {} is nil, not []interface {}
goroutine 307362 [running]:
net/http.(*conn).serve.func1(0xc000d6f400)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x1a1c8c0, 0xc000e6fbc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/argoproj/argo-cd/util/webhook.affectedRevisionInfo(0x1b39700, 0xc00038a780, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/util/webhook/webhook.go:116 +0xce9
github.com/argoproj/argo-cd/util/webhook.(*ArgoCDWebhookHandler).HandleEvent(0xc0003785f0, 0x1b39700, 0xc00038a780)
	/go/src/github.com/argoproj/argo-cd/util/webhook/webhook.go:144 +0x50
github.com/argoproj/argo-cd/util/webhook.(*ArgoCDWebhookHandler).Handler(0xc0003785f0, 0x20042e0, 0xc000e30b60, 0xc001612600)
	/go/src/github.com/argoproj/argo-cd/util/webhook/webhook.go:217 +0x16f
net/http.HandlerFunc.ServeHTTP(0xc000791c10, 0x20042e0, 0xc000e30b60, 0xc001612600)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000340500, 0x20042e0, 0xc000e30b60, 0xc001612600)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
github.com/argoproj/argo-cd/server.(*bug21955Workaround).ServeHTTP(0xc00037a2e0, 0x20042e0, 0xc000e30b60, 0xc001612600)
	/go/src/github.com/argoproj/argo-cd/server/server.go:831 +0x13d
github.com/argoproj/argo-cd/server.(*handlerSwitcher).ServeHTTP(0xc0005308a0, 0x20042e0, 0xc000e30b60, 0xc001612600)
	/go/src/github.com/argoproj/argo-cd/server/server.go:808 +0x16d
net/http.serverHandler.ServeHTTP(0xc000985380, 0x20042e0, 0xc000e30b60, 0xc001612600)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000d6f400, 0x200a820, 0xc0006dd2c0)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```
Wondering whether this has to do with the amount of the groups....?
Is it related to https://github.com/argoproj/argo-cd/issues/1103?
Unfortunately, I do not know any user who has few groups in our org so couldn't try it with one..

### PR DESCRIPTION
**Pull request by kshamajain99**
Signed-off-by: kshamajain99 <kshamajain99@gmail.com>

closes #2917

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: util/http/http.go [hunk 1]
```diff
@@ -2,27 +2,82 @@ package http
...
-	header := strings.Join(components, "; ")
+	return cookies
+}
+
+// JoinCookies combines chunks of cookie based on key as prefix.
+// It returns cookie value as string. cookieString is of format
+// key1=value1; key2=value2; key3=value3
+func JoinCookies(key string, cookieString string) string {
+	cookies := make(map[string]string)
+	for _, cookie := range strings.Split(cookieString, ";") {
```
Comment (alexmt) [inline util/http/http.go:60]: Reproduce an issue:

* User is part of many groups. Login to Argo CD and got 2 cookie chunks.
* Remove all groups and login again: small cookie was generated and only first chunk got replaced. So browser has two cookies and second if leftover from first login
* User unable to login anymore

I really want to avoid asking users to clean cookies and try to login again. I would suggest that if cookie is chunked then first part must include information about number of chunks. E.g. `parts=<count>:<token>`

**Review by alexmt — CHANGES_REQUESTED** [review]

File: util/http/http.go (hunk 1 above)
Comment (kshamajain99) [reply util/http/http.go:60]: It's a good idea to add number of chunks in first part. I have added the changes. 

To point out the above issue, I have added code to make sure to clear all cookies with prefix `argocd.token`

File: util/http/http.go [hunk 2]
```diff
@@ -2,27 +2,104 @@ package http
...
+	}
+
+	var sb strings.Builder
+	firstPart, ok := cookies[key]
+	if !ok {
+		return "", fmt.Errorf("failed to retrieve cookie %s", key)
+	}
+	token := strings.Split(firstPart, ":")
+	if len(token) < 2 {
+		return "", fmt.Errorf("invalid cookie for key %s", key)
```
Comment (alexmt) [inline util/http/http.go:84]: For backward compatibility (to support users who manually set cookie in scripts  ) we need to assume one chunk, if number of chunks in not specified in first chunk.

File: server/server.go [hunk 3]
```diff
@@ -933,12 +935,9 @@ func getToken(md metadata.MD) string {
 
 	// check the HTTP cookie
 	for _, t := range md["grpcgateway-cookie"] {
```
Comment (alexmt) [inline server/server.go:937]: The `server.go` filtere cookies, should we do it here as well?

File: server/logout/logout.go [hunk 4]
```diff
@@ -60,18 +61,33 @@ func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
-	if err != nil {
+	cookies := r.Cookies()
+	// filter cookies with prefix common.AuthCookieName
+	var filteredCookies []string
+	for _, cookie := range cookies {
+		if strings.HasPrefix(cookie.Name, common.AuthCookieName) {
+			filteredCookies = append(filteredCookies, fmt.Sprintf("%s=%s", cookie.Name, cookie.Value))
+		}
+	}
+	tokenString, err = httputil.JoinCookies(common.AuthCookieName, strings.Join(filteredCookies, "; "))
```
Comment (alexmt) [inline server/logout/logout.go:72]: Looks like we join cookie into one string and `JoinCookies` immediately split it. Why not just pass list of strings?

**Review by alexmt — CHANGES_REQUESTED** [review]

File: server/logout/logout.go (hunk 4 above)
Comment (kshamajain99) [reply server/logout/logout.go:72]: We can pass the list of strings as well. I kept this format as in server.go we get token in this format from `metadata.MD` https://github.com/argoproj/argo-cd/pull/5497/files?file-filters%5B%5D=.go#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4R938

File: server/server.go (hunk 3 above)
Comment (kshamajain99) [reply server/server.go:937]: I didn't want to add an additional loop here. I will add a filter logic inside `JoinCookies` loop.

Comment (alexmt) [reply server/server.go:942]: Agree. Since `JoinCookies` has filtering now we should remove it in `logout.go` as well https://github.com/argoproj/argo-cd/pull/5497/files#diff-49aa5cdf3cd8adb7bb4d8c1f6fe1cb5a0c665977142b7f33d183ebc4b0b0a1b8R69

File: server/server.go [hunk 5]
```diff
@@ -938,12 +940,9 @@ func getToken(md metadata.MD) string {
...
-		header := http.Header{}
-		header.Add("Cookie", t)
-		request := http.Request{Header: header}
-		token, err := request.Cookie(common.AuthCookieName)
-		if err == nil {
-			tokens = append(tokens, token.Value)
+		token, err := httputil.JoinCookies(common.AuthCookieName, strings.Split(t, ";"))
```
Comment (alexmt) [inline server/server.go:943]: Just discovered that cookie parsing in not just `strings.Split(";")` . The cookie value might has quotes etc. [Stackoverflow](https://stackoverflow.com/questions/28262376/parse-cookie-string-in-golang) suggest this:

```golang
header := http.Header{}
    header.Add("Cookie", rawCookies)
    request := http.Request{Header: header}

    fmt.Println(request.Cookies()) 
```

File: util/http/http.go [hunk 6]
```diff
@@ -2,27 +2,120 @@ package http
...
 	"net/http/httputil"
+	"strconv"
 	"strings"
 
 	log "github.com/sirupsen/logrus"
 )
 
+// max number of chunks a cookie can be broken into. To be compatible with
+// widest range of browsers, we shouldn't create more than 30 cookies per domain
+const maxNumber = 5
```
Comment (alexmt) [inline util/http/http.go:16]: Package name is `http` so it is not just about cookies. Please rename variables to denote this is related to cookies. E.g. `maxCookieNumber`, `maxCookieLength`

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
LGTM. thank you @kshamajain99 !
