### PR TITLE
fix: set HELM_CONFIG_HOME dir for oci registry authentication; fixes: #11284

### LINKED ISSUE #11284: Conflict in OCI helm authentication during force refresh
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

While force refreshing an application in the UI, two calls to the repo server (1. to refresh manifests 2. get app details) race each other, and as the registry login/logout is global they cause either failure to log out, or failure to fetch from server.

**To Reproduce**

Click force refresh in the Application Details page for a OCI Helm application. Watch the reposerver logs, to observe that two helm ExtractChart operations for the same application run in paralel. One of them fails all the time to either log out or fetch.

**Expected behavior**

Log out should not fail. Pull should not throw 401 Unauthenticated.

**Screenshots**
n/a

**Version**

latest

**Logs**

```
time="2022-11-14T04:45:29Z" level=info msg="fetching communication-preferences tags from https://(redacted).dkr.ecr.eu-central-1.amazonaws.com/v2/communication-preferences/tags/list"
time="2022-11-14T04:45:29Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:(redacted).dkr.ecr.eu-central-1.amazonaws.com,Path:,TargetRevision:*,Helm:&ApplicationSourceHelm{ValueFiles:[values-testing-testing20.yaml values-applications-gatekeeper.yaml],Parameters:[]HelmParameter{},ReleaseName:,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,},Kustomize:nil,Directory:nil,Plugin:nil,Chart:apps-testing,}/208.0.0"
time="2022-11-14T04:45:29Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-11-14T04:45:29Z" grpc.time_ms=34.485 span.kind=server system=grpc
time="2022-11-14T04:45:29Z" level=info msg="took to get tags" chart=communication-preferences repo=(redacted).dkr.ecr.eu-central-1.amazonaws.com seconds=0.049296995
time="2022-11-14T04:45:29Z" level=info msg="fetching communication-preferences tags from https://(redacted).dkr.ecr.eu-central-1.amazonaws.com/v2/communication-preferences/tags/list"
time="2022-11-14T04:45:29Z" level=info msg="helm registry login (redacted).dkr.ecr.eu-central-1.amazonaws.com --username ****** --password ******" dir= execID=4b7fc
time="2022-11-14T04:45:29Z" level=info msg="took to get tags" chart=communication-preferences repo=(redacted).dkr.ecr.eu-central-1.amazonaws.com seconds=0.042672384
time="2022-11-14T04:45:29Z" level=info msg="helm registry login (redacted).dkr.ecr.eu-central-1.amazonaws.com --username ****** --password ******" dir= execID=0a9c8
time="2022-11-14T04:45:29Z" level=info msg=Trace args="[helm registry login (redacted).dkr.ecr.eu-central-1.amazonaws.com --username ****** --password ******" dir= operation_name="exec helm" time_ms=131.883468
time="2022-11-14T04:45:29Z" level=info msg="helm pull oci://(redacted).dkr.ecr.eu-central-1.amazonaws.com/communication-preferences --version 2487.0.0 --destination /tmp/94f2e595-6c59-4883-835f-49f123a3e905" dir= execID=23861
time="2022-11-14T04:45:29Z" level=info msg=Trace args="[helm registry login (redacted).dkr.ecr.eu-central-1.amazonaws.com --username ****** --password ******" dir= operation_name="exec helm" time_ms=96.568152
time="2022-11-14T04:45:29Z" level=info msg="helm pull oci://(redacted).dkr.ecr.eu-central-1.amazonaws.com/communication-preferences --version 2487.0.0 --destination /tmp/fcedf43d-273f-43de-b592-bdbfba88b06e" dir= execID=98737
time="2022-11-14T04:45:30Z" level=info msg=Trace args="[helm pull oci://(redacted).dkr.ecr.eu-central-1.amazonaws.com/communication-preferences --version 2487.0.0 --destination /tmp/94f2e595-6c59-4883-835f-49f123a3e905]" dir= operation_name="exec helm" time_ms=338.06943099999995
time="2022-11-14T04:45:30Z" level=info msg="tar -zxvf /tmp/_argocd-repo/09c771eb-348a-453b-ba26-60205c06fbec" dir=/tmp/0a174887-83fe-4e7e-b298-b9eb7f181985 execID=59645
time="2022-11-14T04:45:30Z" level=info msg=Trace args="[tar -zxvf /tmp/_argocd-repo/09c771eb-348a-453b-ba26-60205c06fbec]" dir=/tmp/0a174887-83fe-4e7e-b298-b9eb7f181985 operation_name="exec tar" time_ms=5.098417
time="2022-11-14T04:45:30Z" level=info msg="helm registry logout (redacted).dkr.ecr.eu-central-1.amazonaws.com" dir= execID=7a9b3
time="2022-11-14T04:45:30Z" level=info msg=Trace args="[helm registry logout (redacted).dkr.ecr.eu-central-1.amazonaws.com]" dir= operation_name="exec helm" time_ms=56.433991000000006
time="2022-11-14T04:45:30Z" level=info msg=Trace args="[helm pull oci://(redacted).dkr.ecr.eu-central-1.amazonaws.com/communication-preferences --version 2487.0.0 --destination /tmp/fcedf43d-273f-43de-b592-bdbfba88b06e]" dir= operation_name="exec helm" time_ms=387.687449
time="2022-11-14T04:45:30Z" level=info msg="tar -zxvf /tmp/_argocd-repo/09c771eb-348a-453b-ba26-60205c06fbec" dir=/tmp/751fe005-34aa-4012-8754-655035014d68 execID=0f61f
time="2022-11-14T04:45:30Z" level=info msg="helm template . --name-template communication-preferences --namespace communication-preferences --kube-version 1.23 --set cluster=testing20 --set global.cluster=testing20 --values /tmp/0a174887-83fe-4e7e-b298-b9eb7f181985/communication-preferences/values-testing.yaml ..." dir=/tmp/0a174887-83fe-4e7e-b298-b9eb7f181985/communication-preferences execID=266e5
time="2022-11-14T04:45:30Z" level=info msg=Trace args="[tar -zxvf /tmp/_argocd-repo/09c771eb-348a-453b-ba26-60205c06fbec]" dir=/tmp/751fe005-34aa-4012-8754-655035014d68 operation_name="exec tar" time_ms=16.312111
time="2022-11-14T04:45:30Z" level=info msg="helm registry logout (redacted).dkr.ecr.eu-central-1.amazonaws.com" dir= execID=48a13
time="2022-11-14T04:45:30Z" level=info msg=Trace args="[helm template . --name-template communication-preferences --namespace communication-preferences --kube-version 1.23 --set cluster=testing20 --set global.cluster=testing20 --values /tmp/0a174887-83fe-4e7e-b298-b9eb7f181985/communication-preferences/values-testing.yaml ..." dir=/tmp/0a174887-83fe-4e7e-b298-b9eb7f181985/communication-preferences operation_name="exec helm" time_ms=62.160055
time="2022-11-14T04:45:30Z" level=error msg="`helm registry logout (redacted).dkr.ecr.eu-central-1.amazonaws.com` failed exit status 1: Error: not logged in" execID=48a13
time="2022-11-14T04:45:30Z" level=info msg=Trace args="[helm registry logout (redacted).dkr.ecr.eu-central-1.amazonaws.com]" dir= operation_name="exec helm" time_ms=50.003592
time="2022-11-14T04:45:30Z" level=info msg="helm show values ." dir=/tmp/751fe005-34aa-4012-8754-655035014d68/communication-preferences execID=1d155
```

### PR DESCRIPTION
**Pull request by alexef**
in ExtractChart and TestHelmOCI we "RegistryLogin" and defer "RegistryLogout". by setting the HOME to helmHome (temporary, unique) we avoid one operation from logging out of another one's context.

Signed-off-by: Alex Eftimie <alex.eftimie@getyourguide.com>

Fixes: #11284 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexef** [comment]
Doesn’t solve the issue, needs a bit more investigating

File: util/helm/cmd.go [hunk 1]
```diff
@@ -63,6 +63,8 @@ func (c Cmd) run(args ...string) (string, error) {
 
 	if c.IsHelmOci {
 		cmd.Env = append(cmd.Env, "HELM_EXPERIMENTAL_OCI=1")
+		// set the home for registry login/logout to use it as the registry/config.json location
+		cmd.Env = append(cmd.Env, fmt.Sprintf("HELM_CONFIG_HOME=%s/config", c.helmHome))
```
Comment (jessesuen) [inline util/helm/cmd.go:67]: Looks like this broke when upgrading to Helm v3. If you see above we had set `HELM_HOME`. But in v3 they moved to `HELM_CONFIG_HOME`:

https://helm.sh/docs/topics/v2_v3_migration/#overview-of-helm-3-changes
> v3 configuration no longer uses $HELM_HOME and uses XDG directory specification instead. It is also created on the fly as need be. It is therefore independent of v2 configuration. This is applicable only when both versions are installed on the same system

So I think the proper fix is to replace `HELM_HOME` with `HELM_CONFIG_HOME` above so it works for OCI and non-OCI

**Review by jessesuen — CHANGES_REQUESTED** [review]

File: util/helm/cmd.go (hunk 1 above)
Comment (jessesuen) [reply util/helm/cmd.go:67]: > and uses XDG directory specification instead

It may have been worked for non-OCI because perhaps non-OIC implementation understand XDG directory specification whereas OCI implementation may have not. Regardless, setting `HELM_HOME` has no effect and setting `HELM_CONFIG_HOME` in the common codepath seems like the right thing to do.

**Review by jessesuen — APPROVED** [review]
