### PR TITLE
fix(security): add url validation for help chat (#9956)

### LINKED ISSUE #9956: ADA-ARGO-SA-01: `help.chatUrl` should be validated
It can currently be a `javascript:` link. Only admins can set this value, so it's reasonably safe. But it's probably better to URL validate that value to help admins avoid doing something dangerous.

### PR DESCRIPTION
**Pull request by saumeya**
closes #9956 

Screenshot from 2022-08-21 19-19-31
Signed-off-by: saumeya <saumeyakatyal@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: ui/src/app/ui-banner/ui-banner.tsx [hunk 1]
```diff
@@ -66,6 +68,12 @@ export const Banner = (props: React.Props<any>) => {
                         chatBottomPosition = 85;
                     }
                 }
+                try {
+                    const externalLink = new ExternalLink(chatUrl);
+                    chatUrl = externalLink.ref;
+                } catch (InvalidExternalLinkError) {
+                    chatUrl = 'invalid-url';
```
Comment (crenshaw-dev) [inline ui/src/app/ui-banner/ui-banner.tsx:75]: Could we use `null` instead of a magic string? Effectively the same, just seems a bit more expressive.  :-)

File: ui/src/app/ui-banner/ui-banner.tsx [hunk 2]
```diff
@@ -96,9 +104,17 @@ export const Banner = (props: React.Props<any>) => {
                         {show ? <div className={wrapperClassname}>{props.children}</div> : props.children}
                         {chatUrl && (
                             <div style={{position: 'fixed', right: 10, bottom: chatBottomPosition}}>
-                                <a href={chatUrl} className='argo-button argo-button--special'>
-                                    <i className='fas fa-comment-alt' /> {chatText}
-                                </a>
+                                {chatUrl === 'invalid-url' ? (
+                                    <Tooltip content='Invalid URL provided'>
+                                        <a className='argo-button argo-button--special'>
```
Comment (crenshaw-dev) [inline ui/src/app/ui-banner/ui-banner.tsx:109]: Is there a "disabled" button state we could use to improve the UX a bit?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Thanks for the PR and for your patience on the review @saumeya!

File: ui/src/app/ui-banner/ui-banner.tsx (hunk 2 above)
Comment (saumeya) [reply ui/src/app/ui-banner/ui-banner.tsx]: Added

File: ui/src/app/ui-banner/ui-banner.tsx (hunk 1 above)
Comment (saumeya) [reply ui/src/app/ui-banner/ui-banner.tsx:75]: The null check is added to not render a button when there is no chat url provided. If it is invalid then should we give them a warning/message or remove the button entirely?

Comment (crenshaw-dev) [reply ui/src/app/ui-banner/ui-banner.tsx:75]: Ahh. Yeah, I think leaving the button with a warning message is fine!

**Comment by saumeya** [comment]
@crenshaw-dev is some other change rquired or can this be merged? I can use a variable to validate it - in case magic string is bad practice.

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.3, release-2.5 for 2.5.12, and release-2.4 for 2.4.24.

**Comment by woehrl01** [comment]
@saumeya @crenshaw-dev  This change now results in showing the chat button even though there is no url at all configured
