### PR TITLE
fix(appset): do not trigger reconciliation on appsets not part of allowed namespaces when updating a cluster secret

### LINKED ISSUE #25621: Multiple ArgoCD per cluster - Cluster secret update triggers reconciliations for all appsets, without respecting allowed namespaces
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

When running several ArgoCD in the same Kubernetes cluster, if you use AppSets with ClusterGenerators and you update something in the cluster secret, it will trigger a reconciliation on all ApplicationSets having a clustergenerator, even if this Appset is not in one of the namespaces allowed.

**To Reproduce**

```yaml
make start-e2e-local # namespaces allowed here for appsets are 
# create a cluster secret
kubectl create namespace argocd-other
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cm-appset
  namespace: argocd-other
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {} 
  template:
    metadata:
      name: '{{.name}}-cm' 
    spec:
      project: "mynonexistingproject"
      source:
        repoURL: https://github.com/OpenGuidou/simple-configmap.git
        targetRevision: HEAD
        path: .
      destination:
        server: '{{.server}}' # 'server' field of the secret
        namespace: '{{.name}}-cm'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
```

```yaml
make start-e2e-local # namespaces allowed here for appsets are 
# create a cluster secret
kubectl apply  -f appset.yaml -n argocd-other
```

-> The appset is not considered by the applicationset-controller

-> Add a label to the cluster secret created previously

-> See logs below

**Expected behavior**

The Appset should be discarded as not in one of the allowed namespaces.

**Version**

latest

**Logs**

```
15:10:28 applicationset-controller | {"applicationset":"cm-appset","level":"debug","msg":"clusters matching labels: 1","namespace":"argocd-other","time":"2025-12-11T15:10:28+01:00"}
15:10:28 applicationset-controller | {"applicationset":"cm-appset","level":"debug","msg":"Using flat mode = false for cluster generator","namespace":"argocd-other","time":"2025-12-11T15:10:28+01:00"}
15:10:28 applicationset-controller | {"applicationset":"cm-appset","cluster":"local cluster","level":"info","msg":"matched local cluster","namespace":"argocd-other","time":"2025-12-11T15:10:28+01:00"}
15:10:28 applicationset-controller | {"applicationset":"cm-appset","cluster":"mycluster-secret","level":"debug","msg":"matched cluster secret","namespace":"argocd-other","time":"2025-12-11T15:10:28+01:00"}
15:10:28 applicationset-controller | {"applicationset":{"Namespace":"argocd-other","Name":"cm-appset"},"generator":{"clusters":{"selector":{},"template":{"metadata":{},"spec":{"destination":{},"project":""}}}},"level":"debug","msg":"apps from generator: [{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:in-cluster-cm GenerateName: Namespace:argocd-other SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:\u003cnil\u003e DeletionGracePeriodSeconds:\u003cnil\u003e Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[resources-finalizer.argocd.argoproj.io] ManagedFields:[]} Spec:{Source:\u0026ApplicationSource{RepoURL:https://github.com/OpenGuidou/simple-configmap.git,Path:.,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:,Name:,} Destination:{Server:https://kubernetes.default.svc Namespace:in-cluster-cm Name:} Project:mynonexistingproject SyncPolicy:\u0026SyncPolicy{Automated:nil,SyncOptions:[CreateNamespace=true],Retry:nil,ManagedNamespaceMetadata:nil,} IgnoreDifferences:[] Info:[] RevisionHistoryLimit:\u003cnil\u003e Sources:[] SourceHydrator:nil} Status:{Resources:[] Sync:{Status: ComparedTo:{Source:{RepoURL: Path: TargetRevision: Helm:nil Kustomize:nil Directory:nil Plugin:nil Chart: Ref: Name:} Destination:{Server: Namespace: Name:} Sources:[] IgnoreDifferences:[]} Revision: Revisions:[]} Health:{Status: Message: LastTransitionTime:\u003cnil\u003e} History:[] Conditions:[] ReconciledAt:\u003cnil\u003e OperationState:nil ObservedAt:\u003cnil\u003e SourceType: Summary:{ExternalURLs:[] Images:[]} ResourceHealthSource: SourceTypes:[] ControllerNamespace: SourceHydrator:{LastSuccessfulOperation:nil CurrentOperation:nil}} Operation:nil} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:remote-cluter-cm GenerateName: Namespace:argocd-other SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:\u003cnil\u003e DeletionGracePeriodSeconds:\u003cnil\u003e Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[resources-finalizer.argocd.argoproj.io] ManagedFields:[]} Spec:{Source:\u0026ApplicationSource{RepoURL:https://github.com/OpenGuidou/simple-configmap.git,Path:.,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:,Name:,} Destination:{Server:https://0.0.0.0:42083 Namespace:remote-cluter-cm Name:} Project:mynonexistingproject SyncPolicy:\u0026SyncPolicy{Automated:nil,SyncOptions:[CreateNamespace=true],Retry:nil,ManagedNamespaceMetadata:nil,} IgnoreDifferences:[] Info:[] RevisionHistoryLimit:\u003cnil\u003e Sources:[] SourceHydrator:nil} Status:{Resources:[] Sync:{Status: ComparedTo:{Source:{RepoURL: Path: TargetRevision: Helm:nil Kustomize:nil Directory:nil Plugin:nil Chart: Ref: Name:} Destination:{Server: Namespace: Name:} Sources:[] IgnoreDifferences:[]} Revision: Revisions:[]} Health:{Status: Message: LastTransitionTime:\u003cnil\u003e} History:[] Conditions:[] ReconciledAt:\u003cnil\u003e OperationState:nil ObservedAt:\u003cnil\u003e SourceType: Summary:{ExternalURLs:[] Images:[]} ResourceHealthSource: SourceTypes:[] ControllerNamespace: SourceHydrator:{LastSuccessfulOperation:nil CurrentOperation:nil}} Operation:nil}]","time":"2025-12-11T15:10:28+01:00"}
```

### PR DESCRIPTION
**Pull request by OpenGuidou**
Fixes #25621

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by speedfl** [comment]
LGTM

**Comment by OpenGuidou** [comment]
@argoproj/argocd-approvers : Hello guys, can I get a review for this fix of an annoying bug ?

File: applicationset/controllers/clustereventhandler.go [hunk 1]
```diff
@@ -68,6 +70,10 @@ func (h *clusterSecretEventHandler) queueRelatedAppGenerators(ctx context.Contex
 
 	h.Log.WithField("count", len(appSetList.Items)).Info("listed ApplicationSets")
 	for _, appSet := range appSetList.Items {
+		if !utils.IsNamespaceAllowed(h.ApplicationSetNamespaces, appSet.GetNamespace()) {
+			// Ignore it
```
Comment (pjiang-dev) [inline applicationset/controllers/clustereventhandler.go]: Maybe add a debug log on what was skipped or at least a comment explaining why we ignore

Comment (OpenGuidou) [reply applicationset/controllers/clustereventhandler.go]: I would be careful with the log here, as it's called as many times as we have clusters and appsets. It can become very noisy very quickly.
I've enhanced a bit the comment. I hope it's fine for you.

File: applicationset/controllers/clustereventhandler.go [hunk 2]
```diff
@@ -68,6 +70,10 @@ func (h *clusterSecretEventHandler) queueRelatedAppGenerators(ctx context.Contex
 
 	h.Log.WithField("count", len(appSetList.Items)).Info("listed ApplicationSets")
 	for _, appSet := range appSetList.Items {
+		if !utils.IsNamespaceAllowed(h.ApplicationSetNamespaces, appSet.GetNamespace()) {
```
Comment (nitishfy) [inline applicationset/controllers/clustereventhandler.go:73]: how are we determining that `h.ApplicationSetNamespaces` contains the appset namespaces?

Comment (nitishfy) [reply applicationset/controllers/clustereventhandler.go:73]: ah, found it at line 668 of controller

File: applicationset/controllers/applicationset_controller.go [hunk 3]
```diff
@@ -663,8 +663,9 @@ func (r *ApplicationSetReconciler) SetupWithManager(mgr ctrl.Manager, enableProg
 		Watches(
 			&corev1.Secret{},
 			&clusterSecretEventHandler{
-				Client: mgr.GetClient(),
-				Log:    log.WithField("type", "createSecretEventHandler"),
+				Client:                   mgr.GetClient(),
+				Log:                      log.WithField("type", "createSecretEventHandler"),
+				ApplicationSetNamespaces: r.ApplicationSetNamespaces,
```
Comment (agaudreault) [inline applicationset/controllers/applicationset_controller.go:668]: Seems like the method `WithEventFilter(ignoreNotAllowedNamespaces(r.ApplicationSetNamespaces)).` should also apply to the Secret type.

```
// WithEventFilter sets the event filters, to filter which create/update/delete/generic events eventually
// trigger reconciliations. For example, filtering on whether the resource version has changed.
// Given predicate is added for all watched objects and thus must be able to deal with the type
// of all watched objects.
```

Do you have an explanation why it is not the case?

**Review by agaudreault — CHANGES_REQUESTED** [review]

File: applicationset/controllers/applicationset_controller.go (hunk 3 above)
Comment (OpenGuidou) [reply applicationset/controllers/applicationset_controller.go:668]: This correctly filters the cluster secrets in the correct namespaces, however the code inside createSecretEventHandler does a list on ApplicationSets at cluster scope without any filter on namespaces. 

This PR fixes that

Comment (agaudreault) [reply applicationset/controllers/applicationset_controller.go:668]: So it should use the `object.GetNamespace()` for to list on a specific namespace and not all namespace instead.

afaik, Appset cannot use cluster secrets from another namespace than where they are defined right?

Comment (OpenGuidou) [reply applicationset/controllers/applicationset_controller.go:668]: In the case of Appset in any namespaces, they can.
Cluster secrets are in fact not allowed anywhere else than the controller namespace.
So we have this list of allowed namespaces for applicationsets as controller variable, that I'm just reusing here.

Comment (agaudreault) [reply applicationset/controllers/applicationset_controller.go:668]: Gotcha, but I think what you are doing is not officially supported based on https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Appset-Any-Namespace/#cluster-scoped-argo-cd-installation, most likely because cluster resource is access is required, but the event handling should work correctly.

Your code is good, but a small optimization could be that if the len(ApplicationSetNamespaces) == 1, use a ListOption to only list on the single watched namespace instead of cluster scoped. This would need a new unit test for 1 vs multiple allowedNamespace.

Comment (agaudreault) [reply applicationset/controllers/applicationset_controller.go:668]: Approving this PR still since it is an optimization and this PR by itself fixes the issue.

**Review by agaudreault — APPROVED** [review]

File: applicationset/controllers/applicationset_controller.go (hunk 3 above)
Comment (OpenGuidou) [reply applicationset/controllers/applicationset_controller.go:668]: I agree and it forces to have the list/watch rbac at cluster level even if it's not required. I don't think that's the only place we would have to change that...
Thanks !

**Comment by OpenGuidou** [comment]
@agaudreault could you add the labels for cherry picking on 3.X releases ?
