### PR TITLE
fix: use resource health for hook status evaluation

### LINKED ISSUE #2515: Expand hook status to query resource health
# Summary

Related slack thread: https://argoproj.slack.com/archives/CASHNF6MS/p1571384149222500

I'd like to use things other than `BatchJob` or `Job` resources as a `PostSync` hook and rely on the resource health to determine hook pass/fail status.

# Motivation

Specifically, I am deploying a (custom in-house) operator providing a CRD. I'd like to apply a resource of my own custom type as a `PostSync` hook and have the sync show as failed if the health of my resource shows "Degraded".

I added a custom health lua script and validated that if my custom resource is "bad" (operator failed) that it does show Degraded. But the overall sync operation still shows as success.

# Proposal

`controller. getOperationPhase` could fall back to checking resource health instead of returning `v1alpha1.OperationSucceeded`. Will open a PR with an initial (rough) proposal.

### PR DESCRIPTION
**Pull request by alexmt**
Closes #2515

### CODE REVIEW

File: controller/sync_hooks.go [hunk 1]
```diff
@@ -5,116 +5,31 @@ import (
...
 	"github.com/argoproj/argo-cd/util/health"
 
-	apiv1 "k8s.io/api/core/v1"
-	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
-	"k8s.io/apimachinery/pkg/runtime"
-	"k8s.io/apimachinery/pkg/runtime/schema"
-	"k8s.io/kubernetes/pkg/apis/batch"
-
 	"github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1"
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
```
Comment (golangcibot) [inline controller/sync_hooks.go]: File is not `goimports`-ed with -local github.com/argoproj/argo-cd (from `goimports`)
```suggestion
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	"github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1"
```

File: controller/sync.go [hunk 2]
```diff
@@ -603,17 +608,24 @@ func (sc *syncContext) terminate() {
 	sc.log.Debug("terminating")
 	tasks, _ := sc.getSyncTasks()
 	for _, task := range tasks {
-		if !task.isHook() || !task.completed() {
+		if !task.isHook() || task.liveObj == nil {
 			continue
 		}
-		if isRunnable(task.groupVersionKind()) {
+		phase, msg, err := sc.getOperationPhase(task.liveObj)
```
Comment (jessesuen) [inline controller/sync.go]: Note that this change is significant, breaking change of a corner case. The new behavior is that we will delete any **_in-flight_** hook resource when an operation is terminated, where in-flight means `v1alpha1.HealthStatusProgressing` and `v1alpha1.HealthStatusSuspended`. This means that if a progressing Deployment, PVC, StatefulSet, ReplicaSet, Service, Ingress, APIService  is used as a sync hook, then those resources will become deleted when the operation is terminated.

That said:
* using things like Deployments was never the intended use case of hooks (since that use case was intention of waves)
*  the new behavior is probably the correct behavior, since without this change we cannot use things like other CRDs (TensorflowJob) as a hook.

We either need to list this as a breaking change, or we need to modify the code such that when it sees Deployment, PVC, StatefulSet, ReplicaSet, Service, Ingress, APIService as a Sync hook, it will choose not to delete the resource.

**Review by jessesuen — APPROVED** [review]
LGTM, but let's not forget to document the breaking change.

File: controller/sync.go (hunk 2 above)
Comment (alexmt) [reply controller/sync.go]: 👍  working on PR with docs changes
