### PR TITLE
fix: prevent idle connection buildup by cloning http.DefaultTransport in Bitbucket SCM/PR generator #24209

### LINKED ISSUE #24209: ApplicationSet controller: Bitbucket Server SCM/PullRequest generator leaks idle HTTP connections
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using the ApplicationSet controller with Bitbucket Server (via scmProviderGenerator or pullRequestGenerator), we observe a continuous buildup of idle TCP connections from the controller to the Bitbucket server.

Investigation shows that the controller instantiates a new http.Transport on every reconcile loop (introduced in #19002). Each new transport creates its own connection pool and spawns goroutines (persistConn.readLoop, persistConn.writeLoop) for keep-alive connections. Since these transports are not reused and do not inherit the cleanup settings of http.DefaultTransport (e.g. IdleConnTimeout), idle connections remain open indefinitely.

Over time, this leads to an accumulation of idle sockets and goroutines. Causing the scm Server to run out of available connections.

The correct approach is to reuse a shared http.Transport (or at least a clone of http.DefaultTransport) so that connections are pooled correctly and idle connections are reclaimed after the configured timeout.

**To Reproduce**

1. Run the ArgoCD ApplicationSet controller with a Bitbucket Server SCM or PR generator.
2. Allow the controller to reconcile multiple times.
3. Inspect open file descriptors or network sockets (lsof -p <pid> or netstat -anp | grep <pid>).
4. Observe that the number of idle connections to the Bitbucket server grows over time.

**Expected behavior**

* Idle connections should be reclaimed automatically after the IdleConnTimeout expires.
* No unbounded growth of idle sockets or background goroutines.

**Screenshots**

**Version**

v2.14.7

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by portly-halicore-76**
**Description**

This PR fixes an idle connection leak in the ApplicationSet controller when using the Bitbucket Server SCM/PullRequest generators.

Currently, a new http.Transport is created on each reconcile. Since this transport does not inherit defaults from http.DefaultTransport (e.g. IdleConnTimeout), every reconcile creates a fresh connection pool and new goroutines. Idle connections are never reclaimed, leading to a buildup of sockets and goroutines over time.

This PR updates the code to use a clone of http.DefaultTransport instead of constructing a bare http.Transport. This ensures:

* Proper connection pooling and reuse across reconciles.
* Idle connections are reclaimed after the configured timeout (IdleConnTimeout = 90s by default).
* No unbounded growth of idle TCP connections or goroutines.

Fixes #24209 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by nitishfy — COMMENTED** [review]
can we add tests to verify this?

**Comment by portly-halicore-76** [comment]
> can we add tests to verify this?

Direct unit tests for connection leaks are not practical, since they depend on observing internal net/http goroutines and OS-level sockets.

What we can test (and I propose adding) is a unit test verifying that the transport we configure inherits defaults from http.DefaultTransport (e.g. IdleConnTimeout > 0). That way, we prevent regressions where a bare http.Transport{} is accidentally reintroduced.

For end-to-end validation, an integration test could use an httptest.Server and assert that connections are reused and idle ones eventually close, but this is more of a system-level test than a unit test and rather difficult. Also I believe we don't have a baseline of integration tests for the appSet controller right?

**Comment by portly-halicore-76** [comment]
In addition, which this PR, we match the implementation of for example https://github.com/argoproj/argo-cd/blob/v3.1.0/applicationset/services/scm_provider/gitlab.go#L34

File: applicationset/services/pull_request/bitbucket_server.go [hunk 1]
```diff
@@ -51,9 +51,8 @@ func NewBitbucketServiceNoAuth(ctx context.Context, url, projectKey, repositoryS
 func newBitbucketService(ctx context.Context, bitbucketConfig *bitbucketv1.Configuration, projectKey, repositorySlug string, scmRootCAPath string, insecure bool, caCerts []byte) (PullRequestService, error) {
 	bitbucketConfig.BasePath = utils.NormalizeBitbucketBasePath(bitbucketConfig.BasePath)
 	tlsConfig := utils.GetTlsConfig(scmRootCAPath, insecure, caCerts)
-	bitbucketConfig.HTTPClient = &http.Client{Transport: &http.Transport{
-		TLSClientConfig: tlsConfig,
-	}}
+	bitbucketConfig.HTTPClient = &http.Client{Transport: http.DefaultTransport.(*http.Transport).Clone()}
+	bitbucketConfig.HTTPClient.Transport.(*http.Transport).TLSClientConfig = tlsConfig
```
Comment (rumstead) [inline applicationset/services/pull_request/bitbucket_server.go]: I think something like this reads more easily with only a single type assertion, what do you think? 
```suggestion
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.TLSClientConfig = tlsConfig
	bitbucketConfig.HTTPClient = &http.Client{Transport: transport}
```

**Comment by rumstead** [comment]
Great find! I left a small NIT

File: applicationset/services/pull_request/bitbucket_server.go (hunk 1 above)
Comment (portly-halicore-76) [reply applicationset/services/pull_request/bitbucket_server.go]: agreed, implemented! and reordered the statements within this code as well.

File: applicationset/services/pull_request/bitbucket_server.go [hunk 2]
```diff
@@ -49,11 +49,11 @@ func NewBitbucketServiceNoAuth(ctx context.Context, url, projectKey, repositoryS
 }
 
 func newBitbucketService(ctx context.Context, bitbucketConfig *bitbucketv1.Configuration, projectKey, repositorySlug string, scmRootCAPath string, insecure bool, caCerts []byte) (PullRequestService, error) {
```
Comment (rumstead) [inline applicationset/services/pull_request/bitbucket_server.go:51]: Sorry, I should've realized this before. I hate that we have the same code in two spots. Can we create a method, maybe in the `services package` or wherever you feel is appropriate? 

```
// SetupBitbucketClient configures and creates a Bitbucket API client with TLS settings
func SetupBitbucketClient(ctx context.Context, config *bitbucketv1.Configuration, scmRootCAPath string, insecure bool, caCerts []byte) *bitbucketv1.APIClient {
	config.BasePath = utils.NormalizeBitbucketBasePath(config.BasePath)
	tlsConfig := utils.GetTlsConfig(scmRootCAPath, insecure, caCerts)

	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.TLSClientConfig = tlsConfig
	config.HTTPClient = &http.Client{Transport: transport}

	return bitbucketv1.NewAPIClient(ctx, config)
}
```

Comment (rumstead) [reply applicationset/services/pull_request/bitbucket_server.go:51]: This also may make testing easier since we can do some assertions on the bitbucket client like the default path and the client isn't nil, etc.

Comment (portly-halicore-76) [reply applicationset/services/pull_request/bitbucket_server.go:51]: WDYT about this approach?

**Comment by portly-halicore-76** [comment]
@rumstead I doubt these e2e failures are related to my changes. Can you confirm? Looks to be a timeout of the CI 🔢

**Comment by portly-halicore-76** [comment]
@rumstead btw can this be backported once merged to a lowest version after being introduced. Preferable starting from v3.0.x That we we can benefit from the fix asap.

**Review by rumstead — APPROVED** [review]

**Comment by anandf** [comment]
@rumstead Looks like the cherry-pick commands did not work ? Should I submit a manually created PR ?

**Comment by rumstead** [comment]
> @rumstead Looks like the cherry-pick commands did not work ? Should I submit a manually created PR ?

sure!
