### PR TITLE
fix: cache external TLS cert to avoid `Loading TLS config` log spam (#17277) (#23965)

### LINKED ISSUE #17277: argocd-server-tls continuously reloaded
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

When the argocd-server-tls secret is present, the server continuously reloads it. This gives issues in web interface responsiveness

NB: the certificate has a TTL of 90 days, it's not being renewed in the timeframe of the logs below

**To Reproduce**

In a cluster where cert-manager is configured (you need an issuer in the argo-cd namespace), enable the server ingress and configure it to autogenerate the certificate (snippet of values below, installed using chart v6.2.1)
```yaml
configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/issuer: "YOUR_ISSUER_S_NAME"
    tls: true
```

**Expected behavior**

The certificate should be reloaded only when its serial changes

**Screenshots**

**Version**

```shell
argocd: v2.10.1+a79e0ea
  BuildDate: 2024-02-14T17:37:43Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

UTC+4

```
time="2024-02-22T07:13:29Z" level=info msg="Loading TLS configuration from secret argo-cd/argocd-server-tls"
time="2024-02-22T07:13:39Z" level=info msg="Loading TLS configuration from secret argo-cd/argocd-server-tls"
time="2024-02-22T07:13:49Z" level=info msg="Loading TLS configuration from secret argo-cd/argocd-server-tls" 
time="2024-02-22T07:13:59Z" level=info msg="Loading TLS configuration from secret argo-cd/argocd-server-tls" 
time="2024-02-22T07:14:00Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2024-02-22T07:11:06Z" grpc.time_ms=174681.06 span.kind=server system=grpc 
time="2024-02-22T07:14:00Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2024-02-22T07:11:05Z" grpc.time_ms=175039.48 span.kind=server system=grpc
time="2024-02-22T07:14:09Z" level=info msg="Loading TLS configuration from secret argo-cd/argocd-server-tls"
--
Thu, Feb 22 2024 11:14:19 am | time="2024-02-22T07:14:19Z" level=info msg="Loading TLS configuration from secret argo-cd/argocd-server-tls"
Thu, Feb 22 2024 11:14:29 am | time="2024-02-22T07:14:29Z" level=info msg="Loading TLS configuration from secret argo-cd/argocd-server-tls"
Thu, Feb 22 2024 11:14:39 am | time="2024-02-22T07:14:39Z" level=info msg="Loading TLS configuration from secret argo-cd/argocd-server-tls"
Thu, Feb 22 2024 11:14:49 am | time="2024-02-22T07:14:49Z" level=info msg="Loading TLS configuration from secret argo-cd/argocd-server-tls"
Thu, Feb 22 2024 11:14:51 am | time="2024

```

### LINKED ISSUE #23965: Excessive logging of loading external server TLS certificate
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Periodically the argocd-application-controller logs a block like 70+ lines of identical messages like this:

```
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
...
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
```

Never mind the fact how wasteful reloading a secret 70+ times unnecessarily is, but the fact that even the timestamps are identical causes a downstream issue where using Fluentbit+Opensearch (with Generate_ID enabled) the logging backend rejects them as duplicate, causing a constant headache.

**To Reproduce**

Use external TLS certificate with ArgoCD.

**Expected behavior**

Argocd Application Controller reloads TLS certificate excessively without checking for changes, and logs each.

**Screenshots**

n/a

**Version**

```shell
argocd: v3.0.0+e98f483
  BuildDate: 2025-05-06T14:00:23Z
  GitCommit: e98f483bfd5781df2592fef1aeed1148f150d9c9
  GitTreeState: clean
  GoVersion: go1.24.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v3.0.0+e98f483
```

**Logs**

```
Paste any relevant application logs here.
```

```
{"app-namespace":"<redacted>","app-qualified-name":"<project/app redacted>","application":"<redacted>","level":"info","msg":"Refreshing app status (comparison expired, requesting refresh. reconciledAt: 2025-07-28 08:34:04 +0000 UTC, expiry: 1m0s), level (2)","project":"<redacted>","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Ignore status for all objects","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"application":"<project/app redacted>","level":"info","msg":"Comparing app state (cluster: https://kubernetes.default.svc, namespace: <redacted>)","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"application":"<project/app redacted>","build_options_ms":0,"level":"info","manifests_ms":25,"msg":"GetRepoObjs stats","plugins_ms":0,"repo_ms":0,"time":"2025-07-28T08:35:09Z","time_ms":25}
{"level":"info","msg":"Ignore status for all objects","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Ignore status for all objects","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Ignore status for all objects","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Ignore status for all objects","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Ignore status for all objects","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Ignore status for all objects","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Ignore status for all objects","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Ignore status for all objects","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"app-namespace":"<redacted>","app-qualified-name":"<project/app redacted>","application":"<redacted>","level":"info","msg":"Skipping auto-sync: application status is Synced","project":"<redacted>","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"app-namespace":"<redacted>","app-qualified-name":"<project/app redacted>","application":"<redacted>","level":"info","msg":"Update successful","project":"<redacted>","time":"2025-07-28T08:35:09Z"}
{"app-namespace":"<redacted>","app-qualified-name":"<project/app redacted>","app_status_update_ms":0,"application":"<redacted>","auto_sync_ms":0,"compare_app_state_ms":41,"comparison-level":2,"comparison_with_nothing_ms":0,"dedup_ms":0,"dest-name":"","dest-namespace":"<redacted>","dest-server":"https://kubernetes.default.svc","diff_ms":13,"git_ms":26,"health_ms":0,"level":"info","live_ms":0,"msg":"Reconciliation completed","normalize_application_ms":0,"patch_ms":50,"persist_app_status_ms":51,"process_finalizers_ms":0,"project":"<redacted>","refresh_app_conditions_ms":0,"set_app_managed_resources_ms":17,"setop_ms":0,"settings_ms":0,"sync_ms":0,"time":"2025-07-28T08:35:09Z","time_ms":111}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
{"app-namespace":"<redacted>","app-qualified-name":"<project/app redacted>","application":"<redacted>","level":"info","msg":"Refreshing app status (controller refresh requested), level (0)","project":"<redacted>","time":"2025-07-28T08:35:09Z"}
{"level":"info","msg":"Loading TLS configuration from secret argocd/argocd-server-tls","time":"2025-07-28T08:35:09Z"}
```

### PR DESCRIPTION
**Pull request by mtbennett-godaddy**
* Fixes #17277.
* Fixes #23965.
* Closes #22282.
* Closes #24021.

Updates `SettingsManager.externalServerTLSCertificate` to cache the key parsed from the secret’s cert and to invalidate that cache when the secret is updated. It also moves the `Loading TLS configuration from secret` log message so that it is only emitted when the cert is parsed (as opposed to every time `SettingsManager.GetSettings` is called).

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* ~[ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.~
* ~[ ] Does this PR require documentation updates?~
* ~[ ] I've updated documentation as required by this PR.~
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* ~[ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.~
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by blakepettersson** [comment]
@mtbennett-godaddy is there any reason why we couldn't do something like

```golang
// externalServerTLSCertificate will try and load a TLS certificate from an
// external secret, instead of tls.crt and tls.key in argocd-secret. If both
// return values are nil, no external secret has been configured.
func (mgr *SettingsManager) externalServerTLSCertificate(existingCert *tls.Certificate) (*tls.Certificate, error) {
	var cert tls.Certificate
	secret, err := mgr.GetSecretByName(externalServerTLSSecretName)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return nil, nil
		}
	}

	if secret.ResourceVersion != mgr.tlsCertCacheSecretVersion || existingCert == nil {
		log.Infof("Loading TLS configuration from secret %s/%s", mgr.namespace, externalServerTLSSecretName)

		tlsCert, certOK := secret.Data[settingServerCertificate]
		tlsKey, keyOK := secret.Data[settingServerPrivateKey]
		if certOK && keyOK {
			cert, err = tls.X509KeyPair(tlsCert, tlsKey)
			if err != nil {
				return nil, err
			}
		}

		mgr.tlsCertCacheSecretVersion = secret.ResourceVersion
		return &cert, nil
	}

	return existingCert, nil
}
```

**Comment by mtbennett-godaddy** [comment]
@blakepettersson Commited some refactors before I saw your comment. The refactor adds a `loadTLSCertificateFromSecret` function that gets called with the external cert and if there’s nothing there, it calls it again with the `argocd-secret`. The caching logic is in that function so it applies to both cert sources, not just the external one.

However, there are sporadic unit test failures in the GH action runs that I haven’t been able to reproduce locally. Still trying to figure that out.

**Comment by mtbennett-godaddy** [comment]
@blakepettersson Ready for review. I figured out the unit test issue… I was calling `invalidateTLSCertCache` unnecessarily in the informer event handler, which was being triggered more frequently in the action-run tests than it was locally for some reason.

File: util/settings/settings.go [hunk 1]
```diff
@@ -1592,6 +1622,8 @@ func (mgr *SettingsManager) SaveSettings(settings *ArgoCDSettings) error {
 		return err
 	}
 
+	mgr.invalidateTLSCertCache()
```
Comment (blakepettersson) [inline util/settings/settings.go]: Do we need to invalidate the cache at all? During which situations would this need to happen?

Comment (mtbennett-godaddy) [reply util/settings/settings.go]: I basically just kept that logic when I copied #22282’s changes as my initial template. But, no, now that you mention it, I can’t think of any reason why explicit invalidation would be necessary. Any relevant change to the config/secret should be respected by the name/version check next time `loadTLSCertificateFromSecret()` runs.

I’ll remove it and make sure everything still passes.

Comment (mtbennett-godaddy) [reply util/settings/settings.go]: Addressed in a77299f.

File: util/settings/settings.go [hunk 2]
```diff
@@ -1533,25 +1525,54 @@ func (mgr *SettingsManager) updateSettingsFromSecret(settings *ArgoCDSettings, a
...
+	mgr.mutex.Lock()
+	defer mgr.mutex.Unlock()
+	if externalSecret != nil {
+		cert, err := mgr.loadTLSCertificateFromSecret(externalSecret)
+
+		if err != nil {
+			return err
+		} else if cert != nil {
+			settings.Certificate = cert
+			settings.CertificateIsExternal = true
```
Comment (blakepettersson) [inline util/settings/settings.go:1538]: Github doesn't allow to do the suggestion across the full range of where the code block is supposed to be, but you'll get the gist of this. This is more of a nit than anything else, but how about this?


```suggestion
	var err error
	var cert *tls.Certificate
	if externalSecret != nil {
		cert, err = mgr.loadTLSCertificateFromSecret(externalSecret)
	} else if !settings.CertificateIsExternal {
		// if there was no external cert found, check internal
		cert, err = mgr.loadTLSCertificateFromSecret(argoCDSecret)
	}

	if err != nil {
		return err
	} else if cert != nil {
		settings.Certificate = cert
		settings.CertificateIsExternal = externalSecret != nil
	}
	return nil
```

Apart from that, this LGTM

**Comment by blakepettersson** [comment]
Seems like this should be cherry-picked back to 3.0 and 3.1 (once this PR gets approved and merged)

File: util/settings/settings.go (hunk 2 above)
Comment (mtbennett-godaddy) [reply util/settings/settings.go:1538]: Since `loadTLSCertificateFromSecret` can return `nil, nil`:
* Your `else if !settings.CertificateIsExternal` seems unsafe because that value is based on the previous result of `loadTLSCertificate`. (I used that value in my `if` condition because my earlier branch would have set it if a non-`nil` cert came back from the external secret.)
* Your `settings.CertificateIsExternal = externalSecret != nil` at the end isn’t necessarily the case. `externalSecret` can be non-`nil` but it might still end up with the non-external cert.

If I work around those issues, I basically end up with what I already have.

Comment (blakepettersson) [reply util/settings/settings.go:1538]: Fair enough, LGTM!

**Review by blakepettersson — APPROVED** [review]

**Comment by blakepettersson** [comment]
@mtbennett-godaddy thanks a lot! Do you mind creating cherry-pick PRs for 3.0 and 3.1?

**Comment by ivanpedersen** [comment]
I'm new to the ArgoCD project and don't really understand the release process. Has this been released? @blakepettersson

**Comment by crenshaw-dev** [comment]
@ivanpedersen we haven't cherry-picked this back, so it'll go out in 3.2.0-rc1 which is released in ~2 weeks.

We have cherry-picked and released https://github.com/argoproj/argo-cd/pull/24235, which I'm hoping will sufficiently mitigate the logs and performance issues.

**Comment by Lirt** [comment]
Hello,

the patch would deserve to be released also in current stable tag - `v3.1.x`. You'd avoid unnecessary new GH issues, comments, etc.

**Comment by blakepettersson** [comment]
3.2 is out, would be great to hear if this has been fixed

**Comment by ArieLevs** [comment]
> 3.2 is out, would be great to hear if this has been fixed

yes i can confirm this issue has been resolved :tada:
