### PR TITLE
fix: Rm browser history

### LINKED ISSUE #7090: UI pollutes browser location history
We recently upgraded to ArgoCD v2.1.0+d0b2d55 and have noticed that when browsing the UI the history in Firefox gets really polluted when changing pages.

## Steps to reproduce;

1. Open a new browser tab
2. Navigate to ArgoCD
3. Long-press back button on browser

## Expected
- A single entry for ArgoCD

## Actual

History contains 15 separate entries for the same URI, preventing the back button being functional in any real term

image

This issue also manifests when;

- side-scrolling wide application views
- clicking any element inside a viewport

### PR DESCRIPTION
**Pull request by pasha-codefresh**
Closes: https://github.com/argoproj/argo-cd/issues/7090

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: ui/src/app/applications/components/applications-list/applications-table.tsx [hunk 1]
```diff
@@ -40,7 +40,9 @@ export const ApplicationsTable = (props: {
                             key={app.metadata.name}
                             className={`argo-table-list__row
                 applications-list__entry applications-list__entry--health-${app.status.health.status} ${selectedApp === i ? 'applications-tiles__selected' : ''}`}>
-                            <div className={`row applications-list__table-row`} onClick={e => ctx.navigation.goto(`/applications/${app.metadata.name}`, {}, {event: e})}>
+                            <div
+                                className={`row applications-list__table-row`}
+                                onClick={e => ctx.navigation.goto(`/applications/${app.metadata.name}`, {}, {event: e, replace: true})}>
```
Comment (alexmt) [inline ui/src/app/applications/components/applications-list/applications-table.tsx:45]: I think the ApplicationList -> App Details page navigation should be recorded in history. Please revert this line change.

File: ui/src/app/settings/components/clusters-list/clusters-list.tsx [hunk 2]
```diff
@@ -33,7 +33,7 @@ export const ClustersList = (props: RouteComponentProps<{}>) => {
                                                     <div
                                                         className='argo-table-list__row'
                                                         key={cluster.server}
-                                                        onClick={() => ctx.navigation.goto(`./${encodeURIComponent(cluster.server)}`)}>
+                                                        onClick={() => ctx.navigation.goto(`./${encodeURIComponent(cluster.server)}`, {}, {replace: true})}>
```
Comment (alexmt) [inline ui/src/app/settings/components/clusters-list/clusters-list.tsx:36]: I think the ClustersList -> Cluster Details page navigation should be recorded in history. Please revert this line change.

**Review by alexmt — CHANGES_REQUESTED** [review]
Awesome! Added couple minor comments. LGTM after resolving

**Review by alexmt — APPROVED** [review]
LGTM
