### PR TITLE
fix(ui): prevent wide gaps in grouped resource tree

### LINKED ISSUE #25619: UI Group Nodes option leaves empty space between nodes in apps with a high number of pods
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

When the Group Nodes option is used, apps with a large amount of pods result in wide visual gaps between ReplicaSets.

**To Reproduce**

1. Create an app with a Deployment with 10 pods.
1. Enable the Group Nodes option in UI.
1. Observe that there are no wide gaps between the nodes.
1. Scale it up to about 300 pods.
1. Observe that there are now wider gaps between the nodes that slowly increase as the number of pods grows.

**Expected behavior**

It should look mostly the same, whether there are 3, 300, or 3000 pods, when the Group Nodes option is selected.

**Screenshots**

App with 3 ReplicaSets (managed by a Rollout), with almost 4000 pods total: (note the 10% zoom-out and also the scroll bar on the right. There is also a lot of empty space underneath that can be scrolled to)

Image

App with 480 pods, managed by a StatefulSet:

Image

**Version**

```shell
argocd: v3.2.1+8c4ab63
  BuildDate: 2025-12-01T09:30:12Z
  GitCommit: 8c4ab63a9c72b31d96c6360514cda6254e7e6629
  GitTreeState: clean
  GoVersion: go1.25.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v3.1.7+511ebd7
  BuildDate: 2025-09-22T22:21:06Z
  GitCommit: 511ebd799e64f9af6484feaa84a5e718a77620d5
  GitTreeState: clean
  GoVersion: go1.24.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.7.0 2025-06-28T07:00:07Z
  Helm Version: v3.18.4+gd80839c
  Kubectl Version: v0.33.1
  Jsonnet Version: v0.21.0
```

**Logs**

```
---
```

### PR DESCRIPTION
**Pull request by choejwoo**
Closes #25619

When Group Nodes is enabled, apps with large pod counts create increasingly large gaps/empty space between nodes as reported.

Promoted previously hard-coded pod-group sizing values to `POD_GROUP_ROW_HEIGHT` constants for consistency. 
And added `getPodGroupNumberOfRows` func to centralize pod-group row calculation and applied it to both Dagre layout height and rendered height, preventing spacing from growing with large pod counts.

fix_podgroup_ui_empty_space
Screenshot above shows the grouped node view, the normal view is unchanged.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx [hunk 1]
```diff
@@ -397,7 +398,33 @@ function processPodGroup(targetPodGroup: ResourceTreeNode, child: ResourceTreeNo
...
+                continue;
+            }
+            const health = pod.health;
+            if (health === 'Healthy' || health === 'Degraded' || health === 'Progressing') {
+                statuses.add(health);
+            }
+        }
+        return statuses.size;
+    }
+    return Math.ceil(pods.length / 8);
```
Comment (jwinters01) [inline ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx]: I know this is not your work but why do we divide by 8 here?

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx [hunk 2]
```diff
@@ -1178,8 +1203,14 @@ export const ApplicationResourceTree = (props: ApplicationResourceTreeProps) =>
...
-        const numberOfRows = Math.ceil(node.podGroup.pods.length / 8);
-        graph.setNode(treeNodeKey(node), {...node, type: NODE_TYPES.podGroup, width: NODE_WIDTH, height: POD_NODE_HEIGHT + 30 * numberOfRows, root});
+        const numberOfRows = getPodGroupNumberOfRows(node.podGroup?.pods, showPodGroupByStatus);
+        graph.setNode(treeNodeKey(node), {
+            ...node,
+            type: NODE_TYPES.podGroup,
+            width: NODE_WIDTH,
+            height: POD_NODE_HEIGHT + POD_GROUP_ROW_HEIGHT * numberOfRows,
+            root
+        });
```
Comment (jwinters01) [inline ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx:1266]: it looks like right now for pod groups, we are measuring the height and width of the pod groups in [setGroupNode](https://github.com/jwinters01/argo-cd/blob/094c848c29fda8166ac7fc6abea6d697be657a99/ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx#L1180), but then here on Layout we are modifying the position of them after the fact. our graph library should be able to handle this offset itself if we pass the correct sizing information for the node to it.

would it be possible to instead calculate the value for `topExtra` as a height adjustment within [setPodGroupNode](https://github.com/jwinters01/argo-cd/blob/094c848c29fda8166ac7fc6abea6d697be657a99/ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx#L1180) so that dagre can handle all the positioning logic? This way we aren't manually overriding it which can be error-prone

**Review by jwinters01 — CHANGES_REQUESTED** [review]
suggested an alternate approach, let me know your thoughts on it

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx (hunk 1 above)
Comment (choejwoo) [reply ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx]: Thanks for the review!

https://github.com/argoproj/argo-cd/blob/1d6659319513881a1367bd544829979ae9ff565b/ui/src/app/applications/components/application-resource-tree/application-resource-tree.scss#L61-L63
We render pods in a fixed grid of 8 pods per row (see `$pods-per-row: 8` in `application-resource-tree.scss`), so when not grouping by status we compute the number of rows as ceil `pods.length / 8` to match the rendered pod-group height. I also promoted 8 to a shared constant `POD_GROUP_PODS_PER_ROW` to avoid a magic number, and added a short `keep in sync` comment to make the relationship between the TS constant and the SCSS value explicit.

`divide by 4`
스크린샷 2026-02-03 오후 10 08 42
`divide by 8`
스크린샷 2026-02-03 오후 10 08 57

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx (hunk 2 above)
Comment (choejwoo) [reply ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx:1266]: Agreed, we shouldn’t apply a post-layout Y offset like `topExtra`. I updated the pod-group sizing so Dagre receives the correct pod-group height up front (centralized row calculation used for both Dagre sizing and rendering), which prevents spacing from drifting as pod counts grow.

One nuance is that this view currently mixes coordinate conventions (Dagre’s center-based coordinates vs. DOM top/left). Because of that, changing only the node height while leaving `node.y` unchanged can lead to node overlap. A full `Dagre-only x/y` approach would require normalizing the center → top-left conversion across all node types, which is a larger refactor than this change.

The screenshot below shows the result when we keep `node.y` unchanged and adjust only the node height.
스크린샷 2026-02-03 오후 10 14 51

**Comment by choejwoo** [comment]
I noticed some renderer params `id` in `renderPodGroup`/`renderResourceNode` function weren’t used anymore, so I removed them.

File: ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx [hunk 3]
```diff
@@ -444,14 +465,10 @@ function renderPodGroup(
...
-        ? [podGroupHealthy, podGroupDegraded, podGroupInProgress].reduce((total, podGroupByStatus) => total + (podGroupByStatus.filter(pod => pod).length > 0 ? 1 : 0), 0)
-        : Math.ceil(podGroup?.pods.length / 8);
-
-    if (podGroup) {
-        topExtra = margin + (POD_NODE_HEIGHT / 2 + 30 * numberOfRows) / 2;
-    }
+    // Use Dagre's measured height directly to avoid duplicating sizing logic in the render path.
+    // Dagre assigns node.y as the node center; convert to DOM top-left for rendering.
+    const podGroupHeight = node.height;
+    const podGroupTop = node.y - podGroupHeight / 2;
```
[the remark this answers is not in the document]
Comment (choejwoo) [reply ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx:471]: The existing edge-routing code at line 1337 already treats `node.y` as the Dagre center and converts to top-left `endNode.y - endNode.height / 2`, so `podGroupTop = node.y - podGroupHeight / 2` is consistent with how this codebase handles variable-height nodes. 

Using `node.y` directly (without the center->top conversion) causes node overlap when the pod-group height grows, as shown in the screenshot from the earlier review discussion.

**Review by jwinters01 — APPROVED** [review]

**Review by blakepettersson — APPROVED** [review]
Thanks!
