### PR TITLE
Issue #1375 - Error view instead of blank page in UI

### LINKED ISSUE #1375: Error view instead of blank page in UI
Now any JS error crashes UI and user is seeing an empty screen. Instead, UI should show view with an explanation of what happened and instructions to file a bug. Instructions should include stack trace, UI version and link to github create issue. Preferrably link should include parameters to prepopulate bug in github ui.

### PR DESCRIPTION
**Pull request by AdityaGupta1**
Closes #1375

If an error causes the UI to crash, a page with the stacktrace and a link to submit a new issue is shown, for example:

image

### CODE REVIEW

File: ui/src/app/app.tsx [hunk 1]
```diff
@@ -97,6 +101,20 @@ export class App extends React.Component<{}, { popupProps: PopupProps }> {
     }
 
     public render() {
+        if (this.state.error != null) {
+            const stack = this.state.error.stack;
+            const url = 'https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md';
+
+            return (
+                <React.Fragment>
```
Comment (alexec) [inline ui/src/app/app.tsx]: Minor, did we want to use https://reactjs.org/docs/error-boundaries.html?

Comment (alexec) [reply ui/src/app/app.tsx]: Duh. I can see you did.

**Review by alexec — APPROVED** [review]

File: ui/src/app/app.tsx (hunk 1 above)
Comment (AdityaGupta1) [reply ui/src/app/app.tsx]: The docs say that if a class defines either or both of `static getDerivedStateFromError()` or `componentDidCatch()`, then it becomes an error boundary. I used `getDerivedStateFromError()` here.
