### PR TITLE
fix: Unable to edit http repo credentials from ArgoCD UI

### LINKED ISSUE #22246: Unable to edit HTTP repo credentials from ArgoCD UI
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Unable  to edit http repo credentials from argocd UI. The  repos hosted with http are not clickable from UI

**To Reproduce**

Add a repo hosted with http to argocd and try to click the repo in-order to modify the credentials

**Expected behavior**

Should be able to edit http repo credentials from argocd UI

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by aali309**
Fixes: #22246 
This PR fixes the issue where HTTP repository credentials cannot be edited from the ArgoCD UI. Previously, only HTTPS repositories were clickable and editable in the UI. Now both HTTP and HTTPS repositories can be edited.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by aali309** [comment]
Screenshot 2025-02-27 at 2 00 04 PM

Screenshot 2025-02-27 at 2 00 37 PM

**Review by keithchong — COMMENTED** [review]
Do we have to add `http` as a new Connection method, as a separate change, when one wants to create a new repo connection?  Or, should the current https be named to `http(s)`, or `http/https`, or.....?

File: ui/src/app/settings/components/repos-list/repos-list.tsx [hunk 1]
```diff
@@ -208,31 +208,31 @@ export class ReposList extends React.Component<
...
                 return {
                     url:
-                        (!httpsValues.url && 'Repository URL is required') ||
-                        (this.credsTemplate && !this.isHTTPSUrl(httpsValues.url) && !httpsValues.enableOCI && 'Not a valid HTTPS URL'),
-                    name: httpsValues.type === 'helm' && !httpsValues.name && 'Name is required',
-                    username: !httpsValues.username && httpsValues.password && 'Username is required if password is given.',
-                    password: !httpsValues.password && httpsValues.username && 'Password is required if username is given.',
-                    bearerToken:
-                        (httpsValues.password && httpsValues.bearerToken && 'Either the password or the bearer token must be set, but not both.') ||
-                        (httpsValues.type != 'git' && 'Bearer token is only supported for Git BitBucket Data Center repositories'),
```
Comment (todaywasawesome) [inline ui/src/app/settings/components/repos-list/repos-list.tsx:221]: I don't think you meant to remove this. We don't want to drop the bearer token support.

**Review by todaywasawesome — CHANGES_REQUESTED** [review]

**Comment by aali309** [comment]
> Do we have to add `http` as a new Connection method, as a separate change, when one wants to create a new repo connection? Or, should the current https be named to `http(s)`, or `http/https`, or.....?

The existing HTTPS connection method already handles both HTTP and HTTPS protocols under the hood - we just needed to fix the validation and UI display. Renaming it to HTTP/HTTPS would make sense to better reflect this capability.

File: ui/src/app/settings/components/repos-list/repos-list.tsx [hunk 2]
```diff
@@ -208,31 +208,34 @@ export class ReposList extends React.Component<
...
-                    password: !httpsValues.password && httpsValues.username && 'Password is required if username is given.',
+                        (!validURLValues.url && 'Repository URL is required') ||
+                        (this.credsTemplate && !this.isHTTPOrHTTPSUrl(validURLValues.url) && !validURLValues.enableOCI && 'Not a valid HTTP/HTTPS URL'),
+                    name: validURLValues.type === 'helm' && !validURLValues.name && 'Name is required',
+                    username: !validURLValues.username && validURLValues.password && 'Username is required if password is given.',
+                    password: !validURLValues.password && validURLValues.username && 'Password is required if username is given.',
+                    tlsClientCertKey: !validURLValues.tlsClientCertKey && validURLValues.tlsClientCertData && 'TLS client cert key is required if TLS client cert is given.',
                     bearerToken:
-                        (httpsValues.password && httpsValues.bearerToken && 'Either the password or the bearer token must be set, but not both.') ||
```
Comment (keithchong) [inline ui/src/app/settings/components/repos-list/repos-list.tsx:220]: You're just renaming the httpsValues constant to validURLValues, correct?  @todaywasawesome mentioned that this should not be removed.

File: ui/src/app/settings/components/repos-list/repos-list.tsx [hunk 3]
```diff
@@ -355,7 +358,14 @@ export class ReposList extends React.Component<
                                                     <div className='columns small-4'>
                                                         <Tooltip content={repo.repo}>
                                                             <span>
-                                                                <Repo url={repo.repo} />
+                                                                <a
```
Comment (keithchong) [inline ui/src/app/settings/components/repos-list/repos-list.tsx:361]: Do we need this change?  The `Repo` component should take care of this?

File: ui/src/app/settings/components/repos-list/repos-list.tsx [hunk 4]
```diff
@@ -125,7 +125,7 @@ interface NewGoogleCloudSourceRepoCredsParams {
 
 export enum ConnectionMethod {
     SSH = 'via SSH',
-    HTTPS = 'via HTTPS',
+    HTTPS = 'via HTTP/HTTPS',
```
Comment (keithchong) [inline ui/src/app/settings/components/repos-list/repos-list.tsx:128]: Screenshot 2025-03-05 at 9 31 00 AM

This looks ok...

**Review by keithchong — CHANGES_REQUESTED** [review]

**Review by keithchong — CHANGES_REQUESTED** [review]

**Review by keithchong — APPROVED** [review]
LGTM

**Review by todaywasawesome — APPROVED** [review]
Thanks looks good!
