### PR TITLE
Convert maintenance windows to sync windows

### LINKED ISSUE #2379: "Unable to create K8s REST config: invalid configuration" error when running using make start
**Describe the bug**
The api-server terminates when it is not running inside a kubernetes cluster. **To Reproduce**

1. make && make start 
2. go to http://localhost:8080

**Screenshots**
Screenshot 2019-09-29 at 13 07 39

**Expected behavior**

The ui should load

**Version**
master branch build

**Logs**

```
13:05:50  api-server | INFO[0015] received unary call /cluster.SettingsService/Get  grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2019-09-29T13:05:50+01:00" span.kind=server system=grpc
13:05:50  api-server | INFO[0015] finished unary call with code OK              grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2019-09-29T13:05:50+01:00" grpc.time_ms=1.173 span.kind=server system=grpc
13:05:50  api-server | INFO[0015] received unary call /cluster.SettingsService/Get  grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2019-09-29T13:05:50+01:00" span.kind=server system=grpc
13:05:50  api-server | INFO[0015] finished unary call with code OK              grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2019-09-29T13:05:50+01:00" grpc.time_ms=0.379 span.kind=server system=grpc
13:05:50  api-server | INFO[0015] received unary call /cluster.ClusterService/List  grpc.method=List grpc.request.claims=null grpc.request.content= grpc.service=cluster.ClusterService grpc.start_time="2019-09-29T13:05:50+01:00" span.kind=server system=grpc
13:05:50  api-server | W0929 13:05:50.165740   36826 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
13:05:50  api-server | panic: Unable to create K8s REST config: invalid configuration: no configuration has been provided
13:05:50  api-server | goroutine 256 [running]:
13:05:50  api-server | github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1.(*Cluster).RESTConfig(0xc0008ca5a0, 0xc0008ca5a0)
13:05:50  api-server |    /Users/a.johnson/go/src/github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1/types.go:1836 +0x7ed
13:05:50  api-server | github.com/argoproj/argo-cd/server/cluster.(*Server).List.func1(0x1, 0x2963e00, 0xc00067bb60)
13:05:50  api-server |    /Users/a.johnson/go/src/github.com/argoproj/argo-cd/server/cluster/cluster.go:105 +0x137
13:05:50  api-server | github.com/argoproj/argo-cd/util.RunAllAsync.func2(0xc00067bb60, 0xc0003ee2d0, 0xc000a68c10, 0x1)
13:05:50  api-server |    /Users/a.johnson/go/src/github.com/argoproj/argo-cd/util/util.go:148 +0x5a
13:05:50  api-server | created by github.com/argoproj/argo-cd/util.RunAllAsync
13:05:50  api-server |    /Users/a.johnson/go/src/github.com/argoproj/argo-cd/util/util.go:146 +0xf9
13:05:50  api-server | exit status 2
13:05:50  api-server | Terminating api-server
```

### PR DESCRIPTION
**Pull request by adamjohnson01**
Related to #2398 and also resolves #2379

This pr converts the current `maintenance windows` to `sync windows` and add some improvements.

- Windows can now be either allow or deny, with deny overriding allow if both active at the same time.
- All fields of a window can now be edited using CLI or UI
- There is a new field for allowing manual syncs during the window.
- The windows table will display all of the windows and their effective state
- More tooltips explaining what each field does and how it works
- CLI command have been simplified
- Resolves issue where windows are lost if project was edited through the UI.
- Application status panel and the `app get` command will display the window state for no syncs allowed, manual syncs allowed and all syncs allowed.

Windows Table
Screenshot 2019-10-04 at 17 29 01

Screenshot 2019-10-04 at 17 35 24
Screenshot 2019-10-04 at 17 41 20
Screenshot 2019-10-04 at 17 46 18

### CODE REVIEW

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -1523,14 +1573,93 @@ func (w *ProjectMaintenanceWindows) Match(app *Application) (bool, ProjectMainte
...
+		if !w.InactiveAllows().HasWindows() && !denyActive {
+			allow = true
+		}
+	} else {
+		allow = true
+	}
+	return allow
+}
+
+func (w *SyncWindows) CanSync() bool {
```
Comment (alexmt) [inline pkg/apis/application/v1alpha1/types.go]: Just a suggestion. You can return true as of `HasWindows` is false. This would allow to avoid nested if block:

```
if !w.HasWindows() {
  return true
}
...
```

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you for continue working on it @adamjohnson01 !

**Comment by adamjohnson01** [comment]
@alexmt 

> Unless I'm reading it incorrectly, the ability to sync depends on windows order. E.g. if deny window goes before allow the sync is allowed.

That is not correct, it will check all of the windows but if it finds and active deny then it no longer checks if allows are active as deny overrides allow.

> Can we make it consistent with Argo CD RBAC implementation? If any windows allow syncing, then syncing is allows regardless of order.

I think that it is standard practice for deny to override allow. If we have it the other way around then it makes it very difficult to configure denies as you need to edit all of you allows so that they do not overlap with any denies.

**Comment by adamjohnson01** [comment]
@alexmt 

`		if !w.InactiveAllows().HasWindows() && !denyActive {
`

This is checking that there are no inactive allow windows and no active deny windows. 

Inactive allows and active denies are the same except
- active allow overrides inactive allow
- active deny overrides active allow

allow windows:
- if no allow windows configured then syncs are allowed unless there is an active deny
- if allow windows configured and no active allow windows then syncs are blocked
- if active allows then syncs are allowed unless there is an active deny

deny windows:
- if no active deny windows then syncs are allowed unless there are allow windows configured and no active allows
- if active deny windows then syncs are blocked

**Comment by adamjohnson01** [comment]
I have updated the UI section that configures the schedule to use select instead of text this will hopefully make it easier to use.
Screenshot 2019-10-07 at 13 57 24

**Comment by alexec** [comment]
@adamjohnson01 doing house keeping. I've added the "not ready for review" label as there is a genuine CI failure related to code lint.

**Review by adamjohnson01 — COMMENTED** [review]
> @adamjohnson01 doing house keeping. I've added the "not ready for review" label as there is a genuine CI failure related to code lint.

@alexec , thanks, I thought that I had pushed that fix already. I have pushed it now.

**Comment by adamjohnson01** [comment]
I have updated the schedule editor to allow multiple selects and to support ranges
Screenshot 2019-10-07 at 22 50 01

File: server/application/application.go [hunk 2]
```diff
@@ -888,12 +888,12 @@ func (s *Server) Sync(ctx context.Context, syncReq *application.ApplicationSyncR
...
 	}
-	active := proj.Spec.Maintenance.ActiveWindows()
-	match, _ := active.Match(a)
-	if match {
-		s.logEvent(a, ctx, argo.EventReasonOperationCompleted, fmt.Sprint("Cannot sync: Maintenance Windows are active"))
-		return a, err
+
+	if !proj.Spec.SyncWindows.Matches(a).CanSync() {
+		s.logEvent(a, ctx, argo.EventReasonOperationCompleted, fmt.Sprint("Cannot sync: Blocked by sync window"))
+		return a, status.Errorf(codes.PermissionDenied, "Cannot sync: Blocked by sync window")
```
[the remark this answers is not in the document]
Comment (alexmt) [reply server/application/application.go]: I think this is correct. API should return an error so user understand that sync is not allowed.

File: server/application/application.go [hunk 3]
```diff
@@ -888,12 +888,12 @@ func (s *Server) Sync(ctx context.Context, syncReq *application.ApplicationSyncR
...
 		return a, err
 	}
-	active := proj.Spec.Maintenance.ActiveWindows()
-	match, _ := active.Match(a)
-	if match {
-		s.logEvent(a, ctx, argo.EventReasonOperationCompleted, fmt.Sprint("Cannot sync: Maintenance Windows are active"))
-		return a, err
+
+	if !proj.Spec.SyncWindows.Matches(a).CanSync(true) {
+		s.logEvent(a, ctx, argo.EventReasonOperationCompleted, fmt.Sprint("Cannot sync: Blocked by sync window"))
```
Comment (alexmt) [inline server/application/application.go]: Event `EventReasonOperationCompleted` should be created only sync operation completion. Please remove this line.

File: server/application/application.proto [hunk 4]
```diff
@@ -180,139 +182,139 @@ message ManagedResourcesResponse {
 // ApplicationService
 service ApplicationService {
 
-	// List returns list of applications
```
Comment (alexmt) [inline server/application/application.proto]: Looks like files was reformatted to use spaces instead of tabs. Can you please keep tabs?

**Review by alexmt — CHANGES_REQUESTED** [review]
Added two minor comments. I think it is almost ready to merge

File: server/application/application.proto (hunk 4 above)
Comment (adamjohnson01) [reply server/application/application.proto]: sure, I did not do it intentionally. I will revert.

File: server/application/application.go (hunk 3 above)
Comment (adamjohnson01) [reply server/application/application.go]: Will do

File: pkg/apis/application/v1alpha1/types.go [hunk 5]
```diff
@@ -1388,114 +1389,162 @@ type AppProjectSpec struct {
...
+	Clusters []string `json:"clusters,omitempty" protobuf:"bytes,6,opt,name=clusters"`
+	// ManualSync enables manual syncs when they would otherwise be blocked
+	ManualSync bool `json:"manualSync,omitempty" protobuf:"bytes,7,opt,name=manualSync"`
+}
+
+// ApplicationSyncWindows is a collection of ApplicationSyncWindows
+type ApplicationSyncWindows []*ApplicationSyncWindow
+
+// ApplicationSyncWindow contains the kind, time, duration and manualSync fields of a window assigned to an application
+type ApplicationSyncWindow struct {
```
[the remark this answers is not in the document]
Comment (adamjohnson01) [reply pkg/apis/application/v1alpha1/types.go]: sure, will do

[the remark this answers is not in the document]
Comment (adamjohnson01) [reply pkg/apis/application/v1alpha1/types.go]: Done

File: server/application/application.proto (hunk 4 above)
Comment (adamjohnson01) [reply server/application/application.proto]: Done

File: server/application/application.go (hunk 3 above)
Comment (adamjohnson01) [reply server/application/application.go]: Done

**Review by alexmt — APPROVED** [review]
LGTM! Could you please resovle merge conflicts and fix formatting in application.go. (CI fails https://circleci.com/gh/argoproj/argo-cd/5817)

**Comment by adamjohnson01** [comment]
> LGTM! Could you please resovle merge conflicts and fix formatting in application.go. (CI fails https://circleci.com/gh/argoproj/argo-cd/5817)

Done

**Comment by alexmt** [comment]
thank you @adamjohnson01 !
