### PR TITLE
fix(helm): login OCI Helm dependencies correctly (#11324)

### LINKED ISSUE #8563: Registry login error with helm OCI private dependencies
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Similar issue to this comment : https://github.com/argoproj/argo-cd/issues/8266#issuecomment-1027261191

When setting credentials templates that match a registry but that are not given as a repository (repocreds instead), the login fails because Argo CD [passes the schema oci:// as the registry URL](https://github.com/argoproj/argo-cd/blob/v2.3.0-rc1/reposerver/repository/repository.go#L487-L511), but helm (using oras-go) will fail because it does not support the oci:// schema, and so login command will fail

**To Reproduce**

1) Create an ArgoCD helm OCI repo-creds secret 
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argoproj-gitlab-helm-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: registry.gitlab.com/test
  enableOCI: true
  type: helm
  password: my-password
  username: my-username
```

2) Use a chart with a dependencie that match the repo-creds url
```yaml
apiVersion: v2
name: test-chart
version: 1.0.0
dependencies:
- name: toto-spa
  version: 1.1.1
  repository: "oci://registry.gitlab.com/test/toto"
```

3) ArgoCD will try to login with oci scheme in url
```
helm registry login oci://registry.gitlab.com/test/toto --username ****** --password ******
```

**Expected behavior**
helm registry login without oci scheme in url

```shell
helm registry login registry.gitlab.com/test/toto --username ****** --password ******
```

**Version**

```shell
argocd: v2.2.5+8f981cc
  BuildDate: 2022-02-05T01:33:25Z
  GitCommit: 8f981ccfcf942a9eb00bc466649f8499ba0455f5
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64``
```

**Logs**

```
rpc error: code = Unknown desc = `helm registry login oci://registry.gitlab.com/test/toto --username ****** --password ******` failed exit status 1: WARNING: Using --password ****** the CLI is insecure. Use --password-stdin. time="2022-02-18T11:02:49Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get \"https://oci/v2/\": dial tcp: lookup oci on 10.32.0.10:53: no such host" Error: Get "https://oci/v2/": dial tcp: lookup oci on 10.32.0.10:53: no such host
```

### LINKED ISSUE #11324: Helm OCI Login is broken
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I am using a helm chart dependency on a OCI helm repo. Under 2.14.X my config worked  (I dont know when the error started exactly, the cache seems to be preventing it from affecting everything so far.)

Currently I am seeing this error 
```json
{"error":"Manifest generation error (cached): `helm registry login oci://ghcr.io/XXXXX/XXXXXXXX --username ****** --password ******` failed exit status 1: WARNING: Using --password ****** the CLI is insecure. Use --password-stdin.\ntime=\"2022-11-16T22:06:57Z\" level=info msg=\"Error logging in to endpoint, trying next endpoint\" error=\"Get \\\"https://oci/v2/\\\": dial tcp: lookup oci on XXXXXXXX:53: no such host\"\nError: Get \"https://oci/v2/\": dial tcp: lookup oci on XXXXXXX:53: no such host","grpc.code":"Unknown","grpc.method":"GenerateManifest","grpc.service":"repository.RepoServerService","grpc.start_time":"2022-11-16T22:45:56Z","grpc.time_ms":221.418,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2022-11-16T22:45:57Z"}
```

It appears to be trying to login with `helm registry login oci://ghcr.io` instead of `helm registry login https://ghcr.io`

**To Reproduce**

Helm Chart with an OCI dependency
```yaml
apiVersion: v2
name: template
description: A helm3 chart 
type: application
dependencies:
  - name: common
    version: "^1.0.4"
    repository: "oci://ghcr.io/XXXXXX/XXXXXX"
appVersion: 1.0.0
version: 1.0.0
```

an Application
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  project: project
  source:
    repoURL: 'https://github.com/XXXXXXXX'
    path: .
    targetRevision: main
    helm:
      releaseName: test
  destination:
    namespace: XXXXX
    name: XXXXX
```

oci helm secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: github-oci-common
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  enableOCI: "true"
  name: github-oci-common
  type: helm
  url: ghcr.io/XXXXXXX/XXXXXXX/common
```

oci helm secret creds
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: github-oci-common-creds
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  enableOCI: "true"
  type: helm
  url: ghcr.io/XXXXXXX
  username: XXXXXX
  password: XXXXXX
```

**Expected behavior**

It should login correctly to the helm registry

**Version**

```json
{
    "Version": "v2.5.1+504da42",
    "BuildDate": "2022-11-01T21:14:30Z",
    "GitCommit": "504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.8",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.1+g9f88ccb",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.18.0"
}
```

### PR DESCRIPTION
**Pull request by alexef**
Fixes: #11324 
Fixes: #8563 

Signed-off-by: Alex Eftimie <alex.eftimie@getyourguide.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -819,6 +819,32 @@ func runHelmBuild(appPath string, h helm.Helm) error {
 	return os.WriteFile(markerFile, []byte("marker"), 0644)
 }
 
+func populateRequestRepos(appPath string, q *apiclient.ManifestRequest) error {
```
Comment (alexef) [inline reposerver/repository/repository.go:822]: I moved it to a separate function to enable testing

File: reposerver/repository/repository.go [hunk 2]
```diff
@@ -819,6 +819,32 @@ func runHelmBuild(appPath string, h helm.Helm) error {
...
+		return err
+	}
+
+	for _, r := range repos {
+		if !repoExists(r.Repo, q.Repos) {
+			repositoryCredential := getRepoCredential(q.HelmRepoCreds, r.Repo)
+			if repositoryCredential != nil {
+				if repositoryCredential.EnableOCI {
+					r.Repo = strings.TrimPrefix(r.Repo, ociPrefix)
+				}
```
Comment (alexef) [inline reposerver/repository/repository.go:834]: This is the fix for #11324 - strip out prefix here as well.

**Comment by alexef** [comment]
@crenshaw-dev this is still active, would be nice to make it into 2.6

**Comment by crenshaw-dev** [comment]
How far back should we cherry-pick this?

**Comment by alexef** [comment]
@crenshaw-dev same as the other, this applies to back when helm v3 was introduced, so v2.4?

**Review by crenshaw-dev — APPROVED** [review]
Thanks @alexef!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.5 for 2.5.5 and release-2.4 for 2.4.18.
