### PR TITLE
fix: error sending generate manifest metadata cmp server

### LINKED ISSUE #25511: error sending generate manifest metadata to cmp-server
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

We're trying to use a plugin for generating manifests through tanka, and we are using the CMP, actually we had using it for almost two years, without issues.
Since a couple of days we're experimenting different issues, perhaps connected between them. All our apps that use the CMP failed to sync.

First we got some issues about the application couldn't find the plugin, then we tried to specify the plugin name in all our apps. But still got some issues later, about context deadline exceeded, finally we tried to bump the timout for the CMP execution without success.

**To Reproduce**

Create a CMP as following
```
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: tanka-argo-cmp
spec:
  version: v1.0

  generate:
    command: [sh, -c]
    args:
        - |
          set -ue ;
          ENV_DIR=$(realpath -m "environments/$ARGOCD_ENV_TK_ENV") ;
          tk show "$ENV_DIR" --dangerous-allow-redirect ${ARGOCD_ENV_EXTRA_ARGS}

  discover:
    find:
        glob: "**/jsonnetfile.json"
```

Deploy as a sidecar following the documentation, and finally specify the plugin name to avoid discovery and unnecessary time spent on searching for the plugin.

```
  plugin:
    name: tanka-argo-cmp-v1.0

```

**Expected behavior**

We expect the plugin to generate the manifests using tanka and do not throw sync errors. Also we expect the generation to be quite fast. On our laptops, `tk show` is almost instant, in terms of speed.

**Screenshots**

Image

Image

**Version**

```shell
v3.2.1+8c4ab63
```

**Logs**

```
{"CWE":775,"level":"error","msg":"repository /tmp/_argocd-repo/a7dacee6-73cd-419e-8496-ce1d1032fe12 is not the match because error sending stream: error sending generate manifest metadata to cmp-server: EOF","security":2,"time":"2025-12-04T09:44:31Z"}
{"grpc.code":"Unknown","grpc.component":"server","grpc.error":"CMP processing failed for application \"welbee-staging\": could not find cmp-server plugin with name \"tanka-argo-cmp-v1.0\" supporting the given repository","grpc.method":"GenerateManifest","grpc.method_type":"unary","grpc.request.deadline":"2025-12-04T09:44:29Z","grpc.service":"repository.RepoServerService","grpc.start_time":"2025-12-04T09:43:29Z","grpc.time_ms":"61999.496","level":"error","msg":"finished call","peer.address":"10.128.2.142:21714","protocol":"grpc","time":"2025-12-04T09:44:31Z"}
```

### PR DESCRIPTION
**Pull request by ppapapetrou76**
Closes #25511 

### The first commit addresses the actual issue as described below
reposerver tries to detect the CMP sidecar (`DetectConfigManagementPlugin`). If the detection fails, it returns: "could not find cmp-server plugin with name %q supporting the given repository". That is exactly the message in the user's logs.

If detect succeeds, reposerver opens a GenerateManifest stream: 
`generateManifestStream, err := cmpClient.GenerateManifest(ctx, grpc_retry.Disable())`
It then calls `SendRepoStream` to send metadata, but the code currently passes this `generateManifestStream.Context()` as context. If this context is by any reason cancelled/closed early on the server-side (for any reason) the client-side will return an error (sometimes io.EOF), which is wrapped and logged as: "error sending generate manifest metadata to cmp-server: EOF". The PR now uses the original context. 

### The second commit improves the diagnostic/debugging level of `DetectConfigManagementPlugin` function as below
Currently, `DetectConfigManagementPlugin` returns a generic error when a named plugin is not found/usable: "could not find cmp-server plugin with name %q supporting the given repository". `cmpSupports` function logs detailed reasons but does not return the concrete error to the caller. 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by reggie-k — APPROVED** [review]

File: util/app/discovery/discovery.go [hunk 1]
```diff
@@ -112,13 +116,16 @@ func DetectConfigManagementPlugin(ctx context.Context, appPath, repoPath, plugin
 		}
 		for _, file := range fileList {
 			if file.Type() == os.ModeSocket {
-				conn, cmpClient, connFound = cmpSupports(ctx, pluginSockFilePath, appPath, repoPath, file.Name(), env, tarExcludedGlobs, false)
+				conn, cmpClient, connFound, lastErr = cmpSupports(ctx, pluginSockFilePath, appPath, repoPath, file.Name(), env, tarExcludedGlobs, false)
```
Comment (choejwoo) [inline util/app/discovery/discovery.go:119]: I might be misunderstanding the intent here, so I just want to make sure I understand correctly.
In discovery mode, iterate over multiple socket files. If the first probe returns an error like EOF, but a later probe returns `connfound=false`, `lastErr=nil` (`not supported`), does that later result overwrite `lastErr` and effectively drop the earlier error?

Comment (ppapapetrou76) [reply util/app/discovery/discovery.go:119]: @choejwoo yes that is correct

Comment (choejwoo) [reply util/app/discovery/discovery.go:119]: > @choejwoo yes that is correct

Thanks for confirming, LGTM.

**Review by choejwoo — APPROVED** [review]

**Review by pbhatnagar-oss — APPROVED** [review]
