### PR TITLE
fix(rbac): resolve RBAC regression for project-scoped resources in multi-namespace architecture (#25289)

### LINKED ISSUE #25289: AppProject RBAC Policy to get logs does not work as documented for an 'Applications in any namespace' setup
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

We are using the 'Applications in any namespace' feature and created AppProjects with a few policies. Most policies seem to work as desired, however the policy to 'get' 'logs' does not seem to be producing the desired outcome.

The policy is defined as follows:
```yaml
p, proj:<project-name>:<role-name>, logs, get, <project-name>/<app-namespace>/*, allow
```
Our expectation was that with this policy, the respective user would be able to view, for example, the Pod logs in the ArgoCD UI. However, that was not the case. The 'LOGS' tab and action did not exist on the pod (see screenshots).
 
We also have other policies in the AppProject which work as documented and expected, e.g.:
```yaml
p, proj:<project-name>:<role-name>, applications, get, <project-name>/<app-namespace>/*, allow
```
```yaml
p, proj:<project-name>:<role-name>, applications, action/apps/Deployment/*, <project-name>/<app-namespace>/*, allow
```
For all policies, the `<project-name>` is the name of the AppProject, the `<role-name>` is the name given to the role for which these policies are being defined and `<app-namespace>` is the namespace in which the Application Manifests exist in the cluster.

Afterwards, I started playing around with the broken policy. The first thing I tried was to use a wildcard for the object (`<project-name>/<app-namespace>/*`) which produced the following policy:
```yaml
p, proj:<project-name>:<role-name>, logs, get, *, allow
```
This rule allowed the targeted user for this policy to get the logs in the UI from the desired Application and everything worked as we had initially desired. Then I proceeded to use the object format which is meant to be used for ArgoCDs **not** using the 'Applications in any Namespace' feature (`<project-name>/<app-name>`). The resulting policy was:
```yaml
p, proj:<project-name>:<role-name>, logs, get, <project-name>/*, allow
```
Even with this policy, the targeted user for this policy could get the logs in the UI from the desired Application. Following this, I added one final granularity before we reach the initially defined Policy, and got the following policy:
```yaml
p, proj:<project-name>:<role-name>, logs, get, <project-name>/*/*, allow
```
This policy displayed the problem we had at the start and the user could not get the logs anymore.

Relevant documentation pages:
- https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/
  - On this page, there is also an example which uses the same combination (logs + apps in any namespace): https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#application-in-any-namespaces
- https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#configuring-rbac-with-projects
- https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#application-rbac

**To Reproduce**

Create an AppProject in an ArgoCD with the 'Applications in any namespace' feature enabled and add a role with a policy to explicitly get applications and logs, e.g.
```yaml
- p, proj:<project-name>:<role-name>, applications, get, <project-name>/<app-namespace>/*, allow
- p, proj:<project-name>:<role-name>, logs, get, <project-name>/<app-namespace>/*, allow
```
Deploy an app in the AppProject which deploys a workload (e.g. Deployment or Pod).
Check whether the logs can be viewed by the user permitted through the AppProject

**Expected behavior**

The user(s) specified in the role should be able to view logs using the ArgoCD UI.

**Screenshots**
LOGS Tab:
- Expected
  Image
- Actual
  Image

Logs Action:
- Expected
  Image
- Actual
  Image

**Version**

```shell
argocd: v3.2.0+66b2f30
  BuildDate: 2025-11-04T14:51:35Z
  GitCommit: 66b2f302d91a42cc151808da0eec0846bbe1062c
  GitTreeState: clean
  GoVersion: go1.25.0
  Compiler: gc
  Platform: linux/amd64
```

### PR DESCRIPTION
**Pull request by tcfwbper**
### Summary
This PR fixes the RBAC regression for project-scoped resources in multi-namespace architecture (#25289)

The issue was caused by inappropriate migration when we introduced "applications in any namespaces".
I have updated the following areas to restore the expected behavior:
* make sure RBAC queries with a namespace if any namespace defined
* normalize the subresource in the query for backward compatibility
* add unit tests
* revise the documents to claim that 3-segment subresource doesn't match those in default namespace

### Checklist
* [x] (b) this is a bug fix.
* [x] The title of the PR states what changed and the related issues number.
* [x] The title of the PR conforms to the Title of the PR.
* [x] I've included "Fixes #25289" in the description.
* [ ] I've updated both the CLI and UI.
* [x] Does this PR require documentation updates?
* [x] I have signed off all my commits as required by DCO.
* [x] I have written unit and/or e2e tests for my change.
* [x] My build is green.
* [x] I have added a brief description of why this PR is necessary.

Fixes #25289

### CODE REVIEW

**Comment by tcfwbper** [comment]
Dear reviewers, this guide might help you speed up reviewing.

The core changes of this PR are:
1. Load Policy
    - from argocd-rbac-cm (util/rbac/rbac.go)
    - from appproj (pkg/apis/application/v1alpha1/app_project_types.go)
2. CLI
    - argocd admin proj (cmd/argocd/commands/admin/project.go)
    - argocd admin settings (cmd/argocd/commands/admin/settings_rbac.go)
3. API calls
    - API server: authz verification requests (server/account/account.go)
    - RBACName: generate RBAC resource name for API calls (util/security/rbac.go)
4. Buildin policies (assets/builtin-policy.csv)
5. e2e tests (test/e2e/accounts_test.go)

Almost other changes are corresponding adjustment for unit tests

**Comment by tcfwbper** [comment]
FYI, I had some tests in my local environment.

Setup:
- accounts: admin, tester (non-admin local account)
- appproj: my-project
- app: test-app in argocd (default ns), test-app in my-app-team (any-ns)

Experiment:
adjust policies defined in appproj
    a. "my-project/*/test-app"
    b. "my-project/my-app-team/test-app"
    c. "my-project/argocd/test-app"
    d. "my-project/test-app"
then, try to get applications/logs from UI/CLI

Results: all of the results are as expected


https://github.com/user-attachments/assets/b95627e2-390e-4fae-8650-3936bfe850d2


https://github.com/user-attachments/assets/70075683-41c2-4299-9d92-1dd87e92b94e

File: pkg/apis/application/v1alpha1/app_project_types.go [hunk 1]
```diff
@@ -361,24 +362,19 @@ func (proj *AppProject) RemoveGroupFromRole(roleName, group string) (bool, error
...
 
-func (proj *AppProject) normalizePolicy(policy string) string {
-	policyComponents := strings.Split(policy, ",")
-	normalizedPolicy := ""
-	for _, component := range policyComponents {
-		if normalizedPolicy == "" {
-			normalizedPolicy = component
-		} else {
-			normalizedPolicy = fmt.Sprintf("%s, %s", normalizedPolicy, strings.Trim(component, " "))
+			if _, ok := seen[normalizedPolicy]; ok {
```
Comment (afzal442) [inline pkg/apis/application/v1alpha1/app_project_types.go]:
```suggestion
	for i, role := range proj.Spec.Roles {
		proj.Spec.Roles[i].Policies = normalizeUniquePolicies(role.Policies, proj.Namespace)
	}
```

File: pkg/apis/application/v1alpha1/app_project_types.go
Comment (afzal442) [inline pkg/apis/application/v1alpha1/app_project_types.go:359]:
```suggestion
// normalizeUniquePolicies normalizes and deduplicates a slice of policy strings.
func normalizeUniquePolicies(policies []string, namespace string) []string {
	watched := make(map[string]struct{}, len(policies))
	result := make([]string, 0, len(policies))
	for _, policy := range policies {
		normalized := rbac.NormalizePolicy(policy, namespace)
		if _, ok := watched[normalized]; ok {
			continue
		}
		watched[normalized] = struct{}{}
		result = append(result, normalized)
	}
	return result
}
```

**Review by afzal442 — CHANGES_REQUESTED** [review]

**Review by afzal442 — APPROVED** [review]
LGTM! Work like a charm. 🎉 Thanks @tcfwbper

**Comment by afzal442** [comment]
@ishitasequeira tagged you since you reviewed the [approach](https://github.com/argoproj/argo-cd/issues/25289#issuecomment-3929778933)

**Review by agaudreault — CHANGES_REQUESTED** [review]
Rejecting until the issue is clarified. Currently, the issue only describe a problem with the "logs" rbac evaluation while this PR affect all rbac evaluation. This might affect backward compatibility as well and requires a deeper review.

**Comment by afzal442** [comment]
> Currently, the issue only describe a problem with the "logs" rbac evaluation while this PR affect all rbac evaluation. This might affect backward compatibility as well and requires a deeper review.

I agree. The issue description is confusing. But this covers all rbac evaluation and maintain the backward compatibility.

File: assets/builtin-policy.csv [hunk 2]
```diff
@@ -6,29 +6,29 @@
 # 2. All other resources:
 # p, <role/user/group>, <resource>, <action>, <object>, <allow/deny>
 
-p, role:readonly, applications, get, */*, allow
-p, role:readonly, applicationsets, get, */*, allow
+p, role:readonly, applications, get, */*/*, allow
```
Comment (agaudreault) [inline assets/builtin-policy.csv]: if the policies are backward compatible, then we should not need to update the builtin-policy.csv

File: server/application/application_test.go [hunk 3]
```diff
@@ -1976,68 +1976,68 @@ func TestPatchResourcesRBAC(t *testing.T) {
...
+p, test-user, applications, update, default/default/test-app, allow
 `)
 		_, err := appServer.PatchResource(ctx, &req)
 		assert.Equal(t, codes.PermissionDenied.String(), status.Code(err).String())
 	})
 
 	t.Run("patch with application permission with inheritance", func(t *testing.T) {
 		_ = appServerWithRBACInheritance.enf.SetBuiltinPolicy(`
-p, test-user, applications, update, default/test-app, allow
+p, test-user, applications, update, default/default/test-app, allow
```
Comment (agaudreault) [inline server/application/application_test.go]: If the code is backward compatible, existing test that validate the 2-segment behaviour should not be modified, and should still be valid.

New tests should be added for the 3-segment policies

**Review by agaudreault — CHANGES_REQUESTED** [review]
I think this PR is extremely hard to review since the existing unit tests are modified, which prevent us from validating breaking changes. The builtin policy should not change as well. New tests should be added to validate policies with the 3-segment pattern.

I think the fix for the related issue can be much simpler. I did a POC in https://github.com/argoproj/argo-cd/pull/26926 to try to address the issue with a different approach.

The main problem identified in the issue was that the UI does not perform correctly the calls to the CanI API (used to validate log access). For this, this PR correctly address it with `getCanISubresource` now passing the namespace  for the apps-in-any-namespace support.

However, I think that normalizing every policies to a 3-segment path is unnecessary to solve this issue. The CanI function on the server side can normalize the default namespace use case to a 2-segment path, and use the exiting policy to evaluate the access.

**Comment by tcfwbper** [comment]
@agaudreault Thanks for your comments and PoC.

Firstly, the issue only describe a problem with the "logs" though, this RBAC regression covers four resources, "applications, applicationsets, logs, and exec". I can provide more experimental results to convince you. The code changes are only for these four resources.

Secondly, I agree with you that we've better not to adjust the existing unit tests. That makes my approach unstable.

I noticed that you revised the document to claim three-parts pattern is not valid if the namespace is default namespace. I can understand, but I think `proj/argocd/app` matches app in argocd sounds really straightforward.

Do you think the approach @crenshaw-dev said yesterday is better?
Do permission checks with three-parts, if not allowed and the namespace is default namespace, check again with two-parts.
By this approach, both `proj/app` and `proj/argocd/app` matches app in argocd and I think it wouldn't be a breaking change.

**Comment by agaudreault** [comment]
@tcfwbper I think while it would be more consistent to support the 3 parts for the Argo namespace, it is really against best security practices to give access to an application in the argo namespace when using a project used for apps-in-any-namespace.

So the value to support it is very low. I almost consider it a good thing that it is not working, so it prevents user to give that access.

Giving that access requires giving permission to the sourceNamespace and giving permission to an application in the argo namespace means the owner of the app can choose any project, and bypass the project permission.

And since `*/*` is valid for `*/*/*`, then I don't see the need to change the default policies to 3-parts segment

**Comment by tcfwbper** [comment]
@agaudreault fair enough to me, so I tried your approach in my local environment. I deployed app in any ns and appset in any ns and make sure the bug fixed. Additionally, I completed some end-to-end tests to make sure the decision on this issue won't be reversed

**Comment by tcfwbper** [comment]
Hi @agaudreault, sorry to bother. I've updated the tests and ensured all CI passes. This is based on your PoC with extra e2e tests. Is there anything else needed from my side to move this forward?

File: test/e2e/accounts_test.go [hunk 4]
```diff
@@ -42,45 +42,120 @@ func TestCreateAndUseAccount(t *testing.T) {
...
-		Project(ProjectName).
-		When().
-		Create().
-		Login().
-		SetPermissions([]ACL{
-			{
-				Resource: "logs",
-				Action:   "get",
-				Scope:    ProjectName + "/*",
+func TestCanIGetLogs(t *testing.T) {
```
Comment (agaudreault) [inline test/e2e/accounts_test.go]: As E2E are expensive to run, prefer using the explicit syntax. 

Only add a use case to validate the feature happy path and basic behaviour.

In this case, these test cases should be able to be covered by the unit test.

File: server/account/account_test.go [hunk 5]
```diff
@@ -332,3 +332,137 @@ func TestCanI_GetLogsDeny(t *testing.T) {
...
+			resp, err := accountServer.CanI(adminContext(t.Context()), &account.CanIRequest{
+				Resource:    "logs",
+				Action:      "get",
+				Subresource: "myproject/default/myapp",
+			})
+			require.NoError(t, err)
+			assert.Equal(t, tt.expectedResp, resp.Value)
+		})
+	}
+}
```
Comment (tcfwbper) [inline server/account/account_test.go:369]: @agaudreault since we already have the Happy Path e2e test, I reverted the e2e changes and moved the most important two test cases here to make sure the decision won't be reverted

**Review by agaudreault — APPROVED** [review]

**Comment by wanddynosios** [comment]
@agaudreault Do you think this can be cherry-picked into 3.4.x? 

https://argo-cd.readthedocs.io/en/stable/developer-guide/submit-your-pr/#cherry-picking-fixes

**Comment by agaudreault** [comment]
@wanddynosios you will need to manually open a PR against 3.4 release branch to make the changes without conflicts

**Comment by wanddynosios** [comment]
Sure thing, @agaudreault! Here's the PR: https://github.com/argoproj/argo-cd/pull/28062
