### PR TITLE
fix(sharding): fix log format verb and document intentional shard-0 fallback 

### LINKED ISSUE #27199: Consistent hashing silently assigns clusters to shard 0 on parse error
**Checklist:**

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

In `controller/sharding/sharding.go`, the `createConsistentHashingWithBoundLoads`
function has two issues in the same error handling block when `strconv.Atoi`
fails to parse the shard index returned by the consistent hashing ring.

1. The format verb `%d` is used to log an `error` value. Go's `fmt` package
   renders this as `%!d(*errors.errorString=&{...})`, so the actual error
   message is never visible in the logs.

2. There is no `continue` after the log statement, so execution falls through
   and `shardIndexedByCluster[c.ID]` is left as `0` — the zero value returned
   by `strconv.Atoi` on failure. In a multi-replica setup this silently assigns
   the affected cluster to shard 0 instead of skipping it, which can lead to
   uneven load distribution and unexpected ownership changes across replicas.

Relevant code (`controller/sharding/sharding.go`):

```go
shardIndexedByCluster[c.ID], err = strconv.Atoi(clusterIndex)
if err != nil {
    log.Errorf("Consistent Hashing was supposed to return a shard index but it returned %d", err)
    // no continue here — falls through and writes 0 into the map
}
```

**To Reproduce**

The bad assignment happens whenever the hashing ring returns a value that cannot
be parsed as an integer — for example when the ring is initialised with a
non-numeric node label, or if an upstream library change affects the return
format of `GetLeast`.

To confirm the garbled log locally:

```go
err := fmt.Errorf("some error")
log.Errorf("returned %d", err)
// prints: returned %!d(*errors.errorString=&{some error})
```

To hit the shard-0 fallback, patch `GetLeast` in the existing sharding unit
tests to return a non-numeric string. The cluster will end up at index `0` in
`shardIndexedByCluster` rather than being skipped.

**Expected behavior**

`%d` should be replaced with `%v` so the error is readable, and a `continue`
should skip the cluster rather than leaving it mapped to shard 0.

```go
shardIndexedByCluster[c.ID], err = strconv.Atoi(clusterIndex)
if err != nil {
    log.Errorf("Consistent Hashing returned a non-integer shard index %q for cluster %s: %v", clusterIndex, c.ID, err)
    continue
}
```

**Screenshots**

**Version**

```shell
argocd: v3.3.6
  BuildDate: 2026-03-27T14:29:30Z
  GoVersion: go1.23.4
  Platform: linux/amd64
```

**Logs**

```
time="..." level=error msg="Consistent Hashing was supposed to return a shard index but it returned %!d(*errors.errorString=&{...})"
```

### PR DESCRIPTION
**Pull request by nitishfy**
Closes https://github.com/argoproj/argo-cd/issues/27199

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: controller/sharding/sharding.go [hunk 1]
```diff
@@ -222,7 +222,10 @@ func createConsistentHashingWithBoundLoads(replicas int, getCluster clusterAcces
 		}
 		shardIndexedByCluster[c.ID], err = strconv.Atoi(clusterIndex)
 		if err != nil {
-			log.Errorf("Consistent Hashing was supposed to return a shard index but it returned %d", err)
+			log.Errorf("Consistent Hashing was supposed to return a shard index but it returned %v", err)
```
Comment (gdsoumya) [inline controller/sharding/sharding.go]: I think this error log makes more sense

```suggestion
			log.Errorf("Failed to get shard index from consistent hashing, error=%v", err)
```

**Review by gdsoumya — CHANGES_REQUESTED** [review]

**Review by gdsoumya — APPROVED** [review]

**Review by rumstead — APPROVED** [review]

**Review by choejwoo — APPROVED** [review]
