### PR TITLE
fix: remove tracking annotation from git manifest when performing hydration

### LINKED ISSUE #23815: Hydrator: Tracking annotation present in Git manifest
**Describe the bug**

Argo CD commits the hydrated manifests to git when sourceHydrator is used. The manifest will contain the Argo CD tracking annotations. The manifest should contain the result of the "generation" (helm/kustomize) without any special normalization from Argo CD.

**To Reproduce**

1. Create an application using sourceHydrator
2. Execute hydration

**Expected behavior**

Argo CD should not add the tracking annotations to the manifest in git. Just like when it uses plain directory sources, it should add the tracking annotation dynamically before comparing/syncing the live resources.

Image

**Version**

```shell
3.1.0-rc3
```

### PR DESCRIPTION
**Pull request by nitishfy**
Fixes https://github.com/argoproj/argo-cd/issues/23815

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: commitserver/commit/hydratorhelper.go [hunk 1]
```diff
@@ -204,6 +204,17 @@ func writeManifests(root *os.Root, dirPath string, manifests []*apiclient.Hydrat
...
+		// This annotation is used only for in-memory tracking and should not be persisted.
+		annotations := obj.GetAnnotations()
+		if annotations != nil {
+			delete(annotations, common.AnnotationKeyAppInstance)
+			if len(annotations) == 0 {
+				obj.SetAnnotations(nil)
+			} else {
+				obj.SetAnnotations(annotations)
+			}
+		}
```
Comment (crenshaw-dev) [inline commitserver/commit/hydratorhelper.go]: Instead of adding the behavior inline here, how about adding a new `RemoveAppInstance` method to the `argo.ResourceTracking` interface? Some of the logic from `SetAppInstance` could be duplicated to cover both the label and annotation cases.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Thanks for the PR! Suggested a similar approach but different organization.

File: commitserver/commit/hydratorhelper.go (hunk 1 above)
Comment (nitishfy) [reply commitserver/commit/hydratorhelper.go]: What's the benefit of adding a new method than doing inline behavior?

Comment (crenshaw-dev) [reply commitserver/commit/hydratorhelper.go]: 1) Location: it's in the same place as `SetAppInstance `, so it's easier to notice if something changes in one function requiring a change in the other function
2) Readability: it keeps the hydrationhelper function focused on its core behavior
3) Testing: it makes the tracking-removal code independently testable

Comment (nitishfy) [reply commitserver/commit/hydratorhelper.go]: I researched a bit more about the flow of code and I want to ask something here:

Reading the following code here:

1. https://github.com/argoproj/argo-cd/blob/master/controller/hydrator/hydrator.go#L311
2. https://github.com/argoproj/argo-cd/blob/master/controller/state.go#L304
3. https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L1562 (this is where app instance is set)

Even after adding the `RemoveAppInstance` method to the interface, Is it idle to call that method for removing the app instance fields once the app instance is set in `repository.go`?  What would you suggest here doing?

Comment (crenshaw-dev) [reply commitserver/commit/hydratorhelper.go]: I think we have a few options:

1) Set `q.AppLabelKey` to `""` so that repository.go doesn't set tracking info. This is convenient since it doesn't require removing the tracking info later, and it doesn't require any new repo-server params. But on the other hand, it would require passing more params to functions like GetRepoObjs so that the hydrator can tell it not to set `q.AppLabelKey`. It also requires relying on repo-server to always treat `q.AppLabelKey=""` as "don't set tracking info," which may change in the future.
2) Add a new repo-server GenerateManifests parameter for `setTrackingMetadata`. This is clearer than using `q.AppLabelKey`, but it still requires passing new params.
3) Move logic that adds tracking metadata outside repo-server. i.e. have the caller always add tracking info client-side if it's needed, and just don't add it in the hydrator. This is the most invasive option, and there might be side-effects related to not caching the tracking metadata in Redis.
4) Add `RemoveAppInstance` and all it from the hydrator. This is probably the simplest solution, but it does have the downside of weirdly adding metadata in repository.go just to remove it again in hydrator.go.

Comment (crenshaw-dev) [reply commitserver/commit/hydratorhelper.go]: I think option 4 is my favorite, but I could be wrong. One of the other options might be better, or I might be missing some options.

Comment (nitishfy) [reply commitserver/commit/hydratorhelper.go]: Let's say we go with the option 4. Even if we add that, we are still required to call that function before committing the manifest. Isn't it? So, how is adding the method benefiting us when we are still doing the inline addition (calling that function) before committing?

Comment (crenshaw-dev) [reply commitserver/commit/hydratorhelper.go]: For the reasons in this comment: https://github.com/argoproj/argo-cd/pull/23857#discussion_r2219542292

File: util/argo/resource_tracking.go [hunk 2]
```diff
@@ -244,3 +245,20 @@ func (rt *resourceTracking) Normalize(config, live *unstructured.Unstructured, l
 
 	return nil
 }
+
+func (rt *resourceTracking) RemoveAppInstance(un *unstructured.Unstructured) error {
```
Comment (crenshaw-dev) [inline util/argo/resource_tracking.go]: Can you move this up to immediately after `SetAppInstance`, since their behavior should be very closely mirrored?

File: util/argo/resource_tracking.go [hunk 3]
```diff
@@ -244,3 +245,20 @@ func (rt *resourceTracking) Normalize(config, live *unstructured.Unstructured, l
...
+	err = kube.RemoveAnnotation(un, common.AnnotationInstallationID)
+	if err != nil {
+		return err
+	}
+	err = kube.RemoveLabel(un, common.LabelKeyAppInstance)
+	if err != nil {
+		return err
+	}
+
+	return nil
```
Comment (crenshaw-dev) [inline util/argo/resource_tracking.go]: Instead of removing all known tracking label/annotations, can we dynamically remove just the ones that we know were set by `SetAppInstance`? 

If someone is using annotation-based tracking and sets the `app.kubernetes.io/instance` label on a resource in git, we should only remove the annotation, not the label.

File: commitserver/commit/hydratorhelper.go [hunk 4]
```diff
@@ -204,6 +204,17 @@ func writeManifests(root *os.Root, dirPath string, manifests []*apiclient.Hydrat
 		if err != nil {
 			return fmt.Errorf("failed to unmarshal manifest: %w", err)
 		}
+		// Remove Argo CD's internal tracking annotation before committing to Git.
```
Comment (crenshaw-dev) [inline commitserver/commit/hydratorhelper.go]: Instead of doing this in hydratorhelper.go immediately before commiting, can we do it in hydrator.go immediately after calling GetRepoObjs? I'd like to keep manifest-mutation logic out of the commit server.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: util/argo/resource_tracking.go (hunk 2 above)
Comment (nitishfy) [reply util/argo/resource_tracking.go]: resolved.

File: util/argo/resource_tracking.go (hunk 3 above)
Comment (nitishfy) [reply util/argo/resource_tracking.go]: Can you please take a look now? I added a new annotation to keep track of the tracking method and later using that  value to remove the values dynamically.

File: commitserver/commit/hydratorhelper.go (hunk 4 above)
Comment (nitishfy) [reply commitserver/commit/hydratorhelper.go]: resolved.

File: commitserver/commit/hydratorhelper.go (hunk 1 above)
Comment (nitishfy) [reply commitserver/commit/hydratorhelper.go]: That's alright. If you look at the changes now, the `RemoveAppInstance` is literally a dead code. Hence, if we were to manually range over objects and remove it, what's the use of the function we wrote instead?

File: util/argo/resource_tracking.go [hunk 5]
```diff
@@ -167,8 +167,54 @@ func (rt *resourceTracking) SetAppInstance(un *unstructured.Unstructured, key, v
...
+			return err
+		}
+		if err := kube.RemoveLabel(un, common.LabelKeyAppInstance); err != nil {
+			return err
+		}
+	default:
+		// Fallback: we don’t know what method was used (e.g. old resource), so remove all known fields
+		_ = kube.RemoveAnnotation(un, common.AnnotationKeyAppInstance)
+		_ = kube.RemoveAnnotation(un, common.AnnotationInstallationID)
+		_ = kube.RemoveLabel(un, common.LabelKeyAppInstance)
```
Comment (crenshaw-dev) [inline util/argo/resource_tracking.go]: The default case should be identical to `TrackingMethodAnnotation`, just like in `SetAppInstance`.

File: util/argo/resource_tracking.go [hunk 6]
```diff
@@ -167,8 +167,54 @@ func (rt *resourceTracking) SetAppInstance(un *unstructured.Unstructured, key, v
...
 	}
+
+	// Finally, always remove the tracking-method marker annotation itself
+	_ = kube.RemoveAnnotation(un, v1alpha1.AnnotationKeyTrackingMethod)
```
Comment (crenshaw-dev) [inline util/argo/resource_tracking.go]: We should check the error here.

File: util/argo/resource_tracking.go [hunk 7]
```diff
@@ -167,8 +167,54 @@ func (rt *resourceTracking) SetAppInstance(un *unstructured.Unstructured, key, v
...
+	// so that we can later remove only those when needed.
+	// This is useful to remove the all known tracking label/annotations
+	// set by Argo CD especially when generating hydrated manifest.
+	return kube.SetAppInstanceAnnotation(un, v1alpha1.AnnotationKeyTrackingMethod, string(trackingMethod))
+}
+
+func (rt *resourceTracking) RemoveAppInstance(un *unstructured.Unstructured) error {
+	trackingMethod, _, _ := unstructured.NestedString(un.Object, "metadata", "annotations", v1alpha1.AnnotationKeyTrackingMethod)
+
+	switch v1alpha1.TrackingMethod(trackingMethod) {
```
Comment (crenshaw-dev) [inline util/argo/resource_tracking.go:175]: Each of the cases should return nil early if there's no error, like in `SetAppInstance`.

File: pkg/apis/application/v1alpha1/application_annotations.go [hunk 8]
```diff
@@ -6,10 +6,12 @@ const (
...
 	AnnotationKeyHydrate string = "argocd.argoproj.io/hydrate"
-
 	// AnnotationKeyManifestGeneratePaths is an annotation that contains a list of semicolon-separated paths in the
 	// manifests repository that affects the manifest generation. Paths might be either relative or absolute. The
 	// absolute path means an absolute path within the repository and the relative path is relative to the application
 	// source path within the repository.
 	AnnotationKeyManifestGeneratePaths = "argocd.argoproj.io/manifest-generate-paths"
+	// AnnotationKeyTrackingMethod is used to record how Argo CD tracked the resource (label, annotation, or both).
+	// It helps ensure only the tracking metadata added by Argo CD is removed later.
+	AnnotationKeyTrackingMethod = "argocd.argoproj.io/tracking-method"
```
Comment (crenshaw-dev) [inline pkg/apis/application/v1alpha1/application_annotations.go]: We should pass the tracking method as a param on the function instead of passing it on the manifest.

File: controller/hydrator_dependencies.go [hunk 9]
```diff
@@ -51,6 +53,19 @@ func (ctrl *ApplicationController) GetRepoObjs(origApp *appv1.Application, drySo
...
+		annotations := obj.GetAnnotations()
+		if annotations != nil {
+			delete(annotations, common.AnnotationKeyAppInstance)
+			if len(annotations) == 0 {
+				obj.SetAnnotations(nil)
+			} else {
+				obj.SetAnnotations(annotations)
+			}
+		}
+	}
```
Comment (crenshaw-dev) [inline controller/hydrator_dependencies.go]: Switch this to a call to `RemoveAppInstance`?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Getting closer!

File: controller/hydrator_dependencies.go (hunk 9 above)
Comment (nitishfy) [reply controller/hydrator_dependencies.go]: There's no instance of  resource tracking that could call that. Maybe we move the `RemoveAppinstance` as part of `settingMgr` so we can call something like `ctrl.settingMgr.RemoveAppInstance()`

Comment (crenshaw-dev) [reply controller/hydrator_dependencies.go]: GetRepoObjs in hydrator_dependencies.go has access to the settings manager. I think it can pull the tracking method from there.

Comment (nitishfy) [reply controller/hydrator_dependencies.go]: Pulling the tracking method is possible, something like `ctrl.settingMgr.GetTrackingMethod()`, however, we still can't call the `RemoveAppInstance` there.

Comment (crenshaw-dev) [reply controller/hydrator_dependencies.go]: I don't follow... couldn't you do something like this?

```go
import github.com/argoproj/argo-cd/v3/util/argo

func (ctrl) GetRepoObjs() {
    method := ctrl.settingMgr.GetTrackingMethod()
    argo.NewResourceTracking().RemoveAppInstance(obj, method)
}
```

File: util/argo/resource_tracking.go (hunk 6 above)
Comment (nitishfy) [reply util/argo/resource_tracking.go]: resolved.

File: util/argo/resource_tracking.go (hunk 7 above)
Comment (nitishfy) [reply util/argo/resource_tracking.go:175]: Please see now.

File: pkg/apis/application/v1alpha1/application_annotations.go (hunk 8 above)
Comment (nitishfy) [reply pkg/apis/application/v1alpha1/application_annotations.go]: resolved.

File: util/argo/resource_tracking.go (hunk 5 above)
Comment (nitishfy) [reply util/argo/resource_tracking.go]: resolved.

**Comment by nitishfy** [comment]
Marking all the comments as resolved and added tests too! :)

File: docs/user-guide/source-hydrator.md [hunk 10]
```diff
@@ -323,3 +323,10 @@ from pushing to the hydrated branches, enable branch protection in your SCM.
 
 It is best practice to prefix the hydrated branches with a common prefix, such as `environments/`. This makes it easier
 to configure branch protection rules on the destination repository.
+
+!!! note
+To maintain reproducibility and determinism in the Hydrator’s output,
+Argo CD-specific metadata (such as `argocd.argoproj.io/tracking-id`) is
+not written to Git during hydration. These annotations are added dynamically
+during application sync and comparison.
+!!!
```
Comment (crenshaw-dev) [inline docs/user-guide/source-hydrator.md]:
```suggestion
    To maintain reproducibility and determinism in the Hydrator’s output,
    Argo CD-specific metadata (such as `argocd.argoproj.io/tracking-id`) is
    not written to Git during hydration. These annotations are added dynamically
    during application sync and comparison.
```

I think this is the correct format for mkdocs notes.

File: controller/hydrator_dependencies.go [hunk 11]
```diff
@@ -54,6 +54,15 @@ func (ctrl *ApplicationController) GetRepoObjs(origApp *appv1.Application, drySo
...
 	}
+	trackingMethod, err := ctrl.settingsMgr.GetTrackingMethod()
+	if err != nil {
+		return nil, nil, fmt.Errorf("failed to get tracking method: %w", err)
+	}
+	for _, obj := range objs {
+		if err := argoutil.NewResourceTracking().RemoveAppInstance(obj, trackingMethod); err != nil {
+			return nil, nil, fmt.Errorf("failed to remove the app instance value: %w", err)
+		}
+	}
```
Comment (crenshaw-dev) [inline controller/hydrator_dependencies.go:65]: Is there any chance we can test GetRepoObjs for this behavior? The ResourceTracking unit tests are awesome, but I think we could use something at a higher level too.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: docs/user-guide/source-hydrator.md (hunk 10 above)
Comment (nitishfy) [reply docs/user-guide/source-hydrator.md]: resolved.

File: controller/hydrator_dependencies.go (hunk 11 above)
Comment (nitishfy) [reply controller/hydrator_dependencies.go:65]: Done adding a test, please take a look now.

File: controller/hydrator_dependencies_test.go [hunk 12]
```diff
@@ -0,0 +1,77 @@
...
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"testing"
+	"time"
+)
+
+func TestGetRepoObjs(t *testing.T) {
+	cm := test.NewConfigMap()
+	cm.SetAnnotations(map[string]string{
+		"custom-annotation":             "custom-value",
+		common.AnnotationInstallationID: "id",     // tracking annotation should be removed
```
Comment (nitishfy) [inline controller/hydrator_dependencies_test.go:23]: The main purpose of setting this is just to keep track of whether these annotations gets removed or not. Although  Argo CD internally sets these tracking annotation and outputs the resource without those annotations but since we want to make sure those annotations are actually getting removed (that's the purpose of this test), we are adding it here to later test for their removal.

**Review by crenshaw-dev — APPROVED** [review]
LGTM, thanks! I'll set to auto-merge so it'll go in after lint fixes. :-)
