### PR TITLE
fix(ui): Don't try to show helm metadata

### LINKED ISSUE #5489: nginx Helm Version handling is broken
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I can't tell what kind of version it is, but it feels like it isn't git. The handler definitely assumes it's git.

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/ingress-nginx?view=tree
2. Click the more by current sync status

**Expected behavior**

Show a version

**Screenshots**

image
image

**Version**

```shell
{
    "Version": "v1.9.0+223335d",
    "BuildDate": "2021-02-11T01:58:55Z",
    "GitCommit": "223335d96e5bb054d6081c168f53898072bcac3a",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.1",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by rbreeze**
Signed-off-by: Remington Breeze <remington@breeze.software>

Fix #5489

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM

File: ui/src/app/applications/components/application-status-panel/application-status-panel.tsx [hunk 1]
```diff
@@ -95,13 +100,16 @@ export const ApplicationStatusPanel = ({application, showOperation, showConditio
...
-                                daysSinceLastSynchronized +
-                                ' days since last sync. Click for the status of that sync.'
-                        })}
+                        {sectionHeader(
+                            {
+                                title: 'LAST SYNC STATUS',
+                                helpContent:
+                                    'Whether or not your last app sync was successful. It has been ' +
+                                    daysSinceLastSynchronized +
+                                    ' days since last sync. Click for the status of that sync.'
```
Comment (jsoref) [inline ui/src/app/applications/components/application-status-panel/application-status-panel.tsx:109]: Shouldn't this use backtick notation instead of string concatenation?
