### PR TITLE
fix: return missing information in cluster get API

### LINKED ISSUE #25311: [API] Cluster GET does not return complete configuration
**Describe the bug**

When running a GET on the ArgoCD API to fetch a cluster's details, the value returned does not contain the full configuration. In our case, it does not return the `execProviderConfig` section.

**To Reproduce**

Create a cluster secret like so:
```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-test
  namespace: argocd
type: Opaque
stringData:
  config: '{"tlsClientConfig":{"insecure":false,"caData":"<redacted>"},"execProviderConfig":{"command":"argocd-k8s-auth","args":["azure"],"apiVersion":"client.authentication.k8s.io/v1beta1"}}'
  name: cluster-test
  server: https://<redacted>
```

Then, run the `GET` call by going to:
`https://<argocdUrl>/api/v1/clusters/cluster-test?id.type=name`

**Expected behavior**

I would expect to receive:
```json
{
  "server": "https://<redacted>",
  "name": "cluster-test",
  "config": {
    "tlsClientConfig": {
      "insecure": false,
      "caData":"<redacted>",
    },
    "execProviderConfig": {
      "command": "argocd-k8s-auth",
      "args": ["azure"],
      "apiVersion": "client.authentication.k8s.io/v1beta1",
    },
  },
  "connectionState": {
    "status": "Successful",
    "message": "",
    "attemptedAt": "2025-11-17T17:42:15Z"
  },
  "serverVersion": "1.33",
  "info": {
    "connectionState": {
      "status": "Successful",
      "message": "",
      "attemptedAt": "2025-11-17T17:42:15Z"
    },
    "serverVersion": "1.33",
    "cacheInfo": { "<redacted>" },
    "applicationsCount": 650,
    "apiVersions": [ "<redacted>" ],
  }
}
```

However I'm only getting the following:
```json
{
  "server": "https://<redacted>",
  "name": "cluster-test",
  "config": {
    "tlsClientConfig": {
      "insecure": false
    }
  },
  "connectionState": {
    "status": "Successful",
    "message": "",
    "attemptedAt": "2025-11-17T17:47:18Z"
  },
  "serverVersion": "1.33",
  "info": {
    "connectionState": {
      "status": "Successful",
      "message": "",
      "attemptedAt": "2025-11-17T17:47:18Z"
    },
    "serverVersion": "1.33",
    "cacheInfo": {
      "resourcesCount": 1325,
      "apisCount": 114,
      "lastCacheSyncTime": "2025-11-17T14:16:40Z"
    },
    "applicationsCount": 1,
    "apiVersions": [ "<redacted>" ],
  }
}
```

Notably, the `config` is incomplete and missing the `execProviderConfig` section entirely and missing details in the `tlsConfig` part as well.

**Version**

```json
{
    "Version": "v3.1.9+8665140",
    "BuildDate": "2025-10-17T21:35:08Z",
    "GitCommit": "8665140f96f6b238a20e578dba7f9aef91ddac51",
    "GitTreeState": "clean",
    "GoVersion": "go1.24.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.7.0 2025-06-28T07:00:07Z",
    "HelmVersion": "v3.18.4+gd80839c",
    "KubectlVersion": "v0.33.1",
    "JsonnetVersion": "v0.21.0"
}
```

**Side effect**

This has a side-effect in Crossplane's [provider-argocd](https://github.com/crossplane-contrib/provider-argocd) which uses the API to create Cluster connections and reconciliate them. During it's Observe flow, it always detects a drift between the desired state and what ArgoCD returns through the API. This forces the provider to always try to update the cluster connection indefinitely.

# EDIT
New proposal after comments in the PR:
Since most of the API currently does not return secrets in GET requests and cluster configs could contain secrets, it's better to stay consistent and leave it as it is.  However, we still need to be able to validate that the currently stored value matches our desired state.
The proposal is to add a new field which is either the `resourceVersion` matching the config or a hash of the whole config.

### PR DESCRIPTION
**Pull request by ppapapetrou76**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

In this #24387 PR, we started sanitizing cluster information to avoid returning sensitive information
However, we are missing some non-sensitive information.

this PR is addressing this issue and closes #25311

### CODE REVIEW

**Review by blakepettersson — APPROVED** [review]
LGTM

**Review by rumstead — APPROVED** [review]

**Comment by ppapapetrou76** [comment]
@crenshaw-dev I'm tagging you because you have made the sanitization PR to confirm that I'm not missing anything 

I know that we had [this](https://github.com/argoproj/argo-cd/pull/24387/files#diff-47255bee56d3ad7830d9721f65c73fac53009229cb98c63c67745527d598835bL480) in the past, so I want to confirm that it's ok to return them and let the users accountable of they are adding in there or keep th existing behavior

**Review by reggie-k — APPROVED** [review]
LGTM

**Review by todaywasawesome — APPROVED** [review]
LGTM

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -2291,8 +2291,10 @@ func (c *Cluster) Sanitized() *Cluster {
 			ProxyUrl:           c.Config.ProxyUrl,
 			DisableCompression: c.Config.DisableCompression,
 			TLSClientConfig: TLSClientConfig{
-				Insecure: c.Config.Insecure,
+				Insecure:   c.Config.Insecure,
+				ServerName: c.Config.ServerName,
 			},
+			ExecProviderConfig: c.Config.ExecProviderConfig,
```
Comment (crenshaw-dev) [inline pkg/apis/application/v1alpha1/types.go]: I think we assessed in the past that ExecProviderConfig isn't really safe to return since it may contain secrets, e.g. as args. I don't think that would be best practice, because those secrets would show up in the process table, but it's not out of the question.

I think @alexmt and I talked about this at one point. Any thoughts, Alex?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: pkg/apis/application/v1alpha1/types.go (hunk 1 above)
Comment (ppapapetrou76) [reply pkg/apis/application/v1alpha1/types.go]: > I think we assessed in the past that ExecProviderConfig isn't really safe to return since it may contain secrets, e.g. as args. I don't think that would be best practice, because those secrets would show up in the process table, but it's not out of the question.
> 
> I think @alexmt and I talked about this at one point. Any thoughts, Alex?

Yup, this is what I understood from the comments in the past. 
How about including only the exec command and omit the args / env 
Or how about dropping the ball on the user side, meaning that we do return them, but it's the user's responsibility NOT to include any sensitive information in these?

Comment (reggie-k) [reply pkg/apis/application/v1alpha1/types.go]: I think that the user does not necessarily have the control over the env section, as for example for execProviderConfig for Azure the user has to provide AZURE_CLIENT_ID or AZURE_CLIENT_SECRET and for AWS AWS_SECRET_ACCESS_KEY. But I have just realized that command name `argocd-k8s-auth` is always the same, so @ppapapetrou76 you were right saying we won't benefit much from returning it.

Comment (gravufo) [reply pkg/apis/application/v1alpha1/types.go]: In my opinion, if a user has access to get cluster information, he should be able to get all of it. Sensitive or not, he has access to it.
Just as a background to what started the issue: we use crossplane and [provider-argocd](https://github.com/crossplane-contrib/provider-argocd) to create Cluster connections. The provider uses the ArgoCD API to create and then fetch the object. However, the object fetched is never equal to the one created because it doesn't contain the execProvider section. This has the unfortunate side-effect of causing infinite reconciliation loops on Cluster objects for the provider.

Comment (crenshaw-dev) [reply pkg/apis/application/v1alpha1/types.go]: We've followed the standard of making secret info write-only across several APIs, and I'm hesitant to roll that back.

Does the Argo CD provider _have_ to use the Argo CD API? Could it instead use the k8s API?

Or would it be possible for provider-argocd to short-circuit the apply loop by inspecting some non-sensitive data, like a resourceVersion or a hash of the secret's contents?

Comment (gravufo) [reply pkg/apis/application/v1alpha1/types.go]: The provider _can_ use the k8s api (uses the argocd client in the background, so core mode is possible), but that's not always desirable, i.e. when talking to an ArgoCD in a different cluster where we don't necessarily have k8s API Server access.

The compare logic can be found here: https://github.com/crossplane-contrib/provider-argocd/blob/main/pkg/controller/cluster/cluster/controller.go#L396

So the answer is yes there are workarounds that could be done in the provider, however we would need certainty that the applied version is the same as the desired state. The idea of a resourceVersion or a hash is also good in my opinion.

I would need to validate with the provider maintainers if that is something they would want to merge though, but I don't see anything inherently bad with using this kind of approach.

Comment (crenshaw-dev) [reply pkg/apis/application/v1alpha1/types.go]: Sweet, so maybe let's start with the `resourceVersion` approach and see how far we could get with that?

Comment (blakepettersson) [reply pkg/apis/application/v1alpha1/types.go]: Another precedent is argoproj-labs/terraform-provider-argocd#780, where ExecProviderConfig is just not considered to be a part of the plan

Comment (gravufo) [reply pkg/apis/application/v1alpha1/types.go]: Interesting that they did it like that. I don't think it's a good approach since there is no way to detect drift in that case. I much prefer the resourceVersion/hash approach and it could then also be implemented in the terraform provider as well :)

Comment (ppapapetrou76) [reply pkg/apis/application/v1alpha1/types.go]: Thank you so much guys for the reviews and the insights. 
I will remove the code that returns the `ExecProviderConfig` but I want to keep the UT improvement because it's make it crystal clear that we don't return it and it is safety pillow for future changes. 

@gravufo do you mind opening a new ticket or update the existing one with the proposed solution of `resourceVersion` ?

Comment (gravufo) [reply pkg/apis/application/v1alpha1/types.go]: @ppapapetrou76 I edited my post in the issue. I didn't touch the initial content, because I think it's still interesting for someone who reads this in the future. The end of the post contains the edit which proposes using `resourceVersion` or a hash of the config.

Comment (crenshaw-dev) [reply pkg/apis/application/v1alpha1/types.go]: @ppapapetrou76 wanna also add back the comment explaining why we dont return the exec config?

**Comment by ppapapetrou76** [comment]
@crenshaw-dev I updated the PR to improve the tests and added back the comment to make it crystal clear why the code should not return the `ExecProviderConfig` in the cluster API 

feel free to review and merge when possible

**Review by crenshaw-dev — APPROVED** [review]
