### PR TITLE
fix: limit number of resources in appset status

### LINKED ISSUE #24689: Appset fails to update status with " Request entity too large" error
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

An application set controller fails to update application set status with " Request entity too large" error. 

**To Reproduce**

After investigation we've discovered that error is happening because application set controller stores each produced app info in status. With large number of applications that status grows too much and eventually exceeds 3145728 bytes limit.

**Expected behavior**

The number of managed applications should not be limited by k8s sub-resource size

**Version**

```shell
v3.1.6
```

**Logs**

```
argocd-applicationset-controller-7fdbf6dbcb-px428 argocd-applicationset-controller {"ApplicationSet":"<REDUCTED>","controller":"applicationset","controllerGroup":"argoproj.io","controllerKind":"ApplicationSet","error":"failed to get update resources status for application set: unable to set application set status: Request entity too large: limit is 3145728","level":"error","msg":"Reconciler error","name":"REDUCTED","namespace":"argocd","reconcileID":"fdfbcffe-c16f-4a9b-98e4-0e3fe82c62ef","time":"2025-09-19T21:49:57Z"}
```

### PR DESCRIPTION
**Pull request by alexmt**
Closes https://github.com/argoproj/argo-cd/issues/24689

The `applicationSet.status.resources` is meant for appset visualization in a future UI/CLI. However it limits the number of applications that can be managed by a single appset.

The desire to build UI should not limit core functionality of application set. From experience of building application tree visualization we know that 1000+ resources is already hard to scale. So in this PR I'm proposing to introduce `ARGOCD_APPLICATIONSET_CONTROLLER_MAX_RESOURCES_STATUS_COUNT` that limits number of resources stored in status (5k by default). So this way appset can generate any number of apps and in a future UI we can add a warning that only first 5k is shown.

### CODE REVIEW

**Review by nitishfy — COMMENTED** [review]
Thank you! The changes looks good to me. Few points:

1. Can you please add unit test [here](https://github.com/argoproj/argo-cd/blob/master/applicationset/controllers/applicationset_controller_test.go#L5964)?
2. The lint check is failing that needs to be fixed.

**Comment by alexmt** [comment]
Thanks for looking at PR @nitishfy !

* Can you please add unit test [here](https://github.com/argoproj/argo-cd/blob/master/applicationset/controllers/applicationset_controller_test.go#L5964)?
This is already done: https://github.com/argoproj/argo-cd/pull/24690/files#diff-88fec9c8d881ff513bb04ee8842efcc4f0db0ec0ce631fec3f730633a91ebea6R6137

* The lint check is failing that needs to be fixed.
Fixes - thank you!

**Comment by crenshaw-dev** [comment]
Should we have a condition to indicate the truncation to the user/UI?

File: cmd/argocd-applicationset-controller/commands/applicationset_controller.go [hunk 1]
```diff
@@ -275,6 +277,7 @@ func NewCommand() *cobra.Command {
 	command.Flags().IntVar(&webhookParallelism, "webhook-parallelism-limit", env.ParseNumFromEnv("ARGOCD_APPLICATIONSET_CONTROLLER_WEBHOOK_PARALLELISM_LIMIT", 50, 1, 1000), "Number of webhook requests processed concurrently")
 	command.Flags().StringSliceVar(&metricsAplicationsetLabels, "metrics-applicationset-labels", []string{}, "List of Application labels that will be added to the argocd_applicationset_labels metric")
 	command.Flags().BoolVar(&enableGitHubAPIMetrics, "enable-github-api-metrics", env.ParseBoolFromEnv("ARGOCD_APPLICATIONSET_CONTROLLER_ENABLE_GITHUB_API_METRICS", false), "Enable GitHub API metrics for generators that use the GitHub API")
+	command.Flags().IntVar(&maxResourcesStatusCount, "max-resources-status-count", env.ParseNumFromEnv("ARGOCD_APPLICATIONSET_CONTROLLER_MAX_RESOURCES_STATUS_COUNT", 5000, 0, math.MaxInt), "Max number of resources stored in appset status.")
```
Comment (crenshaw-dev) [inline cmd/argocd-applicationset-controller/commands/applicationset_controller.go]: Also add to argocd-cmd-params-cm? (Both the vended and the example files.)

Comment (alexmt) [reply cmd/argocd-applicationset-controller/commands/applicationset_controller.go]: Done!

**Comment by alexmt** [comment]
Thanks for review @crenshaw-dev !

> Should we have a condition to indicate the truncation to the user/UI?

I was thinking about too while writing PR description. Added `status.resourcesCount` with the number of resources before truncation. This way UI warning can have e.g. `Warning: 100 more applications are hidden" .

File: pkg/apis/application/v1alpha1/applicationset_types.go [hunk 2]
```diff
@@ -804,7 +804,8 @@ type ApplicationSetStatus struct {
 	Conditions        []ApplicationSetCondition         `json:"conditions,omitempty" protobuf:"bytes,1,name=conditions"`
 	ApplicationStatus []ApplicationSetApplicationStatus `json:"applicationStatus,omitempty" protobuf:"bytes,2,name=applicationStatus"`
 	// Resources is a list of Applications resources managed by this application set.
-	Resources []ResourceStatus `json:"resources,omitempty" protobuf:"bytes,3,opt,name=resources"`
+	Resources      []ResourceStatus `json:"resources,omitempty" protobuf:"bytes,3,opt,name=resources"`
+	ResourcesCount int64            `json:"resourcesCount,omitempty" protobuf:"varint,4,opt,name=resourcesCount"`
```
Comment (crenshaw-dev) [inline pkg/apis/application/v1alpha1/applicationset_types.go]: Probably wants a doc string so the future UI dev knows how to use this.

Are you hoping to cherry-pick the change back? I think for 3.2 it would be fine, but adding a CRD field further back feels maybe not great.

Comment (alexmt) [reply pkg/apis/application/v1alpha1/applicationset_types.go]: ah, you are right. What do you think about adding `resourcesCount` in a separate PR? The UI functionality is not ready yet, so we are not loosing anything without `resourcesCount`. We can cherry-pick first PR into previous release and `resourcesCount` can go only to `master` branch.

Comment (alexmt) [reply pkg/apis/application/v1alpha1/applicationset_types.go]: I've moved change to a separate commit: https://github.com/argoproj/argo-cd/commit/d5e690f832c8c7dd4dfece8a8b566b419d7531e7 . If you are fine with it, I will create new PR as soon as this one merged.

**Review by crenshaw-dev — APPROVED** [review]
