### PR TITLE
fix: downgrade DiffFromCache log level for cache-miss errors

### LINKED ISSUE #5068: Error log on missing cache key
Hello

I getting this error log sometimes:

```
[argo-cd-argocd-server-bf74d748b-2xmgb] time="2020-12-16T03:45:46Z" level=error msg="finished streaming call with code Unknown" error="cache: key is missing" grpc.code=Unknown grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2020-12-16T03:45:22Z" grpc.time_ms=24038.105 span.kind=server system=grpc
```

I can see that it is marked as level error
In my opinion missing key cache could be warning level instead

What do you think ?

### PR DESCRIPTION
**Pull request by cp319391**
**Summary**

This PR downgrades the log level for DiffFromCache errors caused by expected Redis cache misses (specifically cache: key is missing) from ERROR to WARN, while preserving ERROR logs for genuine Redis failures.

The diff behaviour and control flow are unchanged; Argo CD continues to fall back to a non-cache diff when the cache is unavailable.

**Motivation**

In Redis HA / Sentinel setups, cache misses are expected during events such as:
- Redis restarts
- Sentinel master failovers
- Replica resynchronisation

In these scenarios, Argo CD currently logs `DiffFromCache` failures at `ERROR` level even though:
- The cache is best-effort and rebuildable
- Applications recover automatically
- No user action is required

This results in repeated error-level log noise and false alerts in otherwise healthy clusters.

**What this PR changes**
- Downgrades the log level to WARN when the error message contains cache: key is missing
- Retains ERROR level logging for all other Redis/cache errors (e.g. connection refused, timeouts, auth failures)
- Does not change application behaviour, reconcile logic, or diff results

**Why this is safe**
- Cache misses already trigger a fallback to live diff
- No functional or behavioural changes are introduced
- Only the log severity is adjusted for a known benign case

**Scope**
- No CLI changes
- No UI changes
- No API changes
- No documentation changes required

**Related issues**

Fixes: #5068

### CODE REVIEW

File: util/argo/diff/diff.go [hunk 1]
```diff
@@ -400,7 +401,11 @@ func (c *diffConfig) DiffFromCache(appName string) (bool, []*v1alpha1.ResourceDi
 	if c.stateCache != nil {
 		err := c.stateCache.GetAppManagedResources(appName, &cachedDiff)
 		if err != nil {
-			log.Errorf("DiffFromCache error: error getting managed resources for app %s: %s", appName, err)
+			if strings.Contains(err.Error(), "cache: key is missing") {
```
Comment (ppapapetrou76) [inline util/argo/diff/diff.go]: Instead of using a hard-coded value that is vulnerable to future changes, wouldn't it be better to check that the error is `ErrCacheMiss`?

**Comment by ppapapetrou76** [comment]
Looks like tests are failing @cp319391

**Comment by cp319391** [comment]
@ppapapetrou76 
Please check now. Thanks

File: util/argo/diff/diff.go [hunk 2]
```diff
@@ -397,15 +397,16 @@ func (c *diffConfig) DiffFromCache(appName string) (bool, []*v1alpha1.ResourceDi
 		return false, nil
 	}
 	cachedDiff := make([]*v1alpha1.ResourceDiff, 0)
-	if c.stateCache != nil {
-		err := c.stateCache.GetAppManagedResources(appName, &cachedDiff)
-		if err != nil {
+	err := c.stateCache.GetAppManagedResources(appName, &cachedDiff)
+	if err != nil {
+		if errors.Is(err, appstatecache.ErrCacheMiss) {
+			log.Warnf("DiffFromCache warning: error getting managed resources for app %s: %s", appName, err)
```
Comment (ppapapetrou76) [inline util/argo/diff/diff.go]: Is this a warning or an error? :) reading this, I'm confused 

Maybe something like

```suggestion
			log.Warnf("DiffFromCache warning: cannot get managed resources for app %s: %s", appName, err)
```

**Review by ppapapetrou76 — APPROVED** [review]
LGTM 🏅  - thanks for addressing my comments

I left one more to improve the log and avoid future confusion

**Comment by cp319391** [comment]
any plan to consider this PR for review @nitishfy

File: util/argo/diff/diff.go [hunk 3]
```diff
@@ -397,15 +397,16 @@ func (c *diffConfig) DiffFromCache(appName string) (bool, []*v1alpha1.ResourceDi
 		return false, nil
 	}
 	cachedDiff := make([]*v1alpha1.ResourceDiff, 0)
-	if c.stateCache != nil {
-		err := c.stateCache.GetAppManagedResources(appName, &cachedDiff)
-		if err != nil {
+	err := c.stateCache.GetAppManagedResources(appName, &cachedDiff)
+	if err != nil {
+		if errors.Is(err, appstatecache.ErrCacheMiss) {
+			log.Warnf("DiffFromCache warning: cannot get managed resources for app %s: %s", appName, err)
```
Comment (nitishfy) [inline util/argo/diff/diff.go]:
```suggestion
			log.Warnf("DiffFromCache: cannot get managed resources for app %s: %s", appName, err)
```
the word _warning_ is redundant provided it's already a `Warnf` call.

**Review by nitishfy — CHANGES_REQUESTED** [review]
Two small additions please:

1. Please add a test covering the cache-miss warn path vs. the other-error error path would make this more robust.
2. (Optional):  The branch has 9+commits for a 13-line change. Consider squashing before merge.

**Comment by cp319391** [comment]
@nitishfy @ppapapetrou76 would you like to review it again.

File: util/argo/diff/diff.go [hunk 4]
```diff
@@ -397,15 +397,16 @@ func (c *diffConfig) DiffFromCache(appName string) (bool, []*v1alpha1.ResourceDi
 		return false, nil
 	}
 	cachedDiff := make([]*v1alpha1.ResourceDiff, 0)
-	if c.stateCache != nil {
```
Comment (alexrecuenco) [inline util/argo/diff/diff.go:400]: > The diff behaviour and control flow are unchanged; Argo CD continues to fall back to a non-cache diff when the cache is unavailable.

however, the c.stateCache is no longer checked, can you help me understand?

**Review by nitishfy — APPROVED** [review]
LGTM!

File: util/argo/diff/diff.go (hunk 4 above)
Comment (cp319391) [reply util/argo/diff/diff.go:400]: it gets checked here on line 396 `if c.noCache || c.stateCache == nil || appName == "" {`

**Review by agaudreault — APPROVED** [review]

File: util/argo/diff/diff.go (hunk 4 above)
Comment (alexrecuenco) [reply util/argo/diff/diff.go:400]: the git fragment GitHyb was displaying was cutting just before that line :)
