### PR TITLE
fix(appset): Reconcile appset only once when appset is refreshed (#21171)

### LINKED ISSUE #21171: ApplicationSet are reconciled twice when refreshed
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When an ApplicationSet is refreshed (via a webhook call or annotating it), the reconcile loop is done twice in appset controller.
Maybe in most of the case this is not an issue, because we rely on things that are cached by Argo.
But when you use Plugin generator, backend receive twice as many requests. This issue combined with #20830 can lead to flood your backend.

**To Reproduce**

- Create a simple appset (create only two apps, based on a noop chart) : 
```shell
k apply -f https://raw.githubusercontent.com/dacofr/hello-appset/refs/heads/main/git-appset.yaml
```
- Send a webhook:
```shell
kubectl port-forward svc/argocd-applicationset-controller 7000:7000

curl -X "POST" -H "Content-Type: application/json" -H "X-Github-Event: push" \
-d '{"ref": "refs/heads/main", "repository": {"html_url": "https://github.com/dacofr/hello-appset", "default_branch": "main"}}' \
http://localhost:7000/api/webhook
```
- We can simulate by annotating it with **argocd.argoproj.io/application-set-refresh** annotation
```shell
k annotate appset hello-git-appset argocd.argoproj.io/application-set-refresh=true
```

**Expected behavior**

ApplicationSet are reconciled only once. 

For me, issue come to fact that Appset object is updated twice : 

1. One time to add annotation to force entering in reconcile loop
2. Second time, because we remove annotation ([here](https://github.com/argoproj/argo-cd/blob/master/applicationset/controllers/applicationset_controller.go#L314)) so we enter again in reconcile loop

**Version**

Tested with commit master be080a531
But 2.11 has same issue (current running version in our production) 

**Logs**

```
## webhook called and just after we reconcile twice
time="2024-12-13T15:38:45Z" level=info msg="Received push event repo: https://github.com/dacofr/hello-appset, revision: main, touchedHead: true"
time="2024-12-13T15:38:45Z" level=info msg="refresh ApplicationSet argocd/hello-git-appset from webhook"
time="2024-12-13T15:38:46Z" level=info msg="generated 2 applications" applicationset=argocd/hello-git-appset
time="2024-12-13T15:38:46Z" level=info msg="end reconcile in 250.026842ms" applicationset=argocd/hello-git-appset requeueAfter=3m0s 
time="2024-12-13T15:38:46Z" level=info msg="generated 2 applications" applicationset=argocd/hello-git-appset
time="2024-12-13T15:38:46Z" level=info msg="end reconcile in 20.094022ms" applicationset=argocd/hello-git-appset requeueAfter=3m0s
## same here
time="2024-12-13T15:38:50Z" level=info msg="Received push event repo: https://github.com/dacofr/hello-appset, revision: main, touchedHead: true"
time="2024-12-13T15:38:50Z" level=info msg="refresh ApplicationSet argocd/hello-git-appset from webhook"
time="2024-12-13T15:38:50Z" level=info msg="generated 2 applications" applicationset=argocd/hello-git-appset
time="2024-12-13T15:38:50Z" level=info msg="end reconcile in 264.838319ms" applicationset=argocd/hello-git-appset requeueAfter=3m0s 
time="2024-12-13T15:38:50Z" level=info msg="generated 2 applications" applicationset=argocd/hello-git-appset
time="2024-12-13T15:38:50Z" level=info msg="end reconcile in 20.415265ms" applicationset=argocd/hello-git-appset requeueAfter=3m0s
## same here
time="2024-12-13T15:38:51Z" level=info msg="Received push event repo: https://github.com/dacofr/hello-appset, revision: main, touchedHead: true"
time="2024-12-13T15:38:51Z" level=info msg="refresh ApplicationSet argocd/hello-git-appset from webhook"
time="2024-12-13T15:38:51Z" level=info msg="generated 2 applications" applicationset=argocd/hello-git-appset
time="2024-12-13T15:38:51Z" level=info msg="end reconcile in 341.74681ms" applicationset=argocd/hello-git-appset requeueAfter=3m0s
time="2024-12-13T15:38:51Z" level=info msg="generated 2 applications" applicationset=argocd/hello-git-appset
time="2024-12-13T15:38:51Z" level=info msg="end reconcile in 19.232116ms" applicationset=argocd/hello-git-appset requeueAfter=3m0s
```

### PR DESCRIPTION
**Pull request by dacofr**
Fixes #21171 

Currently, when webhook wants to refresh an appset, it's done by setting this annotation :  **argocd.argoproj.io/application-set-refresh** via  [refreshApplicationSet](https://github.com/argoproj/argo-cd/blob/master/applicationset/webhook/webhook.go#L149) method. 

After that, appset controller enter the reconcile loop because he receives a change on Kubernetes object,
after processing the appset, the controller removes the annotation, which has the consequence to enter again in reconcile loop (because Kubernetes object is updated a second time).

In current PR, we implement an `EventFilter` to not requeue the second appset change, based on logic :
` if oldAppSet has refreshAnnotation and newAppSet do not have refreshAnnotation also do not requeue`.

Signed-off-by: Philippe Da Costa <pdacosta@gmail.com>

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by rumstead** [comment]
I don't think we should change the annotation removal and addition logic to rely on timestamps. What I would suggest is adding logic when we decide to requeue an applicationset. 

I made similar changes for deciding when we requeue applicationsets based on applications changing [here](https://github.com/argoproj/argo-cd/blob/72c711e7f06f633a63b15e94946a2e76e9922619/applicationset/controllers/applicationset_controller.go#L1531).

**Review by nitishfy — CHANGES_REQUESTED** [review]
Thanks for raising the PR. Please go through the @rumstead comment and see if you can follow the approach he mentioned to requeue the applicationset.

**Comment by dacofr** [comment]
Thanks for your replies :+1: 

Yes, I will have a look on how requeue mechanism works.
If I understand well, I need to build predicates for Appset CR, inject those predicates here : 
```
return ctrl.NewControllerManagedBy(mgr).WithOptions(controller.Options{
		MaxConcurrentReconciles: maxConcurrentReconciliations,
	}).For(&argov1alpha1.ApplicationSet{}, builder.WithPredicates(--> HERE <--)).
		Owns(&argov1alpha1.Application{}, builder.WithPredicates(ownsHandler)).
```
and inside predicates, when UpdateFunc is called we can decide if we want to requeue or not an appset.
For example : `if oldAppSet has refreshAnnotation and newAppSet do not have refreshAnnotation also requeue = false`

I'm right ?

File: applicationset/generators/git.go [hunk 1]
```diff
@@ -84,9 +82,9 @@ func (g *GitGenerator) GenerateParams(appSetGenerator *argoprojiov1alpha1.Applic
 	var err error
 	var res []map[string]interface{}
 	if len(appSetGenerator.Git.Directories) != 0 {
-		res, err = g.generateParamsForGitDirectories(appSetGenerator, noRevisionCache, verifyCommit, appSet.Spec.GoTemplate, appSet.Spec.GoTemplateOptions)
+		res, err = g.generateParamsForGitDirectories(appSetGenerator, true, verifyCommit, appSet.Spec.GoTemplate, appSet.Spec.GoTemplateOptions)
```
[the remark this answers is not in the document]
Comment (dacofr) [reply applicationset/generators/git.go:85]: I think I get your point :+1: 
Naively, I thought that git generator was called only once per appset, when appset need to be refresh.
But maybe in fact the git generator is called several time for the same appset ? And in this case it make sense to use git ls-remote cache.

**Comment by rumstead** [comment]
> Thanks for your replies 👍
> 
> Yes, I will have a look on how requeue mechanism works. If I understand well, I need to build predicates for Appset CR, inject those predicates here :
> 
> ```
> return ctrl.NewControllerManagedBy(mgr).WithOptions(controller.Options{
> 		MaxConcurrentReconciles: maxConcurrentReconciliations,
> 	}).For(&argov1alpha1.ApplicationSet{}, builder.WithPredicates(--> HERE <--)).
> 		Owns(&argov1alpha1.Application{}, builder.WithPredicates(ownsHandler)).
> ```
> 
> and inside predicates, when UpdateFunc is called we can decide if we want to requeue or not an appset. For example : `if oldAppSet has refreshAnnotation and newAppSet do not have refreshAnnotation also requeue = false`
> 
> I'm right ?

That logic is sound to me!

**Comment by dacofr** [comment]
Hey @rumstead, @nitishfy 
I updated logic to use EventFilter to not requeue the appset on the second update.
If you have time to have a look :pray:

File: applicationset/controllers/applicationset_controller.go [hunk 2]
```diff
@@ -532,6 +532,27 @@ func ignoreNotAllowedNamespaces(namespaces []string) predicate.Predicate {
...
 }
 
+// ignoreWhenAnnotationApplicationSetRefreshIsRemoved returns a predicate that ignores updates to ApplicationSet resources
+// when the ApplicationSetRefresh annotation is removed
+// First reconciliation is triggered when the annotation is added by [webhook.go#refreshApplicationSet]
+// Using this predicate we avoid a second reconciliation triggered by the controller himself when the annotation is removed.
+func ignoreWhenAnnotationApplicationSetRefreshIsRemoved() predicate.Predicate {
+	return predicate.Funcs{
+		UpdateFunc: func(e event.UpdateEvent) bool {
+			oldAppset, _ := e.ObjectOld.(*argov1alpha1.ApplicationSet)
```
Comment (rumstead) [inline applicationset/controllers/applicationset_controller.go:542]: we should validate that the cast was successful for each object.

File: applicationset/controllers/applicationset_controller.go [hunk 3]
```diff
@@ -532,6 +532,27 @@ func ignoreNotAllowedNamespaces(namespaces []string) predicate.Predicate {
...
+			newAppset, _ := e.ObjectNew.(*argov1alpha1.ApplicationSet)
+
+			_, oldHasRefreshAnnotation := oldAppset.Annotations[common.AnnotationApplicationSetRefresh]
```
Comment (rumstead) [inline applicationset/controllers/applicationset_controller.go:545]: could annotations be nil here?

File: applicationset/controllers/applicationset_controller.go [hunk 4]
```diff
@@ -560,6 +581,7 @@ func (r *ApplicationSetReconciler) SetupWithManager(mgr ctrl.Manager, enableProg
 	}).For(&argov1alpha1.ApplicationSet{}).
```
Comment (rumstead) [inline applicationset/controllers/applicationset_controller.go:581]:
```suggestion
For(&argov1alpha1.ApplicationSet{}, builder.WithPredicates(ignoreWhenAnnotationApplicationSetRefreshIsRemoved())).
```
`WithEventFilter` will run for all objects that trigger a reconciliation. In this case, it would be `applications` and `applicationsets`. I suggest we move the predicate for applicationsets unless there is a good reason not to.

**Comment by rumstead** [comment]
> Hey @rumstead, @nitishfy I updated logic to use EventFilter to not requeue the appset on the second update. If you have time to have a look 🙏

Thanks! Added a few comments. Side note, were you able to test this in a local cluster?

**Comment by dacofr** [comment]
Hello,

Back after some days off  :santa: :smiley: 
Following your recommendation, I update PR to use predicate at appset level (and not `WithEventFilter`)

> Thanks! Added a few comments. Side note, were you able to test this in a local cluster?

I tested in a Kind cluster, and got strange behaviour due to the fact that I used `WithEventFilter`, now seems we are fine.

File: applicationset/controllers/applicationset_controller.go (hunk 3 above)
Comment (dacofr) [reply applicationset/controllers/applicationset_controller.go:545]: Even, if annotations are nil, Golang tolerate to index a nil map (but not add values to it).
So it's not necessary to add a safeguard in this case.

File: applicationset/controllers/applicationset_controller.go (hunk 4 above)
Comment (dacofr) [reply applicationset/controllers/applicationset_controller.go]: You were right, using WithEventFilter was a bad idea, Moving predicate for appset is enough.

File: applicationset/controllers/applicationset_controller.go (hunk 2 above)
Comment (dacofr) [reply applicationset/controllers/applicationset_controller.go:542]: We can add a safeguard to be sure that the cast will success,
but now that we moved predicate to appset level : 
```
.For(&argov1alpha1.ApplicationSet{},builder.WithPredicates(ignoreWhenAnnotationApplicationSetRefreshIsRemoved()))
```
can we receive something other than AppSet ?

Comment (rumstead) [reply applicationset/controllers/applicationset_controller.go:542]: is there any reason not to handle the error if it happens?

Comment (dacofr) [reply applicationset/controllers/applicationset_controller.go]: No specific reason :smiley:  edited just now to add a safeguard in case of cast failed

**Review by rumstead — APPROVED** [review]
LGTM

**Review by agaudreault — APPROVED** [review]
LGTM

**Comment by dacofr** [comment]
Thanks :smile:
