### PR TITLE
fix: correctly compare application destinations with inferred cluster URL

### LINKED ISSUE #4926: Constant git requests on v1.8.0-rc1
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading to v1.8.0-rc1, we noticed that git requests (ls-remote / checkout) continues to increase, this is hammering our git server.

We have a mono repo with 500 helm chart applications and have included `.argocd-allow-concurrency`, we then scaled the application-controller with 5 replicas and set `ARGOCD_CONTROLLER_REPLICAS=5`.

**To Reproduce**

```bash
# argo application controller
argocd-application-controller --status-processors 50 --operation-processors 25 --repo-server-timeout-seconds 900 --app-resync 86400 --app-state-cache-expiration 1h0m0s --self-heal-timeout-seconds 5 --loglevel info --sentinel argocd-redis-master-0.argocd-redis-headless.argocd.svc:26379 --sentinel argocd-redis-slave-0.argocd-redis-headless.argocd.svc:26379 --sentinel argocd-redis-slave-1.argocd-redis-headless.argocd.svc:26379 --sentinelmaster argocd
```

**Expected behavior**

Application controller to not be constantly causing git-requests.

**Screenshots**

The end of the 26th is when we deployed v1.8.0-rc1 (where the huge spike is).

Here's a chart of the metrics for repo server for the last 7 days, the spikes are the `--app-resync`, otherwise the syncs are 0 (`ARGOCD_CONTROLLER_REPLICAS=5`):

Screen Shot 2020-11-27 at 9 37 36 PM

We deployed `v1.8.0-rc1` on the 26th, where we can see a huge spike in git requests (`ARGOCD_CONTROLLER_REPLICAS=5`):

Screen Shot 2020-11-27 at 9 40 17 PM

After that huge spike, the requests become constant at ~60 (`ARGOCD_CONTROLLER_REPLICAS=5`):

Screen Shot 2020-11-27 at 9 41 40 PM

Here's a chart going from 0 application controllers to 1 to demonstrate the rise in syncing (`ARGOCD_CONTROLLER_REPLICAS=1`):

Screen Shot 2020-11-27 at 9 02 09 PM

**Version**

```shell
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:46:53Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.0-rc1+868516f
  BuildDate: 2020-11-25T18:14:46Z
  GitCommit: 868516f0bd03e067d9252ca4030e0b291594aff2
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
```

**Logs**

We notice this in the application logs:

```
2020-11-28T05:03:36.652593013Z time="2020-11-28T05:03:36Z" level=info msg="Refreshing app status (spec.destination differs), level (2)" application=test
```

Could this be causing the constant git checkouts?

### PR DESCRIPTION
**Pull request by alexmt**
Fixes https://github.com/argoproj/argo-cd/issues/4926

Argo CD incorrectly performs full app reconciliation if app destination contains cluster name instead of cluster URL

Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

### CODE REVIEW

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -2398,6 +2398,17 @@ func (source *ApplicationSource) ExplicitType() (*ApplicationSourceType, error)
 
 // Equals compares two instances of ApplicationDestination and return true if instances are equal.
 func (dest ApplicationDestination) Equals(other ApplicationDestination) bool {
+	// ignore destination cluster name and isServerInferred fields during comparison
```
Comment (kshamajain99) [inline pkg/apis/application/v1alpha1/types.go:2401]: Do you mean to say that "ignore destination cluster URL" because we are setting `dest.Server = ""`?

**Review by kshamajain99 — APPROVED** [review]

**Review by mayzhang2000 — APPROVED** [review]
LGTM
