### PR TITLE
fix: webhook handler fails to refresh when alternate application namespaces are configured

### LINKED ISSUE #13158: Git Webhooks not working when "Applications in any namespace" is configured
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When "Applications in any namespace" is configured, git push events do not trigger a repo refresh

**To Reproduce**

1. Install Argo CD from https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/ha/install.yaml
2. Follow the instructions on https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/ to enable Applications in any namespace, with or without following recommended step for changing resource tracking methods.
3. Create an application linked to a git repository
4. Push a change to that repository

This happens regardless of whether the application is in the argocd namespace, or a separate namespace. With the additional namespaces disabled, updates work as expected.

**Expected behavior**

Argo CD should trigger an immediate refresh of any applications that use the repository.

**Version**

```shell
v2.7.0-rc1+0d0d2a9.dirty
and
v2.6.7
```

**Logs**

```
time="2023-04-07T18:50:45Z" level=info msg="Received push event repo: https://git.redacted/kubernetes/tkg-prod/mgr, revision: main, touchedHead: true"
time="2023-04-07T18:50:45Z" level=debug msg="https://git.redacted/kubernetes/tkg-prod/applications.git does not match (?i)^(http://|https://|[a-zA-Z0-9_\\.][a-zA-Z0-9_\\.-]{0,30}[a-zA-Z0-9_\\.\\$-]?@|ssh://([a-zA-Z0-9_\\.][a-zA-Z0-9_\\.-]{0,30}[a-zA-Z0-9_\\.\\$-]?@)?)git\\.lebow\\.drexel\\.edu(:[0-9]+|)[:/]kubernetes/tkg-prod/mgr(\\.git)?$"
time="2023-04-07T18:50:45Z" level=debug msg="https://git.redacted/kubernetes/tkg-prod/mgr.git uses repoURL https://git.redacted/kubernetes/tkg-prod/mgr"
time="2023-04-07T18:50:45Z" level=warning msg="Failed to refresh app 'applications-mgr' for controller reprocessing: error patching annotations in application \"applications-mgr\": the server could not find the requested resource (patch applications.argoproj.io applications-mgr)"
time="2023-04-07T18:50:45Z" level=debug msg="https://git.redacted/kubernetes/tkg-prod/mgr.git uses repoURL https://git.redacted/kubernetes/tkg-prod/mgr"
time="2023-04-07T18:50:45Z" level=warning msg="Failed to refresh app 'hello-world' for controller reprocessing: error patching annotations in application \"hello-world\": the server could not find the requested resource (patch applications.argoproj.io hello-world)"
```

### PR DESCRIPTION
**Pull request by Niksko**
Closes https://github.com/argoproj/argo-cd/issues/13158.

There were already tests for this, this implementation work was done, but it was missing the fact that the application interface doesn't have a namespace, which means that the patch action that causes a refresh can't possibly succeed.

This updates the tests to catch this, and then correctly namespaces the application interface so that this works.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

File: util/webhook/webhook_test.go [hunk 1]
```diff
@@ -149,10 +149,14 @@ func TestGitHubCommitEvent_MultiSource_Refresh(t *testing.T) {
 func TestGitHubCommitEvent_AppsInOtherNamespaces(t *testing.T) {
 	hook := test.NewGlobal()
 
-	patchedApps := make([]string, 0, 3)
+	type nameAndNamespace struct {
+		Name      string
+		Namespace string
+	}
```
Comment (jaideepr97) [inline util/webhook/webhook_test.go:155]: @Niksko can we just use standard `types.namespacedName` here instead of defining a new struct?
https://pkg.go.dev/k8s.io/apimachinery/pkg/types#NamespacedName

**Review by todaywasawesome — CHANGES_REQUESTED** [review]
https://github.com/argoproj/argo-cd/pull/13976/files#r1224266040

Ideally we'd use the existing struct, if it doesn't work let me know.

**Comment by Niksko** [comment]
Thanks for the review @jaideepr97 and @todaywasawesome, I've fixed that up, ready for another review

**Comment by Niksko** [comment]
> @Niksko could you take a look at the test failure? other than this looks good to me

@jaideepr97 Looks like it was a transient thing

**Review by jaideepr97 — APPROVED** [review]

**Comment by mugioka** [comment]
@crenshaw-dev 

Please review this.
I need this pr changes!!!!!!!!

**Review by crenshaw-dev — APPROVED** [review]
Thank you, @Niksko, and thanks others for your patience! :-)
