### PR TITLE
fix: Allow to delete repos with invalid urls (#20921)

### LINKED ISSUE #20921: Trying to delete a repo I added by mistake and getting "permission denied"
Checklist:

* [ V ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ V ] I've included steps to reproduce the bug.
* [ V ] I've pasted the output of `argocd version`.

**Describe the bug**
I've copy paste git url from bitbucket, not sure why, they provide it with `git clone` command in prefix, and by mistake I've try to add the repo like that.
After I saw the connection status fail and I added it in right way, but now I'm not able to delete the wrong typo, not from CLI and not from UI.

**To Reproduce**
Instead put git http url, add `git clone https://bitbucket.org/workspace/repo.git`

**Expected behavior**
Just allow to delete

**Screenshots**
image

**Version**

```shell
➜  ~ argocd version
argocd: v2.12.6+4dab5bd
  BuildDate: 2024-10-18T21:32:12Z
  GitCommit: 4dab5bd6a60adea12e084ad23519e35b710060a2
  GitTreeState: clean
  GoVersion: go1.23.2
  Compiler: gc
  Platform: darwin/arm64
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**
This is me trying to delete the repo from CLI
```
➜  ~ argocd repo rm "git clone https://bitbucket.org/workspace/repo.git"
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
FATA[0001] rpc error: code = PermissionDenied desc = permission denied 
```

I did not saw any related logs in ArgoCD NS after trying to run the command or delete from UI, here is the last logs I saw:
image

### PR DESCRIPTION
**Pull request by andrii-korotkov-verkada**
Fixes #20921

Normalization of repo url is attempted during repo deletion before comparison with existing repos. Before this change, it'd fail on invalid urls and return "", resulting in permission denied. This ended up in a state where people can add repos with invalid urls but couldn't delete them. Return raw repo url if url parsing failed. Add a test to validate the deletion can be performed and make sure it fails without the main change.

This needs to be cherry-picked to v2.11-2.13

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by reggie-k — APPROVED** [review]

File: util/git/git.go [hunk 1]
```diff
@@ -45,6 +45,16 @@ func SameURL(leftRepo, rightRepo string) bool {
 // Prefer using SameURL() over this function when possible. This algorithm may change over time
 // and should not be considered stable from release to release
 func NormalizeGitURL(repo string) string {
+	return normalizeGitURL(repo, false)
+}
+
+// Similar to NormalizeGitURL, except returning a not fully normalized string when the url is invalid.
+// Needed to allow a deletion of repos with invalid urls. See https://github.com/argoproj/argo-cd/issues/20921.
+func NormalizeGitURLAllowInvalid(repo string) string {
+	return normalizeGitURL(repo, true)
```
Comment (pasha-codefresh) [inline util/git/git.go:54]: I think it will be better not to add allowInvalid parameter to private function. Can we just return original "repo" in case if error happens ? In such case you will not need to modify with additional conditions normalizeGitURL function

**Review by pasha-codefresh — CHANGES_REQUESTED** [review]

File: util/git/git.go (hunk 1 above)
Comment (andrii-korotkov-verkada) [reply util/git/git.go]: I've made the change.

**Review by pasha-codefresh — APPROVED** [review]

**Comment by andrii-korotkov-verkada** [comment]
@pasha-codefresh, can we cherry pick this into 2.11-2.13, please?

**Comment by pasha-codefresh** [comment]
2.11 has some conflicts, need to do it manually @andrii-korotkov-verkada
