### PR TITLE
fix: Ignore diff with schema

### LINKED ISSUE #9071: ignoreDifferences.managedFieldsManagers not working as expected
**Describe the bug**

Setting ignoreDifferences.managedFieldsManagers is not ignoring fields marked as managed by `external-secrets`

**To Reproduce**

1. Create an application for external-secrets.io using their [helm chart](https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets) (version 0.5.1).  Be sure you set `installCRDs=true`
2.  Add this application with the following application spec:
```yaml
- name: external-secrets
      namespace: argo
      destination:
        namespace: external-secrets
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
        path: external-secrets
        repoURL: https://<url-to-your-argo-repo>
        targetRevision: HEAD
      ignoreDifferences:
      - group: "*"
        kind: "*"
        managedFieldsManagers:
        - external-secrets
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

```
3.  Sync the application
4. Notice that two validating webhooks and three CRDs will show as out of sync because their fields are modified by the external-secrets controller
5. If you look at the manifests for these resources, you'll notice that the fields that are different are also marked in .metadata.managedFields as being managed by `external-secrets`.

**Expected behavior**

Setting `.ignoreDifferences.managedFieldsManagers` to `external-secrets` should ignore the fields managed marked as managed by the external-secrets controller.

**Screenshots**
External Secrets resources after sync
image

*** Managed Fields for one of the validating webhooks
image

*** Diff of the validating webhook from above
image

**Version**

```shell
argocd: v2.3.1+b65c169
  BuildDate: 2022-03-11T00:05:18Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: windows/amd64
time="2022-04-11T15:56:03-04:00" level=warning msg="Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web."
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

I don't have any relevant logs:  the applications sync correctly, but then the controller immediately changes the fields, causing them to be out of sync.

### PR DESCRIPTION
**Pull request by leoluz**
Fix https://github.com/argoproj/argo-cd/issues/9071

- fix: managed fields diff using proper schema from cluster cache

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: util/argo/diff/diff.go [hunk 1]
```diff
@@ -309,8 +323,9 @@ func preDiffNormalize(lives, targets []*unstructured.Unstructured, diffConfig Di
 			idc := NewIgnoreDiffConfig(diffConfig.Ignores(), diffConfig.Overrides())
 			ok, ignoreDiff := idc.HasIgnoreDifference(gvk.Group, gvk.Kind, target.GetName(), target.GetNamespace())
 			if ok && len(ignoreDiff.ManagedFieldsManagers) > 0 {
+				pt := diffConfig.GVKParser().Type(gvk)
```
Comment (leoluz) [inline util/argo/diff/diff.go:326]: Need to nil check GVKParser() here

**Review by alexmt — APPROVED** [review]
LGTM. Please don't forget to update gitops engine version before merging.
