### PR TITLE
fix: improve CMP logging and error messages

### LINKED ISSUE #12144: Improve cmp logging/error messages
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

1. both `couldn't` and `could not` appear in related messages (only one style should be used for the project)
2. the argocd application name isn't reported -- making it incredibly hard to do anything with the message (yes, it might be obvious when viewed in certain circumstances, but when reviewing the `argocd-repo-server` output, that information is definitely not readily available)

**To Reproduce**

1. have some CMPs that are declared (but likely not completely working)
2. have a number of applications that want to use those various plugins
3. view the logs for argocd-repo-server (I'm using Google Cloud's Logs Explorer, but you can experience this by using ArgoCD to view the logs for an individual argocd-repo-server pod / sidecar pod, or k9s to do the same)

    ```
    resource.type="k8s_container"
    resource.labels.namespace_name="argocd"
    labels.k8s-pod/app_kubernetes_io/instance="argocd"
    labels.k8s-pod/app_kubernetes_io/name="argocd-repo-server"
    severity="ERROR"
    ```

**Expected behavior**

1. consistently use `couldn't`/`could not` (probably always avoid the abbreviation?)
2. report the app name in messages
5. don't say `plugin sidecar failed` when no sidecar could be found, it should probably say `could not find a sidecar` or `could not found a matching sidecar` or `could not find a sidecar cmp plugin` or ...

**Screenshots**

**Version**

```shell
{
    "Version": "v2.6.0+8238b53.dirty",
    "BuildDate": "2023-01-25T15:13:11Z",
    "GitCommit": "8238b53da09f2ca7dc2f0b3b3dcb9579866d148e",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
error="Manifest generation error (cached): plugin sidecar failed. couldn't find cmp-server plugin with name dhall-to-yaml supporting the given repository"
error="Manifest generation error (cached): plugin sidecar failed. could not find plugin supporting the given repository"
```

### PR DESCRIPTION
**Pull request by korECM**
## Summary

This PR addresses issue #12144 by improving CMP (Config Management Plugin) logging and error messages in three key areas:

- **Standardize error message wording**: Consistently use "could not" instead of "couldn't" throughout the codebase for better consistency
- **Include application name in error messages**: Add application name to CMP error messages to make debugging easier when reviewing argocd-repo-server logs  
- **Improve error message clarity**: Replace generic "plugin sidecar failed" message with more descriptive "CMP processing failed" message as suggested in the issue

### Error Message Standardization
- `util/app/discovery/discovery.go`: Use "could not" for consistency
- `util/oidc/oidc.go`: Standardize "couldn't" to "could not" in error messages  
- `applicationset/utils/utils.go`: Fix typo "coundn't" and standardize error messages to "could not"
- `applicationset/controllers/applicationset_controller.go`: Use "could not" for consistency

### CMP Error Message Improvements
- `reposerver/repository/repository.go`: Include application name and use clearer error wording

## Before/After

**Before:**
```
err = fmt.Errorf("plugin sidecar failed. %s", err.Error())
```

**After:**
```
err = fmt.Errorf("CMP processing failed for application %q: %w", q.AppName, err)
```

This results in error messages changing from:
```
error="plugin sidecar failed. could not find cmp-server plugin with name 'example' supporting the given repository"
```

To:
```
error="CMP processing failed for application \"my-app\": could not find cmp-server plugin with name 'example' supporting the given repository"
```

## Test plan

- [x] Existing tests pass
- [x] Error message changes are consistent with codebase patterns
- [x] CMP-related code compiles and functions correctly

Fixes #12144

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -1517,7 +1517,7 @@ func GenerateManifests(ctx context.Context, appPath, repoRoot, revision string,
 		// if pluginName is provided it has to be `<metadata.name>-<spec.version>` or just `<metadata.name>` if plugin version is empty
 		targetObjs, err = runConfigManagementPluginSidecars(ctx, appPath, repoRoot, pluginName, env, q, q.Repo.GetGitCreds(gitCredsStore), opt.cmpTarDoneCh, opt.cmpTarExcludedGlobs, opt.cmpUseManifestGeneratePaths)
 		if err != nil {
-			err = fmt.Errorf("plugin sidecar failed. %s", err.Error())
+			err = fmt.Errorf("could not find CMP sidecar for application %q: %s", q.AppName, err.Error())
```
Comment (peschmae) [inline reposerver/repository/repository.go]: `runConfigManagementPluginSidecar` can return a lot more error, than just not finding the CMP sidecar. While the old error message, isn't really helpful, the new one is misleading which is worse.
For example error like this ( https://github.com/argoproj/argo-cd/blob/c9fd4409168b8f1cf1341409a15c1a6ef50c84c3/reposerver/repository/repository.go#L2116 ) would be reported as `could no find CMP sidecar`

To improve on this message here, it would need to differentiate between the different error messages.

Comment (korECM) [reply reposerver/repository/repository.go]: @peschmae 
Thanks for the feedback! You're absolutely right that labeling all CMP errors as "could not find CMP sidecar" would be misleading.

I've simplified the approach to use a generic but accurate wrapper message:

```go
err = fmt.Errorf("CMP processing failed for application %q: %w", q.AppName, err)
```

This gives users logs like:
```
# Plugin discovery failure
error="Manifest generation error (cached): CMP processing failed for application 'my-app': could not find plugin supporting the given repository"

# Manifest conversion failure (your example)
error="Manifest generation error (cached): CMP processing failed for application 'my-app': failed to convert CMP manifests to unstructured objects: invalid YAML"
```

The generic "CMP processing failed" prefix gives context about the subsystem while letting the original error message provide the specific details. What do you think of this approach?

[`7934920` (#24022)](https://github.com/argoproj/argo-cd/pull/24022/commits/7934920794cdfcbbc31a6da105e746ed321a3eaa)

**Review by agaudreault — APPROVED** [review]
