### PR TITLE
fix: Badge display revision for multiple-sources application #17986

### LINKED ISSUE #17986: Display revisions when generating a badge for a multi-source application
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

[badge.go](https://github.com/argoproj/argo-cd/blob/master/server/badge/badge.go#L133) does not take into account multi-source applications when determining the revision to display on a badge. It only extracts the value from `app.Status.OperationState.SyncResult.Revision`, leaving `app.Status.OperationState.SyncResult.Revisions` behind.

Example multi-source application object dumped via the API:

image

**To Reproduce**

Crate a multi-source application and generate a the badge passing `revision=true`. No revision is added.

**Expected behavior**

Revisions from sources are added to the badge.

**Screenshots**

n/a

**Version**

`v2.10.7`

**Logs**

n/a

### PR DESCRIPTION
**Pull request by fpetr**
Fixes #17986

Shows revision in badge status for multiple sources application. Currently no revision is displayed for multi-source app. This PR will update badge to show revision of first defined source in multi-source setup.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: server/badge/badge_test.go [hunk 1]
```diff
@@ -451,6 +451,24 @@ func TestHandlerRevisionIsEnabledShortCommitSHA(t *testing.T) {
...
 }
 
+func TestHandlerRevisionIsEnabledMultipleSources(t *testing.T) {
+	app := testApp()
+	app.Status.OperationState.SyncResult.Revision = ""
+	app.Status.OperationState.SyncResult.Revisions = []string{"aa29b85", "cf41g63"}
+
+	settingsMgr := settings.NewSettingsManager(t.Context(), fake.NewClientset(argoCDCm(), argoCDSecret()), "default")
+	handler := NewHandler(appclientset.NewSimpleClientset(app), settingsMgr, "default", []string{})
+	req, err := http.NewRequest(http.MethodGet, "/api/badge?name=test-app&revision=true", nil)
```
Comment (henryxparker) [inline server/badge/badge_test.go]: Might want to fix this if you want a review. `httpNoBody: http.NoBody should be preferred to the nil request body (gocritic)`
I'm not a maintainer but if I was I might skip reviewing PRs that don't pass all checks especially if I'm really busy

**Review by agaudreault — APPROVED** [review]
