### PR TITLE
fix: Don't allow arbitrary redirects at login

### LINKED ISSUE #2707: Phishing attacks possible due to non-validated redirects
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

When a user tries to access a URL for which they need to be authenticated, the user
is redirected to the login page. The original URL is remembered in the return_url
parameter, where the user is redirected to after logging in.
Because no input validation is performed on the return_url parameter, it is possible
to supply any URL pointing to a third party website.

**To Reproduce**

1. Browse to https://argocd.domain.com/auth/login?return_url=//google.com
2. Login using Keycloak or other provider.
The Google homepage is opened

Recommendation:
Use a reputable, trusted library to implement the interaction with Keycloak.
 Accept only relative instead of absolute URLs to indicate the page to redirect to.
 Validate all input parameters used for redirection and deny any request if the
supplied value does not belong to the application’s domain.
 Create a coding guideline to ensure redirects are created in a secure manner.

```shell
any version
```

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #2707

Check for validity of `return_url` query parameter at OIDC auth in `/auth/login`.

This change ensures that `return_url` is pointing to the URL given in the `url` (`settings.URL`) configuration, or to a path within that URL. For example, if `url` is `https://localhost:4000/argocd`, then the following values for `return_url` will be valid:

* `https://localhost:4000/argocd`
* `https://localhost:4000/argocd/applications`

while the following URLs will not be considered valid and HTTP request is canceled:

* `https://localhost:4000/applications`
* `https://localhost:4000/argocd/../some/other/app`
* `https://www.google.com`

Refer to https://cwe.mitre.org/data/definitions/601.html and  https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html for more details. 

Signed-off-by: jannfis <jann@mistrust.net>

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

File: util/oidc/oidc.go [hunk 1]
```diff
@@ -199,6 +247,11 @@ func (a *ClientApp) HandleLogin(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 	returnURL := r.FormValue("return_url")
+	// Check if return_url is valid, otherwise abort processing (see #2707)
+	if !isValidRedirectURL(returnURL, []string{a.settings.URL}) {
+		http.Error(w, "Invalid return_url", http.StatusBadRequest)
```
Comment (jannfis) [inline util/oidc/oidc.go:252]: I was unsure what HTTP response code to chose. I picked HTTP 400 Bad Request, because that's what we basically considered it to be

**Review by alexmt — APPROVED** [review]
