### PR TITLE
fix: trigger app sync on app-set spec change

### LINKED ISSUE #26585: Progressive sync out of sync when changing image sha
**Describe the bug**

In case when using progressive sync with application sets and with image sha versions defined in the generator list (which we are patching within CI when we want to rollout new image version), with v3.3 version now our ArgoCD applications are out of sync always. 
When we merge some changes to the origin sources it takes some time until we run CI job that is patching image sha version in the generator list - and assumption is that sync argcd already syncs to that last merged commit, any changes later to the argo application set will result in with out of sync.

The image sha value is part of the generator list and is used inside the rendered Application spec (e.g. via kustomize/helm).  
Therefore, patching the generator modifies the rendered Application spec.

**To Reproduce**

Example of ArgoCD Application Set - mimicking the one we are using:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dummy
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - images:
                    dummy: "registry.gitlab.com/dummy/dummy:6d16ee7a916d27706b606f802e1930457368c9a7"
          - list:
              elements:
                - cluster: cluster-europe-west4
                  region: europe-west4
                - cluster: cluster-us-west1
                  region: us-west1
                - cluster: cluster-us-east4
                  region: us-east4
                - cluster: cluster-asia-southeast1
                  region: asia-southeast1
  strategy:
    rollingSync:
      steps:
        - matchExpressions:
            - key: region
              operator: In
              values:
                - us-east4
          maxUpdate: 1
        - matchExpressions:
            - key: region
              operator: In
              values:
                - europe-west4
          maxUpdate: 1
        - matchExpressions:
            - key: region
              operator: In
              values:
                - us-west1
          maxUpdate: 1
        - matchExpressions:
            - key: region
              operator: In
              values:
                - asia-southeast1
          maxUpdate: 1
    type: RollingSync
  template:
    metadata:
      labels:
        region: '{{.region}}'
      name: "dummy-{{.region}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: dummy
        name: "{{.cluster}}"
      project: prototypes
      sources:
        - repoURL: "https://gitlab.com/dummy/dummy.git"
           path: chart
           targetRevision: master
           helm:
             values: |
                replicaCount: 1
                image:
                repository: registry.gitlab.com/tatum-io/prototypes/dummy
                tag: "{{ .images.dummy }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
```

Once we merge some change to the repo in this example to https://gitlab.com/dummy/dummy.git to master branch and after 5 minutes or so ArgoCD syncs all changes to underlaying ArgoCD Applications.

Now, after some time (crucial is that we are patching after argoCD already syncs Applications to the latest revision - change in the master branch), our CI is patching ArgoCD Application Set to change image sha in the generator list to the new one, that change won't be rollout but all argoCD Applications will stay out of sync until we manually press Sync button.

This behavior started to pop up after we migrated to v3.3, while on v2.14 we didn't have such cases.

**Expected behavior**

I would expected that whenever there is a change in Application set that it will streamline changes to underlaying Applications and rollout them.

**Version**

```shell
v3.3.0
```

Is this behavior expected with the current RollingSync implementation in v3.3.0,  
or is this a regression compared to v2.14?

If expected, what is the supported way to trigger a new progressive rollout when generator values change without modifying Git targetRevision?

The workaround we found working for us is to add a new source that is targeting to the commit sha and that way its "forcing" argoCD Applications to be in sync - the additional source does not deploy any manifests.  
It is used only to force a change in targetRevisions so that RollingSync detects a new revision and starts a new rollout cycle.

```
- repoURL: "https://gitlab.com/dummy/dummy.git"
   targetRevision: "{{ .images.dummy }}"
   ref: rollout-marker
```

### PR DESCRIPTION
**Pull request by ppapapetrou76**
Closes https://github.com/argoproj/argo-cd/issues/26585

Fixes the code top trigger applications sync when there's a change in the application set spec ( that apparantely generated the apps ) 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: applicationset/controllers/applicationset_controller.go [hunk 1]
```diff
@@ -1182,10 +1188,27 @@ func (r *ApplicationSetReconciler) updateApplicationSetApplicationStatus(ctx con
...
-			newAppStatus.Message = "Application has pending changes, setting status to Waiting"
+
+			switch {
+			case revisionsChanged && specChanged:
+				newAppStatus.Message = "Application has pending changes (revision and spec differ), setting status to Waiting"
+			case revisionsChanged:
+				newAppStatus.Message = "Application has pending changes, setting status to Waiting"
+			default:
+				newAppStatus.Message = "Application has pending changes (spec differs), setting status to Waiting"
+			}
```
Comment (ishitasequeira) [inline applicationset/controllers/applicationset_controller.go:1214]: nit: we are adding what differs in each message except for `revisionsChanged`. Shall we align on the message?

**Review by ishitasequeira — APPROVED** [review]
Overall changes look good. Added a nit!!

File: applicationset/controllers/applicationset_controller.go (hunk 1 above)
Comment (sivchari) [inline applicationset/controllers/applicationset_controller.go:1214]: How about making messages const ? I think it's better to do it since we can use same const in logic and tests.

Comment (ppapapetrou76) [reply applicationset/controllers/applicationset_controller.go:1214]: @ishitasequeira This was intentional since now we are handling one more case ( spec change ) - if you think it's too much I'm happy to stick on the same message.

**Comment by rromic** [comment]
@ppapapetrou76 any eta when this fix will be released? thanks!
