### PR TITLE
fix(hook): Fixed hook code issues that caused stuck applications on "Deleting" state (Issues #18355 and #17191)

### LINKED ISSUE #17191: PostDelete Hook with other resources than pod/job (like SA)
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I create a PostDelete hook with other resources like ServiceAccount, Role, RoleBinding, even if the hook succeed, the Application stay in Deleted state.

**To Reproduce**

Create resources like ServiceAccount, Role, RoleBinding and Pod/Job that use this ServiceAccount to works.

You can view this repo : https://github.com/dtrouillet/postdelete-hook-issue2 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2-damien
  namespace: argocd
spec:
  destination:
    namespace: test2-damien
    server: https://XXXXX
  project: default
  revisionHistoryLimit: 10
  sources:
    - path: .
      repoURL: https://github.com/dtrouillet/postdelete-hook-issue2.git
      targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

**Expected behavior**

Application is deleted after hook execution

**Screenshots**

**Version**

argocd: v2.10.0+2175939
BuildDate: 2024-02-06T14:28:43Z
GitCommit: https://github.com/argoproj/argo-cd/commit/2175939ed6156ddd743e60f427f7f48118c971bf
GitTreeState: clean
GoVersion: go1.21.3
Compiler: gc
Platform: linux/amd64

**Logs**

No logs

### LINKED ISSUE #18355: helm post-delete  hooks is not working with argocd as expected
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I have an helm application present in path https://github.com/dsharma24101992/helmHooksDemo/tree/main/deployments/helm-hooks-demo  which has 2  helm hooks . First one is pre-install hook which will create the clusterrole update-namespaces(Please refer to file https://github.com/dsharma24101992/helmHooksDemo/blob/main/deployments/helm-hooks-demo/templates/pre-install-hooks-job.yaml  and job helm-hooks-demo-create-clusterrole-pre-install-job) . second is a post-delete hook.as part of post-delete hook(https://github.com/dsharma24101992/helmHooksDemo/blob/main/deployments/helm-hooks-demo/templates/post-delete-hooks-job.yaml), I am deleting the clusterrole **update-namespaces**  as part of job **delete-clusterrole**). my understanding is that post-delete hooks for clusterrole, clusterrolebinding,serviceAccount should be be created first and as soon as  my job **delete-clusterrole**  is completed, the clusterrole ,clusterrolebinding,serviceAccount which are created as part of post-delete hooks should be deleted.  but I am getting the following error when post-delete hooks are executing in argoUI.

**clusterroles.rbac.authorization.k8s.io "helm-hooks-demo-post-delete" already exists**

I am doing the same steps via  helm install and uninstall, everything is working fine. below are the uninstall logs using helm uninstall.

```
deesharma@dac0272-lcedt:~/Downloads$ helm uninstall helm-hooks-demo -n helm-hooks-demo --debug 
uninstall.go:102: [debug] uninstall: Deleting helm-hooks-demo
client.go:486: [debug] Starting delete for "allow-all-traffic" NetworkPolicy
client.go:142: [debug] creating 1 resource(s)
client.go:142: [debug] creating 1 resource(s)
client.go:142: [debug] creating 1 resource(s)
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job delete-clusterrole with timeout of 5m0s
client.go:740: [debug] Add/Modify event for delete-clusterrole: ADDED
client.go:779: [debug] delete-clusterrole: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for delete-clusterrole: MODIFIED
client.go:779: [debug] delete-clusterrole: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for delete-clusterrole: MODIFIED
client.go:779: [debug] delete-clusterrole: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for delete-clusterrole: MODIFIED
client.go:486: [debug] Starting delete for "helm-hooks-demo-post-delete" ClusterRole
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:486: [debug] Starting delete for "helm-hooks-demo-post-delete" ServiceAccount
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:486: [debug] Starting delete for "helm-hooks-demo-post-delete" ClusterRoleBinding
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:486: [debug] Starting delete for "delete-clusterrole" Job
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 
5m0s
uninstall.go:155: [debug] purge requested for helm-hooks-demo
release "helm-hooks-demo" uninstalled
```

I have attached the argoUI snapshot which I have taken after trigger application delete from argoUI. 
helm-hooks-demo-delete-output

helm-hooks-demo-UI-error during deletion
helm-hooks-demo-argoUI-error

helm-hooks-demo-UI-install during application installation
helm-hooks-demo-installation

 In summary , the problem statement is why **helm-hooks-demo-post-delete** clusterrole is not getting deleted as  soon as the post-delete job is completed.

**To Reproduce**
1. Git repo => https://github.com/dsharma24101992/helmHooksDemo.git
2. create the minikube cluster and install argo using command kubectl apply -n argocd https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.10/manifests/install.yaml
3. Configure the helm-hooks-demo argo application using these 2 commands
      1. kubectl apply -f https://raw.githubusercontent.com/dsharma24101992/helmHooksDemo/main/helm-hooks-argo-application.yaml
      2. kubectl apply -f https://raw.githubusercontent.com/dsharma24101992/helmHooksDemo/main/helm-hooks-configmap.yaml
 4. Delete the application from argoUI using foreground-deletion propogation policy.
 5. The issue should be reproduced and the application deletion will throw the error **clusterroles.rbac.authorization.k8s.io "helm-hooks-demo-post-delete" already exists**

**Expected behavior**

**Screenshots**

**Version**

```shell
argocd: v2.5.8+bbe870f
  BuildDate: 2023-01-25T16:17:49Z
  GitCommit: bbe870ff5904dd1cebeba6c5dcb7129ce7c2b5e2
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.8+bbe870f
  BuildDate: 2023-01-25T16:17:49Z
  GitCommit: bbe870ff5904dd1cebeba6c5dcb7129ce7c2b5e2
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.14.3+gf03cc04
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0

```

### PR DESCRIPTION
**Pull request by nikos445**
Issue Fixed:

- Applications with PreDelete and PostDelete hooks were not working correctly when hooks were defined with kustomization or via helm chart. These applications are stucking on "Deleting" state while the "post-delete" and "pre-delete" hooks were executed and even after the jobs were successfully finished.

Fixes #18355
Fixes #17191

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

File: controller/hook.go [hunk 1]
```diff
@@ -165,12 +173,17 @@ func (ctrl *ApplicationController) executeHooks(hookType HookType, app *appv1.Ap
 				Status: health.HealthStatusHealthy,
 			}
 		}
+
 		switch hookHealth.Status {
 		case health.HealthStatusProgressing:
+			logCtx.Infof("Hook %s is progressing", key)
```
Comment (ppapapetrou76) [inline controller/hook.go]: I believe this should a `debug` log

File: controller/hook.go [hunk 2]
```diff
@@ -165,12 +173,17 @@ func (ctrl *ApplicationController) executeHooks(hookType HookType, app *appv1.Ap
...
 			progressingHooksCount++
 		case health.HealthStatusDegraded:
+			logCtx.Warnf("Hook %s is degraded: %s", key, hookHealth.Message)
 			failedHooks = append(failedHooks, fmt.Sprintf("%s/%s", obj.GetNamespace(), obj.GetName()))
 			failedHookObjects = append(failedHookObjects, obj)
+		case health.HealthStatusHealthy:
+			logCtx.Infof("Hook %s is healthy", key)
```
Comment (ppapapetrou76) [inline controller/hook.go]: same here I believe this should a `debug` log

**Review by ppapapetrou76 — COMMENTED** [review]
Can we please add/update some UTs to verify the new behavior?

**Comment by nikos445** [comment]
> Can we please add/update some UTs to verify the new behavior?

I'm just a beginner in this but I will try. Cant promise 😁 if you can support I would really appreciate it.

**Comment by nikos445** [comment]
> Can we please add/update some UTs to verify the new behavior?

I managed to write some tests :) Hope they are good enough.

**Review by ppapapetrou76 — COMMENTED** [review]
Thanks for addressing my requests @nikos445 
One last thing because I can't verify that the change is actually addressing the original issues. 
have you tested it locally?
Any change to share a short video of before / after the fix behavior?

**Comment by nikos445** [comment]
> Thanks for addressing my requests @nikos445 One last thing because I can't verify that the change is actually addressing the original issues. have you tested it locally? Any change to share a short video of before / after the fix behavior?

Sure thing. I will setup locally again and upload a video later today.

**Comment by nikos445** [comment]
Hello @ppapapetrou76 , 

here is an image build (temporary public for few next days) including this fix in case you want to test it:  

---

_docker.io/nikos445/argoproj:latest_     (replacing original: quay.io/argoproj/argocd:latest)

--- 

**Video before fix:**

[before_fix.webm](https://github.com/user-attachments/assets/7fe49db6-4ae4-47a3-923c-d2b456608a8c)


**Video after fix:**

[after_fix.webm](https://github.com/user-attachments/assets/ce8bd6f5-1cb6-452e-9ff0-5d8421418f44)

**Review by ppapapetrou76 — APPROVED** [review]
LGTM 🏅  - thanks for addressing my comments

**Review by sivchari — APPROVED** [review]

**Comment by nikos445** [comment]
Hello @argoproj/argocd-approvers + @ppapapetrou76 

Can this be merged or do I need to do something more?

**Comment by ppapapetrou76** [comment]
> Hello @argoproj/argocd-approvers + @ppapapetrou76
> 
> Can this be merged or do I need to do something more?

I have enabled auto-merge but we need someone with approve permissions first 🤷🏾

**Review by blakepettersson — APPROVED** [review]
