### PR TITLE
fix: ignore gitlab projects w/o repository (#12819)

### LINKED ISSUE #12819: GitLab SCM Provider Generator fails on projects without repository
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The GitLab SCM Provider Generator bails out with an error when encountering a project that does not contain a valid repository. This can be caused by:

* a freshly created project which does not contain a repository,
* a project with a repository that is not accessible for the account/token used by the generator,
* a project which will be used for other purposes (wiki, tasks, et.al)

**To Reproduce**

Configure a `ApplicationSet` with a `scmProvider` of type `gitlab` and a `group` that includes a project which has an uninitialised repository.

**Expected behavior**

The generator skips the problematic project(s), without bailing out with an error.

**Screenshots**

**Version**

```shell
argocd: v2.6.4+7be094f.dirty
  BuildDate: 2023-03-07T23:43:59Z
  GitCommit: 7be094f38d06859b594b98eb75c7c70d39b80b1e
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.4+7be094f
  BuildDate: 2023-03-07T22:48:16Z
  GitCommit: 7be094f38d06859b594b98eb75c7c70d39b80b1e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
time="2023-03-10T22:21:19Z" level=error msg="error generating params" error="error listing repos: error listing branches for ops/example/tasks: GET https://gitlab.example.com/api/v4/projects/1337/repository/branches: 404 {message: 404 Repository Not Found}" generator="&{0xc000cece60 <nil> {0xc000cf3dd0}}"
time="2023-03-10T22:21:19Z" level=error msg="error generating application from params" error="error listing repos: error listing branches for ops/example/tasks: GET https://gitlab.example.com/api/v4/projects/1337/repository/branches: 404 {message: 404 Repository Not Found}" generator="{nil nil nil &SCMProviderGenerator{Github:nil,Gitlab:&SCMProviderGeneratorGitlab{Group:ops,IncludeSubgroups:true,API:https://gitlab.example.com/,TokenRef:&SecretRef{SecretName:gitlab,Key:token,},AllBranches:true,},Bitbucket:nil,BitbucketServer:nil,Gitea:nil,AzureDevOps:nil,Filters:[]SCMProviderGeneratorFilter{SCMProviderGeneratorFilter{RepositoryMatch:*^puppet,PathsExist:[],PathsDoNotExist:[],LabelMatch:nil,BranchMatch:nil,},},CloneProtocol:https,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},} nil nil nil nil nil}"
```

### PR DESCRIPTION
**Pull request by pjoomen**
Fixes #12819

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: applicationset/services/scm_provider/gitlab.go [hunk 1]
```diff
@@ -157,6 +161,10 @@ func (g *GitlabProvider) listBranches(_ context.Context, repo *Repository) ([]gi
 	}
 	for {
 		gitlabBranches, resp, err := g.client.Branches.ListBranches(repo.RepositoryId, opt)
+		// 404s are not an error here, just a normal false.
+		if resp != nil && resp.StatusCode == 404 {
```
Comment (crenshaw-dev) [inline applicationset/services/scm_provider/gitlab.go:165]:
```suggestion
		if resp != nil && resp.StatusCode == http.StatusNotFound {
```

File: applicationset/services/scm_provider/gitlab.go [hunk 2]
```diff
@@ -144,7 +144,11 @@ func (g *GitlabProvider) listBranches(_ context.Context, repo *Repository) ([]gi
 	branches := []gitlab.Branch{}
 	// If we don't specifically want to query for all branches, just use the default branch and call it a day.
 	if !g.allBranches {
-		gitlabBranch, _, err := g.client.Branches.GetBranch(repo.RepositoryId, repo.Branch, nil)
+		gitlabBranch, resp, err := g.client.Branches.GetBranch(repo.RepositoryId, repo.Branch, nil)
+		// 404s are not an error here, just a normal false.
+		if resp != nil && resp.StatusCode == 404 {
```
Comment (crenshaw-dev) [inline applicationset/services/scm_provider/gitlab.go:149]:
```suggestion
		if resp != nil && resp.StatusCode == http.StatusNotFound {
```

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

**Review by jannfis — APPROVED** [review]
LGTM!

**Review by crenshaw-dev — APPROVED** [review]
