### PR TITLE
fix: adding pagination to grouped nodes sliding panel#7837

### LINKED ISSUE #7837: Compact application resource tree - Add pagination in collapse node details sliding panel
# Summary and motivation

This is a follow-on enhancement to #7349

In its initial design and implementation, the sliding panel that appears (after you click on the collapsed-group node) shows the list of the child leaf nodes that were collapsed.  This list could potentially be long and the user will then have to scroll up and down.

Implement pagination (Somewhat similar to the existing Application Details List view anyway....so it will be consistent)

# Proposal

Add Pagination to show the list of nodes.

### PR DESCRIPTION
**Pull request by ciiay**
Closes #7837
Signed-off-by: ciiay yicai@redhat.com

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Preview:
Screen Shot 2021-12-13 at 1 16 41 PM

### CODE REVIEW

File: ui/src/app/applications/components/application-details/application-details.tsx [hunk 1]
```diff
@@ -328,15 +330,25 @@ export class ApplicationDetails extends React.Component<RouteComponentProps<{nam
...
-                                            <ApplicationResourceList
-                                                onNodeClick={fullName => this.selectNode(fullName)}
-                                                resources={this.state.groupedResources}
-                                                nodeMenu={node =>
-                                                    AppUtils.renderResourceMenu({...node, root: node}, application, tree, this.appContext, this.appChanged, () =>
-                                                        this.getApplicationActionMenu(application, false)
-                                                    )
-                                                }
-                                            />
+                                            <div style={{marginTop: '1.25em'}}>
```
Comment (keithchong) [inline ui/src/app/applications/components/application-details/application-details.tsx:333]: I know there are places where we mix styles in the code, but maybe for this one, we could add it to the scss file?

**Review by alexmt — APPROVED** [review]
Thank you!
