### PR TITLE
fix: suppress Kubernetes API deprecation warnings from application controller (#11973)

### LINKED ISSUE #11973: Issues with Kubernetes API Deprecation warnings
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

```log
W0112 20:10:35.903374       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

A few issues with how the application-controller logs these warnings:

- They are insistent and excessive, consuming large volumes of our logging quota.
- If you have JSON logging enabled, they are not JSON wrapped, screwing up any log parsing you may have setup
- They are not actionable, they do not say what resource or application is throwing the warning.

**To Reproduce**

Use a deprecated API.

**Expected behavior**

These should be properly JSON wrapped, they should be actionable, you should be able to disable this warning.

**Version**

```shell
argocd: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:34:36Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:10:26Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

```
W0112 20:10:35.903374       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

### PR DESCRIPTION
**Pull request by toVersus**
Signed-off-by: Tsubasa Nagasawa <toversus2357@gmail.com>

Fixes: #11973

Suppress Kubernetes API deprecation warnings for log levels that are less than Debug by customizing the cluster cache client warning handler.

```sh
❯ kind version
kind v0.17.0 go1.19.2 linux/amd64

# Build Argo CD image from fix/suppress-deprecation-warnings branch
make image

# Create Kind cluster
kind create cluster --image kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61
# Load Argo CD image into Kind cluster
kind load docker-image argocd:latest

# Install Argo CD using default setup
kubectl create ns argocd
kubectl apply -n argocd -f manifests/install.yaml

# Apply the patch to replace the image with a local build
kubectl patch -n argocd sts argocd-application-controller -p '{"spec":{"template":{"spec":{"containers":[{"name":"argocd-application-controller","image":"argocd:latest","imagePullPolicy":"Never"}]}}}}'

# Create Argo CD Application to start watcher
cat <<EOF | kubectl apply -n argocd -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.50.8
    helm:
      releaseName: grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
EOF

# Check to see if there are no API deprecation warning logs
kubectl logs -n argocd -f sts/argocd-application-controller

# Change log level to debug
kubectl patch -n argocd configmap/argocd-cmd-params-cm -p '{"data":{"controller.log.level":"debug"}}'

# Restart argocd-application-controller
kubectl rollout restart -n argocd sts/argocd-application-controller

# Check to see if there are API deprecation warning logs
kubectl logs -n argocd -f sts/argocd-application-controller
# W0222 11:29:33.616120       1 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
# W0222 11:29:33.626792       1 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: controller/cache/cache.go [hunk 1]
```diff
@@ -394,6 +395,15 @@ func (c *liveStateCache) getCluster(server string) (clustercache.ClusterCache, e
...
 	}
 
+	// controller dynamically fetches all resource types available on the cluster using a discovery API
+	// that may contain deprecated APIs. This causes log flooding when managing a large number of clusters.
+	// https://github.com/argoproj/argo-cd/issues/11973
+	// However, we can safely suppress deprecation warnings
+	// because we do not rely on resources with a particular API group or version.
+	// https://kubernetes.io/blog/2020/09/03/warnings/#customize-client-handling
+	clusterCacheConfig := cluster.RESTConfig()
+	clusterCacheConfig.WarningHandler = rest.NoWarnings{}
```
Comment (blakepettersson) [inline controller/cache/cache.go:405]: Hmm, I'm not sure if I agree this should be completely shut off. Perhaps if this is wrapped like this, where it is enabled only for log levels that are higher than Debug?

```suggestion
	if log.GetLevel() >= log.DebugLevel {
		clusterCacheConfig.WarningHandler = rest.NoWarnings{}
	}
```

Comment (toVersus) [reply controller/cache/cache.go:405]: Yeah, it can be helpful for debugging purposes. I'm fine with leaving the option to log the warnings.
@sidewinder12s, @jannfis WDYT?

Comment (sidewinder12s) [reply controller/cache/cache.go:405]: Agreed it should just be hidden in higher log levels.

Comment (toVersus) [reply controller/cache/cache.go]: Thanks, I have revised the commit to reflect the suggestion.

**Comment by toVersus** [comment]
@blakepettersson
Added step in PR description to confirm that changes work as expected. PTAL

**Review by blakepettersson — APPROVED** [review]
LGTM 👍

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @toVersus!

**Comment by crenshaw-dev** [comment]
Manually cherry-picked onto release-2.5 and release-2.4.
