### PR TITLE
fix: add target branch support for bitbucket cloud pull request gener…

### LINKED ISSUE #22005: targetBranchMatch filter does not work with pullRequest generator for Bitbucket Cloud
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Adding `targetBranchMatch` filter on generator for Azure DevOps pull request produces zero apps output

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: feature
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        requeueAfterSeconds: 60
        bitbucket:
          owner: owner
          repo: repo
          api: https://api.bitbucket.org/2.0
          bearerToken:
            tokenRef:
              secretName: bitbucket-bearer-token
              key: token
        filters:
          - targetBranchMatch: "develop"
```

**Expected behavior**

ApplicationSet generates apps for pull requests with matched target branch

**Version**

```shell
argocd: v2.14.2+ad27246
  BuildDate: 2025-02-06T02:19:55Z
  GitCommit: ad2724661b66ede607db9b5bd4c3c26491f5be67
  GitTreeState: clean
  GoVersion: go1.23.6
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.14.2+ad27246
  BuildDate: 2025-02-05T23:44:17Z
  GitCommit: ad2724661b66ede607db9b5bd4c3c26491f5be67
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

### PR DESCRIPTION
**Pull request by mihallis**
Fix #22005

### CODE REVIEW

**Review by crenshaw-dev — DISMISSED** [review]
Thanks for the PR! Could you add unit tests?

**Comment by CMDMichalKoval** [comment]
> Thanks for the PR! Could you add unit tests?

Done

**Review by ishitasequeira — COMMENTED** [review]
Thanks for the PR @CMDMichalKoval !!

Could you also update the documentation explaining the new field [here](https://github.com/argoproj/argo-cd/blob/8e696a5caa859a8cf1f80d869df810bd0af64491/docs/operator-manual/applicationset/Generators-Pull-Request.md#bitbucket-cloud) ?

**Comment by CMDMichalKoval** [comment]
@ishitasequeira I have updated the docs and added more examples for filters

**Comment by MIcQo** [comment]
@crenshaw-dev  @ishitasequeira  can you look at this, please?

**Comment by CMDMichalKoval** [comment]
@crenshaw-dev @ishitasequeira can you look at this, please?

**Comment by MIcQo** [comment]
@crenshaw-dev can you please re-run checks ? or should i create new PR ?

**Comment by CMDMichalKoval** [comment]
@crenshaw-dev can you please unblock PR and merge it ?

File: applicationset/services/pull_request/bitbucket_cloud.go [hunk 1]
```diff
@@ -17,10 +17,19 @@ type BitbucketCloudService struct {
...
+	Author      BitbucketCloudPullRequestAuthor      `json:"author"`
+	Destination BitbucketCloudPullRequestDestination `json:"destination"`
+}
+
+type BitbucketCloudPullRequestDestination struct {
+	Branch BitbucketCloudPullRequestDestinationBranch `json:"branch"`
+}
+
+type BitbucketCloudPullRequestDestinationBranch struct {
+	BitbucketCloudPullRequestSourceBranch
```
Comment (olivergondza) [inline applicationset/services/pull_request/bitbucket_cloud.go:32]: I advise not to reuse the fields for _source_ in _destination_, even when they are the same now. That will let the two evolve separately without nasty surprised to future maintainers.

Comment (CMDMichalKoval) [reply applicationset/services/pull_request/bitbucket_cloud.go]: Good point! I already updated it with own type

**Review by olivergondza — COMMENTED** [review]
The code looks good to me!

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Comment by ishitasequeira** [comment]
@crenshaw-dev , any more concerns on the PR?
