### PR TITLE
fix: get correct username from jwt token subject (#5836)

### LINKED ISSUE #5836: [2.0.0-rc1] ArgoCD update-password causes immediate fatal error after successful update
**Describe the bug**
When updating the password of the current (and only) account via the CLI, a fatal error is immediately thrown.

**To Reproduce**
```bash
argocd login localhost:7000 --username admin --password "$ARGOCD_PASSWORD" --insecure
argocd account update-password --current-password "$ARGOCD_PASSWORD" --new-password "$ARGOCD_DEFAULT_PASSWORD"
Password updated
FATA[0005] rpc error: code = Unauthenticated desc = Invalid username or password
```

**Expected behavior**
Resetting the password of the current account should be handled gracefully, refreshing the in-use token.

**Version**
```shell
argocd: v2.0.0-rc1+0ca643f
  BuildDate: 2021-03-19T21:27:59Z
  GitCommit: 0ca643f027b99e8a5b931bb8ee9df42c3e4b64bf
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0-rc1+0ca643f
```

### PR DESCRIPTION
**Pull request by kshamajain99**
fixes #5836

Adapt change https://github.com/argoproj/argo-cd/blob/bde4ad4d820c0cb024ad5188d2f223bfe8521de2/server/session/session.go#L67

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: util/localconfig/localconfig.go [hunk 1]
```diff
@@ -262,3 +263,11 @@ func DefaultLocalConfigPath() (string, error) {
 	}
 	return path.Join(dir, "config"), nil
 }
+
+func GetUsername(subject string) string {
```
Comment (sbose78) [inline util/localconfig/localconfig.go:267]: Could we have a unit test for this, please?

**Review by sbose78 — CHANGES_REQUESTED** [review]
Looks good to me, a unit test would be nice.

File: util/localconfig/localconfig.go [hunk 2]
```diff
@@ -262,3 +263,11 @@ func DefaultLocalConfigPath() (string, error) {
...
+	parts := strings.Split(subject, ":")
+	if len(parts) > 0 {
+		return parts[0]
+	}
+	return subject
```
Comment (jannfis) [inline util/localconfig/localconfig.go:272]: Since `strings.Split()` always returns an array with at least one element, this can be simplified to:

```go
return strings.Split(subject, ":")[0]
```

From https://golang.org/pkg/strings/#Split
>  If s does not contain sep and sep is not empty, Split returns a slice of length 1 whose only element is s.

**Review by jannfis — APPROVED** [review]
