### PR TITLE
fix: return http400/405 to invalid webhook requests

### LINKED ISSUE #5124: Webhook never fails
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x]  I've included steps to reproduce the bug.
* [x]  I've pasted the output of `argocd version`.

**Describe the bug**

There is no error when something goes wrong in Webhook usage. It always returns http 200 status

**To Reproduce**

Specify http scheme in webhook settings in git repository provider. This will causes [this](https://github.com/argoproj/argo-cd/blob/v1.8.1/util/webhook/webhook.go#L348-L351) error message in logs:

`level=info msg="Webhook processing failed: invalid HTTP Method"`

But HTTP status of response will remain the same - HTTP 200 OK

**Expected behavior**

Return HTTP 500 with an error message

**Version**

```shell
argocd: v1.8.1+c2547dc
  BuildDate: 2020-12-10T03:00:31Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

```
level=info msg="Webhook processing failed: invalid HTTP Method"
```

### PR DESCRIPTION
**Pull request by mnacharov**
Fixes #5124

Checklist:

* [x] this is a bug fix
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates? -- NO
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: util/webhook/webhook.go [hunk 1]
```diff
@@ -342,11 +351,13 @@ func (a *ArgoCDWebhookHandler) Handler(w http.ResponseWriter, r *http.Request) {
 		payload, err = a.bitbucketserver.Parse(r, bitbucketserver.RepositoryReferenceChangedEvent)
 	default:
 		log.Debug("Ignoring unknown webhook event")
+		replyBadRequest(w, "Unknown webhook event")
```
Comment (jannfis) [inline util/webhook/webhook.go:354]: I think it would be good to use the more standardized method `http.Error()` to write the status to the client.

File: util/webhook/webhook.go [hunk 2]
```diff
@@ -342,11 +351,13 @@ func (a *ArgoCDWebhookHandler) Handler(w http.ResponseWriter, r *http.Request) {
...
 		return
 	}
 
 	if err != nil {
 		log.Infof("Webhook processing failed: %s", err)
+		replyBadRequest(w, fmt.Sprintf("Webhook processing failed: %s", err))
```
Comment (jannfis) [inline util/webhook/webhook.go:360]: Same as above. And also please use `html.EscapeString(err.Error())` for passing the contents of the error message back to the client.

**Review by jannfis — CHANGES_REQUESTED** [review]
Thanks @mnacharov! I have two suggestions, please see my review comments.

File: util/webhook/webhook.go (hunk 2 above)
Comment (mnacharov) [reply util/webhook/webhook.go]: thx, added

**Review by jannfis — APPROVED** [review]
LGTM. Thank you @mnacharov!

**Comment by MPV** [comment]
Just a heads-up that this caused https://github.com/argoproj/argo-cd/issues/7685 😊
