### PR TITLE
fix: #20183 preserve syncOptions when rolling back from the UI

### LINKED ISSUE #20183: Rollback in Argo CD Removes ServerSideApply=true from syncPolicy Configuration
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**
We are experiencing an issue with Argo CD where rolling back an application unexpectedly alters our syncPolicy setup, specifically losing the ServerSideApply=true option.

**Current Setup:**
```
syncPolicy:
  automated: {}
  syncOptions:
    - ServerSideApply=true
```

**After performing a rollback, we observe:**
```
syncPolicy: {}
```
This prevents us from applying previous ConfigMaps as expected because the ServerSideApply flag is necessary for large ConfigMaps.

**Additional Observations:**

When testing rollbacks with syncPolicy:
```
syncPolicy:
  syncOptions:
    - ServerSideApply=true
```
and with auto-sync disabled, ArgoCD does not reset syncOptions, leading to a successful rollback.

**To Reproduce**
Configure an Argo CD application with the following syncPolicy:
```
syncPolicy:
  automated: {}
  syncOptions:
    - ServerSideApply=true
```
Perform a rollback to a previous version of the application via the Argo CD UI or CLI.

Observe that the resultant configuration is missing syncOptions.
```
syncPolicy: {}
```

**Expected behavior**
After rollback, the syncPolicy should remain:
```
syncPolicy:
  syncOptions:
    - ServerSideApply=true
```

**Version**
Taken from UI
```shell
v2.9.0+9cf0c69
```

### PR DESCRIPTION
**Pull request by alexef**
a rollback initiated from the UI shouldn't remove `syncOptions` if they are set.

note: this is only an issue in the UI, because the UI will first disable auto-sync, then rolllback. during the auto sync disabling, the syncOptions are accidentally removed. if the rollback is initiated via CLI, then [this code](https://github.com/alexef/argo-cd/blob/41c3d5ba9ba60ee887848c8cea52d6b17fec1bdb/server/application/application.go#L2111) preserves existing sync options.

fixes: #20183 

## Steps to reproduce for tester

1. create an Application, set `spec.syncPolicy.syncOptions` to anything, for instance: `[ "CreateNamespace=true" ]`
2. enable auto-sync (set the `spec.syncPolicy.automated` to an object)
3. deploy it twice at two different versions, so that you have a version to rollback to in the "History and Rollback" dialogue
4. rollback. 
5. check `spec.syncPolicy.syncOptions` to still have your settings at point 1.

Before this PR, the syncOptions will be gone. After it, they would be preserved.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

File: ui/src/app/applications/components/application-details/application-details.tsx [hunk 1]
```diff
@@ -1205,6 +1205,10 @@ Are you sure you want to disable auto-sync and rollback application '${this.prop
                 if (needDisableRollback) {
                     const update = JSON.parse(JSON.stringify(application)) as appModels.Application;
                     update.spec.syncPolicy = {automated: null};
+                    // preserve syncOptions when doing rollback
+                    if (application.spec.syncPolicy.syncOptions) {
+                        update.spec.syncPolicy.syncOptions = application.spec.syncPolicy.syncOptions;
+                    }
```
Comment (agaudreault) [inline ui/src/app/applications/components/application-details/application-details.tsx:1211]: Would this work? This way the same problem does not happen if new properties are added to syncPolicy.

```suggestion
                    update.spec.syncPolicy = application.spec.syncPolicy;
                    update.spec.syncPolicy.automated = null;
```

Comment (linghaoSu) [reply ui/src/app/applications/components/application-details/application-details.tsx:1211]:
```suggestion
                   set('spec.syncPolicy.syncOptions.automated', null)
```
It seems we already clone syncPolicy from the application, so just setting automated to null should be enough instead of overriding the whole syncPolicy.🤔

**Review by todaywasawesome — COMMENTED** [review]
Can you test the suggestions from @linghaoSu?

File: ui/src/app/applications/components/application-details/application-details.tsx [hunk 2]
```diff
@@ -1204,7 +1204,7 @@ Are you sure you want to disable auto-sync and rollback application '${this.prop
             if (confirmed) {
                 if (needDisableRollback) {
                     const update = JSON.parse(JSON.stringify(application)) as appModels.Application;
-                    update.spec.syncPolicy = {automated: null};
+                   set('spec.syncPolicy.syncOptions.automated', null)
```
Comment (alexef) [inline ui/src/app/applications/components/application-details/application-details.tsx:1207]:
```suggestion
                    update.spec.syncPolicy.syncOptions.automated = null;
```

File: ui/src/app/applications/components/application-details/application-details.tsx [hunk 3]
```diff
@@ -1204,7 +1204,7 @@ Are you sure you want to disable auto-sync and rollback application '${this.prop
             if (confirmed) {
                 if (needDisableRollback) {
                     const update = JSON.parse(JSON.stringify(application)) as appModels.Application;
-                    update.spec.syncPolicy = {automated: null};
+                    update.spec.syncPolicy.syncOptions.automated = null;
```
Comment (alexef) [inline ui/src/app/applications/components/application-details/application-details.tsx:1207]:
```suggestion
                    update.spec.syncPolicy.automated = null;
```

**Comment by alexef** [comment]
I've updated the PR description with testing instructions. also [raised it here](https://cloud-native.slack.com/archives/C020XM04CUW/p1742816679992589)

**Review by linghaoSu — APPROVED** [review]
LGTM

**Comment by alexef** [comment]
@ishitasequeira any chance this can be merged 🙏 ?
