### PR TITLE
No longer waits for healthy before completing sync op. Closes #1715

### LINKED ISSUE #1715: Sync operation unnecessary waits for a healthy state of all resources
**Describe the bug**
Sync operation unnecessary waits for a healthy state of all resources even if user has a single "wave"

**To Reproduce**
1. Sync any deployment which consist of a single wave.
2. Sync operation stays in running state until all resources are healty or degraded.

**Expected behavior**
The last waive should not wait for a healthy state of all resources. This is changing sync operation behavior.

**Version**: 1.1.0 (unreleased)

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

File: controller/sync.go [hunk 1]
```diff
@@ -259,14 +259,15 @@ func (sc *syncContext) sync() {
 	// If no sync tasks were generated (e.g., in case all application manifests have been removed),
 	// the sync operation is successful.
 	if len(tasks) == 0 {
-		sc.setOperationPhase(v1alpha1.OperationSucceeded, "successfully synced")
+		sc.setOperationPhase(v1alpha1.OperationSucceeded, "successfully synced (no more tasks)")
```
Comment (alexec) [inline controller/sync.go]: So we can differentiante cause.

File: test/e2e/testdata/deprecated-extensions/deployment.yaml [hunk 2]
```diff
@@ -16,7 +16,7 @@ spec:
     spec:
       containers:
         - name: extensions-deployment
-          image: "gcr.io/heptio-images/ks-guestbook-demo:0.1"
+          image: "gcr.io/heptio-images/ks-guestbook-demo:0.2"
```
Comment (alexec) [inline test/e2e/testdata/deprecated-extensions/deployment.yaml]: Make tests faster/robust (minor impact).

File: controller/sync.go [hunk 3]
```diff
@@ -275,6 +276,13 @@ func (sc *syncContext) sync() {
 	sc.log.WithFields(log.Fields{"tasks": tasks}).Debug("wet-run")
 	if !sc.runTasks(tasks, false) {
 		sc.setOperationPhase(v1alpha1.OperationFailed, "one or more objects failed to apply")
+	} else {
+		// if it is the last phase/wave and the only remaining tasks are non-hooks, the we are successful
+		// EVEN if those objects subsequently degraded
+		// this does create a special-case logic that we need to deal with
+		if len(preFilterTasks.Filter(func(t *syncTask) bool { return t.phase != phase || wave != t.wave() || t.isHook() })) == 0 {
```
Comment (jessesuen) [inline controller/sync.go]: I think the logic should actually be:

`( t.isHook() && t.isRunnable() )`

Corner case: if I have a Deployment as an application hook (instead of a job/pod/workflow), and we are at the last wave, we should complete as soon as the apply was successful.

Comment (alexec) [reply controller/sync.go]: I'm not sure about this. The `preFilterList` will only contain running tasks (line 613) or tasks that have not been run (I'm assuming this is what you mean by 'isRunnable'). I'm going to refactor this, as the code is complex.

File: controller/sync.go [hunk 4]
```diff
@@ -259,14 +259,19 @@ func (sc *syncContext) sync() {
...
+		sc.setOperationPhase(v1alpha1.OperationSucceeded, "successfully synced (no more tasks)")
 		return
 	}
 
 	// remove any tasks not in this wave
 	phase := tasks.phase()
 	wave := tasks.wave()
 
+	// if it is the last phase/wave and the only remaining tasks are non-hooks, the we are successful
+	// EVEN if those objects subsequently degraded
```
Comment (jessesuen) [inline controller/sync.go]: This handles the common case where neither hooks or waves are used and a sync equates to simply an (asynchronous) `kubectl apply` of manifests, which succeeds immediately.

**Review by jessesuen — APPROVED** [review]
Just wanted to add more reasoning about this logic for future readers of this code.
