### PR TITLE
fix: CMPv2 does not allow symlinks to adjacent files in same git repo. Fixes #13342

### LINKED ISSUE #13342: Argo CD CMPv2 does not allow symlinks to adjacent files in same git repo
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
ArgoCD Application that contains symlinks to adjacent files/folder in same git repo doesn't get resolved properly if the Config Management Plugin v2 is enabled.

- If the application directory is symlink to a folder, the following error happens: 
> time="2023-04-25T09:02:03Z" level=error msg="repository /tmp/_argocd-repo/a396feca-5bf2-4b61-9aca-71e372bf75e7/projects/file-drive/kasane is not the match because error sending stream: no files to send" CWE=775 security=2
- If all files of ArgoCD application are symlinks, the following error happens:
> time="2023-04-25T09:01:18Z" level=error msg="repository /tmp/_argocd-repo/a396feca-5bf2-4b61-9aca-71e372bf75e7/projects/file-drive/kasane-symlink-file is not the match because error sending stream: no files to send" CWE=775 security=2
- If only partial files are symlinks:
> time="2023-04-25T08:58:17Z" level=error msg="repository /tmp/_argocd-repo/888be1f3-f440-4c21-b27c-cd644b6011e6/projects/file-drive/kasane-partial-symlink-file is not the match because error receiving stream response: rpc error: code = Unknown desc = match repository error receiving stream: error decompressing tgz file: illegal filepath in symlink: /tmp/_cmp_server/pkg/kasane/Kasanefile" CWE=775 security=2

**To Reproduce**
I have prepared a git repository that contains different applications that can be used to reproduce the issue: https://github.com/jiachengxu/argocd-symlink-example:
- [kasane](https://github.com/jiachengxu/argocd-symlink-example/tree/main/projects/file-drive/kasane) directory contains a folder symlink.
- [kasane-symlink-file](https://github.com/jiachengxu/argocd-symlink-example/tree/main/projects/file-drive/kasane-symlink-file) contains all symlinks. 
- [kasane-partial-symlink-file](https://github.com/jiachengxu/argocd-symlink-example/tree/main/projects/file-drive/kasane-partial-symlink-file) contains partial files and partial symlinks.
 Creating applications from those directories will fail and reproduce the issue 

**Expected behavior**
Applications that contain symlinks can be created and symlinks can be resolved properly when Config Management Plugin v2 is enabled.

**Screenshots**
image
image
image

**Version**

```shell
v2.6.7
```

**Logs**

- If the application directory is symlink to a folder, the following error happens: 
> time="2023-04-25T09:02:03Z" level=error msg="repository /tmp/_argocd-repo/a396feca-5bf2-4b61-9aca-71e372bf75e7/projects/file-drive/kasane is not the match because error sending stream: no files to send" CWE=775 security=2
- If all files of ArgoCD application are symlinks, the following error happens:
> time="2023-04-25T09:01:18Z" level=error msg="repository /tmp/_argocd-repo/a396feca-5bf2-4b61-9aca-71e372bf75e7/projects/file-drive/kasane-symlink-file is not the match because error sending stream: no files to send" CWE=775 security=2
- If only partial files are symlinks:
> time="2023-04-25T08:58:17Z" level=error msg="repository /tmp/_argocd-repo/888be1f3-f440-4c21-b27c-cd644b6011e6/projects/file-drive/kasane-partial-symlink-file is not the match because error receiving stream response: rpc error: code = Unknown desc = match repository error receiving stream: error decompressing tgz file: illegal filepath in symlink: /tmp/_cmp_server/pkg/kasane/Kasanefile" CWE=775 security=2

### PR DESCRIPTION
**Pull request by jiachengxu**
Fixes: #13342 
This PR fixes the issue that CMP v2 doesn't work with applications that have symlinks to adjacent file in the same git repo.
The root cause is that when calling `detectConfigManagementPlugin`, we should pass repo path and app path, otherwise, the check can fail since the symlinks can be pointing to files out of the app path but in the repo path.
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -1918,7 +1918,7 @@ func runConfigManagementPluginSidecars(ctx context.Context, appPath, repoPath, p
 	}
 
 	// detect config management plugin server (sidecar)
-	conn, cmpClient, err := discovery.DetectConfigManagementPlugin(ctx, appPath, pluginName, env, tarExcludedGlobs)
```
Comment (alexmt) [inline reposerver/repository/repository.go:1921]: The `DetectConfigManagementPlugin` is supposed to check the path provided in the second argument and return true if the directory contains the file that matches the settings provided in  `spec.discover` .

So if we provide `repoPath` in the second parameter then repo server would try to render manifests from e.g. `my-app` sub-directory but would try to pick a plugin based on root repo directory which is incorrect.


If I'm understanding it correctly we have performance optimization here: when repo server is trying to check if given sub-path matches plugin it sends only sub-directory content. But it causes problem with symlinks. I think only option is to send whole repo and sub-directory that should be checked. gRPC method of CMP plugin already supports it. So we just need to change [DetectConfigManagementPlugin](https://github.com/argoproj/argo-cd/blob/03513ebeec3e70926f6c33328d11be5c99478c18/util/app/discovery/discovery.go#LL88C6-L88C34) method so it would receive both `repoPath` and `appPath`

**Review by alexmt — CHANGES_REQUESTED** [review]

File: test/e2e/custom_tool_test.go [hunk 2]
```diff
@@ -350,3 +350,60 @@ func TestPreserveFileModeForCMP(t *testing.T) {
...
+	Given(t).
+		And(func() {
+			go startCMPServer("./testdata/cmp-symlink")
+			time.Sleep(1 * time.Second)
+			os.Setenv("ARGOCD_BINARY_NAME", "argocd")
+		}).
+		Path("guestbook-partial-symlink-files").
+		When().
+		CreateFromFile(func(app *Application) {
+			app.Spec.Source.Plugin = &ApplicationSourcePlugin{Name: "cmp-symlink-v1.0"}
```
Comment (alexmt) [inline test/e2e/custom_tool_test.go:364]: I plugin name is provided then discovery is not used: repo server connects to the specified CMP plugin server. We need to test without plugin name to confirm discovery is fixed.

File: reposerver/repository/repository.go (hunk 1 above)
Comment (jiachengxu) [reply reposerver/repository/repository.go:1921]: Got it, I have updated the PR, please take a look!

File: test/e2e/custom_tool_test.go (hunk 2 above)
Comment (jiachengxu) [reply test/e2e/custom_tool_test.go]: I have updated test with the discovery setting, please take a look

**Comment by alexmt** [comment]
Can you check why `TestCMPDiscoverWithFileName` is failing please ? Looks like it is related to changes and not flakiness.

File: test/e2e/testdata/cmp-fileName/plugin.yaml [hunk 3]
```diff
@@ -7,4 +7,4 @@ spec:
   generate:
     command: [sh, -c, 'echo "{\"kind\": \"ConfigMap\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"$ARGOCD_APP_NAME\", \"namespace\": \"$ARGOCD_APP_NAMESPACE\", \"annotations\": {\"Foo\": \"$FOO\", \"KubeVersion\": \"$KUBE_VERSION\", \"KubeApiVersion\": \"$KUBE_API_VERSIONS\",\"Bar\": \"baz\"}}}"']
   discover:
-    fileName: "subdir/s*.yaml"
+    fileName: "cmp-fileName/subdir/s*.yaml"
```
Comment (jiachengxu) [inline test/e2e/testdata/cmp-fileName/plugin.yaml:10]: > Can you check why TestCMPDiscoverWithFileName is failing please ? Looks like it is related to changes and not flakiness.

@alexmt It turned out that this test failed because of the test case is wrong.
As stated on the [config management plugin doc](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#write-the-plugin-configuration-file), the `filename` should be applied to the repository root not the application source:
> fileName is a glob pattern (https://pkg.go.dev/path/filepath#Glob) that is applied to the repository's root directory (not the Application source directory). If there is a match, this plugin may be used for the repository.

and in the test case, the `testdata` is the repo, so we need to have `cmp-fileName` as part of the `fileName`.
It was not caught because we only passed `appPath` but not `repoPath` so the `appPath` was considered as `repoPath` and `cmp-fileName` was not needed.

File: test/e2e/testdata2/guestbook-partial-symlink-files/guestbook-ui-deployment.yaml [hunk 4]
```diff
@@ -0,0 +1 @@
+../guestbook/guestbook-ui-deployment.yaml
```
Comment (jiachengxu) [inline test/e2e/testdata2/guestbook-partial-symlink-files/guestbook-ui-deployment.yaml:1]: I have to put all test files related to symlinks to a dedicated folder `testdata2` otherwise it will fail other tests with `repository contains out-of-bounds symlinks` errors. I think that is because in the codebase we deny all absolute symlinks (https://github.com/argoproj/argo-cd/blob/master/util/app/path/path.go#L67), however, in our tests, we use local repo in `/tmp/` folder and that means all files are absolute paths.

**Review by alexmt — APPROVED** [review]
Thank you! LGTM

File: test/e2e/testdata/cmp-fileName/plugin.yaml (hunk 3 above)
Comment (crenshaw-dev) [reply test/e2e/testdata/cmp-fileName/plugin.yaml:10]: This change is causing issues, so I'm going to try to revert this change without reverting your whole bugfix. https://github.com/argoproj/argo-cd/issues/13940
