### PR TITLE
fix: Prevent cluster privilege warning for cluster add cmd

### LINKED ISSUE #8957: Argo CD CLI throws misleading warning about cluster privileges when adding a cluster with namespace privileges
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The Argo CD CLI throws a misleading warning about cluster level privileges when adding a cluster with namespace level privileges.

Only the warning looks wrong, the cluster is still added to Argo CD with namespace level permissions. 

**To Reproduce**

1. Add a cluster using the Argo CD CLI with the `--namespace` flag.
2. View the WARNING provided by the CLI
```
WARNING: This will create a service account `argocd-manager` on the cluster referenced by context `example-kube-context` with full cluster level admin privileges.
```

**Expected behavior**

The WARNING is not displayed because the `argocd-manager` ServiceAccount is not created with cluster level admin privileges. 

**Screenshots**

**Version**

```shell
argocd: v2.1.10+de6735c
  BuildDate: 2022-02-05T01:20:40Z
  GitCommit: de6735c386b2bc6cad2372f43881df7898fb13cb
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.10+de6735c
  BuildDate: 2022-02-05T01:18:20Z
  GitCommit: de6735c386b2bc6cad2372f43881df7898fb13cb
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by ksch84**
Fixes #8957

Signed-off-by: ksch84 <ksch84@protonmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: cmd/argocd/commands/cluster.go [hunk 1]
```diff
@@ -115,8 +115,9 @@ func NewClusterAddCommand(clientOpts *argocdclient.ClientOptions, pathOpts *clie
 					managerBearerToken, err = clusterauth.GetServiceAccountBearerToken(clientset, clusterOpts.SystemNamespace, clusterOpts.ServiceAccount)
 				} else {
 					isTerminal := isatty.IsTerminal(os.Stdout.Fd()) || isatty.IsCygwinTerminal(os.Stdout.Fd())
+					isNamespaced := len(clusterOpts.Namespaces) > 0
 
-					if isTerminal && !skipConfirmation {
+					if isTerminal && !skipConfirmation && !isNamespaced {
```
Comment (crenshaw-dev) [inline cmd/argocd/commands/cluster.go:120]: It will still create a ServiceAccount with full namespace-level privileges though, right? Should we just add a second warning/prompt specific to that case?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: cmd/argocd/commands/cluster.go (hunk 1 above)
Comment (ksch84) [reply cmd/argocd/commands/cluster.go]: @crenshaw-dev You are right! I made some changes and dropped the `admin` word from the warning message. It now looks like: `...with full cluster level privileges...` or `...with full namespace level privileges...` based on the absence/presence of the namespace flag. Please let me know if that's ok.
Thanks!

Comment (crenshaw-dev) [reply cmd/argocd/commands/cluster.go]: That looks awesome, thanks!

**Review by crenshaw-dev — APPROVED** [review]
LGTM! I'd ask for a unit test, but setting up the test to handle the y/n prompt could be a lot of work. Happy to merge as-is.

**Comment by ksch84** [comment]
thanks @crenshaw-dev !
