### PR TITLE
fix(project): Do not block project update when a cluster referenced in an App doesn't exist

### LINKED ISSUE #23650: Can't create sync windows if a cluster doesn't exist anymore but is still referenced in an app
Since Argo 3.0, a new behavior appeared regarding the sync apps.

We have the case in some of our instances, where clusters were deleted but some apps remained and where not correctly cleaned-up.

If it happens that some Applications reference as destination a cluster that does not exist anymore, it's no longer possible to create a Sync Window.

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Image

**To Reproduce**

Create an app referencing a non-existing cluster:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  destination:
    namespace: mynamespace
    server: https://mycluster
  source:
    path: .
    repoURL: https://test-repo
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

Try to create any sync window in the same project.
The error above appears.

**Expected behavior**

It should allow to create sync windows.

**Version**

```shell
3.0.6
```

### PR DESCRIPTION
**Pull request by OpenGuidou**
Fixes #23650

As it's present since ArgoCD 3.0, I'd like this to be cherry-picked on the release as well.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by ppapapetrou76 — COMMENTED** [review]
The change is simple and clear and the Unit test added very descriptive so all good

I just want to make sure ( maybe someone from the maintainers ) that the original change in the behavior was a side effect and it wan't done on purpose

File: server/project/project.go [hunk 1]
```diff
@@ -412,7 +412,8 @@ func (s *Server) Update(ctx context.Context, q *project.ProjectUpdateRequest) (*
 		destCluster, err := argo.GetDestinationCluster(ctx, a.Spec.Destination, s.db)
 		if err != nil {
 			if err.Error() != argo.ErrDestinationMissing {
-				return nil, err
+				// If cluster is not found, we should discard this app, as it's most likely already in error
```
Comment (rumstead) [inline server/project/project.go:415]: For an application that is deploying to a removed cluster by server, wouldn't [this](https://github.com/argoproj/argo-cd/blob/e692a22b0114474360a31fbcbe297d7317f2dd5e/util/argo/argo.go#L1035) be the returned error?

File: server/project/project.go [hunk 2]
```diff
@@ -412,7 +412,8 @@ func (s *Server) Update(ctx context.Context, q *project.ProjectUpdateRequest) (*
 		destCluster, err := argo.GetDestinationCluster(ctx, a.Spec.Destination, s.db)
 		if err != nil {
 			if err.Error() != argo.ErrDestinationMissing {
```
Comment (rumstead) [inline server/project/project.go:414]: I really wish we could use `errors.Is`. Should we still increment the `invalidDstCount++` before continuing?

Comment (OpenGuidou) [reply server/project/project.go:414]: I think the intended behavior is to find destinations that become invalid with the project update.
In the case here, the destination would already be in error as the cluster does not exist. So I wouldn't increment it.

**Review by rumstead — APPROVED** [review]
I am not as familiar with this code, but over LGTM. maybe @crenshaw-dev can take a peek as well.

**Review by andrii-korotkov — APPROVED** [review]

**Comment by OpenGuidou** [comment]
@crenshaw-dev : Would you have any comment about this fix ?

**Comment by OpenGuidou** [comment]
Hi @andrii-korotkov , @rumstead, how can we move forward with this fix ?

**Comment by neith00** [comment]
This fix seems nice to fix the issue we are also facing. Would be happy to see it merged.

**Review by crenshaw-dev — APPROVED** [review]
