### PR TITLE
fix: Better handling of base64 encoded passwords/credentials

### LINKED ISSUE #4858: Better handling of base64 encoded passwords/credentials
# Summary

Argo CD should strip off any trailing CR and LF characters from passwords that are stored base64 encoded in Argo CD's configuration secrets.

# Motivation

When Argo CD needs to store a base64 encoded somewhere (i.e. oAuth secrets, repository passwords, etc), users tend to base64 encode these passwords in the following way:

```
echo "somepassword" | base64
```

This will encode the trailing newline added by `echo`, and Argo CD will use the decoded string in a verbatim way, including any trailing CRLF characters, and pass them to the system requiring these credentials. This will obviously result in an authentication failure, because `somepassword` is different from `somepassword\n'.

# Proposal

The best approach in my opinion would be to provide a new set of methods, i.e. `DecodeBase64Credential(encoded string, verbatim bool) string`, which should be used for decoding all base64 encoded credentials in the code base. 

If `verbatim` is set to false, it will strip any trailing CRLF characters (or possibly, all white-space) from the decoded string before returning it. Otherwise, string will be returned as-is.

A contra argument would be, that user input should not be mutated, as the Kubernetes people decided to do (refer https://github.com/kubernetes/kubernetes/issues/23404). While this approach is very valid for Kubernetes, since they don't know how the data will be used, in Argo CD we have a lot more of contextual knowledge about where and how data from our secrets will be used.

### PR DESCRIPTION
**Pull request by gaganhegde**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Issue details: https://github.com/argoproj/argo-cd/issues/4858

There might occur a situation where the user incorrectly appends a space (i.e. CRLF character ) to the secrets required by argocd, this PR is used to correct those errors in the event of an incorrect space in the user input.

The following secrets will be corrected :
repositories: referenced from config map
helm repositories: referenced from  config map
oidc secrets: referenced from  config map
dex secrets: referenced from config map

"webhook.github.secret":      referenced from v1.secrets Name:argocd-secret   
"webhook.bitbucket.uuid":        referenced from v1.secrets Name:argocd-secret   
"webhook.bitbucketserver.secret": referenced from v1.secrets Name:argocd-secret   
"webhook.gogs.secret":           referenced from v1.secrets Name:argocd-secret

### CODE REVIEW

File: util/settings/settings.go [hunk 1]
```diff
@@ -1282,13 +1282,16 @@ func ReplaceStringSecret(val string, secretValues map[string]string) string {
 	if val == "" || !strings.HasPrefix(val, "$") {
 		return val
 	}
+	if !strings.HasPrefix(val, "$") {
+		return strings.TrimSpace(val)
+	}
```
Comment (jannfis) [inline util/settings/settings.go:1287]: I think this code will actually never be executed, because the condition `!strings.HasPrefix(val, "$")` is already tested for in the `if` branch above.

File: util/settings/settings.go [hunk 2]
```diff
@@ -848,19 +848,19 @@ func updateSettingsFromSecret(settings *ArgoCDSettings, argoCDSecret *apiv1.Secr
 		errs = append(errs, &incompleteSettingsError{message: "server.secretkey is missing"})
 	}
 	if githubWebhookSecret := argoCDSecret.Data[settingsWebhookGitHubSecretKey]; len(githubWebhookSecret) > 0 {
-		settings.WebhookGitHubSecret = string(githubWebhookSecret)
+		settings.WebhookGitHubSecret = strings.TrimSpace(string(githubWebhookSecret))
```
Comment (jannfis) [inline util/settings/settings.go:851]: I'm unsure whether we should mutate the values stored in `settings` here and write them back to the `settings` struct. The `argocd-secret` will be updated with these settings, and this could lead to Out-of-Sync conditions when Argo CD is managing itself in Git (see https://github.com/argoproj/argo-cd/blob/d4ef7444545549cd4763bc8bca3f26f1899d946e/util/settings/settings.go#L921)

On the other hand, this could be used as an indicator that the stored password has unwanted trailing CRLF. But we should have this documented, at least in the FAQ (for example, "Why is my argocd-secret out of sync?")

**Review by jannfis — DISMISSED** [review]
Thanks for this awesome PR @gaganhegde - great code quality and unit tests as well!

I have some minor comments with one would require finding a decision. Please see below.

File: util/settings/settings.go (hunk 2 above)
Comment (gaganhegde) [reply util/settings/settings.go:851]: Thank you @jannfis for the prompt review, I personally think this might be confusing to users who have a well set up argo-cd. I think just logging the warning about the extra CRLF characters in the secret string might suffice.

**Comment by rbreeze** [comment]
Fixes #4858

**Comment by rbreeze** [comment]
@gaganhegde Are you still working on this? I'd be happy to finish it if not. We're trying to get this in for 1.9 release

**Comment by gaganhegde** [comment]
I think the PR is close to ready, I can wind up the required change by this Saturday. @rbreeze but if it's really urgent then please go ahead.

**Comment by rbreeze** [comment]
If you can wrap this up by Saturday that would be fantastic, it's not so urgent that it can't wait until the end of this week. Thanks!

**Comment by gaganhegde** [comment]
Hey @rbreeze @jannfis, this PR can be reviewed now. Thank you.

**Comment by rbreeze** [comment]
Can you resolve the merge conflicts in `util/db/`?

**Comment by gaganhegde** [comment]
Hey @rbreeze, the conflicts have been resolved. Thank you.

**Comment by gaganhegde** [comment]
Hey @rbreeze any update on this issue?

**Review by alexmt — APPROVED** [review]
LGTM. Great PR. thank you @gaganhegde !
