### PR TITLE
fix: Fix semver resolution

### LINKED ISSUE #19495: The ArgoCD v2.12.0 doesn't work with tag tracking
Hello.

Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

Unfortunately, after we did upgrade from version v2.8.3 to v.2.12.0 the tag tracking doesn't work anymore.

**To Reproduce**

This configuration doesn't work anymore

``` sources:
    - repoURL: https://github.com/org/repo
      path: .
      targetRevision: "0.41.36" 
```

**Expected behavior**

The Sync status is expected to be - **Sync OK**

**Version**

```shell
{
  "app.kubernetes.io/component": "server",
  "app.kubernetes.io/instance": "argocd",
  "app.kubernetes.io/managed-by": "Helm",
  "app.kubernetes.io/name": "argocd-server",
  "app.kubernetes.io/part-of": "argocd",
  "app.kubernetes.io/version": "v2.12.0",
  "helm.sh/chart": "argo-cd-7.4.1",
  "pod-template-hash": "75d8977c45"
}


```

**Logs**

```
{"error":"error parsing version for tag: Version segment starts with 0","grpc.code":"Unknown","grpc.method":"GenerateManifest","grpc.service":"repository.RepoServerService","grpc.start_time":"2024-08-12T13:03:37Z","grpc.time_ms":613.995,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2024-08-12T13:03:37Z"}
```

Thank you for the help

### PR DESCRIPTION
**Pull request by pierreyves-lebrun**
# Description:

This PR addresses an issue where a repository with invalid semver references can't be resolved. This is caused by [this change](https://github.com/argoproj/argo-cd/pull/17566/files#diff-b431853d628a3d3169b6298c356c8b57fed26c1174269fa3ab356a128ed9ecc4) which assumes that all references on the repository are valid semver revisions.

# Solution:

The code has been modified to ensure that the revision is a valid semver constraint before attempting to resolve it.

# Related Issue:

Fixes #19495

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: util/git/client.go [hunk 1]
```diff
@@ -710,12 +709,24 @@ func (m *nativeGitClient) resolveSemverRevision(revision string, refs []*plumbin
 		tag := ref.Name().Short()
 		version, err := semver.NewVersion(tag)
 		if err != nil {
-			if errors.Is(err, semver.ErrInvalidSemVer) {
-				log.Debugf("Invalid semantic version: %s", tag)
-				continue
+			switch {
```
Comment (crenshaw-dev) [inline util/git/client.go:712]: Instead of a switch with custom error strings, why not just use the returned error itself? i.e. only use what's currently coded as the `default` case.

**Review by crenshaw-dev — DISMISSED** [review]
Thanks for the PR! Can you add tests to cover this?

**Review by todaywasawesome — CHANGES_REQUESTED** [review]
@pierreyves-lebrun can you fix the linting issue?

File: util/git/client.go [hunk 2]
```diff
@@ -631,13 +631,17 @@ func (m *nativeGitClient) lsRemote(revision string) (string, error) {
...
-	}
-
-	if semverSha != "" {
-		return semverSha, nil
+	// Check if the revision is a valid semver constraint before attempting to resolve it
+	if constraint, err := semver.NewConstraint(revision); err == nil {
+		semverSha, err := m.resolveSemverRevision(constraint, refs)
+		if err != nil {
+			return "", err
+		}
```
Comment (ishitasequeira) [inline util/git/client.go:639]: With the current change in the PR, the function `resolveSemverRevision` never returns an error.  Was this intended?

**Review by alexmt — APPROVED** [review]
LGTM

**Review by todaywasawesome — APPROVED** [review]
Thanks!
