### PR TITLE
fix: revert kubeVersion change to preserve trailing `+`

### LINKED ISSUE #23778: Helm does not support --kube-version with trailing "+"
Checklist:

* [+] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [+] I've included steps to reproduce the bug.
* [+] I've pasted the output of `argocd version`.

**Describe the bug**

In the `v3.1.0-rc3` "execute helm template command" fails with error:
`Error: invalid kube version '1.28+': Invalid Semantic Version`
Related change is there ea97dec6

**To Reproduce**

- Deploy the ArgoCD onto k8s cluster
- Create an ApplicationSet with helm chart
- Push ApplicationSet into the repo
- Sync ArgoCD

**Expected behavior**

The helm template command must execute successfully. 

**Screenshots**

**Version**

```shell
{
    "Version": "v3.2.0+276d92d.dirty",
    "BuildDate": "2025-07-11T14:52:48Z",
    "GitCommit": "276d92d4e0b0b011f4bf0db0bc6ab6310f128087",
    "GitTreeState": "dirty",
    "GoVersion": "go1.24.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.7.0 2025-06-28T07:00:07Z",
    "HelmVersion": "v3.18.4+gd80839c",
    "KubectlVersion": "v0.33.1",
    "JsonnetVersion": "v0.21.0"
}
```

**Logs**

The error on sync
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): failed to execute helm template command: failed to get command args to log: `helm template . --name-template <APP_NAME> --namespace <NAMESPACE> --kube-version 1.28+ --values <TEMP_DIR_1>/values.yaml --values <TEMP_DIR_2> <api versions removed> --include-crds` failed exit status 1: Error: invalid kube version '1.28+': Invalid Semantic Version
```

### PR DESCRIPTION
**Pull request by agaudreault**
Reverts https://github.com/argoproj/argo-cd/pull/22650 until https://github.com/helm/helm/pull/31091 is released. This preserves the backward compatibility to older Helm versions.

This will use the k8s libs to correctly parse the kubernetes version instead of the original method fixing https://github.com/argoproj/argo-cd/issues/22606

Closes https://github.com/argoproj/argo-cd/issues/23778

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -1168,17 +1169,36 @@ func isSourcePermitted(url string, repos []string) bool {
 	return p.IsSourcePermitted(v1alpha1.ApplicationSource{RepoURL: url})
 }
 
+// parseKubeVersion is an helper function to remove the non-semantic information supported by kubernetes
```
Comment (pjiang-dev) [inline reposerver/repository/repository.go:1172]: nit: parseKubeVersion is a helper

**Review by reggie-k — APPROVED** [review]
