### PR TITLE
fix: added extra protection to syncing app with replace

### LINKED ISSUE #9093: Extra protection around destructive features such as the "replace" checkbox
# Summary

Potentially the "replace" checkbox might cause a lot of damage to running clusters, and it will be great to have extra measures around it, especially when using the app of apps pattern

# Motivation

When using the "replace" checkbox even though it is marked with a yellow triangle and a confirmation popup, the user might not fully understand the implications of the checkbox, but I would like to emphasize the difference between a standalone app, and an app of apps application, when accidentally using it on an app of apps application the implication might be catastrophic, deleting and recreating hundreds of apps with a single feature, this scenario happened to my workplace running in production with hundreds of applications, and an engineer that knows exactly what this checkbox means, didn't notice he is looking at the app of apps and not the application itself and practically deleted the entire cluster.

# Proposal

I have few options in mind:
1. label an app of apps application differently and remove this checkbox from this type of application
2. implement some kind of a lab with feature toggles, and wrap the checkbox with a feature flag that admins can turn off.
3. only root users, not even admins can use such a destructive checkbox
4. delete this feature, we can easily delete/create when something is not working

### PR DESCRIPTION
**Pull request by ciiay**
Signed off: [yicai@redhat.com](mailto:yicai@redhat.com)
Closes: https://github.com/argoproj/argo-cd/issues/9093

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Solution summary:
1. Only pops up Warning prompt when any App of Apps is selected for Syncing with Replace option.
2. Points out the impact in the Warning prompt directly.
3. Adds "(App Of Apps)" prefix to the app name in the app selection checkbox list.

Updated App selection list:
Screen Shot 2022-04-22 at 9 02 04 PM

Updated Warning popup window:
Screen Shot 2022-04-22 at 9 01 49 PM

### CODE REVIEW

File: ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx [hunk 1]
```diff
@@ -55,18 +110,19 @@ export const ApplicationsSyncPanel = ({show, apps, hide}: {show: boolean; apps:
...
-                            }
+                            // const replace = params.syncOptions?.findIndex((opt: string) => opt === 'Replace=true') > -1;
+                            // setReplace(replace);
+                            // if (replace) {
+                            //     const confirmed = await ctx.popup.confirm('Synchronize using replace?', () => (
+                            //         <div>
+                            //             <i className='fa fa-exclamation-triangle' style={{color: ARGO_WARNING_COLOR}} /> {REPLACE_WARNING} Are you sure you want to continue?
+                            //         </div>
+                            //     ));
+                            //     if (!confirmed) {
```
Comment (terrytangyuan) [inline ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:121]: Remove unused code

File: ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx [hunk 2]
```diff
@@ -2,23 +2,78 @@ import {ErrorNotification, FormField, NotificationType, SlidingPanel} from 'argo
...
+                appOfAppsList.push(app.metadata.labels[InstanceLabel]);
+            }
+        });
+        const newAppList: models.Application[] = apps.map(app => {
+            const newApp = {...app, isAppOfAppsPattern: false};
+            if (appOfAppsList.indexOf(app.metadata.name) > -1) {
+                newApp.isAppOfAppsPattern = true;
+            }
+            return newApp;
+        });
```
Comment (terrytangyuan) [inline ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:69]: Why not modify the existing app lists and update `isAppOfAppsPattern` field?

File: ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx [hunk 3]
```diff
@@ -2,23 +2,78 @@ import {ErrorNotification, FormField, NotificationType, SlidingPanel} from 'argo
...
+            });
+        } else {
+            currentForm.submitForm(null);
+        }
+    };
+
+    React.useEffect(() => {
+        const appOfAppsList: string[] = [];
+        apps.forEach(app => {
+            const appName = app.metadata.labels && app.metadata.labels[InstanceLabel];
```
Comment (terrytangyuan) [inline ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:58]: Is this the correct indicator of app of apps pattern?

Comment (terrytangyuan) [inline ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:58]: Is this the correct indicator of app of apps pattern?

File: ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx (hunk 2 above)
Comment (ciiay) [reply ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:69]: Thanks for the review. This is how I edited the existing app list. If the app name matches any item in the `appPfAppsList`, then assign `true` to the `isAppPfAppsPattern` field. Or I didn't get what you mean.

File: ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx (hunk 3 above)
Comment (ciiay) [reply ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:58]: This label "determine which resources form the app", which could be "helm", "kustomize" or another app etc. It's not only for the app of apps pattern but if an app is created by another app, the resource app name is automatically generated to this label. 

This is the easiest way to tell if an app is App of Apps Pattern and I wanted to bring the solution up here for an open discussion and see if this is a reliable way to do it.

Comment (ciiay) [reply ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:58]: @alexmt @rbreeze How do you think about this implementation? I tested with [/helm-guestbook](https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook) and [/kustomize-guestbook](https://github.com/argoproj/argocd-example-apps/tree/master/kustomize-guestbook), none of these apps have the instance label in metadata.

Comment (ciiay) [reply ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:58]: Update: checked out with Alex in the Argo CD Contributor's meeting. It's confirmed that `status.resources` list is a reliable field to check if an app is App of Apps Pattern. If there are more than 0 apps. in the `status.resources` field, it means this app is App of Apps Pattern. Will update this PR.

File: ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (ciiay) [reply ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx]: Because `apps` is the condition of `useEffect`, if the value of `apps` gets updated, it triggers lines inside `useEffect` method which will cause a execution loop.

**Comment by terrytangyuan** [comment]
@ciiay Looks like you accidentally pushed many other commits to this PR.

**Comment by ciiay** [comment]
> @ciiay Looks like you accidentally pushed many other commits to this PR.

Thanks for the reminder @terrytangyuan . Issue fixed :)

File: ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx [hunk 4]
```diff
@@ -19,6 +20,34 @@ export const ApplicationsSyncPanel = ({show, apps, hide}: {show: boolean; apps:
...
+    const syncHandler = (currentForm: FormApi, ctx: ContextApis, applications: models.Application[]) => {
+        const formValues = currentForm.getFormState().values;
+        const replaceChecked = formValues.syncOptions?.includes('Replace=true');
+        const selectedApps = [];
+        const selectedAppOfApps: models.Application[] = [];
+        let containAppOfApps = false;
+
+        for (const key in formValues) {
+            if (key.startsWith('app/') && formValues[key]) {
+                selectedApps.push(applications[parseInt(key.slice(key.lastIndexOf('/') + 1), 10)]);
```
Comment (saumeya) [inline ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:32]: Yi, Could you explain the logic behind this line, what does the slice contain?

**Review by saumeya — APPROVED** [review]
LGTM
Great work Yi, tested the changes and works well! I do have one question though, because the field for `isAppofAppPattern` is added in _models.ts_, is there any alternative place where the logic can be added other than the _filter function_ call.

**Review by rbreeze — APPROVED** [review]
LGTM

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Review by rbreeze — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]

File: ui/src/app/shared/components/application-selector/application-selector.tsx [hunk 5]
```diff
@@ -18,7 +18,7 @@ export const ApplicationSelector = ({apps, formApi}: {apps: models.Application[]
                     <label key={app.metadata.name} style={{marginTop: '0.5em', cursor: 'pointer'}}>
                         <CheckboxField field={`app/${i}`} />
                         &nbsp;
-                        {app.metadata.name}
+                        {app.isAppOfAppsPattern ? `(App of Apps)${app.metadata.name}` : app.metadata.name}
```
Comment (keithchong) [inline ui/src/app/shared/components/application-selector/application-selector.tsx:21]: Add a space after the right bracket ')'

Comment (keithchong) [inline ui/src/app/shared/components/application-selector/application-selector.tsx:21]: Add a space after the right bracket ')'

File: ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx [hunk 6]
```diff
@@ -2,12 +2,13 @@ import {ErrorNotification, FormField, NotificationType, SlidingPanel} from 'argo
 import * as React from 'react';
```
Comment (keithchong) [inline ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:2]: As discussed, we should look at `application-sync-panel` as well.

File: ui/src/app/shared/components/application-selector/application-selector.tsx (hunk 5 above)
Comment (keithchong) [reply ui/src/app/shared/components/application-selector/application-selector.tsx:21]: As discussed, we could probably redesign this so that the app of apps are listed out separately under a different list or category, so it's even more obvious.  This can be done later in a separate PR.

Comment (ciiay) [reply ui/src/app/shared/components/application-selector/application-selector.tsx:21]: Thanks for the review. Added space after the right bracket in this PR.

File: ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx (hunk 6 above)
Comment (ciiay) [reply ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx:2]: Will include this `application-sync-panel` in the redesign issue. Thanks for the catch 👍

**Review by keithchong — APPROVED** [review]
