### PR TITLE
fix: disable jwt claim audience validation #5381

### LINKED ISSUE #5381: Authentication error occurs for >=v1.8.2
**Describe the bug**

version: >=v1.8.2

For environments using existing OIDC provider, argocd cli returns following error
```
argocd app list
FATA[0001] oauth2: cannot fetch token: 404 Not Found
Response: 404 page not found
````

**To Reproduce**

upgrade argocd to >=v1.8.2 on an environment using existing OIDC provider

**workaround**

Removed the `refresh-token` value from `$HOME/.argocd/config` and that fixed the issue

**Version**

```shell
 argocd version
argocd: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:33:00Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:20:39Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
```

Another instance: https://github.com/argoproj/argo-cd/discussions/5253

### PR DESCRIPTION
**Pull request by kshamajain99**
Signed-off-by: kshamajain99 <kshamajain99@gmail.com>

closes #5381
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

File: pkg/apiclient/apiclient.go [hunk 1]
```diff
@@ -349,14 +349,14 @@ func (c *client) refreshAuthToken(localCfg *localconfig.LocalConfig, ctxName, co
 		return err
 	}
 	parser := &jwt.Parser{
-		ValidationHelper: jwt.NewValidationHelper(jwt.WithoutClaimsValidation()),
+		ValidationHelper: jwt.NewValidationHelper(jwt.WithoutClaimsValidation(), jwt.WithoutAudienceValidation()),
```
Comment (kshamajain99) [inline pkg/apiclient/apiclient.go:352]: @alexmt Should we disable audience validation for all jwt-go/v4 parsers? 
Based on https://github.com/argoproj/argo-cd/pull/5184/files

Comment (alexmt) [reply pkg/apiclient/apiclient.go:352]: I think you are right. Nice catch! We need to update all other places as well.

**Review by alexmt — APPROVED** [review]
