### PR TITLE
fix: make sure repo server discard cached empty response

### LINKED ISSUE #6707: argocd-repo-server crashed
**Describe the bug**

Repo server was continuously crashing with the error below:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x1f709c6]
goroutine 1252 [running]:
github.com/argoproj/argo-cd/v2/reposerver/apiclient.(*ManifestResponse).MarshalToSizedBuffer(0x0, 0x4a4f6e8, 0x0, 0x0, 0x40bb45, 0x29999e0, 0x2c52420)
	/go/src/github.com/argoproj/argo-cd/reposerver/apiclient/repository.pb.go:2043 +0x26
github.com/argoproj/argo-cd/v2/reposerver/apiclient.(*ManifestResponse).Marshal(0x0, 0x2c52420, 0x0, 0x7fd9fc3f6198, 0x0, 0x1)
	/go/src/github.com/argoproj/argo-cd/reposerver/apiclient/repository.pb.go:2026 +0x7a
google.golang.org/grpc/encoding/proto.codec.Marshal(0x2c52420, 0x0, 0x0, 0x0, 0x40a51f, 0xc00003a000, 0x29b3380)
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/encoding/proto/proto.go:70 +0x199
google.golang.org/grpc.encode(0x7fd9fc4b8450, 0x4a4f6e8, 0x2c52420, 0x0, 0x4a4f6e8, 0x321f6f8, 0xc001fd12c0, 0x2ca6c80, 0xc000e64100)
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/rpc_util.go:511 +0x52
google.golang.org/grpc.(*Server).sendResponse(0xc000402600, 0x3242c38, 0xc0014ad380, 0xc000e64000, 0x2c52420, 0x0, 0x0, 0x0, 0xc001c10f9a, 0x0, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:805 +0x91
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000402600, 0x3242c38, 0xc0014ad380, 0xc000e64000, 0xc00055e510, 0x48f47c0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:1004 +0x5d1
google.golang.org/grpc.(*Server).handleStream(0xc000402600, 0x3242c38, 0xc0014ad380, 0xc000e64000, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:1208 +0x122c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000544630, 0xc000402600, 0x3242c38, 0xc0014ad380, 0xc000e64000)
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:686 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:684 +0xa5
```

Error not reproducible locally. Fixed by deleting all keys from redis.

**To Reproduce**

No clear steps to reproduce

**Version**

https://github.com/argoproj/argo-cd/commit/3bba77c36fd2518c02e8757e502b786624f41c2e

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

Closes #6707

### CODE REVIEW

**Review by rbreeze — APPROVED** [review]
LGTM

File: reposerver/cache/cache.go [hunk 1]
```diff
@@ -152,8 +152,8 @@ func (c *Cache) GetManifests(revision string, appSrc *appv1.ApplicationSource, c
 		return fmt.Errorf("Unable to generate hash value: %s", err)
 	}
 
-	// If the expected hash of the cache entry does not match the actual hash value...
-	if hash != res.CacheEntryHash {
+	// If cached result does not have manifests or the expected hash of the cache entry does not match the actual hash value...
+	if hash != res.CacheEntryHash || res.ManifestResponse == nil {
 		log.Warnf("Manifest hash did not match expected value, treating as a cache miss: %s", appName)
```
Comment (wanghong230) [inline reposerver/cache/cache.go:157]: Do you want to update the log message also?

Comment (alexmt) [reply reposerver/cache/cache.go]: sure, it makes sense. updated .
