### PR TITLE
fix: server-side diff shows duplicate containerPorts

### LINKED ISSUE #24786: Server Side Diff shows duplicate container ports
Checklist:

- [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [ ] I've included steps to reproduce the bug.
- [ ] I've pasted the output of `argocd version`.

**Describe the bug**

There was a regression since upgrading to k8s 1.34 that introduced this bug. 
During server side diff we see duplicate containerPorts on deployments due to SSD removing the default field: protocol. This causes the current logic to add a duplicate set of ports without protocol field

**To Reproduce**

deploy an app with containerPorts
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-container-ports
  namespace: default
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 8080
          name: metrics
      - name: sidecar
        image: busybox:1.35
        command: ["sleep", "3600"]
        ports:
        - containerPort: 9090
          name: sidecar-port
```

**Expected behavior**

No diff

**Screenshots**

Image

**Version**

```shell
v3.2.0
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by pjiang-dev**
fixes https://github.com/argoproj/argo-cd/issues/24786

Fixes cases like `.spec.template.spec.containers[name="nginx"].ports[containerPort=8080,protocol="TCP"].protocol`
where protocol is part of the key itself.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by ppapapetrou76 — COMMENTED** [review]
Can we please add a unit test that is supposed to fail without the changes and succeeds with the changes of this PR?

File: gitops-engine/pkg/diff/diff.go [hunk 1]
```diff
@@ -289,29 +289,57 @@ func removeWebhookMutation(predictedLive, live *unstructured.Unstructured, gvkPa
...
+
+	return filteredFields
+}
+
+// isCompositeKeyField checks if a field path represents a field that is part of a composite key
+// in an associative list by examining the PathElement structure.
+// Example: .spec.containers[name="nginx"].ports[containerPort=80,protocol="TCP"].protocol
+// The path elements include:
+//   - PathElement{Key: {name: "nginx"}} - single key (not composite)
+//   - PathElement{Key: {containerPort: 80, protoc ol: "TCP"}} - composite key with 2 fields
```
Comment (ppapapetrou76) [inline gitops-engine/pkg/diff/diff.go]: `nit`
```suggestion
//   - PathElement{Key: {containerPort: 80, protocol: "TCP"}} - composite key with 2 fields
```

**Review by nitishfy — DISMISSED** [review]
Thank you. Can you please add unit tests for it?

File: gitops-engine/pkg/diff/diff.go [hunk 2]
```diff
@@ -289,29 +289,57 @@ func removeWebhookMutation(predictedLive, live *unstructured.Unstructured, gvkPa
...
+			}
+			// This is a composite key
+			for _, keyField := range *pe.Key {
+				if keyField.Name == finalFieldName {
+					return true
+				}
 			}
-		})
-		return adjustedFieldsToRemove
+		}
```
Comment (crenshaw-dev) [inline gitops-engine/pkg/diff/diff.go]:
```suggestion
		if pe.Key == nil {
			continue
		}
		if len(*pe.Key) <= 1 {
			continue
		}
		// This is a composite key
		for _, keyField := range *pe.Key {
			if keyField.Name == finalFieldName {
				return true
			}
		}
```

less nesting

**Review by leoluz — APPROVED** [review]
LGTM

**Comment by pjiang-dev** [comment]
> Thank you. Can you please add unit tests for it?

@nitishfy Added tests can you take another look and approve if good?
