### PR TITLE
fix(appset): add default retry limit for operations triggered via RollingSync when syncPolicy.retry is not defined (#20428)

### LINKED ISSUE #20428: Application operation from progressive sync do not have retries by default
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Application that is generated from ApplicationSet with RollingSync configuration never retried if error occurred and if template does not have retries configuration defined.

**To Reproduce**

-

**Expected behavior**

Progressive sync uses same defaults for retries as regular application sync operation.

**Screenshots**

-

**Version**

```shell
argocd: v2.12.4+27d1e64
  BuildDate: 2024-09-26T06:36:13Z
  GitCommit: 27d1e641b6ea99d9f4bf788c032aeaeefd782910
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

-

### PR DESCRIPTION
**Pull request by mikeshng**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

Fixes https://github.com/argoproj/argo-cd/issues/20428

Extending @StupidScience 's fix in https://github.com/argoproj/argo-cd/pull/20429 by adding a comment and unit testing. When sync operations are triggered from the ApplicationSet RollingSync strategy, apply a default retry limit of 5 if the ApplicationSet's Application template does not define syncPolicy.retry. This aligns with the default value used by the appcontroller auto-sync: https://github.com/argoproj/argo-cd/blob/v3.0.5/controller/appcontroller.go#L2126

In the future, this could be made configurable via the ApplicationSet spec.

### CODE REVIEW

**Comment by mikeshng** [comment]
Hi @StupidScience, since there was no response to @andrii-korotkov-verkada initial review feedback from last year and the original PR https://github.com/argoproj/argo-cd/pull/20429 has been stale for some time, I've opened this PR instead. It's based on @crenshaw-dev 's https://github.com/argoproj/argo-cd/pull/20429#issuecomment-2956543165 Thanks again for bringing this to the community’s attention and for providing the initial fix.

**Review by ishitasequeira — APPROVED** [review]
It would be good to make this configurable via config parameter. But based on @crenshaw-dev's comment from previous MR, the change looks good!!

File: applicationset/controllers/applicationset_controller.go [hunk 1]
```diff
@@ -1441,6 +1441,11 @@ func syncApplication(application argov1alpha1.Application, prune bool) argov1alp
 			},
 		},
 		Sync: &argov1alpha1.SyncOperation{},
+		// Set a retry limit of 5, aligning with the default in Argo CD's appcontroller auto-sync behavior.
+		// This provides consistency for retry behavior across controllers.
+		// See: https://github.com/argoproj/argo-cd/blob/v3.0.5/controller/appcontroller.go#L2126
+		// In the future, consider making this configurable via the ApplicationSet spec.
```
Comment (agaudreault) [inline applicationset/controllers/applicationset_controller.go]: Use permalink. This is already configurable with the code below.
```suggestion
		// See: https://github.com/argoproj/argo-cd/blob/af9ebac0bb35dc16eb034c1cefaf7c92d1029927/controller/appcontroller.go#L2126
```

**Review by agaudreault — APPROVED** [review]
