### PR TITLE
fix(ui): Show error message when max pods to view logs are reached

### LINKED ISSUE #21706: "max pods to view logs are reached" error is silent in the UI
**Describe the bug**

By default, we will not show logs for more than 10 Pods in a single ReplicaSet view.

**To Reproduce**

Create a deployment with 11 replicas. Look at the "Logs" tab in the ReplicaSet detail pane. Notice that it's just a blank page.

**Expected behavior**

I should receive an error message indicating why logs aren't loading.

**Screenshots**

Image

**Version**

2.13.3

**Logs**

```
data: {"error":{"grpc_code":3,"http_code":400,"message":"max pods to view logs are reached. Please provide more granular query","http_status":"Bad Request"}} 
```

### PR DESCRIPTION
**Pull request by pjiang-dev**
Fixes #21706 
Displays an error message in the logs when error message on "max pods to view logs are reached" when there are more than 10 pods for a deployment/replica set for better user experience.

Before:
407818866-f04a7e8a-ba2a-41d9-a84c-d4a8898e8c5a

After:
Screenshot 2025-01-30 at 3 50 39 PM

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: ui/src/app/shared/services/requests.ts [hunk 1]
```diff
@@ -68,7 +68,18 @@ export default {
...
+            const fullUrl = `${apiRoot()}${url}`;
+
+            // If there is an error, show it beforehand
+            fetch(fullUrl).then(response => {
+                if (!response.ok) {
+                    return response.text().then(text => {
+                        observer.error({status: response.status, statusText: response.statusText, body: text});
+                    });
+                }
+            });
```
Comment (crenshaw-dev) [inline ui/src/app/shared/services/requests.ts:80]: Is the preflight request necessary? Wouldn't the `onerror` handler take care of this anyway?

Comment (pjiang-dev) [reply ui/src/app/shared/services/requests.ts:80]: @crenshaw-dev The preflight request is needed because the onerror handler does not handle the HTTP request error (400 Bad Request) and swallows the error message.
Instead EventSource considers it a connection problem and throws the generic error`('connection got closed unexpectedly')`

**Review by ishitasequeira — APPROVED** [review]
The change looks good!! Thanks @pjiang-dev!!
