### PR TITLE
fix: Handle GnuPG verification errors gracefully

### LINKED ISSUE #4828: GnuPG signature verification should fail gracefully on parse errors
# Summary

When parsing unknown or invalid GnuPG signature verification results (i.e. output of `git verify-commit`), the GPG sub-module should fail gracefully instead of throwing an error.

# Motivation

Currently, when there is an error parsing the GnuPG verification result (invalid or unexpected data), Argo CD will throw a user visible error message. The source of the error is not clear on first sight, and probably shouldn't be propagated to the user.

# Proposal

When the GPG module fails to parse a commit verification message, it should set verification result to unknown and set the error message as the reason for the result being unknown. Additionally, a warning message could be printed in the log.

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #4828 

This changes behavior of signature result parsing, in that it will not error on failure but instead sets the verification result to `UNKNOWN`.

Signed-off-by: jannfis <jann@mistrust.net>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -1242,17 +1242,17 @@ func (s *Service) GetRevisionMetadata(ctx context.Context, q *apiclient.RepoServ
 	if gpg.IsGPGEnabled() && q.CheckSignature {
 		cs, err := gitClient.VerifyCommitSignature(q.Revision)
 		if err != nil {
-			log.Debugf("Could not verify commit signature: %v", err)
+			log.Errorf("error verifying signature of commit '%s' in repo '%s': %v", q.Revision, q.Repo.Repo, err)
```
Comment (jannfis) [inline reposerver/repository/repository.go:1245]: This is a hard error from `git verify-commit`, and should still be handled as such. I changed log level, and increased verbosity, because it indicates something is wrong.

**Review by alexmt — APPROVED** [review]
LGTM!
