### PR TITLE
fix: fetch syncedRevision in UpdateRevisionForPaths (#21014)

### LINKED ISSUE #21014: Sync clash by `failed to diff ... git diff ...` when using ManifestGeneratePaths and syncedRevision proceeds targetRevision
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

* ArgoCD sync clashed by follwoing error.
  * commit sha `481fbe3e687c8f339c0ecca000ee7ee7666a7aab` proceeds `85dd68870f5c09225ae05c2b81e9136af7bce397`.

```console
ComparisonError: Failed to load target state: failed to compare revisions for source 1 of 1: rpc error: code = Internal desc = unable to get changed files for repo https://github.com/xxx/xxx.git with revision 85dd68870f5c09225ae05c2b81e9136af7bce397: failed to diff 481fbe3e687c8f339c0ecca000ee7ee7666a7aab..85dd68870f5c09225ae05c2b81e9136af7bce397: git diff --name-only 481fbe3e687c8f339c0ecca000ee7ee7666a7aab..85dd68870f5c09225ae05c2b81e9136af7bce397` failed exit status 128: fatal: Invalid revision range 481fbe3e687c8f339c0ecca000ee7ee7666a7aab..85dd68870f5c09225ae05c2b81e9136af7bce397 (retried 3 times).`
```

* We use manifestGeneratePaths with large monorepo and have multiple repo-server.

**Root cause**

*  As is clear from the error message, the root cause is https://github.com/argoproj/argo-cd/pull/15636 
  * https://github.com/argoproj/argo-cd/blob/27d1e641b6ea99d9f4bf788c032aeaeefd782910/reposerver/repository/repository.go#L2778
  * Indirectly, https://github.com/argoproj/argo-cd/pull/18657 cause this error.
* The issue may occurs following situation:
   * Sync is queued with targetRevision shaA.
   * Someone commits main branch with commit shaB, where changed files are not included in manifestGeneratePaths.
   * `UpdateRevisionForPaths` update cache key with commit shaB and change syncRevision to shaB in one repo-server repo-server.
   * `UpdateRevisionForPaths` compares `git diff shaB..shaA`
   * Local repository does not has commit `sha B` In other repo-servers, so throws the error.
     * Note that `git fetch origin` is skipped in some cases by https://github.com/argoproj/argo-cd/pull/18657

**To Reproduce*

Described in root cause. Note that we need more than two repo-servers to reproduce this issue.

```log
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=info msg="git cat-file -t db63a656360ed3a57c2bcd76f72ef38d793f5733" dir=/tmp/_argocd-repo/74473fb6-60e9-44dd-8fd0-25f9fb516214 execID=dde19
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=info msg=Trace args="[git cat-file -t db63a656360ed3a57c2bcd76f72ef38d793f5733]" dir=/tmp/_argocd-repo/74473fb6-60e9-44dd-8fd0-25f9fb516214 operation_name="exec git" time_ms=1.7880369999999999
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=info msg="git checkout --force db63a656360ed3a57c2bcd76f72ef38d793f5733" dir=/tmp/_argocd-repo/74473fb6-60e9-44dd-8fd0-25f9fb516214 execID=eae87
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=info msg=Trace args="[git checkout --force db63a656360ed3a57c2bcd76f72ef38d793f5733]" dir=/tmp/_argocd-repo/74473fb6-60e9-44dd-8fd0-25f9fb516214 operation_name="exec git" time_ms=2.4994940000000003
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=info msg="git clean -ffdx" dir=/tmp/_argocd-repo/74473fb6-60e9-44dd-8fd0-25f9fb516214 execID=5ae04
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=info msg=Trace args="[git clean -ffdx]" dir=/tmp/_argocd-repo/74473fb6-60e9-44dd-8fd0-25f9fb516214 operation_name="exec git" time_ms=1.080456
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=info msg="git diff --name-only c39784b87ce7df09f2c22651cbcb95536c938deb..db63a656360ed3a57c2bcd76f72ef38d793f5733" dir=/tmp/_argocd-repo/74473fb6-60e9-44dd-8fd0-25f9fb516214 execID=8e750
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=error msg="`git diff --name-only c39784b87ce7df09f2c22651cbcb95536c938deb..db63a656360ed3a57c2bcd76f72ef38d793f5733` failed exit status 128: fatal: Invalid revision range c39784b87ce7df09f2c22651cbcb95536c938deb..db63a656360ed3a57c2bcd76f72ef38d793f5733" execID=8e750
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=info msg=Trace args="[git diff --name-only c39784b87ce7df09f2c22651cbcb95536c938deb..db63a656360ed3a57c2bcd76f72ef38d793f5733]" dir=/tmp/_argocd-repo/74473fb6-60e9-44dd-8fd0-25f9fb516214 operation_name="exec git" time_ms=1.462371
argocd-repo-server-856db549f5-pgh49 repo-server time="2024-12-01T16:20:41Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = unable to get changed files for repo https://github.com/toyamagu-2021/argo-cd-sandbox.git with revision db63a656360ed3a57c2bcd76f72ef38d793f5733: failed to diff c39784b87ce7df09f2c22651cbcb95536c938deb..db63a656360ed3a57c2bcd76f72ef38d793f5733: `git diff --name-only c39784b87ce7df09f2c22651cbcb95536c938deb..db63a656360ed3a57c2bcd76f72ef38d793f5733` failed exit status 128: fatal: Invalid revision range c39784b87ce7df09f2c22651cbcb95536c938deb..db63a656360ed3a57c2bcd76f72ef38d793f5733" grpc.code=Internal grpc.method=UpdateRevisionForPaths grpc.service=repository.RepoServerService grpc.start_time="2024-12-01T16:20:41Z" grpc.time_ms=7.459 span.kind=server system=grpc
```

image

**Expected behavior**

**Screenshots**

**Version**

ArgoCD v2.13.1

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by toyamagu-2021**
Signed-off-by: toyamagu2021 <toyamagu2021@gmail.com>

Closes #21014

Check if syncedRevision exists in a local git repo.
Can be cherry-picked into v2.12 and v2.13.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -2843,6 +2843,19 @@ func (s *Service) UpdateRevisionForPaths(_ context.Context, request *apiclient.U
 	s.metricsServer.IncPendingRepoRequest(repo.Repo)
 	defer s.metricsServer.DecPendingRepoRequest(repo.Repo)
 
+	// Check if the synced revision is present in the repo. If not, checkout the revision
+	// Note that fetching with an explicit version can cause repo bloat [https://github.com/argoproj/argo-cd/issues/8845],
+	// so we should take lock (theoretically not necessary) and checkout.
+	if !gitClient.IsRevisionPresent(syncedRevision) {
+		closer, err := s.repoLock.Lock(gitClient.Root(), syncedRevision, true, func() (goio.Closer, error) {
```
Comment (toyamagu-2021) [inline reposerver/repository/repository.go:2850]: Taking this lock should be considered carefully because of the performance aspect, but this happens in rare situations.

File: reposerver/repository/repository.go [hunk 2]
```diff
@@ -2843,6 +2843,19 @@ func (s *Service) UpdateRevisionForPaths(_ context.Context, request *apiclient.U
...
+			return s.checkoutRevision(gitClient, syncedRevision, false)
+		})
+		if err != nil {
+			return nil, status.Errorf(codes.Internal, "unable to checkout git repo %s with syncedRevision %s: %v", repo.Repo, syncedRevision, err)
+		}
+		io.Close(closer)
+	}
+
```
Comment (andrii-korotkov-verkada) [inline reposerver/repository/repository.go:2858]: Can we somehow dedupe the code with the one below, i.e. pick between revision or syncedRevision, or maybe take lock one time only and check for both of them?

Comment (toyamagu-2021) [reply reposerver/repository/repository.go]: Thanks!
I've created a fetch function for this use case, which does not require a repository lock.

File: reposerver/repository/repository.go [hunk 3]
```diff
@@ -2851,6 +2884,10 @@ func (s *Service) UpdateRevisionForPaths(_ context.Context, request *apiclient.U
 	}
 	defer io.Close(closer)
 
+	if err := s.fetch(gitClient, []string{syncedRevision, revision}); err != nil {
+		return nil, status.Errorf(codes.Internal, "unable to fetch git repo %s with revisions (%s, %s): %v", repo.Repo, syncedRevision, revision, err)
+	}
```
Comment (andrii-korotkov-verkada) [inline reposerver/repository/repository.go:2889]: How would locking above work with both revisions being used here? Can we lock for multiple revisions?

File: reposerver/repository/repository.go [hunk 4]
```diff
@@ -2851,6 +2895,10 @@ func (s *Service) UpdateRevisionForPaths(_ context.Context, request *apiclient.U
 	}
 	defer io.Close(closer)
 
+	if err := s.fetch(gitClient, []string{syncedRevision}); err != nil {
```
Comment (andrii-korotkov-verkada) [inline reposerver/repository/repository.go:2898]: We lock on revision above, but use syncedRevision here. Should it be consistent?

File: reposerver/repository/repository.go (hunk 3 above)
Comment (toyamagu-2021) [reply reposerver/repository/repository.go:2900]: Should we take a lock to fetch from the remote? If we checkout we need to take a lock, but for fetch we don't need to lock.

File: reposerver/repository/repository.go (hunk 4 above)
Comment (toyamagu-2021) [reply reposerver/repository/repository.go:2898]: To exec `git diff syncRevision..targetRevision` we only need to fetch from remote, so I think we needn't take a lock.

Comment (andrii-korotkov-verkada) [reply reposerver/repository/repository.go:2898]: I see. Maybe we can release the lock earlier then.

File: reposerver/repository/repository.go (hunk 3 above)
Comment (andrii-korotkov-verkada) [reply reposerver/repository/repository.go:2900]: I don't know

File: reposerver/repository/repository.go [hunk 5]
```diff
@@ -2507,6 +2507,50 @@ func (s *Service) checkoutRevision(gitClient git.Client, revision string, submod
...
+	err := fetch(gitClient, targetRevisions)
+	if err != nil {
+		for _, revision := range targetRevisions {
+			s.metricsServer.IncGitFetchFail(gitClient.Root(), revision)
+		}
+	}
+	return err
+}
+
+func fetch(gitClient git.Client, targetRevisions []string) error {
```
Comment (nitishfy) [inline reposerver/repository/repository.go:2522]:
```suggestion
func fetchRevision(gitClient git.Client, targetRevisions []string) error {
```
Is there a specific reason behind using the same func name as `fetch`? If not, we can probably change the func name to avoid confusion.

**Review by nitishfy — COMMENTED** [review]
PTAL

File: reposerver/repository/repository.go (hunk 5 above)
Comment (toyamagu-2021) [reply reposerver/repository/repository.go:2522]: I'm not being particular, but it is the same naming convention as `checkoutRevision`.

https://github.com/toyamagu-2021/argo-cd/blob/514df2c77c58c8bc5f4da1000e09af0e8e4fb552/reposerver/repository/repository.go#L2554

**Comment by yash-asana** [comment]
@toyamagu-2021 Are you still working on this PR?

**Review by seffparker — APPROVED** [review]

**Review by andrii-korotkov-verkada — APPROVED** [review]

**Review by gdsoumya — APPROVED** [review]
LGTM
