### PR TITLE
fix: Fail gracefully when unable to unmarshal cluster secret

### LINKED ISSUE #6423: Bad Kubernetes Secret Breaks ArgoCD Deployment
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I added a Secret to ArgoCD when toying with ApplicationSets and it ended up bricking the ArgoCD Deployment.

Hopefully this is enough to reproduce the issue - I ran through it twice with the instructions as is and I could recreate the situation both times.

**To Reproduce**

1. Clone https://github.com/poblahblahblah/argocd-test

2. Set up cluster via kind, create namespaces, install argocd and applicationsets:

```
git checkout 805771a886b20314c93ca87f4bfeabbecd380366

# this command creates a kind cluster, creates the namespaces, then installs argocd
./create_dev_env.sh
```

3. Create initial argocd Application:

```
git checkout bc9f0aa86c3d959b549f51e29ecf1d76c8138d91
kubectl apply -f apps.yaml
```

4. Add bad secret. This creates a "bad" secret which causes the argocd-application-controller and argocd-server to crashloop.

```
git checkout 20ed82c0268e5a2254962101d5ea477fac8a6823
kubectl apply -f apps.yaml
```

5. Try to repair by pointing it to a fixed SHA and manually deleting the secret:

```
git checkout 667cd321328efb021a2bf55461ccde4930c2e07e
kubectl apply -f apps.yaml
kubectl -n argocd delete secret argocd-kind
```

6. Monitor secrets to make sure ArgoCD doesn't keep creating the secret. I had to repeatedly delete the secret since ArgoCD kept recreating it, even when pointing to a known good sha:

```
watch 'kubectl -n argocd get secrets'
```

At this point the UI is down and the CLI can't initiate a login presumably due to the argocd-application-controller-0 pod being in a crashloop.

**Expected behavior**

I would expect that ArgoCD processes and UI would throw an error, but not cause a crashloop.

**Screenshots**

Crashloop:

```
NAME                                                READY   STATUS             RESTARTS   AGE
argocd-application-controller-0                     0/1     CrashLoopBackOff   7          23m
argocd-applicationset-controller-76fc4dc766-56krh   1/1     Running            0          23m
argocd-dex-server-9dc558f5-srq5c                    1/1     Running            0          23m
argocd-redis-759b6bc7f4-7vnnr                       1/1     Running            0          23m
argocd-repo-server-5fbf484547-4nlb2                 1/1     Running            0          23m
argocd-server-6d4678f7f6-5k4d9                      1/1     Running            4          23m
```

**Version**

```shell
~ ❯ argocd version
argocd: v2.0.3+8d2b13d.dirty
  BuildDate: 2021-05-27T19:03:08Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: dirty
  GoVersion: go1.16.4
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

pod crashloop log:
```
time="2021-06-08T00:15:56Z" level=info msg="Processing all cluster shards"
time="2021-06-08T00:15:56Z" level=info msg="appResyncPeriod=3m0s"
time="2021-06-08T00:15:56Z" level=info msg="Application Controller (version: v2.0.2+9a7b0bc, built: 2021-05-20T19:30:25Z) starting (namespace: argocd)"
time="2021-06-08T00:15:56Z" level=info msg="Starting configmap/secret informers"
time="2021-06-08T00:15:56Z" level=info msg="Configmap/secret informer synced"
time="2021-06-08T00:15:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-06-08T00:15:56Z" level=info msg="0xc0008b62a0 subscribed to settings updates"
time="2021-06-08T00:15:56Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-06-08 00:10:46 +0000 UTC, expiry: 3m0s), level (2)" application=my-application
time="2021-06-08T00:15:56Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-06-08 00:10:46 +0000 UTC, expiry: 3m0s), level (2)" application=devops-toolkit
time="2021-06-08T00:15:56Z" level=info msg="Starting clusterSecretInformer informers"
time="2021-06-08T00:15:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-06-08T00:15:56Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: production)" application=my-application
time="2021-06-08T00:15:56Z" level=info msg="Start syncing cluster" server="https://kubernetes.default.svc"
time="2021-06-08T00:15:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-06-08T00:15:56Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: production)" application=devops-toolkit
time="2021-06-08T00:15:56Z" level=info msg="Resuming in-progress operation. phase: Running, message: " application=my-application
time="2021-06-08T00:15:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-06-08T00:15:56Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: production)" application=my-application
W0608 00:15:56.577254       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0608 00:15:56.629921       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
time="2021-06-08T00:15:56Z" level=info msg="getRepoObjs stats" application=my-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=231 unmarshal_ms=6 version_ms=224
time="2021-06-08T00:15:56Z" level=info msg="getRepoObjs stats" application=my-application build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=229 unmarshal_ms=8 version_ms=221
time="2021-06-08T00:15:56Z" level=info msg="Skipping auto-sync: another operation is in progress" application=my-application
time="2021-06-08T00:15:56Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-06-08T00:15:56Z" level=info msg=Syncing application=my-application skipHooks=false started=false syncId=00001-dIpJY
time="2021-06-08T00:15:56Z" level=info msg="Update successful" application=my-application
time="2021-06-08T00:15:56Z" level=info msg="Reconciliation completed" application=my-application dedup_ms=0 dest-name= dest-namespace=production dest-server="https://kubernetes.default.svc" diff_ms=2 fields.level=2 git_ms=231 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=252
time="2021-06-08T00:15:56Z" level=info msg="Applying resource Secret/argocd-kind in cluster: https://192.168.202.1:443, namespace: argocd"
time="2021-06-08T00:15:57Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=my-application
time="2021-06-08T00:15:57Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-06-08T00:15:57Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: production)" application=my-application
E0608 00:15:57.194498       1 runtime.go:78] Observed a panic: &json.SyntaxError{msg:"invalid character '\\'' looking for beginning of object key string", Offset:2} (invalid character '\'' looking for beginning of object key string)
goroutine 188 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2528ee0, 0xc000b92450)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:48 +0x86
panic(0x2528ee0, 0xc000b92450)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/argoproj/argo-cd/v2/util/db.secretToCluster(0xc000294640, 0xc0004a3408)
	/go/src/github.com/argoproj/argo-cd/util/db/cluster.go:321 +0x997
github.com/argoproj/argo-cd/v2/util/db.(*db).WatchClusters.func2(0x28997c0, 0xc000294640)
	/go/src/github.com/argoproj/argo-cd/util/db/cluster.go:155 +0x72
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000d2a760)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00088ff60, 0x2d1afa0, 0xc0004a04e0, 0x251d501, 0xc00013e360)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d2a760, 0x3b9aca00, 0x0, 0x1370801, 0xc00013e360)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004bc280)
	/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0006f2300, 0xc0009e8560)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:71 +0x65
panic: invalid character '\'' looking for beginning of object key string [recovered]
	panic: invalid character '\'' looking for beginning of object key string

goroutine 188 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:55 +0x109
panic(0x2528ee0, 0xc000b92450)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/argoproj/argo-cd/v2/util/db.secretToCluster(0xc000294640, 0xc0004a3408)
	/go/src/github.com/argoproj/argo-cd/util/db/cluster.go:321 +0x997
github.com/argoproj/argo-cd/v2/util/db.(*db).WatchClusters.func2(0x28997c0, 0xc000294640)
	/go/src/github.com/argoproj/argo-cd/util/db/cluster.go:155 +0x72
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000d2a760)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0009bdf60, 0x2d1afa0, 0xc0004a04e0, 0x251d501, 0xc00013e360)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d2a760, 0x3b9aca00, 0x0, 0x1370801, 0xc00013e360)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004bc280)
	/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0006f2300, 0xc0009e8560)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:71 +0x65
```

Bad secret being deleted repeatedly even after apps.yaml was updated to reference a "good" ref:

```
~/src/scratch/argocd-test @667cd321 ❯ kubectl -n argocd delete secret argocd-kind
secret "argocd-kind" deleted

~/src/scratch/argocd-test @667cd321 ❯ sleep 300

~/src/scratch/argocd-test @667cd321 5s ❯ kubectl -n argocd get secrets
NAME                                           TYPE                                  DATA   AGE
argocd-application-controller-token-d9dhk      kubernetes.io/service-account-token   3      26m
argocd-applicationset-controller-token-5fj7r   kubernetes.io/service-account-token   3      26m
argocd-dex-server-token-dgz7z                  kubernetes.io/service-account-token   3      26m
argocd-initial-admin-secret                    Opaque                                1      22m
argocd-kind                                    Opaque                                3      41s
argocd-redis-token-nrctk                       kubernetes.io/service-account-token   3      26m
argocd-secret                                  Opaque                                5      26m
argocd-server-token-26j4l                      kubernetes.io/service-account-token   3      26m
default-token-cqvm5                            kubernetes.io/service-account-token   3      26m

~/src/scratch/argocd-test @667cd321 ❯ kubectl -n argocd delete secret argocd-kind
secret "argocd-kind" deleted

~/src/scratch/argocd-test @667cd321 ❯ sleep 200

~/src/scratch/argocd-test @667cd321 ❯ kubectl -n argocd get secrets
NAME                                           TYPE                                  DATA   AGE
argocd-application-controller-token-d9dhk      kubernetes.io/service-account-token   3      31m
argocd-applicationset-controller-token-5fj7r   kubernetes.io/service-account-token   3      31m
argocd-dex-server-token-dgz7z                  kubernetes.io/service-account-token   3      31m
argocd-initial-admin-secret                    Opaque                                1      26m
argocd-kind                                    Opaque                                3      1s
argocd-redis-token-nrctk                       kubernetes.io/service-account-token   3      31m
argocd-secret                                  Opaque                                5      31m
argocd-server-token-26j4l                      kubernetes.io/service-account-token   3      31m
default-token-cqvm5                            kubernetes.io/service-account-token   3      31m

~/src/scratch/argocd-test @667cd321 ❯ kubectl -n argocd delete secret argocd-kind
secret "argocd-kind" deleted
```

CLI login failure:

```
~ ❯ argocd login localhost:8080 --username admin
WARNING: server is not configured with TLS. Proceed (y/n)? y
Password:
FATA[0203] rpc error: code = Unavailable desc = transport is closing
```

curl failing (rather than a screenshot of Firefox failing):

```
~ ❯ curl https://localhost:8080 -D-
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8080
```

### PR DESCRIPTION
**Pull request by jannfis**
Correctly handle errors when failing to parse cluster secrets instead of emitting a `panic()`

Fixes #6423 

Signed-off-by: jannfis <jann@mistrust.net>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: util/db/cluster.go [hunk 1]
```diff
@@ -87,8 +87,11 @@ func (db *db) ListClusters(ctx context.Context) (*appv1.ClusterList, error) {
 	}
 	hasInClusterCredentials := false
 	for i, clusterSecret := range clusterSecrets {
-		cluster := *secretToCluster(clusterSecret)
-		clusterList.Items[i] = cluster
+		cluster, err := secretToCluster(clusterSecret)
+		if err != nil {
+			log.Errorf("could not unmarshal cluster secret: %v", err)
```
Comment (jannfis) [inline util/db/cluster.go:92]: I'm not quite sure (here as well as below) whether we should pass the value of `err` to the Logger, since it _may_ contain some confidential information?

Is the error content required for users to troubelshoot, or shall we just omit the details?

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
LGTM. Please resolve comment about error before merging
