### PR TITLE
fix: rbac validate command can now take either namespace or policy-file

### LINKED ISSUE #6126: argocd-util settings rbac validate --namespace NAME requires a --policy-file argument
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When reading the docs for the `argo-cd` util, the [docs say](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md)  that you can use the following command:

`argocd-util settings rbac validate --namespace argo # or whatever your argo Namespace name is
`
However, you get an error about a required argument `--policy-file` which should not be the case since I was
expecting it to read the policy from the ConfigMap in the namespace.

**To Reproduce**

Simply execute 

`argocd-util settings rbac validate --namespace argo`

Output will be similar to:

```shell
argocd-util settings rbac validate -n argo

Validates an RBAC policy for being syntactically correct. The policy must be
a local file, and in either CSV or K8s ConfigMap format.

Usage:
  argocd-util settings rbac validate --policy-file=POLICYFILE [flags]

Flags:
  -h, --help                 help for validate
      --policy-file string   path to the policy file to use

Global Flags:
      --argocd-cm-path string          Path to local argocd-cm.yaml file
      --argocd-secret-path string      Path to local argocd-secret.yaml file
      --as string                      Username to impersonate for the operation
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to a kube config. Only required if out-of-cluster
      --load-cluster-settings          Indicates that config map and secret should be loaded from cluster unless local file path is provided
  -n, --namespace string               If present, the namespace scope for this CLI request (default "")
      --password string                Password for basic authentication to the API server
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
      --server string                  The address and port of the Kubernetes API server
      --tls-server-name string         If provided, this name will be used to validate server certificate. If this is not provided, hostname used to contact the server is used.
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use
      --username string                Username for basic authentication to the API server
FATA[0000] Please specify policy to validate using --policy-file 
```

**Expected behavior**

I expected it to read the policy file from the ConfigMap instead of requiring a local one.

**Screenshots**

**Version**

```shell
argocd-version
bash: argocd-version: command not found
TJXL033541:terraform eri05161$ argocd version
argocd: v2.0.1+33eaf11.dirty
  BuildDate: 2021-04-21T18:44:13Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: dirty
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

### PR DESCRIPTION
**Pull request by ashinsabu3**
fixes: #6126
This fix now allows the command to take only a namespace flag if required.
image

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@ashinsabu3 can you write a test to prevent regressions?

**Comment by ashinsabu3** [comment]
> @ashinsabu3 can you write a test to prevent regressions?

I don't quite understand what you mean by this. If you mean a unit test, I'm not exactly sure how I would test the Rbac command functions.

**Comment by crenshaw-dev** [comment]
Yep, unit testing! Cobra has unit testing utilities. I think there are a couple examples using it in our code base. It'll probably require a bit of mocking to get working.

**Comment by ashinsabu3** [comment]
I've added a test to check the command being returned, but couldn't get the test for it's execution working. The more I went into trying to get it working, it felt less like a unit test. I've commented it out for now

**Comment by ashinsabu3** [comment]
The previous CI failures seem to be due to some flake e2e tests, not sure, all passed when run on a weekend night 🙂

File: cmd/argocd/commands/admin/settings_rbac.go [hunk 1]
```diff
@@ -200,26 +202,50 @@ argocd admin settings rbac can someuser create application 'default/app' --defau
...
 // NewRBACValidateCommand returns a new rbac validate command
-func NewRBACValidateCommand() *cobra.Command {
+func NewRBACValidateCommand(clientConfig clientcmd.ClientConfig) *cobra.Command {
 	var (
 		policyFile string
 	)
 
 	var command = &cobra.Command{
-		Use:   "validate --policy-file=POLICYFILE",
+		Use:   "validate --policy-file POLICYFILE [--namespace NAMESPACE]",
```
Comment (ishitasequeira) [inline cmd/argocd/commands/admin/settings_rbac.go:211]: As policy-file is also optional now, put it in square brackets.
```suggestion
		Use:   "validate [--policy-file POLICYFILE] [--namespace NAMESPACE]",
```

File: cmd/argocd/commands/admin/settings_rbac.go [hunk 2]
```diff
@@ -200,26 +202,50 @@ argocd admin settings rbac can someuser create application 'default/app' --defau
...
 		Short: "Validate RBAC policy",
 		Long: `
 Validates an RBAC policy for being syntactically correct. The policy must be
-a local file, and in either CSV or K8s ConfigMap format.
+a local file or a K8s ConfigMap in the provided namespace, and in either CSV or K8s ConfigMap format.
```
Comment (ishitasequeira) [inline cmd/argocd/commands/admin/settings_rbac.go:215]: While we are updating the command, can we add an example as well?

File: cmd/argocd/commands/admin/settings_rbac.go [hunk 3]
```diff
@@ -72,31 +72,34 @@ var validRBACActions map[string]bool = map[string]bool{
...
-	command.AddCommand(NewRBACValidateCommand())
+	clientConfig = cli.AddKubectlFlagsToCmd(command)
+	command.AddCommand(NewRBACCanCommand(clientConfig))
+	command.AddCommand(NewRBACValidateCommand(clientConfig))
 	return command
 }
 
 // NewRBACCanRoleCommand is the command for 'rbac can-role'
-func NewRBACCanCommand() *cobra.Command {
+func NewRBACCanCommand(clientConfig clientcmd.ClientConfig) *cobra.Command {
```
Comment (ishitasequeira) [inline cmd/argocd/commands/admin/settings_rbac.go:92]: Any reason to put the clientConfig as a parameter? If we are taking namespace as an input, do we need to fetch the namespace from clientConfig rather than adding namespace as a variable like `policyFile`?

File: cmd/argocd/commands/admin/settings_rbac.go [hunk 4]
```diff
@@ -228,11 +254,15 @@ a local file, and in either CSV or K8s ConfigMap format.
...
 					os.Exit(1)
 				}
+			} else {
+				log.Fatalf("Policy is empty or could not be loaded.")
 			}
 		},
 	}
 
 	command.Flags().StringVar(&policyFile, "policy-file", "", "path to the policy file to use")
+	command.Flags().StringVar(&policyFile, "namespace", "", "namespace to get argo rbac configmap from")
```
Comment (ishitasequeira) [inline cmd/argocd/commands/admin/settings_rbac.go:264]: the flag `&policyFile` is repeated. This should be `&namespace`?

**Review by ishitasequeira — CHANGES_REQUESTED** [review]

File: cmd/argocd/commands/admin/settings_rbac.go [hunk 5]
```diff
@@ -200,26 +202,50 @@ argocd admin settings rbac can someuser create application 'default/app' --defau
...
-			userPolicy, _, _ := getPolicy(ctx, policyFile, nil, "")
+			realClientset, err := kubernetes.NewForConfig(restConfig)
+			if err != nil {
+				log.Fatalf("could not create k8s client: %v", err)
+			}
+
+			// if policyFile == "" {
+			// 	c.HelpFunc()(c, args)
+			// 	log.Fatalf("Please specify policy to validate using --policy-file")
+			// }
```
[the remark this answers is not in the document]
Comment (ashinsabu3) [reply cmd/argocd/commands/admin/settings_rbac.go:247]: Done

File: cmd/argocd/commands/admin/settings_rbac.go (hunk 1 above)
Comment (ashinsabu3) [reply cmd/argocd/commands/admin/settings_rbac.go:211]: Done

File: cmd/argocd/commands/admin/settings_rbac.go (hunk 2 above)
Comment (ashinsabu3) [reply cmd/argocd/commands/admin/settings_rbac.go:215]: Adding one, let me know if the wording looks fine

File: cmd/argocd/commands/admin/settings_rbac.go (hunk 3 above)
Comment (ashinsabu3) [reply cmd/argocd/commands/admin/settings_rbac.go:92]: I've modified this back, at the time I missed something (most likely the issue you commented below 
`the flag &policyFile is repeated. This should be &namespace?` and while testing the command it repeatedly returned some segmentation fault so I thought it was due to this and putting the clientConfig in params fixed it.

I've changed it back now that I know why my command was failing at the time

File: cmd/argocd/commands/admin/settings_rbac.go (hunk 4 above)
Comment (ashinsabu3) [reply cmd/argocd/commands/admin/settings_rbac.go:264]: Yup missed this thanks. Addressed

**Comment by ashinsabu3** [comment]
@ishitasequeira Addressed comments you had. Do the changes look good?

File: cmd/argocd/commands/admin/settings_rbac.go (hunk 2 above)
Comment (ishitasequeira) [reply cmd/argocd/commands/admin/settings_rbac.go:214]: The wording looks good! Thanks!

**Review by ishitasequeira — APPROVED** [review]
Thanks @ashinsabu3! Changes look good!
