### PR TITLE
fix: controller should load application related nodes from target cluster

### LINKED ISSUE #4232: Ability to manage Node resources with ArgoCD
# Summary

Currently the management of `Node` resources have been disabled by a hardcoded value, shown here in the following;
https://github.com/argoproj/argo-cd/blob/c44074d4d6a6671f6e7be9983fed32f5e1f219e6/util/settings/resources_filter.go#L3-L11

# Motivation

I would like to be able to have ArgoCD manage the labels of the `Node` resources.

# Proposal

Removing `Node` from the following;
https://github.com/argoproj/argo-cd/blob/c44074d4d6a6671f6e7be9983fed32f5e1f219e6/util/settings/resources_filter.go#L9

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

PR implement two changes:

* https://github.com/argoproj/argo-cd/pull/5208/commits/56251db70cc8d8a91661b5633b8ce0c965400102 information about application nodes required for Pod view should be loaded from target app cluster, instead of control plane cluster
* https://github.com/argoproj/argo-cd/pull/5208/commits/bb04f223e32a769cc6e496abe499bf2217193a4f improves node metrics handling:
  * Metrics bars are supposed to show node capacity vs requests, so we don't need Pod limits
  * It is really difficult to convert formatted cpu/memory cap/limit to a number on client side. Instead convert everything to "milli-values" on backend and format on the client:

image

Additionally closes https://github.com/argoproj/argo-cd/issues/4232

### CODE REVIEW

**Comment by alexmt** [comment]
@rbreeze . Heads up in case you started reviewing already. Just pushed an addition commit into the same PR to get accurate node metrics rendering

**Comment by alexmt** [comment]
Tested the changes on several real applications and realized that without information about neighbours pods metrics is not super useful. Converting PR to draft and working on third commit to add neighbor pod metrics.

File: controller/appcontroller.go [hunk 1]
```diff
@@ -381,7 +382,96 @@ func (ctrl *ApplicationController) getResourceTree(a *appv1.Application, managed
...
+				}
+				info := resources[name]
+				info.RequestedByNeighbors += resource.MilliValue()
+				resources[name] = info
+			}
+		}
+
+		var resourcesInfo []appv1.HostResourceInfo
+		for _, info := range resources {
+			if supportedResourceNames[info.ResourceName] && info.Available > 0 {
```
Comment (rbreeze) [inline controller/appcontroller.go:468]: What if `info.Available == 0` because all resources are taken up, rather than because it's invalid? Is it desired behavior to skip resources that are 100% used?

File: controller/cache/cache.go [hunk 2]
```diff
@@ -342,12 +360,31 @@ func (c *liveStateCache) IterateHierarchy(server string, key kube.ResourceKey, a
 	return nil
 }
 
+type NodeWithPods struct {
```
Comment (rbreeze) [inline controller/cache/cache.go:363]: Is this used anywhere?

File: controller/cache/info.go [hunk 3]
```diff
@@ -313,16 +316,23 @@ func populatePodInfo(un *unstructured.Unstructured, res *ResourceInfo) {
...
-	res.Info = append(res.Info, v1alpha1.InfoItem{Name: "Resource.CpuReq", Value: fmt.Sprintf("%d", cpuReq.MilliValue())})
-	res.Info = append(res.Info, v1alpha1.InfoItem{Name: "Resource.CpuLimit", Value: fmt.Sprintf("%d", cpuLimit.MilliValue())})
-	res.Info = append(res.Info, v1alpha1.InfoItem{Name: "Resource.MemoryReq", Value: fmt.Sprintf("%d", memoryReq.Value())})
-	res.Info = append(res.Info, v1alpha1.InfoItem{Name: "Resource.MemoryLimit", Value: fmt.Sprintf("%d", memoryLimit.Value())})
-
 	res.Info = append(res.Info, v1alpha1.InfoItem{Name: "Containers", Value: fmt.Sprintf("%d/%d", readyContainers, totalContainers)})
 	res.NetworkingInfo = &v1alpha1.ResourceNetworkingInfo{Labels: un.GetLabels()}
 }
+
+func populateHostNodeInfo(un *unstructured.Unstructured, res *ResourceInfo) {
```
Comment (rbreeze) [inline controller/cache/info.go:327]: This is much more elegant, I really like this

**Review by rbreeze — COMMENTED** [review]
This looks great, only minor comments. Thanks!

File: controller/appcontroller.go [hunk 4]
```diff
@@ -381,7 +382,96 @@ func (ctrl *ApplicationController) getResourceTree(a *appv1.Application, managed
...
+		v1.ResourceStorage: true,
+		v1.ResourceMemory:  true,
+	}
+	appPods := map[kube.ResourceKey]bool{}
+	for _, node := range appNodes {
+		if node.Group == "" && node.Kind == kube.PodKind {
+			appPods[kube.NewResourceKey(node.Group, node.Kind, node.Namespace, node.Name)] = true
+		}
+	}
+	allNodes := map[string]statecache.NodeInfo{}
```
[the remark this answers is not in the document]
Comment (alexmt) [reply controller/appcontroller.go]: agree - renamed

File: controller/appcontroller.go (hunk 1 above)
Comment (alexmt) [reply controller/appcontroller.go]: I think `Available` is a misleading field name, it should be `Capacity`. If `Capacity` is zero that means we don't have information about that resource and cannot display it. Renamed field to `Capacity`.

File: controller/appcontroller.go [hunk 5]
```diff
@@ -381,7 +382,96 @@ func (ctrl *ApplicationController) getResourceTree(a *appv1.Application, managed
...
+	allPodsByNode := map[string][]statecache.PodInfo{}
+	appPodsByNode := map[string][]statecache.PodInfo{}
+	err = ctrl.stateCache.IterateResources(a.Spec.Destination.Server, func(res *clustercache.Resource, info *statecache.ResourceInfo) {
+		key := res.ResourceKey()
+		switch {
+		case info.NodeInfo != nil && key.Group == "" && key.Kind == "Node":
+			allNodes[key.Name] = *info.NodeInfo
```
[the remark this answers is not in the document]
Comment (alexmt) [reply controller/appcontroller.go]: A node can be only once in cache.

File: controller/cache/cache.go (hunk 2 above)
Comment (alexmt) [reply controller/cache/cache.go]: Good catch - deleted

**Review by rbreeze — APPROVED** [review]
LGTM!
