### PR TITLE
Fix: #6910 ParseDurationFromEnv calls to send a valid max value

### LINKED ISSUE #6910: ParseDurationFromEnv almost always returns default value
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

When trying to use the new `timeout.reconciliation` value in the `argocd-cm`, we realized that the repo-server does not actually use it. Looking at it's logs we saw
```
time="2021-08-04T15:35:25Z" level=warning msg="Value in ARGOCD_RECONCILIATION_TIMEOUT is 10s, which is greater than maximum 2.147483647s allowed"
```
Looking at the code, it seems like the max value of ParseDurationFromEnv is wrongly set to 2.14 seconds.

**To Reproduce**
Add `timeout.reconciliation: 10s` to your `argocd-cm` data, and restart the repo-server.

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

Valid duration values should be allowed for `timeout.reconciliation`. Specifically, a max value of just over 2 seconds seems wrong.

**Screenshots**

**Version**

```shell
argocd: v2.0.5+4c94d88.dirty
  BuildDate: 2021-07-23T05:12:02Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: dirty
  GoVersion: go1.16.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.0-rc1+458416b
  BuildDate: 2021-08-01T13:34:35Z
  GitCommit: 458416bff1963c0ea75274fb2468f7343e20c629
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.1.2 2021-04-15T20:38:06Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0```

**Logs**

```
time="2021-08-04T15:35:25Z" level=warning msg="Value in ARGOCD_RECONCILIATION_TIMEOUT is 10s, which is greater than maximum 2.147483647s allowed"
```

### PR DESCRIPTION
**Pull request by noam-codefresh**
Fixes #6910 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM 

Thanks a lot!

File: cmd/argocd-application-controller/commands/argocd_application_controller.go [hunk 1]
```diff
@@ -144,16 +144,16 @@ func NewCommand() *cobra.Command {
 	}
 
 	clientConfig = cli.AddKubectlFlagsToCmd(&command)
-	command.Flags().Int64Var(&appResyncPeriod, "app-resync", int64(env.ParseDurationFromEnv("ARGOCD_RECONCILIATION_TIMEOUT", defaultAppResyncPeriod*time.Second, 0, math.MaxInt32).Seconds()), "Time period in seconds for application resync.")
```
Comment (alexmt) [inline cmd/argocd-application-controller/commands/argocd_application_controller.go:147]: 🤦
