### PR TITLE
fix(docs): ensure version dropdown sorts correctly regardless of browser language #20289

### LINKED ISSUE #20289: Release Versions are not sorted in the documentation.
# Summary
The current documentation site for Argo CD displays release versions in an unsorted manner.

스크린샷 2024-10-08 오후 10 09 43

# Motivation
Proper sorting will improve user experience by providing a clear structure for accessing different releases.

# Proposal
Update the logic responsible for displaying release versions on the documentation site to ensure they are sorted in ascending numerical order.

### PR DESCRIPTION
**Pull request by jaehanbyun**
Closes #20289 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

## What I have done:
I resolved an issue where 'version' was hardcoded, preventing proper sorting in browsers set to languages other than English.
The screenshot below shows that it now operates correctly in a browser set to German.
image

### CODE REVIEW

File: docs/assets/versions.js [hunk 1]
```diff
@@ -80,11 +80,20 @@ function sortVersionLinks(container) {
...
-      // Found the Versions <dl>
-      const ddElements = Array.from(dl.querySelectorAll('dd'));
+    const ddElements = Array.from(dl.querySelectorAll('dd'));
+
+    // Check if ddElements contain version links
+    const isVersionDl = ddElements.some(dd => {
+      const link = dd.querySelector('a');
+      if (link) {
+        // Check if the link's href matches version pattern
+        return /\/en\/(release-(?:v?\d+[\.\d+]*)|\d+\.\d+\.\d+|latest|stable)\//.test(link.getAttribute('href'));
```
Comment (linghaoSu) [inline docs/assets/versions.js:90]: https://github.com/argoproj/argo-cd/blob/3cb9292dff006289fc3c74f8a5858ab1af51c6d6/docs/assets/versions.js#L23

image

The version regex expression Line 23 excludes versions without the release- prefix, except for 'latest' or 'stable'. However,Here currently including them. Why is this necessary? 🤔

image

**Review by nitishfy — APPROVED** [review]
Overall LGTM. I'd like to present another small request related to this - 

Right now, if I select any version on the docs, the topbar doesn't reflect which version I'm currently at completely. As you can see in the below image, it shows as _Release...._. You can either put those changes in the same PR or raise a new PR for it. 
image

File: docs/assets/versions.js (hunk 1 above)
Comment (jaehanbyun) [reply docs/assets/versions.js]: I have now corrected it. I appreciate your help!

**Comment by jaehanbyun** [comment]
Hello, @nitishfy nitishfy.

I have reviewed what you mentioned. I will address the issue and submit a new PR shortly. Thank you!

File: docs/assets/versions.js [hunk 2]
```diff
@@ -80,11 +80,20 @@ function sortVersionLinks(container) {
...
+    const ddElements = Array.from(dl.querySelectorAll('dd'));
+
+    // Check if ddElements contain version links
+    const isVersionDl = ddElements.some(dd => {
+      const link = dd.querySelector('a');
+      if (link) {
+        // Check if the link's href matches version pattern
+        return /\/en\/(release-(?:v\d+|[\d\.]+|\w+)|latest|stable)\//.test(link.getAttribute('href'));
+      }
+      return false;
```
Comment (linghaoSu) [inline docs/assets/versions.js:92]:
```suggestion
      return /\/en\/(release-(?:v\d+|[\d\.]+|\w+)|latest|stable)\//.test(link?.getAttribute?.('href'));
```
This could be simplified.

 If the version regex expression is the same as above, maybe we should store it in a constant.

Comment (jaehanbyun) [reply docs/assets/versions.js]: I used a constant for the regex as you suggested. Thanks!

**Review by linghaoSu — APPROVED** [review]
LGTM

**Review by todaywasawesome — APPROVED** [review]
LGTM

**Review by nitishfy — APPROVED** [review]

**Review by christianh814 — APPROVED** [review]
