### PR TITLE
fix: Truncated synchronize check-boxes should have tooltips #4233

### LINKED ISSUE #4233: Truncated synchronize check-boxes should have tooltips
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/prometheus-operator
1. click the ellipsis by prometheus-operator project
1. click sync
1. scroll down to ` MONITORING.COREOS.COM/SERVICEMONITOR/PROMETHEUS-OPERATOR/PROMETHEUS-OPERATOR`...
1. You can't see the full name of the item
1. You can't differentiate items at all

**Expected behavior**

* Ellipsis should be in the middle, not the end
* Tooltips for anything with ellipsis

**Screenshots**

top
identical

**Version**

```json
{
    "Version": "v2.1.0+3091bc5",
    "BuildDate": "2021-08-09T10:16:24Z",
    "GitCommit": "3091bc5b6f3d389376feaa999a63fc4986ae72a9",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

### PR DESCRIPTION
**Pull request by ciiay**
Fixes #4233 

Signed-off-by: ciiay <yicai@redhat.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx [hunk 1]
```diff
@@ -172,9 +172,27 @@ export const ApplicationSyncPanel = ({application, selectedResource, hide}: {app
                                                 .filter(item => !item.hook)
                                                 .map((item, i) => {
                                                     const resKey = nodeKey(item);
+                                                    const contentStart = resKey.substr(0, Math.floor(resKey.length / 2));
+                                                    let contentEnd = resKey.substr(-Math.floor(resKey.length / 2));
+                                                    // Fix Latin letters being rendered left to right on ellipsis with direction set to rtl
+                                                    const indexOfFirstLetter = /[a-z]/i.exec(contentEnd).index;
+                                                    contentEnd = contentEnd.slice(indexOfFirstLetter);
```
Comment (jsoref) [inline ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:179]: I'm puzzled by this.
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

Afaict, this regex: `/[-0-9a-zA-Z.]{0,253}/` allows more things than kubernetes does.

Does ArgoCD support translations at all?

Comment (ciiay) [reply ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:179]: Thanks for the review. Could you elaborate what translation did you mean? 

Code in line 178 and line 179 is to avoid contentEnd string which starts with special characters such as `/`, `-` and `.` being placed to the rightmost of contentEnd string when rendered with direction property set to rtl value. For example, if contentEnd is `/abcd/argo-cd/test/example`, without the fix it would be rendered as `...abcd/argo-cd/test/example/`.

Comment (jsoref) [reply ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:179]: I'm mostly interested in line 177.

`RTL` relates to Arabic and Hebrew rendering (namely that logical elements are rendered Right-to-Left). Typically this only happens if you have a "localization" of an application, typically performed by translating the user interface.

For example:
https://www.google.co.il/?hl=he
image

Given that as far as I can tell, it is not possible to view ArgoCD in Arabic or Hebrew, and given that kubernetes resources can't have non ascii (~Latin) characters, a reference to RTL seems out of place.

https://developer.mozilla.org/en-US/docs/Glossary/rtl

Comment (jsoref) [reply ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:179]: Simply put, do you have an example of RTL actually breaking? If so, a picture here would be helpful.

Comment (ciiay) [reply ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:179]: Sure, I added this only because I observed the weird extra `/`, `-` and `.` at the end of the contentEnd string. Here's an example with out the two lines code. Note that the content-end attribute has the value of `/CustomResourceDefinition/...`, and then the `/` got moved to the end of the contentEnd of the rendered resource string. Did some research on this issue and it turned out `/`, `-` and `.` are considered Latin characters which will be put in the rightmost when use direction of right-to-left. So I made the change to make the contentEnd string starts with the first English letter instead the original string.

Screen Shot 2021-08-12 at 10 06 59 AM
Screen Shot 2021-08-12 at 10 07 13 AM

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss [hunk 2]
```diff
@@ -2,11 +2,30 @@
...
+
+        label::before {
+            content: attr(content-start);
+            text-overflow: ellipsis;
+        }
+
+        label::after {
+            content: attr(content-end);
+            text-overflow: clip;
+            direction: rtl;
```
Comment (jsoref) [inline ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss:28]: This `direction: rtl` is doing a lot of work and needs a comment

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx [hunk 3]
```diff
@@ -172,9 +172,27 @@ export const ApplicationSyncPanel = ({application, selectedResource, hide}: {app
                                                 .filter(item => !item.hook)
                                                 .map((item, i) => {
                                                     const resKey = nodeKey(item);
+                                                    const contentStart = resKey.substr(0, Math.floor(resKey.length / 2));
+                                                    let contentEnd = resKey.substr(-Math.floor(resKey.length / 2));
+                                                    // Fix Latin letters being rendered left to right on ellipsis with direction set to rtl
```
Comment (jsoref) [inline ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:177]: @ciiay reached out to me and explained that this is tied to the css change.

A comment in both spots explaining that it's relying on the direction change to place the ellipsis where we want it would help.

And then this comment after it can explain "and because we've direction swapped, we now trip on strong LTR characters, so we need to do a bit of extra work for them".

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss (hunk 2 above)
Comment (ciiay) [inline ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss:28]: Adding a comment here after `direction: rtl;` as `// This is for ellipse in the middle`.

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx (hunk 3 above)
Comment (ciiay) [inline ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:177]: Updating this comment as `// Fix Latin letters being rendered left to right on ellipsis with direction set to rtl as special characters are handled as Latin letters which are naturally left to right`.

Comment (jsoref) [reply ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:177]: I'm not sure I'd write it like this...

I was thinking more like:
```
// We want the ellipsis to be in the middle of our text, so we use RTL layout to put it there.
// Unfortunately, strong LTR characters get jumbled around, so make sure that the last character isn't strong.
```

For reference, `strong` is a technical term:
https://en.wikipedia.org/wiki/Bidirectional_text#Strong_characters

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss [hunk 4]
```diff
@@ -2,11 +2,30 @@
...
+
+        label::before {
+            content: attr(content-start);
+            text-overflow: ellipsis;
+        }
+
+        label::after {
+            content: attr(content-end);
+            text-overflow: clip;
+            direction: rtl; // This is for ellipsis in the middle instead of the end of resource path
```
Comment (jsoref) [inline ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss:28]:
```suggestion
            direction: rtl; // This is to help put the ellipsis in the middle instead of at the end of the resource path
```

**Review by jsoref — APPROVED** [review]

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx [hunk 5]
```diff
@@ -172,9 +172,28 @@ export const ApplicationSyncPanel = ({application, selectedResource, hide}: {app
...
+                                                    const indexOfFirstLetter = /[a-z]/i.exec(contentEnd).index;
+                                                    contentEnd = contentEnd.slice(indexOfFirstLetter);
                                                     return (
                                                         <div key={resKey} className='application-sync-panel__resource'>
-                                                            <CheckboxField id={resKey} field={`resources[${i}]`} /> <label htmlFor={resKey}>{resKey}</label>{' '}
+                                                            <CheckboxField id={resKey} field={`resources[${i}]`} />
+                                                            <Tooltip content={<div style={{wordBreak: 'break-all'}}>{resKey}</div>}>
+                                                                <div className='container'>
+                                                                    <label htmlFor={resKey} style={{display: resKey.length <= 68 ? '' : 'none'}}>
```
Comment (rbreeze) [inline ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:186]: Instead of setting the `display` property of these elements conditionally, I think it would be simpler to do something like: 

```js
isLongLabel = resKey.length > 68;

...

<label htmlFor={resKey} content-start={isLongLabel && contentStart} content-end={isLongLabel && contentEnd} />
```

Also, I'm can't find documentation about the `content-start` or `content-end` properties. Could you explain what they do?

**Review by rbreeze — CHANGES_REQUESTED** [review]

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss [hunk 6]
```diff
@@ -2,11 +2,30 @@
...
+        label::after {
+            vertical-align: middle;
+            display: inline-block;
+            max-width: 50%;
+            overflow: hidden;
+            white-space: pre;
+        }
+
+        label::before {
+            content: attr(content-start);
```
Comment (jsoref) [inline ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss:21]: This is the consumer of `content-start`

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss [hunk 7]
```diff
@@ -2,11 +2,30 @@
...
+            text-overflow: ellipsis;
+        }
+
+        label::after {
+            content: attr(content-end);
```
Comment (jsoref) [inline ui/src/app/applications/components/application-sync-panel/application-sync-panel.scss:26]: This is the consumer of `content-end`

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx (hunk 5 above)
Comment (jsoref) [reply ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:186]: They're custom things which are used by the css.

I'm not sure I'm a huge fan of the names, although I don't offhand have a suggestion for better names.

Comment (ciiay) [reply ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx]: @rbreeze Good point on the inline style. I'm removing it. Please confirm updated PR. Thanks for the review.

**Review by rbreeze — CHANGES_REQUESTED** [review]
Screen Shot 2021-08-19 at 5 48 34 PM

Is there a way to avoid the character in the middle getting cut off? 

Personally I think it seems like a lot of complexity to add for something as small as moving ellipses. I think it's preferable to keep the ellipses to the right (with pure CSS) and simply add a tooltip.

**Comment by ciiay** [comment]
> Screen Shot 2021-08-19 at 5 48 34 PM
> 
> Is there a way to avoid the character in the middle getting cut off?
> 
> Personally I think it seems like a lot of complexity to add for something as small as moving ellipses. I think it's preferable to keep the ellipses to the right (with pure CSS) and simply add a tooltip.

It's either cutting off letters in the middle or 6 dots for the ellipsis. 3 from first part of content, 3 from the second part of the content.

I agree it's adding too much complexity for moving ellipsis. Since we already added tooltip, there's no problem to see the full path of resource. 

@jsoref How do you think?

**Comment by jsoref** [comment]
I like the PR as proposed.

Ellipsis indicate clipped content. It doesn't matter much how that segment is clipped, if someone cares, they'll hover.

But ellipsis of the end results in dozens of identical items and no hint as to which should be hovered. That's the bug that this PR addresses.

There might be a css property to get character oriented clipping instead of pixel oriented…

**Review by rbreeze — CHANGES_REQUESTED** [review]

File: ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx [hunk 8]
```diff
@@ -172,9 +172,22 @@ export const ApplicationSyncPanel = ({application, selectedResource, hide}: {app
...
+                                                    const indexOfFirstLetter = /[a-z]/i.exec(contentEnd).index;
+                                                    contentEnd = contentEnd.slice(indexOfFirstLetter);
+                                                    const isLongLabel = resKey.length > 68;
                                                     return (
                                                         <div key={resKey} className='application-sync-panel__resource'>
-                                                            <CheckboxField id={resKey} field={`resources[${i}]`} /> <label htmlFor={resKey}>{resKey}</label>{' '}
+                                                            <CheckboxField id={resKey} field={`resources[${i}]`} />
+                                                            <Tooltip content={<div style={{wordBreak: 'break-all'}}>{resKey}</div>}>
+                                                                <div className='container'>
+                                                                    {!isLongLabel && <label htmlFor={resKey}>{resKey}</label>}
```
[the remark this answers is not in the document]
Comment (ciiay) [reply ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx:187]: Yeah, ternary operator is better. Thanks for the feedback. Changing to ternary operator.

**Review by rbreeze — APPROVED** [review]
LGTM
