### PR TITLE
fix: Allow multiple hostnames per SSH known hosts entry and also allow IPv6 (#2814)

### LINKED ISSUE #2814: Cannot add https://source.cloud.google.com repo
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.

1. Try to add a Cloud Source Repository https://source.cloud.google.com/
2. It fails

* [x] I've pasted the output of `argocd version`.

```
$ argocd version
argocd: v1.3.2+a5a65cd
  BuildDate: 2019-12-03T21:32:47Z
  GitCommit: a5a65cdfe7c43fd1e3beada202d80c19bc50bd40
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.2+a5a65cd
  BuildDate: 2019-12-03T21:32:18Z
  GitCommit: a5a65cdfe7c43fd1e3beada202d80c19bc50bd40
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Describe the bug**

```
argocd-server-744fb699f7-7qf8j argocd-server time="2019-12-05T14:03:29Z" level=error msg="finished unary call with code Unknown" error="ssh: handshake failed: knownhosts: key is unknown" grpc.code=Unknown grpc.method=ValidateAccess grpc.service=repository.RepositoryService grpc.start_time="2019-12-05T14:03:29Z" grpc.time_ms=241.072 span.kind=server system=grpc
```

**To Reproduce**

1. see above and https://argoproj.slack.com/archives/CASHNF6MS/p1575554219161800

**Expected behavior**

1. Default to including a key from Google Source Repositories

alt

1. Make sure something like this works: `$ argocd repo add ssh://your.name@example.com@source.developers.google.com:2022/p/example/r/my-repo --ssh-private-key-path ./argo-cd.id25519`

alt

1. Make sure something like this works:  `$ argocd repo add ssh://your.name@example.com@source.developers.google.com:2022/p/example/r/my-repo --ssh-private-key-path ./argo-cd.id25519 --insecure-ignore-host-key`

Also, the command line says --insecure-ignore-host-key is deprecated and suggests `--insecure-skip-server-validation` but that flag doesn't exist.

alt

1. Make sure something like this works `$ argocd repo add https://source.developers.google.com:2022/p/example-proj/r/my-repo` after adding the child certificate from `$ openssl s_client -showcerts -servername source.developers.google.com -connect source.developers.google.com:443 </dev/null` in the UI

Also, the editor for known_host_keys is broken in that it doesn't accept the contents of the `~/.ssh/known_hosts_keys` file.

**Screenshots**

Screenshot 2019-12-05 at 14 56 19

**Logs**

```
argocd-server-744fb699f7-7qf8j argocd-server time="2019-12-05T14:03:29Z" level=error msg="finished unary call with code Unknown" error="ssh: handshake failed: knownhosts: key is unknown" grpc.code=Unknown grpc.method=ValidateAccess grpc.service=repository.RepositoryService grpc.start_time="2019-12-05T14:03:29Z" grpc.time_ms=241.072 span.kind=server system=grpc

//

error="Invalid hostname in request: your.name@example.com ...

//

argocd-server-744fb699f7-7qf8j argocd-server time="2019-12-05T14:07:04Z" level=error msg="finished unary call with code Unknown" error="ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain" grpc.code=Unknown grpc.method=ValidateAccess grpc.service=repository.RepositoryService grpc.start_time="2019-12-05T14:07:03Z" grpc.time_ms=499.563 span.kind=server system=grpc

//


```

### PR DESCRIPTION
**Pull request by jannfis**
Allow multiple hostnames separated by comma when parsing SSH known_hosts data and also allow to specify IPv6 addresses as hostname.

Fixes #2814 

Checklist:

* [x] this is a bug fix
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

File: cmd/argocd/commands/cert.go [hunk 1]
```diff
@@ -174,18 +174,20 @@ func NewCertAddSSHCommand(clientOpts *argocdclient.ClientOptions) *cobra.Command
...
-				_, _, err = certutil.KnownHostsLineToPublicKey(knownHostsEntry)
+				hostnameList, _, err := certutil.KnownHostsLineToPublicKey(knownHostsEntry)
 				errors.CheckError(err)
-				certificate := appsv1.RepositoryCertificate{
-					ServerName:  hostname,
-					CertType:    "ssh",
-					CertSubType: certSubType,
-					CertData:    certData,
+				// Each key could be valid for multiple hostnames
+				for _, hostname := range(hostnameList) {
```
Comment (golangcibot) [inline cmd/argocd/commands/cert.go]: File is not `goimports`-ed with -local github.com/argoproj/argo-cd (from `goimports`)
```suggestion
				for _, hostname := range hostnameList {
```

**Review by alexmt — APPROVED** [review]
LGTM!
