### PR TITLE
Issue #2721 - cache parsed repositories, repo credentials to avoid unnecessary yaml parsing

### LINKED ISSUE #2721: High CPU utilisation (5 cores) and spammy logs
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

High CPU utilisation (5 cores) and spamming logs:

```
W1114 12:35:34.096340       1 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
```

**To Reproduce**

N/A

**Expected behavior**

Less resource usage and not so many log entries about the same thing.

**Screenshots**

image

image

**Version**

```shell
argocd: v1.3.0-rc1+8a43840
  BuildDate: 2019-10-16T21:46:40Z
  GitCommit: 8a43840f0baef50946d3eadc1d52d6a2abc162d5
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.0-rc1+8a43840
  BuildDate: 2019-10-16T21:46:08Z
  GitCommit: 8a43840f0baef50946d3eadc1d52d6a2abc162d5
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.1.0
  Helm Version: v2.12.1
  Kubectl Version: v1.14.0
```

**Logs**

N/A

### PR DESCRIPTION
**Pull request by alexmt**
Closes #2721

Once PR is merged the SettingManager is going to cache parsed repositories and repository credentials. In real live Argo CD might has hundreds of  connected repositories and YAML parsing consumes a lot of CPU

### CODE REVIEW

File: util/settings/settings.go [hunk 1]
```diff
@@ -235,6 +237,34 @@ func (mgr *SettingsManager) GetSecretsLister() (v1listers.SecretLister, error) {
...
+			ObjectMeta: metav1.ObjectMeta{
+				Name: common.ArgoCDConfigMapName,
+			},
+		}
+		createCM = true
+	}
+	if argoCDCM.Data == nil {
+		argoCDCM.Data = make(map[string]string)
+	}
+	err = callback(argoCDCM)
```
Comment (golangcibot) [inline util/settings/settings.go]: ineffectual assignment to `err` (from `ineffassign`)

File: controller/cache/cache.go [hunk 2]
```diff
@@ -187,6 +190,13 @@ func (c *liveStateCache) GetManagedLiveObjs(a *appv1.Application, targetObjs []*
 	}
 	return clusterInfo.getManagedLiveObjs(a, targetObjs, c.metricsServer)
 }
+func (c *liveStateCache) GetServerVersion(server string) (string, error) {
+	clusterInfo, err := c.getSyncedCluster(server)
```
Comment (alexec) [inline controller/cache/cache.go]: test please

File: controller/cache/cache.go [hunk 3]
```diff
@@ -27,6 +27,9 @@ type cacheSettings struct {
 }
 
 type LiveStateCache interface {
+	// Returns k8s server version
+	GetServerVersion(server string) (string, error)
```
Comment (alexec) [inline controller/cache/cache.go]: is `server` the URL? or the name?

File: util/settings/settings.go [hunk 4]
```diff
@@ -235,6 +237,38 @@ func (mgr *SettingsManager) GetSecretsLister() (v1listers.SecretLister, error) {
 	return mgr.secrets, nil
 }
 
+func (mgr *SettingsManager) updateConfigMap(callback func(*apiv1.ConfigMap) error) error {
+	argoCDCM, err := mgr.getConfigMap()
+	createCM := false
+	if err != nil {
+		if !apierr.IsNotFound(err) {
```
Comment (alexec) [inline util/settings/settings.go]: test please

File: controller/cache/cache.go (hunk 3 above)
Comment (alexmt) [reply controller/cache/cache.go]: URL. Renamed to serverURL

File: util/settings/settings.go (hunk 4 above)
Comment (alexmt) [reply util/settings/settings.go]: done

File: controller/cache/cache.go (hunk 2 above)
Comment (alexmt) [reply controller/cache/cache.go]: done

**Review by alexec — APPROVED** [review]
LGTM
