### PR TITLE
fix: argocd version --client tries to connect server

### LINKED ISSUE #7986: `argocd version --client` does not work offline in --core mode
When using ArgoCD in --core mode, I had just wanted to see argocd client version, and I did not have a connection to k8s or argocd server. But `argocd version --client` still tries to connect:

When k8s access is unavailable:
```
$ argocd version --client
I1217 11:52:18.998450   63040 trace.go:205] Trace[425192877]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167 (17-Dec-2021 11:51:50.485) (total time: 28513ms):
Trace[425192877]: [28.513512417s] [28.513512417s] END
I1217 11:52:18.999184   63040 trace.go:205] Trace[528268835]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167 (17-Dec-2021 11:51:58.043) (total time: 20955ms):
Trace[528268835]: [20.955849917s] [20.955849917s] END
```

When k8s is available, but argocd is not installed:
```
$ argocd version --client
FATA[0000] configmap "argocd-cm" not found
```

The expectation is that `argocd version --client` should always work in an offline mode.

To reproduce:

```
k3d cluster start
argocd login --core
k3d cluster stop
argocd version --client
```

Affected Version:
```
argocd: v2.2.0+6da92a8
  BuildDate: 2021-12-14T18:11:55Z
  GitCommit: 6da92a8e8103ce4145bb0fe2b7e952be79c9ff0a
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: darwin/amd64
```

### PR DESCRIPTION
**Pull request by gdsoumya**
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>

All commands call the PreRun hook and try to startup the local API server even when it's not required leading to the errors noticed. The proposed solution is to move the local API server creation from the PreRun hook into the `argocdclient.NewClientOrDie` call which will make sure the server is created only when a client needs to access it.

#Fixes #7986

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jessesuen** [comment]
Based on https://github.com/argoproj/argo-cd/issues/7986#issuecomment-997457305, the issue turns out to be a bit deeper. I think we need to improve the CLI in general such that the assumption of a valid kube context is only used when necessary. For example, is it possible to fix this such that `argocd app` doesn't fail with an invalid kube context?

**Comment by jessesuen** [comment]
I feel like the logic for starting `startInProcessAPI` should be moved out of the `PersistentPreRunE` that sets up the CLI commands. @alexmt can you think of a better place to conditionally start this?

**Comment by jessesuen** [comment]
I think I've come to the conclusion the only way to fix this for `argocd app`, `argocd repo`, etc... is to remove the call to `headless.InitCommand` outside of `root.go` and instead move them inside the `app`, `repo`, etc... for each subcommand. Similar to https://github.com/argoproj/argo-cd/blob/8b57bc990cd72c6475e2ae88126a1ed57e2460a3/cmd/argocd/commands/admin/dashboard.go#L28

@alexmt any better ideas?

**Comment by jessesuen** [comment]
Actually, I think the cleaner approach would be to create a wrapper around `argocdclient.NewClientOrDie(clientOpts)` which starts up the throwaway local API server depending on if `clientOpts.Core` is set.

**Comment by gdsoumya** [comment]
For commands like the version --client, it doesn't have any subcommands and probably still needs hardcoded checks in `InitCommand`. 

Also I took a look at how cobra parses the command and for commands with subcommands, it appears that `len(cmd.Commands())>0` (subcommand count) if that command is called without calling a subcommand. On the other hand, if the subcommand is called `cmd` actually points to the subcommand and not the parent command which means that `len(cmd.Command())` points to the no. of commands that are children of the current subcommand. 

With this if we can make an assumption that all top-level commands will only perform actions when a subcommand is called and only display the `HelpFunc()` when called alone (which is the case for all the commands as far as I can see) we could put a check in the PreRun hook:
```
if len(cmd.Commands())>0{
  return nil
  }
```
This would skip the hook execution if a top-level command is called without the subcommands and will display the help data.

**Comment by gdsoumya** [comment]
This is a more generalized solution and will work for any depth of subcommands but if there are subcommands without any more children commands that need to skip this hook that would need to an extra check like the version command.

**Comment by gdsoumya** [comment]
> Actually, I think the cleaner approach would be to create a wrapper around `argocdclient.NewClientOrDie(clientOpts)` which starts up the throwaway local API server depending on if `clientOpts.Core` is set.

This is actually better as it only executes when a call to the server is needed.

**Review by emretanriverdi — APPROVED** [review]

**Comment by gdsoumya** [comment]
@jessesuen have updated the PR according to your suggestion, let me know if this is good.

**Review by jessesuen — COMMENTED** [review]
Could you group the imports such that we have:

* standard libs in one block
* 3rd party libs in 2nd block
* github.com/argoproj/argo-cd in the third block

File: cmd/argocd/commands/initialize/cmd.go [hunk 1]
```diff
@@ -0,0 +1,32 @@
+package initialize
```
Comment (jessesuen) [inline cmd/argocd/commands/initialize/cmd.go:1]: I think InitCommand is only used by admin/dashboard, so it could be a private function there. As for RetrieveContextIfChanged, maybe a better place for it. I think with those two changes the initialize package can be removed entirely?

Comment (gdsoumya) [reply cmd/argocd/commands/initialize/cmd.go:1]: Actually, InitCommand is still used where ever it was previously because it did an extra step apart from just starting the server. It took all the kubeconfig flags and put them into the cmd context. I kept that functionality intact because if the cmd context is accessed in the command for some reason apart from the API server then it will break the code. If the context is not needed anywhere I can shift that part too and make this function private

**Comment by gdsoumya** [comment]
> Could you group the imports such that we have:
> 
> * standard libs in one block
> * 3rd party libs in 2nd block
> * github.com/argoproj/argo-cd in the third block

Have made the fix, it seems that there were some other files too that needed the import order to be fixed  - I have updated those too.

File: cmd/argocd/commands/account.go [hunk 2]
```diff
@@ -72,7 +74,7 @@ has appropriate RBAC permissions to change other accounts.
 				c.HelpFunc()(c, args)
 				os.Exit(1)
 			}
-			acdClient := argocdclient.NewClientOrDie(clientOpts)
+			acdClient := headless.NewClientOrDie(clientOpts, initialize.RetrieveContextIfChanged(c.Flag("context")))
```
Comment (jessesuen) [inline cmd/argocd/commands/account.go:77]: I think we can do this a little bit cleaner. Everywhere we repeat a call to `initialize.RetrieveContextIfChanged` when initializing the client. i.e.:

```golang
headless.NewClientOrDie(clientOpts, initialize.RetrieveContextIfChanged(c.Flag("context")))
```

Can we somehow improve/reduce this to:

```
headless.NewClientOrDie(clientOpts)
```

Can we update the clientOpts to have a `.context` field so we don't have to parse this everywhere?

File: pkg/apiclient/headless/headless.go [hunk 3]
```diff
@@ -0,0 +1,243 @@
...
+	appclientset "github.com/argoproj/argo-cd/v2/pkg/client/clientset/versioned"
+	repoapiclient "github.com/argoproj/argo-cd/v2/reposerver/apiclient"
+	"github.com/argoproj/argo-cd/v2/server"
+	servercache "github.com/argoproj/argo-cd/v2/server/cache"
+	"github.com/argoproj/argo-cd/v2/util/cache"
+	appstatecache "github.com/argoproj/argo-cd/v2/util/cache/appstate"
+	"github.com/argoproj/argo-cd/v2/util/cli"
+	"github.com/argoproj/argo-cd/v2/util/io"
+	kubeutil "github.com/argoproj/argo-cd/v2/util/kube"
+	"github.com/argoproj/argo-cd/v2/util/localconfig"
```
Comment (jessesuen) [inline pkg/apiclient/headless/headless.go:33]: I think we might be bringing in too many dependencies into `pkg/apiclient`, which is meant to be a library/SDK. I think this package still belongs next to CLI code rather than library code.

**Review by jessesuen — CHANGES_REQUESTED** [review]

File: pkg/apiclient/headless/headless.go (hunk 3 above)
Comment (gdsoumya) [reply pkg/apiclient/headless/headless.go:33]: If we are okay with shifting the `NewClientOrDie()` to the CLI (which should be okay because it's only used there) we can move this pkg to the cli part. NewClientOrDie needs to access the headless methods which if kept in the apiClient pkg separate from headless in cli, causes import cycles.

File: cmd/argocd/commands/account.go (hunk 2 above)
Comment (gdsoumya) [reply cmd/argocd/commands/account.go:77]: I was initially thinking of doing that but this specific context is only required when we need to create the local server and the CLientOptions struct is a more general client pkg data that might be used by other API clients and binaries so I felt it might be better to keep it specific to the cli only instead of modifying the original struct. But we can add it in there too.

File: pkg/apiclient/headless/headless.go (hunk 3 above)
Comment (jessesuen) [reply pkg/apiclient/headless/headless.go:33]: > If we are okay with shifting the NewClientOrDie() to the CLI (which should be okay because it's only used there) we can move this pkg to the cli part. 

Spoke with @alexmt and he agrees that we should move this logic into CLI specific package to keep dependencies of pkg/apiclient leaner.

File: cmd/argocd/commands/account.go (hunk 2 above)
Comment (jessesuen) [reply cmd/argocd/commands/account.go:77]: I see your point. But unfortunately, there's already a `clientOpts.Core` which is a useless flag to the generic argocd client package. So for better or worse, we already have CLI specific flag which made its way into in `clientOpts`.

If we want to be slightly cleaner about this, we could preserve the existing API client constructor. e.g.:

```golang
apiclient.NewClientOrDie(clientOpts)
```

And introduce a CLI specific constructor that accepts the `cobra.Command` as a second argument:

```golang
headless.NewClientOrDie(clientOpts, c)
```

The `headless.NewClientOrDie` would call:

```golang
initialize.RetrieveContextIfChanged(c.Flag("context"))
...
apiclient.NewClientOrDie(clientOpts)
```

Then we don't have to introduce more useless options to `clientOpts` which aren't really used by the API client package. And we could even remove the Core option from clientOpts. WDYT?

Comment (gdsoumya) [reply cmd/argocd/commands/account.go:77]: That sounds good to me, also we'll shift the `headless.NewClientOrDie` to the CLI pkg so it will not technically change anything in the apiclient pkg.

File: pkg/apiclient/headless/headless.go (hunk 3 above)
Comment (gdsoumya) [reply pkg/apiclient/headless/headless.go:33]: Will shift it to CLI

Comment (gdsoumya) [reply pkg/apiclient/headless/headless.go]: fixed

File: pkg/apiclient/apiclient.go [hunk 4]
```diff
@@ -457,15 +457,6 @@ func (c *client) redeemRefreshToken() (string, string, error) {
...
 
-// NewClientOrDie creates a new API client from a set of config options, or fails fatally if the new client creation fails.
-func NewClientOrDie(opts *ClientOptions) Client {
-	client, err := NewClient(opts)
-	if err != nil {
-		log.Fatal(err)
-	}
-	return client
-}
-
```
Comment (jessesuen) [inline pkg/apiclient/apiclient.go:468]: I know we don't use this anymore in the CLI, but since it exists in `pkg` i think we may want to keep this for other projects importing argo-cd as a library.

**Review by jessesuen — APPROVED** [review]
This is much cleaner approach. Thank you!

**Review by alexmt — APPROVED** [review]

File: pkg/apiclient/apiclient.go (hunk 4 above)
Comment (gdsoumya) [reply pkg/apiclient/apiclient.go:468]: Yes exactly, that's why I did not remove this incase someone else is already using it.

Comment (jessesuen) [reply pkg/apiclient/apiclient.go:468]: Wait according to this diff. You _did_ remove this.

Comment (gdsoumya) [reply pkg/apiclient/apiclient.go:468]: Oh sorry, I thought I moved the code around in the same pkg. Let me add it back.

Comment (gdsoumya) [reply pkg/apiclient/apiclient.go]: Reverted it back.
