### PR TITLE
fix: app names with non-alphanumeric characters in position 63 break syncs (issue #18237)

### LINKED ISSUE #10110: Invalid label after label+annotation tracking truncation
We have some apps with long names. Thankfully, in label+annotation resource tracking mode, we are able to sync most all of them! We sadly had to rename one app because it was unfortunate enough to end in a hyphen when the label was truncated to 63 chars. 

Would it be possible to strip labels of ending hyphens (and other potential invalid chars) after truncating in label+annotation tracking mode? Thank you!

### LINKED ISSUE #18237: App names with non-alphanumeric characters in position 63 break syncs due to invalid label name
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using `annotation+label` tracking method, app names with more than 63 characters are truncated to 63 characters. If the 63rd character is a hyphen, then the label value is invalid and the sync fails with the following error:

`Failed sync attempt to a3e64b7ba2ba8ddc3d5878bc6aa2e116d29e0a50: one or more objects failed to apply, reason: ConfigMap "test" is invalid: metadata.labels: Invalid value: "the-very-suspicious-name-with-precisely-sixty-three-characters-": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') (retried 1 times).`

I believe the issue is in this code:

https://github.com/argoproj/argo-cd/blob/2b89d6c2220160a55dd71b1f2b57f4744decf210/util/argo/resource_tracking.go#L156-L158

**To Reproduce**
 
1. Set `application.resourceTrackingMethod: annotation+label` in `argocd-cm`
2. Create an application with a name that has a hyphen as its 63rd character, e.g. `the-very-suspicious-name-with-precisely-sixty-three-characters-with-hyphen`, containing any resources
3. Attempt to sync the app

**Expected behavior**

The application syncs normally.

**Screenshots**

image
image

**Version**

```shell
argocd: v2.10.5+335875d
  BuildDate: 2024-03-28T16:12:55Z
  GitCommit: 335875d13e018bed6e03873f4742582582964745
  GitTreeState: clean
  GoVersion: go1.21.8
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.11.0-rc2+24ef777
  BuildDate: 2024-04-15T19:43:50Z
  GitCommit: 24ef7775e79a6ec20b441544aacf8d9d727a676f
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.3+gf03cc04
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

N/A

### PR DESCRIPTION
**Pull request by RobinsonZ**
Fixes #18237. Fixes #10110.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] ~~Does this PR require documentation updates?~~
* [ ] ~~I've updated documentation as required by this PR.~~
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] ~~My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.~~
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] ~~Optional. My organization is added to USERS.md.~~
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by jannfis** [comment]
This seems trying to fix the same issue as https://github.com/argoproj/argo-cd/pull/17560

**Comment by RobinsonZ** [comment]
Seems so. That PR looks stale but I will defer to maintainers as to which version you would like to go with. This is actively biting us, and workarounds are tricky for a variety of reasons, so whatever gets the issue fixed is fine by me.

**Review by todaywasawesome — APPROVED** [review]
I think this looks reasonable but I leave it to @jannfis since he looked at the other PR. 

I prefer this one a bit because it seems simpler.

File: util/argo/resource_tracking.go [hunk 1]
```diff
@@ -155,6 +156,13 @@ func (rt *resourceTracking) SetAppInstance(un *unstructured.Unstructured, key, v
 		}
 		if len(val) > LabelMaxLength {
 			val = val[:LabelMaxLength]
+			// Prevent errors if the truncated name ends in a special character.
+			// See https://github.com/argoproj/argo-cd/issues/18237.
+			okEndPattern := regexp.MustCompile("[a-zA-Z0-9]$")
+
+			for !okEndPattern.MatchString(val) {
```
Comment (jannfis) [inline util/argo/resource_tracking.go:163]: This is paranoia realm, but I think it'd be wise to also check for `len(val) > 1` here, just in case someone will ever be able to pass a `val` that would trigger an out of bound exception.

**Review by jannfis — COMMENTED** [review]
Thanks. I agree @todaywasawesome, the changes here look a bit simpler and accomplishing the same.

@RobinsonZ I do have some comments, please have a look.

**Comment by RobinsonZ** [comment]
@jannfis Updated per your feedback. Let me know if any other changes are needed.

**Review by pasha-codefresh — APPROVED** [review]

**Comment by RobinsonZ** [comment]
Can this be cherry-picked into 2.11?
