### PR TITLE
Issue #1736 - Auto-sync should support self-healing option

### LINKED ISSUE #1736: auto-sync apply only once for one commit
**Describe the bug**
According to Argocd documentation "Argo CD has the ability to automatically sync an application when it detects differences between the desired manifests in Git, and the live state in the cluster" 

However, it does not worked as expected

**To Reproduce**
Deploy test application and configure auto-synced option as documented in the documentation
~/$ ./argocd app get guestbook
Name: guestbook
[...]
Repo: https://github.com/argoproj/argocd-example-apps.git
Path: guestbook
Sync Policy: Automated (Prune)
Sync Status: Synced to HEAD (0ad95c5)

The status is synced, now lets delete the services via kubectl -nNamespaceUsed delete service/guestbook-ui
Argocd correctly reports the outofSync, at this step it is expected that argocd resync automatically, which is not the case even after 30minutes

~$ ./argocd app get guestbook
Name: guestbook
[...]
Repo: https://github.com/argoproj/argocd-example-apps.git
Path: guestbook
Sync Policy: Automated (Prune)
Sync Status: OutOfSync from HEAD (0ad95c5)

**Expected behavior**
Argo should automatically synchronise regarding the autosync policy configuration

**Version**

argocd: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:26:35Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:27:38Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1

**Have you thought about contributing a fix yourself?**
Short term workaround, perform cron argocd app sync AppName

### PR DESCRIPTION
**Pull request by alexmt**
Closes #1736

### CODE REVIEW

File: controller/appcontroller.go [hunk 1]
```diff
@@ -877,28 +886,52 @@ func (ctrl *ApplicationController) autoSync(app *appv1.Application, syncStatus *
...
+				if resources[i].Status != appv1.SyncStatusCodeSynced {
+					op.Sync.Resources = append(op.Sync.Resources, appv1.SyncOperationResource{
+						Kind:  resources[i].Kind,
+						Group: resources[i].Group,
+						Name:  resources[i].Name,
+					})
+				}
+			}
+		} else {
+			logCtx.Infof("Skipping auto-sync: already attempted sync to %s with timeout %v (retrying in %v)", desiredCommitSHA, ctrl.selfHealTimeout, retryAfter)
```
Comment (alexec) [inline controller/appcontroller.go]: minor - should be structured logging

File: test/e2e/app_autosync_test.go [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+		Then().
+		Expect(SyncStatusIs(SyncStatusCodeOutOfSync))
+}
+
+func TestAutoSyncSelfHealEnabled(t *testing.T) {
+	Given(t).
+		Path(guestbookPath).
+		When().
+		// app should be auto-synced once created
+		CreateFromFile(func(app *Application) {
```
Comment (alexec) [inline test/e2e/app_autosync_test.go]: I think we should have a `SyncPolicy` func for this

File: controller/appcontroller.go [hunk 3]
```diff
@@ -877,28 +886,52 @@ func (ctrl *ApplicationController) autoSync(app *appv1.Application, syncStatus *
...
 			logCtx.Warnf("Skipping auto-sync: failed previous sync attempt to %s", desiredCommitSHA)
 			message := fmt.Sprintf("Failed sync attempt to %s: %s", desiredCommitSHA, app.Status.OperationState.Message)
 			return &appv1.ApplicationCondition{Type: appv1.ApplicationConditionSyncError, Message: message}
 		}
 		logCtx.Infof("Skipping auto-sync: most recent sync already to %s", desiredCommitSHA)
 		return nil
-	}
+	} else if alreadyAttempted && selfHeal {
+		if shouldSelfHeal, retryAfter := ctrl.shouldSelfHeal(app); shouldSelfHeal {
+			for i := range resources {
```
Comment (alexec) [inline controller/appcontroller.go]: minor - loop could be `for _, resource := range resources ` and therefore tidier

File: cmd/argocd-application-controller/main.go [hunk 4]
```diff
@@ -106,6 +108,8 @@ func newCommand() *cobra.Command {
 	command.Flags().StringVar(&logLevel, "loglevel", "info", "Set the logging level. One of: debug|info|warn|error")
 	command.Flags().IntVar(&glogLevel, "gloglevel", 0, "Set the glog logging level")
 	command.Flags().IntVar(&metricsPort, "metrics-port", common.DefaultPortArgoCDMetrics, "Start metrics server on given port")
+	command.Flags().IntVar(&selfHealTimeoutSeconds, "self-heal-timeout-seconds", 5, "Specifies timeout between application self heal attempts.")
```
Comment (alexec) [inline cmd/argocd-application-controller/main.go]: minor - remove trailing period

File: docs/user-guide/auto_sync.md [hunk 5]
```diff
@@ -45,7 +46,10 @@ spec:
   Synced or error state will not attempt automated sync.
 * Automated sync will only attempt one synchronization per unique combination of commit SHA1 and
   application parameters. If the most recent successful sync in the history was already performed
-  against the same commit-SHA and parameters, a second sync will not be attempted.
+  against the same commit-SHA and parameters, a second sync will not be attempted, unless `selfHeal` flag is set to true.
+* If `selfHeal` flag is set to true then sync will be attempted again after self heal timeout (5 seconds by default)
```
Comment (alexec) [inline docs/user-guide/auto_sync.md]: Is this the best way to configure this? What about using an `argocd-cm` setting?

File: controller/appcontroller.go [hunk 6]
```diff
@@ -913,20 +946,34 @@ func (ctrl *ApplicationController) autoSync(app *appv1.Application, syncStatus *
 
 // alreadyAttemptedSync returns whether or not the most recent sync was performed against the
 // commitSHA and with the same app source config which are currently set in the app
-func alreadyAttemptedSync(app *appv1.Application, commitSHA string) bool {
+func alreadyAttemptedSync(app *appv1.Application, commitSHA string) (bool, appv1.OperationPhase) {
```
Comment (alexec) [inline controller/appcontroller.go]: why do you need the extra return? this value must be in scope for any caller

File: controller/appcontroller.go [hunk 7]
```diff
@@ -533,6 +536,12 @@ func (ctrl *ApplicationController) processRequestedAppOperation(app *appv1.Appli
 		// if we just completed an operation, force a refresh so that UI will report up-to-date
 		// sync/health information
 		ctrl.requestAppRefresh(app.ObjectMeta.Name, CompareWithLatest)
+		if key, err := cache.MetaNamespaceKeyFunc(app); err == nil {
```
Comment (alexec) [inline controller/appcontroller.go]: what does this do?

**Review by alexec — CHANGES_REQUESTED** [review]

File: controller/appcontroller.go (hunk 1 above)
Comment (alexmt) [reply controller/appcontroller.go]: Do you mean using `WithFields`? We already use WithFields for context (app name field). I think we should not move other values into fields, since it is more difficult to read

```
Skipping auto-sync: already attempted sync. commit="%s", timeout="%v", retryingIn="%v"
```
than

```
Skipping auto-sync: already attempted sync to %s with timeout %v (retrying in %v)
```

File: cmd/argocd-application-controller/main.go (hunk 4 above)
Comment (alexmt) [reply cmd/argocd-application-controller/main.go]: done

File: controller/appcontroller.go (hunk 3 above)
Comment (alexmt) [reply controller/appcontroller.go]: done

File: test/e2e/app_autosync_test.go (hunk 2 above)
Comment (alexmt) [reply test/e2e/app_autosync_test.go]: CLI does not support all required fields yet. So I have to use `argocd create app -f `

File: docs/user-guide/auto_sync.md (hunk 5 above)
Comment (alexmt) [reply docs/user-guide/auto_sync.md]: All controllers timeouts are controlled using flags right now. I'm not 100% sure why exactly we split settings this way. I guess because these are only controller related settings and we don't expect end-user to change it at all, except rare cases.

File: controller/appcontroller.go (hunk 6 above)
Comment (alexmt) [reply controller/appcontroller.go]: I wanted to have `app.Status.OperationState != nil`  as close as possible `app.Status.OperationState.Phase` and don't assume that `app.Status.OperationState` cannot be nil if `alreadyAttemptedSync` returns true

File: controller/appcontroller.go (hunk 7 above)
Comment (alexmt) [reply controller/appcontroller.go]: The `requestAppRefresh` only forces app comparison during reconciliation loop, but does not trigger the reconciliation loop itself. The `if key, err := cache.MetaNamespaceKeyFunc(app); err == nil { ....etc ` triggers reconciliation loop

File: controller/appcontroller.go (hunk 1 above)
Comment (alexec) [reply controller/appcontroller.go]: I don't feel strongly about this

File: docs/user-guide/auto_sync.md (hunk 5 above)
Comment (alexec) [reply docs/user-guide/auto_sync.md]: @jessesuen ?

File: controller/appcontroller.go (hunk 7 above)
Comment (alexec) [reply controller/appcontroller.go]: I think you should comment this behaviour

Comment (alexmt) [reply controller/appcontroller.go]: done

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Comments on testing:

* I successfully created an app, turned on self-heal, deleted the service, and Argo CD re-created the service as expected.
* I could not select self-heal when creating my app. Do we want this as an option?

@alexmt

**Comment by alexmt** [comment]
Self heal check box is shown is auto-sync is enabled:

image
