### PR TITLE
fix: Allow quoted RBAC group names in API

### LINKED ISSUE #8644: LDAP groups cannot be specified in Project roles
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

LDAP groups cannot be specified in Project specific RBAC rules, because they contain comma characters.

The check at https://github.com/argoproj/argo-cd/blob/70e55c86289686329f1dd569fe864860b8d932c5/pkg/apis/application/v1alpha1/types.go#L1623 is too strict, and doesn't consider quoted strings.

**To Reproduce**

```shell
vagrant@argocd-nutshell:~$ argocd proj role create default somerole
Role 'somerole' created
vagrant@argocd-nutshell:~$ argocd proj role add-group default somerole '"CN=foo,OU=bar,O=baz"'
FATA[0000] rpc error: code = InvalidArgument desc = group 'CN=foo,OU=bar,O=baz' contains invalid characters 
```

**Expected behavior**

According to the docs, specifying LDAP groups should be possible by using quotes around the LDAP DN. This works in a declarative setup, but not when using the API.

**Screenshots**

**Version**

```shell
argocd: v2.2.5+8f981cc
  BuildDate: 2022-02-05T01:33:25Z
  GitCommit: 8f981ccfcf942a9eb00bc466649f8499ba0455f5
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.5+8f981cc
  BuildDate: 2022-02-05T01:33:25Z
  GitCommit: 8f981ccfcf942a9eb00bc466649f8499ba0455f5
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0

```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #8644

This change will allow quoted group names containing comma characters, such as LDAP DNs (i.e. `"CN=foo,O=bar,OU=baz"`), to be passed to the API for use in Project specific RBAC roles.

Signed-off-by: jannfis <jann@mistrust.net>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -1618,10 +1618,23 @@ func validateRoleName(name string) error {
...
+	}
+	if isQuoted {
+		// Remove surrounding quotes for further inspection of the group name
+		name = name[1 : len(name)-1]
+	} else {
+		if strings.Contains(name, ",") {
+			return status.Errorf(codes.InvalidArgument, "group '%s' must be quoted", name)
+		}
+	}
+	if name == "" {
```
Comment (crenshaw-dev) [inline pkg/apis/application/v1alpha1/types.go:1637]:
```suggestion
	name = strings.TrimSpace(name)
	if len(name) > 1 && strings.HasPrefix(name, "\"") && strings.HasSuffix(name, "\"") {
		// Remove surrounding quotes for further inspection of the group name
		name = name[1 : len(name)-1]
	} else if strings.Contains(name, ",") {
		return status.Errorf(codes.InvalidArgument, "group '%s' must be quoted", name)
	}

	if name == "" {
```

Added a string length check and simplified a bit.

File: pkg/apis/application/v1alpha1/types_test.go [hunk 2]
```diff
@@ -2596,3 +2596,37 @@ func TestEnvsubst(t *testing.T) {
...
 	assert.Equal(t, "$foo", env.Envsubst("$$foo"))
 }
+
+func Test_validateGroupName(t *testing.T) {
+	tcs := []struct {
+		name      string
+		groupname string
+		isvalid   bool
+	}{
+		{"Normal group name", "foo", true},
```
Comment (crenshaw-dev) [inline pkg/apis/application/v1alpha1/types_test.go:2606]:
```suggestion
		{"Just a double quote", "\"", false},
		{"Just two double quotes", "\"\"", false},
		{"Normal group name", "foo", true},
```

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]

File: pkg/apis/application/v1alpha1/types.go (hunk 1 above)
Comment (jannfis) [reply pkg/apis/application/v1alpha1/types.go:1637]: Thanks. How could I miss the string length check :facepalm:  Also, agree with the simplification.

**Comment by crenshaw-dev** [comment]
Yay, DCO woes on GitHub patches. :-)

**Review by crenshaw-dev — APPROVED** [review]

**Comment by jannfis** [comment]
> Yay, DCO woes on GitHub patches

Rebased and squashed to fix it :)

**Review by alexmt — APPROVED** [review]
