### PR TITLE
fix(appset): ensure finalizer is added when deletionOrder is set as reverse

### LINKED ISSUE #25105: Ensure there is a finalizer on applicationSet when `deletionOrder` is set to `Reverse`
# Summary

Ensure there is a finalizer on applicationSet when `deletionOrder` is set to `Reverse`

# Motivation

By default background deletion is performed, but when deletionOrder  is set to reverse, for controlled deletion applicationset needs to be deleted last. At present `performReverseDeletion` is reached only when the applicationSet has a finalizer added when created, but if users miss to add this finalizer then reverse deletion does not happen as expected. ref - [slack thread](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1761639347717359) 
Ensuring that any ApplicationSet configured for reverse deletion will have the necessary finalizer to enable the controlled deletion sequence when the ApplicationSet is eventually deleted is a better user experience.

# Proposal

Before generators, ensure finalizer exists or add if missing:
```
if isProgressiveSyncDeletionOrderReversed(&applicationSetInfo) {
      if !controllerutil.ContainsFinalizer(&applicationSetInfo, argov1alpha1.ResourcesFinalizerName) {
          controllerutil.AddFinalizer(&applicationSetInfo, argov1alpha1.ResourcesFinalizerName)
          if err := r.Update(ctx, &applicationSetInfo); err != nil {
              return ctrl.Result{}, err
          }
          logCtx.Infof("Added resources finalizer to ApplicationSet %s for reverse deletion", applicationSetInfo.Name)
          // Requeue to continue with updated resource
          return ctrl.Result{RequeueAfter: requeueAfter,}, nil
      }
  }
```

### PR DESCRIPTION
**Pull request by ranakan19**
Closes https://github.com/argoproj/argo-cd/issues/25105

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: applicationset/controllers/applicationset_controller.go [hunk 1]
```diff
@@ -176,6 +176,17 @@ func (r *ApplicationSetReconciler) Reconcile(ctx context.Context, req ctrl.Reque
...
 	}
 
+	// ensure finalizer exists if deletionOrder is set as Reverse
+	if r.EnableProgressiveSyncs && isProgressiveSyncDeletionOrderReversed(&applicationSetInfo) {
+		if !controllerutil.ContainsFinalizer(&applicationSetInfo, argov1alpha1.ResourcesFinalizerName) {
+			controllerutil.AddFinalizer(&applicationSetInfo, argov1alpha1.ResourcesFinalizerName)
+			if err := r.Update(ctx, &applicationSetInfo); err != nil {
+				return ctrl.Result{}, err
+			}
+			return ctrl.Result{}, nil
```
Comment (ranakan19) [inline applicationset/controllers/applicationset_controller.go]: we can likely remove this - updating the annotations would already reconcile Appset again - so explicit reconcile has no real effect.

**Review by nitishfy — COMMENTED** [review]
LGTM! can we also update the docs to mention this?

**Comment by ranakan19** [comment]
@nitishfy done in [f073dfb](https://github.com/argoproj/argo-cd/pull/25125/commits/f073dfb9142b2b0a71346d14dd198b7bf4d34a6f)

File: docs/operator-manual/applicationset/Progressive-Syncs.md [hunk 2]
```diff
@@ -115,7 +115,9 @@ This strategy is particularly useful when you need to tear down dependent servic
 - Requires `rollingSync.steps` to be defined
 - Applications are deleted in reverse order of step sequence
 
-**Important:** The ApplicationSet finalizer is not removed until all applications are successfully deleted. This ensures proper cleanup and prevents the ApplicationSet from being removed before its managed applications.
+**Important:** The ApplicationSet finalizer is not removed until all applications are successfully deleted. This ensures proper cleanup and prevents the ApplicationSet from being removed before its managed applications. 
+
+**Note:** ApplicationSet controller ensures there is a finalizer when deletionOrder is set as Reverse with progressive sync enabled. That is - if the applicationset is missing the required finalizer, the controller adds the finalizer to ApplicationSet before generating applications.
```
Comment (nitishfy) [inline docs/operator-manual/applicationset/Progressive-Syncs.md]:
```suggestion
**Note:** ApplicationSet controller ensures there is a finalizer when `deletionOrder` is set as `Reverse` with progressive sync enabled. This means that if the applicationset is missing the required finalizer, the applicationset controller adds the finalizer to ApplicationSet before generating applications.
```

Comment (ranakan19) [reply docs/operator-manual/applicationset/Progressive-Syncs.md]: done in [ddb6dc9](https://github.com/argoproj/argo-cd/pull/25125/commits/ddb6dc9f93e03c4a4979f597310ddc50e7ca3280)
for some reason, the sign off and commit suggestion was using my other acc and i wanted to avoid any DCO related issues, so added it seprately.

**Review by todaywasawesome — APPROVED** [review]
LGTM

**Review by nitishfy — APPROVED** [review]

**Review by reggie-k — APPROVED** [review]
