### PR TITLE
fix: self-heal should retry syncing an application after specified delay

### LINKED ISSUE #2941: Autosync without pruning seems to cause CPU spikes
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

From what I can observe, when numerous applications with autosync on and pruning off are all in a state where they need to prune, they continously attempt to sync on every reconciliation loop. This causes a huge increase in CPU usage, which can throttle ArgoCD.

**To Reproduce**

This is what seems to have cause the issue for us. I don't quite have time to thoroughly reproduce, but the evidence seems fairly clear.

We have 6 applications that deploy the exact same content, each to a separate cluster. These application use autosync, but do not enable pruning. We updated the source repo to remove a resource, which caused all these applications to enter an "Out Of Sync" state (the resource required pruning). Then, the applications continuously tried to autosync on every reconciliation loop. Our CPU usage for the application-controller container spiked to its limit, and it become very difficult to sync any other application.

**Expected behavior**

If an application uses autosync without pruning and is out of sync, yet the only necessary change is to prune a resource, the application should not attempt to sync.

**Screenshots**

Here is a graph of our CPU usage and throttle during this time period. Once I manually deleted the resources that required pruning, we see the CPU drop back down.
image

**Version**

```shell
time="2020-01-03T19:53:02Z" level=fatal msg="Argo CD server address unspecified"
argocd: v1.3.5+3e150df
  BuildDate: 2019-12-09T21:13:03Z
  GitCommit: 3e150df0ede862c476d2ad0b90717ae00a890551
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

I don't have any relevant logs at this time.

### PR DESCRIPTION
**Pull request by alexmt**
Closes #2941

### CODE REVIEW

File: controller/appcontroller.go [hunk 1]
```diff
@@ -1187,14 +1231,26 @@ func isOperationInProgress(app *appv1.Application) bool {
 	return app.Status.OperationState != nil && !app.Status.OperationState.Phase.Completed()
 }
 
-// toggledAutomatedSync tests if an app went from auto-sync disabled to enabled.
+// automatedSyncEnabled tests if an app went from auto-sync disabled to enabled.
 // if it was toggled to be enabled, the informer handler will force a refresh
-func toggledAutomatedSync(old *appv1.Application, new *appv1.Application) bool {
-	if new.Spec.SyncPolicy == nil || new.Spec.SyncPolicy.Automated == nil {
-		return false
+func automatedSyncEnabled(old *appv1.Application, new *appv1.Application) bool {
```
Comment (jessesuen) [inline controller/appcontroller.go]: Note that `new` is a reserved function name in go, so consider a different variable name

**Review by jessesuen — APPROVED** [review]
LGTM
