### PR TITLE
fix: Regression in signature verification for git tags

### LINKED ISSUE #7377: ArgoCD complains about revision being unsigned when using a tag
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If I run `kubectl apply` using a signed commit and a `targetRevision` of, e.g. main, it deploys fine. But when I use a `targetRevision` pointing to a tag (signed or unsigned), I get a 'Target revision in Git is not signed' error. My repo is https://github.com/jjohnson-ah/jjohnson-argocd-tags.

**To Reproduce**

Generate a GPG key and verify with GitHub. Add the GPG key to ArgoCD and your project in ArgoCD. Create a repo and sign the commit. Deploy and you'll see the deployment is fine. Now create a tag (signed or unsigned) and change `targetRevision` to the tag. The deployment fails.

**Expected behavior**

I expect ArgoCD to be satisfied with the signed tag.

**Screenshots**

Here is the output of pointing to branch main (signed).
Screenshot 2021-10-06 at 13 19 51

Here is the output of pointing to tag ah-tst (signed).
Screenshot 2021-10-06 at 13 22 28

**Version**

```shell
argocd: v2.1.2+7af9dfb.dirty
  BuildDate: 2021-09-02T21:28:55Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: dirty
  GoVersion: go1.17
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.2+7af9dfb
  BuildDate: 2021-09-02T18:05:23Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #7377

There was a regression not covered by tests when we changed passing the resolved commit SHA (instead of the symbolic reference) to verification routines, which resulted in trying to run `git verify-tag` on a commit SHA a tag was pointing to, instead of running against the tag.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -426,7 +427,7 @@ func (s *Service) runRepoOperation(
 		return operation(gitClient.Root(), commitSHA, revision, func() (*operationContext, error) {
```
Comment (crenshaw-dev) [inline reposerver/repository/repository.go:427]: Is the comment just wrong here? It seems to assume revision == resolvedRevision. If it's right, seems like we should either replace revision with resolvedRevision in the function call, or drop the redundant parameter.

Comment (jannfis) [reply reposerver/repository/repository.go:427]: `operation()` itself is a callback that expects the resolved revision, while we use `resolvedRevision` in the anonymous function passed as callback to the `operation` callback.

I was wondering now though, whether that concludes a race condition that could be exploited if we use the unresolved revision for verifying the signature, in case it's the tip of a branch. For example:

* `main` resolves to `<commit_sha_1>`, which is unsigned and potentially malicious
* we pass `<commit_sha_1>` as `revision` to `operation()`
* in the meanwhile, someone pushes a signed commit to the `main` branch, say `<commit_sha_2>`
* signature is validated on tip of `main`, so `<commit_sha_2>` is validated but `<commit_sha_1>` is processed

Need to check that further down the line.

Comment (jannfis) [reply reposerver/repository/repository.go:427]: Ah, now I see what you were saying. Sorry :) Yes, probably `commitSHA` and `revision` now mean the same thing in terms of parameters. Need to check that, too.

Comment (jannfis) [reply reposerver/repository/repository.go:427]: OK. Checked: The repository is locked between checking out the revision for the sync and the verification of the tag.

Regarding the parameter names, I could not reliably reconstruct whether we can drop the revision.

`commitSHA` is the SHA of the tip of `HEAD` of the checked out `revision`. It should always be the same as the resolved revision, right? It's used as the cache key, which apparently was different from the commit SHA at some point in time, and has changed since to become similar to commit SHA (or, the resolved revision).

I think in the case of annotated tags, which have a unique SHA that differs from the commit it points to, `commitSHA` may be different from resolved `revision`. But I've yet to verify.

**Comment by jannfis** [comment]
@crenshaw-dev bump :)

**Review by crenshaw-dev — APPROVED** [review]
