### PR TITLE
Issue #1533 - Prevent reconciliation loop for self-managed apps

### LINKED ISSUE #1533: Manage Argo CD Using Argo CD Reconciliation loop
**Describe the bug**
Apparently i've somehow build a reconciliation loop by managing argocd using argocd.
```
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=189.357799
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:29Z" level=info msg="received unary call /application.ApplicationService/ResourceTree" grpc.method=ResourceTree grpc.request.claims="{\"acr\":\"0\",\"aud\":\"cd.svc.xxx.de\",\"auth_time\":1556267652,\"azp\":\"cd.svc.xxx.de\",\"email\":\"k.siemer@domain.de\",\"exp\":1556276350,\"groups\":[\"/teams/black-ops\",\"/orgs/engineering\",\"/teams/operations\",\"/k8s/cluster/admins\"],\"iat\":1556275450,\"iss\":\"https://id.domain.net/auth/realms/xxx\",\"jti\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"nbf\":0,\"nonce\":\"xxxxxxxxx\",\"session_state\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"sub\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"typ\":\"ID\"}" grpc.request.content="applicationName:\"argo-cd\" " grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:29Z" span.kind=server system=grpc
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:29Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:29Z" grpc.time_ms=6.115 span.kind=server system=grpc
argocd-application-controller-65d85974d-t9kwx argocd-application-controller W0426 10:53:29.569909       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=201.867236
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:29Z" level=info msg="received unary call /application.ApplicationService/ResourceTree" grpc.method=ResourceTree grpc.request.claims="{\"acr\":\"0\",\"aud\":\"cd.svc.xxx.de\",\"auth_time\":1556267652,\"azp\":\"cd.svc.xxx.de\",\"email\":\"k.siemer@domain.de\",\"exp\":1556276350,\"groups\":[\"/teams/black-ops\",\"/orgs/engineering\",\"/teams/operations\",\"/k8s/cluster/admins\"],\"iat\":1556275450,\"iss\":\"https://id.domain.net/auth/realms/xxx\",\"jti\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"nbf\":0,\"nonce\":\"xxxxxxxxx\",\"session_state\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"sub\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"typ\":\"ID\"}" grpc.request.content="applicationName:\"argo-cd\" " grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:29Z" span.kind=server system=grpc
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:29Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:29Z" grpc.time_ms=6.487 span.kind=server system=grpc
argocd-application-controller-65d85974d-t9kwx argocd-application-controller W0426 10:53:29.772895       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=187.965437
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:29Z" level=info msg="received unary call /application.ApplicationService/ResourceTree" grpc.method=ResourceTree grpc.request.claims="{\"acr\":\"0\",\"aud\":\"cd.svc.xxx.de\",\"auth_time\":1556267652,\"azp\":\"cd.svc.xxx.de\",\"email\":\"k.siemer@domain.de\",\"exp\":1556276350,\"groups\":[\"/teams/black-ops\",\"/orgs/engineering\",\"/teams/operations\",\"/k8s/cluster/admins\"],\"iat\":1556275450,\"iss\":\"https://id.domain.net/auth/realms/xxx\",\"jti\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"nbf\":0,\"nonce\":\"xxxxxxxxx\",\"session_state\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"sub\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"typ\":\"ID\"}" grpc.request.content="applicationName:\"argo-cd\" " grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:29Z" span.kind=server system=grpc
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:29Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:29Z" grpc.time_ms=5.521 span.kind=server system=grpc
argocd-application-controller-65d85974d-t9kwx argocd-application-controller W0426 10:53:29.960502       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:29Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=183.817583
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="received unary call /application.ApplicationService/ResourceTree" grpc.method=ResourceTree grpc.request.claims="{\"acr\":\"0\",\"aud\":\"cd.svc.xxx.de\",\"auth_time\":1556267652,\"azp\":\"cd.svc.xxx.de\",\"email\":\"k.siemer@domain.de\",\"exp\":1556276350,\"groups\":[\"/teams/black-ops\",\"/orgs/engineering\",\"/teams/operations\",\"/k8s/cluster/admins\"],\"iat\":1556275450,\"iss\":\"https://id.domain.net/auth/realms/xxx\",\"jti\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"nbf\":0,\"nonce\":\"xxxxxxxxx\",\"session_state\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"sub\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"typ\":\"ID\"}" grpc.request.content="applicationName:\"argo-cd\" " grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" span.kind=server system=grpc
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" grpc.time_ms=26.681 span.kind=server system=grpc
argocd-application-controller-65d85974d-t9kwx argocd-application-controller W0426 10:53:30.153956       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=190.51399899999998
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller W0426 10:53:30.338137       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="received unary call /application.ApplicationService/ResourceTree" grpc.method=ResourceTree grpc.request.claims="{\"acr\":\"0\",\"aud\":\"cd.svc.xxx.de\",\"auth_time\":1556267652,\"azp\":\"cd.svc.xxx.de\",\"email\":\"k.siemer@domain.de\",\"exp\":1556276350,\"groups\":[\"/teams/black-ops\",\"/orgs/engineering\",\"/teams/operations\",\"/k8s/cluster/admins\"],\"iat\":1556275450,\"iss\":\"https://id.domain.net/auth/realms/xxx\",\"jti\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"nbf\":0,\"nonce\":\"xxxxxxxxx\",\"session_state\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"sub\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"typ\":\"ID\"}" grpc.request.content="applicationName:\"argo-cd\" " grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" span.kind=server system=grpc
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" grpc.time_ms=6.126 span.kind=server system=grpc
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=207.910877
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="received unary call /application.ApplicationService/ResourceTree" grpc.method=ResourceTree grpc.request.claims="{\"acr\":\"0\",\"aud\":\"cd.svc.xxx.de\",\"auth_time\":1556267652,\"azp\":\"cd.svc.xxx.de\",\"email\":\"k.siemer@domain.de\",\"exp\":1556276350,\"groups\":[\"/teams/black-ops\",\"/orgs/engineering\",\"/teams/operations\",\"/k8s/cluster/admins\"],\"iat\":1556275450,\"iss\":\"https://id.domain.net/auth/realms/xxx\",\"jti\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"nbf\":0,\"nonce\":\"xxxxxxxxx\",\"session_state\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"sub\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"typ\":\"ID\"}" grpc.request.content="applicationName:\"argo-cd\" " grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" span.kind=server system=grpc
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" grpc.time_ms=5.991 span.kind=server system=grpc
argocd-application-controller-65d85974d-t9kwx argocd-application-controller W0426 10:53:30.547050       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=186.86920700000002
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller W0426 10:53:30.738720       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="received unary call /application.ApplicationService/ResourceTree" grpc.method=ResourceTree grpc.request.claims="{\"acr\":\"0\",\"aud\":\"cd.svc.xxx.de\",\"auth_time\":1556267652,\"azp\":\"cd.svc.xxx.de\",\"email\":\"k.siemer@domain.de\",\"exp\":1556276350,\"groups\":[\"/teams/black-ops\",\"/orgs/engineering\",\"/teams/operations\",\"/k8s/cluster/admins\"],\"iat\":1556275450,\"iss\":\"https://id.domain.net/auth/realms/xxx\",\"jti\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"nbf\":0,\"nonce\":\"xxxxxxxxx\",\"session_state\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"sub\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"typ\":\"ID\"}" grpc.request.content="applicationName:\"argo-cd\" " grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" span.kind=server system=grpc
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" grpc.time_ms=9.8 span.kind=server system=grpc
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=190.88876299999998
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-65d85974d-t9kwx argocd-application-controller W0426 10:53:30.927467       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:53:30Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="received unary call /application.ApplicationService/ResourceTree" grpc.method=ResourceTree grpc.request.claims="{\"acr\":\"0\",\"aud\":\"cd.svc.xxx.de\",\"auth_time\":1556267652,\"azp\":\"cd.svc.xxx.de\",\"email\":\"k.siemer@domain.de\",\"exp\":1556276350,\"groups\":[\"/teams/black-ops\",\"/orgs/engineering\",\"/teams/operations\",\"/k8s/cluster/admins\"],\"iat\":1556275450,\"iss\":\"https://id.domain.net/auth/realms/xxx\",\"jti\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"nbf\":0,\"nonce\":\"xxxxxxxxx\",\"session_state\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"sub\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"typ\":\"ID\"}" grpc.request.content="applicationName:\"argo-cd\" " grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" span.kind=server system=grpc
argocd-server-7dc6666d45-mk8lp argocd-server time="2019-04-26T10:53:30Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2019-04-26T10:53:30Z" grpc.time_ms=7.142 span.kind=server system=grpc
```
As it can be seen here, the controller constantly requests a refresh of the argo-cd application.
Even though it is already healthy and in sync. The auto sync feature isn't even on.

**Screenshots**
argocd

The argo-cd application is owned by the system-cicd appproject.
The argocd-apps application is owned by argocd-objects appproject and used to create applications that are lying  inside git.
The argocd-projects application is also owned by argocd-objects and used to create appprojects that are lying  inside git.

I do not see any reason why it would be in a loop.
Here you can see, that it is trying to reconcile very often:
```
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:45:51Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=186.208233
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:45:51Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=196.083342
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:45:52Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=192.908786
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:45:52Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=192.06886
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:45:52Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=205.887309
argocd-application-controller-65d85974d-t9kwx argocd-application-controller time="2019-04-26T10:45:52Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=196.757855
```
I am also unsure what  `can not retrieve list of objects using index : Index with name namespace does not exist` means.
Since argo-cd works wonderfully on all applications that i've passed to it.

**Versions:**
argo-cd: v1.0.0rc0 
kubernetes: v1.14.1

I am having this problem for a few releases now. I am not sure when it started, but in version `v0.10.3` this was working just fine

### PR DESCRIPTION
**Pull request by alexmt**
Closes #1533

### CODE REVIEW

**Review by alexec — APPROVED** [review]

File: controller/appcontroller.go [hunk 1]
```diff
@@ -112,8 +114,12 @@ func NewApplicationController(
 	projInformer := v1alpha1.NewAppProjectInformer(applicationClientset, namespace, appResyncPeriod, cache.Indexers{})
 	metricsAddr := fmt.Sprintf("0.0.0.0:%d", common.PortArgoCDMetrics)
 	ctrl.metricsServer = metrics.NewMetricsServer(metricsAddr, appLister)
-	stateCache := statecache.NewLiveStateCache(db, appInformer, ctrl.settings, kubectlCmd, ctrl.metricsServer, func(appName string, fullRefresh bool) {
-		ctrl.requestAppRefresh(appName, fullRefresh)
+	stateCache := statecache.NewLiveStateCache(db, appInformer, ctrl.settings, kubectlCmd, ctrl.metricsServer, func(appName string, fullRefresh bool, key kube.ResourceKey) {
```
Comment (alexec) [inline controller/appcontroller.go]: How about a test?

Comment (alexmt) [reply controller/appcontroller.go]: 👍. added

**Comment by KarstenSiemer** [comment]
I am testing this right now and the loop is gone, what remains is that the application for self management now stays in progressing state forever. The applications controller acknowledges that the app is in sync and stopps logging after reconciliation. But in argocd dashboard + metrics the application stays in progressing state

**Comment by alexmt** [comment]
Thank you for catching it @KarstenSiemer !

**Comment by alexmt** [comment]
Seems like this was introduced by https://github.com/argoproj/argo-cd/issues/1433. Created  https://github.com/argoproj/argo-cd/issues/1557 to fix it

**Comment by KarstenSiemer** [comment]
today it started to fall into a reconcillation loop again
```
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=166.93416
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:16.470944       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=115.64300499999999
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:16.588937       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=109.672411
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:16.699362       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=116.590482
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:16.817098       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=113.798542
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:16.931640       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:16Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=127.63157899999999
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:17.059649       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=131.052107
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:17.190738       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=121.30029
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:17.313022       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=113.21549
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:17.427161       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=123.142335
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:17.550362       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Update successful" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Reconciliation completed" application=argo-cd full=true time_ms=117.577545
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Refreshing app status (controller refresh requested)" application=argo-cd
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller W0509 12:49:17.668069       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
argocd-application-controller-8688d7f85-vp8vh argocd-application-controller time="2019-05-09T12:49:17Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: system-cicd)" application=argo-cd
```
the blue memory used line from memory used shows how long i've used the same image (latest)
new-image
reconcilliationloop

today, suddenly at 10 o'clock the reconciliation loop started again. I then killed the pod and a brand new latest image was pulled (green line in memory used) but the reconciliation loop persisted.
There were no changes to my argocd app in this time

**Comment by KarstenSiemer** [comment]
in the application controller logs is nothing suspicious that i can find, on one point it just started reconciling over and over again

**Comment by alexmt** [comment]
Hello @KarstenSiemer , I think fix is not available in any release yet. Which argocd image are you using?

**Comment by KarstenSiemer** [comment]
latest is what i used and after this pr got merged to master it was gone for some time

**Comment by alexec** [comment]
This is targeted for v1.1. I do know if @alexmt plans to backport it to v1.0.

**Comment by alexmt** [comment]
Yes, it is possible that older code  got pushed into `latest` version. Fixes for all self-referenced app related bugs are cherry-picked into v1.0 release branch and available in [v1.0.0-rc3](https://github.com/argoproj/argo-cd/releases/tag/v1.0.0-rc3) release. @KarstenSiemer can you give it a try please?

**Comment by KarstenSiemer** [comment]
also loops with  v1.0.0-rc3

**Comment by alexmt** [comment]
@KarstenSiemer thanks for catching it. Looks like I introduced a bug in https://github.com/argoproj/argo-cd/commit/0b945ef6166847b8e6ddc90fb0f6e26236201e46. Working on fix.

**Comment by KarstenSiemer** [comment]
This is still not working, we tested latest@sha256:64d01e02916b5df5ff74389383827b49c788f9110870af91e9737d5e2f2ac25e
