### PR TITLE
fix: multi-level cross-namespace hierarchy traversal for cluster-scoped intermediates (#26408, #24379)

### LINKED ISSUE #7655: UI: Application resource tree does not show namespace-scope children of cluster-scope resources
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In case the parent resource is a cluster-scope resource, the resource graph **only** shows cluster-wide children (resources that contain the appropriate ownerReference). As per [Kubernetes Doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications) owners can be either same-namespace resources or cluster-scope resources.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

The graph should also show namespace-scope resources that are owned by a cluster-scope resource. 

**Screenshots**

CleanShot 2021-11-08 at 22 03 51@2x

**Version**

rel 2.1.6

```shell
argocd: v2.1.6+a346cf9.dirty
  BuildDate: 2021-11-01T01:01:41Z
  GitCommit: a346cf933e10d872eae26bff8e58c5e7ac40db25
  GitTreeState: dirty
  GoVersion: go1.17.2
  Compiler: gc
```

### LINKED ISSUE #26408: Multi-level cross-namespace hierarchy traversal fails for cluster-scoped intermediates
Checklist:

  - [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
  - [x] I've included steps to reproduce the bug.
  - [x] I've pasted the output of `argocd version`.

  **Describe the bug**

  PR #24847 added support for cross-namespace hierarchy traversal from cluster-scoped parents to namespaced children.  However, there's a bug when the hierarchy has **multiple levels of cluster-scoped resources** before reaching namespaced children.

  The bug affects hierarchies like:
  ClusterScoped (managed) → ClusterScoped (dynamic) → Namespaced

  Real-world example with Crossplane:
 ```
 Provider (managed by ArgoCD)
    └── ProviderRevision (dynamically created by Crossplane)
          └── Deployment (namespaced, in crossplane-system)
                └── ReplicaSet
                      └── Pod
```

  Only the first two levels appear in the resource tree:
  - ✅ Provider (Level 1)
  - ✅ ProviderRevision (Level 2)
  - ❌ Deployment, ReplicaSet, Pod (Level 3+) - **MISSING**

  **Root Cause**

  In `gitops-engine/pkg/cache/cluster.go`, the `processCrossNamespaceChildren` function correctly finds cluster-scoped
   children. However, when a cluster-scoped child (like ProviderRevision) is already visited by
  `processNamespaceHierarchy`, the function skips it entirely without checking for its cross-namespace children.

  The issue is in this logic flow:
  1. `processNamespaceHierarchy` runs first and processes all cluster-scoped resources (namespace=""), marking them as
   visited
  2. `processCrossNamespaceChildren` then runs for the initial managed keys
  3. When it finds ProviderRevision as a child of Provider, `visited[ProviderRevision] != 0` (already visited)
  4. The function skips ProviderRevision entirely, never discovering its namespaced children (Deployment)

  Additionally, `iterateChildrenUsingIndex` skips children with different namespaces, assuming the outer loop will
  handle them - but that only processes initial keys, not recursively discovered cluster-scoped children.

  **To Reproduce**

  1. Create a 3-level hierarchy with cluster-scoped intermediate:
     - ClusterRole A (managed by ArgoCD application)
     - ClusterRole B with ownerReference pointing to A (created dynamically, not in manifest)
     - Role C in a namespace with ownerReference pointing to B

  2. View the ArgoCD application resource tree

  3. Observe that Role C does not appear, even though ClusterRole B correctly shows as a child of ClusterRole A

  Alternative reproduction: Deploy Crossplane with a Provider via ArgoCD. The Provider and ProviderRevision appear in
  the tree, but the provider's Deployment/Pod do not.

  **Expected behavior**

  All resources in the hierarchy should appear in the ArgoCD resource tree with correct parent references:
  - Provider → ProviderRevision → Deployment → ReplicaSet → Pod

  **Screenshots**

  N/A - issue is in backend resource tree API response, not UI rendering.

  **Version**

  ```shell
  argocd: v3.4.0+21acbb8
    BuildDate: 2026-02-11T19:34:54Z
    GitCommit: 21acbb861dcc8cd40f8d53ff285da99c4ee7cf06
    GitTreeState: clean
    GoVersion: go1.25.6
    Compiler: gc
    Platform: linux/arm64

  (Bug exists in any version containing PR #24847, merged in 3.3)

  Logs

  N/A - no error logs produced; resources are silently not traversed.
  ```

### PR DESCRIPTION
**Pull request by jcogilvie**
PR #24847 added support for cross-namespace hierarchy traversal from cluster-scoped parents to namespaced children. However, there's a bug when the hierarchy has multiple levels of cluster-scoped resources before reaching namespaced children.  This PR addresses the issue.

Should be cherry-picked back to 3.3.

Fixes #26408 
 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
~~* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.~~
~~* [ ] Does this PR require documentation updates?~~
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by jcogilvie** [comment]
## Performance Testing Results

(thanks claude)

  ### Environment
  - **Platform:** darwin/arm64 (Apple M2 Max)
  - **Go Version:** 1.24
  - **ArgoCD Version:** v3.4.0+21acbb8.dirty

  ### Cross-Namespace Traversal Benchmarks

  These benchmarks measure `IterateHierarchyV2` performance with varying percentages of cross-namespace children.

  | Scenario | Baseline (PR #24847) | With Fix | Delta |
  |----------|---------------------|----------|-------|
  | 50NS_0pct_100perNS | 5,765 ns/op | 5,770 ns/op | +0.1% |
  | 50NS_2pct_100perNS_10cross | 5,764 ns/op | 5,946 ns/op | +3.2% |
  | 50NS_4pct_100perNS_10cross | 5,977 ns/op | 6,057 ns/op | +1.3% |
  | 50NS_10pct_100perNS_10cross | 6,389 ns/op | 6,316 ns/op | -1.1% |
  | 50NS_20pct_100perNS_10cross | 7,632 ns/op | 7,517 ns/op | -1.5% |
  | 50NS_100pct_100perNS_10cross | 15,541 ns/op | 15,681 ns/op | +0.9% |

  **Conclusion:** No measurable regression - variations are within noise margin (~3%).

  ### Memory Allocation Comparison

  | Scenario | Baseline (PR #24847) | With Fix |
  |----------|---------------------|----------|
  | 50NS_0pct_100perNS | 6,328 B/op, 105 allocs | 6,328 B/op, 105 allocs |
  | 50NS_2pct_100perNS_10cross | 6,328 B/op, 105 allocs | 6,328 B/op, 105 allocs |
  | 50NS_20pct_100perNS_10cross | 7,648 B/op, 108 allocs | 7,648 B/op, 108 allocs |
  | 50NS_100pct_100perNS_10cross | 15,264 B/op, 112 allocs | 15,264 B/op, 112 allocs |

  **Conclusion:** Identical memory allocation patterns - no additional overhead.

  ### Multi-Level Cluster-Scoped Hierarchy Benchmarks

  These benchmarks specifically test the scenario fixed by this change: `ClusterScoped → ClusterScoped → Namespaced`
  (e.g., Crossplane's `Provider → ProviderRevision → Deployment`).

  | Scenario | Resources | Old (Broken) | With Fix | Resources Found |
  |----------|-----------|--------------|----------|-----------------|
  | NoMultiLevel | 1 | 428 ns/op | 425 ns/op | 1/1 ✅ |
  | 1Intermediate_5Grandchildren | 7 | 1,148 ns/op | 1,814 ns/op | **2/7** ❌ → **7/7** ✅ |
  | 5Intermediate_5Grandchildren | 31 | 2,682 ns/op | 9,272 ns/op | **6/31** ❌ → **31/31** ✅ |
  | 10Intermediate_10Grandchildren | 111 | 5,867 ns/op | 26,295 ns/op | **11/111** ❌ → **111/111** ✅ |
  | 20Intermediate_20Grandchildren | 421 | 11,953 ns/op | 94,223 ns/op | **21/421** ❌ → **421/421** ✅ |

  **Key Insight:** The old code was faster because it was **broken** - it only found the root and intermediate
  cluster-scoped resources, completely missing all namespaced grandchildren. The fix correctly traverses the full
  hierarchy.

  ### Memory Allocation (Multi-Level Benchmarks)

  | Scenario | Old (Broken) | With Fix |
  |----------|--------------|----------|
  | NoMultiLevel | 120 B/op, 3 allocs | 120 B/op, 3 allocs |
  | 1Intermediate_5Grandchildren | 1,024 B/op, 7 allocs | 1,088 B/op, 8 allocs |
  | 5Intermediate_5Grandchildren | 1,056 B/op, 11 allocs | 10,312 B/op, 23 allocs |
  | 10Intermediate_10Grandchildren | 3,616 B/op, 25 allocs | 21,376 B/op, 41 allocs |
  | 20Intermediate_20Grandchildren | 8,048 B/op, 39 allocs | 83,824 B/op, 67 allocs |

  Memory usage scales with the number of resources actually being traversed - the old code used less memory because it
   wasn't finding the grandchildren.

  ### Performance Analysis

  For a typical Crossplane Provider with:
  - 1 Provider (managed by ArgoCD)
  - 1 ProviderRevision (dynamically created)
  - 5 child resources (Deployment, ServiceAccount, etc.)

  | Metric | Old (Broken) | With Fix |
  |--------|--------------|----------|
  | Time | 1.15 μs | 1.81 μs |
  | Resources found | 2 of 7 | **7 of 7** |

  The fix adds ~0.66 μs per traversal to correctly find all resources. This is **negligible** compared to:
  - Network latency to Kubernetes API (~1-10 ms)
  - Full resource tree computation (~90-100 ms for 5000 resources)

  ### Summary

  | Metric | Result |
  |--------|--------|
  | Regression in existing benchmarks | ❌ None detected |
  | Memory overhead for existing scenarios | ❌ None |
  | Multi-level hierarchy correctness | ✅ Fixed (was finding 0% of grandchildren) |
  | Multi-level hierarchy performance | ✅ Linear O(n) scaling |
  | Test suite | ✅ All tests pass |

  The performance difference in multi-level scenarios is the cost of **actually finding the resources** that were
  previously invisible. This is expected and acceptable behavior.

File: gitops-engine/pkg/cache/cluster.go [hunk 1]
```diff
@@ -1230,7 +1232,22 @@ func (c *clusterCache) processCrossNamespaceChildren(
 		childKeys := c.parentUIDToChildren[clusterResource.Ref.UID]
 		for _, childKey := range childKeys {
 			child := c.resources[childKey]
-			if child == nil || visited[childKey] != 0 {
+			if child == nil {
+				continue
+			}
+
+			// Check if already visited
+			alreadyVisited := visited[childKey] != 0
```
Comment (agaudreault) [inline gitops-engine/pkg/cache/cluster.go]:
```suggestion
			alreadyVisited := visited[childKey] != 0
```

File: gitops-engine/pkg/cache/cluster_test.go [hunk 2]
```diff
@@ -1912,6 +2004,120 @@ func BenchmarkIterateHierarchyV2_ClusterParentTraversal(b *testing.B) {
 	}
 }
 
+// BenchmarkIterateHierarchyV2_MultiLevelClusterScoped tests the performance of
+// multi-level cluster-scoped hierarchies: ClusterScoped -> ClusterScoped -> Namespaced
+// This is the specific scenario fixed by the bug fix for Crossplane's
+// Provider -> ProviderRevision -> Deployment hierarchy.
```
Comment (agaudreault) [inline gitops-engine/pkg/cache/cluster_test.go]:
```suggestion
```

File: gitops-engine/pkg/cache/cluster_test.go [hunk 3]
```diff
@@ -1350,6 +1350,98 @@ func TestIterateHierarchyV2_ClusterScopedParent_FindsAllChildren(t *testing.T) {
 	assert.ElementsMatch(t, expected, keys)
 }
 
+func TestIterateHierarchyV2_MultiLevelClusterScoped_FindsNamespacedGrandchildren(t *testing.T) {
+	// Test 3-level hierarchy: ClusterScoped -> ClusterScoped -> Namespaced
+	// This reproduces the Crossplane bug where:
```
Comment (agaudreault) [inline gitops-engine/pkg/cache/cluster_test.go]:
```suggestion
	// This test the scenario where:
```

**Review by agaudreault — APPROVED** [review]
LGTM
