### PR TITLE
fix: multi-source app breaks application parameters UI (#16910)

### LINKED ISSUE #16910: multi-source apps break application parameters UI
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm using the [beta feature](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/) multi sources for an app with a CMP plugin. It's working all fine, my plugin take a config source with values and app source with helm charts. 

```
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: app
syncPolicy:
  automated:
    prune: true
    selfHeal: true
sources:
  - repoURL: 'ssh://gitolite@forge.com/my-config.git'
    path: ./addons/cert-manager
    targetRevision: cluster115
    plugin:
      name: plugin-v1.0.0
  - repoURL: 'ssh://gitolite@forge.com/dome-apps.git'
    path: ./security/cert-manager
    targetRevision:  cluster115
    plugin:
      name: plugin-v1.0.0
      env:
        - name: OVERLAY
          value: internal
        - name: HELM_RELEASE_NAME
          value: certm
        - name: APP_VERSION
          value: latest
```

However, in the UI, If I try to reach the parameters from an app, I got an error:
https://apps.cluster115.sts.lan/applications/app/cert-manager?view=tree&node=argoproj.io%2FApplication%2Fapp%2Fcert-manager%2F0&tab=parameters&resource=

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).

Stacktrace:

Mh@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:1725680
Za@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:808354
Es@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:854400
Sl@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:847162
xl@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:847085
hl@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:844108
82002/Xo/<@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:795769
90362/t.unstable_runWithPriority@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:870971
qo@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:795478
Xo@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:795716
Jo@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:795649
cl@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:840878
enqueueSetState@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:799432
17952/y.prototype.setState@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:1024313
t@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:1566791
o@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:1566912
```

**Screenshots**

argo_bug

**Version**

```shell
argocd version --grpc-web
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:24:09Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.4+c279299
  BuildDate: 2023-09-13T19:12:09Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
  ```
  
  **Logs**

logs with `server.log.level: "debug"` when I click:

```
time="2024-01-18T15:14:39Z" level=info msg="received unary call /repository.RepositoryService/GetAppDetails" grpc.method=GetAppDetails grpc.request.claims="{\"acr\":\"0\",\"at_hash\":\"N_pM01J5F0Kd5Bc4abPQBg\",\"aud\":\"argo-cd\",\"auth_time\":1705572021,\"azp\":\"argo-cd\",\"email\":\"admin@replaced_name.exemple.bar.eu\",\"email_verified\":true,\"exp\":1705591173,\"family_name\":\"Administrator\",\"given_name\":\"replaced_name\",\"groups\":[\"/admin\"],\"iat\":1705590873,\"iss\":\"https://auth.cluster115.sts.lan/realms/replaced_name\",\"jti\":\"a7d5dab4-aff8-4f19-bf3c-b8e0faeddc20\",\"name\":\"replaced_name Administrator\",\"preferred_username\":\"replaced_name_admin\",\"realm_access\":{\"roles\":[\"view-dashboards\",\"edit-dashboards\",\"edit-subscribers\",\"view-subscribers\",\"admin\",\"manage-dashboards\",\"manage-apps\",\"view-alerts\",\"view-metrics\",\"view-apps\",\"view-logs\"]},\"session_state\":\"389cce28-3a15-4f2c-be94-c3a317ec7be2\",\"sid\":\"389cce28-3a15-4f2c-be94-c3a317ec7be2\",\"sub\":\"f08abe40-829c-412e-8d3a-15283a3b8ddb\",\"typ\":\"ID\"}" grpc.request.content="source:<repoURL:\"ssh://gitolite@forge.b-com.com/dop-css/nnerambour/my-replaced_name-config.git\" path:\"./replaced_name-addons/cert-manager\" targetRevision:\"cluster115\" plugin:<name:\"replaced_name-plugin-v1.0.0\" > chart:\"\" ref:\"\" > appName:\"cert-manager\" appProject:\"default\" " grpc.service=repository.RepositoryService grpc.start_time="2024-01-18T15:14:39Z" span.kind=server system=grpc
time="2024-01-18T15:14:39Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetAppDetails grpc.service=repository.RepositoryService grpc.start_time="2024-01-18T15:14:39Z" grpc.time_ms=4.833 span.kind=server system=grpc
time="2024-01-18T15:14:39Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2024-01-18T15:14:33Z" grpc.time_ms=5581.443 span.kind=server system=grpc
time="2024-01-18T15:14:39Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2024-01-18T15:14:33Z" grpc.time_ms=5485.515 span.kind=server system=grpc
```

### PR DESCRIPTION
**Pull request by keithchong**
Fixes https://github.com/argoproj/argo-cd/issues/16910

As part of the original multi-source feature implementation, the Parameters tab shows the parameters related to the _first_ source. If you reverse the order of the two sources (from the bug issue) in the manifest yaml, then it doesn't blow up. It only happens with the sock-shop example. 

So with this fix, the parameters page will show the same contents as if the sock-shop example was created as a single source application. (It's a plugin still)

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: ui/src/app/applications/components/application-parameters/application-parameters.tsx [hunk 1]
```diff
@@ -299,7 +299,7 @@ export const ApplicationParameters = (props: {
             title: 'ENV',
             view: (
                 <div style={{marginTop: 15}}>
-                    {app.spec.source.plugin &&
+                    {app.spec.source?.plugin &&
                         (app.spec.source.plugin.env || []).map(val => (
```
Comment (blakepettersson) [inline ui/src/app/applications/components/application-parameters/application-parameters.tsx:303]: I think this can be shortened

```suggestion
                    {app.spec.source?.plugin?.env || []).map(val => (
```

File: ui/src/app/applications/components/application-parameters/application-parameters.tsx [hunk 2]
```diff
@@ -286,7 +286,7 @@ export const ApplicationParameters = (props: {
     } else if (props.details.type === 'Plugin') {
         attributes.push({
             title: 'NAME',
-            view: <div style={{marginTop: 15, marginBottom: 5}}>{ValueEditor(app.spec.source.plugin && app.spec.source.plugin.name, null)}</div>,
+            view: <div style={{marginTop: 15, marginBottom: 5}}>{ValueEditor(app.spec.source?.plugin && app.spec.source.plugin.name, null)}</div>,
```
Comment (blakepettersson) [inline ui/src/app/applications/components/application-parameters/application-parameters.tsx:289]: I think this can be shortened as well 

```suggestion
            view: <div style={{marginTop: 15, marginBottom: 5}}>{ValueEditor(app.spec.source?.plugin?.name, null)}</div>,
```

Comment (keithchong) [reply ui/src/app/applications/components/application-parameters/application-parameters.tsx:289]: Indeed. Simplified.

File: ui/src/app/applications/components/application-parameters/application-parameters.tsx (hunk 1 above)
Comment (keithchong) [reply ui/src/app/applications/components/application-parameters/application-parameters.tsx:303]: Indeed. Simplified.

**Comment by keithchong** [comment]
Thanks for the review @blakepettersson . I've made the changes.

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Review by blakepettersson — APPROVED** [review]
