### PR TITLE
fix: add api-server liveness probe that catches bad data in informer

### LINKED ISSUE #4960: POST /api/v1/application fails during cluster validation
# Summary

The API failed load cluster information and app creation failed with the following error

```
argocd-server-968d48d9f-qj6v8 argocd-server time="2020-12-03T06:38:18Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to get cluster: object does not implement the Object interfaces" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2020-12-03T06:38:16Z" grpc.time_ms=2619.464 span.kind=server system=grpc
```

### PR DESCRIPTION
**Pull request by alexmt**
Closes https://github.com/argoproj/argo-cd/issues/4960

Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -241,6 +241,21 @@ func NewServer(ctx context.Context, opts ArgoCDServerOpts) *ArgoCDServer {
 	}
 }
 
+const (
+	notObjectErrMsg = "object does not implement the Object interfaces"
```
Comment (jessesuen) [inline server/server.go:245]: Can you link to the issue for context, for the next person who is trying to figure out why this exists?

**Review by jessesuen — APPROVED** [review]

File: server/server.go (hunk 1 above)
Comment (alexmt) [reply server/server.go:246]: sure, good idea!

File: controller/metrics/metrics_test.go [hunk 2]
```diff
@@ -112,7 +112,7 @@ status:
     status: Healthy
 `
 
-var noOpHealthCheck = func() error {
+var noOpHealthCheck = func(r *http.Request) error {
```
Comment (mayzhang2000) [inline controller/metrics/metrics_test.go:115]: This input parameter `r *http.Request` is not used in this function. Any reason it needs to be defined?
