### PR TITLE
Issue #2620 - Cluster list page fails if any cluster is not reachable

### LINKED ISSUE #2620: Cluster list page fails if any cluster is not reachable
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Cluster list page fails if any cluster is not reachable

**To Reproduce**

1. Configure invalid cluster credentials.
2. Navigate to the clusters list page
3. See page fails to load list of clusters

**Expected behavior**

Page should be loaded.

### PR DESCRIPTION
**Pull request by alexmt**
Closes #2620

### CODE REVIEW

File: server/cluster/cluster.go [hunk 1]
```diff
@@ -41,25 +40,24 @@ func NewServer(db db.ArgoDB, enf *rbac.Enforcer, cache *servercache.Cache, kubec
...
+		},
 	}
 
-	config := cluster.RESTConfig()
-	config.Timeout = time.Second
-	kubeClientset, err := kubernetes.NewForConfig(config)
-	if err == nil {
-		_, err = kubeClientset.Discovery().ServerVersion()
-	}
+	version, err := s.kubectl.GetServerVersion(cluster.RESTConfig())
```
Comment (alexec) [inline server/cluster/cluster.go]: why this?

Comment (alexmt) [reply server/cluster/cluster.go]: I had to move it from https://github.com/argoproj/argo-cd/pull/2621/files#diff-02ca8f1595ce93b75591586acd227047L105 to avoid failing whole request if one cluster has incorrect credentials.

If we are able to get the cluster server version when it ensures that cluster is reachable and `kubeClientset.Discovery().ServerVersion()` no longer required.

Comment (alexec) [reply server/cluster/cluster.go]: Thank explains why I don't understand .I don't think we should mix up connection state with server version, they are different things and should not be stored together like this.

Comment (alexmt) [reply server/cluster/cluster.go]: The caching was introduced because a single unreachable cluster makes `/cluster` API very slow. To avoid it we cache the most recent verification result. Also the verification is result of running `GetServerVersion`, so I think it is pretty much the same thing.

File: server/cache/cache.go [hunk 2]
```diff
@@ -31,6 +31,11 @@ type OIDCState struct {
 	ReturnURL string `json:"returnURL"`
 }
 
+type ClusterConnectionState struct {
```
Comment (alexec) [inline server/cache/cache.go]: how about renaming this to `ClusterInfo`?

File: server/cache/cache.go [hunk 3]
```diff
@@ -62,8 +67,8 @@ func clusterConnectionStateKey(server string) string {
 	return fmt.Sprintf("cluster|%s|connection-state", server)
 }
 
-func (c *Cache) GetClusterConnectionState(server string) (appv1.ConnectionState, error) {
```
Comment (alexec) [inline server/cache/cache.go]: change to get `GetClusterInfo`

File: server/cache/cache.go [hunk 4]
```diff
@@ -82,7 +87,7 @@ func (c *Cache) GetRepoConnectionState(repo string) (appv1.ConnectionState, erro
 	return res, err
 }
 
-func (c *Cache) SetClusterConnectionState(server string, state *appv1.ConnectionState) error {
+func (c *Cache) SetClusterConnectionState(server string, state *ClusterConnectionState) error {
```
Comment (alexec) [inline server/cache/cache.go]: change to get `SetClusterInfo`

File: server/cache/cache.go (hunk 2 above)
Comment (alexmt) [reply server/cache/cache.go]: sure, done

File: server/cache/cache.go (hunk 3 above)
Comment (alexmt) [reply server/cache/cache.go]: done

File: server/cache/cache.go (hunk 4 above)
Comment (alexmt) [reply server/cache/cache.go]: done

File: server/cluster/cluster.go [hunk 5]
```diff
@@ -41,37 +41,38 @@ func NewServer(db db.ArgoDB, enf *rbac.Enforcer, cache *servercache.Cache, kubec
 	}
 }
 
-func (s *Server) getConnectionState(cluster appv1.Cluster, errorMessage string) appv1.ConnectionState {
-	if connectionState, err := s.cache.GetClusterConnectionState(cluster.Server); err == nil {
-		return connectionState
+func (s *Server) getConnectionState(cluster appv1.Cluster, errorMessage string) (appv1.ConnectionState, string) {
+	if connectionState, err := s.cache.GetClusterInfo(cluster.Server); err == nil {
```
Comment (alexec) [inline server/cluster/cluster.go]: rename 'connectionState' to 'info`

File: server/cluster/cluster.go [hunk 6]
```diff
@@ -100,11 +101,9 @@ func (s *Server) List(ctx context.Context, q *cluster.ClusterQuery) (*appv1.Clus
 			warningMessage = fmt.Sprintf("There are %d credentials configured this cluster.", len(clusters))
 		}
 		if clust.ConnectionState.Status == "" {
-			clust.ConnectionState = s.getConnectionState(clust, warningMessage)
-		}
-		clust.ServerVersion, err = s.kubectl.GetServerVersion(clust.RESTConfig())
-		if err != nil {
-			return err
+			state, serverVersion := s.getConnectionState(clust, warningMessage)
+			clust.ConnectionState = state
```
Comment (alexec) [inline server/cluster/cluster.go]: rename `clus` to `clusterInfo`

**Review by alexec — APPROVED** [review]
Conditional approval - please rename variables.

**Comment by alexmt** [comment]
Thanks for noticing it, renamed.
