### PR TITLE
fix: register pprof endpoints in repo-server using the params config map

### LINKED ISSUE #25988: Add pprof support for argocd-repo-server
# Summary

Today only the [server, applicationset, and controller](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#cpumemory-profiling) have pprof enabled. We should also enable pprof for the repo server.

# Motivation

Memory and CPU profiling. 

# Proposal

Follow a similar approach that was taken in the controller and server.

### PR DESCRIPTION
**Pull request by ppapapetrou76**
closes #25988 

Check the issue with the (problematic) current status
Alongside the code changes, I also updated the docs and the manifest with the new config map key to enable pprof endpoints in repo-server

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: cmd/argocd-repo-server/commands/argocd_repo_server.go [hunk 1]
```diff
@@ -199,8 +201,9 @@ func NewCommand() *cobra.Command {
 				}
 				return nil
 			})
-			http.Handle("/metrics", metricsServer.GetHandler())
-			go func() { errors.CheckError(http.ListenAndServe(fmt.Sprintf("%s:%d", metricsHost, metricsPort), nil)) }()
+			mux.Handle("/metrics", metricsServer.GetHandler())
+			profile.RegisterProfiler(mux)
+			go func() { errors.CheckError(http.ListenAndServe(fmt.Sprintf("%s:%d", metricsHost, metricsPort), mux)) }()
```
Comment (rumstead) [inline cmd/argocd-repo-server/commands/argocd_repo_server.go:206]: As part of our code coverage, we need the server to gracefully shutdown in the e2e tests so the buffers clear. Any concerns here with this preventing a clean shutdown?

Comment (ppapapetrou76) [reply cmd/argocd-repo-server/commands/argocd_repo_server.go:206]: @rumstead Other services handle profiler the same way without issues - I mean, we should have already noticed problems during shutdown. 

However, I can push a commit to include the metrics handler to stop gracefully. 

WDYT?

Comment (rumstead) [reply cmd/argocd-repo-server/commands/argocd_repo_server.go:206]: Yea it may not be an issue. I was trying to look up code coverage to see if our e2e tests get it but looks like our sonar integration is currently broken. 

https://github.com/argoproj/argo-cd/commit/d63aa846c5c0b8d5dbfed632d5b6c9d11c1cf42b

Comment (rumstead) [reply cmd/argocd-repo-server/commands/argocd_repo_server.go:206]: Now that the code coverage is fixed, I wonder if we can create a dummy pull based off this branch and make sure the code is covered?

Comment (ppapapetrou76) [reply cmd/argocd-repo-server/commands/argocd_repo_server.go:206]: @rumstead sorry I think I lost you - should I update the branch against master ? something else?

Comment (rumstead) [reply cmd/argocd-repo-server/commands/argocd_repo_server.go:206]: i meant something like this: https://github.com/argoproj/argo-cd/pull/26378 to see how the code coverage looks. Let's see what it comes back with

Comment (ppapapetrou76) [reply cmd/argocd-repo-server/commands/argocd_repo_server.go:206]: 🤦🏾 🤦🏾 🤦🏾 🤦🏾 🤦🏾 🤦🏾 
OFC

Comment (rumstead) [reply cmd/argocd-repo-server/commands/argocd_repo_server.go:206]: https://github.com/argoproj/argo-cd/pull/26378 looks like it still gets the coverage from the e2e tests!

**Review by rumstead — APPROVED** [review]
LGTM
