### PR TITLE
fix: hide app namespace on the ui

### LINKED ISSUE #11111: Disable argo-cd namespace in applications title on web-ui
# Summary

Disable argo-cd "release name" in applications title on web-ui

# Motivation

No reason to show it

# Proposal

Disable it

test

### PR DESCRIPTION
**Pull request by ashutosh16**
Fixes https://github.com/argoproj/argo-cd/issues/11111
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexef** [comment]
superseeds: https://github.com/argoproj/argo-cd/pull/11165

**Comment by ashutosh16** [comment]
@crenshaw-dev  @alexef  Can you review the PR?

File: ui/src/app/shared/components/application-selector/application-selector.tsx [hunk 1]
```diff
@@ -18,7 +20,9 @@ export const ApplicationSelector = ({apps, formApi}: {apps: models.Application[]
                     <label key={appInstanceName(app)} style={{marginTop: '0.5em', cursor: 'pointer'}}>
                         <CheckboxField field={`app/${i}`} />
                         &nbsp;
-                        {app.isAppOfAppsPattern ? `(App of Apps) ${appQualifiedName(app)}` : appQualifiedName(app)}
+                        {app.isAppOfAppsPattern
```
Comment (alexef) [inline ui/src/app/shared/components/application-selector/application-selector.tsx:23]: side note, I never seen the `(App of Apps)` prefix so far

File: ui/src/app/applications/components/applications-list/applications-list.tsx [hunk 2]
```diff
@@ -307,6 +307,15 @@ export const ApplicationsList = (props: RouteComponentProps<{}>) => {
     const [isAppCreatePending, setAppCreatePending] = React.useState(false);
     const loaderRef = React.useRef<DataLoader>();
     const {List, Summary, Tiles} = AppsListViewKey;
+    const [authSettings, setAuthSettings] = React.useState(null);
+
+    React.useEffect(() => {
```
Comment (alexef) [inline ui/src/app/applications/components/applications-list/applications-list.tsx:312]: We already call services.authService.settings() in the top level App component. Can we set the context there instead?

File: ui/src/app/shared/components/application-selector/application-selector.tsx (hunk 1 above)
Comment (ashutosh16) [reply ui/src/app/shared/components/application-selector/application-selector.tsx:23]: I've not seen the `App of Apps`  ui myself.

File: ui/src/app/applications/components/applications-list/applications-list.tsx (hunk 2 above)
Comment (ashutosh16) [reply ui/src/app/applications/components/applications-list/applications-list.tsx]: Agreed, the Context can be moved further up.

File: ui/src/app/applications/components/utils.tsx [hunk 3]
```diff
@@ -1118,8 +1118,8 @@ export const urlPattern = new RegExp(
     )
 );
 
-export function appQualifiedName(app: appModels.Application): string {
-    return app.metadata.namespace + '/' + app.metadata.name;
+export function appQualifiedName(app: appModels.Application, nsEnabled: boolean): string {
+    return nsEnabled ? app.metadata.namespace + '/' + app.metadata.name : app.metadata.name;
```
Comment (blakepettersson) [inline ui/src/app/applications/components/utils.tsx:1122]: A minor nit, which IMO is a bit clearer (maybe not for others though, so take this with a grain of salt)

Otherwise LGTM!

```suggestion
    return `${nsEnabled ? app.metadata.namespace + '/': ''}app.metadata.name`;
```

**Review by alexef — APPROVED** [review]

**Review by blakepettersson — APPROVED** [review]

**Comment by alexef** [comment]
@ashutosh16 please fix lint https://github.com/argoproj/argo-cd/actions/runs/3447734925/jobs/5754058103

**Comment by ashutosh16** [comment]
@crenshaw-dev  Can we merge the PR?

**Comment by crenshaw-dev** [comment]
@ashutosh16 early next week. :-)

**Review by crenshaw-dev — APPROVED** [review]
Local test checks out. Thanks @ashutosh16!
