### PR TITLE
fix: "admin cluster generate-spec" fails on missing "argocd-cm" (#10429)

### LINKED ISSUE #10429: argocd CLI admin cluster generate spec does not work in v2.4.9
**Describe the bug**
When executing `argocd admin cluster generate-spec clustername` an error is printed instead of the cluster config. This used to work in an older version of argocd CLI.

**To Reproduce**
```bash
$ export KUBECONFIG=~/.kube/my-cluster 
» argocd admin cluster generate-spec azure-eu-v2 |yq eval '.stringData.config' -|jq|yq eval - -P
FATA[0000] configmap "argocd-cm" not found              
null
```

```bash
$ argocd version
argocd: v2.4.11+3d9e9f2.dirty
  BuildDate: 2022-08-22T12:52:04Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: dirty
  GoVersion: go1.19
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified    
```

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://RREDACTED
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-cluster-admin
  name: my-cluster-admin@my-cluster
current-context: my-cluster-admin@my-cluster
kind: Config
preferences: {}
users:
- name: my-cluster-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

**Expected behavior**
```bash
$ argocd version
argocd: v2.2.11+aa3f374
  BuildDate: 2022-07-12T16:13:20Z
  GitCommit: aa3f3749f8d5f174d2e4cdd2cf14cf6f9ef55143
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified  
```

```bash
$ export KUBECONFIG=~/.kube/my-cluster 
$ argocd admin cluster generate-spec azure-eu-v2 |yq eval '.stringData.config' -|jq|yq eval - -P
tlsClientConfig:
  insecure: false
  certData: REDACTED
  keyData: REDACTED
  caData: REDACTED
```

### PR DESCRIPTION
**Pull request by ATGardner**
when calling "CreateCluster" in "admin cluster generate-spec" context, there is no argocd-cm avilable.
closes #10429 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: util/db/cluster.go [hunk 1]
```diff
@@ -94,12 +94,15 @@ func (db *db) ListClusters(_ context.Context) (*appv1.ClusterList, error) {
...
 // CreateCluster creates a cluster
 func (db *db) CreateCluster(ctx context.Context, c *appv1.Cluster) (*appv1.Cluster, error) {
-	settings, err := db.settingsMgr.GetSettings()
-	if err != nil {
-		return nil, err
-	}
-	if c.Server == appv1.KubernetesInternalAPIServerAddr && !settings.InClusterEnabled {
-		return nil, status.Errorf(codes.InvalidArgument, "cannot register cluster: in-cluster has been disabled")
+	if c.Server == appv1.KubernetesInternalAPIServerAddr {
+		settings, err := db.settingsMgr.GetSettings()
```
Comment (ATGardner) [inline util/db/cluster.go]: only try to get the "argocd-cm" if the requested server to create is "https://kubernetes.default.svc".

in the "admin cluster generate-spec" it will never be found, because we use a fake clientSet, and not connect to a real argo-cd instance with any settings.

**Review by reggie-k — CHANGES_REQUESTED** [review]
I think it is better to change only the `cluster generate-spec` command, and not the wider-scope `CreateCluster` method, we can just create an empty minimal cm and cluster secret, and send them in the fake.NewClientset(...) in NewGenClusterConfigCommand:
``` yaml
			// Seed a minimal in-memory Argo CD environment so settings retrieval succeeds
			argoCDCM := &corev1.ConfigMap{
				TypeMeta: metav1.TypeMeta{Kind: "ConfigMap", APIVersion: "v1"},
				ObjectMeta: metav1.ObjectMeta{
					Name:      common.ArgoCDConfigMapName,
					Namespace: ArgoCDNamespace,
					Labels: map[string]string{
						"app.kubernetes.io/part-of": "argocd",
					},
				},
			}
			argoCDSecret := &corev1.Secret{
				TypeMeta: metav1.TypeMeta{Kind: "Secret", APIVersion: "v1"},
				ObjectMeta: metav1.ObjectMeta{
					Name:      common.ArgoCDSecretName,
					Namespace: ArgoCDNamespace,
					Labels: map[string]string{
						"app.kubernetes.io/part-of": "argocd",
					},
				},
				Data: map[string][]byte{
					"server.secretkey": []byte("test"),
				},
			}
			kubeClientset := fake.NewClientset(argoCDCM, argoCDSecret)
```
It aligns better with how we generate spec for a repo.

**Review by reggie-k — APPROVED** [review]
LGTM!

**Comment by ATGardner** [comment]
closes #10429
