### PR TITLE
fix: bump cache version due to redis compression feature

### LINKED ISSUE #4270: Bump cache version due to redis compression feature
Need to bump up the version in our cache, since the redis compression feature which was merged earlier today causes cache retrieval to fail

### PR DESCRIPTION
**Pull request by alexmt**
Closes https://github.com/argoproj/argo-cd/issues/4270

PR ensures that upgrading 1.8 release will invalidate cached objects stored in redis.

### CODE REVIEW

File: common/common.go [hunk 1]
```diff
@@ -163,7 +163,7 @@ const (
 	MinClientVersion = "1.4.0"
 	// CacheVersion is a objects version cached using util/cache/cache.go.
 	// Number should be bumped in case of backward incompatible change to make sure cache is invalidated after upgrade.
-	CacheVersion = "1.0.0"
+	CacheVersion = "2"
```
Comment (jessesuen) [inline common/common.go:166]: Lets use the version where we make the breaking change, like we do for MinClientVersion.

**Review by jessesuen — APPROVED** [review]

File: common/common.go (hunk 1 above)
Comment (alexmt) [reply common/common.go]: done
