### PR TITLE
Issue #1944 - Gracefully handle missing cached app state

### LINKED ISSUE #1944: Error message "Unable to load data: key is missing" is confusing
**Describe the bug**

Confusing error message `Unable to load data: key is missing` is shown on application details page if app info is missing in the cache. Instead of showing meaningless message UI should trigger app refresh. Usually, the error is reproducible if the controller is no functioning properly and therefore cache is not populated. Refresh should trigger reconciliation loop and either populate the cache or reveal real issue.

**To Reproduce**
1. Create new app
2. Break controller, e.g. scaledown controller deployment to 0. Restart redis to get rid of cache
3. Click on any app node
4. See the error

**Version**: v1.2.0

### PR DESCRIPTION
**Pull request by alexmt**
Closes #1944 

PR implements graceful handling of cache miss error. If API server cannot find cache app state it triggers app refresh and wait for cache to be populated.

### CODE REVIEW

File: server/application/application.go [hunk 1]
```diff
@@ -618,8 +620,32 @@ func (s *Server) getApplicationClusterConfig(applicationName string) (*rest.Conf
...
+	err := getFromCache()
+	if err != nil && err == cache.ErrCacheMiss {
+		conditions := a.Status.GetConditions(map[appv1.ApplicationConditionType]bool{
+			appv1.ApplicationConditionComparisonError:  true,
+			appv1.ApplicationConditionInvalidSpecError: true,
+		})
+		if len(conditions) > 0 {
+			return errors.New(argoutil.FormatAppConditions(conditions))
+		}
+		_, err = s.Get(ctx, &application.ApplicationQuery{
```
Comment (golangcibot) [inline server/application/application.go]: ineffectual assignment to `err` (from `ineffassign`)

File: util/cache/redis.go [hunk 2]
```diff
@@ -28,24 +29,37 @@ type redisCache struct {
 	codec      *rediscache.Codec
 }
 
+// if redis server goes down the first client request fails with EOF error
+func doWithRetry(action func() error) error {
+	err := action()
+	if err == io.EOF {
```
Comment (alexec) [inline util/cache/redis.go]: any danger of thundering herd?

**Review by alexec — COMMENTED** [review]
What do you want to do about testing?

File: util/cache/redis.go (hunk 2 above)
Comment (alexmt) [reply util/cache/redis.go]: I don't think so. EOF happens only if redis got restarted and one retry won't hurt.

**Comment by alexmt** [comment]
Implemented unit test for the `getCachedAppState` and `GetConditions` method. I don't think it is possible to implement meaningful e2e test.

File: util/cache/redis.go [hunk 3]
```diff
@@ -28,24 +29,37 @@ type redisCache struct {
...
+		return action()
+	}
+	return err
+}
+
 func (r *redisCache) Set(item *Item) error {
```
Comment (alexec) [inline util/cache/redis.go]: tests?

**Review by alexec — CHANGES_REQUESTED** [review]
I think this should be rebased on top of my preceding work.
Also - more tests please.

**Review by alexec — APPROVED** [review]
