### PR TITLE
fix(gitops-engine): apply HideSecretData to server-side diff results for Secrets

### LINKED ISSUE #25260: Secrets become OutOfSync with `ServerSideDiff=true,IncludeMutationWebhook=true`
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

I use [Bank-Vault secret injection webhook](https://bank-vaults.dev/docs/mutating-webhook/) with Secret to inject values from Vault. I added `argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true` annotation to avoid having diff after apply but it reliably  become OutOfSync immediately or with short delay.
`kubectl apply -f secret.yaml --dry-run=server -o yaml` and `kubectl get secret -n test-chart test-creds -o yaml` returns same value after mutation for the secret field. But ArgoCD shows diff like on the screenshot.  
Further testing showed that `IncludeMutationWebhook=true` has no effect on result. Mutated CRDs do not show any diff. Secrets become OutOfSync either way.

**To Reproduce**

1. Deploy Vault and [vault-secrets-webhook](https://github.com/bank-vaults/vault-secrets-webhook/tree/main/deploy/charts/vault-secrets-webhook).
2. Deploy example Secret using ArgoCD, where passwd is base64 ref for secret in vault. `vault:test/data/test#TEST` is example

secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-creds
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://your.vault.url
    vault.security.banzaicloud.io/vault-path: kubernetes
    vault.security.banzaicloud.io/vault-role: vault-role
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  labels:
    helm.sh/chart: my-test-chart-0.3.1
    app.kubernetes.io/name: my-test-chart
    app.kubernetes.io/instance: my-test-chart
    environment: dev
    app.kubernetes.io/version: "0.0.2"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  passwd: dmF1bHQ6dGVzdC9kYXRhL3Rlc3QjVEVTVA==
```
app.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-chart
  namespace: argocd
spec:
  destinations:
    - name: in-cluster
      namespace: "test-chart"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://test-repo.git
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true  #,IncludeMutationWebhook=true
spec:
  destination:
    namespace: test-chart
    name: in-cluster
  project: test-chart
  source:
    helm:
      valueFiles:
        - values-dev.yaml
    path: charts/test-chart
    repoURL: https://test-repo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ServerSideApply=true
```
3. Observe incorrect behavior.

**Expected behavior**

No diff is displayed after Sync

**Screenshots**

Image

**Version**

```shell
argocd: v3.2.0+66b2f30
  BuildDate: 2025-11-04T14:51:35Z
  GitCommit: 66b2f302d91a42cc151808da0eec0846bbe1062c
  GitTreeState: clean
  GoVersion: go1.25.0
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by pjiang-dev**
Fixes https://github.com/argoproj/argo-cd/issues/25260

### Summary
Fixes Secret resources showing persistent OutOfSync status when using IncludeMutationWebhook=true with mutation webhooks.

### Problem

After sync, the live Secret already contains the webhook-mutated value. On the next server-side diff, Argo CD performs dry-run SSA, which also runs the webhook and produces predictedLive. Logically, predictedLive should match live. But for core Secrets, the webhook-mutated data can differ at the raw comparison level between the dry-run result and the actual live object. Argo CD compares those bytes and marks the resource OutOfSync.

### Solution
Use HideSecretData during ServerSideDiff to ensure after mutating webhook modifies secret that data is symmetrical before comparison if secret values are identical

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: gitops-engine/pkg/diff/diff.go [hunk 1]
```diff
@@ -190,14 +190,32 @@ func serverSideDiff(config, live *unstructured.Unstructured, opts ...Option) (*D
...
+		if err != nil {
+			return nil, fmt.Errorf("error hiding secret data for resource %s/%s: %w", config.GetKind(), config.GetName(), err)
+		}
+		predictedLiveBytes, err = json.Marshal(maskedPredictedLive)
+		if err != nil {
+			return nil, fmt.Errorf("error marshaling predicted live for resource %s/%s: %w", config.GetKind(), config.GetName(), err)
+		}
+		live = maskedLive
+	}
+
```
Comment (agaudreault) [inline gitops-engine/pkg/diff/diff.go]: It looks like the first `if !isCoreSecret(config)` is not necessary if the code is re-ordered.

```suggestion
	Normalize(live, opts...)
	unstructured.RemoveNestedField(live.Object, "metadata", "managedFields")
	unstructured.RemoveNestedField(live.Object, "metadata", "resourceVersion")

	if isCoreSecret(config) {
		// Mask Secret data symmetrically before comparison.
		// Equal values get equal placeholders, different values get different placeholders.
		maskedPredictedLive, maskedLive, err := HideSecretData(predictedLive, live, nil)
		if err != nil {
			return nil, fmt.Errorf("error hiding secret data for resource %s/%s: %w", config.GetKind(), config.GetName(), err)
		}
		live = maskedLive
		predictedLive = maskedPredictedLive
	}
	
	predictedLiveBytes, err := json.Marshal(predictedLive)
	if err != nil {
		return nil, fmt.Errorf("error marshaling predicted live for resource %s/%s: %w", config.GetKind(), config.GetName(), err)
	}

```

Comment (pjiang-dev) [reply gitops-engine/pkg/diff/diff.go]: sure, this works for me

**Review by agaudreault — APPROVED** [review]
LGTM

**Comment by 1ovsss** [comment]
@pjiang-dev hey, thanks a lot for this PR.
I noticed there are no cherry-pick labels added. Does this mean the fix will only land in the next 3.5 release or is there way it can make it into 3.4.x?
