### PR TITLE
fix: handle annotated git tags correctly in repo server cache

### LINKED ISSUE #21548: Regression: Application targetting an annotated tag will self heal, even when self-healing is disabled.
**Describe the bug**

**Note**: The cause of this bug is likely the same as https://github.com/argoproj/argo-cd/issues/20082. I have opened this current bug to track another failing case, but it likely shares the same root cause as #20082. See that bug for some additional details.

In Git, there are two types of tags: annotated tags and lightweight tags. Annotated tags may have a message/data attached to them, while lightweight tags do not. This means that annotated tags have their own ID (different from the commit SHA), while lightweight tags do not. The ID of the lightweight tag is the same as the target commit SHA. 

However, Argo CD behaviour currently differs when `.spec.source.targetRevision` points to an annotated tag, versus a lightweight tag. This appears to be a regression that was introduced in April 2024, [based on 'git bisect' testing](https://github.com/argoproj/argo-cd/issues/20082).

When:
- you create an Application with `automatedSync: true, selfHealing: false`
- AND that Application targets an annotated tag, 

Then:
- the Application should NOT self heal in any scenario, because `selfHealing: false`

But at present, selfHealing WILL occur when the targetRevision is an annotated tag, in some cases.

In contrast, when you use a lightweight tag, rather than an annotated tag, the behaviour is correct and as expected (no self healing).

### Automated test:

I wrote an Argo CD E2E test case that reproduces the problem:
- Clone [the repo](https://github.com/argoproj/argo-cd/compare/master...jgwest:argo-cd:annotated-tag-behaviour-jan-2024?expand=1)
```
git clone git@github.com:jgwest/argo-cd
cd argo-cd
git checkout annotated-tag-behaviour-jan-2024
# rebase to main if you wish
make start-e2e

# This will currently fail, as the test is verifying that Argo CD behaviour has regressed: 
go test -count=1 -timeout 30s -run ^TestAutomatedSelfHealingAgainstAnnotatedTag$ github.com/argoproj/argo-cd/v3/test/e2e

# The exact same test, run against a lightweight tag, will pass:
go test -count=1 -timeout 30s -run ^TestAutomatedSelfHealingAgainstLightweightTag$ github.com/argoproj/argo-cd/v3/test/e2e
```

### Manually:

1) For a GitOps repo of your choice, add an annotated tag:

```bash
git clone (your gitops repo)
cd "(your gitops repo)"
git tag -f -a my-annotated-tag -m "my annotated tag"
git push -f && git push -f --tag
```

2) Create Application targetting that annotated tag via `.spec.source.targetRevision`.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-application
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: # (... your repo URL ...)
    targetRevision: my-annotated-tag
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
```

3) Wait for it to sync.

4) Update a K8s resource in your gitops repository (for example, updating `.spec.revisionHistoryLimit` of a Deployment). Push that new commit.

5) Update annotated tag to point to new commit.
- git tag -f -a my-annotated-tag -m "message"
- git push --tags -f origin master

6) Do a hard refresh in the Argo CD UI.

7) Wait for Argo CD to reconcile the K8s resource (e.g. `.spec.revisionHistoryLimit` of a Deployment) to the new value in Git.

8) Within K8s itself, update that same K8s resource. (e.g. update `.spec.revisionHistoryLimit` of a Deployment to a value that is different from what is in git).

9) *Fail*: Even though the Application is `selfHeal: false`, you will see the change that was made in step 8 is reverted to the previous version of the resource from step 5. (e.g. `.spec.revisionHistoryLimit` of Deployment has changed back to the value in Git, even though it should not)

**Version**

See #20082 for detailed description of what caused the regression, but TL;DR: this behaviour is currently present in v2.11.x, v2.12.x, v2.13.x and current `master`.

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

### PR DESCRIPTION
**Pull request by aali309**
When using annotated git tags with auto-sync enabled but self-heal disabled, manual changes were getting reverted. This was happening because the repo server cache wasn't handling annotated tags correctly.

Fixes: #21548 

See https://github.com/argoproj/argo-cd/issues/20082 for detailed description of what caused the regression, but TL;DR: this behaviour is currently present in v2.11.x, v2.12.x, v2.13.x and current master

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: util/git/client_test.go [hunk 1]
```diff
@@ -129,6 +130,23 @@ func Test_IsAnnotatedTag(t *testing.T) {
...
+
+	// Test single function
+	resolvedRef := resolveTagReference(tagRef, commitHash)
+
+	// Verify
+	assert.Equal(t, commitHash, resolvedRef.Hash())
+	assert.Equal(t, tagRef.Name(), resolvedRef.Name())
+}
+
+func resolveTagReference(tagRef *plumbing.Reference, commitHash plumbing.Hash) *plumbing.Reference {
```
Comment (anandf) [inline util/git/client_test.go:146]: De we need this separate method ? All it does is wrap a function call.

File: test/e2e/testdata/deployment/deployment.yaml [hunk 2]
```diff
@@ -15,7 +15,7 @@ spec:
         app: nginx
     spec:
       containers:
-        - name: nginx
-          image: quay.io/argoprojlabs/argocd-e2e-container:0.1
-          ports:
-            - containerPort: 80
+      - name: nginx
```
Comment (anandf) [inline test/e2e/testdata/deployment/deployment.yaml:18]: this formatting change may not be required.

File: test/e2e/git_test.go [hunk 3]
```diff
@@ -90,3 +98,79 @@ func TestGitSemverResolutionUsingConstraintWithLeadingZero(t *testing.T) {
 		Expect(SyncStatusIs(SyncStatusCodeSynced)).
 		Expect(Pod(func(p corev1.Pod) bool { return strings.HasPrefix(p.Name, "new-app") }))
 }
+
+func TestAnnotatedTagInStatusSyncRevision(t *testing.T) {
```
Comment (jgwest) [inline test/e2e/git_test.go:102]: - Your E2E tests are not currently correctly testing the failing case, AFAICT. 
- Notice that if you comment out your fix in this PR (e.g. you remove the changes in `workaround.go`), that those E2E tests still pass.
	- Since the fix has been removed, obviously the tests should fail. If they don't, that means the tests aren't testing what we think they are.
	- The tests in my original E2E test branch do not exhibit this behaviour, if you want to use those as originally constructed.

File: test/e2e/testdata/deployment/deployment.yaml (hunk 2 above)
Comment (aali309) [reply test/e2e/testdata/deployment/deployment.yaml:18]: Yes, this is default Cursor app behaviour!

File: test/e2e/fixture/app/actions.go [hunk 4]
```diff
@@ -535,3 +547,12 @@ func (a *Actions) WithImpersonationDisabled() *Actions {
 	errors.CheckError(fixture.SetImpersonationEnabled("false"))
 	return a
 }
+
```
Comment (blakepettersson) [inline test/e2e/fixture/app/actions.go:550]:
```suggestion
```

File: test/e2e/fixture/app/actions.go [hunk 5]
```diff
@@ -535,3 +547,12 @@ func (a *Actions) WithImpersonationDisabled() *Actions {
...
+/* // AddAnnotatedTag creates an annotated git tag
+func (a *Actions) AddAnnotatedTag(tag, message string) *Actions {
+	// Run git commands in the test repo directory with -f flag to force update
+	_, err := fixture.Run("/tmp/argo-e2e/testdata.git", "git", "tag", "-f", "-a", tag, "-m", message)
+	errors.CheckError(err)
+	return a
+}
+*/
```
Comment (blakepettersson) [inline test/e2e/fixture/app/actions.go:558]:
```suggestion
```

File: test/e2e/fixture/app/actions.go [hunk 6]
```diff
@@ -491,7 +503,7 @@ func (a *Actions) And(block func()) *Actions {
 
 func (a *Actions) Then() *Consequences {
 	a.context.t.Helper()
-	return &Consequences{a.context, a, 15}
+	return &Consequences{a.context, a, 30}
```
Comment (blakepettersson) [inline test/e2e/fixture/app/actions.go:506]: Why has the timeout value changed?

**Comment by blakepettersson** [comment]
I followed the @anandf [protocol](https://github.com/argoproj/argo-cd/issues/20083#issuecomment-2376706348)™ and it looks like the issue has disappeared.

File: test/e2e/fixture/app/actions.go (hunk 6 above)
Comment (aali309) [reply test/e2e/fixture/app/actions.go:506]: The timeout value was increased from 15 to 30 to ensure stability during test execution. We observed intermittent failures where operations took longer than expected, and increasing the timeout helps mitigate those issues.

Comment (blakepettersson) [reply test/e2e/fixture/app/actions.go]: Could you leave it at 15? At least on CI, if it fails it'll automatically retry.

**Review by blakepettersson — APPROVED** [review]
LGTM

**Review by anandf — APPROVED** [review]
LGTM

**Review by keithchong — APPROVED** [review]
Thanks @blakepettersson and @anandf for your reviews.  I'm approving this.

**Comment by awx-fuyuanchu** [comment]
Thanks guys. really appreciate for your contributions.
