### PR TITLE
fix: Fixed matrix requeueAfterSeconds for PR

### LINKED ISSUE #10914: RequeueAfterSeconds for PR generator not being detected when using Matrix generator
When trying to use Matrix generator with PR + Cluster generators, the 'RequeueAfterSeconds' parameter of the PullRequest generator always returns 0.

**Describe the bug**

The ApplicationSet is not detecting new PullRequests when the PR generator is used with the Matrix gen.

**To Reproduce**

- Create an AppSet resource with Matrix generator (Here is mine)
- Set RequeueAfterSeconds to whatever value, say 15
- Apply the AppSet to your cluster (I tested with kind and EKS)
- Checks the argocd/argocd-applicationset-controller-xxxxx pod's log, and you'll see sth similar to the below one:

```
time="2022-10-12T15:23:33Z" level=info msg="matched cluster secret" cluster=cluster-aaaaa.sk1.eu-west-1.eks.amazonaws.com-927495557
time="2022-10-12T15:23:33Z" level=info msg="matched cluster secret" cluster=cluster-bbbbb.gr7.eu-west-2.eks.amazonaws.com-1658368765
time="2022-10-12T15:23:34Z" level=info msg="generated 0 applications" generator="{nil nil nil nil nil nil &MatrixGenerator{Generators:xxxx ....}"
time="2022-10-12T15:23:34Z" level=info msg="end reconcile" requeueAfter=0s <--------
```

The doc says that the default value of `requeueAfterSeconds` is 30mins, and in our buggy-case, if I don't provide it I still get 0s in the logs.

**Version**

argocd: v2.5.0-rc1
clusters: kind and EKS v1.23
Git: Gitlab MRs and Github PRs (same issue)

### PR DESCRIPTION
**Pull request by Aym3nTN**
Fixes: https://github.com/argoproj/argo-cd/issues/10914

Signed-off-by: Aymen Ben Tanfous <aymen.bentanfous@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by mubarak-j** [comment]
@Aym3nTN I reached out to ArgoCD maintainers on slack to review this PR (as I'm also impacted by this issue) and they asked if a unit test can be included in this PR? if not I can start a similar PR and add that. I don't think I've write permission to your branch/repo

**Comment by Aym3nTN** [comment]
I'll give it a look tonight Mubarak!

**Comment by Aym3nTN** [comment]
@mubarak-j I gave you access to my [repo](https://github.com/Aym3nTN/argo-cd); I tried to add some tests, but I don't believe that's good enough.. Check your email, you should have received an invitation by now to collaborate on my repo.

File: applicationset/generators/matrix_test.go [hunk 1]
```diff
@@ -431,6 +433,31 @@ func TestMatrixGetRequeueAfter(t *testing.T) {
...
+				},
+				{
+					PullRequest: pullRequestGenerator,
+				},
+			},
+			gitGetRequeueAfter: time.Duration(15 * time.Second),
+			expected:           time.Duration(15 * time.Second),
+		},
+		{
+			name: "returns the default time if no requeueAfterSeconds is provided",
```
Comment (Aym3nTN) [inline applicationset/generators/matrix_test.go:450]: @crenshaw-dev so I added this test.. I run the test before I implement the fix and it was failing.. it was returning 0 instead of the default value..
Now after the fix, this tests is passing.. I think this is sufficient, right?

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@Aym3nTN thanks for this! I will merge/release the fix one week from today.

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.0-rc4, release-2.5 for 2.5.7, and release-2.4 for 2.4.19.
