### PR TITLE
fix: health check doesn't detect resource deletion during sync operation

### LINKED ISSUE #25323: Health check loop doesn't detect resource deletion during sync operation
# Sync gets stuck indefinitely when resource is deleted during synchronization

**Checklist:**

- [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq
- [ ] I've included steps to reproduce the bug
- [ ] I've pasted the output of `argocd version`

---

## Describe the bug

When a resource with sync wave annotations is manually deleted from the cluster during an ongoing synchronization operation, the sync operation gets stuck indefinitely in a "waiting for healthy state" phase and never completes or fails.

---

## To Reproduce

1. Create an application with resources that have sync wave annotations:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  key: value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
```

2. Start a synchronization operation for the application
3. While the sync is in progress (when resources are waiting to become healthy), manually delete the resource from the cluster:
   ```bash
   kubectl delete deployment my-app
   ```
4. Observe the sync operation status in ArgoCD UI or CLI

---

## Expected behavior

The sync operation should detect that the resource has been deleted and fail with a clear error message, such as:
- "resource was deleted during synchronization"
- "resource no longer exists in cluster"

This would allow users to understand what happened and take appropriate action (e.g., retry the sync, investigate why the resource was deleted).

---

## Actual behavior

The sync operation gets stuck indefinitely in the "waiting for healthy state" phase. 

In the ArgoCD UI, the application status shows a message similar to:
```
Syncing
waiting for healthy state of apps/Deployment/my-app
```

The sync operation never completes or fails, even though the resource no longer exists in the cluster. The only way to recover is to manually terminate the sync operation.

---

## Root Cause Analysis

The synchronization engine appears to rely on cached resource objects when checking health status. When a resource is deleted during synchronization:

1. The system continues to use the cached object for health checks
2. There is no verification that the resource still exists in the actual cluster
3. The sync operation enters an infinite waiting loop, continuously checking the health of a non-existent resource

---

## Additional Context

This issue is particularly problematic in scenarios where:
- Resources are managed by external controllers that may delete and recreate them
- Manual intervention is needed during troubleshooting
- There are race conditions between ArgoCD sync and other cluster operations

**Edge Case Consideration:**

There is a potential edge case where a resource has just been applied but hasn't appeared in the cluster yet (Kubernetes is still processing the creation). The fix should distinguish between:
- A resource that was just applied and is still being created (should wait)
- A resource that was previously running but has been deleted (should fail)

A reasonable approach might be to allow a grace period (e.g., 30 seconds) after the sync operation starts before marking a missing resource as deleted.

---

## Version

```shell
argocd: v2.14.2
```

---

## Logs

```
time="2024-01-15T10:30:45Z" level=info msg="Synchronizing application" application=my-app
time="2024-01-15T10:30:46Z" level=info msg="Applying resource ConfigMap/my-config" application=my-app
time="2024-01-15T10:30:47Z" level=info msg="Resource ConfigMap/my-config synced successfully" application=my-app
time="2024-01-15T10:30:48Z" level=info msg="Applying resource Deployment/my-app" application=my-app
time="2024-01-15T10:30:49Z" level=info msg="Waiting for resource to become healthy" resource="apps/Deployment/my-app"
time="2024-01-15T10:30:54Z" level=info msg="Waiting for resource to become healthy" resource="apps/Deployment/my-app"
time="2024-01-15T10:30:59Z" level=info msg="Waiting for resource to become healthy" resource="apps/Deployment/my-app"
time="2024-01-15T10:31:04Z" level=info msg="Waiting for resource to become healthy" resource="apps/Deployment/my-app"
time="2024-01-15T10:31:09Z" level=info msg="Waiting for resource to become healthy" resource="apps/Deployment/my-app"
# ... (logs continue indefinitely with the same "waiting for healthy state" message)
# Note: The resource was deleted at approximately 10:30:52, but the sync operation 
# continues to wait without detecting the deletion
```

### PR DESCRIPTION
**Pull request by cjcocokrisp**
Closes #25323 

Note: This is my first contribution to the internal workings of the application controller so please correct me if anything is wrong or this is something that is intended behavior.

This PR addresses a bug with the health check loop during a sync that includes sync waves. If a resource is deleted during the operations of its wave it will infinitely loop saying that it is waiting for healthy state of that resource.

At the current moment, this is fixed by checking to see if the operations live object is nil and if it is throw an operation error.

I have a few concerns with this solution however. The fail could happen if there is lag on the creation of the resource and probably other reasons I'm not thinking of. I'm thinking it might be a better idea to just return a different message that says that the resource is missing just to give the user a bit more indication. So let me know what you guys think. Was going to bring this up during the contributor meeting to get some opinions but time ran out.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [N/A] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [N/A] Does this PR require documentation updates?
* [N/A] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [X] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: gitops-engine/pkg/sync/sync_context.go [hunk 1]
```diff
@@ -515,6 +515,23 @@ func (sc *syncContext) Sync() {
 	multiStep := tasks.multiStep()
 	runningTasks := tasks.Filter(func(t *syncTask) bool { return (multiStep || t.isHook()) && t.running() })
 	if runningTasks.Len() > 0 {
+		// check if any of the running task's resources are missing to prevent infinite loop of waiting for healthy
+		for _, task := range runningTasks {
+			if task.phase == common.SyncPhaseSync && task.liveObj == nil {
+				liveObj, err := sc.getResource(task)
+				if err != nil && !apierrors.IsNotFound(err) {
+					sc.setResourceResult(task, task.syncStatus, common.OperationError, fmt.Sprintf("Failed to get live resource %v", err))
+				}
```
Comment (ppapapetrou76) [inline gitops-engine/pkg/sync/sync_context.go:541]: i think we need to add a `continue` here, if there is an error because right now  after setting the resource result to error, the code continues execution.  Then it checks if liveObj != nil (which will be false if there was an error)
Then it always sets the resource result to "missing resource". This means that even if there's an error here the function always returns "missing"

File: gitops-engine/pkg/sync/sync_context.go [hunk 2]
```diff
@@ -515,6 +515,23 @@ func (sc *syncContext) Sync() {
...
+				if liveObj != nil {
+					task.liveObj = liveObj
+					continue
+				}
+
+				sc.setResourceResult(task, common.ResultCodeSyncFailed, common.OperationError, fmt.Sprintf("Resource %s/%s/%s is missing, it might have been deleted", task.group(), task.kind(), task.name()))
+				return
```
Comment (ppapapetrou76) [inline gitops-engine/pkg/sync/sync_context.go]: Should we `continue` with the remaining tasks instead of returning?

**Review by ppapapetrou76 — COMMENTED** [review]
The fix looks on the right path but as you already stated it might lead to some false-positives when resources are being created. 

I suggest the following 

1. add a retry mechanism before declaring that a resource is missing.
2. maybe check for the obj previous state to figure out if it is a deletion or a new resource

And we need UTs for the introduced code

File: gitops-engine/pkg/sync/sync_context.go (hunk 2 above)
Comment (cjcocokrisp) [reply gitops-engine/pkg/sync/sync_context.go]: I think that would make sense if multiple tasks are running all should be checked not just one.

**Comment by cjcocokrisp** [comment]
Addressed the feedback comments. For the solution to the concern that I had, I added in a check before setting the error. which is:
```golang
if result, ok := sc.syncRes[task.resultKey()]; ok && result.Status == common.ResultCodeSynced
```

Checking if the resource has a result should combat the issue of the object not being created yet. It also seems to me that the status of a result is only set to synced when an apply is successful so that should hopefully mean the resource exists. 

Also added the unit tests. Let me know if there is anything else that I should change or add.

File: gitops-engine/pkg/sync/sync_context.go [hunk 3]
```diff
@@ -515,6 +515,26 @@ func (sc *syncContext) Sync() {
...
+				if err != nil && !apierrors.IsNotFound(err) {
+					sc.setResourceResult(task, task.syncStatus, common.OperationError, fmt.Sprintf("Failed to get live resource %v", err))
+					continue
+				}
+				if liveObj != nil {
+					task.liveObj = liveObj
+					continue
+				}
+
+				if result, ok := sc.syncRes[task.resultKey()]; ok && result.Status == common.ResultCodeSynced {
```
Comment (ppapapetrou76) [inline gitops-engine/pkg/sync/sync_context.go]: I'm wondering if this is enough. I mean we consider that a resource was previously created and not synced ( ResultCodeSyncFailed ) 

How the code would treat this scenario?

Comment (cjcocokrisp) [reply gitops-engine/pkg/sync/sync_context.go]: If the loop was entered in that scenario then it would wait for healthy. My guess would be most of the time if that result code is set it would probably also have an OperationError so this case might not happen. 

However, to be safe do you think it would be best to just check if it exists and not care about the status of it or should it be a more specific check?

**Comment by cjcocokrisp** [comment]
Thought about this a bit more and decided to remove the check for the result code I do not think it is needed.

I also thought a bit about the other solution being to had some sort of retry mechanism. I don't know if that would be too overkill. I think that would require adding a new field to the resource result being some sort of counter be it just an int that counts how many times its been checked or a timestamp for an expiration. That would then need to be remembered throughout sync calls which would require the API object to be altered which is what got me to the conclusion of being overkill.

What are some thoughts for both of the things mentioned?

File: gitops-engine/pkg/sync/sync_context.go [hunk 4]
```diff
@@ -515,6 +515,26 @@ func (sc *syncContext) Sync() {
...
+				}
+				if liveObj != nil {
+					task.liveObj = liveObj
+					continue
+				}
+
+				if _, ok := sc.syncRes[task.resultKey()]; ok {
+					sc.setResourceResult(task, common.ResultCodeSyncFailed, common.OperationError, fmt.Sprintf("Resource %s/%s/%s is missing, it might have been deleted", task.group(), task.kind(), task.name()))
+					continue
+				}
```
Comment (agaudreault) [inline gitops-engine/pkg/sync/sync_context.go]: Why checking the resource map here before setting the result? Shouldnt it be set if liveObj is nil?

Using the list of result to know if a resource exist or not can be misleading since it is not the purpose of the result list.

File: gitops-engine/pkg/sync/sync_context.go [hunk 5]
```diff
@@ -515,6 +515,26 @@ func (sc *syncContext) Sync() {
...
+			if task.phase == common.SyncPhaseSync && task.liveObj == nil {
+				liveObj, err := sc.getResource(task)
+				if err != nil && !apierrors.IsNotFound(err) {
+					sc.setResourceResult(task, task.syncStatus, common.OperationError, fmt.Sprintf("Failed to get live resource %v", err))
+					continue
+				}
+				if liveObj != nil {
+					task.liveObj = liveObj
+					continue
+				}
```
Comment (agaudreault) [inline gitops-engine/pkg/sync/sync_context.go:544]: If the live object does exist, then the next call to the Sync method will handle the flow normally (liveObj will be expected to be set). There are no need to set the task.liveObj for this iteration.

File: gitops-engine/pkg/sync/sync_context.go [hunk 6]
```diff
@@ -515,6 +515,26 @@ func (sc *syncContext) Sync() {
 	multiStep := tasks.multiStep()
 	runningTasks := tasks.Filter(func(t *syncTask) bool { return (multiStep || t.isHook()) && t.running() })
 	if runningTasks.Len() > 0 {
+		// check if any of the running task's resources are missing to prevent infinite loop of waiting for healthy
+		for _, task := range runningTasks {
+			if task.phase == common.SyncPhaseSync && task.liveObj == nil {
```
Comment (agaudreault) [inline gitops-engine/pkg/sync/sync_context.go]: Why `task.phase == common.SyncPhaseSync` and not all phases?

**Review by agaudreault — CHANGES_REQUESTED** [review]

File: gitops-engine/pkg/sync/sync_context.go [hunk 7]
```diff
@@ -515,6 +515,26 @@ func (sc *syncContext) Sync() {
 	multiStep := tasks.multiStep()
 	runningTasks := tasks.Filter(func(t *syncTask) bool { return (multiStep || t.isHook()) && t.running() })
 	if runningTasks.Len() > 0 {
+		// check if any of the running task's resources are missing to prevent infinite loop of waiting for healthy
+		for _, task := range runningTasks {
```
Comment (agaudreault) [inline gitops-engine/pkg/sync/sync_context.go:535]: Can a running task at this point be a "pruning" task where it is the correct result to not have a live resource?

Comment (cjcocokrisp) [reply gitops-engine/pkg/sync/sync_context.go:535]: I do not think so. When a prune task is ran the `OperationPhase` seems to never be set to `OperationRunning`. `pruneObject()` only ever returns `ResultCodePruned`, `ResultCodePruneSkipped`, or `ResultCodeSyncFailed`.

That result code is mapped to the following operationPhases:
```go
var operationPhases = map[common.ResultCode]common.OperationPhase{
	common.ResultCodeSynced:       common.OperationRunning,
	common.ResultCodeSyncFailed:   common.OperationFailed,
	common.ResultCodePruned:       common.OperationSucceeded,
	common.ResultCodePruneSkipped: common.OperationSucceeded,
}
```
So because it never goes to `OperationRunning` and therefore never filtered into `runningTasks`.

File: gitops-engine/pkg/sync/sync_context.go (hunk 6 above)
Comment (cjcocokrisp) [reply gitops-engine/pkg/sync/sync_context.go]: I'm pretty sure it's because I was running into a unit test problem but I just fixed that so it should be for all phases, I think I just did not get around to fixing it.

File: gitops-engine/pkg/sync/sync_context.go (hunk 4 above)
Comment (cjcocokrisp) [reply gitops-engine/pkg/sync/sync_context.go]: This is to check if the resource previously existed. I used this to address my worry about a false positive on resource creation. I originally had the condition as:
`if result, ok := sc.syncRes[task.resultKey()]; ok && result.Status == common.ResultCodeSynced`

This was because it seems to me that ResultCodeSynced is only set when the object is successfully applied in `applyObject`. I'm also pretty sure that the resource ops calls are blocking so it will only get that code if it was applied successfully and therefore should now be apart of the cluster.

After thinking about this again I'm not even sure if this check is needed because if it's running then it was probably applied or exists already. Not really sure WDYT?

Comment (agaudreault) [reply gitops-engine/pkg/sync/sync_context.go]: Correct. If the task is running, it was executed (sync/apply).

Comment (agaudreault) [reply gitops-engine/pkg/sync/sync_context.go]: So calling setResourceResult to Failed if the live object does not exist would be correct. No need for additional checks IMO.

Comment (cjcocokrisp) [reply gitops-engine/pkg/sync/sync_context.go]: Yeah I agree, plus if its not there even after an API call it probably does not exist. I removed the check.

**Review by agaudreault — APPROVED** [review]
LGTM
