### PR TITLE
fix: KubeVersion passed to helm template is incorrectly

### LINKED ISSUE #22606: Application helm spec  kubeVersion incorrectly passed to helm template
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I work with IBM IKS clusters and cluster version looks like `X.Y.Z+IKS`. Using it as value for `kubeVersion` in Application manifest renders Invalid Semantic Version error. It looks like Argo parses it to `X.Y.ZIKS` and that triggers Helm error.

**To Reproduce**

Use `kubeVersion: 1.30.11+IKS`

**Expected behavior**

Helm template will use value exactly as provided:

```
helm template --kube-version X.Y.Z+IKS ...
```

**Version**

```shell
argocd-server: v2.13.2+dc43124
  BuildDate: 2024-12-11T18:37:15Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**

```
ComparisonError
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template logs-agent --namespace ibm-observe --kube-version 1.30.11IKS --values /tmp/04d153a1-7052-45ee-9f77-170a62c1f385 <api versions removed> --include-crds` failed exit status 1: Error: invalid kube version '1.30.11IKS': Invalid Semantic Version
3 minutes ago (Tue Apr 08 2025 12:31:13 GMT+0200)
```

### PR DESCRIPTION
**Pull request by sivchari**
close #22606 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by nitishfy — COMMENTED** [review]
I tested your changes just now. I get the same error for a version such as `1.30.1+xyz` - 
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): failed to execute helm template command: failed to get command args to log: `helm template . --name-template helm-webapp --namespace helm --kube-version 1.30.1_xyz --values <path to cached source>/helm-webapp/values-prod.yaml <api versions removed> --include-crds` failed exit status 1: Error: invalid kube version '1.30.1_xyz': Invalid Semantic Version
```

Maybe this is happening because the kube version of target cluster is not actually `1.30.1_xyz`. 

Secondly, with the current changes, we will be removing the kube-version support for GKE that was introduced in [this PR](https://github.com/argoproj/argo-cd/issues/2303). I'd like to know other maintainers thoughts on this PR before moving forward.

**Comment by sivchari** [comment]
Hi, @nitishfy ! Thank you for investigating about this issue.

How interesting! You can know that helm can receive the kube-version as a 1.30.1+xyz by seeing the log of test I added new one. Helm would replace `+` with `_`, so does this specification results in it ? I'd investigate. Thanks.

> Secondly, with the current changes, we will be removing the kube-version support for GKE that was introduced in this PR. I'd like to know other maintainers thoughts on this PR before moving forward.

I totally agree with your thoughts since this change surely break the compatibility. The essence that we found the problem is current API definition accept various semantic version such as vX.Y.Z+x.y.z. We might have to discuss about rule what version is acceptable and what one isn't acceptable.

File: util/helm/helm_test.go [hunk 1]
```diff
@@ -219,6 +219,29 @@ func TestAPIVersions(t *testing.T) {
 	assert.Equal(t, "sample/v2", objs[0].GetAPIVersion())
 }
 
+func TestIssue22606(t *testing.T) {
```
Comment (nitishfy) [inline util/helm/helm_test.go:222]:
```suggestion
func TestIssue22606(t *testing.T) {
```

please add a better name for this test.

Comment (leoluz) [reply util/helm/helm_test.go:222]: Agree with @nitishfy. Maybe add a more descriptive name for the function and add the link to the issue as a comment.

Comment (sivchari) [reply util/helm/helm_test.go:222]: Thanks you both, I renamed it.

**Comment by sivchari** [comment]
I'll discuss the backward compatibly on original issue later 👍

**Comment by nitishfy** [comment]
let's bring this issue in this week's meeting.

**Comment by FourFifthsCode** [comment]
@sivchari @nitishfy 
It seems like it might be a good idea to remove `text.Semver` function from all three places (Helm, Kustomize, and Plugins) and make a clean break for version 3.0.  

Then add documentation that:
1) we'll no longer remove `+` from Kube versions, which may break deployments for APIs which don't have valid semvers
2) we'll no longer remove `+` from Kube versions, which may change Helm output, depending on how charts handle the Kube version variable

Then for version `2.14`, we could modify `text.Semver` to only remove the `+` when there is no trailing characters, which is what caused the original issue.

**Comment by sivchari** [comment]
@FourFifthsCode @nitishfy @leoluz 
Sorry for absenting the meeting.
Does this mean creating a pr for each of v3 and v2.14?
And where is the proper documentation for these modifications?

**Comment by nitishfy** [comment]
> @FourFifthsCode @nitishfy @leoluz Sorry for absenting the meeting. Does this mean creating a pr for each of v3 and v2.14? And where is the proper documentation for these modifications?

I think we'd be required to do cherry-picking. 

cc @FourFifthsCode

**Comment by crenshaw-dev** [comment]
@FourFifthsCode is suggesting we make two different changes, one for master/v3.0 and the other for v2.14.

The master/v3.0 change would remove the `+` logic entirely, noting the change in release notes. We could merge that PR to master and then cherry-pick to release-3.0.

The 2.14 change would just alter the logic to remove only trailing `+` characters instead of all `+` characters. We'd make that change with a PR directly against the release-2.14 branch.

Personally I'd be satisfied with just the first change, since 3.0 goes GA early next week.

**Comment by crenshaw-dev** [comment]
Note that `text.SemVer` is invoked in 3 different places. We'd want to remove all 3 invocations, since they all could cause the same bug.

**Comment by sivchari** [comment]
I deleted text.Semver from the repo in this commit. That commits for v3.
I don't think it's good way to do cherry-pick to v2.14.X since it's breaking changes for users using Argo v2.14.X

**Comment by crenshaw-dev** [comment]
Code lgtm! Can you add a page to the 2.14-3.0.md file documenting the change?

**Comment by crenshaw-dev** [comment]
Yep, it's a breaking change. Here's the place to document it: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/2.14-3.0.md

**Comment by sivchari** [comment]
Thanks! I added the section about this change.

**Comment by crenshaw-dev** [comment]
@sivchari apologies that we weren't able to get this into 3.0! Could you rebase update the docs to indicate that the change will happen in 3.1?

File: docs/operator-manual/upgrading/3.0-3.1.md [hunk 2]
```diff
@@ -5,3 +5,17 @@
 The `--staticassets` directory in the API server (`/app/shared` by default) is now protected against out-of-bounds 
 symlinks. This is to help protect against symlink attacks. If you have any symlinks in your `--staticassets` directory
 to a location outside the directory, they will return a 500 error starting with 3.1.
+
+## Breaking Changes
+
+### Kube versions
+
+Until v3.0, Argo CD removed `+` identifier from `kubeVersions` in Helm, Kustomize and Plugins. For example, if Argo CD receive `kubeVersions` as vX.Y.Z+, we convert to vX.Y.Z internally. After v3.0, the internal conversation is entirely removed.
```
Comment (crenshaw-dev) [inline docs/operator-manual/upgrading/3.0-3.1.md]:
```suggestion
Until v3.0, Argo CD removed `+` identifier from `kubeVersions` in Helm, Kustomize and Plugins. For example, if Argo CD receive `kubeVersions` as vX.Y.Z+, we convert to vX.Y.Z internally. Starting with v3.1, the internal conversation is entirely removed.
```

File: docs/operator-manual/upgrading/3.0-3.1.md [hunk 3]
```diff
@@ -5,3 +5,17 @@
...
+
+#### Detection
+
+To detect if you are affected, check the `kubeVersions` you'are using. If you use `kubeVersions` including `+` identifier, the application must be failed when you upgrade from v3.0 to v3.1.
```
Comment (crenshaw-dev) [inline docs/operator-manual/upgrading/3.0-3.1.md]:
```suggestion
To detect if you are affected, check the `kubeVersions` you are using. If you use `kubeVersions` including `+` identifier, the application must be failed when you upgrade from v3.0 to v3.1.
```

File: docs/operator-manual/upgrading/3.0-3.1.md [hunk 4]
```diff
@@ -5,3 +5,17 @@
...
+
+#### Remediation
+
+This problem is that Argo CD removes no longer `+` identifier from `kubeVersions. Your application has already used `kubeVersions` triming `+` identifier, so it just works correctlly by removing `+` identifier.
```
Comment (crenshaw-dev) [inline docs/operator-manual/upgrading/3.0-3.1.md]:
```suggestion
The plus symbol was originally removed [because Helm did not support it](https://github.com/argoproj/argo-cd/issues/2303). Helm no longer enforces this restriction, so apps should work fine even if your kubeVersions include `+`.

However, since Argo CD now sends unmodified kubeVersions to Helm, the generated manifests may differ due to the changed kubeVersions. For apps which require extra caution, it may be advisable to disable auto-sync, upgrade, check any diffs, and then reenable auto-sync.
```

**Review by crenshaw-dev — APPROVED** [review]
