### PR TITLE
fix(state): fix(controller): display correct SyncWave for hook resources #26208

### LINKED ISSUE #26208: UI displays incorrect Sync Wave for resources annotated as Sync hooks
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

---

## Describe the bug

The Argo CD Web UI displays an incorrect **Sync Wave** for resources annotated as
**Sync hooks**.

When a Kubernetes resource (for example a `Job`) is annotated with:

- `argocd.argoproj.io/hook: Sync`
- and a non-zero `argocd.argoproj.io/sync-wave`

the resource is always shown in the UI with **Sync Wave = 0**, even though a different
wave is explicitly configured.

Internally, Argo CD *does respect the configured sync-wave* when executing the sync,
but the Web UI does not reflect the effective wave ordering for hook resources.

This results in misleading information when inspecting the application state.

---

## To Reproduce

1. Create an Argo CD Application with multiple resources using sync waves.
2. Example setup:
   - A database resource (e.g. CNPG Cluster) with:
     ```yaml
     metadata:
       annotations:
         argocd.argoproj.io/sync-wave: "1"
     ```
   - A migration Job annotated as a Sync hook:
     ```yaml
     metadata:
       annotations:
         argocd.argoproj.io/hook: Sync
         argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
         argocd.argoproj.io/sync-wave: "2"
     ```
3. Trigger a sync of the application.
4. Open the Application view in the Argo CD Web UI and inspect the resource list.

---

## Expected behavior

The Argo CD Web UI should display the **configured sync-wave value (e.g. 2)** for hook
resources, or otherwise clearly indicate the **effective execution order** of the hook
within the Sync phase.

At minimum, the UI should not display `Wave = 0` when a different wave is explicitly
configured and honored by the sync engine.

---
## Actual behavior

- The Sync hook resource is displayed with: 
  ```
  Sync Wave: 0
  Hook: Sync
  ```
- This occurs even when `argocd.argoproj.io/sync-wave` is set to a non-zero value.
- Despite the UI display, the hook is executed **after lower waves have completed and
become Healthy**, indicating that the wave is respected internally.

---

## Why this is a problem

- The UI representation contradicts the actual sync execution order.
- This makes debugging ordering issues difficult, especially for workflows involving:
- database provisioning
- schema migrations
- ordered application bootstrapping
- Users may incorrectly assume that the hook runs in wave 0 and before dependent
resources.

---

## Screenshots

Image

---

## Version

```
v3.1.11+cc053b2
```

### PR DESCRIPTION
**Pull request by linghaoSu**
## Summary

This PR fixes an issue where the Argo CD UI displays `SyncWave: 0` for resources annotated as Sync hooks, even when those resources have a non-zero `argocd.argoproj.io/sync-wave` annotation.

test data https://github.com/linghaoSu/argocd-example-apps/blob/test/sync-wave-hooks/manifests.yaml

Fixes #26208

**Before**
image

**After**
image

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: controller/state.go [hunk 1]
```diff
@@ -896,6 +889,13 @@ func (m *appStateManager) CompareAppState(app *v1alpha1.Application, project *v1
 		}
 		if targetObj != nil {
 			resState.SyncWave = int64(syncwaves.Wave(targetObj))
+		} else if isHook(obj) {
```
Comment (olivergondza) [inline controller/state.go]: Extract the `isHook(obj)`, it is called few lines above.

**Review by olivergondza — CHANGES_REQUESTED** [review]
Thanks for the fix. Verified locally that it resolved the problem.

**Review by olivergondza — APPROVED** [review]

File: controller/state.go (hunk 1 above)
Comment (linghaoSu) [reply controller/state.go]: Thanks for the review! Fixed.

**Review by blakepettersson — APPROVED** [review]
