### PR TITLE
fix: Only show `apiVersion/kind` when `targetState` is defined

### LINKED ISSUE #16643: `undefined/undefined` is wrong...
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

the details for a not found resource reflected `undefined/undefined:`
```
Resource not found in cluster: undefined/undefined:cert-manager-startupapicheck
```
**To Reproduce**

1. let argocd manage a cert-manager install
2. let argocd upgrade cert-manager install
3. while argocd is triggering the cert-manager upgrade, a service account for `cert-manager-startupapicheck` will appear and can be clicked (?)
4. click it
5. depending on (hand waving) the `cert-manager-startupapicheck` will probably already be gone? so a confusing error will be rendered by argocd

note that for a while longer i could ask argocd to filter for service accounts and see it, but i couldn't click it to actually show the item... and it eventually stopped appearing...

**Expected behavior**

information about expect objects should be stored in the request pointer so that they can be filled in in cases when they no longer exist instead of asking the ui to imagine them after the fact

**Screenshots**

image

**Version**

```shell
{
    "Version": "v2.8.3+77556d9",
    "BuildDate": "2023-09-07T16:05:43Z",
    "GitCommit": "77556d9e64304c27c718bb0794676713628e435e",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by jsoref**
- Fixes #16643

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: ui/src/app/applications/components/application-node-info/application-node-info.tsx [hunk 1]
```diff
@@ -270,7 +270,10 @@ export const ApplicationNodeInfo = (props: {
                                 ) : (
                                     <div className='application-node-info__err_msg'>
                                         Resource not found in cluster:{' '}
-                                        {`${props?.controlled?.state?.targetState?.apiVersion}/${props?.controlled?.state?.targetState?.kind}:${props.node.name}`}
+                                        {typeof props?.controlled?.state?.targetState !== 'undefined' && (
+                                            <span>{`${props?.controlled?.state?.targetState?.apiVersion}/${props?.controlled?.state?.targetState?.kind}:`}</span>
+                                        )}
```
Comment (chansuke) [inline ui/src/app/applications/components/application-node-info/application-node-info.tsx:275]:
```suggestion
                                        {typeof props?.controlled?.state?.targetState !== 'undefined' && (
                                            <span>{`${props.controlled.state.targetState.apiVersion}/${props.controlled.state.targetState.kind}:`}</span>
                                        )}
```

imo: no need optional chain since we already checked that targetState is not undefined in condition

**Review by nitishfy — APPROVED** [review]

**Review by blakepettersson — APPROVED** [review]

**Comment by blakepettersson** [comment]
@jsoref do you want this backported to some version(s)?

**Comment by jsoref** [comment]
That'd be nice. We haven't managed to upgrade to the new world...
