### PR TITLE
Issue #1414 - Load target resource using K8S if conversion fails

### LINKED ISSUE #1414: ComparisonError while try to deploy k8s resource kind: APIService
testet with vesion v0.12.0

**Describe the bug**
CompareError while try to deploy k8s resource kind: APIService

**To Reproduce**
Deploy Application with source directory. 

in this directory i have this file:
```yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    app: metrics-server
    chart: metrics-server
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```

when argo try to deploy this resource
i go the following error from UI
```
ComparisonError
error: unable to decode "/dev/shm/063309308": no kind "APIService" is registered for version "apiregistration.k8s.io/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29"
```

in my repo-server-log i find this
```
time="2019-04-09T12:04:55Z" level=warning msg="Failed to remarshal oject: no kind \"APIService\" is registered for version \"apiregistration.k8s.io/v1beta1\" in sch
eme \"k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28\""
```

**Expected behavior**
This kind should be able to deploy

### PR DESCRIPTION
**Pull request by alexmt**
Closes #1414 

Implements changes described at https://github.com/argoproj/argo-cd/issues/1414#issuecomment-486724028

### CODE REVIEW

File: controller/metrics/transportwrapper.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+func (mrt *metricsRoundTripper) RoundTrip(r *http.Request) (*http.Response, error) {
+	resp, err := mrt.roundTripper.RoundTrip(r)
+	if resp != nil {
+		mrt.metricsServer.IncKubernetesRequest(mrt.app, resp.StatusCode)
+	}
+	return resp, err
+}
+
+func WrapConfig(server *MetricsServer, app *v1alpha1.Application, config *rest.Config) *rest.Config {
```
Comment (alexec) [inline controller/metrics/transportwrapper.go]: I feel like this name is wrong.

File: controller/metrics/metrics.go [hunk 2]
```diff
@@ -17,6 +18,7 @@ import (
 type MetricsServer struct {
 	*http.Server
 	syncCounter        *prometheus.CounterVec
+	k8sRequestCounter  *prometheus.CounterVec
```
Comment (alexec) [inline controller/metrics/metrics.go]: Is this a new counter that shows the number of requests? Minor: could be a separate PR.

File: controller/metrics/transportwrapper.go [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+type metricsRoundTripper struct {
+	roundTripper  http.RoundTripper
+	app           *v1alpha1.Application
+	metricsServer *MetricsServer
+}
+
+func (mrt *metricsRoundTripper) RoundTrip(r *http.Request) (*http.Response, error) {
+	resp, err := mrt.roundTripper.RoundTrip(r)
+	if resp != nil {
+		mrt.metricsServer.IncKubernetesRequest(mrt.app, resp.StatusCode)
```
Comment (alexec) [inline controller/metrics/transportwrapper.go]: Are we ignoring request failures here?

File: controller/metrics/transportwrapper.go (hunk 1 above)
Comment (alexmt) [reply controller/metrics/transportwrapper.go]: Renamed to `AddMetricsTransportWrapper`

File: controller/metrics/metrics.go (hunk 2 above)
Comment (alexmt) [reply controller/metrics/metrics.go]: Right. This is a counter which reports number of kubernetes api requests per application. Ideally, all information should be available in cache and counter should be zero. 

If for some reason cache don't have required information (e.g. application has resource which we cannot convert and have to load from k8s) then it will be easy to understand which app is causing performance degradation.

File: controller/metrics/transportwrapper.go (hunk 3 above)
Comment (alexmt) [reply controller/metrics/transportwrapper.go]: We don't need to handle the error here just need to let it bubble up in stack. If something happened and k8s call failed without status code we still want to increment counter. Changed the code to use status code '0' to indicate that we attempted the k8s request and did not get any response code.

**Review by alexec — APPROVED** [review]
