### PR TITLE
fix: add fatal timeout upgrade with SIGKILL to ARGO_EXEC_TIMEOUT (closes #20785, #18478)

### LINKED ISSUE #20785: Applications are stuck in refreshing
**Describe the bug**
I have 3000-5000 Applications, sometimes, Applications are stucking in refreshing, only restart application-controller or repo-server can solve it. About 2~3 times per day. Application is triggered to sync by gitlab webhook. 
I have :
- application-controller Deployment, and 1 replicas, and not use Dynamic Cluster Distribution.  app_reconcile_queue depth is large
- 5 repo-server, one repo-server replica have much goroutines, can restart it to solve the hang probelem
image
image

I have got  the repo-server goroutine profile, and like this
image

My ArgoCD version is 2.12.4

my some config
```yaml
  controller.operation.processors: "100"
  controller.repo.server.timeout.seconds: "120"
  controller.status.processors: "300"
  reposerver.git.attempts.count: "5"
  reposerver.parallelism.limit: "30"
  server.grpc.max.size.mb: "200"
  server.k8sclient.retry.base.backoff: "200"
  server.webhook.parallelism.limit: "50"`

**Expected behavior**

Application not stuck in refreshing

**Version**
v2.12.4 tag and with this commit https://github.com/argoproj/argo-cd/commit/95be90b5f9f5acebca46e3dcc3df9355307f6285

```shell
Paste the output from `argocd version` here.
```

**Logs**
Application Controller is Comparing app state, and can not get generated manifests from repo-server

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by hazel-sudz**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

Closes #20785 #18478. Based on what multiple people have reported it appears as though calls to git may sometimes deadlock and not respect SIGTERM. The root cause of this is not currently known. Based on reports it seems to be happen when git remote is really slow/flaky. If cmds do not respect SIGTERM the expected behavior should be to upgrade to SIGKILL after a given additional timeout interval. Otherwise, the entire argocd repo-server will stall which is an objectively worse outcome. 

# New Documentation
image
image

docs build for PR: https://argo-cd--22713.org.readthedocs.build/en/22713/operator-manual/config-management-plugins/#using-a-config-management-plugin-with-an-application

### CODE REVIEW

File: util/exec/exec.go [hunk 1]
```diff
@@ -45,6 +46,10 @@ func initTimeout() {
 	if err != nil {
 		timeout = 90 * time.Second
 	}
+	fatalTimeout, err = time.ParseDuration(os.Getenv("ARGOCD_EXEC_FATAL_TIMEOUT"))
```
Comment (hazel-sudz) [inline util/exec/exec.go:49]: I don't think this is something that should be exposed to users but in a followup I think we should add metrics for when the fatal SIGKILL is sent. My guess is that the SIGTERM stall is either some kind of race-condition corruption in argo multithreading or an actual rare race condition in git itself but I don't have a good idea of what to debug without further understanding of the issue.

File: util/exec/exec_test.go [hunk 2]
```diff
@@ -73,8 +73,10 @@ func TestRunWithExecRunOptsFatal(t *testing.T) {
 			ShouldWait: true,
 		},
 	}
+	// The returned error string in this case should contain a "fatal" in this case
```
Comment (hazel-sudz) [inline util/exec/exec_test.go:76]: added test for new error flow case

File: util/exec/exec_test.go [hunk 3]
```diff
@@ -73,8 +73,10 @@ func TestRunWithExecRunOptsFatal(t *testing.T) {
...
 	_, err := RunWithExecRunOpts(exec.Command("sh", "-c", "trap 'trap - 15 && echo captured && sleep 10000' 15 && sleep 2"), opts)
-	assert.ErrorContains(t, err, "failed timeout after 200ms")
+	// The expected timeout is ARGOCD_EXEC_TIMEOUT + ARGOCD_EXEC_FATAL_TIMEOUT = 200ms + 100ms = 300ms
```
Comment (hazel-sudz) [inline util/exec/exec_test.go:78]: maybe ARGOCD_EXEC_FATAL_TIMEOUT is a little bit confusing naming since this is timeout in addition too ARGOCD_EXEC_TIMEOUT. open to suggestions on a better name here

File: util/exec/exec.go [hunk 4]
```diff
@@ -228,10 +228,26 @@ func RunCommandExt(cmd *exec.Cmd, opts CmdOpts) (string, error) {
...
+			select {
+			case <-done:
+			case <-fatalTimeoutCh:
+				// upgrades to SIGKILL if cmd does not respect SIGTERM
+				_ = cmd.Process.Signal(fatalTimeoutBehaviour)
+				output := stdout.String()
+				if opts.CaptureStderr {
+					output += stderr.String()
+				}
+				logCtx.WithFields(logrus.Fields{"duration": time.Since(start)}).Debug(redactor(output))
```
Comment (hazel-sudz) [inline util/exec/exec.go:244]: some overlap here with the logic below but with different error code. I'm open to refactoring the exit to a new function if this is desired but also fine leaving it as is since it's not too bad

**Comment by hazel-sudz** [comment]
hey @crenshaw-dev lmk what you need from me to help get this merged. I think all the core logic and tests are there. thanks

**Review by todaywasawesome — COMMENTED** [review]
I think we should add docs to how how to change the default fataltimeout and this will be ready to go.

**Comment by hazel-sudz** [comment]
@todaywasawesome added docs and linked screenshots and PR diff of the documentation changes. lmk if there's anything else you need. thanks!

File: docs/operator-manual/config-management-plugins.md [hunk 5]
```diff
@@ -327,6 +327,8 @@ If you don't need to set any environment variables, you can set an empty plugin
     and let the automatic discovery to identify the plugin.
 !!! note
     If a CMP renders blank manfiests, and `prune` is set to `true`, Argo CD will automatically remove resources. CMP plugin authors should ensure errors are part of the exit code. Commonly something like `kustomize build . | cat` won't pass errors because of the pipe. Consider setting `set -o pipefail` so anything piped will pass errors on failure.
+!!! note
+    Although this should never happen, if a CMP command fails to gracefully exit on `ARGOCD_EXEC_TIMEOUT`, it will be forcefully killed after an additional timeout of `ARGOCD_EXEC_FATAL_TIMEOUT`. This is an implementation detail that should generally not concern end users.
```
Comment (todaywasawesome) [inline docs/operator-manual/config-management-plugins.md:331]:
```suggestion
    If a CMP command fails to gracefully exit on `ARGOCD_EXEC_TIMEOUT`, it will be forcefully killed after an additional timeout of `ARGOCD_EXEC_FATAL_TIMEOUT`. 
```

I don't think we need so much commentary there. Here people are making CMPs so they're buying their own problems.

**Review by todaywasawesome — COMMENTED** [review]
One last suggestion, looks great. Good work.

File: docs/operator-manual/config-management-plugins.md (hunk 5 above)
Comment (hazel-sudz) [reply docs/operator-manual/config-management-plugins.md]: thanks no worries pushed on the last commit https://github.com/argoproj/argo-cd/pull/22713/commits/a615cf49fc8485c4b8077b2c5d76dcb0fabdb0b7

Comment (hazel-sudz) [reply docs/operator-manual/config-management-plugins.md]: updated PR body with a new link to the docs @todaywasawesome

**Review by ishitasequeira — APPROVED** [review]
Thanks @hazel-sudz for the PR. LGTM! @todaywasawesome do you have any open concerns?

**Comment by prathameshnyt** [comment]
Thank you @hazel-sudz @crenshaw-dev for this fix. Are you planning to get it release in version `2.x`?
