### PR TITLE
fix: Allow plugins to lock repository at top-level to prevent git races

### LINKED ISSUE #6174: Plugin argocd for git-crypt
Version : 
- Argocd 1.8.7
- Argocd 2.0.1

Hello,

In our argocd config repo, we are using git-crypt with gpg keys to crypt our secrets. That means that we are using argocd plugin to unlock the repo , so argocd can read the crypted files. We have one gpg key for argocd.

Here is the config in configmap :

```
  configManagementPlugins: |    
    - name: encrypted-yaml    
      init:    
        command: ["sh", "-c"]    
        args: ["export GNUPGHOME=/home/argocd/.gnupg; export HOME=/home/argocd; eval $(gpg-agent --daemon); gpg --import /home/argo/argo.key; git crypt unlock"]                                                                               
      generate:    
        command: ["sh", "-c"]    
        args: ["find . -name '*.yaml' -exec cat {} \\;"]    
    - name: bootstrap-argo-projects    
      generate:    
        command: ["sh", "-c"]    
        args: ["find operation -name '*.yaml' -exec cat {} \\+ && find application -name 'argo.yaml' -exec cat {} \\+"]    
    - name: recursive-argo-bootstrap    
      generate:    
        command: ["sh", "-c"]    
        args: ["find . -name 'argo.yaml' -exec cat {} \\+"]    
    - name: recursive-project-deploy    
      generate:    
        command: ["sh", "-c"]    
        args: ["find . -name '*.yaml' -a ! -name 'argo.yaml' -exec cat {} \\+"]    
    - name: recursive-encrypted-project-deploy    
      init:    
        command: ["sh", "-c"]    
        args: ["export GNUPGHOME=/home/argocd/.gnupg; export HOME=/home/argocd; eval $(gpg-agent --daemon); gpg --import /home/argo/argo.key; git crypt unlock"]    
      generate:    
        command: ["sh", "-c"]    
````

It worked well when we were in version 1.7.X and below.

Now we have that kind of error

```
ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): `sh -c export GNUPGHOME=/home/argocd/.gnupg; export HOME=/home/argocd; eval $(gpg-agent --daemon); gpg --import /home/argo/argo.key; git crypt unlock` failed exit status 1: gpg-agent: a gpg-agent is already running - not starting a new one gpg: key xxxx: "ArgoCD xxx<team@xxx.com>" not changed gpg: key xxx : secret key imported gpg: Total number processed: 1 gpg: unchanged: 1 gpg: secret keys read: 1 gpg: secret keys unchanged: 1 fatal: Unable to create '/tmp/http:__myrepo_url_scm_oc_projects/.git/index.lock': File exists. Another git process seems to be running in this repository, e.g. an editor opened by 'git commit'. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repository earlier: remove the file manually to continue. Error: 'git checkout' failed git-crypt has been set up but existing encrypted files have not been decrypted
```

Do you have any idea why this is happening in version > 1.8.7 & 2.0.1 ?

Any workaround ?

Thx
Regards

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #6174

This PR introduces a new plugin configuration option, `lockRepo: <bool>`:

```
configManagementPlugins: |
  - name: some-plugin
    init: ...
    generate: ...
    lockRepo: <true|false> # defaults to false
```

Custom plugins may make use of `git` for certain operations (e.g. `git crypt`), which requires an exclusive lock on the Git repository. 

The current locking mechanism for plugins lock on the application path within the repository, which may not be sufficient if two applications using a plugin that executes `git` on the same repository, but on different paths.

As a follow-up, we should modify our `KeyLock` interface at https://github.com/argoproj/pkg/blob/master/sync/key_lock.go to also consider locks on path-based matching, instead of exact matches. E.g. if a lock exist on `/tmp/foo/bar`, a request on a lock for `/tmp/foo/bar/baz` should wait until the previous lock is released.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by jgwest — APPROVED** [review]
Looks good! Since https://github.com/argoproj/argo-cd/pull/4625 merged, reasoning about the concurrency implications of this particular area of the codebase is fairly time consuming :thinking: .

While you're at it, can you add this comment to the `var manifestGenerateLock = sync.NewKeyLock()` line?
```go
// When multiple threads are accessing a Git repository (checked out in the local container,
// eg under '/tmp/(...)') at the the same time, the existing 'Service.repoLock' lock should
// prevent those threads from clobbering each other's files with different revisions (for non-Helm).
//
// However, some manifest generation utilities (helm, custom config management plugins) might still
// write to this repository path during execution of that utility. Thus we need a way to ALSO
// prevent multiple threads from running manifest generation at the same time against the
// same Git repository path. Note: for non-Helm, this will only happen when the two threads are 
// both using the same Git revision at the same time (differing revisions is covered by repoLock).
//
// That is the purpose of manifestGenerateLock: this lock should be acquired if a manifest
// generation utility might cause files to be written to the checked out Git repository
// path, and thus multiple threads should not run this utility at the same time.
var manifestGenerateLock = sync.NewKeyLock()
```

This is my understanding of the purpose of this lock, after reading through the code in the context of reviewing the PR.

**Review by kshamajain99 — APPROVED** [review]

File: reposerver/repository/repository.go [hunk 1]
```diff
@@ -1087,17 +1087,25 @@ func findPlugin(plugins []*v1alpha1.ConfigManagementPlugin, name string) *v1alph
...
+		return nil, fmt.Errorf("config management plugin with name '%s' is not supported", q.ApplicationSource.Plugin.Name)
 	}
+
+	// Plugins can request to lock the complete repository when they need to
+	// use git client operations.
+	if plugin.LockRepo {
+		manifestGenerateLock.Lock(repoRoot)
+		defer manifestGenerateLock.Unlock(repoRoot)
+	} else {
+		concurrencyAllowed := isConcurrencyAllowed(appPath)
```
Comment (alexmt) [inline reposerver/repository/repository.go:1102]: The `isConcurrencyAllowed` method already returns false for plugins. Unless I'm missing something plugins already lock repo. We probably need opposite setting  `allowConcurrency` for plugins

**Review by alexmt — CHANGES_REQUESTED** [review]

File: reposerver/repository/repository.go (hunk 1 above)
Comment (jannfis) [reply reposerver/repository/repository.go:1102]: As far as I could tell, it locks on the `appPath`, but we need to lock at the repository root to prevent concurrent `git` operations (i.e. a plugin calling `git` in the same repo, but on different paths).

Comment (jgwest) [reply reposerver/repository/repository.go:1102]: That [`isConcurrencyAllowed`](https://github.com/argoproj/argo-cd/blob/40629e5715c3726c0bf97902eab67501e22c79b2/reposerver/repository/repository.go#L511) method only checks for `.argocd-allow-concurrency`, which could exist for plugins,  unless I am missing something? I had assumed that the general point of the logic here was about forcing this method to lock even if that file was specified (if the plugin is configured with lockrepo).

**Review by alexmt — APPROVED** [review]
Sorry @jannfis . Forgot to click "Submit review" button.

LGTM

**Comment by PierreR** [comment]
@jessesuen what is the status ?

**Comment by Kronk74** [comment]
Hello,

I've got the same issue. @jessesuen Is is possible to review this PR ? :)

**Review by jessesuen — APPROVED** [review]

**Comment by jessesuen** [comment]
This should be good to go. @jannfis just needs to rebase and merge.
