### PR TITLE
fix: UI 6337 cluster filter improvement for issue #6337

### LINKED ISSUE #6337: filter bug: when cluster field is "bge-dev1", the applications with cluster "dev1" is selected
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
The argocd 2.0.2 has a bug on the filter function. We have two clusters, one is "dev1" and the other is "bge-dev1". However, the application with cluster "dev1" are selected when we using filter cluster "bge-dev1"

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**
When filtering apps with cluster, only the applications with that cluster name should be selected. 

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by ciiay**
Fixes #6337 
Signed-off-by: ciiay yicai@redhat.com

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by ciiay** [comment]
Hi @alexmt , I made the fix but with a little difference from what we came up from our last discussion. Here's the detailed note for the change. Let me know what do you think. Thank you!

As the autocomplete component uses “includes” logic to fetch suggestion list, it’s already doing fuzzy search to fetch possible matching clusters for any filter input. For example, the below suggestion list will be autocompleted in dropdown options when user inputs “dev”, “d”, “.com” and so on.
“dev (https://123.com)”
“dev-1 (https://456.com)”

When user clicks on one of the listed options, the selected cluster is fixed, which means either Cluster Name or Cluster URL, or both must exactly match the app spec base on which value or values are specified when app is added. For example, if the user specifies Cluster Name only when a new app is added, Cluster URL would be undefined when filter with Cluster.

Based on the above research result, the fix will be updating comparison logic to “===“ on both Cluster Name and Cluster URL with OR condition.
Screen Shot 2021-07-28 at 4 54 21 PM

**Comment by ciiay** [comment]
Update:
As now we Allow filters in input that are not listed in suggestions #6788, I added logic to do Fuzzy search of Cluster Name and Exact search of Cluster URL for random input.

File: ui/src/app/applications/components/applications-list/applications-filter.tsx [hunk 1]
```diff
@@ -33,9 +33,17 @@ export function getFilterResults(applications: Application[], pref: AppsListPref
             clusters:
                 pref.clustersFilter.length === 0 ||
                 pref.clustersFilter.some(
-                    selector =>
-                        (app.spec.destination.server && selector.includes(app.spec.destination.server)) ||
-                        (app.spec.destination.name && selector.includes(app.spec.destination.name))
+                    filterString =>
```
Comment (alexmt) [inline ui/src/app/applications/components/applications-list/applications-filter.tsx:36]: I agree with idea @ciiay, thank you!

Just want to propose slightly different implementation:

```typescript
pref.clustersFilter.some(filterString => {
    const match = filterString.match('^.* [(](http.*)[)]$');
    if (match?.length === 2) {
        const [, url] = match;
        return url === app.spec.destination.server;
    } else {
        return app.spec.destination.name && minimatch(app.spec.destination.name, filterString);
    }
}),
```

It is pretty much the same but it extracts URL using regex and uses `minimatch` so that user could choose between exact and fuzzy much for cluster name

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
LGTM!
