### PR TITLE
fix: Event timestamp incorrectly shows unix epoch (#7879)

### LINKED ISSUE #7879: Scheduled ... First occurred is unix epoch
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The `Scheduled` event is effectively rendering a 0 timestamp

**To Reproduce**

1. Have a pod w/ >~250 events
2. open events
3. check the first event

**Expected behavior**

don't render 0 epoch

**Screenshots**

image
image

**Version**

```shell
{
    "Version": "v2.2.0+78e256e",
    "BuildDate": "2021-12-03T22:39:09Z",
    "GitCommit": "78e256eef3dc5fdb8553e58c024d234d8e354e20",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

Fixes https://github.com/argoproj/argo-cd/issues/7879

The issue is that the firstTimestamp and lastTimestamp can be null.  See above issue for screenshots with the fix.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: ui/src/app/shared/components/events-list/events-list.tsx [hunk 1]
```diff
@@ -31,12 +40,30 @@ export const EventsList = (props: {events: models.Event[]}) => {
                                 <div className='columns small-4 xxlarge-5'>{event.message}</div>
                                 <div className='columns small-2 xxlarge-1'>{event.count}</div>
                                 <div className='columns small-2 xxlarge-2'>
-                                    <div className='events-list__event__ago'>{ago(new Date(event.firstTimestamp))}</div>
-                                    <div className='events-list__event__time'>{readableFormat(new Date(event.firstTimestamp))}</div>
+                                    {event.firstTimestamp ? (
+                                        <>
+                                            <div className='events-list__event__ago'>{ago(new Date(event.firstTimestamp))}</div>
+                                            <div className='events-list__event__time'>{readableFormat(new Date(event.firstTimestamp))}</div>
```
Comment (jsoref) [inline ui/src/app/shared/components/events-list/events-list.tsx:46]: I know this is preexisting code, but the idea of calling `new Date(x)` .. `new Date(x)` instead of `date_x=new Date(x)` .. `date_x` .. `date_x` bothers me.

Comment (keithchong) [reply ui/src/app/shared/components/events-list/events-list.tsx]: Hi @jsoref , that's fair.  Please have a look again.

**Review by jsoref — APPROVED** [review]
I like this

**Review by alexmt — APPROVED** [review]
Thank you!
