### PR TITLE
fix: correct mismatch in typescript repository model (#25273)

### LINKED ISSUE #25273: GitHub App Auth repositories incorrectly updatable in the GUI
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

HTTP/HTTPS git repositories in the GUI may be updated. Git repositories using GitHub App Auth are not supposed to be updatable, but a bug in the GUI permits this.

Worse still, should you save a change, the `githubAppID` and `githubAppInstallationID` get set to `0` and the `githubAppPrivateKey` becomes an empty string.

**To Reproduce**

A repository with GitHub App Auth needs to exist first, then in the GUI:

Settings -> Repositories -> click on the repository -> edit panel slides in

**Expected behavior**

The repository is not clickable, and therefore does not present the edit panel

**Screenshots**

This edit panel should not appear when clicking GitHub App Auth repositories
Image

**Version**

This happens on the current master branch, the most recent release is v3.2.0

### PR DESCRIPTION
**Pull request by allanyung**
Fixes #25273

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Title of the PR](https://argo-cd.readthedocs.io/en/latest/developer-guide/submit-your-pr/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: ui/src/app/shared/models.ts [hunk 1]
```diff
@@ -633,7 +633,7 @@ export interface Repository {
     noProxy?: string;
     insecure?: boolean;
     enableLfs?: boolean;
-    githubAppId?: string;
+    githubAppID?: number;
```
Comment (choejwoo) [inline ui/src/app/shared/models.ts]: Thank you for creating the PR.
I have a couple of questions, The `Repository` interface is used in other places as well. Would it still be okay to change the type from `string` to `number`?
Also, is there a specific reason you renamed `githubAppId` to `githubAppID`?

File: ui/src/app/settings/components/repos-list/repos-list.tsx [hunk 2]
```diff
@@ -308,7 +308,7 @@ export const ReposList = ({match, location}: RouteComponentProps) => {
 
     // only connections of git type which is not via GitHub App are updatable
     const isRepoUpdatable = (repo: models.Repository) => {
-        return isHTTPOrHTTPSUrl(repo.repo) && repo.type === 'git' && !repo.githubAppId;
+        return isHTTPOrHTTPSUrl(repo.repo) && repo.type === 'git' && !repo.githubAppID;
```
Comment (choejwoo) [inline ui/src/app/settings/components/repos-list/repos-list.tsx:311]: If changing the type from `string` to `number` could affect other parts of the logic, wouldn’t it be better to handle the conversion inside that function instead?

**Review by choejwoo — CHANGES_REQUESTED** [review]

File: ui/src/app/settings/components/repos-list/repos-list.tsx (hunk 2 above)
Comment (allanyung) [reply ui/src/app/settings/components/repos-list/repos-list.tsx:311]: I retested without changing the type and the fix still works so I've removed the change in the interest of playing it safe

File: ui/src/app/shared/models.ts (hunk 1 above)
Comment (allanyung) [reply ui/src/app/shared/models.ts]: My IDE indicated that this field is only used in one place, I've removed the type change so hopefully this is acceptable now.

The repo object that comes back actually uses uppercase for `ID` in the githubApp keys. I think this is because it is rendered into the K8s Secret with keys: `githubAppID` and `githubAppInstallationID`

```json
{
    "repo": "REDACTED",
    "connectionState": {
        "status": "Successful",
        "message": "",
        "attemptedAt": "2025-11-15T09:09:23Z"
    },
    "type": "git",
    "githubAppID": 1111111,
    "githubAppInstallationID": 2222222
}
```

To clarify, the `!repo.githubAppId` check in `repos-list.tsx` would always return true as there was never a `githubAppId` key in the repo object, as shown above

Comment (choejwoo) [reply ui/src/app/shared/models.ts]: I see. My IDE also shows that this field is only used in one place.
I understand the issue now. LGTM!

**Review by choejwoo — APPROVED** [review]

**Review by blakepettersson — APPROVED** [review]

**Comment by blakepettersson** [comment]
IMO the `Repository` type should also have its field renamed to githubAppID to be consistent with its serialization in json/protobuf, but that can be done in another PR. Thanks!
