### PR TITLE
fix: make test fails with exec format error

### LINKED ISSUE #21562: cannot execute binary file: Exec format error
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**After running `make install-tools-local`, upon running `make-test`, I get the error: `/go/src/github.com/argoproj/argo-cd/dist/gotestsum: cannot execute binary file: Exec format error`. But I didn't find any other make target that creates those binaries for a virtualized chain, so if I delete the binaries under `dist` folder, `make test` complains that `gotestsum` does not exist**

**To Reproduce**

This may be an issue only for Mac or for some other specific setup that I have, but it should reproduce upon:
`make install-tools-local` and then `make test`

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by reggie-k**
Closes #21562

test Dockerfile is now installing `gotestsum` similarly to how it installs `kustomize`.
For local chain, the binary from `dist` will be used.
For virtualized chain, the binary from `/usr/local/bin` will be used, similarly to how `kustomize` is used.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by nitishfy — COMMENTED** [review]
can you fix the failing tests?

File: hack/installers/install-gotestsum.sh [hunk 1]
```diff
@@ -21,6 +21,6 @@ url=https://github.com/gotestyourself/gotestsum/releases/download/v${gotestsum_v
 
 mkdir -p /tmp/gotestsum-${gotestsum_version}
 tar -xvzf ${temp_path} -C /tmp/gotestsum-${gotestsum_version}
-cp /tmp/gotestsum-${gotestsum_version}/gotestsum ${DIST_PATH}/gotestsum
-chmod +x ${DIST_PATH}/gotestsum
+sudo cp /tmp/gotestsum-${gotestsum_version}/gotestsum ${INSTALL_PATH}/gotestsum
+chmod +x ${INSTALL_PATH}/gotestsum
```
Comment (rumstead) [inline hack/installers/install-gotestsum.sh:25]: This may require a sudo because `$BIN` is set to `/usr/local/bin`

**Review by rumstead — APPROVED** [review]
One minor comment but otherwise LGTM

```
user@cdf9d54eb56b:/go/src/github.com/argoproj/argo-cd$ which gotestsum
/usr/local/bin/gotestsum
```

File: hack/installers/install-gotestsum.sh (hunk 1 above)
Comment (reggie-k) [reply hack/installers/install-gotestsum.sh]: Thanks for the catch! Added sudo before changing permissions as well.

**Review by nitishfy — APPROVED** [review]

**Review by rumstead — APPROVED** [review]

**Review by ishitasequeira — APPROVED** [review]
