### PR TITLE
Fix for displaying hooks in app diff view. Fixes #2215

### LINKED ISSUE #2215: Application summary diff page shows hooks
**Describe the bug**
The application summary diff tab shows hooks.

**To Reproduce**
1. Create and sync an application which has hook
2. See application is in sync. Click on app details and choose diff tab
3. See hook manifest

**Expected behavior**
Hooks should be hidden

**Version**

```shell
v1.2.0-rc2
```

### PR DESCRIPTION
**Pull request by alexec**
Fixes #2215

### CODE REVIEW

File: ui/src/app/applications/components/application-resources-diff/application-resources-diff.tsx [hunk 1]
```diff
@@ -33,10 +33,13 @@ export const ApplicationResourcesDiff = (props: ApplicationResourcesDiffProps) =
                 return {
                     a: live ? jsYaml.safeDump(live, {indent: 2}) : '',
                     b: target ? jsYaml.safeDump(target, {indent: 2}) : '',
+                    hook: state.liveState.metadata.annotations['argocd.argoproj.io/hook'],
```
Comment (alexec) [inline ui/src/app/applications/components/application-resources-diff/application-resources-diff.tsx]: I'm aware that this will not deal with Helm, but it'll do for now, and Helm can be fixed in #1865.

**Comment by alexec** [comment]
Should back-port to v1.2

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
