### PR TITLE
Fail app sync if `prune` flag is required

### LINKED ISSUE #273: `argocd app sync` should fail if `prune` flag is required
The `argocd app sync` command deletes unexpected sources only if flag `prune` is set. In such case application stays unsynced, so `argocd app sync` should fail (return none 0 return code.)

### PR DESCRIPTION
**Pull request by merenbach**
Closes #273

### CODE REVIEW

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -74,11 +74,21 @@ type SyncOperationResult struct {
 	Resources []*ResourceDetails `json:"resources" protobuf:"bytes,1,opt,name=resources"`
 }
 
+type ResourceSyncStatus int
+
+const (
+	ResourceDetailsSynced          ResourceSyncStatus = iota
```
Comment (alexmt) [inline pkg/apis/application/v1alpha1/types.go]: Please use string for consistency with other enumerations

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
LGTM
