### PR TITLE
fix: argocd-dex now merges existing dex.config.oauth2 block instead of overwriting

### LINKED ISSUE #7275: Argo CD's dex integration overwrites a custom dex.config.oauth2 yaml block
**Describe the bug**

When

**To Reproduce**

Deploy Argo CD with the following data for the `argo-cm` ConfigMap

```yaml
apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: |
    oauth2:
      passwordConnector: ldap  # I want this enabled in dex to leverage the password grant type against LDAP
    connectors:
      - type: ldap
        name: LDAP
        id: ldap
        config:
          host: myldap.company.com
          usernamePrompt: Username
          userSearch:
            baseDN: "cn=users,dc=example,dc=com"
            username: uid
            idAttr: uid
            emailAttr: uid
            nameAttr: uid
          groupSearch:
            baseDN: "cn=groups,dc=freeipa,dc=example,dc=com"
            nameAttr: cn
  url: https://argocd.company.com/
kind: ConfigMap
```

When I examine generated dex config in the argocd-dex-server pod I find this

```yaml
# /shared/dex.yaml 
connectors:
- config:
    groupSearch:
      baseDN: cn=groups,dc=freeipa,dc=example,dc=com
      nameAttr: cn
    host: myldap.company.com
    userSearch:
      baseDN: cn=users,dc=example,dc=com
      emailAttr: uid
      idAttr: uid
      nameAttr: uid
      username: uid
    usernamePrompt: Username
  id: ldap
  name: LDAP
  type: ldap
grpc:
  addr: 0.0.0.0:5557
issuer: https://argocd.company.com//api/dex
oauth2:
  skipApprovalScreen: true  # passwordConnector was removed
staticClients:
- id: argo-cd
  name: Argo CD
  redirectURIs:
  - https://argocd.company.com/auth/callback
  secret: "<SOME SECRET VALUE HERE>"
- id: argo-cd-cli
  name: Argo CD CLI
  public: true
  redirectURIs:
  - http://localhost
  - http://localhost:8085/auth/callback
storage:
  type: memory
telemetry:
  http: 0.0.0.0:5558
web:
  http: 0.0.0.0:5556

```

I expected to see 

```yaml
oauth2:
   passwordConnector: ldap
   skipApprovalScreen: true
```
but instead I got:

```yaml
oauth2:
  skipApprovalScreen: true
```

**Expected behavior**

I want to be able to generate an oauth token with dex using the password grant-type when integrating with LDAP.  Therefore, when I pass in the following yaml to the argocd-cm ConfMap

```yaml
apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: |
    oauth2:
      passwordConnector: ldap
      # Rest of the config....
```
argocd-dex will take that configuration into account when generating the dex configuration file.

**Version**

```shell
argocd: v2.1.2+7af9dfb
  BuildDate: 2021-09-02T18:05:23Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64```

### PR DESCRIPTION
**Pull request by jphelton**
Fixes #7275 

Signed-off-by: Joshua Helton <jdoghelton@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

File: util/dex/config.go [hunk 1]
```diff
@@ -35,8 +35,17 @@ func GenerateDexConfigYAML(settings *settings.ArgoCDSettings) ([]byte, error) {
...
+	if ok {
+		_ , ok := oauth2Cfg["skipApprovalScreen"].(bool)
+		if !ok {
+			oauth2Cfg["skipApprovalScreen"] = true
+		}
+	}else {
+		dexCfg["oauth2"] = map[string]interface{}{
+			"skipApprovalScreen": true,
+		}
 	}
```
Comment (wtam2018) [inline util/dex/config.go:50]: It looks good.  I would slightly simplify it.
`	if oauth2Cfg, found := dexCfg["oauth2"].(map[string]interface{}); found {
		if _, found := oauth2Cfg["skipApprovalScreen"].(bool); !found {
			oauth2Cfg["skipApprovalScreen"] = true
		}
	} else {
		dexCfg["oauth2"] = map[string]interface{}{
			"skipApprovalScreen": true,
		}
	}`

Comment (jphelton) [reply util/dex/config.go:48]: Thanks for the advice.  I'm new to Go and not used to variable declaration inside of an if-statement.

**Review by wtam2018 — APPROVED** [review]
LGTM
Thanks @jphelton

**Review by alexmt — APPROVED** [review]
