### PR TITLE
fix(cli): Prevent Get & Sync from Hanging on Invalid Application Spec

### LINKED ISSUE #21613: `app sync --timeout x` and `app get --refresh` hangs forever if application spec is invalid
**Describe the bug**

When an existing Application has an invalid spec that cannot be reconciled anymore, the `argocd.argoproj.io/refresh: normal` annotations will not be removed by the controller. This causes the get command to never return. Since this get is used without context timeout in sync and get command, the command hangs forever.

**To Reproduce**

- Create a valid app
- ~~(fixed) Modify the app so it is invalid (remove the cluster, change permissions)~~
- Scale down application-controller to 0 replicas (simulate very long processing).
- perform `app sync --timeout 5`

```
> argocd app sync test-comparison-fails-if-in-cluster-disabled  --server localhost:8080 --auth-token x.y.z --insecure --timeout 5 --prune        
TIMESTAMP                  GROUP        KIND   NAMESPACE                                                                      NAME    STATUS   HEALTH        HOOK  MESSAGE
2025-01-21T15:22:44-05:00            Service  argocd-e2e--test-comparison-fails-if-in-cluster-disabled-mudys          guestbook-ui    Synced  Healthy              
2025-01-21T15:22:44-05:00   apps  Deployment  argocd-e2e--test-comparison-fails-if-in-cluster-disabled-mudys          guestbook-ui    Synced  Healthy              

This is the state of the app after `wait` timed out:
[HANGS HERE]
```

Or with `app get --refresh`
```
> argocd app get test-comparison-fails-if-in-cluster-disabled  --server localhost:8080 --auth-token x.y.z --insecure --refresh
[HANGS HERE]
```

The return condition for the get is never met: https://github.com/argoproj/argo-cd/blob/5ef4faa8a4ba5486ffde9cffc4ec4f60eedec1ec/server/application/application.go#L793-L808

**Expected behavior**

- (DONE) ~~The Controller should remove the refresh annotation when the reconciliation resulted in the application being invalid.~~
- Because refresh may hang, the CLI should have a timeout parameter on the get.
- The sync command should respect the timeout provided for the sync operation.

**Version**

```shell
3.0 / master
```

### PR DESCRIPTION
**Pull request by almoelda**
Closes https://github.com/argoproj/argo-cd/issues/21613

Adding context cancellation to get cmd and cancelling the context before printFinalStatus on sync command

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

File: cmd/argocd/commands/app.go [hunk 1]
```diff
@@ -2588,8 +2600,8 @@ func waitOnApplicationStatus(ctx context.Context, acdClient argocdclient.Client,
 				fmt.Println("This is the state of the app after `wait` timed out:")
 			}
 
-			printFinalStatus(app)
 			cancel()
+			printFinalStatus(app)
```
Comment (nitishfy) [inline cmd/argocd/commands/app.go:2604]:
```suggestion
			printFinalStatus(app)
```
why are you printing after the `cancel()` has been called?

File: cmd/argocd/commands/app.go [hunk 2]
```diff
@@ -382,17 +383,27 @@ func NewApplicationGetCommand(clientOpts *argocdclient.ClientOptions) *cobra.Com
...
+			defer func() {
+				argoio.Close(conn)
+				cancel()
+			}()
 
 			appName, appNs := argo.ParseFromQualifiedName(args[0], appNamespace)
 
+			if timeout != 0 {
+				time.AfterFunc(time.Duration(timeout)*time.Second, func() {
+					fmt.Println("Context cancelled due to timeout")
```
Comment (nitishfy) [inline cmd/argocd/commands/app.go:402]:
```suggestion
```
I don't think it's necessary.

File: cmd/argocd/commands/app.go [hunk 3]
```diff
@@ -337,6 +337,7 @@ func NewApplicationGetCommand(clientOpts *argocdclient.ClientOptions) *cobra.Com
 		refresh        bool
 		hardRefresh    bool
 		output         string
+		timeout        int
```
Comment (nitishfy) [inline cmd/argocd/commands/app.go:340]:
```suggestion
		timeout        uiint
```
This should be `uint`.

File: cmd/argocd/commands/app.go [hunk 4]
```diff
@@ -462,6 +473,7 @@ func NewApplicationGetCommand(clientOpts *argocdclient.ClientOptions) *cobra.Com
 		},
 	}
 	command.Flags().StringVarP(&output, "output", "o", "wide", "Output format. One of: json|yaml|wide|tree")
+	command.Flags().IntVar(&timeout, "timeout", 15, "Specifies the maximum duration for the operation to complete. The command will terminate if the timeout is exceeded.")
```
Comment (nitishfy) [inline cmd/argocd/commands/app.go:476]:
```suggestion
	command.Flags().UintVar(&timeout, "timeout", defaultCheckTimeoutSeconds, "Time out after this many seconds")
```

File: cmd/argocd/commands/app.go [hunk 5]
```diff
@@ -382,17 +383,27 @@ func NewApplicationGetCommand(clientOpts *argocdclient.ClientOptions) *cobra.Com
...
-			defer argoio.Close(conn)
+			defer func() {
+				argoio.Close(conn)
+				cancel()
+			}()
 
 			appName, appNs := argo.ParseFromQualifiedName(args[0], appNamespace)
 
+			if timeout != 0 {
+				time.AfterFunc(time.Duration(timeout)*time.Second, func() {
```
Comment (nitishfy) [inline cmd/argocd/commands/app.go:401]:
```suggestion
				time.AfterFunc(time.Duration(timeout) * time.Second, func() {
```
looks better.

**Review by nitishfy — CHANGES_REQUESTED** [review]
Works perfectly.  I've left a few comments before we merge this PR. The changes work well for the sync command too even though you only added the `timeout` flag to the get command. I wonder how and why?

**Comment by almoelda** [comment]
Thanks @nitishfy 
I've committed the suggested changes
Regarding sync command, it already has a timeout flag propagated into `waitOnApplicationStatus`, see below

https://github.com/argoproj/argo-cd/blob/8449bab9ec461620911509e535610878de6e805f/cmd/argocd/commands/app.go#L2588

File: cmd/argocd/commands/app.go (hunk 1 above)
Comment (almoelda) [reply cmd/argocd/commands/app.go]: Good point, thanks

**Comment by nitishfy** [comment]
> Thanks @nitishfy I've committed the suggested changes Regarding sync command, it already has a timeout flag propagated into `waitOnApplicationStatus`, see below
> 
> https://github.com/argoproj/argo-cd/blob/8449bab9ec461620911509e535610878de6e805f/cmd/argocd/commands/app.go#L2588

why can't you call the waitOnApplicationStatus() in the get command too like the way we are calling for `argocd app wait` command?

File: cmd/argocd/commands/app.go (hunk 1 above)
Comment (nitishfy) [reply cmd/argocd/commands/app.go]: This is correct otherwise the ctx never gets called in the Get function. It is better to give a cancellation signal when the timeout has occured.

File: cmd/argocd/commands/app.go [hunk 6]
```diff
@@ -382,17 +383,26 @@ func NewApplicationGetCommand(clientOpts *argocdclient.ClientOptions) *cobra.Com
...
+					cancel()
+				})
+			}
```
Comment (nitishfy) [inline cmd/argocd/commands/app.go:404]:
```suggestion
                   app, _, err := waitOnApplicationStatus(ctx, acdClient, appName, uint(timeout), watchOpts{operation: true}, nil, output)
                   errors.CheckError(err)
```

You don't need all of this. Instead call the `waitOnApplicationStatus` before making the first GET call.

**Review by nitishfy — CHANGES_REQUESTED** [review]
PTAL now.

File: cmd/argocd/commands/app.go (hunk 6 above)
Comment (almoelda) [reply cmd/argocd/commands/app.go:404]: Yeah sounds good. I wanted to ask about `hardRefresh` since waitOnApplicationStatus only do a normal refresh 
please correct me if got it wrong

Comment (almoelda) [reply cmd/argocd/commands/app.go:404]: I guess (correct me if i'm wrong) if we proceed with `waitOnApplicationStatus` we would have to flag an `hardRefresh` somehow. maybe a context key-value or adding a parameter causing us to adjust all callers to this function. let me know what do you think and i'll get on it.

File: cmd/argocd/commands/app.go [hunk 7]
```diff
@@ -382,17 +383,26 @@ func NewApplicationGetCommand(clientOpts *argocdclient.ClientOptions) *cobra.Com
   		`),
 
 		Run: func(c *cobra.Command, args []string) {
-			ctx := c.Context()
+			ctx, cancel := context.WithCancel(c.Context())
```
[the remark this answers is not in the document]
Comment (nitishfy) [reply cmd/argocd/commands/app.go:386]: I don't think we need to change the ctx here anymore if we use the `waitOnApplicationStatus` func.

[the remark this answers is not in the document]
Comment (almoelda) [reply cmd/argocd/commands/app.go:386]: Generally I agree with you @nitishfy invoking the the wait function looks like the best way
But it will not utilize the hardRefresh

https://github.com/argoproj/argo-cd/pull/21702#discussion_r1934568251

File: cmd/argocd/commands/app.go [hunk 8]
```diff
@@ -382,17 +383,26 @@ func NewApplicationGetCommand(clientOpts *argocdclient.ClientOptions) *cobra.Com
...
 				c.HelpFunc()(c, args)
 				os.Exit(1)
 			}
 			acdClient := headless.NewClientOrDie(clientOpts, c)
 			conn, appIf := acdClient.NewApplicationClientOrDie()
-			defer argoio.Close(conn)
+			defer func() {
+				argoio.Close(conn)
+				cancel()
+			}()
```
Comment (agaudreault) [inline cmd/argocd/commands/app.go:396]: defer separately.
```suggestion
			defer argoio.Close(conn)
```

File: cmd/argocd/commands/app.go (hunk 7 above)
Comment (agaudreault) [inline cmd/argocd/commands/app.go:386]: immediately call `defer cancel()`

**Review by agaudreault — CHANGES_REQUESTED** [review]

File: cmd/argocd/commands/app.go [hunk 9]
```diff
@@ -382,17 +383,26 @@ func NewApplicationGetCommand(clientOpts *argocdclient.ClientOptions) *cobra.Com
...
 
 			appName, appNs := argo.ParseFromQualifiedName(args[0], appNamespace)
 
+			if timeout != 0 {
+				time.AfterFunc(time.Duration(timeout)*time.Second, func() {
+					cancel()
```
Comment (agaudreault) [inline cmd/argocd/commands/app.go:402]: I think the logic of a `app get --refresh --timeout 10` should be to try to get with the refresh for 10 sec, and after 10 second, print a message, then fallback to the normal get and return that.

Comment (almoelda) [reply cmd/argocd/commands/app.go:401]: i've pushed the changes

File: cmd/argocd/commands/app.go (hunk 7 above)
Comment (almoelda) [reply cmd/argocd/commands/app.go:387]: done

**Review by nitishfy — CHANGES_REQUESTED** [review]
I tested your changes today, the sync command hangs if the timeout flag is not provided.

```
> argocd app sync guestbook            
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2025-02-03T19:58:31+05:30   apps  Deployment   guestbook          guestbook-ui    Synced  Healthy              
2025-02-03T19:58:31+05:30            Service   guestbook          guestbook-ui    Synced  Healthy              
[HANG]
```

**Comment by nitishfy** [comment]
> Please correct me if I'm wrong but the default is 0 Do you think we should change the default? @nitishfy

The default should not be changed. I think this is happening because we are not closing the [event channels here](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/app.go#L2624) due to which we never exit the for loop and CLI hangs.

**Comment by almoelda** [comment]
> > Please correct me if I'm wrong but the default is 0 Do you think we should change the default? @nitishfy
> 
> 
> 
> The default should not be changed. I think this is happening because we are not closing the [event channels here](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/app.go#L2624) due to which we never exit the for loop and CLI hangs.

I understand. So in your opinion, what should we do?

If timeout is provided, it is now respected. The context will be cancelled after x seconds.

If not provided, should we exit? How long should we wait before we exit?

**Comment by nitishfy** [comment]
> > > Please correct me if I'm wrong but the default is 0 Do you think we should change the default? @nitishfy
> > 
> > 
> > The default should not be changed. I think this is happening because we are not closing the [event channels here](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/app.go#L2624) due to which we never exit the for loop and CLI hangs.
> 
> I understand. So in your opinion, what should we do?
> 
> If timeout is provided, it is now respected. The context will be cancelled after x seconds.
> 
> If not provided, should we exit? How long should we wait before we exit?

you shouldn't exit. Instead find a way to close the channels so you don't get stuck in loop.

File: cmd/argocd/commands/app.go [hunk 10]
```diff
@@ -393,13 +396,49 @@ func NewApplicationGetCommand(clientOpts *argocdclient.ClientOptions) *cobra.Com
...
 			appName, appNs := argo.ParseFromQualifiedName(args[0], appNamespace)
 
-			app, err := appIf.Get(ctx, &application.ApplicationQuery{
-				Name:         &appName,
-				Refresh:      getRefreshType(refresh, hardRefresh),
-				AppNamespace: &appNs,
-			})
+			if timeout != 0 {
+				time.AfterFunc(time.Duration(timeout)*time.Second, func() {
+					cancel()
```
Comment (andrii-korotkov-verkada) [inline cmd/argocd/commands/app.go:401]: I think you don't wanna cancel twice, so need to check if wasn't cancelled already.

File: cmd/argocd/commands/app.go [hunk 11]
```diff
@@ -2512,18 +2552,47 @@ func resourceParentChild(ctx context.Context, acdClient argocdclient.Client, app
 
 const waitFormatString = "%s\t%5s\t%10s\t%10s\t%20s\t%8s\t%7s\t%10s\t%s\n"
 
+// AppWithLock encapsulates the application and its lock
+type AppWithLock struct {
+	mu  sync.RWMutex
```
Comment (andrii-korotkov-verkada) [inline cmd/argocd/commands/app.go:2557]: RWMutex may be less efficient than a regular mutex, unless it's some specific case. What does justify using it here? I'm asking since I've once tried to replace regular with rw and got a regression.

**Review by andrii-korotkov-verkada — CHANGES_REQUESTED** [review]

File: cmd/argocd/commands/app.go (hunk 10 above)
Comment (almoelda) [reply cmd/argocd/commands/app.go]: Agreed. done

File: cmd/argocd/commands/app.go (hunk 11 above)
Comment (almoelda) [reply cmd/argocd/commands/app.go]: > RWMutex may be less efficient than a regular mutex
I agree. actually nothing justifies it here, switched it back to Mutex. Thanks

File: cmd/argocd/commands/app.go [hunk 12]
```diff
@@ -2518,18 +2563,47 @@ func resourceParentChild(ctx context.Context, acdClient argocdclient.Client, app
...
 	defer cancel()
 
+	appWithLock := NewAppWithLock()
 	// refresh controls whether or not we refresh the app before printing the final status.
 	// We only want to do this when an operation is in progress, since operations are the only
 	// time when the sync status lags behind when an operation completes
 	refresh := false
 
+	// AppURL is declared here so that it can be used in the printFinalStatus function when the context is cancelled
+	AppURL := appURL(ctx, acdClient, appName)
```
Comment (agaudreault) [inline cmd/argocd/commands/app.go:2605]:
```suggestion
	appURL := getAppURL(ctx, acdClient, appName)
```

**Review by agaudreault — APPROVED** [review]
LGTM. 

I made the edit to rename the variable in Github UI. Hopefully all unit tests are passing and this is auto-merged.
