### PR TITLE
fix: issue with project scoped resources

### LINKED ISSUE #8041: Permission denied when adding a project scoped repository
Hello!

I've upgraded to ArgoCD v2.2.1, but I'm unable to use the new feature.

I expected this to work if I add policies to the AppProject manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocdtest
  namespace: openshift-gitops
spec:
  description: argocdtest
  destinations:
    - namespace: argocdtest
      server: 'https://kubernetes.default.svc'
  roles:
    - description: Admin privileges
      groups:
        - argocdtest_admin_group
      name: admin
      policies:
        - 'p, proj:argocdtest:admin, applications, *, argocdtest/*, allow'
        - 'p, proj:argocdtest:admin, repositories, create, argocdtest/*, allow'
        - 'p, proj:argocdtest:admin, repositories, delete, argocdtest/*, allow'
        - 'p, proj:argocdtest:admin, repositories, update, argocdtest/*, allow'
  sourceRepos:
    - '*'
```

but it doesn't (used web UI to connect repo):

```
time="2021-12-28T02:32:17Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied: repositories, create, argocdtest/https://myrepo.git, sub: CiQ3MjE1NDI0YS1iNjUyLTQ2MjctOGE5MC00NmU2OTFjMzBhNjUSCW9wZW5zaGlmdA, iat: 2021-12-28T02:16:05Z" grpc.code=PermissionDenied grpc.method=Create grpc.service=repository.RepositoryService grpc.start_time="2021-12-28T02:32:17Z" grpc.time_ms=1.043 span.kind=server system=grpc
time="2021-12-28T02:35:40Z" level=info msg="Alloc=18878 TotalAlloc=25684654 Sys=75729 NumGC=3244 Goroutines=243"
time="2021-12-28T02:45:40Z" level=info msg="Alloc=18584 TotalAlloc=25717725 Sys=75729 NumGC=3249 Goroutines=243"
```

Here is my argocd-rbac-cm (tried to add policies related to project scoped repositories there as well):

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-rbac-cm
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, proj:argocdtest:admin, repositories, create, argocdtest/*, allow
    p, proj:argocdtest:admin, repositories, delete, argocdtest/*, allow
    p, proj:argocdtest:admin, repositories, update, argocdtest/*, allow
    g, my_oidc_admin_group, role:admin
  policy.default: 'role:readonly'
  scopes: '[groups]'
```

Normally I use more restricted default policy, but I kept the default readonly policy for the test.
If there are no permissions to `get` repositories  in the default policy, the statement like

```
p, proj:argocdtest:admin, repositories, get, argocdtest/*, allow
```

will not actually allow to use already connected repositories as well.

What am I doing wrong?

### PR DESCRIPTION
**Pull request by pasha-codefresh**
Closes #8041

### CODE REVIEW

File: pkg/apis/application/v1alpha1/types.go [hunk 1]
```diff
@@ -1578,7 +1578,7 @@ func validatePolicy(proj string, role string, policy string) error {
 	}
 	// resource
 	resource := strings.Trim(policyComponents[2], " ")
-	if resource != "applications" {
+	if resource != "applications" && resource != "repositories" && resource != "clusters" {
 		return status.Errorf(codes.InvalidArgument, "invalid policy rule '%s': project resource must be: 'applications', not '%s'", policy, resource)
```
Comment (alexmt) [inline pkg/apis/application/v1alpha1/types.go:1582]: Please update error message as well:
```suggestion
		return status.Errorf(codes.InvalidArgument, "invalid policy rule '%s': project resource must be: 'applications', 'repositories' or 'clusters', not '%s'", policy, resource)
```

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you! Minor nitpick in comment

**Review by alexmt — APPROVED** [review]
LGTM
