### PR TITLE
fix(server): Send Azure DevOps token via git extra headers (#23478)

### LINKED ISSUE #23478: Unable to use workload identity for AzureDevops repository
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of `argocd version`.

**Describe the bug**

Unable to use workload identity for AzureDevops repository.  
Any attempt to use workload identity instead of PAT  produce the same error , no matter if project specified or not , tried different versions from 3.0.0 to 3.0.9. 
However on Repositories list page - connection status is  Successful and target revision dropdown list successfully shows existing branches , that means network connectivity and access to AzureDevops project works fine.

**To Reproduce**
- add pod label for server and repo-server  - azure.workload.identity/use: "true"
- add annotation for repo-server service account azure.workload.identity/client-id: "some client id"
- managed identity has Basic access level on AzureDevop and Reader permissions on Project
- connect repository via HTTP , type git , with empty project field , selected `Use Azure Workload Identity`
- try to change target revision on existing application

**Expected behavior**

Authentication to AzureDevops worked with workload identity

**Screenshots**

**Version**

```shell
argocd: v3.0.9+a1faf02
  BuildDate: 2025-06-17T20:46:21Z
  GitCommit: a1faf0265f5256f0b09e045f8486421359e3211f
  GitTreeState: clean
  GoVersion: go1.24.4
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
 rpc error: code = Unknown desc = failed to initialize repository resources: rpc error: code = Internal desc = Failed to fetch default: git fetch origin --tags --force --prune failed exit status 128: fatal: Authentication failed for 'https://dev.azure.com/*/
```
```
time="2025-06-18T15:07:12Z" level=info msg="git cat-file -t e76e6f130067894f44e9115649dedf53a6a0d48d" dir=/tmp/_argocd-repo/f69373aa-bcd4-404f-9f91-4083c995d9ad execID=cea5d
time="2025-06-18T15:07:12Z" level=info msg=Trace args="[git cat-file -t e76e6f130067894f44e9115649dedf53a6a0d48d]" dir=/tmp/_argocd-repo/f69373aa-bcd4-404f-9f91-4083c995d9ad operation_name="exec git" time_ms=2.216312
time="2025-06-18T15:07:12Z" level=info msg="git fetch origin --tags --force --prune" dir=/tmp/_argocd-repo/f69373aa-bcd4-404f-9f91-4083c995d9ad execID=235d0
time="2025-06-18T15:07:12Z" level=error msg="`git fetch origin --tags --force --prune` failed exit status 128: fatal: Authentication failed for 'https://dev.azure.com/*/'" execID=235d0
time="2025-06-18T15:07:12Z" level=info msg=Trace args="[git fetch origin --tags --force --prune]" dir=/tmp/_argocd-repo/f69373aa-bcd4-404f-9f91-4083c995d9ad operation_name="exec git" time_ms=234.175592
time="2025-06-18T15:07:12Z" level=error msg="finished call" grpc.code=Unknown grpc.component=server grpc.error="failed to initialize repository resources: rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune` failed exit status 128: fatal: Authentication failed for 'https://dev.azure.com/*/'" grpc.method=GenerateManifest grpc.method_type=unary grpc.service=repository.RepoServerService grpc.start_time="2025-06-18T15:07:12Z" grpc.time_ms=289.937 peer.address="10.48.11.3:33406" protocol=grpc
time="2025-06-18T15:07:13Z" level=info msg="started call" grpc.component=server grpc.method=Check grpc.method_type=unary grpc.service=grpc.health.v1.Health grpc.start_time="2025-06-18T15:07:13Z" grpc.time_ms=0.01 peer.address="[::1]:33396" protocol=grpc
```

### PR DESCRIPTION
**Pull request by mikebordon**
The project's "Git Askpass" implementation only supports username-password authentication, but Azure DevOps specifically requires the token be provided via an Authorization-Bearer request header. This change replaces the "store" approach required by the former in favor of the environment variable mechanism currently leveraged for HTTPS credentials when a bearer token is provided.

Fixes #23478 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by agaudreault** [comment]
@jagpreetstamber do you mind validating this issue/pr?

File: util/git/creds.go [hunk 1]
```diff
@@ -708,13 +706,10 @@ func (creds AzureWorkloadIdentityCreds) Environ() (io.Closer, []string, error) {
...
 	}
-	nonce := creds.store.Add("", token)
-	env := creds.store.Environ(nonce)
 
-	return utilio.NewCloser(func() error {
-		creds.store.Remove(nonce)
-		return nil
-	}), env, nil
+	var env []string
+	env = append(env, fmt.Sprintf("%s=Authorization: Bearer %s", bearerAuthHeaderEnv, token))
```
Comment (agaudreault) [inline util/git/creds.go:713]: I don't see a reason to remove the credsStore. Perhaps the only change necessary is to do an approach similar to HTTPSCreds? https://github.com/argoproj/argo-cd/blob/c60a727524b34699669d44eff6d851174f265c65/util/git/creds.go#L243-L246

**Review by agaudreault — CHANGES_REQUESTED** [review]

File: util/git/creds.go (hunk 1 above)
Comment (mikebordon) [reply util/git/creds.go:713]: Initially I had left it in there, but then I realized it ultimately becomes unused (because it doesn't work as-is). But I can definitely restore it if you'd prefer that.

**Comment by mikebordon** [comment]
Hi @agaudreault. Have you had a chance to review after the last push to incorporate your requested change? Please let me know if you have any other concerns which I can address.

**Review by rumstead — APPROVED** [review]

**Comment by mikebordon** [comment]
@agaudreault This PR is still blocked by your previous change for request. Could you please re-review when you have a chance (or clear your vote since @rumstead has now approved)?

**Review by agaudreault — APPROVED** [review]
