### PR TITLE
fix: editing Clusers in the UI drops credentials from the secret

### LINKED ISSUE #4405: Editing Clusers in the UI drops credentials from the secret
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have created a cluster definition at the command line. The definition includes an SA token. Like this:

```
ARGOCD_MANAGER_TOKEN="$(echo -e "$(oc sa get-token argocd-manager -n aicoe-argocd-dev)" | tr -d '[:space:]')"
CLUSTER_SPEC_CONFIG=$(echo -n "{\"bearerToken\":\"${ARGOCD_MANAGER_TOKEN}\",\"tlsClientConfig\":{\"insecure\":true}}" | base64 | tr -d '[:space:]')
oc patch secret dev-cluster-spec -n aicoe-argocd-dev --type='json' -p="[{'op': 'add', 'path': '/data/config', 'value':'${CLUSTER_SPEC_CONFIG}'}]"

# We also need to provide the cluster spec with the location of this server.
API_SERVER_ENCODED=$(echo -ne ${API_SERVER} | base64 | tr -d '[:space:]')
oc patch secret dev-cluster-spec -n aicoe-argocd-dev --type='json' -p="[{'op': 'add', 'path': '/data/server', 'value':'${API_SERVER_ENCODED}'}]"
```

Then editing the "Namespaces" field of the cluster in the UI causes the bearer token to be lost.

**To Reproduce**

1. create a cluster definition (above)
1. edit the cluster definition in the UI
1. observe things starting to fail due to missing access to the cluster for the argo SA

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

Changing the namespaces in the UI should not change other values.

**Screenshots**

### Editing in the UI:
a1-2020-09-23_12-04
a2-2020-09-23_12-04
a3-2020-09-23_12-07

### Value of the secret before and after editing the namespaces

a4-2020-09-23_12-08

## ArgoCD starts failing due to missing access to the cluster

a5-2020-09-23_12-13

**Version**

```shell
$ argocd version
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:44:27Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:45:44Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8

```

**Logs**

```
none relevant
```

### PR DESCRIPTION
**Pull request by alexmt**
Closes #4405 

PR allows UI to update selected cluster fields using update API.

### CODE REVIEW

File: test/testdata.go [hunk 1]
```diff
@@ -1,17 +1,21 @@
...
 
-	"github.com/argoproj/gitops-engine/pkg/utils/testing"
-
 	"github.com/argoproj/argo-cd/common"
 	apps "github.com/argoproj/argo-cd/pkg/client/clientset/versioned/fake"
 	appinformer "github.com/argoproj/argo-cd/pkg/client/informers/externalversions"
 	applister "github.com/argoproj/argo-cd/pkg/client/listers/application/v1alpha1"
+	servercache "github.com/argoproj/argo-cd/server/cache"
+	cacheutil "github.com/argoproj/argo-cd/util/cache"
+	appstatecache "github.com/argoproj/argo-cd/util/cache/appstate"
```
Comment (jannfis) [inline test/testdata.go:18]: I think these are responsible for the import cycle. Imho, the `NewServerInMemoryCache()` should be moved to `cluster_test.go`, as a non-exported function (or, in the long run, split up package `test` into more specific test fixture packages).

**Review by jannfis — CHANGES_REQUESTED** [review]

File: test/testdata.go (hunk 1 above)
Comment (alexmt) [reply test/testdata.go]: thank you! fixed.

**Review by jannfis — APPROVED** [review]
LGTM!
