### PR TITLE
fix: correct lookup for the kustomization file when applying patches

### LINKED ISSUE #21914: Adding patches to kustomize requires that the kustomization file have a `.yaml` extension
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Kustomize allows a [couple different file names](https://github.com/argoproj/argo-cd/blob/feb7097fc9808bd725b26d012bf04121e5c59995/util/kustomize/kustomize.go#L392) for the kustomization file. If the `patches` option is included in the kustomization section of an appset file the only allowed filename is `kustomization.yaml`, causing previously working deployments to break.

**To Reproduce**

1. Have a kustomization.yml file for a project pointed to by `argoproj.io/v1alpha1.Application` without a `patches` key under `spec.source.kustomize`.
2. Add a patch, the error you get is something akin to `code = Unknown desc = Manifest generation error (cached): failed to load kustomization.yaml`
3. Rename your `kustomization.yml` from item 1 to `kustomization.yaml`
4. Profit

**Expected behavior**

There should not be any required changes to the file name when introducing supported features.

**Screenshots**

**Version**

```shell
v2.11.5+c4b283c
```

**Logs**

```
Paste any relevant application logs here.
```

Here are the relevant files:

* https://github.com/argoproj/argo-cd/blob/feb7097fc9808bd725b26d012bf04121e5c59995/util/kustomize/kustomize.go#L259
* https://github.com/argoproj/argo-cd/blob/feb7097fc9808bd725b26d012bf04121e5c59995/util/kustomize/kustomize.go#L392

### PR DESCRIPTION
**Pull request by nitishfy**
Fixes https://github.com/argoproj/argo-cd/issues/21914

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by gdsoumya — CHANGES_REQUESTED** [review]

File: util/kustomize/kustomize.go [hunk 1]
```diff
@@ -72,7 +72,29 @@ type kustomize struct {
...
+	for _, kustomization := range KustomizationNames {
+		if path == kustomization {
+			return true
+		}
+	}
+	return false
+}
+
+// LookKustFile looks for any known kustomization file in the path
+func LookKustFile(dir string) string {
```
Comment (crenshaw-dev) [inline util/kustomize/kustomize.go:88]: Can these 3 things be private?

Comment (crenshaw-dev) [reply util/kustomize/kustomize.go:88]: Nevermind, I see that the first two were public. Can the new function be private? :-)

File: util/kustomize/kustomize.go [hunk 2]
```diff
@@ -72,7 +72,29 @@ type kustomize struct {
 	noProxy string
 }
 
-var _ Kustomize = &kustomize{}
+var KustomizationNames = []string{"kustomization.yaml", "kustomization.yml", "Kustomization"}
```
Comment (rumstead) [inline util/kustomize/kustomize.go:75]: Any reason to not use RecognizedKustomizationFileNames](https://github.com/kubernetes-sigs/kustomize/blob/447a60903cd142948443a6bd441b2749ad643815/api/konfig/general.go#L10)

Comment (crenshaw-dev) [reply util/kustomize/kustomize.go:75]: Would we have to import additional Kustomize Stuff?

Comment (rumstead) [reply util/kustomize/kustomize.go:75]: yea we only have an indirect dependency on `kustomize/api`

File: util/kustomize/kustomize.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (nitishfy) [reply util/kustomize/kustomize.go]: The name was inspired from [kustomize codebase](https://github.com/kubernetes-sigs/kustomize/blob/447a60903cd142948443a6bd441b2749ad643815/api/internal/target/kusttarget.go#L100) because we initially thought to use the exact function.

Nvm, I've changed the name.

Comment (nitishfy) [reply util/kustomize/kustomize.go]: changed.

File: util/kustomize/kustomize.go (hunk 2 above)
Comment (crenshaw-dev) [reply util/kustomize/kustomize.go:75]: Going from indirect to direct doesn't worry me too much... I don't feel strongly either way.

**Review by rumstead — APPROVED** [review]
LGTM

**Comment by nitishfy** [comment]
@crenshaw-dev Is the cherry pick bot working? If no, should I go ahead and raise cherry pick PRs?

**Review by gdsoumya — APPROVED** [review]
